// Copyright (c) 2001-2004 NovodeX AG. All rights reserved.
// Copyright (c) 2004-2008 AGEIA Technologies, Inc. All rights reserved.
// SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#ifndef PXG_BP_KERNEL_INDICES_H
#define PXG_BP_KERNEL_INDICES_H

namespace physx
{

struct PxgBPKernelBlockDim
{
	enum
	{
		BP_TRANSLATE_AABBS					= 256,
		BP_UPDATE_DELETEDPAIRS				= 256,
		BP_UPDATE_UPDATEDPAIRS				= 256,
		BP_UPDATE_UPDATEDPAIRS2				= 256,
		BP_UPDATE_CREATEDPAIRS				= 256,
	
		BP_INITIALIZE_SAPBOX				= 256,

		BP_COMPUTE_ENDPT_HISTOGRAM				= 256,
		BP_OUTPUT_ENDPT_HISTOGRAM				= 256,

		BP_CREATE_REGIONS						= 256,

		BP_COMPUTE_START_REGION_HISTOGRAM		= 256, 
		BP_OUTPUT_START_REGION_HISTOGRAM		= 256, 

		BP_COMPUTE_REGION_HISTOGRAM				= 256, 
		BP_OUTPUT_REGION_HISTOGRAM				= 256, 

		BP_WRITEOUT_ACTIVE_HISTOGRAM			= 256,
		BP_COMPUTE_ACTIVE_HISTOGRAM				= 512,
		BP_OUTPUT_ACTIVE_HISTOGRAM				= 256,

		BP_COMPUTE_OVERLAPCHECKS_HISTOGRAM		= 256,
		BP_OUTPUT_OVERLAPCHECKS_HISTOGRAM		= 256,

		BP_CLEAR_NEWFLAG						= 256,

		BP_INITIALIZE_RANKS						= 256,
		BP_UDPATE_HANDLES						= 256,
		BP_COMPUTE_INCREMENTAL_CMP_COUNTS1		= 256,
		BP_COMPUTE_INCREMENTAL_CMP_COUNTS2		= 256,
		BP_INCREMENTAL_SAP						= 256,
		BP_GENERATE_FOUNDPAIR_NEWBOUNDS			= 256,
		BP_WRITEOUT_OVERLAPCHECKS_HISTOGRAM_NEWBOUNDS =256,
		BP_COPY_REPORTS							= 256,

		BP_AGGREGATE_SORT						= 64,
		BP_AGGREGATE_REMOVE						= 1024
	};
};

struct PxgBPKernelGridDim
{
	enum
	{
//		BP_TRANSLATE_AABBS						= 64,	// PT: not used?
		BP_UPDATE_DELETEDPAIRS					= 32,
		BP_UPDATE_UPDATEDPAIRS					= 32,
		BP_UPDATE_UPDATEDPAIRS2					= 32,
		BP_UPDATE_CREATEDPAIRS					= 32,

//		BP_INITIALIZE_SAPBOX					= 64,	// PT: not used?

		BP_COMPUTE_ENDPT_HISTOGRAM				= 32,
		BP_OUTPUT_ENDPT_HISTOGRAM				= 32,

		BP_CREATE_REGIONS						= 32,

		BP_COMPUTE_START_REGION_HISTOGRAM		= 32, 
		BP_OUTPUT_START_REGION_HISTOGRAM		= 32, 

		BP_COMPUTE_REGION_HISTOGRAM				= 32, 
		BP_OUTPUT_REGION_HISTOGRAM				= 32, 

		BP_WRITEOUT_ACTIVE_HISTOGRAM			= 32,
		BP_COMPUTE_ACTIVE_HISTOGRAM				= 64,
		BP_OUTPUT_ACTIVE_HISTOGRAM				= 64,

		BP_COMPUTE_OVERLAPCHECKS_HISTOGRAM		= 32,
		BP_OUTPUT_OVERLAPCHECKS_HISTOGRAM		= 32,

		BP_CLEAR_NEWFLAG						= 32,

		BP_INITIALIZE_RANKS						= 64,
		BP_UDPATE_HANDLES						= 64,
		BP_COMPUTE_INCREMENTAL_CMP_COUNTS1		= 32,
		BP_COMPUTE_INCREMENTAL_CMP_COUNTS2		= 32,
		BP_INCREMENTAL_SAP						= 256,
		BP_GENERATE_FOUNDPAIR_NEWBOUNDS			= 64,
		BP_WRITEOUT_OVERLAPCHECKS_HISTOGRAM_NEWBOUNDS = 32,
		BP_COPY_REPORTS							= 64,

		BP_AGGREGATE_REMOVE						= 32
	};
};

}

#endif
