PxVehicleDirectDriveCommandResponseComponent Class Reference
PxVehicleDirectDriveCommandResponseComponent Class Reference abstract
Vehicle2
Forward the applicable set of control values for a direct drive vehicle to a command response state for each applicable control value.
#include <PxVehicleDrivetrainComponents.h>
Public Member Functions
PxVehicleDirectDriveCommandResponseComponent ()
virtual ~PxVehicleDirectDriveCommandResponseComponent ()
virtual void getDataForDirectDriveCommandResponseComponent (const PxVehicleAxleDescription *&axleDescription, PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > &brakeResponseParams, const PxVehicleDirectDriveThrottleCommandResponseParams *&throttleResponseParams, const PxVehicleSteerCommandResponseParams *&steerResponseParams, PxVehicleSizedArrayData< const PxVehicleAckermannParams > &ackermannParams, const PxVehicleCommandState *&commands, const PxVehicleDirectDriveTransmissionCommandState *&transmissionCommands, const PxVehicleRigidBodyState *&rigidBodyState, PxVehicleArrayData< PxReal > &brakeResponseStates, PxVehicleArrayData< PxReal > &throttleResponseStates, PxVehicleArrayData< PxReal > &steerResponseStates)=0
Provide vehicle data items for this component.
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Compute a per wheel response to the input brake/handbrake/throttle/steer commands and determine if there is an intention to accelerate the vehicle.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Detailed Description
Forward the applicable set of control values for a direct drive vehicle to a command response state for each applicable control value.
Note
The applicable control values are brake, handbrake, throttle and steer.
See also
PxVehicleDirectDriveActuationStateComponent
PxVehicleDirectDrivetrainComponent
PxVehicleBrakeCommandLinearUpdate
PxVehicleDirectDriveThrottleLinearCommandUpdate
PxVehicleSteerCommandLinearUpdate
PxVehicleAckermannSteerUpdate
Constructor & Destructor Documentation
PxVehicleDirectDriveCommandResponseComponent()
PxVehicleDirectDriveCommandResponseComponent::PxVehicleDirectDriveCommandResponseComponent () inline
~PxVehicleDirectDriveCommandResponseComponent()
virtual PxVehicleDirectDriveCommandResponseComponent::~PxVehicleDirectDriveCommandResponseComponent () inline virtual
Member Function Documentation
getDataForDirectDriveCommandResponseComponent()
virtual void PxVehicleDirectDriveCommandResponseComponent::getDataForDirectDriveCommandResponseComponent (const PxVehicleAxleDescription *& axleDescription, PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > & brakeResponseParams, const PxVehicleDirectDriveThrottleCommandResponseParams *& throttleResponseParams, const PxVehicleSteerCommandResponseParams *& steerResponseParams, PxVehicleSizedArrayData< const PxVehicleAckermannParams > & ackermannParams, const PxVehicleCommandState *& commands, const PxVehicleDirectDriveTransmissionCommandState *& transmissionCommands, const PxVehicleRigidBodyState *& rigidBodyState, PxVehicleArrayData< PxReal > & brakeResponseStates, PxVehicleArrayData< PxReal > & throttleResponseStates, PxVehicleArrayData< PxReal > & steerResponseStates) pure virtual
Provide vehicle data items for this component.
Parameters
[out] axleDescription identifies the wheels on each axle.
[out] brakeResponseParams An array of brake response parameters with a brake response for each brake command.
[out] throttleResponseParams The throttle response parameters.
[out] steerResponseParams The steer response parameters.
[out] ackermannParams The parameters defining Ackermann steering. NULL if no Ackermann steering is desired.
[out] commands The throttle, brake, steer etc. command states.
[out] transmissionCommands The transmission command state describing the current gear.
[out] rigidBodyState The state of the vehicle's rigid body.
[out] brakeResponseStates The resulting brake response states given the command input and brake response parameters.
[out] throttleResponseStates The resulting throttle response states given the command input and throttle response parameters.
[out] steerResponseStates The resulting steer response states given the command input, steer response and (optionally) Ackermann parameters.
update()
virtual bool PxVehicleDirectDriveCommandResponseComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Compute a per wheel response to the input brake/handbrake/throttle/steer commands and determine if there is an intention to accelerate the vehicle.
Implements PxVehicleComponent.
References PxVehicleCommandState::brakes, PxVehicleSimulationContext::frame, PxVehicleRigidBodyState::getLongitudinalSpeed(), PxVehicleCommandState::nbBrakes, PxVehicleAxleDescription::nbWheels, PX_PROFILE_ZONE, PX_UNUSED(), PxVehicleAckermannSteerUpdate(), PxVehicleBrakeCommandResponseUpdate(), PxVehicleDirectDriveThrottleCommandResponseUpdate(), PxVehicleSteerCommandResponseUpdate(), PxVehicleSizedArrayData< T >::size, PxVehicleCommandState::steer, PxVehicleCommandState::throttle, and PxVehicleAxleDescription::wheelIdsInAxleOrder.
The documentation for this class was generated from the following file:
PxVehicleDrivetrainComponents.h