physx::PxPoolBase< T, Alloc > Class Template Reference
physx::PxPoolBase< T, Alloc > Class Template Reference
#include <PxPool.h>
Classes
struct FreeList
Public Member Functions
~PxPoolBase ()
PX_INLINE T * allocate ()
PX_INLINE void deallocate (T *p)
PX_INLINE T * construct ()
template<class A1 >
PX_INLINE T * construct (A1 &a)
template<class A1 , class A2 >
PX_INLINE T * construct (A1 &a, A2 &b)
template<class A1 , class A2 , class A3 >
PX_INLINE T * construct (A1 &a, A2 &b, A3 &c)
template<class A1 , class A2 , class A3 >
PX_INLINE T * construct (A1 *a, A2 &b, A3 &c)
template<class A1 , class A2 , class A3 , class A4 >
PX_INLINE T * construct (A1 &a, A2 &b, A3 &c, A4 &d)
template<class A1 , class A2 , class A3 , class A4 , class A5 >
PX_INLINE T * construct (A1 &a, A2 &b, A3 &c, A4 &d, A5 &e)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 >
PX_INLINE T * construct (A1 &a, A2 &b, A3 &c, A4 &d, A5 &e, A6 &f)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 >
PX_INLINE T * construct (A1 &a, A2 &b, A3 &c, A4 &d, A5 &e, A6 &f, A7 &g)
template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 >
PX_INLINE T * construct (A1 &a, A2 &b, A3 &c, A4 &d, A5 &e, A6 &f, A7 &g, A8 &h)
PX_INLINE void destroy (T *const p)
Public Member Functions inherited from PxUserAllocated
PX_INLINE void * operator new (size_t, void *address)
PX_INLINE void operator delete (void *, void *)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete (void *ptr, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete [] (void *ptr, Alloc alloc, const char *fileName, int line)
PX_INLINE void operator delete (void *ptr)
PX_INLINE void operator delete [] (void *ptr)
Protected Member Functions
PxPoolBase (const Alloc &alloc, uint32_t elementsPerSlab, uint32_t slabSize)
void push (FreeList *p)
void allocateSlab ()
void disposeElements ()
Protected Attributes
PxArray< void *, Alloc > mSlabs
uint32_t mElementsPerSlab
uint32_t mUsed
uint32_t mSlabSize
FreeList * mFreeElement
Detailed Description
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type>
class physx::PxPoolBase< T, Alloc >
Simple allocation pool
Constructor & Destructor Documentation
PxPoolBase()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> physx::PxPoolBase< T, Alloc >::PxPoolBase (const Alloc & alloc, uint32_t elementsPerSlab, uint32_t slabSize) inline protected
References physx::PxPoolBase< T, Alloc >::mSlabs, PX_COMPILE_TIME_ASSERT, and physx::PxArray< T, Alloc >::reserve().
~PxPoolBase()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> physx::PxPoolBase< T, Alloc >::~PxPoolBase () inline
References physx::PxArray< T, Alloc >::begin(), physx::PxPoolBase< T, Alloc >::disposeElements(), physx::PxArray< T, Alloc >::end(), physx::PxPoolBase< T, Alloc >::mSlabs, and physx::PxPoolBase< T, Alloc >::mUsed.
Member Function Documentation
allocate()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE T* physx::PxPoolBase< T, Alloc >::allocate () inline
Mark a specified amount of memory with 0xcd pattern. This is used to check that the meta data definition for serialized classes is complete in checked builds.
References physx::PxPoolBase< T, Alloc >::allocateSlab(), physx::PxPoolBase< T, Alloc >::mFreeElement, physx::PxPoolBase< T, Alloc >::FreeList::mNext, and physx::PxPoolBase< T, Alloc >::mUsed.
Referenced by physx::PxPoolBase< T, Alloc >::construct().
allocateSlab()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> void physx::PxPoolBase< T, Alloc >::allocateSlab () inline protected
References physx::PxPoolBase< T, Alloc >::mElementsPerSlab, physx::PxPoolBase< T, Alloc >::mSlabs, physx::PxPoolBase< T, Alloc >::mSlabSize, physx::PxPoolBase< T, Alloc >::push(), and physx::PxArray< T, Alloc >::pushBack().
Referenced by physx::PxPoolBase< T, Alloc >::allocate().
construct() [1/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct () inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [2/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [3/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [4/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b, A3 & c) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [5/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 * a, A2 & b, A3 & c) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [6/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 , class A4 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b, A3 & c, A4 & d) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [7/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 , class A4 , class A5 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b, A3 & c, A4 & d, A5 & e) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [8/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b, A3 & c, A4 & d, A5 & e, A6 & f) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [9/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b, A3 & c, A4 & d, A5 & e, A6 & f, A7 & g) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
construct() [10/10]
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> template<class A1 , class A2 , class A3 , class A4 , class A5 , class A6 , class A7 , class A8 > PX_INLINE T* physx::PxPoolBase< T, Alloc >::construct (A1 & a, A2 & b, A3 & c, A4 & d, A5 & e, A6 & f, A7 & g, A8 & h) inline
References physx::PxPoolBase< T, Alloc >::allocate(), and PX_PLACEMENT_NEW.
deallocate()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxPoolBase< T, Alloc >::deallocate (T * p) inline
References physx::PxPoolBase< T, Alloc >::mUsed, physx::PxPoolBase< T, Alloc >::push(), and PX_ASSERT.
Referenced by physx::PxPoolBase< T, Alloc >::destroy().
destroy()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxPoolBase< T, Alloc >::destroy (T *const p) inline
References physx::PxPoolBase< T, Alloc >::deallocate().
disposeElements()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> void physx::PxPoolBase< T, Alloc >::disposeElements () inline protected
References physx::PxArray< T, Alloc >::begin(), physx::PxArray< T, Alloc >::end(), physx::PxPoolBase< T, Alloc >::mElementsPerSlab, physx::PxPoolBase< T, Alloc >::mFreeElement, physx::PxPoolBase< T, Alloc >::FreeList::mNext, physx::PxPoolBase< T, Alloc >::mSlabs, physx::PxArray< T, Alloc >::pushBack(), PxSort(), and physx::PxArray< T, Alloc >::size().
Referenced by physx::PxPoolBase< T, Alloc >::~PxPoolBase().
push()
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> void physx::PxPoolBase< T, Alloc >::push (FreeList * p) inline protected
References physx::PxPoolBase< T, Alloc >::mFreeElement, and physx::PxPoolBase< T, Alloc >::FreeList::mNext.
Referenced by physx::PxPoolBase< T, Alloc >::allocateSlab(), and physx::PxPoolBase< T, Alloc >::deallocate().
Member Data Documentation
mElementsPerSlab
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> uint32_t physx::PxPoolBase< T, Alloc >::mElementsPerSlab protected
Referenced by physx::PxPoolBase< T, Alloc >::allocateSlab(), and physx::PxPoolBase< T, Alloc >::disposeElements().
mFreeElement
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> FreeList* physx::PxPoolBase< T, Alloc >::mFreeElement protected
Referenced by physx::PxPoolBase< T, Alloc >::allocate(), physx::PxPoolBase< T, Alloc >::disposeElements(), and physx::PxPoolBase< T, Alloc >::push().
mSlabs
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> PxArray<void*, Alloc> physx::PxPoolBase< T, Alloc >::mSlabs protected
Referenced by physx::PxPoolBase< T, Alloc >::allocateSlab(), physx::PxPoolBase< T, Alloc >::disposeElements(), physx::PxPoolBase< T, Alloc >::PxPoolBase(), and physx::PxPoolBase< T, Alloc >::~PxPoolBase().
mSlabSize
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> uint32_t physx::PxPoolBase< T, Alloc >::mSlabSize protected
Referenced by physx::PxPoolBase< T, Alloc >::allocateSlab().
mUsed
template<class T , class Alloc = typename PxAllocatorTraits<T>::Type> uint32_t physx::PxPoolBase< T, Alloc >::mUsed protected
Referenced by physx::PxPoolBase< T, Alloc >::allocate(), physx::PxPoolBase< T, Alloc >::deallocate(), and physx::PxPoolBase< T, Alloc >::~PxPoolBase().
The documentation for this class was generated from the following file:
PxPool.h