PxVehicleTireComponent Class Reference
PxVehicleTireComponent Class Reference abstract
Vehicle2
#include <PxVehicleTireComponents.h>
Public Member Functions
PxVehicleTireComponent ()
virtual ~PxVehicleTireComponent ()
virtual void getDataForTireComponent (const PxVehicleAxleDescription *&axleDescription, PxVehicleArrayData< const PxReal > &steerResponseStates, const PxVehicleRigidBodyState *&rigidBodyState, PxVehicleArrayData< const PxVehicleWheelActuationState > &actuationStates, PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, PxVehicleArrayData< const PxVehicleSuspensionParams > &suspensionParams, PxVehicleArrayData< const PxVehicleTireForceParams > &tireForceParams, PxVehicleArrayData< const PxVehicleRoadGeometryState > &roadGeomStates, PxVehicleArrayData< const PxVehicleSuspensionState > &suspensionStates, PxVehicleArrayData< const PxVehicleSuspensionComplianceState > &suspensionComplianceStates, PxVehicleArrayData< const PxVehicleSuspensionForce > &suspensionForces, PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelRigidBody1DStates, PxVehicleArrayData< PxVehicleTireGripState > &tireGripStates, PxVehicleArrayData< PxVehicleTireDirectionState > &tireDirectionStates, PxVehicleArrayData< PxVehicleTireSpeedState > &tireSpeedStates, PxVehicleArrayData< PxVehicleTireSlipState > &tireSlipStates, PxVehicleArrayData< PxVehicleTireCamberAngleState > &tireCamberAngleStates, PxVehicleArrayData< PxVehicleTireStickyState > &tireStickyStates, PxVehicleArrayData< PxVehicleTireForce > &tireForces)=0
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Constructor & Destructor Documentation
PxVehicleTireComponent()
PxVehicleTireComponent::PxVehicleTireComponent () inline
~PxVehicleTireComponent()
virtual PxVehicleTireComponent::~PxVehicleTireComponent () inline virtual
Member Function Documentation
getDataForTireComponent()
virtual void PxVehicleTireComponent::getDataForTireComponent (const PxVehicleAxleDescription *& axleDescription, PxVehicleArrayData< const PxReal > & steerResponseStates, const PxVehicleRigidBodyState *& rigidBodyState, PxVehicleArrayData< const PxVehicleWheelActuationState > & actuationStates, PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, PxVehicleArrayData< const PxVehicleSuspensionParams > & suspensionParams, PxVehicleArrayData< const PxVehicleTireForceParams > & tireForceParams, PxVehicleArrayData< const PxVehicleRoadGeometryState > & roadGeomStates, PxVehicleArrayData< const PxVehicleSuspensionState > & suspensionStates, PxVehicleArrayData< const PxVehicleSuspensionComplianceState > & suspensionComplianceStates, PxVehicleArrayData< const PxVehicleSuspensionForce > & suspensionForces, PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelRigidBody1DStates, PxVehicleArrayData< PxVehicleTireGripState > & tireGripStates, PxVehicleArrayData< PxVehicleTireDirectionState > & tireDirectionStates, PxVehicleArrayData< PxVehicleTireSpeedState > & tireSpeedStates, PxVehicleArrayData< PxVehicleTireSlipState > & tireSlipStates, PxVehicleArrayData< PxVehicleTireCamberAngleState > & tireCamberAngleStates, PxVehicleArrayData< PxVehicleTireStickyState > & tireStickyStates, PxVehicleArrayData< PxVehicleTireForce > & tireForces) pure virtual
update()
virtual bool PxVehicleTireComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PxVehicleSimulationContext::frame, PxVehicleAxleDescription::nbWheels, PX_PROFILE_ZONE, PxVehicleTireCamberAnglesUpdate(), PxVehicleTireDirsUpdate(), PxVehicleTireForcesUpdate(), PxVehicleTireGripUpdate(), PxVehicleTireSlipsAccountingForStickyStatesUpdate(), PxVehicleTireSlipSpeedsUpdate(), PxVehicleTireSlipsUpdate(), PxVehicleTireStickyStateUpdate(), PxVehicleSimulationContext::tireSlipParams, PxVehicleSimulationContext::tireStickyParams, and PxVehicleAxleDescription::wheelIdsInAxleOrder.
The documentation for this class was generated from the following file:
PxVehicleTireComponents.h