PxTriangleMesh Class Reference
PxTriangleMesh Class Reference abstract
Geomutils
A triangle mesh, also called a 'polygon soup'.
#include <PxTriangleMesh.h>
Public Member Functions
virtual PxU32 getNbVertices () const =0
Returns the number of vertices.
virtual const PxVec3 * getVertices () const =0
Returns the vertices.
virtual PxVec3 * getVerticesForModification ()=0
Returns all mesh vertices for modification.
virtual PxBounds3 refitBVH ()=0
Refits BVH for mesh vertices.
virtual PxU32 getNbTriangles () const =0
Returns the number of triangles.
virtual const void * getTriangles () const =0
Returns the triangle indices.
virtual PxTriangleMeshFlags getTriangleMeshFlags () const =0
Reads the PxTriangleMesh flags.
virtual const PxU32 * getTrianglesRemap () const =0
Returns the triangle remapping table.
virtual void release ()=0
Decrements the reference count of a triangle mesh and releases it if the new reference count is zero.
virtual PxMaterialTableIndex getTriangleMaterialIndex (PxTriangleID triangleIndex) const =0
Returns material table index of given triangle.
virtual PxBounds3 getLocalBounds () const =0
Returns the local-space (vertex space) AABB from the triangle mesh.
virtual const PxReal * getSDF () const =0
Returns the local-space Signed Distance Field for this mesh if it has one.
virtual void getSDFDimensions (PxU32 &numX, PxU32 &numY, PxU32 &numZ) const =0
Returns the resolution of the local-space dense SDF.
virtual void setPreferSDFProjection (bool preferProjection)=0
Sets whether this mesh should be preferred for SDF projection.
virtual bool getPreferSDFProjection () const =0
Returns whether this mesh prefers SDF projection.
virtual void getMassInformation (PxReal &mass, PxMat33 &localInertia, PxVec3 &localCenterOfMass) const =0
Returns the mass properties of the mesh assuming unit density.
Public Member Functions inherited from PxRefCounted
virtual PxU32 getReferenceCount () const =0
Returns the reference count of the object.
virtual void acquireReference ()=0
Acquires a counted reference to this object.
Public Member Functions inherited from PxBase
virtual const char * getConcreteTypeName () const =0
Returns string name of dynamic type.
template<class T >
T * is ()
template<class T >
const T * is () const
PX_FORCE_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_FORCE_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_FORCE_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_FORCE_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Protected Member Functions
PX_INLINE PxTriangleMesh (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxTriangleMesh (PxBaseFlags baseFlags)
virtual ~PxTriangleMesh ()
virtual bool isKindOf (const char *name) const
Returns whether a given type name matches with the type of this instance.
Protected Member Functions inherited from PxRefCounted
virtual void onRefCountZero ()
PX_INLINE PxRefCounted (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxRefCounted (PxBaseFlags baseFlags)
virtual ~PxRefCounted ()
Protected Member Functions inherited from PxBase
PX_INLINE PxBase (PxType concreteType, PxBaseFlags baseFlags)
Constructor setting concrete type and base flags.
PX_INLINE PxBase (PxBaseFlags baseFlags)
Deserialization constructor setting base flags.
virtual ~PxBase ()
Destructor.
template<class T >
bool typeMatch () const
Additional Inherited Members
Protected Attributes inherited from PxBase
PxType mConcreteType
PxBaseFlags mBaseFlags
PxU32 mBuiltInRefCount
Detailed Description
A triangle mesh, also called a 'polygon soup'.
It is represented as an indexed triangle list. There are no restrictions on the triangle data.
To avoid duplicating data when you have several instances of a particular mesh positioned differently, you do not use this class to represent a mesh object directly. Instead, you create an instance of this mesh via the PxTriangleMeshGeometry and PxShape classes.
Creation
To create an instance of this class call PxPhysics::createTriangleMesh(), and release() to delete it. This is only possible once you have released all of its PxShape instances.
Visualizations:
PxVisualizationParameter::eCOLLISION_AABBS
PxVisualizationParameter::eCOLLISION_SHAPES
PxVisualizationParameter::eCOLLISION_AXES
PxVisualizationParameter::eCOLLISION_FNORMALS
PxVisualizationParameter::eCOLLISION_EDGES
See also
PxTriangleMeshDesc PxTriangleMeshGeometry PxShape PxPhysics.createTriangleMesh()
Constructor & Destructor Documentation
PxTriangleMesh() [1/2]
PX_INLINE PxTriangleMesh::PxTriangleMesh (PxType concreteType, PxBaseFlags baseFlags) inline protected
PxTriangleMesh() [2/2]
PX_INLINE PxTriangleMesh::PxTriangleMesh (PxBaseFlags baseFlags) inline protected
~PxTriangleMesh()
virtual PxTriangleMesh::~PxTriangleMesh () inline protected virtual
Member Function Documentation
getLocalBounds()
virtual PxBounds3 PxTriangleMesh::getLocalBounds () const pure virtual
Returns the local-space (vertex space) AABB from the triangle mesh.
Returns
local-space bounds
getMassInformation()
virtual void PxTriangleMesh::getMassInformation (PxReal & mass, PxMat33 & localInertia, PxVec3 & localCenterOfMass) const pure virtual
Returns the mass properties of the mesh assuming unit density.
The following relationship holds between mass and volume:
mass = volume * density
The mass of a unit density mesh is equal to its volume, so this function returns the volume of the mesh.
Similarly, to obtain the localInertia of an identically shaped object with a uniform density of d, simply multiply the localInertia of the unit density mesh by d.
Parameters
[out] mass The mass of the mesh assuming unit density.
[out] localInertia The inertia tensor in mesh local space assuming unit density.
[out] localCenterOfMass Position of center of mass (or centroid) in mesh local space.
Referenced by PxMassProperties::PxMassProperties().
getNbTriangles()
virtual PxU32 PxTriangleMesh::getNbTriangles () const pure virtual
Returns the number of triangles.
Returns
number of triangles
See also
getTriangles() getTrianglesRemap()
getNbVertices()
virtual PxU32 PxTriangleMesh::getNbVertices () const pure virtual
Returns the number of vertices.
Returns
number of vertices
See also
getVertices()
getPreferSDFProjection()
virtual bool PxTriangleMesh::getPreferSDFProjection () const pure virtual
Returns whether this mesh prefers SDF projection.
Returns
whether this mesh prefers SDF projection.
getSDF()
virtual const PxReal* PxTriangleMesh::getSDF () const pure virtual
Returns the local-space Signed Distance Field for this mesh if it has one.
Returns
local-space SDF.
getSDFDimensions()
virtual void PxTriangleMesh::getSDFDimensions (PxU32 & numX, PxU32 & numY, PxU32 & numZ) const pure virtual
Returns the resolution of the local-space dense SDF.
getTriangleMaterialIndex()
virtual PxMaterialTableIndex PxTriangleMesh::getTriangleMaterialIndex (PxTriangleID triangleIndex) const pure virtual
Returns material table index of given triangle.
This function takes a post cooking triangle index.
Parameters
[in] triangleIndex (internal) index of desired triangle
Returns
Material table index, or 0xffff if no per-triangle materials are used
getTriangleMeshFlags()
virtual PxTriangleMeshFlags PxTriangleMesh::getTriangleMeshFlags () const pure virtual
Reads the PxTriangleMesh flags.
See the list of flags PxTriangleMeshFlag
Returns
The values of the PxTriangleMesh flags.
See also
PxTriangleMesh
getTriangles()
virtual const void* PxTriangleMesh::getTriangles () const pure virtual
Returns the triangle indices.
The indices can be 16 or 32bit depending on the number of triangles in the mesh. Call getTriangleMeshFlags() to know if the indices are 16 or 32 bits.
The number of indices is the number of triangles * 3.
Returns
array of triangles
See also
getNbTriangles() getTriangleMeshFlags() getTrianglesRemap()
getTrianglesRemap()
virtual const PxU32* PxTriangleMesh::getTrianglesRemap () const pure virtual
Returns the triangle remapping table.
The triangles are internally sorted according to various criteria. Hence the internal triangle order does not always match the original (user-defined) order. The remapping table helps finding the old indices knowing the new ones:
remapTable[ internalTriangleIndex ] = originalTriangleIndex
Returns
the remapping table (or NULL if 'PxCookingParams::suppressTriangleMeshRemapTable' has been used)
See also
getNbTriangles() getTriangles() PxCookingParams::suppressTriangleMeshRemapTable
getVertices()
virtual const PxVec3* PxTriangleMesh::getVertices () const pure virtual
Returns the vertices.
Returns
array of vertices
See also
getNbVertices()
getVerticesForModification()
virtual PxVec3* PxTriangleMesh::getVerticesForModification () pure virtual
Returns all mesh vertices for modification.
This function will return the vertices of the mesh so that their positions can be changed in place. After modifying the vertices you must call refitBVH for the refitting to actually take place. This function maintains the old mesh topology (triangle indices).
Returns
inplace vertex coordinates for each existing mesh vertex.
Note
It is recommended to use this feature for scene queries only.
Size of array returned is equal to the number returned by getNbVertices().
This function operates on cooked vertex indices.
This means the index mapping and vertex count can be different from what was provided as an input to the cooking routine.
To achieve unchanged 1-to-1 index mapping with orignal mesh data (before cooking) please use the following cooking flags:
eWELD_VERTICES = 0, eDISABLE_CLEAN_MESH = 1.
It is also recommended to make sure that a call to validateTriangleMesh returns true if mesh cleaning is disabled.
See also
getNbVertices()
refitBVH()
isKindOf()
virtual bool PxTriangleMesh::isKindOf (const char * superClass) const inline protected virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented from PxRefCounted.
Reimplemented in PxBVH34TriangleMesh, and PxBVH33TriangleMesh.
References PxRefCounted::isKindOf().
Referenced by PxBVH33TriangleMesh::isKindOf(), and PxBVH34TriangleMesh::isKindOf().
refitBVH()
virtual PxBounds3 PxTriangleMesh::refitBVH () pure virtual
Refits BVH for mesh vertices.
This function will refit the mesh BVH to correctly enclose the new positions updated by getVerticesForModification. Mesh BVH will not be reoptimized by this function so significantly different new positions will cause significantly reduced performance.
Returns
New bounds for the entire mesh.
Note
For PxMeshMidPhase::eBVH34 trees the refit operation is only available on non-quantized trees (see PxBVH34MidphaseDesc::quantized)
PhysX does not keep a mapping from the mesh to mesh shapes that reference it.
Call PxShape::setGeometry on each shape which references the mesh, to ensure that internal data structures are updated to reflect the new geometry.
PxShape::setGeometry does not guarantee correct/continuous behavior when objects are resting on top of old or new geometry.
It is also recommended to make sure that a call to validateTriangleMesh returns true if mesh cleaning is disabled.
Active edges information will be lost during refit, the rigid body mesh contact generation might not perform as expected.
See also
getNbVertices()
getVerticesForModification()
PxBVH34MidphaseDesc::quantized
release()
virtual void PxTriangleMesh::release () pure virtual
Decrements the reference count of a triangle mesh and releases it if the new reference count is zero.
See also
PxPhysics.createTriangleMesh()
Implements PxRefCounted.
setPreferSDFProjection()
virtual void PxTriangleMesh::setPreferSDFProjection (bool preferProjection) pure virtual
Sets whether this mesh should be preferred for SDF projection.
By default, meshes are flagged as preferring projection and the decisions on which mesh to project is based on the triangle and vertex count. The model with the fewer triangles is projected onto the SDF of the more detailed mesh. If one of the meshes is set to prefer SDF projection (default) and the other is set to not prefer SDF projection, model flagged as preferring SDF projection will be projected onto the model flagged as not preferring, regardless of the detail of the respective meshes. Where both models are flagged as preferring no projection, the less detailed model will be projected as before.
Parameters
[in] preferProjection Indicates if projection is preferred
The documentation for this class was generated from the following file:
PxTriangleMesh.h