PxMutexT< Alloc > Class Template Reference
PxMutexT< Alloc > Class Template Reference
#include <PxMutex.h>
Classes
class ScopedLock
Public Member Functions
PxMutexT (const Alloc &alloc=Alloc())
~PxMutexT ()
PX_FORCE_INLINE void lock () const
PX_FORCE_INLINE bool trylock () const
PX_FORCE_INLINE void unlock () const
Private Attributes
PxMutexImpl * mImpl
Constructor & Destructor Documentation
PxMutexT()
template<typename Alloc = PxReflectionAllocator<PxMutexImpl>> PxMutexT< Alloc >::PxMutexT (const Alloc & alloc = Alloc()) inline
The constructor for Mutex creates a mutex. It is initially unlocked.
References PxMutexImpl::getSize(), and PX_PLACEMENT_NEW.
~PxMutexT()
template<typename Alloc = PxReflectionAllocator<PxMutexImpl>> PxMutexT< Alloc >::~PxMutexT () inline
The destructor for Mutex deletes the mutex.
Member Function Documentation
lock()
template<typename Alloc = PxReflectionAllocator<PxMutexImpl>> PX_FORCE_INLINE void PxMutexT< Alloc >::lock () const inline
Acquire (lock) the mutex. If the mutex is already locked by another thread, this method blocks until the mutex is unlocked.
Referenced by PxMutexT< Alloc >::ScopedLock::ScopedLock().
trylock()
template<typename Alloc = PxReflectionAllocator<PxMutexImpl>> PX_FORCE_INLINE bool PxMutexT< Alloc >::trylock () const inline
Acquire (lock) the mutex. If the mutex is already locked by another thread, this method returns false without blocking, returns true if lock is successfully acquired
unlock()
template<typename Alloc = PxReflectionAllocator<PxMutexImpl>> PX_FORCE_INLINE void PxMutexT< Alloc >::unlock () const inline
Release (unlock) the mutex, the calling thread must have previously called lock() or method will error
Referenced by PxMutexT< Alloc >::ScopedLock::~ScopedLock().
Member Data Documentation
mImpl
template<typename Alloc = PxReflectionAllocator<PxMutexImpl>> PxMutexImpl* PxMutexT< Alloc >::mImpl private
The documentation for this class was generated from the following file:
PxMutex.h