aos::PxMatTransformV Class Reference
aos::PxMatTransformV Class Reference
#include <PxVecTransform.h>
Public Member Functions
PX_FORCE_INLINE PxMatTransformV ()
PX_FORCE_INLINE PxMatTransformV (const Vec3VArg _p, const Mat33V &_rot)
PX_FORCE_INLINE PxMatTransformV (const PxTransformV &other)
PX_FORCE_INLINE PxMatTransformV (const Vec3VArg _p, const QuatV &quat)
PX_FORCE_INLINE Vec3V getCol0 () const
PX_FORCE_INLINE Vec3V getCol1 () const
PX_FORCE_INLINE Vec3V getCol2 () const
PX_FORCE_INLINE void setCol0 (const Vec3VArg col0)
PX_FORCE_INLINE void setCol1 (const Vec3VArg col1)
PX_FORCE_INLINE void setCol2 (const Vec3VArg col2)
PX_FORCE_INLINE Vec3V transform (const Vec3VArg input) const
PX_FORCE_INLINE Vec3V transformInv (const Vec3VArg input) const
PX_FORCE_INLINE Vec3V rotate (const Vec3VArg input) const
PX_FORCE_INLINE Vec3V rotateInv (const Vec3VArg input) const
PX_FORCE_INLINE PxMatTransformV transformInv (const PxMatTransformV &src) const
Public Attributes
Mat33V rot
Vec3V p
Constructor & Destructor Documentation
PxMatTransformV() [1/4]
PX_FORCE_INLINE aos::PxMatTransformV::PxMatTransformV () inline
References physx::aos::M33Identity(), and physx::aos::V3Zero().
PxMatTransformV() [2/4]
PX_FORCE_INLINE aos::PxMatTransformV::PxMatTransformV (const Vec3VArg _p, const Mat33V & _rot) inline
PxMatTransformV() [3/4]
PX_FORCE_INLINE aos::PxMatTransformV::PxMatTransformV (const PxTransformV & other) inline
References aos::Mat33V::col0, aos::Mat33V::col1, aos::Mat33V::col2, aos::PxTransformV::p, aos::PxTransformV::q, and physx::aos::QuatGetMat33V().
PxMatTransformV() [4/4]
PX_FORCE_INLINE aos::PxMatTransformV::PxMatTransformV (const Vec3VArg _p, const QuatV & quat) inline
References aos::Mat33V::col0, aos::Mat33V::col1, aos::Mat33V::col2, and physx::aos::QuatGetMat33V().
Member Function Documentation
getCol0()
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::getCol0 () const inline
References aos::Mat33V::col0.
getCol1()
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::getCol1 () const inline
References aos::Mat33V::col1.
getCol2()
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::getCol2 () const inline
References aos::Mat33V::col2.
rotate()
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::rotate (const Vec3VArg input) const inline
References physx::aos::M33MulV3().
rotateInv()
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::rotateInv (const Vec3VArg input) const inline
References physx::aos::M33TrnspsMulV3().
setCol0()
PX_FORCE_INLINE void aos::PxMatTransformV::setCol0 (const Vec3VArg col0) inline
References aos::Mat33V::col0.
setCol1()
PX_FORCE_INLINE void aos::PxMatTransformV::setCol1 (const Vec3VArg col1) inline
References aos::Mat33V::col1.
setCol2()
PX_FORCE_INLINE void aos::PxMatTransformV::setCol2 (const Vec3VArg col2) inline
References aos::Mat33V::col2.
transform()
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::transform (const Vec3VArg input) const inline
References physx::aos::M33MulV3(), and physx::aos::V3Add().
transformInv() [1/2]
PX_FORCE_INLINE Vec3V aos::PxMatTransformV::transformInv (const Vec3VArg input) const inline
References physx::aos::M33TrnspsMulV3(), and physx::aos::V3Sub().
transformInv() [2/2]
PX_FORCE_INLINE PxMatTransformV aos::PxMatTransformV::transformInv (const PxMatTransformV & src) const inline
References physx::aos::M33MulM33(), physx::aos::M33Trnsps(), physx::aos::M33TrnspsMulV3(), p, rot, and physx::aos::V3Sub().
Member Data Documentation
p
Vec3V aos::PxMatTransformV::p
Referenced by transformInv().
rot
Mat33V aos::PxMatTransformV::rot
Referenced by transformInv().
The documentation for this class was generated from the following file:
PxVecTransform.h