PxBase Class Reference
PxBase Class Reference abstract
Common
Base class for objects that can be members of a PxCollection.
#include <PxBase.h>
Public Member Functions
virtual void release ()=0
Releases the PxBase instance, please check documentation of release in derived class.
virtual const char * getConcreteTypeName () const =0
Returns string name of dynamic type.
template<class T >
T * is ()
template<class T >
const T * is () const
PX_FORCE_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_FORCE_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_FORCE_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_FORCE_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Protected Member Functions
PX_INLINE PxBase (PxType concreteType, PxBaseFlags baseFlags)
Constructor setting concrete type and base flags.
PX_INLINE PxBase (PxBaseFlags baseFlags)
Deserialization constructor setting base flags.
virtual ~PxBase ()
Destructor.
virtual bool isKindOf (const char *superClass) const
Returns whether a given type name matches with the type of this instance.
template<class T >
bool typeMatch () const
Protected Attributes
PxType mConcreteType
PxBaseFlags mBaseFlags
PxU32 mBuiltInRefCount
Friends
void getBinaryMetaData_PxBase (PxOutputStream &stream)
Detailed Description
Base class for objects that can be members of a PxCollection.
All PxBase sub-classes can be serialized.
See also
PxCollection
Constructor & Destructor Documentation
PxBase() [1/2]
PX_INLINE PxBase::PxBase (PxType concreteType, PxBaseFlags baseFlags) inline protected
Constructor setting concrete type and base flags.
PxBase() [2/2]
PX_INLINE PxBase::PxBase (PxBaseFlags baseFlags) inline protected
Deserialization constructor setting base flags.
References PX_ASSERT.
~PxBase()
virtual PxBase::~PxBase () inline protected virtual
Destructor.
Member Function Documentation
getBaseFlags()
PX_FORCE_INLINE PxBaseFlags PxBase::getBaseFlags () const inline
Returns PxBaseFlags.
Returns
PxBaseFlags
See also
PxBaseFlags
getConcreteType()
PX_FORCE_INLINE PxType PxBase::getConcreteType () const inline
Returns concrete type of object.
Returns
PxConcreteType::Enum of serialized object
See also
PxConcreteType
getConcreteTypeName()
virtual const char* PxBase::getConcreteTypeName () const pure virtual
Returns string name of dynamic type.
Returns
Class name of most derived type of this object.
Implemented in PxVehicleWheels, PxShape, PxVehicleDrive, PxArticulationFixedTendon, PxD6Joint, PxArticulationJointReducedCoordinate, PxRigidDynamic, PxArticulationSpatialTendon, PxArticulationSensor, PxMPMMaterial, PxMaterial, PxRevoluteJoint, PxBVH, PxDistanceJoint, PxVehicleDrive4W, PxVehicleDriveTank, PxConstraint, PxAggregate, PxHeightField, PxVehicleDriveNW, PxCustomMaterial, PxPrismaticJoint, PxPBDMaterial, PxVehicleNoDrive, PxArticulationLink, PxSphericalJoint, PxConvexMesh, PxContactJoint, PxFixedJoint, PxRackAndPinionJoint, PxPruningStructure, PxGearJoint, PxFEMClothMaterial, PxFEMSoftBodyMaterial, PxFLIPMaterial, and PxRigidStatic.
is() [1/2]
template<class T > T* PxBase::is () inline
is() [2/2]
template<class T > const T* PxBase::is () const inline
isKindOf()
virtual bool PxBase::isKindOf (const char * superClass) const inline protected virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented in PxVehicleWheels, PxShape, PxRigidBody, PxD6Joint, PxVehicleDrive, PxArticulationJointReducedCoordinate, PxRigidDynamic, PxMPMMaterial, PxJoint, PxActor, PxMaterial, PxBVH34TriangleMesh, PxRevoluteJoint, PxBVH33TriangleMesh, PxTriangleMesh, PxBVH, PxDistanceJoint, PxSoftBodyMesh, PxConstraint, PxVehicleDriveTank, PxVehicleDrive4W, PxAggregate, PxHeightField, PxRefCounted, PxRigidActor, PxPrismaticJoint, PxCustomMaterial, PxVehicleDriveNW, PxPBDMaterial, PxSphericalJoint, PxTetrahedronMesh, PxArticulationLink, PxVehicleNoDrive, PxConvexMesh, PxContactJoint, PxFixedJoint, PxParticleMaterial, PxRackAndPinionJoint, PxPruningStructure, PxGearJoint, PxFEMMaterial, PxFEMClothMaterial, PxFEMSoftBodyMaterial, PxSoftBodyAuxData, PxFLIPMaterial, PxRigidStatic, and PxBaseMaterial.
Referenced by PxPruningStructure::isKindOf(), PxVehicleNoDrive::isKindOf(), PxVehicleDriveNW::isKindOf(), PxRefCounted::isKindOf(), PxAggregate::isKindOf(), PxVehicleDrive4W::isKindOf(), PxVehicleDriveTank::isKindOf(), PxConstraint::isKindOf(), PxBVH::isKindOf(), PxActor::isKindOf(), PxJoint::isKindOf(), PxArticulationJointReducedCoordinate::isKindOf(), PxVehicleDrive::isKindOf(), and PxVehicleWheels::isKindOf().
isReleasable()
virtual bool PxBase::isReleasable () const inline virtual
Whether the object is subordinate.
A class is subordinate, if it can only be instantiated in the context of another class.
Returns
Whether the class is subordinate
See also
PxSerialization::isSerializable
References PxBaseFlag::eIS_RELEASABLE.
release()
virtual void PxBase::release () pure virtual
Releases the PxBase instance, please check documentation of release in derived class.
Implemented in PxVehicleWheels, PxArticulationReducedCoordinate, PxSoftBody, PxArticulationTendon, PxJoint, PxArticulationSensor, PxSoftBodyMesh, PxTriangleMesh, PxActor, PxRefCounted, PxTetrahedronMesh, PxShape, PxConvexMesh, PxAggregate, PxConstraint, PxHeightField, PxSoftBodyAuxData, PxRigidActor, PxPruningStructure, and PxArticulationLink.
setBaseFlag()
PX_FORCE_INLINE void PxBase::setBaseFlag (PxBaseFlag::Enum flag, bool value) inline
Set PxBaseFlag.
Parameters
[in] flag The flag to be set
[in] value The flags new value
setBaseFlags()
PX_FORCE_INLINE void PxBase::setBaseFlags (PxBaseFlags inFlags) inline
Set PxBaseFlags.
Parameters
[in] inFlags The flags to be set
See also
PxBaseFlags
typeMatch()
template<class T > bool PxBase::typeMatch () const inline protected
References PxConcreteType::eUNDEFINED.
Friends And Related Function Documentation
getBinaryMetaData_PxBase
void getBinaryMetaData_PxBase (PxOutputStream & stream) friend
Member Data Documentation
mBaseFlags
PxBaseFlags PxBase::mBaseFlags protected
mBuiltInRefCount
PxU32 PxBase::mBuiltInRefCount protected
mConcreteType
PxType PxBase::mConcreteType protected
The documentation for this class was generated from the following file:
PxBase.h