PxVehiclePhysXRoadGeometrySceneQueryComponent Class Reference
PxVehiclePhysXRoadGeometrySceneQueryComponent Class Reference abstract
Vehicle2
#include <PxVehiclePhysXRoadGeometryComponents.h>
Public Member Functions
PxVehiclePhysXRoadGeometrySceneQueryComponent ()
virtual ~PxVehiclePhysXRoadGeometrySceneQueryComponent ()
virtual void getDataForPhysXRoadGeometrySceneQueryComponent (const PxVehicleAxleDescription *&axleDescription, const PxVehiclePhysXRoadGeometryQueryParams *&roadGeomParams, PxVehicleArrayData< const PxReal > &steerResponseStates, const PxVehicleRigidBodyState *&rigidBodyState, PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, PxVehicleArrayData< const PxVehicleSuspensionParams > &suspensionParams, PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > &materialFrictionParams, PxVehicleArrayData< PxVehicleRoadGeometryState > &roadGeometryStates, PxVehicleArrayData< PxVehiclePhysXRoadGeometryQueryState > &physxRoadGeometryStates)=0
Provide vehicle data items for this component.
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Constructor & Destructor Documentation
PxVehiclePhysXRoadGeometrySceneQueryComponent()
PxVehiclePhysXRoadGeometrySceneQueryComponent::PxVehiclePhysXRoadGeometrySceneQueryComponent () inline
~PxVehiclePhysXRoadGeometrySceneQueryComponent()
virtual PxVehiclePhysXRoadGeometrySceneQueryComponent::~PxVehiclePhysXRoadGeometrySceneQueryComponent () inline virtual
Member Function Documentation
getDataForPhysXRoadGeometrySceneQueryComponent()
virtual void PxVehiclePhysXRoadGeometrySceneQueryComponent::getDataForPhysXRoadGeometrySceneQueryComponent (const PxVehicleAxleDescription *& axleDescription, const PxVehiclePhysXRoadGeometryQueryParams *& roadGeomParams, PxVehicleArrayData< const PxReal > & steerResponseStates, const PxVehicleRigidBodyState *& rigidBodyState, PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, PxVehicleArrayData< const PxVehicleSuspensionParams > & suspensionParams, PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > & materialFrictionParams, PxVehicleArrayData< PxVehicleRoadGeometryState > & roadGeometryStates, PxVehicleArrayData< PxVehiclePhysXRoadGeometryQueryState > & physxRoadGeometryStates) pure virtual
Provide vehicle data items for this component.
Parameters
[out] axleDescription identifies the wheels on each axle.
[out] roadGeomParams The road geometry parameters of the vehicle.
[out] steerResponseStates The steer response state of the wheels.
[out] rigidBodyState The pose, velocity etc. of the vehicle rigid body.
[out] wheelParams The wheel parameters for the wheels.
[out] suspensionParams The suspension parameters for the wheels.
[out] materialFrictionParams The tire friction tables for the wheels.
[out] roadGeometryStates The detected ground surface plane, friction value etc. for the wheels.
[out] physxRoadGeometryStates Optional buffer to store additional information about the query (like actor/shape that got hit etc.). Set to empty if not desired.
update()
virtual bool PxVehiclePhysXRoadGeometrySceneQueryComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PxVehicleSimulationContextType::ePHYSX, PxVehicleSimulationContext::frame, PxVehicleSimulationContext::getType(), PxVehicleArrayData< T >::isEmpty(), PxVehicleAxleDescription::nbWheels, PxVehiclePhysXSimulationContext::physxScene, PxVehiclePhysXSimulationContext::physxUnitCylinderSweepMesh, PX_ALWAYS_ASSERT, PX_PROFILE_ZONE, PX_UNUSED(), PxVehiclePhysXRoadGeometryQueryUpdate(), and PxVehicleAxleDescription::wheelIdsInAxleOrder.
The documentation for this class was generated from the following file:
PxVehiclePhysXRoadGeometryComponents.h