PxVehicleEngineDriveCommandResponseComponent Class Reference
PxVehicleEngineDriveCommandResponseComponent Class Reference abstract
Vehicle2
Forward the applicable set of control values for a vehicle driven by an engine to a command response state for each applicable control value.
#include <PxVehicleDrivetrainComponents.h>
Public Member Functions
PxVehicleEngineDriveCommandResponseComponent ()
virtual ~PxVehicleEngineDriveCommandResponseComponent ()
virtual void getDataForEngineDriveCommandResponseComponent (const PxVehicleAxleDescription *&axleDescription, PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > &brakeResponseParams, const PxVehicleSteerCommandResponseParams *&steerResponseParams, PxVehicleSizedArrayData< const PxVehicleAckermannParams > &ackermannParams, const PxVehicleGearboxParams *&gearboxParams, const PxVehicleClutchCommandResponseParams *&clutchResponseParams, const PxVehicleEngineParams *&engineParams, const PxVehicleRigidBodyState *&rigidBodyState, const PxVehicleEngineState *&engineState, const PxVehicleAutoboxParams *&autoboxParams, const PxVehicleCommandState *&commands, const PxVehicleEngineDriveTransmissionCommandState *&transmissionCommands, PxVehicleArrayData< PxReal > &brakeResponseStates, PxVehicleEngineDriveThrottleCommandResponseState *&throttleResponseState, PxVehicleArrayData< PxReal > &steerResponseStates, PxVehicleGearboxState *&gearboxResponseState, PxVehicleClutchCommandResponseState *&clutchResponseState, PxVehicleAutoboxState *&autoboxState)=0
Provide vehicle data items for this component.
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Detailed Description
Forward the applicable set of control values for a vehicle driven by an engine to a command response state for each applicable control value.
If parameters for an autobox are provided, the autobox will determine if a gear change should begin in order to maintain a desired engine revs.
See also
PxVehicleBrakeCommandLinearUpdate
PxVehicleClutchCommandResponseLinearUpdate
PxVehicleEngineDriveThrottleCommandResponseUpdate
PxVehicleSteerCommandLinearUpdate
PxVehicleAckermannSteerUpdate
PxVehicleAutoBoxUpdate
PxVehicleGearCommandResponseUpdate
Constructor & Destructor Documentation
PxVehicleEngineDriveCommandResponseComponent()
PxVehicleEngineDriveCommandResponseComponent::PxVehicleEngineDriveCommandResponseComponent () inline
~PxVehicleEngineDriveCommandResponseComponent()
virtual PxVehicleEngineDriveCommandResponseComponent::~PxVehicleEngineDriveCommandResponseComponent () inline virtual
Member Function Documentation
getDataForEngineDriveCommandResponseComponent()
virtual void PxVehicleEngineDriveCommandResponseComponent::getDataForEngineDriveCommandResponseComponent (const PxVehicleAxleDescription *& axleDescription, PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > & brakeResponseParams, const PxVehicleSteerCommandResponseParams *& steerResponseParams, PxVehicleSizedArrayData< const PxVehicleAckermannParams > & ackermannParams, const PxVehicleGearboxParams *& gearboxParams, const PxVehicleClutchCommandResponseParams *& clutchResponseParams, const PxVehicleEngineParams *& engineParams, const PxVehicleRigidBodyState *& rigidBodyState, const PxVehicleEngineState *& engineState, const PxVehicleAutoboxParams *& autoboxParams, const PxVehicleCommandState *& commands, const PxVehicleEngineDriveTransmissionCommandState *& transmissionCommands, PxVehicleArrayData< PxReal > & brakeResponseStates, PxVehicleEngineDriveThrottleCommandResponseState *& throttleResponseState, PxVehicleArrayData< PxReal > & steerResponseStates, PxVehicleGearboxState *& gearboxResponseState, PxVehicleClutchCommandResponseState *& clutchResponseState, PxVehicleAutoboxState *& autoboxState) pure virtual
Provide vehicle data items for this component.
Parameters
[out] axleDescription identifies the wheels on each axle.
[out] brakeResponseParams An array of brake response parameters with a brake response for each brake command.
[out] steerResponseParams The steer response parameters.
[out] ackermannParams The parameters defining Ackermann steering. NULL if no Ackermann steering is desired.
[out] gearboxParams The gearbox parameters.
[out] clutchResponseParams The clutch response parameters.
[out] engineParams The engine parameters. Only needed if an autobox is provided (see autoboxParams), else it can be set to NULL.
[out] engineState The engine state. Only needed if an autobox is provided (see autoboxParams), else it can be set to NULL.
[out] autoboxParams The autobox parameters. If not NULL, the autobox will determine the target gear. Requires the parameters engineParams, engineState and autoboxState to be available. If no autobox is desired, NULL can be used in which case the aforementioned additional parameters can be set to NULL too.
[out] rigidBodyState The state of the vehicle's rigid body.
[out] commands The throttle, brake, steer etc. command states.
[out] transmissionCommands The clutch, target gear etc. command states. If an autobox is provided (see autoboxParams) and the target gear is set to PxVehicleEngineDriveTransmissionCommandState::eAUTOMATIC_GEAR, then the autobox will trigger gear shifts.
[out] brakeResponseStates The resulting brake response states given the command input and brake response parameters.
[out] throttleResponseState The resulting throttle response to the input throttle command.
[out] steerResponseStates The resulting steer response states given the command input, steer response and (optionally) Ackermann parameters.
[out] gearboxResponseState The resulting gearbox response state given the command input and gearbox parameters.
[out] clutchResponseState The resulting clutch state given the command input and clutch response parameters.
[out] autoboxState The resulting autobox state given the autobox/engine/gear params and engine state. Only needed if an autobox is provided (see autoboxParams), else it can be set to NULL.
update()
virtual bool PxVehicleEngineDriveCommandResponseComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PxVehicleCommandState::brakes, PxVehicleEngineDriveTransmissionCommandState::clutch, PxVehicleEngineDriveTransmissionCommandState::eAUTOMATIC_GEAR, PxVehicleSimulationContext::frame, PxVehicleRigidBodyState::getLongitudinalSpeed(), PxVehicleCommandState::nbBrakes, PxVehicleAxleDescription::nbWheels, PX_ASSERT, PX_PROFILE_ZONE, PX_UNUSED(), PxVehicleAckermannSteerUpdate(), PxVehicleAutoBoxUpdate(), PxVehicleBrakeCommandResponseUpdate(), PxVehicleClutchCommandResponseLinearUpdate(), PxVehicleEngineDriveThrottleCommandResponseLinearUpdate(), PxVehicleGearCommandResponseUpdate(), PxVehicleSteerCommandResponseUpdate(), PxVehicleSizedArrayData< T >::size, PxVehicleCommandState::steer, PxVehicleGearboxState::targetGear, PxVehicleEngineDriveTransmissionCommandState::targetGear, PxVehicleCommandState::throttle, and PxVehicleAxleDescription::wheelIdsInAxleOrder.
The documentation for this class was generated from the following file:
PxVehicleDrivetrainComponents.h