PxQuatT< Type > Class Template Reference
PxQuatT< Type > Class Template Reference
Foundation
This is a quaternion class. For more information on quaternion mathematics consult a mathematics source on complex numbers.
#include <Px.h>
Public Member Functions
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT ()
Default constructor, does not do any initialization.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT (PxIDENTITY)
identity constructor
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT (Type r)
Constructor from a scalar: sets the real part w to the scalar value, and the imaginary parts (x,y,z) to zero.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT (Type nx, Type ny, Type nz, Type nw)
Constructor. Take note of the order of the elements!
PX_CUDA_CALLABLE PX_INLINE PxQuatT (Type angleRadians, const PxVec3T< Type > &unitAxis)
Creates from angle-axis representation.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT (const PxQuatT &v)
Copy ctor.
PX_CUDA_CALLABLE PX_INLINE PxQuatT (const PxMat33T< Type > &m)
Creates from orientation matrix.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isIdentity () const
returns true if quat is identity
PX_CUDA_CALLABLE bool isFinite () const
returns true if all elements are finite (not NAN or INF, etc.)
PX_CUDA_CALLABLE bool isUnit () const
returns true if finite and magnitude is close to unit
PX_CUDA_CALLABLE bool isSane () const
returns true if finite and magnitude is reasonably close to unit to allow for some accumulation of error vs isValid
PX_CUDA_CALLABLE PX_FORCE_INLINE bool operator== (const PxQuatT &q) const
returns true if the two quaternions are exactly equal
PX_CUDA_CALLABLE PX_INLINE void toRadiansAndUnitAxis (Type &angle, PxVec3T< Type > &axis) const
converts this quaternion to angle-axis representation
PX_CUDA_CALLABLE PX_FORCE_INLINE Type getAngle () const
Gets the angle between this quat and the identity quaternion.
PX_CUDA_CALLABLE PX_FORCE_INLINE Type getAngle (const PxQuatT &q) const
Gets the angle between this quat and the argument.
PX_CUDA_CALLABLE PX_FORCE_INLINE Type magnitudeSquared () const
This is the squared 4D vector length, should be 1 for unit quaternions.
PX_CUDA_CALLABLE PX_FORCE_INLINE Type dot (const PxQuatT &v) const
returns the scalar product of this and other.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT getNormalized () const
PX_CUDA_CALLABLE PX_FORCE_INLINE Type magnitude () const
PX_CUDA_CALLABLE PX_FORCE_INLINE Type normalize ()
maps to the closest unit quaternion.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT getConjugate () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T< Type > getImaginaryPart () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T< Type > getBasisVector0 () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T< Type > getBasisVector1 () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T< Type > getBasisVector2 () const
PX_CUDA_CALLABLE PX_FORCE_INLINE const PxVec3T< Type > rotate (const PxVec3T< Type > &v) const
PX_CUDA_CALLABLE PX_FORCE_INLINE const PxVec3T< Type > rotateInv (const PxVec3T< Type > &v) const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT & operator= (const PxQuatT &p)
Assignment operator.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT & operator*= (const PxQuatT &q)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT & operator+= (const PxQuatT &q)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT & operator-= (const PxQuatT &q)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT & operator*= (const Type s)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT operator* (const PxQuatT &q) const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT operator+ (const PxQuatT &q) const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT operator- () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT operator- (const PxQuatT &q) const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT operator* (Type r) const
Public Attributes
Type x
Type y
Type z
Type w
Detailed Description
template<class Type>
class PxQuatT< Type >
This is a quaternion class. For more information on quaternion mathematics consult a mathematics source on complex numbers.
Constructor & Destructor Documentation
PxQuatT() [1/6]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT< Type >::PxQuatT () inline
Default constructor, does not do any initialization.
PxQuatT() [2/6]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT< Type >::PxQuatT (PxIDENTITY) inline
identity constructor
PxQuatT() [3/6]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT< Type >::PxQuatT (Type r) inline explicit
Constructor from a scalar: sets the real part w to the scalar value, and the imaginary parts (x,y,z) to zero.
PxQuatT() [4/6]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT< Type >::PxQuatT (Type nx, Type ny, Type nz, Type nw) inline
Constructor. Take note of the order of the elements!
PxQuatT() [5/6]
template<class Type> PX_CUDA_CALLABLE PX_INLINE PxQuatT< Type >::PxQuatT (Type angleRadians, const PxVec3T< Type > & unitAxis) inline
Creates from angle-axis representation.
Axis must be normalized!
Angle is in radians!
Unit: Radians
PxQuatT() [6/6]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT< Type >::PxQuatT (const PxQuatT< Type > & v) inline
Copy ctor.
Member Function Documentation
dot()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE Type PxQuatT< Type >::dot (const PxQuatT< Type > & v) const inline
returns the scalar product of this and other.
getAngle() [1/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE Type PxQuatT< Type >::getAngle () const inline
Gets the angle between this quat and the identity quaternion.
Unit: Radians
getAngle() [2/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE Type PxQuatT< Type >::getAngle (const PxQuatT< Type > & q) const inline
Gets the angle between this quat and the argument.
Unit: Radians
getBasisVector0()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T<Type> PxQuatT< Type >::getBasisVector0 () const inline
brief computes rotation of x-axis
getBasisVector1()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T<Type> PxQuatT< Type >::getBasisVector1 () const inline
brief computes rotation of y-axis
getBasisVector2()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T<Type> PxQuatT< Type >::getBasisVector2 () const inline
brief computes rotation of z-axis
getConjugate()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::getConjugate () const inline
Referenced by PxTransformT< float >::getInverse(), PxSeparateSwingTwist(), PxMassProperties::scaleInertia(), and PxTransformT< float >::transformInv().
getImaginaryPart()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T<Type> PxQuatT< Type >::getImaginaryPart () const inline
Referenced by PxLog().
getNormalized()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::getNormalized () const inline
Referenced by PxTransformT< float >::getNormalized(), and PxSeparateSwingTwist().
isFinite()
template<class Type> PX_CUDA_CALLABLE bool PxQuatT< Type >::isFinite () const inline
returns true if all elements are finite (not NAN or INF, etc.)
Referenced by PxMassProperties::getMassSpaceInertia(), PxTransformT< float >::isFinite(), PxTransformT< float >::isValid(), and PxVehicleFrame::isValid().
isIdentity()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxQuatT< Type >::isIdentity () const inline
returns true if quat is identity
isSane()
template<class Type> PX_CUDA_CALLABLE bool PxQuatT< Type >::isSane () const inline
returns true if finite and magnitude is reasonably close to unit to allow for some accumulation of error vs isValid
Referenced by PxTransformT< float >::isSane(), PxVehicleFrame::isValid(), and PxTransformT< float >::PxTransformT().
isUnit()
template<class Type> PX_CUDA_CALLABLE bool PxQuatT< Type >::isUnit () const inline
returns true if finite and magnitude is close to unit
Referenced by PxTransformT< float >::isValid(), PxVehicleFrame::isValid(), PxMeshScale::PxMeshScale(), PxMassProperties::rotateInertia(), and PxMassProperties::scaleInertia().
magnitude()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE Type PxQuatT< Type >::magnitude () const inline
magnitudeSquared()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE Type PxQuatT< Type >::magnitudeSquared () const inline
This is the squared 4D vector length, should be 1 for unit quaternions.
normalize()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE Type PxQuatT< Type >::normalize () inline
maps to the closest unit quaternion.
operator*() [1/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::operator* (const PxQuatT< Type > & q) const inline
quaternion multiplication
operator*() [2/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::operator* (Type r) const inline
operator*=() [1/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT& PxQuatT< Type >::operator*= (const PxQuatT< Type > & q) inline
operator*=() [2/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT& PxQuatT< Type >::operator*= (const Type s) inline
operator+()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::operator+ (const PxQuatT< Type > & q) const inline
quaternion addition
operator+=()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT& PxQuatT< Type >::operator+= (const PxQuatT< Type > & q) inline
operator-() [1/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::operator- () const inline
quaternion subtraction
operator-() [2/2]
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT PxQuatT< Type >::operator- (const PxQuatT< Type > & q) const inline
operator-=()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT& PxQuatT< Type >::operator-= (const PxQuatT< Type > & q) inline
operator=()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuatT& PxQuatT< Type >::operator= (const PxQuatT< Type > & p) inline
Assignment operator.
operator==()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxQuatT< Type >::operator== (const PxQuatT< Type > & q) const inline
returns true if the two quaternions are exactly equal
rotate()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE const PxVec3T<Type> PxQuatT< Type >::rotate (const PxVec3T< Type > & v) const inline
rotates passed vec by this (assumed unitary)
Referenced by PxVehicleRigidBodyState::getLateralSpeed(), PxVehicleRigidBodyState::getLongitudinalSpeed(), PxVehicleRigidBodyState::getVerticalSpeed(), PxTransformT< float >::rotate(), PxTransformT< float >::transform(), and PxTransformT< float >::transformInv().
rotateInv()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE const PxVec3T<Type> PxQuatT< Type >::rotateInv (const PxVec3T< Type > & v) const inline
inverse rotates passed vec by this (assumed unitary)
Referenced by PxTransformT< float >::getInverse(), PxTransformT< float >::rotateInv(), and PxTransformT< float >::transformInv().
toRadiansAndUnitAxis()
template<class Type> PX_CUDA_CALLABLE PX_INLINE void PxQuatT< Type >::toRadiansAndUnitAxis (Type & angle, PxVec3T< Type > & axis) const inline
converts this quaternion to angle-axis representation
Referenced by PxVehicleTransformFrameToFrame().
Member Data Documentation
w
template<class Type> Type PxQuatT< Type >::w
Referenced by PxQuatT< float >::dot(), PxQuatT< float >::operator*(), PxQuatT< float >::operator*=(), PxQuatT< float >::operator+(), PxQuatT< float >::operator+=(), PxQuatT< float >::operator-(), PxQuatT< float >::operator-=(), PxQuatT< float >::operator=(), PxQuatT< float >::operator==(), PxLog(), PxMat33T< float >::PxMat33T(), PxMat44T< float >::PxMat44T(), PxSeparateSwingTwist(), and aos::PxTransformV::PxTransformV().
x
template<class Type> Type PxQuatT< Type >::x
the quaternion elements
Referenced by PxQuatT< float >::dot(), aos::loadTransformA(), aos::loadTransformU(), PxQuatT< float >::operator*(), PxQuatT< float >::operator*=(), PxQuatT< float >::operator+(), PxQuatT< float >::operator+=(), PxQuatT< float >::operator-(), PxQuatT< float >::operator-=(), PxQuatT< float >::operator=(), PxQuatT< float >::operator==(), PxMat33Padded::PxMat33Padded(), PxMat33T< float >::PxMat33T(), PxMat44T< float >::PxMat44T(), PxSeparateSwingTwist(), and aos::PxTransformV::PxTransformV().
y
template<class Type> Type PxQuatT< Type >::y
Referenced by PxQuatT< float >::dot(), PxQuatT< float >::operator*(), PxQuatT< float >::operator*=(), PxQuatT< float >::operator+(), PxQuatT< float >::operator+=(), PxQuatT< float >::operator-(), PxQuatT< float >::operator-=(), PxQuatT< float >::operator=(), PxQuatT< float >::operator==(), PxMat33T< float >::PxMat33T(), PxMat44T< float >::PxMat44T(), and aos::PxTransformV::PxTransformV().
z
template<class Type> Type PxQuatT< Type >::z
Referenced by PxQuatT< float >::dot(), PxQuatT< float >::operator*(), PxQuatT< float >::operator*=(), PxQuatT< float >::operator+(), PxQuatT< float >::operator+=(), PxQuatT< float >::operator-(), PxQuatT< float >::operator-=(), PxQuatT< float >::operator=(), PxQuatT< float >::operator==(), PxMat33T< float >::PxMat33T(), PxMat44T< float >::PxMat44T(), and aos::PxTransformV::PxTransformV().
The documentation for this class was generated from the following files:
Px.h
PxQuat.h
PxMat33.h