PxMat33Padded Class Reference
PxMat33Padded Class Reference
A padded version of PxMat33, to safely load its data using SIMD.
#include <PxSIMDHelpers.h>
Public Member Functions
PX_FORCE_INLINE PxMat33Padded (const PxQuat &q)
PX_FORCE_INLINE ~PxMat33Padded ()
PX_FORCE_INLINE void operator= (const PxMat33 &other)
Public Member Functions inherited from PxMat33T< float >
PX_CUDA_CALLABLE PX_FORCE_INLINE PxMat33T ()
Default constructor.
PX_CUDA_CALLABLE PX_INLINE PxMat33T (PxIDENTITY)
identity constructor
PX_CUDA_CALLABLE PX_INLINE PxMat33T (PxZERO)
zero constructor
PX_CUDA_CALLABLE PxMat33T (const PxVec3T< float > &col0, const PxVec3T< float > &col1, const PxVec3T< float > &col2)
Construct from three base vectors.
PX_CUDA_CALLABLE PX_INLINE PxMat33T (float r)
constructor from a scalar, which generates a multiple of the identity matrix
PX_CUDA_CALLABLE PX_INLINE PxMat33T (float values[])
Construct from Type[9].
PX_CUDA_CALLABLE PX_FORCE_INLINE PxMat33T (const PxQuatT< float > &q)
Construct from a quaternion.
PX_CUDA_CALLABLE PX_INLINE PxMat33T (const PxMat33T &other)
Copy constructor.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxMat33T & operator= (const PxMat33T &other)
Assignment operator.
PX_CUDA_CALLABLE PX_INLINE bool operator== (const PxMat33T &m) const
returns true if the two matrices are exactly equal
PX_CUDA_CALLABLE PX_FORCE_INLINE const PxMat33T getTranspose () const
Get transposed matrix.
PX_CUDA_CALLABLE PX_INLINE const PxMat33T getInverse () const
Get the real inverse.
PX_CUDA_CALLABLE PX_INLINE float getDeterminant () const
Get determinant.
PX_CUDA_CALLABLE PX_INLINE const PxMat33T operator- () const
Unary minus.
PX_CUDA_CALLABLE PX_INLINE const PxMat33T operator- (const PxMat33T &other) const
Subtract.
PX_CUDA_CALLABLE PX_INLINE const PxMat33T operator+ (const PxMat33T &other) const
Add.
PX_CUDA_CALLABLE PX_INLINE const PxMat33T operator* (float scalar) const
Scalar multiplication.
PX_CUDA_CALLABLE PX_INLINE const PxVec3T< float > operator* (const PxVec3T< float > &vec) const
Matrix vector multiplication (returns 'this->transform(vec)')
PX_CUDA_CALLABLE PX_FORCE_INLINE const PxMat33T operator* (const PxMat33T &other) const
Matrix multiplication.
PX_CUDA_CALLABLE PX_INLINE PxMat33T & operator+= (const PxMat33T &other)
Equals-add.
PX_CUDA_CALLABLE PX_INLINE PxMat33T & operator-= (const PxMat33T &other)
Equals-sub.
PX_CUDA_CALLABLE PX_INLINE PxMat33T & operator*= (float scalar)
Equals scalar multiplication.
PX_CUDA_CALLABLE PX_INLINE PxMat33T & operator*= (const PxMat33T &other)
Equals matrix multiplication.
PX_CUDA_CALLABLE PX_FORCE_INLINE float operator() (PxU32 row, PxU32 col) const
Element access, mathematical way!
PX_CUDA_CALLABLE PX_FORCE_INLINE float & operator() (PxU32 row, PxU32 col)
Element access, mathematical way!
PX_CUDA_CALLABLE PX_FORCE_INLINE const PxVec3T< float > transform (const PxVec3T< float > &other) const
Transform vector by matrix, equal to v' = M*v.
PX_CUDA_CALLABLE PX_INLINE const PxVec3T< float > transformTranspose (const PxVec3T< float > &other) const
Transform vector by matrix transpose, v' = M^t*v.
PX_CUDA_CALLABLE PX_FORCE_INLINE const float * front () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T< float > & operator[] (PxU32 num)
PX_CUDA_CALLABLE PX_FORCE_INLINE const PxVec3T< float > & operator[] (PxU32 num) const
Public Attributes
PxU32 padding
Public Attributes inherited from PxMat33T< float >
PxVec3T< float > column0
PxVec3T< float > column1
PxVec3T< float > column2
Additional Inherited Members
Static Public Member Functions inherited from PxMat33T< float >
PX_CUDA_CALLABLE static PX_INLINE const PxMat33T createDiagonal (const PxVec3T< float > &d)
Construct from diagonal, off-diagonals are zero.
PX_CUDA_CALLABLE static PX_INLINE const PxMat33T outer (const PxVec3T< float > &a, const PxVec3T< float > &b)
Computes the outer product of two vectors.
Detailed Description
A padded version of PxMat33, to safely load its data using SIMD.
Constructor & Destructor Documentation
PxMat33Padded()
PX_FORCE_INLINE PxMat33Padded::PxMat33Padded (const PxQuat & q) inline explicit
References physx::aos::QuatGetMat33V(), physx::aos::V3StoreU(), physx::aos::V4LoadU(), physx::aos::V4StoreU(), aos::Vec3V::x, and PxQuatT< Type >::x.
~PxMat33Padded()
PX_FORCE_INLINE PxMat33Padded::~PxMat33Padded () inline
Member Function Documentation
operator=()
PX_FORCE_INLINE void PxMat33Padded::operator= (const PxMat33 & other) inline
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, and PxMat33T< Type >::column2.
Member Data Documentation
padding
PxU32 PxMat33Padded::padding
The documentation for this class was generated from the following file:
PxSIMDHelpers.h