PxMassProperties Class Reference
PxMassProperties Class Reference
Extensions
Utility class to compute and manipulate mass and inertia tensor properties.
#include <PxMassProperties.h>
Public Member Functions
PX_FORCE_INLINE PxMassProperties ()
Default constructor.
PX_FORCE_INLINE PxMassProperties (const PxReal m, const PxMat33 &inertiaT, const PxVec3 &com)
Construct from individual elements.
PxMassProperties (const PxGeometry &geometry)
Compute mass properties based on a provided geometry structure.
PX_FORCE_INLINE PxMassProperties operator* (const PxReal scale) const
Scale mass properties.
PX_FORCE_INLINE void translate (const PxVec3 &t)
Translate the center of mass by a given vector and adjust the inertia tensor accordingly.
Static Public Member Functions
static PX_FORCE_INLINE PxVec3 getMassSpaceInertia (const PxMat33 &inertia, PxQuat &massFrame)
Get the entries of the diagonalized inertia tensor and the corresponding reference rotation.
static PX_FORCE_INLINE PxMat33 translateInertia (const PxMat33 &inertia, const PxReal mass, const PxVec3 &t)
Translate an inertia tensor using the parallel axis theorem.
static PX_FORCE_INLINE PxMat33 rotateInertia (const PxMat33 &inertia, const PxQuat &q)
Rotate an inertia tensor around the center of mass.
static PxMat33 scaleInertia (const PxMat33 &inertia, const PxQuat &scaleRotation, const PxVec3 &scale)
Non-uniform scaling of the inertia tensor.
static PxMassProperties sum (const PxMassProperties *props, const PxTransform *transforms, const PxU32 count)
Sum up individual mass properties.
Public Attributes
PxMat33 inertiaTensor
The inertia tensor of the object.
PxVec3 centerOfMass
The center of mass of the object.
PxReal mass
The mass of the object.
Detailed Description
Utility class to compute and manipulate mass and inertia tensor properties.
In most cases PxRigidBodyExt::updateMassAndInertia(), PxRigidBodyExt::setMassAndUpdateInertia() should be enough to setup the mass properties of a rigid body. This utility class targets users that need to customize the mass properties computation.
Constructor & Destructor Documentation
PxMassProperties() [1/3]
PX_FORCE_INLINE PxMassProperties::PxMassProperties () inline
Default constructor.
PxMassProperties() [2/3]
PX_FORCE_INLINE PxMassProperties::PxMassProperties (const PxReal m, const PxMat33 & inertiaT, const PxVec3 & com) inline
Construct from individual elements.
PxMassProperties() [3/3]
PxMassProperties::PxMassProperties (const PxGeometry & geometry) inline
Compute mass properties based on a provided geometry structure.
This constructor assumes the geometry has a density of 1. Mass and inertia tensor scale linearly with density.
Parameters
[in] geometry The geometry to compute the mass properties for. Supported geometry types are: sphere, box, capsule and convex mesh.
References PxConvexMeshGeometry::convexMesh, PxMat33T< float >::createDiagonal(), PxGeometryType::eBOX, PxGeometryType::eCAPSULE, PxGeometryType::eCONVEXMESH, PxGeometryType::eCUSTOM, PxGeometryType::eSPHERE, PxGeometryType::eTRIANGLEMESH, PxConvexMesh::getMassInformation(), PxTriangleMesh::getMassInformation(), PxGeometry::getType(), PxBoxGeometry::halfExtents, PxCapsuleGeometry::halfHeight, PxVec3T< Type >::multiply(), PX_ASSERT, PxIsFinite(), PxPi, PxSphereGeometry::radius, PxCapsuleGeometry::radius, PxMeshScale::rotation, PxTriangleMeshGeometry::scale, PxConvexMeshGeometry::scale, PxMeshScale::scale, PxMeshScale::transform(), PxTriangleMeshGeometry::triangleMesh, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Member Function Documentation
getMassSpaceInertia()
static PX_FORCE_INLINE PxVec3 PxMassProperties::getMassSpaceInertia (const PxMat33 & inertia, PxQuat & massFrame) inline static
Get the entries of the diagonalized inertia tensor and the corresponding reference rotation.
Parameters
[in] inertia The inertia tensor to diagonalize.
[out] massFrame The frame the diagonalized tensor refers to.
Returns
The entries of the diagonalized inertia tensor.
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, PxQuatT< Type >::isFinite(), PxVec3T< Type >::isFinite(), PX_ASSERT, and PxDiagonalize().
operator*()
PX_FORCE_INLINE PxMassProperties PxMassProperties::operator* (const PxReal scale) const inline
Scale mass properties.
Parameters
[in] scale The linear scaling factor to apply to the mass properties.
Returns
The scaled mass properties.
References PX_ASSERT, and PxIsFinite().
rotateInertia()
static PX_FORCE_INLINE PxMat33 PxMassProperties::rotateInertia (const PxMat33 & inertia, const PxQuat & q) inline static
Rotate an inertia tensor around the center of mass.
Parameters
[in] inertia The inertia tensor to rotate.
[in] q The rotation from the new to the old coordinate frame, i.e. q.rotate(v) transforms the coordinates of vector v from the old to the new coordinate frame.
Returns
The rotated inertia tensor.
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, PxMat33T< Type >::getTranspose(), PxVec3T< Type >::isFinite(), PxQuatT< Type >::isUnit(), and PX_ASSERT.
scaleInertia()
static PxMat33 PxMassProperties::scaleInertia (const PxMat33 & inertia, const PxQuat & scaleRotation, const PxVec3 & scale) inline static
Non-uniform scaling of the inertia tensor.
Parameters
[in] inertia The inertia tensor to scale.
[in] scaleRotation The rotation from the scaling frame to the frame that inertia is expressed in. I.e. scaleRotation.rotate(v) transforms the coordinates of vertex v from inertia's frame to the scaling-axes frame.
[in] scale The scaling factor for each axis (relative to the frame specified with scaleRotation).
Returns
The scaled inertia tensor.
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, PxVec3T< Type >::dot(), PxQuatT< Type >::getConjugate(), PxVec3T< Type >::isFinite(), PxQuatT< Type >::isUnit(), PxVec3T< Type >::multiply(), PX_ASSERT, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
sum()
static PxMassProperties PxMassProperties::sum (const PxMassProperties * props, const PxTransform * transforms, const PxU32 count) inline static
Sum up individual mass properties.
Parameters
[in] props Array of mass properties to sum up.
[in] transforms Reference transforms for each mass properties entry.
[in] count The number of mass properties to sum up.
Returns
The summed up mass properties.
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, inertiaTensor, PxVec3T< Type >::isFinite(), mass, PX_ASSERT, PxIsFinite(), PxZero, and PxTransformT< Type >::transform().
translate()
PX_FORCE_INLINE void PxMassProperties::translate (const PxVec3 & t) inline
Translate the center of mass by a given vector and adjust the inertia tensor accordingly.
Parameters
[in] t The translation vector for the center of mass.
References PxVec3T< Type >::isFinite(), and PX_ASSERT.
translateInertia()
static PX_FORCE_INLINE PxMat33 PxMassProperties::translateInertia (const PxMat33 & inertia, const PxReal mass, const PxVec3 & t) inline static
Translate an inertia tensor using the parallel axis theorem.
Parameters
[in] inertia The inertia tensor to translate.
[in] mass The mass of the object.
[in] t The relative frame to translate the inertia tensor to.
Returns
The translated inertia tensor.
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, PxMat33T< Type >::getTranspose(), PxVec3T< Type >::isFinite(), PX_ASSERT, PxIsFinite(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Member Data Documentation
centerOfMass
PxVec3 PxMassProperties::centerOfMass
The center of mass of the object.
inertiaTensor
PxMat33 PxMassProperties::inertiaTensor
The inertia tensor of the object.
Referenced by sum().
mass
PxReal PxMassProperties::mass
The mass of the object.
Referenced by sum().
The documentation for this class was generated from the following file:
PxMassProperties.h