PxVehiclePVDComponent Class Reference
PxVehiclePVDComponent Class Reference abstract
Vehicle2
#include <PxVehiclePvdComponents.h>
Public Member Functions
PxVehiclePVDComponent ()
virtual ~PxVehiclePVDComponent ()
virtual void getDataForPVDComponent (const PxVehicleAxleDescription *&axleDescription, const PxVehicleRigidBodyParams *&rbodyParams, const PxVehicleRigidBodyState *&rbodyState, const PxVehicleSuspensionStateCalculationParams *&suspStateCalcParams, PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > &brakeResponseParams, const PxVehicleSteerCommandResponseParams *&steerResponseParams, PxVehicleArrayData< PxReal > &brakeResponseStates, PxVehicleArrayData< PxReal > &steerResponseStates, PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, PxVehicleArrayData< const PxVehicleWheelActuationState > &wheelActuationStates, PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, PxVehicleArrayData< const PxVehicleWheelLocalPose > &wheelLocalPoses, PxVehicleArrayData< const PxVehicleRoadGeometryState > &roadGeomStates, PxVehicleArrayData< const PxVehicleSuspensionParams > &suspParams, PxVehicleArrayData< const PxVehicleSuspensionComplianceParams > &suspCompParams, PxVehicleArrayData< const PxVehicleSuspensionForceParams > &suspForceParams, PxVehicleArrayData< const PxVehicleSuspensionState > &suspStates, PxVehicleArrayData< const PxVehicleSuspensionComplianceState > &suspCompStates, PxVehicleArrayData< const PxVehicleSuspensionForce > &suspForces, PxVehicleArrayData< const PxVehicleTireForceParams > &tireForceParams, PxVehicleArrayData< const PxVehicleTireDirectionState > &tireDirectionStates, PxVehicleArrayData< const PxVehicleTireSpeedState > &tireSpeedStates, PxVehicleArrayData< const PxVehicleTireSlipState > &tireSlipStates, PxVehicleArrayData< const PxVehicleTireStickyState > &tireStickyStates, PxVehicleArrayData< const PxVehicleTireGripState > &tireGripStates, PxVehicleArrayData< const PxVehicleTireCamberAngleState > &tireCamberStates, PxVehicleArrayData< const PxVehicleTireForce > &tireForces, PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > &antiRollForceParams, const PxVehicleAntiRollTorque *&antiRollTorque, const PxVehicleCommandState *&commandState, const PxVehicleDirectDriveThrottleCommandResponseParams *&directDriveThrottleResponseParams, const PxVehicleDirectDriveTransmissionCommandState *&directDriveTransmissionState, PxVehicleArrayData< PxReal > &directDrivethrottleResponseState, const PxVehicleClutchCommandResponseParams *&clutchResponseParams, const PxVehicleClutchParams *&clutchParams, const PxVehicleEngineParams *&engineParams, const PxVehicleGearboxParams *&gearboxParams, const PxVehicleAutoboxParams *&autoboxParams, const PxVehicleMultiWheelDriveDifferentialParams *&multiWheelDiffParams, const PxVehicleFourWheelDriveDifferentialParams *&fourWheelDiffParams, const PxVehicleEngineDriveTransmissionCommandState *&engineDriveTransmissionState, const PxVehicleClutchCommandResponseState *&clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState *&engineDriveThrottleResponseState, const PxVehicleEngineState *&engineState, const PxVehicleGearboxState *&gearboxState, const PxVehicleAutoboxState *&autoboxState, const PxVehicleDifferentialState *&diffState, const PxVehicleClutchSlipState *&clutchSlipState, PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > &physxConstraintParams, PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > &physxMaterialFrictionParams, const PxVehiclePhysXActor *&physxActor, const PxVehiclePhysXRoadGeometryQueryParams *&physxRoadGeomQryParams, PxVehicleArrayData< const PxVehiclePhysXRoadGeometryQueryState > &physxRoadGeomStates, PxVehicleArrayData< const PxVehiclePhysXConstraintState > &physxConstraintStates, PxVehiclePvdObjectHandles *&objectHandles)=0
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Private Attributes
bool firstTime
Constructor & Destructor Documentation
PxVehiclePVDComponent()
PxVehiclePVDComponent::PxVehiclePVDComponent () inline
~PxVehiclePVDComponent()
virtual PxVehiclePVDComponent::~PxVehiclePVDComponent () inline virtual
Member Function Documentation
getDataForPVDComponent()
virtual void PxVehiclePVDComponent::getDataForPVDComponent (const PxVehicleAxleDescription *& axleDescription, const PxVehicleRigidBodyParams *& rbodyParams, const PxVehicleRigidBodyState *& rbodyState, const PxVehicleSuspensionStateCalculationParams *& suspStateCalcParams, PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > & brakeResponseParams, const PxVehicleSteerCommandResponseParams *& steerResponseParams, PxVehicleArrayData< PxReal > & brakeResponseStates, PxVehicleArrayData< PxReal > & steerResponseStates, PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, PxVehicleArrayData< const PxVehicleWheelActuationState > & wheelActuationStates, PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, PxVehicleArrayData< const PxVehicleWheelLocalPose > & wheelLocalPoses, PxVehicleArrayData< const PxVehicleRoadGeometryState > & roadGeomStates, PxVehicleArrayData< const PxVehicleSuspensionParams > & suspParams, PxVehicleArrayData< const PxVehicleSuspensionComplianceParams > & suspCompParams, PxVehicleArrayData< const PxVehicleSuspensionForceParams > & suspForceParams, PxVehicleArrayData< const PxVehicleSuspensionState > & suspStates, PxVehicleArrayData< const PxVehicleSuspensionComplianceState > & suspCompStates, PxVehicleArrayData< const PxVehicleSuspensionForce > & suspForces, PxVehicleArrayData< const PxVehicleTireForceParams > & tireForceParams, PxVehicleArrayData< const PxVehicleTireDirectionState > & tireDirectionStates, PxVehicleArrayData< const PxVehicleTireSpeedState > & tireSpeedStates, PxVehicleArrayData< const PxVehicleTireSlipState > & tireSlipStates, PxVehicleArrayData< const PxVehicleTireStickyState > & tireStickyStates, PxVehicleArrayData< const PxVehicleTireGripState > & tireGripStates, PxVehicleArrayData< const PxVehicleTireCamberAngleState > & tireCamberStates, PxVehicleArrayData< const PxVehicleTireForce > & tireForces, PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > & antiRollForceParams, const PxVehicleAntiRollTorque *& antiRollTorque, const PxVehicleCommandState *& commandState, const PxVehicleDirectDriveThrottleCommandResponseParams *& directDriveThrottleResponseParams, const PxVehicleDirectDriveTransmissionCommandState *& directDriveTransmissionState, PxVehicleArrayData< PxReal > & directDrivethrottleResponseState, const PxVehicleClutchCommandResponseParams *& clutchResponseParams, const PxVehicleClutchParams *& clutchParams, const PxVehicleEngineParams *& engineParams, const PxVehicleGearboxParams *& gearboxParams, const PxVehicleAutoboxParams *& autoboxParams, const PxVehicleMultiWheelDriveDifferentialParams *& multiWheelDiffParams, const PxVehicleFourWheelDriveDifferentialParams *& fourWheelDiffParams, const PxVehicleEngineDriveTransmissionCommandState *& engineDriveTransmissionState, const PxVehicleClutchCommandResponseState *& clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState *& engineDriveThrottleResponseState, const PxVehicleEngineState *& engineState, const PxVehicleGearboxState *& gearboxState, const PxVehicleAutoboxState *& autoboxState, const PxVehicleDifferentialState *& diffState, const PxVehicleClutchSlipState *& clutchSlipState, PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > & physxConstraintParams, PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > & physxMaterialFrictionParams, const PxVehiclePhysXActor *& physxActor, const PxVehiclePhysXRoadGeometryQueryParams *& physxRoadGeomQryParams, PxVehicleArrayData< const PxVehiclePhysXRoadGeometryQueryState > & physxRoadGeomStates, PxVehicleArrayData< const PxVehiclePhysXConstraintState > & physxConstraintStates, PxVehiclePvdObjectHandles *& objectHandles) pure virtual
update()
virtual bool PxVehiclePVDComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PxVehicleSimulationContext::attributeHandles, PxVehicleSimulationContext::omniWriter, PX_UNUSED(), PxVehiclePvdAntiRollsRegister(), PxVehiclePvdAntiRollsWrite(), PxVehiclePvdCommandResponseRegister(), PxVehiclePvdCommandResponseWrite(), PxVehiclePvdDirectDrivetrainRegister(), PxVehiclePvdDirectDrivetrainWrite(), PxVehiclePvdEngineDrivetrainRegister(), PxVehiclePvdEngineDrivetrainWrite(), PxVehiclePvdPhysXRigidActorRegister(), PxVehiclePvdPhysXRigidActorWrite(), PxVehiclePvdPhysXWheelAttachmentRegister(), PxVehiclePvdPhysXWheelAttachmentWrite(), PxVehiclePvdRigidBodyRegister(), PxVehiclePvdRigidBodyWrite(), PxVehiclePvdSuspensionStateCalculationParamsRegister(), PxVehiclePvdSuspensionStateCalculationParamsWrite(), PxVehiclePvdWheelAttachmentsRegister(), PxVehiclePvdWheelAttachmentsWrite(), VEHICLE_ARRAY_DATA, VEHICLE_FLOAT_ARRAY_DATA, and VEHICLE_SIZED_ARRAY_DATA.
Member Data Documentation
firstTime
bool PxVehiclePVDComponent::firstTime private
The documentation for this class was generated from the following file:
PxVehiclePvdComponents.h