PxStack< PxAllocator > Class Template Reference
PxStack< PxAllocator > Class Template Reference
Foundation
#include <PxSortInternals.h>
Public Member Functions
PxStack (int32_t *memory, uint32_t capacity, const PxAllocator &inAllocator)
~PxStack ()
void grow ()
PX_INLINE void push (int32_t start, int32_t end)
PX_INLINE void pop (int32_t &start, int32_t &end)
PX_INLINE bool empty ()
Private Attributes
PxAllocator mAllocator
uint32_t mSize
uint32_t mCapacity
int32_t * mMemory
bool mRealloc
Constructor & Destructor Documentation
PxStack()
template<class PxAllocator> PxStack< PxAllocator >::PxStack (int32_t * memory, uint32_t capacity, const PxAllocator & inAllocator) inline
~PxStack()
template<class PxAllocator> PxStack< PxAllocator >::~PxStack () inline
References PxAllocator::deallocate().
Member Function Documentation
empty()
template<class PxAllocator> PX_INLINE bool PxStack< PxAllocator >::empty () inline
Referenced by PxSort().
grow()
template<class PxAllocator> void PxStack< PxAllocator >::grow () inline
References PxAllocator::allocate(), PxAllocator::deallocate(), and intrinsics::memCopy().
pop()
template<class PxAllocator> PX_INLINE void PxStack< PxAllocator >::pop (int32_t & start, int32_t & end) inline
References PX_ASSERT.
Referenced by PxSort().
push()
template<class PxAllocator> PX_INLINE void PxStack< PxAllocator >::push (int32_t start, int32_t end) inline
Referenced by PxSort().
Member Data Documentation
mAllocator
template<class PxAllocator> PxAllocator PxStack< PxAllocator >::mAllocator private
mCapacity
template<class PxAllocator> uint32_t PxStack< PxAllocator >::mCapacity private
mMemory
template<class PxAllocator> int32_t* PxStack< PxAllocator >::mMemory private
mRealloc
template<class PxAllocator> bool PxStack< PxAllocator >::mRealloc private
mSize
template<class PxAllocator> uint32_t PxStack< PxAllocator >::mSize private
The documentation for this class was generated from the following file:
PxSortInternals.h