PxVehicleConstraintConnector Class Reference
PxVehicleConstraintConnector Class Reference
Vehicle2
#include <PxVehiclePhysXConstraintStates.h>
Public Member Functions
PxVehicleConstraintConnector ()
PxVehicleConstraintConnector (PxVehiclePhysXConstraintState *vehicleConstraintState)
~PxVehicleConstraintConnector ()
void setConstraintState (PxVehiclePhysXConstraintState *constraintState)
virtual void * prepareData ()
Pre-simulation data preparation when the constraint is marked dirty, this function is called at the start of the simulation step for the SDK to copy the constraint data block.
virtual const void * getConstantBlock () const
Obtain the pointer to the constraint's constant data.
virtual PxConstraintSolverPrep getPrep () const
Obtain the shader function pointer used to prep rows for this constraint.
virtual void onConstraintRelease ()
Constraint release callback.
virtual bool updatePvdProperties (physx::pvdsdk::PvdDataStream &pvdConnection, const PxConstraint *c, PxPvdUpdateType::Enum updateType) const
this function is called by the SDK to update PVD's view of it
virtual void updateOmniPvdProperties () const
this function is called by the SDK to update OmniPVD's view of it
virtual void onComShift (PxU32 actor)
Center-of-mass shift callback.
virtual void onOriginShift (const PxVec3 &shift)
Origin shift callback.
virtual void * getExternalReference (PxU32 &typeID)
Fetches external data for a constraint.
virtual PxBase * getSerializable ()
Obtain a reference to a PxBase interface if the constraint has one.
Public Member Functions inherited from PxConstraintConnector
virtual void connectToConstraint (PxConstraint *)
Let the connector know it has been connected to a constraint.
virtual ~PxConstraintConnector ()
virtual destructor
Private Attributes
PxVehiclePhysXConstraintState * mVehicleConstraintState
Constructor & Destructor Documentation
PxVehicleConstraintConnector() [1/2]
PxVehicleConstraintConnector::PxVehicleConstraintConnector () inline
PxVehicleConstraintConnector() [2/2]
PxVehicleConstraintConnector::PxVehicleConstraintConnector (PxVehiclePhysXConstraintState * vehicleConstraintState) inline
~PxVehicleConstraintConnector()
PxVehicleConstraintConnector::~PxVehicleConstraintConnector () inline
Member Function Documentation
getConstantBlock()
virtual const void* PxVehicleConstraintConnector::getConstantBlock () const inline virtual
Obtain the pointer to the constraint's constant data.
Implements PxConstraintConnector.
getExternalReference()
virtual void* PxVehicleConstraintConnector::getExternalReference (PxU32 & typeID) inline virtual
Fetches external data for a constraint.
This function is used by the SDK to acquire a reference to the owner of a constraint and a unique owner type ID. This information will be passed on when a breakable constraint breaks or when PxConstraint::getExternalReference() is called.
Parameters
[out] typeID Unique type identifier of the external object. The value 0xffffffff is reserved and should not be used. Furthermore, if the PhysX extensions library is used, some other IDs are reserved already (see PxConstraintExtIDs)
Returns
Reference to the external object which owns the constraint.
See also
PxConstraintInfo PxSimulationEventCallback.onConstraintBreak()
Implements PxConstraintConnector.
References PxConstraintExtIDs::eVEHICLE_JOINT.
getPrep()
virtual PxConstraintSolverPrep PxVehicleConstraintConnector::getPrep () const inline virtual
Obtain the shader function pointer used to prep rows for this constraint.
Implements PxConstraintConnector.
References vehicleConstraintSolverPrep().
getSerializable()
virtual PxBase* PxVehicleConstraintConnector::getSerializable () inline virtual
Obtain a reference to a PxBase interface if the constraint has one.
If the constraint does not implement the PxBase interface, it should return NULL.
Implements PxConstraintConnector.
onComShift()
virtual void PxVehicleConstraintConnector::onComShift (PxU32 actor) inline virtual
Center-of-mass shift callback.
This function is called by the SDK when the CoM of one of the actors is moved. Since the API specifies constraint positions relative to actors, and the constraint shader functions are supplied with coordinates relative to bodies, some synchronization is usually required when the application moves an object's center of mass.
Implements PxConstraintConnector.
References PX_UNUSED().
onConstraintRelease()
virtual void PxVehicleConstraintConnector::onConstraintRelease () inline virtual
Constraint release callback.
When the SDK deletes a PxConstraint object this function is called by the SDK. In general custom constraints should not be deleted directly by applications: rather, the constraint should respond to a release() request by calling PxConstraint::release(), then wait for this call to release its own resources.
This function is also called when a PxConstraint object is deleted on cleanup due to destruction of the PxPhysics object.
Implements PxConstraintConnector.
onOriginShift()
virtual void PxVehicleConstraintConnector::onOriginShift (const PxVec3 & shift) inline virtual
Origin shift callback.
This function is called by the SDK when the scene origin gets shifted and allows to adjust custom data which contains world space transforms.
Note
If the adjustments affect constraint shader data, it is necessary to call PxConstraint::markDirty() to make sure that the data gets synced at the beginning of the next simulation step.
Parameters
[in] shift Translation vector the origin is shifted by.
See also
PxScene.shiftOrigin()
Implements PxConstraintConnector.
References PX_UNUSED().
prepareData()
virtual void* PxVehicleConstraintConnector::prepareData () inline virtual
Pre-simulation data preparation when the constraint is marked dirty, this function is called at the start of the simulation step for the SDK to copy the constraint data block.
Implements PxConstraintConnector.
setConstraintState()
void PxVehicleConstraintConnector::setConstraintState (PxVehiclePhysXConstraintState * constraintState) inline
updateOmniPvdProperties()
virtual void PxVehicleConstraintConnector::updateOmniPvdProperties () const inline virtual
this function is called by the SDK to update OmniPVD's view of it
Implements PxConstraintConnector.
updatePvdProperties()
virtual bool PxVehicleConstraintConnector::updatePvdProperties (physx::pvdsdk::PvdDataStream & pvdConnection, const PxConstraint * c, PxPvdUpdateType::Enum updateType) const inline virtual
this function is called by the SDK to update PVD's view of it
Implements PxConstraintConnector.
References PX_UNUSED().
Member Data Documentation
mVehicleConstraintState
PxVehiclePhysXConstraintState* PxVehicleConstraintConnector::mVehicleConstraintState private
The documentation for this class was generated from the following file:
PxVehiclePhysXConstraintStates.h