aos::PxTransformV Class Reference
aos::PxTransformV Class Reference
#include <PxVecTransform.h>
Public Member Functions
PX_FORCE_INLINE PxTransformV (const PxTransform &orientation)
PX_FORCE_INLINE PxTransformV (const Vec3VArg p0=V3Zero(), const QuatVArg q0=QuatIdentity())
PX_FORCE_INLINE PxTransformV operator* (const PxTransformV &x) const
PX_FORCE_INLINE PxTransformV getInverse () const
PX_FORCE_INLINE void normalize ()
PX_FORCE_INLINE void Invalidate ()
PX_FORCE_INLINE Vec3V transform (const Vec3VArg input) const
PX_FORCE_INLINE Vec3V transformInv (const Vec3VArg input) const
PX_FORCE_INLINE Vec3V rotate (const Vec3VArg input) const
PX_FORCE_INLINE Vec3V rotateInv (const Vec3VArg input) const
PX_FORCE_INLINE PxTransformV transform (const PxTransformV &src) const
Transform transform to parent (returns compound transform: first src, then *this)
PX_FORCE_INLINE bool isValid () const
returns true if finite and q is a unit quaternion
PX_FORCE_INLINE bool isSane () const
returns true if finite and quat magnitude is reasonably close to unit to allow for some accumulation of error vs isValid
PX_FORCE_INLINE bool isFinite () const
returns true if all elems are finite (not NAN or INF, etc.)
PX_FORCE_INLINE PxTransformV transformInv (const PxTransformV &src) const
Transform transform from parent (returns compound transform: first src, then this->inverse)
Static Public Member Functions
static PX_FORCE_INLINE PxTransformV createIdentity ()
Public Attributes
QuatV q
Vec3V p
Constructor & Destructor Documentation
PxTransformV() [1/2]
PX_FORCE_INLINE aos::PxTransformV::PxTransformV (const PxTransform & orientation) inline
References PxTransformT< Type >::p, PxTransformT< Type >::q, physx::aos::QuatVLoadXYZW(), physx::aos::V3LoadU(), PxQuatT< Type >::w, PxQuatT< Type >::x, PxQuatT< Type >::y, and PxQuatT< Type >::z.
PxTransformV() [2/2]
PX_FORCE_INLINE aos::PxTransformV::PxTransformV (const Vec3VArg p0 = V3Zero(), const QuatVArg q0 = QuatIdentity()) inline
References physx::aos::isSaneQuatV(), and PX_ASSERT.
Member Function Documentation
createIdentity()
static PX_FORCE_INLINE PxTransformV aos::PxTransformV::createIdentity () inline static
References physx::aos::V3Zero().
getInverse()
PX_FORCE_INLINE PxTransformV aos::PxTransformV::getInverse () const inline
References isFinite(), PX_ASSERT, physx::aos::QuatConjugate(), physx::aos::QuatRotateInv(), and physx::aos::V3Neg().
Invalidate()
PX_FORCE_INLINE void aos::PxTransformV::Invalidate () inline
References physx::aos::FMax(), physx::aos::QuatIdentity(), and physx::aos::V3Splat().
isFinite()
PX_FORCE_INLINE bool aos::PxTransformV::isFinite () const inline
returns true if all elems are finite (not NAN or INF, etc.)
References physx::aos::isFiniteQuatV(), and physx::aos::isFiniteVec3V().
isSane()
PX_FORCE_INLINE bool aos::PxTransformV::isSane () const inline
returns true if finite and quat magnitude is reasonably close to unit to allow for some accumulation of error vs isValid
References isFinite(), and physx::aos::isSaneQuatV().
Referenced by operator*(), transform(), and transformInv().
isValid()
PX_FORCE_INLINE bool aos::PxTransformV::isValid () const inline
returns true if finite and q is a unit quaternion
References physx::aos::isFiniteQuatV(), physx::aos::isFiniteVec3V(), and physx::aos::isValidQuatV().
normalize()
PX_FORCE_INLINE void aos::PxTransformV::normalize () inline
References physx::aos::QuatIdentity(), and physx::aos::V3Zero().
operator*()
PX_FORCE_INLINE PxTransformV aos::PxTransformV::operator* (const PxTransformV & x) const inline
References isSane(), and PX_ASSERT.
rotate()
PX_FORCE_INLINE Vec3V aos::PxTransformV::rotate (const Vec3VArg input) const inline
References isFinite(), PX_ASSERT, and physx::aos::QuatRotate().
rotateInv()
PX_FORCE_INLINE Vec3V aos::PxTransformV::rotateInv (const Vec3VArg input) const inline
References isFinite(), PX_ASSERT, and physx::aos::QuatRotateInv().
transform() [1/2]
PX_FORCE_INLINE Vec3V aos::PxTransformV::transform (const Vec3VArg input) const inline
References isFinite(), PX_ASSERT, and aos::QuatTransform().
transform() [2/2]
PX_FORCE_INLINE PxTransformV aos::PxTransformV::transform (const PxTransformV & src) const inline
Transform transform to parent (returns compound transform: first src, then *this)
References isSane(), p, PX_ASSERT, q, physx::aos::QuatMul(), physx::aos::QuatRotate(), and physx::aos::V3Add().
transformInv() [1/2]
PX_FORCE_INLINE Vec3V aos::PxTransformV::transformInv (const Vec3VArg input) const inline
References isFinite(), PX_ASSERT, physx::aos::QuatRotateInv(), and physx::aos::V3Sub().
transformInv() [2/2]
PX_FORCE_INLINE PxTransformV aos::PxTransformV::transformInv (const PxTransformV & src) const inline
Transform transform from parent (returns compound transform: first src, then this->inverse)
References isFinite(), isSane(), p, PX_ASSERT, q, physx::aos::QuatConjugate(), physx::aos::QuatMul(), physx::aos::QuatRotate(), and physx::aos::V3Sub().
Member Data Documentation
p
Vec3V aos::PxTransformV::p
Referenced by aos::PxMatTransformV::PxMatTransformV(), transform(), and transformInv().
q
QuatV aos::PxTransformV::q
Referenced by aos::PxMatTransformV::PxMatTransformV(), transform(), and transformInv().
The documentation for this class was generated from the following file:
PxVecTransform.h