PxBaseMaterial Class Reference
PxBaseMaterial Class Reference
Physics
Base material class.
#include <PxBaseMaterial.h>
Public Member Functions
PX_INLINE PxBaseMaterial (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxBaseMaterial (PxBaseFlags baseFlags)
virtual ~PxBaseMaterial ()
virtual bool isKindOf (const char *name) const
Returns whether a given type name matches with the type of this instance.
Public Member Functions inherited from PxRefCounted
virtual void release ()=0
Decrements the reference count of the object and releases it if the new reference count is zero.
virtual PxU32 getReferenceCount () const =0
Returns the reference count of the object.
virtual void acquireReference ()=0
Acquires a counted reference to this object.
Public Member Functions inherited from PxBase
virtual const char * getConcreteTypeName () const =0
Returns string name of dynamic type.
template<class T >
T * is ()
template<class T >
const T * is () const
PX_FORCE_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_FORCE_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_FORCE_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_FORCE_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Public Attributes
void * userData
user can assign this to whatever, usually to create a 1:1 relationship with a user object.
Additional Inherited Members
Protected Member Functions inherited from PxRefCounted
virtual void onRefCountZero ()
PX_INLINE PxRefCounted (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxRefCounted (PxBaseFlags baseFlags)
virtual ~PxRefCounted ()
Protected Member Functions inherited from PxBase
PX_INLINE PxBase (PxType concreteType, PxBaseFlags baseFlags)
Constructor setting concrete type and base flags.
PX_INLINE PxBase (PxBaseFlags baseFlags)
Deserialization constructor setting base flags.
virtual ~PxBase ()
Destructor.
template<class T >
bool typeMatch () const
Protected Attributes inherited from PxBase
PxType mConcreteType
PxBaseFlags mBaseFlags
PxU32 mBuiltInRefCount
Detailed Description
Base material class.
See also
PxPhysics.createMaterial PxPhysics.createFEMClothMaterial PxPhysics.createFEMSoftBodyMaterial PxPhysics.createFLIPMaterial PxPhysics.createMPMMaterial PxPhysics.createPBDMaterial
Constructor & Destructor Documentation
PxBaseMaterial() [1/2]
PX_INLINE PxBaseMaterial::PxBaseMaterial (PxType concreteType, PxBaseFlags baseFlags) inline
PxBaseMaterial() [2/2]
PX_INLINE PxBaseMaterial::PxBaseMaterial (PxBaseFlags baseFlags) inline
~PxBaseMaterial()
virtual PxBaseMaterial::~PxBaseMaterial () inline virtual
Member Function Documentation
isKindOf()
virtual bool PxBaseMaterial::isKindOf (const char * superClass) const inline virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented from PxRefCounted.
Reimplemented in PxMPMMaterial, PxMaterial, PxCustomMaterial, PxPBDMaterial, PxParticleMaterial, PxFEMMaterial, PxFEMClothMaterial, PxFEMSoftBodyMaterial, and PxFLIPMaterial.
References PxRefCounted::isKindOf().
Referenced by PxFEMMaterial::isKindOf(), PxParticleMaterial::isKindOf(), and PxMaterial::isKindOf().
Member Data Documentation
userData
void* PxBaseMaterial::userData
user can assign this to whatever, usually to create a 1:1 relationship with a user object.
The documentation for this class was generated from the following file:
PxBaseMaterial.h