physx::PxSListT< Alloc > Class Template Reference
physx::PxSListT< Alloc > Class Template Reference
#include <PxSList.h>
Public Member Functions
PxSListT (const Alloc &alloc=Alloc())
~PxSListT ()
void push (PxSListEntry &entry)
PxSListEntry * pop ()
PxSListEntry * flush ()
Private Attributes
PxSListImpl * mImpl
Constructor & Destructor Documentation
PxSListT()
template<typename Alloc = PxReflectionAllocator<PxSListImpl>> physx::PxSListT< Alloc >::PxSListT (const Alloc & alloc = Alloc()) inline
References physx::PxSListImpl::getSize(), physx::PxSListT< Alloc >::mImpl, PX_ASSERT, PX_PLACEMENT_NEW, and PX_SLIST_ALIGNMENT.
~PxSListT()
template<typename Alloc = PxReflectionAllocator<PxSListImpl>> physx::PxSListT< Alloc >::~PxSListT () inline
References physx::PxSListT< Alloc >::mImpl, and physx::PxSListImpl::~PxSListImpl().
Member Function Documentation
flush()
template<typename Alloc = PxReflectionAllocator<PxSListImpl>> PxSListEntry* physx::PxSListT< Alloc >::flush () inline
References physx::PxSListImpl::flush(), and physx::PxSListT< Alloc >::mImpl.
pop()
template<typename Alloc = PxReflectionAllocator<PxSListImpl>> PxSListEntry* physx::PxSListT< Alloc >::pop () inline
References physx::PxSListT< Alloc >::mImpl, and physx::PxSListImpl::pop().
push()
template<typename Alloc = PxReflectionAllocator<PxSListImpl>> void physx::PxSListT< Alloc >::push (PxSListEntry & entry) inline
References physx::PxSListT< Alloc >::mImpl, and physx::PxSListImpl::push().
Member Data Documentation
mImpl
template<typename Alloc = PxReflectionAllocator<PxSListImpl>> PxSListImpl* physx::PxSListT< Alloc >::mImpl private
Referenced by physx::PxSListT< Alloc >::flush(), physx::PxSListT< Alloc >::pop(), physx::PxSListT< Alloc >::push(), physx::PxSListT< Alloc >::PxSListT(), and physx::PxSListT< Alloc >::~PxSListT().
The documentation for this class was generated from the following file:
PxSList.h