ExtGpu::PxKernelWrangler Class Reference
ExtGpu::PxKernelWrangler Class Reference
#include <PxKernelManager.h>
Public Member Functions
PxKernelWrangler (PxCudaContextManager &cudaContextManager, PxErrorCallback &errorCallback, const char **funcNames, uint16_t numFuncs)
~PxKernelWrangler ()
PX_FORCE_INLINE CUfunction getCuFunction (uint16_t funcIndex) const
const char * getCuFunctionName (uint16_t funcIndex) const
PX_FORCE_INLINE bool hadError () const
Public Member Functions inherited from PxUserAllocated
PX_INLINE void * operator new (size_t, void *address)
PX_INLINE void operator delete (void *, void *)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete (void *ptr, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete [] (void *ptr, Alloc alloc, const char *fileName, int line)
PX_INLINE void operator delete (void *ptr)
PX_INLINE void operator delete [] (void *ptr)
Static Public Member Functions
static void const *const * getImages ()
static int getNumImages ()
Protected Attributes
bool mError
PxArray< CUfunction > mCuFunctions
PxArray< CUmodule > mCuModules
PxCudaContextManager & mCudaContextManager
PxCudaContext * mCudaContext
PxErrorCallback & mErrorCallback
Constructor & Destructor Documentation
PxKernelWrangler()
ExtGpu::PxKernelWrangler::PxKernelWrangler (PxCudaContextManager & cudaContextManager, PxErrorCallback & errorCallback, const char ** funcNames, uint16_t numFuncs)
~PxKernelWrangler()
ExtGpu::PxKernelWrangler::~PxKernelWrangler ()
Member Function Documentation
getCuFunction()
PX_FORCE_INLINE CUfunction ExtGpu::PxKernelWrangler::getCuFunction (uint16_t funcIndex) const inline
Referenced by ExtGpu::_launch().
getCuFunctionName()
const char* ExtGpu::PxKernelWrangler::getCuFunctionName (uint16_t funcIndex) const
Referenced by ExtGpu::_testLaunch(), ExtGpu::outputKernelLaunchDebugInfo(), and ExtGpu::outputKernelLaunchError().
getImages()
static void const* const* ExtGpu::PxKernelWrangler::getImages () static
getNumImages()
static int ExtGpu::PxKernelWrangler::getNumImages () static
hadError()
PX_FORCE_INLINE bool ExtGpu::PxKernelWrangler::hadError () const inline
Member Data Documentation
mCudaContext
PxCudaContext* ExtGpu::PxKernelWrangler::mCudaContext protected
mCudaContextManager
PxCudaContextManager& ExtGpu::PxKernelWrangler::mCudaContextManager protected
mCuFunctions
PxArray<CUfunction> ExtGpu::PxKernelWrangler::mCuFunctions protected
mCuModules
PxArray<CUmodule> ExtGpu::PxKernelWrangler::mCuModules protected
mError
bool ExtGpu::PxKernelWrangler::mError protected
mErrorCallback
PxErrorCallback& ExtGpu::PxKernelWrangler::mErrorCallback protected
The documentation for this class was generated from the following file:
PxKernelManager.h