PxReflectionAllocator< T > Class Template Reference
PxReflectionAllocator< T > Class Template Reference
#include <PxAllocator.h>
Public Member Functions
PxReflectionAllocator (const PxEMPTY)
PxReflectionAllocator (const char *=0)
PxReflectionAllocator (const PxReflectionAllocator &)
PX_FORCE_INLINE void * allocate (size_t size, const char *filename, int line)
PX_FORCE_INLINE void deallocate (void *ptr)
Static Private Member Functions
static const char * getName ()
Detailed Description
template<typename T>
class PxReflectionAllocator< T >
Allocator used to access the global PxAllocatorCallback instance using a static name derived from T.
Constructor & Destructor Documentation
PxReflectionAllocator() [1/3]
template<typename T > PxReflectionAllocator< T >::PxReflectionAllocator (const PxEMPTY) inline
PxReflectionAllocator() [2/3]
template<typename T > PxReflectionAllocator< T >::PxReflectionAllocator (const char * = 0) inline
PxReflectionAllocator() [3/3]
template<typename T > PxReflectionAllocator< T >::PxReflectionAllocator (const PxReflectionAllocator< T > &) inline
Member Function Documentation
allocate()
template<typename T > PX_FORCE_INLINE void* PxReflectionAllocator< T >::allocate (size_t size, const char * filename, int line) inline
References PxGetBroadcastAllocator().
deallocate()
template<typename T > PX_FORCE_INLINE void PxReflectionAllocator< T >::deallocate (void * ptr) inline
References PxGetBroadcastAllocator().
getName()
template<typename T > static const char* PxReflectionAllocator< T >::getName () inline static private
References PxGetFoundation().
The documentation for this class was generated from the following file:
PxAllocator.h