PxBitMapBase< PxAllocator > Class Template Reference
PxBitMapBase< PxAllocator > Class Template Reference
#include <PxBitMap.h>
Classes
struct AND
class Iterator
struct OR
class PxCircularIterator
class PxLoopIterator
struct XOR
Public Member Functions
PxBitMapBase (const PxEMPTY)
PX_INLINE PxBitMapBase (const PxAllocator &allocator)
PX_INLINE PxBitMapBase ()
PX_INLINE ~PxBitMapBase ()
PX_INLINE void release ()
PX_INLINE PxAllocator & getAllocator ()
PX_INLINE void growAndSet (PxU32 index)
PX_INLINE void growAndReset (PxU32 index)
PX_INLINE PxIntBool boundedTest (PxU32 index) const
PX_INLINE void boundedReset (PxU32 index)
PX_INLINE void set (PxU32 index)
PX_INLINE void reset (PxU32 index)
PX_INLINE PxIntBool test (PxU32 index) const
PX_INLINE PxU32 getNibbleFast (PxU32 nibIndex) const
PX_INLINE void andNibbleFast (PxU32 nibIndex, PxU32 mask)
PX_INLINE void orNibbleFast (PxU32 nibIndex, PxU32 mask)
void clear ()
void resizeAndClear (PxU32 newBitCount)
void setEmpty ()
void setWords (PxU32 *map, PxU32 wordCount)
void resize (PxU32 newBitCount, bool value=false)
PxU32 size () const
void copy (const PxBitMapBase &a)
PX_INLINE PxU32 count () const
PX_INLINE PxU32 count (PxU32 start, PxU32 length) const
PxU32 findLast () const
returns 0 if no bits set (!!!)
template<class Combiner , class _ >
PX_INLINE void combineInPlace (const PxBitMapBase< _ > &b)
template<class Combiner , class _1 , class _2 >
PX_INLINE void combine (const PxBitMapBase< _1 > &a, const PxBitMapBase< _2 > &b)
PX_FORCE_INLINE const PxU32 * getWords () const
PX_FORCE_INLINE PxU32 * getWords ()
PX_FORCE_INLINE PxU32 getWordCount () const
PX_FORCE_INLINE PxU32 isInUserMemory () const
Public Member Functions inherited from PxUserAllocated
PX_INLINE void * operator new (size_t, void *address)
PX_INLINE void operator delete (void *, void *)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete (void *ptr, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete [] (void *ptr, Alloc alloc, const char *fileName, int line)
PX_INLINE void operator delete (void *ptr)
PX_INLINE void operator delete [] (void *ptr)
Protected Member Functions
void extend (PxU32 size)
void extendUninitialized (PxU32 size)
template<class Combiner >
void combine1 (const PxU32 *words, PxU32 length)
template<class Combiner >
void combine2 (const PxU32 *words1, PxU32 length1, const PxU32 *words2, PxU32 length2)
Protected Attributes
PxU32 * mMap
PxU32 mWordCount
PxAllocator mAllocator
PxU8 mPadding [3]
Friends
class Iterator
Detailed Description
template<class PxAllocator>
class PxBitMapBase< PxAllocator >
Hold a bitmap with operations to set,reset or test given bit.
We inhibit copy to prevent unintentional copies. If a copy is desired copy() should be used or alternatively a copy constructor implemented.
Constructor & Destructor Documentation
PxBitMapBase() [1/3]
template<class PxAllocator> PxBitMapBase< PxAllocator >::PxBitMapBase (const PxEMPTY) inline
References PX_SIGN_BITMASK.
PxBitMapBase() [2/3]
template<class PxAllocator> PX_INLINE PxBitMapBase< PxAllocator >::PxBitMapBase (const PxAllocator & allocator) inline
PxBitMapBase() [3/3]
template<class PxAllocator> PX_INLINE PxBitMapBase< PxAllocator >::PxBitMapBase () inline
~PxBitMapBase()
template<class PxAllocator> PX_INLINE PxBitMapBase< PxAllocator >::~PxBitMapBase () inline
Member Function Documentation
andNibbleFast()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::andNibbleFast (PxU32 nibIndex, PxU32 mask) inline
References PX_ASSERT.
boundedReset()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::boundedReset (PxU32 index) inline
boundedTest()
template<class PxAllocator> PX_INLINE PxIntBool PxBitMapBase< PxAllocator >::boundedTest (PxU32 index) const inline
References PxIntFalse.
clear()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::clear () inline
References PxMemSet().
combine()
template<class PxAllocator> template<class Combiner , class _1 , class _2 > PX_INLINE void PxBitMapBase< PxAllocator >::combine (const PxBitMapBase< _1 > & a, const PxBitMapBase< _2 > & b) inline
References PxBitMapBase< PxAllocator >::getWordCount(), and PxBitMapBase< PxAllocator >::mMap.
combine1()
template<class PxAllocator> template<class Combiner > void PxBitMapBase< PxAllocator >::combine1 (const PxU32 * words, PxU32 length) inline protected
References PxMin().
combine2()
template<class PxAllocator> template<class Combiner > void PxBitMapBase< PxAllocator >::combine2 (const PxU32 * words1, PxU32 length1, const PxU32 * words2, PxU32 length2) inline protected
References PxMax(), and PxMin().
combineInPlace()
template<class PxAllocator> template<class Combiner , class _ > PX_INLINE void PxBitMapBase< PxAllocator >::combineInPlace (const PxBitMapBase< _ > & b) inline
References PxBitMapBase< PxAllocator >::getWordCount(), and PxBitMapBase< PxAllocator >::mMap.
copy()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::copy (const PxBitMapBase< PxAllocator > & a) inline
References PxBitMapBase< PxAllocator >::getWordCount(), PxBitMapBase< PxAllocator >::mMap, PxMemCopy(), and PxMemSet().
count() [1/2]
template<class PxAllocator> PX_INLINE PxU32 PxBitMapBase< PxAllocator >::count () const inline
References PxBitCount().
count() [2/2]
template<class PxAllocator> PX_INLINE PxU32 PxBitMapBase< PxAllocator >::count (PxU32 start, PxU32 length) const inline
References PxMin().
extend()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::extend (PxU32 size) inline protected
References PxAllocator::allocate(), PxAllocator::deallocate(), PxMemCopy(), and PxMemSet().
extendUninitialized()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::extendUninitialized (PxU32 size) inline protected
References PxAllocator::allocate(), and PxAllocator::deallocate().
findLast()
template<class PxAllocator> PxU32 PxBitMapBase< PxAllocator >::findLast () const inline
returns 0 if no bits set (!!!)
References PxHighestSetBit().
getAllocator()
template<class PxAllocator> PX_INLINE PxAllocator& PxBitMapBase< PxAllocator >::getAllocator () inline
getNibbleFast()
template<class PxAllocator> PX_INLINE PxU32 PxBitMapBase< PxAllocator >::getNibbleFast (PxU32 nibIndex) const inline
References PX_ASSERT.
getWordCount()
template<class PxAllocator> PX_FORCE_INLINE PxU32 PxBitMapBase< PxAllocator >::getWordCount () const inline
References PX_SIGN_BITMASK.
Referenced by PxBitMapBase< PxAllocator >::combine(), PxBitMapBase< PxAllocator >::combineInPlace(), and PxBitMapBase< PxAllocator >::copy().
getWords() [1/2]
template<class PxAllocator> PX_FORCE_INLINE const PxU32* PxBitMapBase< PxAllocator >::getWords () const inline
getWords() [2/2]
template<class PxAllocator> PX_FORCE_INLINE PxU32* PxBitMapBase< PxAllocator >::getWords () inline
growAndReset()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::growAndReset (PxU32 index) inline
growAndSet()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::growAndSet (PxU32 index) inline
isInUserMemory()
template<class PxAllocator> PX_FORCE_INLINE PxU32 PxBitMapBase< PxAllocator >::isInUserMemory () const inline
References PX_SIGN_BITMASK.
orNibbleFast()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::orNibbleFast (PxU32 nibIndex, PxU32 mask) inline
References PX_ASSERT.
release()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::release (void) inline
reset()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::reset (PxU32 index) inline
References PX_ASSERT.
resize()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::resize (PxU32 newBitCount, bool value = false) inline
References PX_ASSERT, and PX_UNUSED().
resizeAndClear()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::resizeAndClear (PxU32 newBitCount) inline
References PxMemSet().
set()
template<class PxAllocator> PX_INLINE void PxBitMapBase< PxAllocator >::set (PxU32 index) inline
References PX_ASSERT.
setEmpty()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::setEmpty () inline
setWords()
template<class PxAllocator> void PxBitMapBase< PxAllocator >::setWords (PxU32 * map, PxU32 wordCount) inline
References PX_SIGN_BITMASK.
size()
template<class PxAllocator> PxU32 PxBitMapBase< PxAllocator >::size () const inline
test()
template<class PxAllocator> PX_INLINE PxIntBool PxBitMapBase< PxAllocator >::test (PxU32 index) const inline
References PX_ASSERT.
Friends And Related Function Documentation
Iterator
template<class PxAllocator> friend class Iterator friend
Member Data Documentation
mAllocator
template<class PxAllocator> PxAllocator PxBitMapBase< PxAllocator >::mAllocator protected
mMap
template<class PxAllocator> PxU32* PxBitMapBase< PxAllocator >::mMap protected
Referenced by PxBitMapBase< PxAllocator >::combine(), PxBitMapBase< PxAllocator >::combineInPlace(), and PxBitMapBase< PxAllocator >::copy().
mPadding
template<class PxAllocator> PxU8 PxBitMapBase< PxAllocator >::mPadding[3] protected
mWordCount
template<class PxAllocator> PxU32 PxBitMapBase< PxAllocator >::mWordCount protected
The documentation for this class was generated from the following file:
PxBitMap.h