PxRefCounted Class Reference
PxRefCounted Class Reference abstract
Common
Base class for ref-counted objects.
#include <PxBase.h>
Public Member Functions
virtual void release ()=0
Decrements the reference count of the object and releases it if the new reference count is zero.
virtual PxU32 getReferenceCount () const =0
Returns the reference count of the object.
virtual void acquireReference ()=0
Acquires a counted reference to this object.
Public Member Functions inherited from PxBase
virtual const char * getConcreteTypeName () const =0
Returns string name of dynamic type.
template<class T >
T * is ()
template<class T >
const T * is () const
PX_FORCE_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_FORCE_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_FORCE_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_FORCE_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Protected Member Functions
virtual void onRefCountZero ()
PX_INLINE PxRefCounted (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxRefCounted (PxBaseFlags baseFlags)
virtual ~PxRefCounted ()
virtual bool isKindOf (const char *name) const
Returns whether a given type name matches with the type of this instance.
Protected Member Functions inherited from PxBase
PX_INLINE PxBase (PxType concreteType, PxBaseFlags baseFlags)
Constructor setting concrete type and base flags.
PX_INLINE PxBase (PxBaseFlags baseFlags)
Deserialization constructor setting base flags.
virtual ~PxBase ()
Destructor.
template<class T >
bool typeMatch () const
Additional Inherited Members
Protected Attributes inherited from PxBase
PxType mConcreteType
PxBaseFlags mBaseFlags
PxU32 mBuiltInRefCount
Detailed Description
Base class for ref-counted objects.
Constructor & Destructor Documentation
PxRefCounted() [1/2]
PX_INLINE PxRefCounted::PxRefCounted (PxType concreteType, PxBaseFlags baseFlags) inline protected
PxRefCounted() [2/2]
PX_INLINE PxRefCounted::PxRefCounted (PxBaseFlags baseFlags) inline protected
~PxRefCounted()
virtual PxRefCounted::~PxRefCounted () inline protected virtual
Member Function Documentation
acquireReference()
virtual void PxRefCounted::acquireReference () pure virtual
Acquires a counted reference to this object.
This method increases the reference count of the object by 1. Decrement the reference count by calling release()
getReferenceCount()
virtual PxU32 PxRefCounted::getReferenceCount () const pure virtual
Returns the reference count of the object.
At creation, the reference count of the object is 1. Every other object referencing this object increments the count by 1. When the reference count reaches 0, and only then, the object gets destroyed automatically.
Returns
the current reference count.
isKindOf()
virtual bool PxRefCounted::isKindOf (const char * superClass) const inline protected virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented from PxBase.
Reimplemented in PxShape, PxMPMMaterial, PxMaterial, PxBVH34TriangleMesh, PxBVH33TriangleMesh, PxTriangleMesh, PxSoftBodyMesh, PxHeightField, PxCustomMaterial, PxPBDMaterial, PxTetrahedronMesh, PxConvexMesh, PxParticleMaterial, PxFEMMaterial, PxFEMClothMaterial, PxFEMSoftBodyMaterial, PxSoftBodyAuxData, PxFLIPMaterial, and PxBaseMaterial.
References PxBase::isKindOf().
Referenced by PxBaseMaterial::isKindOf(), PxSoftBodyAuxData::isKindOf(), PxFEMClothMaterial::isKindOf(), PxConvexMesh::isKindOf(), PxTetrahedronMesh::isKindOf(), PxHeightField::isKindOf(), PxSoftBodyMesh::isKindOf(), PxTriangleMesh::isKindOf(), and PxShape::isKindOf().
onRefCountZero()
virtual void PxRefCounted::onRefCountZero () inline protected virtual
release()
virtual void PxRefCounted::release () pure virtual
Decrements the reference count of the object and releases it if the new reference count is zero.
Implements PxBase.
Implemented in PxSoftBodyMesh, PxTriangleMesh, PxTetrahedronMesh, PxShape, PxConvexMesh, PxHeightField, and PxSoftBodyAuxData.
The documentation for this class was generated from the following file:
PxBase.h