PxRenderOutput Class Reference
PxRenderOutput Class Reference
#include <PxRenderOutput.h>
Public Types
enum Primitive {
POINTS, LINES, LINESTRIP, TRIANGLES,
TRIANGLESTRIP
}
Public Member Functions
PxRenderOutput (PxRenderBuffer &buffer)
PX_INLINE PxRenderOutput & operator<< (Primitive prim)
PX_INLINE PxRenderOutput & operator<< (PxU32 color)
PX_INLINE PxRenderOutput & operator<< (const PxMat44 &transform)
PX_INLINE PxRenderOutput & operator<< (const PxTransform &t)
PX_INLINE PxRenderOutput & operator<< (const PxVec3 &vertex)
PX_INLINE PxDebugLine * reserveSegments (PxU32 nbSegments)
PX_INLINE PxDebugPoint * reservePoints (PxU32 nbSegments)
PX_INLINE void outputSegment (const PxVec3 &v0, const PxVec3 &v1)
PX_INLINE PxRenderOutput & outputCapsule (PxF32 radius, PxF32 halfHeight, const PxMat44 &absPose)
Private Member Functions
PxRenderOutput & operator= (const PxRenderOutput &)
Private Attributes
Primitive mPrim
PxU32 mColor
PxVec3 mVertex0
PxVec3 mVertex1
PxU32 mVertexCount
PxMat44 mTransform
PxRenderBuffer & mBuffer
Detailed Description
Output stream to fill RenderBuffer
Member Enumeration Documentation
Primitive
enum PxRenderOutput::Primitive
Enumerator
POINTS
LINES
LINESTRIP
TRIANGLES
TRIANGLESTRIP
Constructor & Destructor Documentation
PxRenderOutput()
PxRenderOutput::PxRenderOutput (PxRenderBuffer & buffer) inline
Member Function Documentation
operator<<() [1/5]
PX_INLINE PxRenderOutput & PxRenderOutput::operator<< (Primitive prim)
operator<<() [2/5]
PX_INLINE PxRenderOutput & PxRenderOutput::operator<< (PxU32 color)
operator<<() [3/5]
PX_INLINE PxRenderOutput & PxRenderOutput::operator<< (const PxMat44 & transform)
operator<<() [4/5]
PX_INLINE PxRenderOutput & PxRenderOutput::operator<< (const PxTransform & t)
operator<<() [5/5]
PX_INLINE PxRenderOutput & PxRenderOutput::operator<< (const PxVec3 & vertex)
operator=()
PxRenderOutput& PxRenderOutput::operator= (const PxRenderOutput &) private
outputCapsule()
PX_INLINE PxRenderOutput & PxRenderOutput::outputCapsule (PxF32 radius, PxF32 halfHeight, const PxMat44 & absPose)
References PxMat44T< Type >::column0, PxMat44T< Type >::column1, PxMat44T< Type >::column2, PxMat44T< Type >::column3, outputSegment(), PxPi, PxSwap(), PxTwoPi, and PxMat44T< Type >::rotate().
outputSegment()
PX_INLINE void PxRenderOutput::outputSegment (const PxVec3 & v0, const PxVec3 & v1)
References PxDebugLine::color0, PxDebugLine::color1, PxDebugLine::pos0, and PxDebugLine::pos1.
Referenced by outputCapsule().
reservePoints()
PX_INLINE PxDebugPoint * PxRenderOutput::reservePoints (PxU32 nbSegments)
reserveSegments()
PX_INLINE PxDebugLine * PxRenderOutput::reserveSegments (PxU32 nbSegments)
Member Data Documentation
mBuffer
PxRenderBuffer& PxRenderOutput::mBuffer private
mColor
PxU32 PxRenderOutput::mColor private
mPrim
Primitive PxRenderOutput::mPrim private
mTransform
PxMat44 PxRenderOutput::mTransform private
mVertex0
PxVec3 PxRenderOutput::mVertex0 private
mVertex1
PxVec3 PxRenderOutput::mVertex1 private
mVertexCount
PxU32 PxRenderOutput::mVertexCount private
The documentation for this class was generated from the following file:
PxRenderOutput.h