PxThreadT< Alloc > Class Template Reference
PxThreadT< Alloc > Class Template Reference
#include <PxThread.h>
Public Types
typedef PxThreadImpl::Id Id
Public Member Functions
PxThreadT (const Alloc &alloc=Alloc())
PxThreadT (PxThreadImpl::ExecuteFn fn, void *arg, const char *name, const Alloc &alloc=Alloc())
virtual ~PxThreadT ()
void start (PxU32 stackSize=PxThreadImpl::getDefaultStackSize())
void kill ()
virtual void execute (void)
void signalQuit ()
bool waitForQuit ()
bool quitIsSignalled ()
void quit ()
PxU32 setAffinityMask (PxU32 mask)
void setPriority (PxThreadPriority::Enum prio)
void setName (const char *name)
Public Member Functions inherited from PxUserAllocated
PX_INLINE void * operator new (size_t, void *address)
PX_INLINE void operator delete (void *, void *)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete (void *ptr, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete [] (void *ptr, Alloc alloc, const char *fileName, int line)
PX_INLINE void operator delete (void *ptr)
PX_INLINE void operator delete [] (void *ptr)
Public Member Functions inherited from PxRunnable
PxRunnable ()
virtual ~PxRunnable ()
Static Public Member Functions
static PxThreadPriority::Enum getPriority (PxThreadImpl::Id threadId)
static void sleep (PxU32 ms)
static void yield ()
static void yieldProcesor ()
static PxU32 getDefaultStackSize ()
static PxThreadImpl::Id getId ()
static PxU32 getNbPhysicalCores ()
Private Attributes
class PxThreadImpl * mImpl
Detailed Description
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>>
class PxThreadT< Alloc >
Thread abstraction API
Member Typedef Documentation
Id
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> typedef PxThreadImpl::Id PxThreadT< Alloc >::Id
Constructor & Destructor Documentation
PxThreadT() [1/2]
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> PxThreadT< Alloc >::PxThreadT (const Alloc & alloc = Alloc()) inline
Construct (but do not start) the thread object. Executes in the context of the spawning thread
References PxThreadImpl::getSize(), and PX_PLACEMENT_NEW.
PxThreadT() [2/2]
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> PxThreadT< Alloc >::PxThreadT (PxThreadImpl::ExecuteFn fn, void * arg, const char * name, const Alloc & alloc = Alloc()) inline
Construct and start the the thread, passing the given arg to the given fn. (pthread style)
References PxThreadImpl::getSize(), and PX_PLACEMENT_NEW.
~PxThreadT()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> virtual PxThreadT< Alloc >::~PxThreadT () inline virtual
Deallocate all resources associated with the thread. Should be called in the context of the spawning thread.
Member Function Documentation
execute()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> virtual void PxThreadT< Alloc >::execute (void) inline virtual
The virtual execute() method is the user defined function that will run in the new thread. Called in the context of the spawned thread.
Reimplemented from PxRunnable.
getDefaultStackSize()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static PxU32 PxThreadT< Alloc >::getDefaultStackSize () inline static
References PxThreadImpl::getDefaultStackSize().
getId()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static PxThreadImpl::Id PxThreadT< Alloc >::getId () inline static
References PxThreadImpl::getId().
getNbPhysicalCores()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static PxU32 PxThreadT< Alloc >::getNbPhysicalCores () inline static
References PxThreadImpl::getNbPhysicalCores().
getPriority()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static PxThreadPriority::Enum PxThreadT< Alloc >::getPriority (PxThreadImpl::Id threadId) inline static
References PxThreadImpl::getPriority().
kill()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> void PxThreadT< Alloc >::kill () inline
Violently kill the current thread. Blunt instrument, not recommended since it can leave all kinds of things unreleased (stack, memory, mutexes...) Should be called in the context of the spawning thread.
quit()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> void PxThreadT< Alloc >::quit () inline
Cleanly shut down this thread. Called in the context of the spawned thread.
quitIsSignalled()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> bool PxThreadT< Alloc >::quitIsSignalled () inline
check whether the thread is signalled to quit. Called in the context of the spawned thread.
setAffinityMask()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> PxU32 PxThreadT< Alloc >::setAffinityMask (PxU32 mask) inline
setName()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> void PxThreadT< Alloc >::setName (const char * name) inline
set the thread's name
setPriority()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> void PxThreadT< Alloc >::setPriority (PxThreadPriority::Enum prio) inline
Set thread priority.
signalQuit()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> void PxThreadT< Alloc >::signalQuit () inline
stop the thread. Signals the spawned thread that it should stop, so the thread should check regularly
sleep()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static void PxThreadT< Alloc >::sleep (PxU32 ms) inline static
Put the current thread to sleep for the given number of milliseconds
References PxThreadImpl::sleep().
start()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> void PxThreadT< Alloc >::start (PxU32 stackSize = PxThreadImpl::getDefaultStackSize()) inline
start the thread running. Called in the context of the spawning thread.
waitForQuit()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> bool PxThreadT< Alloc >::waitForQuit () inline
Wait for a thread to stop. Should be called in the context of the spawning thread. Returns false if the thread has not been started.
yield()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static void PxThreadT< Alloc >::yield () inline static
Yield the current thread's slot on the CPU
References PxThreadImpl::yield().
yieldProcesor()
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> static void PxThreadT< Alloc >::yieldProcesor () inline static
Inform the processor that we're in a busy wait to give it a chance to do something clever yield() yields the thread, while yieldProcessor() aims to yield the processor
References PxThreadImpl::yieldProcessor().
Member Data Documentation
mImpl
template<typename Alloc = PxReflectionAllocator<PxThreadImpl>> class PxThreadImpl* PxThreadT< Alloc >::mImpl private
The documentation for this class was generated from the following file:
PxThread.h