PxVehicleContext Class Reference
PxVehicleContext Class Reference
Common parameters and settings used for the vehicle simulation.
#include <PxVehicleSDK.h>
Public Member Functions
PX_INLINE PxVehicleContext ()
Constructor sets to default.
PX_INLINE void setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool isValid () const
Check if the settings descriptor is valid.
PX_INLINE void computeSideAxis ()
Compute the side-axis from the up- and forward-axis.
Public Attributes
PxVec3 upAxis
The axis denoting the up direction for vehicles.
PxVec3 forwardAxis
The axis denoting the forward direction for vehicles.
PxVec3 sideAxis
The axis denoting the side direction for vehicles.
PxVehicleUpdateMode::Enum updateMode
Apply vehicle simulation results as acceleration or velocity modification.
PxF32 pointRejectAngleThresholdCosine
Cosine of threshold angle for rejecting sweep hits.
PxF32 normalRejectAngleThresholdCosine
Cosine of threshold angle for rejecting sweep hits.
PxF32 maxHitActorAcceleration
Maximum acceleration experienced by PxRigidDynamic instances that are found to be in contact with a wheel.
Detailed Description
Common parameters and settings used for the vehicle simulation.
To be passed into PxVehicleUpdates(), for example.
See also
PxVehicleUpdates()
Constructor & Destructor Documentation
PxVehicleContext()
PX_INLINE PxVehicleContext::PxVehicleContext ()
Constructor sets to default.
Referenced by setToDefault().
Member Function Documentation
computeSideAxis()
PX_INLINE void PxVehicleContext::computeSideAxis ()
Compute the side-axis from the up- and forward-axis.
References PxVec3T< Type >::cross(), forwardAxis, sideAxis, and upAxis.
isValid()
PX_INLINE bool PxVehicleContext::isValid () const
Check if the settings descriptor is valid.
Returns
True if the current settings are valid.
References PxVec3T< Type >::cross(), forwardAxis, PxVec3T< Type >::isNormalized(), maxHitActorAcceleration, normalRejectAngleThresholdCosine, pointRejectAngleThresholdCosine, sideAxis, and upAxis.
setToDefault()
PX_INLINE void PxVehicleContext::setToDefault ()
(re)sets the structure to the default.
References PxVehicleContext().
Member Data Documentation
forwardAxis
PxVec3 PxVehicleContext::forwardAxis
The axis denoting the forward direction for vehicles.
Range: unit length vector
Default: PxVec3(0,0,1)
See also
PxVehicleSetBasisVectors()
Referenced by computeSideAxis(), and isValid().
maxHitActorAcceleration
PxF32 PxVehicleContext::maxHitActorAcceleration
Maximum acceleration experienced by PxRigidDynamic instances that are found to be in contact with a wheel.
See PxVehicleSetMaxHitActorAcceleration() for details.
Range: [0, PX_MAX_REAL]
Default: PX_MAX_REAL
See also
PxVehicleSetMaxHitActorAcceleration()
Referenced by isValid().
normalRejectAngleThresholdCosine
PxF32 PxVehicleContext::normalRejectAngleThresholdCosine
Cosine of threshold angle for rejecting sweep hits.
See PxVehicleSetSweepHitRejectionAngles() for details.
Range: (1, -1)
Default: 0.707f (cosine of 45 degrees)
See also
PxVehicleSetSweepHitRejectionAngles()
Referenced by isValid().
pointRejectAngleThresholdCosine
PxF32 PxVehicleContext::pointRejectAngleThresholdCosine
Cosine of threshold angle for rejecting sweep hits.
See PxVehicleSetSweepHitRejectionAngles() for details.
Range: (1, -1)
Default: 0.707f (cosine of 45 degrees)
See also
PxVehicleSetSweepHitRejectionAngles()
Referenced by isValid().
sideAxis
PxVec3 PxVehicleContext::sideAxis
The axis denoting the side direction for vehicles.
Has to be the cross product of the up- and forward-axis. The method computeSideAxis() can be used to do that computation for you.
Range: unit length vector
Default: PxVec3(1,0,0)
See also
PxVehicleSetBasisVectors(), computeSideAxis()
Referenced by computeSideAxis(), and isValid().
upAxis
PxVec3 PxVehicleContext::upAxis
The axis denoting the up direction for vehicles.
Range: unit length vector
Default: PxVec3(0,1,0)
See also
PxVehicleSetBasisVectors()
Referenced by computeSideAxis(), and isValid().
updateMode
PxVehicleUpdateMode::Enum PxVehicleContext::updateMode
Apply vehicle simulation results as acceleration or velocity modification.
See PxVehicleSetUpdateMode() for details.
Default: eVELOCITY_CHANGE
See also
PxVehicleSetUpdateMode()
The documentation for this class was generated from the following file:
PxVehicleSDK.h