PxParticleMaterial Class Reference
PxParticleMaterial Class Reference abstract
Physics
Material class to represent a set of particle material properties.
#include <PxParticleMaterial.h>
Public Member Functions
virtual void setFriction (PxReal friction)=0
Sets friction.
virtual PxReal getFriction () const =0
Retrieves the friction value.
virtual void setDamping (PxReal damping)=0
Sets velocity damping term.
virtual PxReal getDamping () const =0
Retrieves the velocity damping term.
virtual void setAdhesion (PxReal adhesion)=0
Sets adhesion term.
virtual PxReal getAdhesion () const =0
Retrieves the adhesion term.
virtual void setGravityScale (PxReal scale)=0
Sets gravity scale term.
virtual PxReal getGravityScale () const =0
Retrieves the gravity scale term.
virtual void setAdhesionRadiusScale (PxReal scale)=0
Sets material adhesion radius scale. This is multiplied by the particle rest offset to compute the fall-off distance at which point adhesion ceases to operate.
virtual PxReal getAdhesionRadiusScale () const =0
Retrieves the adhesion radius scale.
Public Member Functions inherited from PxBaseMaterial
PX_INLINE PxBaseMaterial (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxBaseMaterial (PxBaseFlags baseFlags)
virtual ~PxBaseMaterial ()
Public Member Functions inherited from PxRefCounted
virtual void release ()=0
Decrements the reference count of the object and releases it if the new reference count is zero.
virtual PxU32 getReferenceCount () const =0
Returns the reference count of the object.
virtual void acquireReference ()=0
Acquires a counted reference to this object.
Public Member Functions inherited from PxBase
virtual const char * getConcreteTypeName () const =0
Returns string name of dynamic type.
template<class T >
T * is ()
template<class T >
const T * is () const
PX_FORCE_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_FORCE_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_FORCE_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_FORCE_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Protected Member Functions
PX_INLINE PxParticleMaterial (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxParticleMaterial (PxBaseFlags baseFlags)
virtual ~PxParticleMaterial ()
virtual bool isKindOf (const char *name) const
Returns whether a given type name matches with the type of this instance.
Protected Member Functions inherited from PxRefCounted
virtual void onRefCountZero ()
PX_INLINE PxRefCounted (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxRefCounted (PxBaseFlags baseFlags)
virtual ~PxRefCounted ()
Protected Member Functions inherited from PxBase
PX_INLINE PxBase (PxType concreteType, PxBaseFlags baseFlags)
Constructor setting concrete type and base flags.
PX_INLINE PxBase (PxBaseFlags baseFlags)
Deserialization constructor setting base flags.
virtual ~PxBase ()
Destructor.
template<class T >
bool typeMatch () const
Additional Inherited Members
Public Attributes inherited from PxBaseMaterial
void * userData
user can assign this to whatever, usually to create a 1:1 relationship with a user object.
Protected Attributes inherited from PxBase
PxType mConcreteType
PxBaseFlags mBaseFlags
PxU32 mBuiltInRefCount
Detailed Description
Material class to represent a set of particle material properties.
See also
PxPhysics.createPBDMaterial, PxPhysics.createFLIPMaterial, PxPhysics.createMPMMaterial
Constructor & Destructor Documentation
PxParticleMaterial() [1/2]
PX_INLINE PxParticleMaterial::PxParticleMaterial (PxType concreteType, PxBaseFlags baseFlags) inline protected
PxParticleMaterial() [2/2]
PX_INLINE PxParticleMaterial::PxParticleMaterial (PxBaseFlags baseFlags) inline protected
~PxParticleMaterial()
virtual PxParticleMaterial::~PxParticleMaterial () inline protected virtual
Member Function Documentation
getAdhesion()
virtual PxReal PxParticleMaterial::getAdhesion () const pure virtual
Retrieves the adhesion term.
Returns
The adhesion term.
See also
setAdhesion()
getAdhesionRadiusScale()
virtual PxReal PxParticleMaterial::getAdhesionRadiusScale () const pure virtual
Retrieves the adhesion radius scale.
Returns
The adhesion radius scale.
See also
setAdhesionRadiusScale()
getDamping()
virtual PxReal PxParticleMaterial::getDamping () const pure virtual
Retrieves the velocity damping term.
Returns
The velocity damping term.
See also
setDamping()
getFriction()
virtual PxReal PxParticleMaterial::getFriction () const pure virtual
Retrieves the friction value.
Returns
The friction value.
See also
setFriction()
getGravityScale()
virtual PxReal PxParticleMaterial::getGravityScale () const pure virtual
Retrieves the gravity scale term.
Returns
The gravity scale term.
See also
setAdhesion()
isKindOf()
virtual bool PxParticleMaterial::isKindOf (const char * superClass) const inline protected virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented from PxBaseMaterial.
Reimplemented in PxMPMMaterial, PxCustomMaterial, PxPBDMaterial, and PxFLIPMaterial.
References PxBaseMaterial::isKindOf().
Referenced by PxFLIPMaterial::isKindOf(), PxPBDMaterial::isKindOf(), PxCustomMaterial::isKindOf(), and PxMPMMaterial::isKindOf().
setAdhesion()
virtual void PxParticleMaterial::setAdhesion (PxReal adhesion) pure virtual
Sets adhesion term.
Parameters
[in] adhesion adhesion coefficient.
See also
getAdhesion
setAdhesionRadiusScale()
virtual void PxParticleMaterial::setAdhesionRadiusScale (PxReal scale) pure virtual
Sets material adhesion radius scale. This is multiplied by the particle rest offset to compute the fall-off distance at which point adhesion ceases to operate.
Parameters
[in] scale Material adhesion radius scale.
See also
getAdhesionRadiusScale
setDamping()
virtual void PxParticleMaterial::setDamping (PxReal damping) pure virtual
Sets velocity damping term.
Parameters
[in] damping Velocity damping term.
See also
getDamping
setFriction()
virtual void PxParticleMaterial::setFriction (PxReal friction) pure virtual
Sets friction.
Parameters
[in] friction Friction. Range: [0, PX_MAX_F32)
See also
getFriction()
setGravityScale()
virtual void PxParticleMaterial::setGravityScale (PxReal scale) pure virtual
Sets gravity scale term.
Parameters
[in] scale gravity scale coefficient.
See also
getAdhesion
The documentation for this class was generated from the following file:
PxParticleMaterial.h