PxAllocator Class Reference
PxAllocator Class Reference
#include <PxAllocator.h>
Public Member Functions
PX_FORCE_INLINE PxAllocator (const char *=NULL)
PX_FORCE_INLINE void * allocate (size_t size, const char *file, int line)
PX_FORCE_INLINE void deallocate (void *ptr)
Detailed Description
Allocator used to access the global PxAllocatorCallback instance without providing additional information.
Constructor & Destructor Documentation
PxAllocator()
PX_FORCE_INLINE PxAllocator::PxAllocator (const char * = NULL) inline
Member Function Documentation
allocate()
PX_FORCE_INLINE void* PxAllocator::allocate (size_t size, const char * file, int line) inline
References PxGetBroadcastAllocator().
Referenced by PxBitMapBase< PxAllocator >::extend(), PxBitMapBase< PxAllocator >::extendUninitialized(), PxStack< PxAllocator >::grow(), and PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::reserveInternal().
deallocate()
PX_FORCE_INLINE void PxAllocator::deallocate (void * ptr) inline
References PxGetBroadcastAllocator().
Referenced by PxBitMapBase< PxAllocator >::extend(), PxBitMapBase< PxAllocator >::extendUninitialized(), PxStack< PxAllocator >::grow(), PxUserAllocated::operator delete(), PxUserAllocated::operator delete [](), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::reserveInternal(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::~PxHashBase(), and PxStack< PxAllocator >::~PxStack().
The documentation for this class was generated from the following file:
PxAllocator.h