PxUserAllocated Class Reference
PxUserAllocated Class Reference
#include <PxUserAllocated.h>
Public Member Functions
PX_INLINE void * operator new (size_t, void *address)
PX_INLINE void operator delete (void *, void *)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void * operator new [] (size_t size, size_t, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete (void *ptr, Alloc alloc, const char *fileName, int line)
template<typename Alloc >
PX_INLINE void operator delete [] (void *ptr, Alloc alloc, const char *fileName, int line)
PX_INLINE void operator delete (void *ptr)
PX_INLINE void operator delete [] (void *ptr)
Detailed Description
Provides new and delete using a UserAllocator. Guarantees that 'delete x;' uses the UserAllocator too.
Member Function Documentation
operator delete() [1/3]
PX_INLINE void PxUserAllocated::operator delete (void * , void *) inline
operator delete() [2/3]
template<typename Alloc > PX_INLINE void PxUserAllocated::operator delete (void * ptr, Alloc alloc, const char * fileName, int line) inline
References PX_UNUSED().
operator delete() [3/3]
PX_INLINE void PxUserAllocated::operator delete (void * ptr) inline
References PxAllocator::deallocate().
operator delete []() [1/2]
template<typename Alloc > PX_INLINE void PxUserAllocated::operator delete [] (void * ptr, Alloc alloc, const char * fileName, int line) inline
References PX_UNUSED().
operator delete []() [2/2]
PX_INLINE void PxUserAllocated::operator delete [] (void * ptr) inline
References PxAllocator::deallocate().
operator new() [1/3]
PX_INLINE void* PxUserAllocated::operator new (size_t , void * address) inline
operator new() [2/3]
template<typename Alloc > PX_INLINE void* PxUserAllocated::operator new (size_t size, Alloc alloc, const char * fileName, int line) inline
operator new() [3/3]
template<typename Alloc > PX_INLINE void* PxUserAllocated::operator new (size_t size, size_t , Alloc alloc, const char * fileName, int line) inline
operator new []() [1/2]
template<typename Alloc > PX_INLINE void* PxUserAllocated::operator new [] (size_t size, Alloc alloc, const char * fileName, int line) inline
operator new []() [2/2]
template<typename Alloc > PX_INLINE void* PxUserAllocated::operator new [] (size_t size, size_t , Alloc alloc, const char * fileName, int line) inline
The documentation for this class was generated from the following file:
PxUserAllocated.h