PxVehiclePhysXActorEndComponent Class Reference
PxVehiclePhysXActorEndComponent Class Reference abstract
Vehicle2
Work items at the end of an update step for a PhysX actor based vehicle.
#include <PxVehiclePhysXActorComponents.h>
Public Member Functions
PxVehiclePhysXActorEndComponent ()
virtual ~PxVehiclePhysXActorEndComponent ()
virtual void getDataForPhysXActorEndComponent (const PxVehicleAxleDescription *&axleDescription, const PxVehicleRigidBodyState *&rigidBodyState, PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, PxVehicleArrayData< const PxTransform > &wheelShapeLocalPoses, PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, PxVehicleArrayData< const PxVehicleWheelLocalPose > &wheelLocalPoses, const PxVehicleGearboxState *&gearState, PxVehiclePhysXActor *&physxActor)=0
Provide vehicle data items for this component.
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Detailed Description
Work items at the end of an update step for a PhysX actor based vehicle.
Includes:
Writing vehicle internal state to the PhysX actor.
Keeping the vehicle awake if certain criteria are met.
Constructor & Destructor Documentation
PxVehiclePhysXActorEndComponent()
PxVehiclePhysXActorEndComponent::PxVehiclePhysXActorEndComponent () inline
~PxVehiclePhysXActorEndComponent()
virtual PxVehiclePhysXActorEndComponent::~PxVehiclePhysXActorEndComponent () inline virtual
Member Function Documentation
getDataForPhysXActorEndComponent()
virtual void PxVehiclePhysXActorEndComponent::getDataForPhysXActorEndComponent (const PxVehicleAxleDescription *& axleDescription, const PxVehicleRigidBodyState *& rigidBodyState, PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, PxVehicleArrayData< const PxTransform > & wheelShapeLocalPoses, PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, PxVehicleArrayData< const PxVehicleWheelLocalPose > & wheelLocalPoses, const PxVehicleGearboxState *& gearState, PxVehiclePhysXActor *& physxActor) pure virtual
Provide vehicle data items for this component.
Parameters
[out] axleDescription identifies the wheels on each axle.
[out] rigidBodyState is the state of the rigid body used by the Vehicle SDK.
[out] wheelParams describes the radius, mass etc. of the wheels.
[out] wheelShapeLocalPoses are the local poses in the wheel's frame to apply to the PxShape instances that represent the wheel
[out] wheelRigidBody1dStates describes the angular speed of the wheels.
[out] wheelLocalPoses describes the local poses of the wheels in the rigid body frame.
[out] gearState The gear state. Can be set to NULL if the vehicle does not have gears.
[out] physxActor is the PxRigidBody instance associated with the vehicle.
update()
virtual bool PxVehiclePhysXActorEndComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PxVehicleSimulationContextType::ePHYSX, PxVehicleSimulationContext::getType(), PxVehicleAxleDescription::nbWheels, PxVehiclePhysXSimulationContext::physxActorUpdateMode, PxVehiclePhysXSimulationContext::physxActorWakeCounterResetValue, PxVehiclePhysXSimulationContext::physxActorWakeCounterThreshold, PX_ALWAYS_ASSERT, PX_PROFILE_ZONE, PX_UNUSED(), PxVehiclePhysxActorKeepAwakeCheck(), PxVehicleWriteRigidBodyStateToPhysXActor(), PxVehicleWriteWheelLocalPoseToPhysXWheelShape(), PxVehiclePhysXActor::rigidBody, PxVehicleAxleDescription::wheelIdsInAxleOrder, and PxVehiclePhysXActor::wheelShapes.
The documentation for this class was generated from the following file:
PxVehiclePhysXActorComponents.h