PxVehicleEngineDrivetrainComponent Class Reference
PxVehicleEngineDrivetrainComponent Class Reference abstract
Vehicle2
Forward integrate the angular speed of each wheel and of the engine, accounting for the state of the clutch, gearbox and differential.
#include <PxVehicleDrivetrainComponents.h>
Public Member Functions
PxVehicleEngineDrivetrainComponent ()
virtual ~PxVehicleEngineDrivetrainComponent ()
virtual void getDataForEngineDrivetrainComponent (const PxVehicleAxleDescription *&axleDescription, PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, const PxVehicleEngineParams *&engineParams, const PxVehicleClutchParams *&clutchParams, const PxVehicleGearboxParams *&gearboxParams, PxVehicleArrayData< const PxReal > &brakeResponseStates, PxVehicleArrayData< const PxVehicleWheelActuationState > &actuationStates, PxVehicleArrayData< const PxVehicleTireForce > &tireForces, const PxVehicleEngineDriveThrottleCommandResponseState *&throttleResponseState, const PxVehicleClutchCommandResponseState *&clutchResponseState, const PxVehicleDifferentialState *&differentialState, const PxVehicleWheelConstraintGroupState *&constraintGroupState, PxVehicleArrayData< PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, PxVehicleEngineState *&engineState, PxVehicleGearboxState *&gearboxState, PxVehicleClutchSlipState *&clutchState)=0
Provide vehicle data items for this component.
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Detailed Description
Forward integrate the angular speed of each wheel and of the engine, accounting for the state of the clutch, gearbox and differential.
See also
PxVehicleGearboxUpdate
PxVehicleEngineDrivetrainUpdate
Constructor & Destructor Documentation
PxVehicleEngineDrivetrainComponent()
PxVehicleEngineDrivetrainComponent::PxVehicleEngineDrivetrainComponent () inline
~PxVehicleEngineDrivetrainComponent()
virtual PxVehicleEngineDrivetrainComponent::~PxVehicleEngineDrivetrainComponent () inline virtual
Member Function Documentation
getDataForEngineDrivetrainComponent()
virtual void PxVehicleEngineDrivetrainComponent::getDataForEngineDrivetrainComponent (const PxVehicleAxleDescription *& axleDescription, PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, const PxVehicleEngineParams *& engineParams, const PxVehicleClutchParams *& clutchParams, const PxVehicleGearboxParams *& gearboxParams, PxVehicleArrayData< const PxReal > & brakeResponseStates, PxVehicleArrayData< const PxVehicleWheelActuationState > & actuationStates, PxVehicleArrayData< const PxVehicleTireForce > & tireForces, const PxVehicleEngineDriveThrottleCommandResponseState *& throttleResponseState, const PxVehicleClutchCommandResponseState *& clutchResponseState, const PxVehicleDifferentialState *& differentialState, const PxVehicleWheelConstraintGroupState *& constraintGroupState, PxVehicleArrayData< PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, PxVehicleEngineState *& engineState, PxVehicleGearboxState *& gearboxState, PxVehicleClutchSlipState *& clutchState) pure virtual
Provide vehicle data items for this component.
Parameters
[out] axleDescription identifies the wheels on each axle.
[out] wheelParams specifies the radius of each wheel.
[out] engineParams specifies the engine's torque curve, idle revs and max revs.
[out] clutchParams specifies the maximum strength of the clutch.
[out] gearboxParams specifies the gear ratio of each gear.
[out] brakeResponseStates stores the instantaneous brake brake torque to apply to each wheel.
[out] actuationStates stores whether a brake and/or drive torque are to be applied to each wheel.
[out] tireForces stores the lateral and longitudinal tire force that has developed on each tire.
[out] throttleResponseState stores the response of the throttle to the input throttle command.
[out] clutchResponseState stores the instantaneous clutch strength that arises from the input clutch command.
[out] differentialState stores the instantaneous torque split between the wheels.
[out] constraintGroupState stores the groups of wheels that are subject to constraints that require them to have the same angular or linear velocity.
[out] wheelRigidBody1dStates stores the per wheel angular speed to be computed by the component.
[out] engineState stores the engine rotation speed to be computed by the component.
[out] gearboxState stores the state of the gearbox to be computed by the component.
[out] clutchState stores the clutch slip to be computed by the component.
Note
If constraintGroupState is set to NULL it is assumed that there are no requirements for any wheels to have the same angular or linear velocity.
update()
virtual bool PxVehicleEngineDrivetrainComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PX_PROFILE_ZONE, PX_UNUSED(), PxVehicleEngineDrivetrainUpdate(), and PxVehicleGearboxUpdate().
The documentation for this class was generated from the following file:
PxVehicleDrivetrainComponents.h