PxShape Class Reference
PxShape Class Reference abstract
Physics
Abstract class for collision shapes.
#include <PxShape.h>
Public Member Functions
virtual void release ()=0
Decrements the reference count of a shape and releases it if the new reference count is zero.
virtual void setGeometry (const PxGeometry &geometry)=0
Adjust the geometry of the shape.
virtual const PxGeometry & getGeometry () const =0
Retrieve a reference to the shape's geometry.
PX_DEPRECATED PX_FORCE_INLINE PxGeometryType::Enum getGeometryType () const
Get the geometry type of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getBoxGeometry (PxBoxGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getSphereGeometry (PxSphereGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getCapsuleGeometry (PxCapsuleGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getPlaneGeometry (PxPlaneGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getConvexMeshGeometry (PxConvexMeshGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getTriangleMeshGeometry (PxTriangleMeshGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getTetrahedronMeshGeometry (PxTetrahedronMeshGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getParticleSystemGeometry (PxParticleSystemGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getHeightFieldGeometry (PxHeightFieldGeometry &geometry) const
Fetch the geometry of the shape.
PX_DEPRECATED PX_FORCE_INLINE bool getCustomGeometry (PxCustomGeometry &geometry) const
Fetch the geometry of the shape.
virtual PxRigidActor * getActor () const =0
Retrieves the actor which this shape is associated with.
virtual void setMaterials (PxMaterial *const *materials, PxU16 materialCount)=0
Assigns material(s) to the shape. Will remove existing materials from the shape.
virtual void setSoftBodyMaterials (PxFEMSoftBodyMaterial *const *materials, PxU16 materialCount)=0
Assigns FEM soft body material(s) to the shape. Will remove existing materials from the shape.
virtual PxU16 getNbMaterials () const =0
Returns the number of materials assigned to the shape.
virtual PxU32 getMaterials (PxMaterial **userBuffer, PxU32 bufferSize, PxU32 startIndex=0) const =0
Retrieve all the material pointers associated with the shape.
virtual PxU32 getSoftBodyMaterials (PxFEMSoftBodyMaterial **userBuffer, PxU32 bufferSize, PxU32 startIndex=0) const =0
Retrieve all the FEM soft body material pointers associated with the shape.
virtual PxBaseMaterial * getMaterialFromInternalFaceIndex (PxU32 faceIndex) const =0
Retrieve material from given triangle index.
virtual void setContactOffset (PxReal contactOffset)=0
Sets the contact offset.
virtual PxReal getContactOffset () const =0
Retrieves the contact offset.
virtual void setRestOffset (PxReal restOffset)=0
Sets the rest offset.
virtual PxReal getRestOffset () const =0
Retrieves the rest offset.
virtual void setDensityForFluid (PxReal densityForFluid)=0
Sets the density used to interact with fluids.
virtual PxReal getDensityForFluid () const =0
Retrieves the density used to interact with fluids.
virtual void setTorsionalPatchRadius (PxReal radius)=0
Sets torsional patch radius.
virtual PxReal getTorsionalPatchRadius () const =0
Gets torsional patch radius.
virtual void setMinTorsionalPatchRadius (PxReal radius)=0
Sets minimum torsional patch radius.
virtual PxReal getMinTorsionalPatchRadius () const =0
Gets minimum torsional patch radius.
virtual void setFlag (PxShapeFlag::Enum flag, bool value)=0
Sets shape flags.
virtual void setFlags (PxShapeFlags inFlags)=0
Sets shape flags.
virtual PxShapeFlags getFlags () const =0
Retrieves shape flags.
virtual bool isExclusive () const =0
Returns true if the shape is exclusive to an actor.
virtual void setName (const char *name)=0
Sets a name string for the object that can be retrieved with getName().
virtual const char * getName () const =0
retrieves the name string set with setName().
virtual const char * getConcreteTypeName () const
Returns string name of dynamic type.
Pose Manipulation
virtual void setLocalPose (const PxTransform &pose)=0
Sets the pose of the shape in actor space, i.e. relative to the actors to which they are attached.
virtual PxTransform getLocalPose () const =0
Retrieves the pose of the shape in actor space, i.e. relative to the actor they are owned by.
Collision Filtering
virtual void setSimulationFilterData (const PxFilterData &data)=0
Sets the user definable collision filter data.
virtual PxFilterData getSimulationFilterData () const =0
Retrieves the shape's collision filter data.
virtual void setQueryFilterData (const PxFilterData &data)=0
Sets the user definable query filter data.
virtual PxFilterData getQueryFilterData () const =0
Retrieves the shape's Query filter data.
Public Member Functions inherited from PxRefCounted
virtual PxU32 getReferenceCount () const =0
Returns the reference count of the object.
virtual void acquireReference ()=0
Acquires a counted reference to this object.
Public Member Functions inherited from PxBase
template<class T >
T * is ()
template<class T >
const T * is () const
PX_FORCE_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_FORCE_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_FORCE_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_FORCE_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Public Attributes
void * userData
user can assign this to whatever, usually to create a 1:1 relationship with a user object.
Protected Member Functions
PX_INLINE PxShape (PxBaseFlags baseFlags)
PX_INLINE PxShape (PxType concreteType, PxBaseFlags baseFlags)
virtual ~PxShape ()
virtual bool isKindOf (const char *name) const
Returns whether a given type name matches with the type of this instance.
template<class T >
PX_FORCE_INLINE bool getGeometryT (PxGeometryType::Enum type, T &geom) const
Protected Member Functions inherited from PxRefCounted
virtual void onRefCountZero ()
PX_INLINE PxRefCounted (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxRefCounted (PxBaseFlags baseFlags)
virtual ~PxRefCounted ()
Protected Member Functions inherited from PxBase
PX_INLINE PxBase (PxType concreteType, PxBaseFlags baseFlags)
Constructor setting concrete type and base flags.
PX_INLINE PxBase (PxBaseFlags baseFlags)
Deserialization constructor setting base flags.
virtual ~PxBase ()
Destructor.
template<class T >
bool typeMatch () const
Additional Inherited Members
Protected Attributes inherited from PxBase
PxType mConcreteType
PxBaseFlags mBaseFlags
PxU32 mBuiltInRefCount
Detailed Description
Abstract class for collision shapes.
Shapes are shared, reference counted objects.
An instance can be created by calling the createShape() method of the PxRigidActor class, or the createShape() method of the PxPhysics class.
Visualizations
PxVisualizationParameter::eCOLLISION_AABBS
PxVisualizationParameter::eCOLLISION_SHAPES
PxVisualizationParameter::eCOLLISION_AXES
See also
PxPhysics.createShape() PxRigidActor.createShape() PxBoxGeometry PxSphereGeometry PxCapsuleGeometry PxPlaneGeometry PxConvexMeshGeometry PxTriangleMeshGeometry PxHeightFieldGeometry
Constructor & Destructor Documentation
PxShape() [1/2]
PX_INLINE PxShape::PxShape (PxBaseFlags baseFlags) inline protected
PxShape() [2/2]
PX_INLINE PxShape::PxShape (PxType concreteType, PxBaseFlags baseFlags) inline protected
~PxShape()
virtual PxShape::~PxShape () inline protected virtual
Member Function Documentation
getActor()
virtual PxRigidActor* PxShape::getActor () const pure virtual
Retrieves the actor which this shape is associated with.
Returns
The actor this shape is associated with, if it is an exclusive shape, else NULL
See also
PxRigidStatic, PxRigidDynamic, PxArticulationLink
getBoxGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getBoxGeometry (PxBoxGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eBOX.
getCapsuleGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getCapsuleGeometry (PxCapsuleGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eCAPSULE.
getConcreteTypeName()
virtual const char* PxShape::getConcreteTypeName () const inline virtual
Returns string name of dynamic type.
Returns
Class name of most derived type of this object.
Implements PxBase.
getContactOffset()
virtual PxReal PxShape::getContactOffset () const pure virtual
Retrieves the contact offset.
Returns
The contact offset of the shape.
See also
setContactOffset()
getConvexMeshGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getConvexMeshGeometry (PxConvexMeshGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eCONVEXMESH.
getCustomGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getCustomGeometry (PxCustomGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eCUSTOM.
getDensityForFluid()
virtual PxReal PxShape::getDensityForFluid () const pure virtual
Retrieves the density used to interact with fluids.
Returns
The density of the body when interacting with fluid.
See also
setDensityForFluid()
getFlags()
virtual PxShapeFlags PxShape::getFlags () const pure virtual
Retrieves shape flags.
Returns
The values of the shape flags.
See also
PxShapeFlag setFlag()
getGeometry()
virtual const PxGeometry& PxShape::getGeometry () const pure virtual
Retrieve a reference to the shape's geometry.
Warning
The returned reference has the same lifetime as the PxShape it comes from.
Returns
Reference to internal PxGeometry object.
See also
PxGeometry PxGeometryType getGeometryType() setGeometry()
Referenced by PxShapeExt::getWorldBounds(), PxShapeExt::overlap(), PxShapeExt::raycast(), and PxShapeExt::sweep().
getGeometryT()
template<class T > PX_FORCE_INLINE bool PxShape::getGeometryT (PxGeometryType::Enum type, T & geom) const inline protected
getGeometryType()
PX_DEPRECATED PX_FORCE_INLINE PxGeometryType::Enum PxShape::getGeometryType () const inline
Get the geometry type of the shape.
Returns
Type of shape geometry.
See also
PxGeometryType
getHeightFieldGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getHeightFieldGeometry (PxHeightFieldGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eHEIGHTFIELD.
getLocalPose()
virtual PxTransform PxShape::getLocalPose () const pure virtual
Retrieves the pose of the shape in actor space, i.e. relative to the actor they are owned by.
This transformation is identity by default.
Returns
Pose of shape relative to the actor's frame.
See also
setLocalPose()
Referenced by PxShapeExt::getGlobalPose().
getMaterialFromInternalFaceIndex()
virtual PxBaseMaterial* PxShape::getMaterialFromInternalFaceIndex (PxU32 faceIndex) const pure virtual
Retrieve material from given triangle index.
The input index is the internal triangle index as used inside the SDK. This is the index returned to users by various SDK functions such as raycasts.
This function is only useful for triangle meshes or heightfields, which have per-triangle materials. For other shapes or SDF triangle meshes, the function returns the single material associated with the shape, regardless of the index.
Parameters
[in] faceIndex The internal triangle index whose material you want to retrieve.
Returns
Material from input triangle
Note
If faceIndex value of 0xFFFFffff is passed as an input for mesh and heightfield shapes, this function will issue a warning and return NULL.
Scene queries set the value of PxQueryHit::faceIndex to 0xFFFFffff whenever it is undefined or does not apply.
See also
PxMaterial getNbMaterials() PxMaterial::release()
getMaterials()
virtual PxU32 PxShape::getMaterials (PxMaterial ** userBuffer, PxU32 bufferSize, PxU32 startIndex = 0) const pure virtual
Retrieve all the material pointers associated with the shape.
You can retrieve the number of material pointers by calling getNbMaterials()
Note: The returned data may contain invalid pointers if you release materials using PxMaterial::release().
Parameters
[out] userBuffer The buffer to store the material pointers.
[in] bufferSize Size of provided user buffer.
[in] startIndex Index of first material pointer to be retrieved
Returns
Number of material pointers written to the buffer.
See also
PxMaterial getNbMaterials() PxMaterial::release()
getMinTorsionalPatchRadius()
virtual PxReal PxShape::getMinTorsionalPatchRadius () const pure virtual
Gets minimum torsional patch radius.
This defines the minimum radius of the contact patch used to apply torsional friction. If the radius is 0, the amount of torsional friction that will be applied will be entirely dependent on the value of torsionalPatchRadius.
If the radius is > 0, some torsional friction will be applied regardless of the value of torsionalPatchRadius or the amount of penetration.
Returns
The minimum torsional patch radius of the shape.
getName()
virtual const char* PxShape::getName () const pure virtual
retrieves the name string set with setName().
Returns
The name associated with the shape.
See also
setName()
getNbMaterials()
virtual PxU16 PxShape::getNbMaterials () const pure virtual
Returns the number of materials assigned to the shape.
You can use getMaterials() to retrieve the material pointers.
Returns
Number of materials associated with this shape.
See also
PxMaterial getMaterials()
getParticleSystemGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getParticleSystemGeometry (PxParticleSystemGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::ePARTICLESYSTEM.
getPlaneGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getPlaneGeometry (PxPlaneGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::ePLANE.
getQueryFilterData()
virtual PxFilterData PxShape::getQueryFilterData () const pure virtual
Retrieves the shape's Query filter data.
See also
setQueryFilterData()
getRestOffset()
virtual PxReal PxShape::getRestOffset () const pure virtual
Retrieves the rest offset.
Returns
The rest offset of the shape.
See also
setRestOffset()
getSimulationFilterData()
virtual PxFilterData PxShape::getSimulationFilterData () const pure virtual
Retrieves the shape's collision filter data.
See also
setSimulationFilterData()
getSoftBodyMaterials()
virtual PxU32 PxShape::getSoftBodyMaterials (PxFEMSoftBodyMaterial ** userBuffer, PxU32 bufferSize, PxU32 startIndex = 0) const pure virtual
Retrieve all the FEM soft body material pointers associated with the shape.
You can retrieve the number of material pointers by calling getNbMaterials()
Note: The returned data may contain invalid pointers if you release materials using PxMaterial::release().
Parameters
[out] userBuffer The buffer to store the material pointers.
[in] bufferSize Size of provided user buffer.
[in] startIndex Index of first material pointer to be retrieved
Returns
Number of material pointers written to the buffer.
See also
PxFEMSoftBodyMaterial getNbMaterials() PxMaterial::release()
getSphereGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getSphereGeometry (PxSphereGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eSPHERE.
getTetrahedronMeshGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getTetrahedronMeshGeometry (PxTetrahedronMeshGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eTETRAHEDRONMESH.
getTorsionalPatchRadius()
virtual PxReal PxShape::getTorsionalPatchRadius () const pure virtual
Gets torsional patch radius.
This defines the radius of the contact patch used to apply torsional friction. If the radius is 0, no torsional friction will be applied. If the radius is > 0, some torsional friction will be applied. This is proportional to the penetration depth so, if the shapes are separated or penetration is zero, no torsional friction will be applied. It is used to approximate rotational friction introduced by the compression of contacting surfaces.
Returns
The torsional patch radius of the shape.
getTriangleMeshGeometry()
PX_DEPRECATED PX_FORCE_INLINE bool PxShape::getTriangleMeshGeometry (PxTriangleMeshGeometry & geometry) const inline
Fetch the geometry of the shape.
Note
If the type of geometry to extract does not match the geometry type of the shape then the method will return false and the passed in geometry descriptor is not modified.
Parameters
[in] geometry The descriptor to save the shape's geometry data to.
Returns
True on success else false
See also
PxGeometry PxGeometryType getGeometryType()
References PxGeometryType::eTRIANGLEMESH.
isExclusive()
virtual bool PxShape::isExclusive () const pure virtual
Returns true if the shape is exclusive to an actor.
See also
PxPhysics::createShape()
isKindOf()
virtual bool PxShape::isKindOf (const char * superClass) const inline protected virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented from PxRefCounted.
References PxRefCounted::isKindOf().
release()
virtual void PxShape::release () pure virtual
Decrements the reference count of a shape and releases it if the new reference count is zero.
Note that in releases prior to PhysX 3.3 this method did not have reference counting semantics and was used to destroy a shape created with PxActor::createShape(). In PhysX 3.3 and above, this usage is deprecated, instead, use PxRigidActor::detachShape() to detach a shape from an actor. If the shape to be detached was created with PxActor::createShape(), the actor holds the only counted reference, and so when the shape is detached it will also be destroyed.
See also
PxRigidActor::createShape() PxPhysics::createShape() PxRigidActor::attachShape() PxRigidActor::detachShape()
Implements PxRefCounted.
Referenced by PxRigidActorExt::createExclusiveShape().
setContactOffset()
virtual void PxShape::setContactOffset (PxReal contactOffset) pure virtual
Sets the contact offset.
Shapes whose distance is less than the sum of their contactOffset values will generate contacts. The contact offset must be positive and greater than the rest offset. Having a contactOffset greater than than the restOffset allows the collision detection system to predictively enforce the contact constraint even when the objects are slightly separated. This prevents jitter that would occur if the constraint were enforced only when shapes were within the rest distance.
Default: 0.02f * PxTolerancesScale::length
Sleeping: Does NOT wake the associated actor up automatically.
Parameters
[in] contactOffset Range: [maximum(0,restOffset), PX_MAX_F32)
See also
getContactOffset PxTolerancesScale setRestOffset
setDensityForFluid()
virtual void PxShape::setDensityForFluid (PxReal densityForFluid) pure virtual
Sets the density used to interact with fluids.
To be physically accurate, the density of a rigid body should be computed as its mass divided by its volume. To simplify tuning the interaction of fluid and rigid bodies, the density for fluid can differ from the real density. This allows to create floating bodies, even if they are supposed to sink with their mass and volume.
Default: 800.0f
Parameters
[in] densityForFluid Range: (0, PX_MAX_F32)
See also
getDensityForFluid
setFlag()
virtual void PxShape::setFlag (PxShapeFlag::Enum flag, bool value) pure virtual
Sets shape flags.
Sleeping: Does NOT wake the associated actor up automatically.
Parameters
[in] flag The shape flag to enable/disable. See PxShapeFlag.
[in] value True to set the flag. False to clear the flag specified in flag.
Default: PxShapeFlag::eVISUALIZATION | PxShapeFlag::eSIMULATION_SHAPE | PxShapeFlag::eSCENE_QUERY_SHAPE
See also
PxShapeFlag getFlags()
setFlags()
virtual void PxShape::setFlags (PxShapeFlags inFlags) pure virtual
Sets shape flags.
See also
PxShapeFlag getFlags()
setGeometry()
virtual void PxShape::setGeometry (const PxGeometry & geometry) pure virtual
Adjust the geometry of the shape.
Note
The type of the passed in geometry must match the geometry type of the shape.
It is not allowed to change the geometry type of a shape.
This function does not guarantee correct/continuous behavior when objects are resting on top of old or new geometry.
Parameters
[in] geometry New geometry of the shape.
See also
PxGeometry PxGeometryType getGeometryType()
setLocalPose()
virtual void PxShape::setLocalPose (const PxTransform & pose) pure virtual
Sets the pose of the shape in actor space, i.e. relative to the actors to which they are attached.
This transformation is identity by default.
The local pose is an attribute of the shape, and so will apply to all actors to which the shape is attached.
Sleeping: Does NOT wake the associated actor up automatically.
Note: Does not automatically update the inertia properties of the owning actor (if applicable); use the PhysX extensions method PxRigidBodyExt::updateMassAndInertia() to do this.
Default: the identity transform
Parameters
[in] pose The new transform from the actor frame to the shape frame. Range: rigid body transform
See also
getLocalPose()
setMaterials()
virtual void PxShape::setMaterials (PxMaterial *const * materials, PxU16 materialCount) pure virtual
Assigns material(s) to the shape. Will remove existing materials from the shape.
Sleeping: Does NOT wake the associated actor up automatically.
Parameters
[in] materials List of material pointers to assign to the shape. See PxMaterial
[in] materialCount The number of materials provided.
See also
PxPhysics.createMaterial() getMaterials()
setMinTorsionalPatchRadius()
virtual void PxShape::setMinTorsionalPatchRadius (PxReal radius) pure virtual
Sets minimum torsional patch radius.
This defines the minimum radius of the contact patch used to apply torsional friction. If the radius is 0, the amount of torsional friction that will be applied will be entirely dependent on the value of torsionalPatchRadius.
If the radius is > 0, some torsional friction will be applied regardless of the value of torsionalPatchRadius or the amount of penetration.
Default: 0.0
Parameters
[in] radius Range: (0, PX_MAX_F32)
setName()
virtual void PxShape::setName (const char * name) pure virtual
Sets a name string for the object that can be retrieved with getName().
This is for debugging and is not used by the SDK. The string is not copied by the SDK, only the pointer is stored.
Default: NULL
Parameters
[in] name The name string to set the objects name to.
See also
getName()
setQueryFilterData()
virtual void PxShape::setQueryFilterData (const PxFilterData & data) pure virtual
Sets the user definable query filter data.
Default: (0,0,0,0)
See also
getQueryFilterData()
setRestOffset()
virtual void PxShape::setRestOffset (PxReal restOffset) pure virtual
Sets the rest offset.
Two shapes will come to rest at a distance equal to the sum of their restOffset values. If the restOffset is 0, they should converge to touching exactly. Having a restOffset greater than zero is useful to have objects slide smoothly, so that they do not get hung up on irregularities of each others' surfaces.
Default: 0.0f
Sleeping: Does NOT wake the associated actor up automatically.
Parameters
[in] restOffset Range: (-PX_MAX_F32, contactOffset)
See also
getRestOffset setContactOffset
setSimulationFilterData()
virtual void PxShape::setSimulationFilterData (const PxFilterData & data) pure virtual
Sets the user definable collision filter data.
Sleeping: Does wake up the actor if the filter data change causes a formerly suppressed collision pair to be enabled.
Default: (0,0,0,0)
See also
getSimulationFilterData()
setSoftBodyMaterials()
virtual void PxShape::setSoftBodyMaterials (PxFEMSoftBodyMaterial *const * materials, PxU16 materialCount) pure virtual
Assigns FEM soft body material(s) to the shape. Will remove existing materials from the shape.
Sleeping: Does NOT wake the associated actor up automatically.
Parameters
[in] materials List of material pointers to assign to the shape. See PxFEMSoftBodyMaterial
[in] materialCount The number of materials provided.
See also
PxPhysics.createFEMSoftBodyMaterial() getSoftBodyMaterials()
setTorsionalPatchRadius()
virtual void PxShape::setTorsionalPatchRadius (PxReal radius) pure virtual
Sets torsional patch radius.
This defines the radius of the contact patch used to apply torsional friction. If the radius is 0, no torsional friction will be applied. If the radius is > 0, some torsional friction will be applied. This is proportional to the penetration depth so, if the shapes are separated or penetration is zero, no torsional friction will be applied. It is used to approximate rotational friction introduced by the compression of contacting surfaces.
Default: 0.0
Parameters
[in] radius Range: (0, PX_MAX_F32)
Member Data Documentation
userData
void* PxShape::userData
user can assign this to whatever, usually to create a 1:1 relationship with a user object.
The documentation for this class was generated from the following file:
PxShape.h