PxVehiclePhysXConstraintComponent Class Reference
PxVehiclePhysXConstraintComponent Class Reference abstract
Vehicle2
#include <PxVehiclePhysXConstraintComponents.h>
Public Member Functions
PxVehiclePhysXConstraintComponent ()
virtual ~PxVehiclePhysXConstraintComponent ()
virtual void getDataForPhysXConstraintComponent (const PxVehicleAxleDescription *&axleDescription, const PxVehicleRigidBodyState *&rigidBodyState, PxVehicleArrayData< const PxVehicleSuspensionParams > &suspensionParams, PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > &suspensionLimitParams, PxVehicleArrayData< const PxVehicleSuspensionState > &suspensionStates, PxVehicleArrayData< const PxVehicleSuspensionComplianceState > &suspensionComplianceStates, PxVehicleArrayData< const PxVehicleRoadGeometryState > &wheelRoadGeomStates, PxVehicleArrayData< const PxVehicleTireDirectionState > &tireDirectionStates, PxVehicleArrayData< const PxVehicleTireStickyState > &tireStickyStates, PxVehiclePhysXConstraints *&constraints)=0
virtual bool update (const PxReal dt, const PxVehicleSimulationContext &context)
Update function for a vehicle component.
Public Member Functions inherited from PxVehicleComponent
virtual ~PxVehicleComponent ()
Constructor & Destructor Documentation
PxVehiclePhysXConstraintComponent()
PxVehiclePhysXConstraintComponent::PxVehiclePhysXConstraintComponent () inline
~PxVehiclePhysXConstraintComponent()
virtual PxVehiclePhysXConstraintComponent::~PxVehiclePhysXConstraintComponent () inline virtual
Member Function Documentation
getDataForPhysXConstraintComponent()
virtual void PxVehiclePhysXConstraintComponent::getDataForPhysXConstraintComponent (const PxVehicleAxleDescription *& axleDescription, const PxVehicleRigidBodyState *& rigidBodyState, PxVehicleArrayData< const PxVehicleSuspensionParams > & suspensionParams, PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > & suspensionLimitParams, PxVehicleArrayData< const PxVehicleSuspensionState > & suspensionStates, PxVehicleArrayData< const PxVehicleSuspensionComplianceState > & suspensionComplianceStates, PxVehicleArrayData< const PxVehicleRoadGeometryState > & wheelRoadGeomStates, PxVehicleArrayData< const PxVehicleTireDirectionState > & tireDirectionStates, PxVehicleArrayData< const PxVehicleTireStickyState > & tireStickyStates, PxVehiclePhysXConstraints *& constraints) pure virtual
update()
virtual bool PxVehiclePhysXConstraintComponent::update (const PxReal dt, const PxVehicleSimulationContext & context) inline virtual
Update function for a vehicle component.
Parameters
[in] dt The timestep size to use for the update step.
[in] context Vehicle simulation context holding global data or data that usually applies to a large group of vehicles.
Returns
True if subsequent components in a sequence should get updated, false if the sequence should be aborted.
See also
PxVehicleComponentSequence
Implements PxVehicleComponent.
References PxVehiclePhysXConstraints::constraintStates, PxVehicleTireAxisStickyParams::damping, PxVehicleTireDirectionModes::eLATERAL, PxVehicleTireDirectionModes::eLONGITUDINAL, PxVehicleAxleDescription::nbWheels, PX_PROFILE_ZONE, PX_UNUSED(), PxVehicleConstraintsDirtyStateUpdate(), PxVehiclePhysXConstraintStatesUpdate(), PxVehicleTireStickyParams::stickyParams, PxVehicleSimulationContext::tireStickyParams, and PxVehicleAxleDescription::wheelIdsInAxleOrder.
The documentation for this class was generated from the following file:
PxVehiclePhysXConstraintComponents.h