physx::PxArray< T, Alloc > Class Template Reference
physx::PxArray< T, Alloc > Class Template Reference
#include <PxArray.h>
Public Types
typedef T * Iterator
typedef const T * ConstIterator
Public Member Functions
PxArray (const PxEMPTY v)
PX_INLINE PxArray (const Alloc &alloc=Alloc())
PX_INLINE PxArray (uint32_t size, const T &a=T(), const Alloc &alloc=Alloc())
template<class A >
PX_INLINE PxArray (const PxArray< T, A > &other, const Alloc &alloc=Alloc())
PX_INLINE PxArray (const PxArray &other, const Alloc &alloc=Alloc())
PX_INLINE PxArray (const T *first, const T *last, const Alloc &alloc=Alloc())
PX_INLINE ~PxArray ()
template<class A >
PX_INLINE PxArray & operator= (const PxArray< T, A > &rhs)
PX_INLINE PxArray & operator= (const PxArray &t)
PX_FORCE_INLINE const T & operator[] (uint32_t i) const
PX_FORCE_INLINE T & operator[] (uint32_t i)
PX_FORCE_INLINE ConstIterator begin () const
PX_FORCE_INLINE Iterator begin ()
PX_FORCE_INLINE ConstIterator end () const
PX_FORCE_INLINE Iterator end ()
PX_FORCE_INLINE const T & front () const
PX_FORCE_INLINE T & front ()
PX_FORCE_INLINE const T & back () const
PX_FORCE_INLINE T & back ()
PX_FORCE_INLINE uint32_t size () const
PX_INLINE void clear ()
PX_FORCE_INLINE bool empty () const
PX_INLINE Iterator find (const T &a)
PX_INLINE ConstIterator find (const T &a) const
PX_FORCE_INLINE T & pushBack (const T &a)
PX_INLINE T popBack ()
PX_INLINE T & insert ()
PX_INLINE void replaceWithLast (uint32_t i)
PX_INLINE void replaceWithLast (Iterator i)
PX_INLINE bool findAndReplaceWithLast (const T &a)
PX_INLINE void remove (uint32_t i)
PX_INLINE void removeRange (uint32_t begin, uint32_t count)
PX_NOINLINE void resize (const uint32_t size, const T &a=T())
PX_NOINLINE void resizeUninitialized (const uint32_t size)
PX_INLINE void shrink ()
PX_INLINE void reset ()
PX_INLINE void resetOrClear ()
PX_INLINE void reserve (const uint32_t capacity)
PX_FORCE_INLINE uint32_t capacity () const
PX_FORCE_INLINE void forceSize_Unsafe (uint32_t size)
PX_INLINE void swap (PxArray< T, Alloc > &other)
PX_INLINE void assign (const T *first, const T *last)
PX_FORCE_INLINE uint32_t isInUserMemory () const
PX_INLINE Alloc & getAllocator ()
return reference to allocator
Protected Member Functions
PxArray (T *memory, uint32_t size, uint32_t capacity, const Alloc &alloc=Alloc())
template<class A >
PX_NOINLINE void copy (const PxArray< T, A > &other)
PX_INLINE T * allocate (uint32_t size)
PX_INLINE void deallocate (void *mem)
PX_NOINLINE T & growAndPushBack (const T &a)
PX_INLINE void grow (uint32_t capacity)
PX_NOINLINE void recreate (uint32_t capacity)
PX_INLINE uint32_t capacityIncrement () const
Static Protected Member Functions
static PX_INLINE void create (T *first, T *last, const T &a)
static PX_INLINE void copy (T *first, T *last, const T *src)
static PX_INLINE void destroy (T *first, T *last)
Protected Attributes
T * mData
uint32_t mSize
uint32_t mCapacity
Detailed Description
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type>
class physx::PxArray< T, Alloc >
An array is a sequential container.
Implementation note entries between 0 and size are valid objects we use inheritance to build this because the array is included inline in a lot of objects and we want the allocator to take no space if it's not stateful, which aggregation doesn't allow. Also, we want the metadata at the front for the inline case where the allocator contains some inline storage space
Member Typedef Documentation
ConstIterator
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> typedef const T* physx::PxArray< T, Alloc >::ConstIterator
Iterator
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> typedef T* physx::PxArray< T, Alloc >::Iterator
Constructor & Destructor Documentation
PxArray() [1/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> physx::PxArray< T, Alloc >::PxArray (const PxEMPTY v) inline explicit
PxArray() [2/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE physx::PxArray< T, Alloc >::PxArray (const Alloc & alloc = Alloc()) inline explicit
Default array constructor. Initialize an empty array
PxArray() [3/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE physx::PxArray< T, Alloc >::PxArray (uint32_t size, const T & a = T(), const Alloc & alloc = Alloc()) inline explicit
Initialize array with given capacity
PxArray() [4/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> template<class A > PX_INLINE physx::PxArray< T, Alloc >::PxArray (const PxArray< T, A > & other, const Alloc & alloc = Alloc()) inline explicit
Copy-constructor. Copy all entries from other array
PxArray() [5/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE physx::PxArray< T, Alloc >::PxArray (const PxArray< T, Alloc > & other, const Alloc & alloc = Alloc()) inline
PxArray() [6/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE physx::PxArray< T, Alloc >::PxArray (const T * first, const T * last, const Alloc & alloc = Alloc()) inline explicit
Initialize array with given length
~PxArray()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE physx::PxArray< T, Alloc >::~PxArray () inline
Destructor
PxArray() [7/7]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> physx::PxArray< T, Alloc >::PxArray (T * memory, uint32_t size, uint32_t capacity, const Alloc & alloc = Alloc()) inline protected
Member Function Documentation
allocate()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE T* physx::PxArray< T, Alloc >::allocate (uint32_t size) inline protected
Mark a specified amount of memory with 0xcd pattern. This is used to check that the meta data definition for serialized classes is complete in checked builds.
Referenced by physx::PxArray< void *, Alloc >::PxArray().
assign()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::assign (const T * first, const T * last) inline
Assign a range of values to this vector (resizes to length of range)
back() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE const T& physx::PxArray< T, Alloc >::back () const inline
Returns a reference to the last element of the array. Undefined if the array is empty
Returns
a reference to the last element of the array
back() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE T& physx::PxArray< T, Alloc >::back () inline
begin() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE ConstIterator physx::PxArray< T, Alloc >::begin () const inline
Returns a pointer to the initial element of the array.
Returns
a pointer to the initial element of the array.
Referenced by physx::PxArray< void *, Alloc >::copy(), physx::PxPoolBase< T, Alloc >::disposeElements(), PxSoftBodySimulationDataDesc::PxSoftBodySimulationDataDesc(), PxTetrahedronMeshDesc::PxTetrahedronMeshDesc(), and physx::PxPoolBase< T, Alloc >::~PxPoolBase().
begin() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE Iterator physx::PxArray< T, Alloc >::begin () inline
capacity()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE uint32_t physx::PxArray< T, Alloc >::capacity () const inline
Query the capacity(allocated mem) for the array.
Referenced by physx::PxArray< void *, Alloc >::capacityIncrement(), physx::PxArray< void *, Alloc >::grow(), physx::PxArray< void *, Alloc >::pushBack(), and physx::PxArray< void *, Alloc >::~PxArray().
capacityIncrement()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE uint32_t physx::PxArray< T, Alloc >::capacityIncrement () const inline protected
clear()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::clear () inline
Clears the array.
Referenced by physx::PxArray< void *, Alloc >::operator=().
copy() [1/2]
template<class T, class Alloc > template<class A > PX_NOINLINE void PxArray::copy (const PxArray< T, A > & other) protected
Referenced by physx::PxArray< void *, Alloc >::operator=(), and physx::PxArray< void *, Alloc >::PxArray().
copy() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> static PX_INLINE void physx::PxArray< T, Alloc >::copy (T * first, T * last, const T * src) inline static protected
create()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> static PX_INLINE void physx::PxArray< T, Alloc >::create (T * first, T * last, const T & a) inline static protected
deallocate()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::deallocate (void * mem) inline protected
Referenced by physx::PxArray< void *, Alloc >::~PxArray().
destroy()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> static PX_INLINE void physx::PxArray< T, Alloc >::destroy (T * first, T * last) inline static protected
Referenced by physx::PxArray< void *, Alloc >::clear(), and physx::PxArray< void *, Alloc >::~PxArray().
empty()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE bool physx::PxArray< T, Alloc >::empty () const inline
Returns whether the array is empty (i.e. whether its size is 0).
Returns
true if the array is empty
Referenced by physx::PxArray< void *, Alloc >::copy().
end() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE ConstIterator physx::PxArray< T, Alloc >::end () const inline
Returns an iterator beyond the last element of the array. Do not dereference.
Returns
a pointer to the element beyond the last element of the array.
Referenced by physx::PxPoolBase< T, Alloc >::disposeElements(), and physx::PxPoolBase< T, Alloc >::~PxPoolBase().
end() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE Iterator physx::PxArray< T, Alloc >::end () inline
find() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE Iterator physx::PxArray< T, Alloc >::find (const T & a) inline
Finds the first occurrence of an element in the array.
Parameters
a The element to find.
find() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE ConstIterator physx::PxArray< T, Alloc >::find (const T & a) const inline
findAndReplaceWithLast()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE bool physx::PxArray< T, Alloc >::findAndReplaceWithLast (const T & a) inline
Replaces the first occurrence of the element a with the last element Operation is O(n)
Parameters
a The position of the element that will be subtracted from this array.
Returns
true if the element has been removed.
forceSize_Unsafe()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE void physx::PxArray< T, Alloc >::forceSize_Unsafe (uint32_t size) inline
Unsafe function to force the size of the array
front() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE const T& physx::PxArray< T, Alloc >::front () const inline
Returns a reference to the first element of the array. Undefined if the array is empty.
Returns
a reference to the first element of the array
front() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE T& physx::PxArray< T, Alloc >::front () inline
getAllocator()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE Alloc& physx::PxArray< T, Alloc >::getAllocator () inline
return reference to allocator
grow()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::grow (uint32_t capacity) inline protected
Resizes the available memory for the array.
Parameters
capacity The number of entries that the set should be able to hold.
growAndPushBack()
template<class T, class Alloc > PX_NOINLINE T & PxArray::growAndPushBack (const T & a) protected
Called when pushBack() needs to grow the array.
Parameters
a The element that will be added to this array.
Referenced by physx::PxArray< void *, Alloc >::pushBack().
insert()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE T& physx::PxArray< T, Alloc >::insert () inline
Construct one element at the end of the array. Operation is O(1).
isInUserMemory()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE uint32_t physx::PxArray< T, Alloc >::isInUserMemory () const inline
Referenced by physx::PxArray< void *, Alloc >::~PxArray().
operator=() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> template<class A > PX_INLINE PxArray& physx::PxArray< T, Alloc >::operator= (const PxArray< T, A > & rhs) inline
Assignment operator. Copy content (deep-copy)
operator=() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE PxArray& physx::PxArray< T, Alloc >::operator= (const PxArray< T, Alloc > & t) inline
operator[]() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE const T& physx::PxArray< T, Alloc >::operator[] (uint32_t i) const inline
Array indexing operator.
Parameters
i The index of the element that will be returned.
Returns
The element i in the array.
operator[]() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE T& physx::PxArray< T, Alloc >::operator[] (uint32_t i) inline
Array indexing operator.
Parameters
i The index of the element that will be returned.
Returns
The element i in the array.
popBack()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE T physx::PxArray< T, Alloc >::popBack () inline
Returns the element at the end of the array. Only legal if the array is non-empty.
pushBack()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE T& physx::PxArray< T, Alloc >::pushBack (const T & a) inline
Adds one element to the end of the array. Operation is O(1).
Parameters
a The element that will be added to this array.
Referenced by physx::PxPoolBase< T, Alloc >::allocateSlab(), and physx::PxPoolBase< T, Alloc >::disposeElements().
recreate()
template<class T , class Alloc > PX_NOINLINE void PxArray::recreate (uint32_t capacity) protected
Creates a new memory block, copies all entries to the new block and destroys old entries.
Parameters
capacity The number of entries that the set should be able to hold.
Referenced by physx::PxArray< void *, Alloc >::grow().
remove()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::remove (uint32_t i) inline
Subtracts the element on position i from the array. Shift the entire array one step. Operation is O(n)
Parameters
i The position of the element that will be subtracted from this array.
removeRange()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::removeRange (uint32_t begin, uint32_t count) inline
Removes a range from the array. Shifts the array so order is maintained. Operation is O(n)
Parameters
begin The starting position of the element that will be subtracted from this array.
count The number of elments that will be subtracted from this array.
replaceWithLast() [1/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::replaceWithLast (uint32_t i) inline
Subtracts the element on position i from the array and replace it with the last element. Operation is O(1)
Parameters
i The position of the element that will be subtracted from this array.
Referenced by physx::PxArray< void *, Alloc >::findAndReplaceWithLast(), and physx::PxArray< void *, Alloc >::replaceWithLast().
replaceWithLast() [2/2]
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::replaceWithLast (Iterator i) inline
reserve()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::reserve (const uint32_t capacity) inline
Ensure that the array has at least size capacity.
Referenced by physx::PxArray< void *, Alloc >::operator=(), and physx::PxPoolBase< T, Alloc >::PxPoolBase().
reset()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::reset () inline
Deletes all array elements and frees memory.
resetOrClear()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::resetOrClear () inline
Resets or clears the array depending on occupancy.
resize()
template<class T, class Alloc > PX_NOINLINE void PxArray::resize (const uint32_t size, const T & a = T())
Resize array
Referenced by physx::PxArray< void *, Alloc >::PxArray().
resizeUninitialized()
template<class T , class Alloc > PX_NOINLINE void PxArray::resizeUninitialized (const uint32_t size)
shrink()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::shrink () inline
Resize array such that only as much memory is allocated to hold the existing elements
size()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_FORCE_INLINE uint32_t physx::PxArray< T, Alloc >::size () const inline
Returns the number of entries in the array. This can, and probably will, differ from the array capacity.
Returns
The number of of entries in the array.
Referenced by physx::PxArray< void *, Alloc >::allocate(), physx::PxArray< void *, Alloc >::copy(), physx::PxPoolBase< T, Alloc >::disposeElements(), physx::PxArray< void *, Alloc >::PxArray(), PxSoftBodySimulationDataDesc::PxSoftBodySimulationDataDesc(), and PxTetrahedronMeshDesc::PxTetrahedronMeshDesc().
swap()
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> PX_INLINE void physx::PxArray< T, Alloc >::swap (PxArray< T, Alloc > & other) inline
Swap contents of an array without allocating temporary storage
Referenced by physx::swap().
Member Data Documentation
mCapacity
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> uint32_t physx::PxArray< T, Alloc >::mCapacity protected
Referenced by physx::PxArray< void *, Alloc >::isInUserMemory(), and physx::PxArray< void *, Alloc >::PxArray().
mData
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> T* physx::PxArray< T, Alloc >::mData protected
Referenced by physx::PxArray< void *, Alloc >::back(), physx::PxArray< void *, Alloc >::begin(), physx::PxArray< void *, Alloc >::clear(), physx::PxArray< void *, Alloc >::end(), physx::PxArray< void *, Alloc >::find(), physx::PxArray< void *, Alloc >::findAndReplaceWithLast(), physx::PxArray< void *, Alloc >::front(), physx::PxArray< void *, Alloc >::operator=(), physx::PxArray< void *, Alloc >::operator[](), physx::PxArray< void *, Alloc >::pushBack(), physx::PxArray< void *, Alloc >::PxArray(), physx::PxArray< void *, Alloc >::replaceWithLast(), and physx::PxArray< void *, Alloc >::~PxArray().
mSize
template<class T, class Alloc = typename PxAllocatorTraits<T>::Type> uint32_t physx::PxArray< T, Alloc >::mSize protected
Referenced by physx::PxArray< void *, Alloc >::back(), physx::PxArray< void *, Alloc >::clear(), physx::PxArray< void *, Alloc >::empty(), physx::PxArray< void *, Alloc >::end(), physx::PxArray< void *, Alloc >::find(), physx::PxArray< void *, Alloc >::findAndReplaceWithLast(), physx::PxArray< void *, Alloc >::front(), physx::PxArray< void *, Alloc >::operator=(), physx::PxArray< void *, Alloc >::operator[](), physx::PxArray< void *, Alloc >::pushBack(), physx::PxArray< void *, Alloc >::PxArray(), physx::PxArray< void *, Alloc >::size(), and physx::PxArray< void *, Alloc >::~PxArray().
The documentation for this class was generated from the following file:
PxArray.h