Vehicle2
Vehicle2
Namespaces
physx
Classes
struct PxVehicleBrakeCommandResponseParams
Distribute a brake response to the wheels of a vehicle.
struct PxVehicleCommandValueResponseTable
Each command value may be associated with a table specifying a normalized response as a function of longitudinal speed. Multiple instances of PxVehicleCommandValueResponseTable allow a normalized response to be authored as a multi-variate piecewise polynomial with normalized command response expressed as a nonlinear function of command value and speed.
class PxVehicleCommandNonLinearResponseParams
struct PxVehicleCommandResponseParams
A description of the per wheel response to an input command.
struct PxVehicleCommandState
A description of the state of commands that are applied to the vehicle.
struct PxVehicleDirectDriveTransmissionCommandState
A description of the state of transmission-related commands that are applied to a vehicle with direct drive.
struct PxVehicleEngineDriveTransmissionCommandState
A description of the state of transmission-related commands that are applied to a vehicle with engine drive.
struct PxVehicleTankDriveTransmissionCommandState
A description of the state of transmission-related commands that are applied to a vehicle with tank drive.
class PxVehicleDirectDriveCommandResponseComponent
Forward the applicable set of control values for a direct drive vehicle to a command response state for each applicable control value.
class PxVehicleDirectDriveActuationStateComponent
Determine the actuation state for each wheel of a direct drive vehicle.
class PxVehicleDirectDrivetrainComponent
Forward integrate the angular speed of each wheel on a vehicle by integrating the brake and drive torque applied to each wheel and the torque that develops on the tire as a response to the longitudinal tire force.
class PxVehicleEngineDriveCommandResponseComponent
Forward the applicable set of control values for a vehicle driven by an engine to a command response state for each applicable control value.
class PxVehicleMultiWheelDriveDifferentialStateComponent
Compute the per wheel drive torque split of a multi-wheel drive differential.
class PxVehicleFourWheelDriveDifferentialStateComponent
Compute the per wheel drive torque split of a differential delivering torque to multiple wheels with limited slip applied to specified wheel pairs.
class PxVehicleTankDriveDifferentialStateComponent
Compute the per wheel drive torque split of a tank drive differential.
class PxVehicleLegacyFourWheelDriveDifferentialStateComponent
Compute the per wheel drive torque split of a four wheel drive differential.
class PxVehicleEngineDriveActuationStateComponent
Determine the actuation state for each wheel for a vehicle propelled by engine torque.
class PxVehicleEngineDrivetrainComponent
Forward integrate the angular speed of each wheel and of the engine, accounting for the state of the clutch, gearbox and differential.
struct PxVehicleDirectDriveThrottleCommandResponseParams
Distribute a throttle response to the wheels of a direct drive vehicle.
struct PxVehicleClutchCommandResponseParams
Specifies the maximum clutch strength that occurs when the clutch pedal is fully disengaged and the clutch is fully engaged.
struct PxVehicleClutchAccuracyMode
Choose between a potentially more expensive but more accurate solution to the clutch model or a potentially cheaper but less accurate solution.
struct PxVehicleClutchParams
The clutch connects two plates together. One plate rotates with the speed of the engine. The second plate rotates with a weighted average of all wheels connected to the differential after accounting for the gear ratio. The difference in rotation speeds generates a restoring torque applied to engine and wheels that aims to reduce the difference in rotational speed. The restoring torque is proportional to the clutch strength and the clutch pedal position.
struct PxVehicleEngineParams
struct PxVehicleGearboxParams
struct PxVehicleAutoboxParams
struct PxVehicleFourWheelDriveDifferentialLegacyParams
struct PxVehicleMultiWheelDriveDifferentialParams
PxVehicleMultiWheelDriveDifferentialParams specifies the wheels that are to receive drive torque from the differential and the division of torque between the wheels that are connected to the differential.
struct PxVehicleFourWheelDriveDifferentialParams
PxVehicleFourWheelDriveDifferentialParams specifies the wheels that are to receive drive torque from the differential and the division of torque between the wheels that are connected to the differential. Additionally, it specifies the biases and strength of a limited slip differential that operates on two wheels specified as front wheels and two wheels specified as rear wheels.
struct PxVehicleTankDriveDifferentialParams
A description of a tank differential.
struct PxVehicleClutchCommandResponseState
struct PxVehicleEngineDriveThrottleCommandResponseState
struct PxVehicleEngineState
struct PxVehicleGearboxState
struct PxVehicleAutoboxState
struct PxVehicleDifferentialState
struct PxVehicleWheelConstraintGroupState
Specify groups of wheels that are to be constrained to have pre-determined angular velocity relationship.
struct PxVehicleClutchSlipState
The clutch is modelled as two spinning plates with one connected to the wheels through the gearing and the other connected to the engine. The clutch slip is angular speed difference of the two plates.
class PxVehiclePhysXActorBeginComponent
Work items at the beginning of an update step for a PhysX actor based vehicle.
class PxVehiclePhysXActorEndComponent
Work items at the end of an update step for a PhysX actor based vehicle.
class PxVehiclePhysXRigidActorParams
class PxVehiclePhysXRigidActorShapeParams
class PxVehiclePhysXWheelParams
class PxVehiclePhysXWheelShapeParams
struct PxVehiclePhysXActor
A description of the PhysX actor and shapes that represent the vehicle in an associated PxScene.
struct PxVehiclePhysXSteerState
A description of the previous steer command applied to the vehicle.
class PxVehiclePhysXConstraintComponent
struct PxVehiclePhysXSuspensionLimitConstraintParams
A description of the PhysX models employed to resolve suspension limit constraints.
struct PxVehiclePhysXConstraintLimits
A description of the number of PxConstraintConnector instances per vehicle required to maintain suspension limit and sticky tire instances.
struct PxVehiclePhysXConstraintState
PxVehiclePhysXConstraintState is a data structure used to write constraint data to the internal state of the associated PxScene.
class PxVehicleConstraintConnector
struct PxVehiclePhysXConstraints
A mapping between constraint state data and the associated PxConstraint instances.
class PxVehiclePhysXRoadGeometrySceneQueryComponent
struct PxVehiclePhysXRoadGeometryQueryType
PhysX scene queries may be raycasts or sweeps.
struct PxVehiclePhysXRoadGeometryQueryParams
A description of type of PhysX scene query and the filter data to apply to the query.
struct PxVehiclePhysXMaterialFriction
struct PxVehiclePhysXMaterialFrictionParams
A mappping between PxMaterial instance and friction for multiple PxMaterial intances.
struct PxVehiclePhysXRoadGeometryQueryState
class PxVehiclePVDComponent
class PxVehicleComponent
struct PxVehicleComponentSequenceLimits
struct PxVehicleComponentSequence
struct PxVehicleLimits
class PxVehicleVectorN
class PxVehicleMatrixNN
class PxVehicleMatrixNNLUSolver
class PxVehicleMatrixNGaussSeidelSolver
class PxVehicleMatrix33Solver
struct PxVehicleAxleDescription
struct PxVehicleAxes
struct PxVehicleFrame
struct PxVehicleScale
struct PxVehicleArrayData< T >
Helper struct to pass array type data to vehice components and functions.
struct PxVehicleSizedArrayData< T >
struct PxVehiclePhysXActorUpdateMode
Determine whether the PhysX actor associated with a vehicle is to be updated with a velocity change or an acceleration change. A velocity change will be immediately reflected in linear and angular velocity queries against the vehicle. An acceleration change, on the other hand, will leave the linear and angular velocities unchanged until the next PhysX scene update has applied the acceleration update to the actor's linear and angular velocities.
struct PxVehicleTireSlipParams
Tire slip values are computed using ratios with potential for divide-by-zero errors. PxVehicleTireSlipParams introduces a minimum value for the denominator of each of these ratios.
struct PxVehicleTireDirectionModes
Tires have two important directions for the purposes of tire force computation: longitudinal and lateral.
struct PxVehicleTireAxisStickyParams
The low speed regime often presents numerical difficulties for the tire model due to the potential for divide-by-zero errors. This particularly affects scenarios where the vehicle is slowing down due to damping and drag. In scenarios where there is no significant brake or drive torque, numerical error begins to dominate and it can be difficult to bring the vehicle to rest. A solution to this problem is to recognise that the vehicle is close to rest and to replace the tire forces with velocity constraints that will bring the vehicle to rest. This regime is known as the "sticky tire" regime. PxVehicleTireAxisStickyParams describes velocity and time thresholds that categorise the "sticky tire" regime. It also describes the rate at which the velocity constraints approach zero speed.
struct PxVehicleTireStickyParams
For each tire, the forces of the tire model may be replaced by velocity constraints when the tire enters the "sticky tire" regime. The "sticky tire" regime of the lateral and longitudinal directions of the tire are managed separately.
struct PxVehicleSimulationContextType
struct PxVehicleSimulationContext
struct PxVehiclePhysXSimulationContext
class PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >
Express a function as a sequence of points {(x, y)} that form a piecewise polynomial.
class PxVehicleRigidBodyComponent
Forward integrate the momentum and pose of the vehicle's rigid body after applying forces and torques from the suspension, tires and anti-roll bars.
struct PxVehicleRigidBodyParams
The properties of the rigid body.
struct PxVehicleRigidBodyState
struct PxVehicleRoadGeometryState
struct PxVehicleSteerCommandResponseParams
Distribute a steer response to the wheels of a vehicle.
struct PxVehicleAckermannParams
A description of a single axle that is to be affected by Ackermann steer correction.
class PxVehicleSuspensionComponent
class PxVehicleLegacySuspensionComponent
struct PxVehicleSuspensionParams
struct PxVehicleSuspensionJounceCalculationType
struct PxVehicleSuspensionStateCalculationParams
struct PxVehicleSuspensionComplianceParams
Compliance describes how toe and camber angle and force application points are affected by suspension compression.
struct PxVehicleSuspensionForceParams
Suspension force is computed by converting suspenson state to suspension force under the assumption of a linear spring.
struct PxVehicleSuspensionForceLegacyParams
Suspension force is computed by converting suspenson state to suspension force under the assumption of a linear spring.
struct PxVehicleAntiRollForceParams
The purpose of the anti-roll bar is to generate a torque to apply to the vehicle's rigid body that will reduce the jounce difference arising between any pair of chosen wheels. If the chosen wheels share an axle, the anti-roll bar will attempt to reduce the roll angle of the vehicle's rigid body. Alternatively, if the chosen wheels are the front and rear wheels along one side of the vehicle, the anti-roll bar will attempt to reduce the pitch angle of the vehicle's rigid body.
struct PxVehicleSuspensionState
struct PxVehicleSuspensionComplianceState
The effect of suspension compliance on toe and camber angle and on the tire and suspension force application points.
struct PxVehicleSuspensionForce
The force and torque for a single suspension to apply to the vehicle's rigid body.
struct PxVehicleAntiRollTorque
The anti-roll torque of all anti-roll bars accumulates in a single torque to apply to the vehicle's rigid body.
class PxVehicleTireComponent
class PxVehicleLegacyTireComponent
struct PxVehicleTireForceParams
struct PxVehicleTireDirectionState
PxVehicleTireDirectionState stores the world frame lateral and longtidinal axes of the tire after projecting the wheel pose in the world frame onto the road geometry plane (also in the world frame).
struct PxVehicleTireSpeedState
PxVehicleTireSpeedState stores the components of the instantaneous velocity of the rigid body at the tire contact point projected along the lateral and longitudinal axes of the tire.
struct PxVehicleTireSlipState
The lateral and longitudinal tire slips.
struct PxVehicleTireGripState
The load and friction experienced by a tire.
struct PxVehicleTireCamberAngleState
Camber angle of the tire relative to the ground plane.
struct PxVehicleTireStickyState
Prolonged low speeds in the lateral and longitudinal directions may be handled with "sticky" velocity constraints that activate after a speed below a threshold has been recorded for a threshold time.
struct PxVehicleTireForce
The longitudinal/lateral forces/torques that develop on the tire.
class PxVehicleWheelComponent
struct PxVehicleWheelParams
struct PxVehicleWheelActuationState
It is useful to know if a brake or drive torque is to be applied to a wheel.
struct PxVehicleWheelRigidBody1dState
struct PxVehicleWheelLocalPose
Macros
#define PX_VEHICLE_FOUR_WHEEL_DIFFERENTIAL_MAXIMUM_STRENGTH PX_MAX_F32
A special value that indicates instantaneous resolution of a slip that exceeds a differential bias.
#define PX_VEHICLE_NO_GEAR_SWITCH_PENDING -1.0f
#define PX_VEHICLE_GEAR_SWITCH_INITIATED -2.0f
#define PX_VEHICLE_UNSPECIFIED_TIME_SINCE_LAST_SHIFT PX_MAX_F32
#define PX_VEHICLE_UNSPECIFIED_STEER_STATE PX_MAX_F32
#define VEHICLE_FLOAT_ARRAY_DATA(b) PxVehicleArrayData<PxReal> b; b.setEmpty();
#define VEHICLE_ARRAY_DATA(a, b) PxVehicleArrayData<const a> b; b.setEmpty();
#define VEHICLE_SIZED_ARRAY_DATA(a, b) PxVehicleSizedArrayData<const a> b; b.setEmpty();
#define PX_VEHICLE_UNSPECIFIED_JOUNCE PX_MAX_F32
#define PX_VEHICLE_UNSPECIFIED_SEPARATION PX_MAX_F32
Functions
PX_FORCE_INLINE void PxVehicleBrakeCommandResponseUpdate (const PxReal *brakeCommands, const PxU32 nbBrakeCommands, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > &brakeResponseParams, PxReal &brakeResponseState)
Compute the brake torque response to an array of brake commands.
PX_FORCE_INLINE PxReal PxVehicleLinearResponseCompute (const PxReal command, const PxU32 wheelId, const PxVehicleCommandResponseParams &responseParams)
Compute the linear response to a command.
PxReal PxVehicleNonLinearResponseCompute (const PxReal command, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleCommandResponseParams &responseParams)
Compute the non-linear response to a command.
void PxVehicleDirectDriveThrottleCommandResponseUpdate (const PxReal throttle, const PxVehicleDirectDriveTransmissionCommandState &transmissionCommands, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleDirectDriveThrottleCommandResponseParams &throttleResponseParams, PxReal &throttleResponseState)
Compute the drive torque response to a throttle command.
void PxVehicleDirectDriveActuationStateUpdate (const PxReal brakeTorque, const PxReal driveTorque, PxVehicleWheelActuationState &actuationState)
Determine the actuation state of a wheel given the brake torque, handbrake torque and drive torque applied to it.
void PxVehicleDirectDriveUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleWheelActuationState &actuationState, const PxReal brakeTorque, const PxReal driveTorque, const PxVehicleTireForce &tireForce, const PxF32 dt, PxVehicleWheelRigidBody1dState &wheelRigidBody1dState)
Forward integrate the angular speed of a wheel given the brake and drive torque applied to it.
void PxVehicleAutoBoxUpdate (const PxVehicleEngineParams &engineParams, const PxVehicleGearboxParams &gearboxParams, const PxVehicleAutoboxParams &autoboxParams, const PxVehicleEngineState &engineState, const PxVehicleGearboxState &gearboxState, const PxReal dt, PxU32 &targetGearCommand, PxVehicleAutoboxState &autoboxState, PxReal &throttle)
void PxVehicleGearCommandResponseUpdate (const PxU32 targetGearCommand, const PxVehicleGearboxParams &gearboxParams, PxVehicleGearboxState &gearboxState)
Propagate input gear commands to the gearbox state.
void PxVehicleClutchCommandResponseLinearUpdate (const PxReal clutchCommand, const PxVehicleClutchCommandResponseParams &clutchResponseParams, PxVehicleClutchCommandResponseState &clutchResponse)
Propagate the input clutch command to the clutch response state.
void PxVehicleEngineDriveThrottleCommandResponseLinearUpdate (const PxVehicleCommandState &commands, PxVehicleEngineDriveThrottleCommandResponseState &throttleResponse)
Propagate the input throttle command to the throttle response state.
void PxVehicleEngineDriveActuationStateUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleGearboxParams &gearboxParams, const PxVehicleArrayData< const PxReal > &brakeResponseStates, const PxVehicleEngineDriveThrottleCommandResponseState &throttleResponseState, const PxVehicleGearboxState &gearboxState, const PxVehicleDifferentialState &diffState, const PxVehicleClutchCommandResponseState &clutchResponseState, PxVehicleArrayData< PxVehicleWheelActuationState > &actuationStates)
Determine the actuation state of all wheels on a vehicle.
void PxVehicleDifferentialStateUpdate (const PxVehicleFourWheelDriveDifferentialLegacyParams &diffParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelStates, PxVehicleDifferentialState &diffState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential.
void PxVehicleDifferentialStateUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleFourWheelDriveDifferentialParams &diffParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelStates, const PxReal dt, PxVehicleDifferentialState &diffState, PxVehicleWheelConstraintGroupState &wheelConstraintGroupState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential. Additionally, add wheel constraints for wheel pairs whose rotational speed ratio exceeds the corresponding differential bias.
void PxVehicleDifferentialStateUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleMultiWheelDriveDifferentialParams &diffParams, PxVehicleDifferentialState &diffState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential.
void PxVehicleDifferentialStateUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, const PxVehicleTankDriveDifferentialParams &diffParams, const PxReal thrustCommand0, PxReal thrustCommand1, PxVehicleDifferentialState &diffState, PxVehicleWheelConstraintGroupState &wheelConstraintGroupState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential.
void PxVehicleGearboxUpdate (const PxVehicleGearboxParams &gearboxParams, const PxF32 dt, PxVehicleGearboxState &gearboxState)
Update the current gear of the gearbox. If a gear change is ongoing then complete the gear change if a threshold time has passed since the beginning of the gear change.
void PxVehicleEngineDrivetrainUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, const PxVehicleEngineParams &engineParams, const PxVehicleClutchParams &clutchParams, const PxVehicleGearboxParams &gearboxParams, const PxVehicleArrayData< const PxReal > &brakeResponseStates, const PxVehicleArrayData< const PxVehicleWheelActuationState > &actuationStates, const PxVehicleArrayData< const PxVehicleTireForce > &tireForces, const PxVehicleGearboxState &gearboxState, const PxVehicleEngineDriveThrottleCommandResponseState &throttleResponse, const PxVehicleClutchCommandResponseState &clutchResponse, const PxVehicleDifferentialState &diffState, const PxVehicleWheelConstraintGroupState *constraintGroupState, const PxReal dt, PxVehicleArrayData< PxVehicleWheelRigidBody1dState > &wheelRigidbody1dStates, PxVehicleEngineState &engineState, PxVehicleClutchSlipState &clutchState)
Forward integrate the angular speed of the vehicle's wheels and engine, given the state of clutch, differential and gearbox.
PX_FORCE_INLINE PxReal PxVehicleClutchStrengthCompute (const PxVehicleClutchCommandResponseState &clutchResponseState, const PxVehicleGearboxParams &gearboxParams, const PxVehicleGearboxState &gearboxState)
Compute the coupling strength of the clutch.
PX_FORCE_INLINE PxReal PxVehicleEngineDampingRateCompute (const PxVehicleEngineParams &engineParams, const PxVehicleGearboxParams &gearboxParams, const PxVehicleGearboxState &gearboxState, const PxVehicleClutchCommandResponseState &clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState &throttleResponseState)
Compute the damping rate of the engine.
PX_FORCE_INLINE PxReal PxVehicleGearRatioCompute (const PxVehicleGearboxParams &gearboxParams, const PxVehicleGearboxState &gearboxState)
Compute the gear ratio delivered by the gearbox in the current gear.
PX_FORCE_INLINE PxReal PxVehicleEngineDriveTorqueCompute (const PxVehicleEngineParams &engineParams, const PxVehicleEngineState &engineState, const PxVehicleEngineDriveThrottleCommandResponseState &throttleCommandResponseState)
Compute the drive torque to deliver to the engine.
void PxVehicleLegacyDifferentialWheelSpeedContributionsCompute (const PxVehicleFourWheelDriveDifferentialLegacyParams &diffParams, PxReal diffAveWheelSpeedContributions[PxVehicleLimits::eMAX_NB_WHEELS])
Compute the contribution that each wheel makes to the averaged wheel speed at the clutch plate connected to the wheels driven by the differential.
void PxVehicleLegacyDifferentialTorqueRatiosCompute (const PxVehicleFourWheelDriveDifferentialLegacyParams &diffParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelOmegas, PxReal diffTorqueRatios[PxVehicleLimits::eMAX_NB_WHEELS])
Compute the fraction of available torque that is delivered to each wheel through the differential.
void PxVehiclePhysxActorWakeup (const PxVehicleCommandState &commands, const PxVehicleEngineDriveTransmissionCommandState *transmissionCommands, const PxVehicleGearboxParams *gearParams, const PxVehicleGearboxState *gearState, PxRigidBody &physxActor, PxVehiclePhysXSteerState &physxSteerState)
Wake up the physx actor if the actor is asleep and the commands signal an intent to change the state of the vehicle.
bool PxVehiclePhysxActorSleepCheck (const PxVehicleAxleDescription &axleDescription, const PxRigidBody &physxActor, const PxVehicleEngineParams *engineParams, PxVehicleRigidBodyState &rigidBodyState, PxVehiclePhysXConstraints &physxConstraints, PxVehicleArrayData< PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, PxVehicleEngineState *engineState)
Check if the physx actor is sleeping and clear certain vehicle states if it is.
void PxVehiclePhysxActorKeepAwakeCheck (const PxVehicleAxleDescription &axleDescription, const PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, const PxReal wakeCounterThreshold, const PxReal wakeCounterResetValue, const PxVehicleGearboxState *gearState, PxRigidBody &physxActor)
Check if the physx actor has to be kept awake.
void PxVehicleReadRigidBodyStateFromPhysXActor (const PxRigidBody &physxActor, PxVehicleRigidBodyState &rigidBodyState)
Read the rigid body state from a PhysX actor.
void PxVehicleWriteWheelLocalPoseToPhysXWheelShape (const PxTransform &wheelLocalPose, const PxTransform &wheelShapeLocalPose, PxShape *shape)
Update the local pose of a PxShape that is associated with a wheel.
void PxVehicleWriteRigidBodyStateToPhysXActor (const PxVehiclePhysXActorUpdateMode::Enum physxActorUpdateMode, const PxVehicleRigidBodyState &rigidBodyState, const PxReal dt, PxRigidBody &physXActor)
Write the rigid body state to a PhysX actor.
void PxVehiclePhysXActorCreate (const PxVehicleFrame &vehicleFrame, const PxVehiclePhysXRigidActorParams &rigidActorParams, const PxTransform &rigidActorCmassLocalPose, const PxVehiclePhysXRigidActorShapeParams &rigidActorShapeParams, const PxVehiclePhysXWheelParams &wheelParams, const PxVehiclePhysXWheelShapeParams &wheelShapeParams, PxPhysics &physics, const PxCookingParams &params, PxVehiclePhysXActor &vehiclePhysXActor)
Create a PxRigidDynamic instance, instantiate it with desired properties and populate it with PxShape instances.
void PxVehiclePhysXActorConfigure (const PxVehiclePhysXRigidActorParams &rigidActorParams, const PxTransform &rigidActorCmassLocalPose, PxRigidBody &rigidBody)
Configure an actor so that it is ready for vehicle simulation.
void PxVehiclePhysXArticulationLinkCreate (const PxVehicleFrame &vehicleFrame, const PxVehiclePhysXRigidActorParams &rigidActorParams, const PxTransform &rigidActorCmassLocalPose, const PxVehiclePhysXRigidActorShapeParams &rigidActorShapeParams, const PxVehiclePhysXWheelParams &wheelParams, const PxVehiclePhysXWheelShapeParams &wheelShapeParams, PxPhysics &physics, const PxCookingParams &params, PxVehiclePhysXActor &vehiclePhysXActor)
Create a PxArticulationReducedCoordinate and a single PxArticulationLink, instantiate the PxArticulationLink with desired properties and populate it with PxShape instances.
void PxVehiclePhysXActorDestroy (PxVehiclePhysXActor &vehiclePhysXActor)
Release the PxRigidDynamic, PxArticulationReducedCoordinate, PxArticulationLink and PxShape instances instantiated by PxVehiclePhysXActorCreate or PxVehiclePhysXArticulationLinkCreate.
void PxVehiclePhysXConstraintStatesUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxVehiclePhysXSuspensionLimitConstraintParams &suspensionLimitParams, const PxVehicleSuspensionState &suspensionState, const PxVehicleSuspensionComplianceState &suspensionComplianceState, const PxVec3 &groundPlaneNormal, const PxReal tireStickyDampingLong, const PxReal tireStickyDampingLat, const PxVehicleTireDirectionState &tireDirectionState, const PxVehicleTireStickyState &tireStickyState, const PxVehicleRigidBodyState &rigidBodyState, PxVehiclePhysXConstraintState &constraintState)
Read constraint data from the vehicle's internal state for a single wheel and write it to a structure that will be read by the associated PxScene and used to impose the constraints during the next PxScene::simulate() step.
void PxVehicleConstraintsCreate (const PxVehicleAxleDescription &axleDescription, PxPhysics &physics, PxRigidBody &physxActor, PxVehiclePhysXConstraints &vehicleConstraints)
Instantiate the PhysX custom constraints that will resolve excess suspension compression and velocity constraints that serve as a replacement low speed tire model.
void PxVehicleConstraintsDirtyStateUpdate (PxVehiclePhysXConstraints &vehicleConstraints)
To ensure the constraints are processed by the PhysX scene they are marked as dirty prior to each simulate step.
void PxVehicleConstraintsDestroy (PxVehiclePhysXConstraints &vehicleConstraints)
Destroy the PhysX custom constraints.
PX_FORCE_INLINE PxU32 vehicleConstraintSolverPrep (Px1DConstraint *constraints, PxVec3p &body0WorldOffset, PxU32 maxConstraints, PxConstraintInvMassScale &, const void *constantBlock, const PxTransform &bodyAToWorld, const PxTransform &bodyBToWorld, bool, PxVec3p &cA2w, PxVec3p &cB2w)
PX_FORCE_INLINE void visualiseVehicleConstraint (PxConstraintVisualizer &viz, const void *constantBlock, const PxTransform &body0Transform, const PxTransform &body1Transform, PxU32 flags)
void PxVehiclePhysXRoadGeometryQueryUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleSuspensionParams &suspParams, const PxVehiclePhysXRoadGeometryQueryParams &roadGeomParams, const PxVehiclePhysXMaterialFrictionParams &materialFrictionParams, const PxReal wheelYawAngle, const PxVehicleRigidBodyState &rigidBodyState, const PxScene &scene, const PxConvexMesh *unitCylinderSweepMesh, const PxVehicleFrame &frame, PxVehicleRoadGeometryState &roadGeomState, PxVehiclePhysXRoadGeometryQueryState *physxRoadGeometryState)
Compute the plane of the road geometry under a wheel and the tire friction of the contact.
PxConvexMesh * PxVehicleUnitCylinderSweepMeshCreate (const PxVehicleFrame &vehicleFrame, PxPhysics &physics, const PxCookingParams &params)
Create a cylindrical mesh with unit radius and half-width.
void PxVehicleUnitCylinderSweepMeshDestroy (PxConvexMesh *mesh)
Release the mesh created with PxVehicleUnitCylinderSweepMeshCreate.
void PxVehiclePvdRigidBodyRegister (const PxVehicleRigidBodyParams *rbodyParams, const PxVehicleRigidBodyState *rbodyState, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Create object instances in omnipvd that will be used to reflect the parameters and state of the rigid body of a vehicle instance. Handles to the created object instances will be stored in a PxVehiclePvdObjectHandles instance.
void PxVehiclePvdRigidBodyWrite (const PxVehicleRigidBodyParams *rbodyParams, const PxVehicleRigidBodyState *rbodyState, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write the parameters and state of the rigid body of a vehicle instance to omnipvd.
void PxVehiclePvdSuspensionStateCalculationParamsRegister (const PxVehicleSuspensionStateCalculationParams *suspStateCalcParams, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register object instances in omnipvd that will be used to reflect the suspension state calculation parameters of a vehicle instance.
void PxVehiclePvdSuspensionStateCalculationParamsWrite (const PxVehicleSuspensionStateCalculationParams *suspStateCalcParams, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write the parameters and state of the rigid body of a vehicle instance to omnipvd.
void PxVehiclePvdCommandResponseRegister (const PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > &brakeResponseParams, const PxVehicleSteerCommandResponseParams *steerResponseParams, const PxVehicleArrayData< PxReal > &brakeResponseStates, const PxVehicleArrayData< PxReal > &steerResponseStates, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register object instances in omnipvd that will be used to reflect the brake and steer command response parameters of a vehicle instance.
void PxVehiclePvdCommandResponseWrite (const PxVehicleAxleDescription &axleDesc, const PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > &brakeResponseParams, const PxVehicleSteerCommandResponseParams *steerResponseParams, const PxVehicleArrayData< PxReal > &brakeResponseStates, const PxVehicleArrayData< PxReal > &steerResponseStates, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write brake and steer command response parameters to omnipvd.
void PxVehiclePvdWheelAttachmentsRegister (const PxVehicleAxleDescription &axleDesc, const PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, const PxVehicleArrayData< const PxVehicleWheelActuationState > &wheelActuationStates, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, const PxVehicleArrayData< const PxVehicleWheelLocalPose > &wheelLocalPoses, const PxVehicleArrayData< const PxVehicleRoadGeometryState > &roadGeometryStates, const PxVehicleArrayData< const PxVehicleSuspensionParams > &suspParams, const PxVehicleArrayData< const PxVehicleSuspensionComplianceParams > &suspCompParams, const PxVehicleArrayData< const PxVehicleSuspensionForceParams > &suspForceParams, const PxVehicleArrayData< const PxVehicleSuspensionState > &suspStates, const PxVehicleArrayData< const PxVehicleSuspensionComplianceState > &suspCompStates, const PxVehicleArrayData< const PxVehicleSuspensionForce > &suspForces, const PxVehicleArrayData< const PxVehicleTireForceParams > &tireForceParams, const PxVehicleArrayData< const PxVehicleTireDirectionState > &tireDirectionStates, const PxVehicleArrayData< const PxVehicleTireSpeedState > &tireSpeedStates, const PxVehicleArrayData< const PxVehicleTireSlipState > &tireSlipStates, const PxVehicleArrayData< const PxVehicleTireStickyState > &tireStickyStates, const PxVehicleArrayData< const PxVehicleTireGripState > &tireGripStates, const PxVehicleArrayData< const PxVehicleTireCamberAngleState > &tireCamberStates, const PxVehicleArrayData< const PxVehicleTireForce > &tireForces, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register object instances in omnipvd that will be used to reflect wheel attachment data such as tires, suspensions and wheels.
void PxVehiclePvdWheelAttachmentsWrite (const PxVehicleAxleDescription &axleDesc, const PxVehicleArrayData< const PxVehicleWheelParams > &wheelParams, const PxVehicleArrayData< const PxVehicleWheelActuationState > &wheelActuationStates, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > &wheelRigidBody1dStates, const PxVehicleArrayData< const PxVehicleWheelLocalPose > &wheelLocalPoses, const PxVehicleArrayData< const PxVehicleRoadGeometryState > &roadGeometryStates, const PxVehicleArrayData< const PxVehicleSuspensionParams > &suspParams, const PxVehicleArrayData< const PxVehicleSuspensionComplianceParams > &suspCompParams, const PxVehicleArrayData< const PxVehicleSuspensionForceParams > &suspForceParams, const PxVehicleArrayData< const PxVehicleSuspensionState > &suspStates, const PxVehicleArrayData< const PxVehicleSuspensionComplianceState > &suspCompStates, const PxVehicleArrayData< const PxVehicleSuspensionForce > &suspForces, const PxVehicleArrayData< const PxVehicleTireForceParams > &tireForceParams, const PxVehicleArrayData< const PxVehicleTireDirectionState > &tireDirectionStates, const PxVehicleArrayData< const PxVehicleTireSpeedState > &tireSpeedStates, const PxVehicleArrayData< const PxVehicleTireSlipState > &tireSlipStates, const PxVehicleArrayData< const PxVehicleTireStickyState > &tireStickyStates, const PxVehicleArrayData< const PxVehicleTireGripState > &tireGripStates, const PxVehicleArrayData< const PxVehicleTireCamberAngleState > &tireCamberStates, const PxVehicleArrayData< const PxVehicleTireForce > &tireForces, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write wheel attachment data such as tire, suspension and wheel data to omnipvd.
void PxVehiclePvdAntiRollsRegister (const PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > &antiRollForceParams, const PxVehicleAntiRollTorque *antiRollTorque, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register object instances in omnipvd that will be used to reflect the antiroll bars of a vehicle instance.
void PxVehiclePvdAntiRollsWrite (const PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > &antiRollForceParams, const PxVehicleAntiRollTorque *antiRollTorque, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write antiroll data to omnipvd.
void PxVehiclePvdDirectDrivetrainRegister (const PxVehicleCommandState *commandState, const PxVehicleDirectDriveTransmissionCommandState *transmissionCommandState, const PxVehicleDirectDriveThrottleCommandResponseParams *directDriveThrottleResponseParams, const PxVehicleArrayData< PxReal > &directDriveThrottleResponseState, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register object instances in omnipvd that will be used to reflect the direct drivetrain of a vehicle instance.
void PxVehiclePvdDirectDrivetrainWrite (const PxVehicleAxleDescription &axleDesc, const PxVehicleCommandState *commandState, const PxVehicleDirectDriveTransmissionCommandState *transmissionCommandState, const PxVehicleDirectDriveThrottleCommandResponseParams *directDriveThrottleResponseParams, const PxVehicleArrayData< PxReal > &directDriveThrottleResponseState, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write direct drivetrain data to omnipvd.
void PxVehiclePvdEngineDrivetrainRegister (const PxVehicleCommandState *commandState, const PxVehicleEngineDriveTransmissionCommandState *transmissionCommandState, const PxVehicleClutchCommandResponseParams *clutchResponseParams, const PxVehicleClutchParams *clutchParams, const PxVehicleEngineParams *engineParams, const PxVehicleGearboxParams *gearboxParams, const PxVehicleAutoboxParams *autoboxParams, const PxVehicleMultiWheelDriveDifferentialParams *multiWheelDiffParams, const PxVehicleFourWheelDriveDifferentialParams *fourWheelDiffPrams, const PxVehicleClutchCommandResponseState *clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState *throttleResponseState, const PxVehicleEngineState *engineState, const PxVehicleGearboxState *gearboxState, const PxVehicleAutoboxState *autoboxState, const PxVehicleDifferentialState *diffState, const PxVehicleClutchSlipState *clutchSlipState, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register object instances in omnipvd that will be used to reflect the engine drivetrain of a vehicle instance.
void PxVehiclePvdEngineDrivetrainWrite (const PxVehicleCommandState *commandState, const PxVehicleEngineDriveTransmissionCommandState *transmissionCommandState, const PxVehicleClutchCommandResponseParams *clutchResponseParams, const PxVehicleClutchParams *clutchParams, const PxVehicleEngineParams *engineParams, const PxVehicleGearboxParams *gearboxParams, const PxVehicleAutoboxParams *autoboxParams, const PxVehicleMultiWheelDriveDifferentialParams *multiWheelDiffParams, const PxVehicleFourWheelDriveDifferentialParams *fourWheelDiffPrams, const PxVehicleClutchCommandResponseState *clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState *throttleResponseState, const PxVehicleEngineState *engineState, const PxVehicleGearboxState *gearboxState, const PxVehicleAutoboxState *autoboxState, const PxVehicleDifferentialState *diffState, const PxVehicleClutchSlipState *clutchSlipState, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write engine drivetrain data of a vehicle instance to omnipvd.
void PxVehiclePvdPhysXWheelAttachmentRegister (const PxVehicleAxleDescription &axleDesc, const PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > &physxSuspLimitConstraintParams, const PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > &physxMaterialFrictionParams, const PxVehiclePhysXActor *physxActor, const PxVehiclePhysXRoadGeometryQueryParams *physxRoadGeometryQueryParams, const PxVehicleArrayData< const PxVehiclePhysXRoadGeometryQueryState > &physxRoadGeomState, const PxVehicleArrayData< const PxVehiclePhysXConstraintState > &physxConstraintStates, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register per wheel attachment data that involves the vehicle's integration with a PhysX scene.
void PxVehiclePvdPhysXWheelAttachmentWrite (const PxVehicleAxleDescription &axleDesc, const PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > &physxSuspLimitConstraintParams, const PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > &physxMaterialFrictionParams, const PxVehiclePhysXActor *physxActor, const PxVehiclePhysXRoadGeometryQueryParams *physxRoadGeometryQueryParams, const PxVehicleArrayData< const PxVehiclePhysXRoadGeometryQueryState > &physxRoadGeomState, const PxVehicleArrayData< const PxVehiclePhysXConstraintState > &physxConstraintStates, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write to omnipvd the per wheel attachment data that involves the vehicle's integration with a PhysX scene.
void PxVehiclePvdPhysXRigidActorRegister (const PxVehiclePhysXActor *physxActor, const PxVehiclePvdAttributeHandles &attributeHandles, PxVehiclePvdObjectHandles *objectHandles, OmniPvdWriter *omniWriter)
Register the PxRigidActor instance that represents the vehicle's rigid body in a PhysX scene.
void PxVehiclePvdPhysXRigidActorWrite (const PxVehiclePhysXActor *physxActor, const PxVehiclePvdAttributeHandles &attributeHandles, const PxVehiclePvdObjectHandles &objectHandles, OmniPvdWriter *omniWriter)
Write the PxRigidActor instance to omnipvd.
PxVehiclePvdAttributeHandles * PxVehiclePvdAttributesCreate (PxAllocatorCallback &allocator, OmniPvdWriter *omniWriter)
Create the attribute handles necessary to reflect vehicles in omnipvd.
void PxVehiclePvdAttributesRelease (PxAllocatorCallback &allocator, OmniPvdWriter *omniWriter, PxVehiclePvdAttributeHandles *attributeHandles)
Destory the attribute handles created by PxVehiclePvdAttributesCreate().
PxVehiclePvdObjectHandles * PxVehiclePvdObjectCreate (const PxU32 nbWheels, const PxU32 nbAntirolls, const PxU32 maxNbPhysxMaterialFrictions, const PxU64 contextHandle, const PxVehiclePvdAttributeHandles &attributeHandles, OmniPvdWriter *omniWriter, PxAllocatorCallback &allocator)
Create omnipvd objects that will be used to reflect an individual veicle in omnipvd.
void PxVehiclePvdObjectRelease (const PxVehiclePvdAttributeHandles &attributeHandles, OmniPvdWriter *omniWriter, PxAllocatorCallback &allocator, PxVehiclePvdObjectHandles *objectHandles)
Destroy the PxVehiclePvdObjectHandles instance created by PxVehiclePvdObjectCreate().
PX_FORCE_INLINE bool PxInitVehicleExtension (physx::PxFoundation &foundation)
Initialize the PhysX Vehicle library.
PX_FORCE_INLINE void PxCloseVehicleExtension ()
Shut down the PhysX Vehicle library.
PX_FORCE_INLINE PxVec3 PxVehicleTransformFrameToFrame (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVec3 &v)
PX_FORCE_INLINE PxVec3 PxVehicleTransformFrameToFrame (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale, const PxVec3 &v)
PX_FORCE_INLINE PxTransform PxVehicleTransformFrameToFrame (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale, const PxTransform &v)
PX_FORCE_INLINE PxVec3 PxVehicleComputeTranslation (const PxVehicleFrame &frame, const PxReal lng, const PxReal lat, const PxReal vrt)
PX_FORCE_INLINE PxQuat PxVehicleComputeRotation (const PxVehicleFrame &frame, const PxReal roll, const PxReal pitch, const PxReal yaw)
PX_FORCE_INLINE PxF32 PxVehicleComputeSign (const PxReal f)
PX_FORCE_INLINE void PxVehicleShiftOrigin (const PxVehicleAxleDescription &axleDesc, const PxVec3 &shift, PxVehicleRigidBodyState &rigidBodyState, PxVehicleRoadGeometryState *roadGeometryStates, PxVehiclePhysXActor *physxActor=NULL, PxVehiclePhysXRoadGeometryQueryState *physxQueryStates=NULL)
Shift the origin of a vehicle by the specified vector.
void PxVehicleRigidBodyUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleRigidBodyParams &rigidBodyParams, const PxVehicleArrayData< const PxVehicleSuspensionForce > &suspensionForces, const PxVehicleArrayData< const PxVehicleTireForce > &tireForces, const PxVehicleAntiRollTorque *antiRollTorque, const PxReal dt, const PxVec3 &gravity, PxVehicleRigidBodyState &rigidBodyState)
Forward integrate rigid body state.
void PxVehicleSteerCommandResponseUpdate (const PxReal steer, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleSteerCommandResponseParams &steerResponseParmas, PxReal &steerResponseState)
Compute the yaw angle response to a steer command.
void PxVehicleAckermannSteerUpdate (const PxReal steer, const PxVehicleSteerCommandResponseParams &steerResponseParmas, const PxVehicleSizedArrayData< const PxVehicleAckermannParams > &ackermannParams, PxVehicleArrayData< PxReal > &steerResponseStates)
Account for Ackermann correction by modifying the per wheel steer response multipliers to engineer an asymmetric steer response across axles.
void PxVehicleSuspensionStateUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionStateCalculationParams &suspensionStateCalcParams, const PxReal suspensionStiffness, const PxReal suspensionDamping, const PxReal steerAngle, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleRigidBodyState &rigidBodyState, const PxReal dt, const PxVehicleFrame &frame, const PxVec3 &gravity, PxVehicleSuspensionState &suspState)
Compute the suspension compression and compression speed for a single suspension.
void PxVehicleSuspensionComplianceUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionComplianceParams &complianceParams, const PxVehicleSuspensionState &suspensionState, PxVehicleSuspensionComplianceState &complianceState)
Compute the toe, camber and force application points that are affected by suspension compression.
void PxVehicleSuspensionForceUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionForceParams &suspensionForceParams, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleSuspensionState &suspensionState, const PxVehicleSuspensionComplianceState &complianceState, const PxVehicleRigidBodyState &rigidBodyState, const PxVec3 &gravity, const PxReal vehicleMass, PxVehicleSuspensionForce &suspensionForce)
Compute the suspension force and torque arising from suspension compression and speed.
PX_DEPRECATED void PxVehicleSuspensionLegacyForceUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionForceLegacyParams &suspensionForceParams, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleSuspensionState &suspensionState, const PxVehicleSuspensionComplianceState &complianceState, const PxVehicleRigidBodyState &rigidBodyState, const PxVec3 &gravity, PxVehicleSuspensionForce &suspensionForce)
Compute the suspension force and torque arising from suspension compression and speed.
void PxVehicleAntiRollForceUpdate (const PxVehicleArrayData< const PxVehicleSuspensionParams > &suspensionParams, const PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > &antiRollParams, const PxVehicleArrayData< const PxVehicleSuspensionState > &suspensionStates, const PxVehicleArrayData< const PxVehicleSuspensionComplianceState > &complianceStates, const PxVehicleRigidBodyState &rigidBodyState, PxVehicleAntiRollTorque &antiRollTorque)
Compute the accumulated anti-roll torque to apply to the vehicle's rigid body.
PX_FORCE_INLINE PxVec3 PxVehicleComputeSuspensionDirection (const PxVehicleSuspensionParams &suspensionParams, const PxTransform &rigidBodyPose)
Compute suspension travel direction in the world frame.
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelPoseForSuspensionQuery (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxReal steerAngle, const PxTransform &rigidBodyPose)
Compute the start pose of a suspension query.
PX_FORCE_INLINE void PxVehicleComputeSuspensionRaycast (const PxVehicleFrame &frame, const PxVehicleWheelParams &wheelParams, const PxVehicleSuspensionParams &suspensionParams, const PxF32 steerAngle, const PxTransform &rigidBodyPose, PxVec3 &start, PxVec3 &dir, PxReal &dist)
Compute the start point, direction and length of a suspension scene raycast.
PX_FORCE_INLINE void PxVehicleComputeSuspensionSweep (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxReal steerAngle, const PxTransform &rigidBodyPose, PxTransform &start, PxVec3 &dir, PxReal &dist)
Compute the start pose, direction and length of a suspension scene sweep.
bool PxVehicleComputeSprungMasses (const PxU32 nbSprungMasses, const PxVec3 *sprungMassCoordinates, const PxReal totalMass, const PxVehicleAxes::Enum gravityDirection, PxReal *sprungMasses)
Compute the sprung masses of the suspension springs given (i) the number of sprung masses, (ii) coordinates of the sprung masses in the rigid body frame, (iii) the center of mass offset of the rigid body, (iv) the total mass of the rigid body, and (v) the direction of gravity.
PX_DEPRECATED void PxVehicleTireDirsLegacyUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxReal steerAngle, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleRigidBodyState &rigidBodyState, const PxVehicleFrame &frame, PxVehicleTireDirectionState &tireDirectionState)
Compute the longitudinal and lateral tire directions in the ground plane.
void PxVehicleTireDirsUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxReal steerAngle, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleSuspensionComplianceState &complianceState, const PxVehicleRigidBodyState &rigidBodyState, const PxVehicleFrame &frame, PxVehicleTireDirectionState &tireDirectionState)
Compute the longitudinal and lateral tire directions in the ground plane.
void PxVehicleTireSlipSpeedsUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleSuspensionParams &suspensionParams, const PxF32 steerAngle, const PxVehicleSuspensionState &suspensionStates, const PxVehicleTireDirectionState &tireDirectionState, const PxVehicleRigidBodyState &rigidBodyState, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleFrame &frame, PxVehicleTireSpeedState &tireSpeedState)
Project the rigid body velocity at the tire contact point along the tire longitudinal directions.
void PxVehicleTireSlipsUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleTireSlipParams &tireSlipParams, const PxVehicleWheelActuationState &actuationState, PxVehicleTireSpeedState &tireSpeedState, const PxVehicleWheelRigidBody1dState &wheelRigidBody1dState, PxVehicleTireSlipState &tireSlipState)
Compute a tire's longitudinal and lateral slip angles.
void PxVehicleTireSlipsLegacyUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleTireSlipParams &tireSlipParams, const PxVehicleWheelActuationState &actuationState, PxVehicleTireSpeedState &tireSpeedState, const PxVehicleWheelRigidBody1dState &wheelRigidBody1dState, PxVehicleTireSlipState &tireSlipState)
Compute a tire's longitudinal and lateral slip angles.
void PxVehicleTireCamberAnglesUpdate (const PxVehicleSuspensionParams &suspensionParams, const PxReal steerAngle, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleSuspensionComplianceState &complianceState, const PxVehicleRigidBodyState &rigidBodyState, const PxVehicleFrame &frame, PxVehicleTireCamberAngleState &tireCamberAngleState)
Compute the camber angle of the wheel.
void PxVehicleTireGripUpdate (const PxVehicleTireForceParams &tireForceParams, const PxVehicleRoadGeometryState &roadGeometryState, const PxVehicleSuspensionState &suspensionState, const PxVehicleSuspensionForce &suspensionForce, const PxVehicleTireSlipState &tireSlipState, PxVehicleTireGripState &tireGripState)
Compute the load and friction experienced by the tire.
void PxVehicleTireStickyStateUpdate (const PxVehicleAxleDescription &axleDescription, const PxVehicleWheelParams &wheelParams, const PxVehicleTireStickyParams &tireStickyParams, const PxVehicleArrayData< const PxVehicleWheelActuationState > &actuationStates, const PxVehicleTireGripState &tireGripState, const PxVehicleTireSpeedState &tireSpeedState, const PxVehicleWheelRigidBody1dState &wheelRigidBody1dState, const PxReal dt, PxVehicleTireStickyState &tireStickyState)
When a tire has been at a very low speed for a threshold time without application of drive torque, a secondary tire model is applied to bring the tire to rest using velocity constraints that asymptotically approach zero speed along the tire's lateral and longitudinal directions. This secondary tire model is referred to as the sticky tire model and the tire is considered to be in the sticky tire state when the speed and time conditions are satisfied. The purpose of PxVehicleTireStickyStateUpdate is to compute the target speeds of the sticky state and to record whether sticky state is active or not.
void PxVehicleTireSlipsAccountingForStickyStatesUpdate (const PxVehicleTireStickyState &tireStickyState, PxVehicleTireSlipState &tireSlipState)
Set the tire longitudinal and lateral slip values to 0.0 in the event that the tire has entred tire sticky state. This is necessary to avoid both tire models being simultaneously active and interfering with each other.
void PxVehicleTireForcesUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleSuspensionParams &suspensionParams, const PxVehicleTireForceParams &tireForceParams, const PxVehicleSuspensionComplianceState &complianceState, const PxVehicleTireGripState &tireGripState, const PxVehicleTireDirectionState &tireDirectionState, const PxVehicleTireSlipState &tireSlipState, const PxVehicleTireCamberAngleState &tireCamberAngleState, const PxVehicleRigidBodyState &rigidBodyState, PxVehicleTireForce &tireForce)
Compute the longitudinal and lateral forces in the world frame that develop on the tire as a consequence of the tire's slip angles, friction and load.
bool PxVehicleAccelerationIntentCompute (const PxVehicleAxleDescription &poweredVehicleAxleDesc, const PxVehicleArrayData< const PxVehicleWheelActuationState > &poweredVehicleActuationStates)
Compute the intention to accelerate by inspecting the actuation states of the wheels of a powered vehicle.
void PxVehicleTireStickyStateReset (const bool poweredVehicleIntentionToAccelerate, const PxVehicleAxleDescription &unpoweredVehicleAxleDesc, PxVehicleArrayData< PxVehicleTireStickyState > &unpoweredVehicleStickyState)
Reset the sticky tire states of an unpowered vehicle if it is in a jointed ensemble of vehicles with at least one powered vehicle.
void PxVehicleWheelRotationAngleUpdate (const PxVehicleWheelParams &wheelParams, const PxVehicleWheelActuationState &actuationState, const PxVehicleSuspensionState &suspensionState, const PxVehicleTireSpeedState &tireSpeedState, const PxReal thresholdForwardSpeedForWheelAngleIntegration, const PxReal dt, PxVehicleWheelRigidBody1dState &wheelRigidBody1dState)
Forward integrate the rotation angle of a wheel.
PX_FORCE_INLINE PxQuat PxVehicleComputeWheelLocalOrientation (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxReal rotationAngle)
Compute the quaternion of a wheel in the rigid body frame.
PX_FORCE_INLINE PxQuat PxVehicleComputeWheelOrientation (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxQuat &rigidBodyOrientation, const PxReal rotationAngle)
Compute the quaternion of a wheel in the world frame.
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelLocalPose (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionState &suspensionState, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxReal rotationAngle)
Compute the pose of the wheel in the rigid body frame.
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelLocalPose (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionState &suspensionState, const PxVehicleSuspensionComplianceState &suspensionComplianceState, const PxReal steerAngle, const PxVehicleWheelRigidBody1dState &wheelState)
Compute the pose of the wheel in the rigid body frame.
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelPose (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionState &suspensionState, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxTransform &rigidBodyPose, const PxReal rotationAngle)
Compute the pose of the wheel in the world frame.
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelPose (const PxVehicleFrame &frame, const PxVehicleSuspensionParams &suspensionParams, const PxVehicleSuspensionState &suspensionState, const PxVehicleSuspensionComplianceState &suspensionComplianceState, const PxReal steerAngle, const PxTransform &rigidBodyPose, const PxVehicleWheelRigidBody1dState &wheelState)
Compute the pose of the wheel in the world frame.
PX_FORCE_INLINE bool PxVehicleIsWheelOnGround (const PxVehicleSuspensionState &suspState)
Check if the suspension could place the wheel on the ground or not.
PX_FORCE_INLINE bool PxVehicleComponentSequence::add (PxVehicleComponent *component)
Add a component to the sequence.
PX_FORCE_INLINE PxU8 PxVehicleComponentSequence::beginSubstepGroup (const PxU8 nbSubSteps=1)
Start a substepping group.
Detailed Description
Macro Definition Documentation
PX_VEHICLE_FOUR_WHEEL_DIFFERENTIAL_MAXIMUM_STRENGTH
#define PX_VEHICLE_FOUR_WHEEL_DIFFERENTIAL_MAXIMUM_STRENGTH PX_MAX_F32
A special value that indicates instantaneous resolution of a slip that exceeds a differential bias.
PX_VEHICLE_GEAR_SWITCH_INITIATED
#define PX_VEHICLE_GEAR_SWITCH_INITIATED -2.0f
PX_VEHICLE_NO_GEAR_SWITCH_PENDING
#define PX_VEHICLE_NO_GEAR_SWITCH_PENDING -1.0f
Referenced by PxVehicleGearboxState::setToDefault().
PX_VEHICLE_UNSPECIFIED_JOUNCE
#define PX_VEHICLE_UNSPECIFIED_JOUNCE PX_MAX_F32
Referenced by PxVehicleComputeWheelLocalPose().
PX_VEHICLE_UNSPECIFIED_SEPARATION
#define PX_VEHICLE_UNSPECIFIED_SEPARATION PX_MAX_F32
PX_VEHICLE_UNSPECIFIED_STEER_STATE
#define PX_VEHICLE_UNSPECIFIED_STEER_STATE PX_MAX_F32
Referenced by PxVehiclePhysXSteerState::setToDefault().
PX_VEHICLE_UNSPECIFIED_TIME_SINCE_LAST_SHIFT
#define PX_VEHICLE_UNSPECIFIED_TIME_SINCE_LAST_SHIFT PX_MAX_F32
Referenced by PxVehicleAutoboxState::setToDefault().
VEHICLE_ARRAY_DATA
#define VEHICLE_ARRAY_DATA (a, b) PxVehicleArrayData<const a> b; b.setEmpty();
Referenced by PxVehiclePVDComponent::update().
VEHICLE_FLOAT_ARRAY_DATA
#define VEHICLE_FLOAT_ARRAY_DATA (b) PxVehicleArrayData<PxReal> b; b.setEmpty();
Referenced by PxVehiclePVDComponent::update().
VEHICLE_SIZED_ARRAY_DATA
#define VEHICLE_SIZED_ARRAY_DATA (a, b) PxVehicleSizedArrayData<const a> b; b.setEmpty();
Referenced by PxVehiclePVDComponent::update().
Function Documentation
add()
bool PxVehicleComponentSequence::add (PxVehicleComponent * component)
Add a component to the sequence.
Parameters
[in] component The component to add to the sequence.
Returns
True on success, else false (for example due to component count limit being reached).
References PxVehicleComponentSequence::SubGroupElement::childGroup, PxVehicleComponentSequence::SubGroupElement::component, PxVehicleComponentSequenceLimits::eMAX_NB_COMPONENTS, PxVehicleComponentSequenceLimits::eMAX_NB_SUBGROUPELEMENTS, and PxVehicleComponentSequence::SubGroupElement::nextElement.
beginSubstepGroup()
PxU8 PxVehicleComponentSequence::beginSubstepGroup (const PxU8 nbSubSteps = 1)
Start a substepping group.
Note
All components added using add() will be added to the new substepping group until either the group is marked as complete with a call to endSubstepGroup() or a subsequent substepping group is started with a call to beginSubstepGroup().
Groups can be nested with stacked calls to beginSubstepGroup().
Each group opened by beginSubstepGroup() must be closed with a complementary endSubstepGroup() prior to calling update().
Parameters
[in] nbSubSteps is the number of substeps for the group's sequence. This can be changed with a call to setSubsteps().
Returns
Handle for the substepping group on success, else eINVALID_SUBSTEP_GROUP
See also
setSubsteps()
endSubstepGroup()
References PxVehicleComponentSequence::SubGroupElement::childGroup, PxVehicleComponentSequence::SubGroupElement::component, PxVehicleComponentSequenceLimits::eMAX_NB_SUBGROUPELEMENTS, PxVehicleComponentSequenceLimits::eMAX_NB_SUBGROUPS, and PxVehicleComponentSequence::SubGroupElement::nextElement.
PxCloseVehicleExtension()
PX_FORCE_INLINE void PxCloseVehicleExtension ()
Shut down the PhysX Vehicle library.
This function should be called to cleanly shut down the PhysX Vehicle library before application exit.
Note
This function is required to be called to release foundation usage.
See also
PxInitVehicleExtension
References PxDecFoundationRefCount().
PxInitVehicleExtension()
PX_FORCE_INLINE bool PxInitVehicleExtension (physx::PxFoundation & foundation)
Initialize the PhysX Vehicle library.
This should be called before calling any functions or methods in extensions which may require allocation.
Note
This function does not need to be called before creating a PxDefaultAllocator object.
Parameters
foundation a PxFoundation object
See also
PxCloseVehicleExtension PxFoundation
References PX_CHECK_AND_RETURN_VAL, PX_UNUSED(), PxGetFoundation(), and PxIncFoundationRefCount().
PxVehicleAccelerationIntentCompute()
bool PxVehicleAccelerationIntentCompute (const PxVehicleAxleDescription & poweredVehicleAxleDesc, const PxVehicleArrayData< const PxVehicleWheelActuationState > & poweredVehicleActuationStates)
Compute the intention to accelerate by inspecting the actuation states of the wheels of a powered vehicle.
Parameters
[in] poweredVehicleAxleDesc describes the axles and wheels of a powered vehicle in a jointed ensemble of vehicles.
[in] poweredVehicleActuationStates describes the drive state of each wheel of the powered vehicle.
See also
PxVehicleTireStickyStateReset
PxVehicleAckermannSteerUpdate()
void PxVehicleAckermannSteerUpdate (const PxReal steer, const PxVehicleSteerCommandResponseParams & steerResponseParmas, const PxVehicleSizedArrayData< const PxVehicleAckermannParams > & ackermannParams, PxVehicleArrayData< PxReal > & steerResponseStates)
Account for Ackermann correction by modifying the per wheel steer response multipliers to engineer an asymmetric steer response across axles.
Parameters
[in] steer is the input steer command value.
[in] steerResponseParmas describes the maximum response and a response multiplier per axle.
[in] ackermannParams is an array that describes the wheels affected by Ackerman steer correction.
[in,out] steerResponseStates contains the corrected per wheel steer response multipliers that take account of Ackermann steer correction.
Referenced by PxVehicleDirectDriveCommandResponseComponent::update(), and PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleAntiRollForceUpdate()
void PxVehicleAntiRollForceUpdate (const PxVehicleArrayData< const PxVehicleSuspensionParams > & suspensionParams, const PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > & antiRollParams, const PxVehicleArrayData< const PxVehicleSuspensionState > & suspensionStates, const PxVehicleArrayData< const PxVehicleSuspensionComplianceState > & complianceStates, const PxVehicleRigidBodyState & rigidBodyState, PxVehicleAntiRollTorque & antiRollTorque)
Compute the accumulated anti-roll torque to apply to the vehicle's rigid body.
Parameters
[in] suspensionParams The suspension parameters for each wheel.
[in] antiRollParams describes the wheel pairs connected by anti-roll bars and the strength of each anti-roll bar.
[in] suspensionStates The suspension states for each wheel.
[in] complianceStates The suspension compliance states for each wheel.
[in] rigidBodyState describes the pose and momentum of the vehicle's rigid body in the world frame.
[in] antiRollTorque is the accumulated anti-roll torque that is computed by iterating over all anti-roll bars describes in *antiRollParams*.
Note
suspensionParams must contain an entry for each wheel index referenced by *antiRollParams*.
suspensionStates must contain an entry for each wheel index referenced by *antiRollParams*.
complianceStates must contain an entry for each wheel index referenced by *antiRollParams*.
antiRollTorque is expressed in the world frame.
Referenced by PxVehicleSuspensionComponent::update(), and PxVehicleLegacySuspensionComponent::update().
PxVehicleAutoBoxUpdate()
void PxVehicleAutoBoxUpdate (const PxVehicleEngineParams & engineParams, const PxVehicleGearboxParams & gearboxParams, const PxVehicleAutoboxParams & autoboxParams, const PxVehicleEngineState & engineState, const PxVehicleGearboxState & gearboxState, const PxReal dt, PxU32 & targetGearCommand, PxVehicleAutoboxState & autoboxState, PxReal & throttle)
Parameters
[in] engineParams specifies the engine configuration.
[in] gearboxParams specifies the gear ratios and the time required to complete a gear change.
[in] autoboxParams specifies the conditions for switching gear.
[in] engineState contains the current angular speed of the engine.
[in] gearboxState describes the current and target gear.
[in] dt is the time that has lapsed since the last call to PxVehicleAutoBoxUpdate.
[in,out] targetGearCommand specifies the desired target gear for the gearbox. If set to PxVehicleEngineDriveTransmissionCommandState::eAUTOMATIC_GEAR, the value will get overwritten with a target gear chosen by the autobox.
[out] autoboxState specifies the time that has lapsed since the last automated gear change and contains a record of any ongoing automated gear change.
[out] throttle A throttle command value in [0, 1] that will be set to 0 if a gear change is initiated or is ongoing.
Note
The autobox will not begin a gear change if a gear change is already ongoing.
The autobox will not begin a gear change until a threshold time has lapsed since the last automated gear change.
A gear change is considered as ongoing for as long as PxVehicleGearboxState::currentGear is different from PxVehicleGearboxState::targetGear.
The autobox will not shift down from 1st gear or up from reverse gear.
The autobox shifts in single gear increments or decrements.
The autobox instantiates a gear change by setting PxVehicleCommandState::targetGear to be different from from PxVehicleGearboxState::currentGear
Referenced by PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleBrakeCommandResponseUpdate()
PX_FORCE_INLINE void PxVehicleBrakeCommandResponseUpdate (const PxReal * brakeCommands, const PxU32 nbBrakeCommands, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > & brakeResponseParams, PxReal & brakeResponseState)
Compute the brake torque response to an array of brake commands.
Parameters
[in] brakeCommands is the array of input brake commands to be applied to the vehicle.
[in] nbBrakeCommands is the number of input brake commands to be applied to the vehicle.
[in] longitudinalSpeed is the longitudinal speed of the vehicle.
[in] wheelId specifies the wheel that is to have its brake response computed.
[in] brakeResponseParams specifies the per wheel brake torque response to each brake command as a nonlinear function of brake command and longitudinal speed.
[out] brakeResponseState is the brake torque response to the input brake command.
Note
commands.brakes[i] and brakeResponseParams[i] are treated as pairs of brake command and brake command response.
References PX_CHECK_AND_RETURN, PxVehicleNonLinearResponseCompute(), and PxVehicleSizedArrayData< T >::size.
Referenced by PxVehicleDirectDriveCommandResponseComponent::update(), and PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleClutchCommandResponseLinearUpdate()
void PxVehicleClutchCommandResponseLinearUpdate (const PxReal clutchCommand, const PxVehicleClutchCommandResponseParams & clutchResponseParams, PxVehicleClutchCommandResponseState & clutchResponse)
Propagate the input clutch command to the clutch response state.
Parameters
[in] clutchCommand specifies the state of the clutch pedal.
[in] clutchResponseParams specifies how the clutch responds to the input clutch command.
[out] clutchResponse specifies the response of the clutch to the input clutch command.
Referenced by PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleClutchStrengthCompute()
PX_FORCE_INLINE PxReal PxVehicleClutchStrengthCompute (const PxVehicleClutchCommandResponseState & clutchResponseState, const PxVehicleGearboxParams & gearboxParams, const PxVehicleGearboxState & gearboxState)
Compute the coupling strength of the clutch.
Parameters
[in] clutchResponseState describes the response of the clutch to the input clutch command.
[in] gearboxParams holds the index of neutral gear.
[in] gearboxState describes the current gear.
Note
If the gear is in neutral the clutch is fully disengaged and the clutch strength is 0.
A clutch response state of 0.0 denotes a fully engaged clutch with maximum strength.
A clutch response state of 1.0 denotes a fully disengaged clutch with a strength of 0.0.
References PxVehicleClutchCommandResponseState::commandResponse, PxVehicleGearboxState::currentGear, and PxVehicleGearboxParams::neutralGear.
PxVehicleComputeRotation()
PX_FORCE_INLINE PxQuat PxVehicleComputeRotation (const PxVehicleFrame & frame, const PxReal roll, const PxReal pitch, const PxReal yaw)
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, and PxVehicleFrame::getFrame().
Referenced by PxVehicleComputeWheelLocalOrientation(), and PxVehicleComputeWheelLocalPose().
PxVehicleComputeSign()
PX_FORCE_INLINE PxF32 PxVehicleComputeSign (const PxReal f)
References fsel().
PxVehicleComputeSprungMasses()
bool PxVehicleComputeSprungMasses (const PxU32 nbSprungMasses, const PxVec3 * sprungMassCoordinates, const PxReal totalMass, const PxVehicleAxes::Enum gravityDirection, PxReal * sprungMasses)
Compute the sprung masses of the suspension springs given (i) the number of sprung masses, (ii) coordinates of the sprung masses in the rigid body frame, (iii) the center of mass offset of the rigid body, (iv) the total mass of the rigid body, and (v) the direction of gravity.
Parameters
[in] nbSprungMasses is the number of sprung masses of the vehicle. This value corresponds to the number of wheels on the vehicle.
[in] sprungMassCoordinates are the coordinates of the sprung masses in the rigid body frame. The array sprungMassCoordinates must be of length nbSprungMasses or greater.
[in] totalMass is the total mass of all the sprung masses.
[in] gravityDirection describes the direction of gravitational acceleration.
[out] sprungMasses are the masses to set in the associated suspension data with PxVehicleSuspensionData::mSprungMass. The sprungMasses array must be of length nbSprungMasses or greater. Each element in the sprungMasses array corresponds to the suspension located at the same array element in sprungMassCoordinates. The center of mass of the masses in sprungMasses with the coordinates in sprungMassCoordinates satisfy the specified centerOfMass.
Returns
True if the sprung masses were successfully computed, false if the sprung masses were not successfully computed.
PxVehicleComputeSuspensionDirection()
PX_FORCE_INLINE PxVec3 PxVehicleComputeSuspensionDirection (const PxVehicleSuspensionParams & suspensionParams, const PxTransform & rigidBodyPose)
Compute suspension travel direction in the world frame.
Parameters
[in] suspensionParams is a description of the suspension frame.
[in] rigidBodyPose is the current pose of the vehicle's rigid body.
Returns
The return value is the suspension travel direction in the world frame.
Note
The suspension travel direction is used to perform queries against the road geometry.
References PxTransformT< Type >::rotate(), and PxVehicleSuspensionParams::suspensionTravelDir.
Referenced by PxVehicleComputeSuspensionRaycast(), and PxVehicleComputeSuspensionSweep().
PxVehicleComputeSuspensionRaycast()
PX_FORCE_INLINE void PxVehicleComputeSuspensionRaycast (const PxVehicleFrame & frame, const PxVehicleWheelParams & wheelParams, const PxVehicleSuspensionParams & suspensionParams, const PxF32 steerAngle, const PxTransform & rigidBodyPose, PxVec3 & start, PxVec3 & dir, PxReal & dist)
Compute the start point, direction and length of a suspension scene raycast.
Parameters
[in] frame is a description of the longitudinal, lateral and vertical axes.
[in] wheelParams describes the radius and halfwidth of the wheel.
[in] suspensionParams describes the suspension frame and the maximum suspension travel.
[in] steerAngle is the yaw angle of the wheel in radians.
[in] rigidBodyPose is the pose of the rigid body in the world frame.
[out] start is the starting point of the raycast in the world frame.
[out] dir is the direction of the raycast in the world frame.
[out] dist is the length of the raycast.
Note
start, dir and dist together describe a raycast that begins at the top of wheel at maximum compression and ends at the bottom of wheel at maximum droop.
References PxTransformT< Type >::p, PxVehicleComputeSuspensionDirection(), PxVehicleComputeWheelPoseForSuspensionQuery(), PxVehicleWheelParams::radius, and PxVehicleSuspensionParams::suspensionTravelDist.
PxVehicleComputeSuspensionSweep()
PX_FORCE_INLINE void PxVehicleComputeSuspensionSweep (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxReal steerAngle, const PxTransform & rigidBodyPose, PxTransform & start, PxVec3 & dir, PxReal & dist)
Compute the start pose, direction and length of a suspension scene sweep.
Parameters
[in] frame is a description of the longitudinal, lateral and vertical axes.
[in] suspensionParams describes the suspension frame and the maximum suspension travel.
[in] steerAngle is the yaw angle of the wheel in radians.
[in] rigidBodyPose is the pose of the rigid body in the world frame.
[out] start is the start pose of the sweep in the world frame.
[out] dir is the direction of the sweep in the world frame.
[out] dist is the length of the sweep.
Note
start, dir and dist together describe a sweep that begins with the wheel placed at maximum compression and ends at the maximum droop pose.
References PxVehicleComputeSuspensionDirection(), PxVehicleComputeWheelPoseForSuspensionQuery(), and PxVehicleSuspensionParams::suspensionTravelDist.
PxVehicleComputeTranslation()
PX_FORCE_INLINE PxVec3 PxVehicleComputeTranslation (const PxVehicleFrame & frame, const PxReal lng, const PxReal lat, const PxReal vrt)
References PxVehicleFrame::getFrame().
PxVehicleComputeWheelLocalOrientation()
PX_FORCE_INLINE PxQuat PxVehicleComputeWheelLocalOrientation (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxReal rotationAngle)
Compute the quaternion of a wheel in the rigid body frame.
Parameters
[in] frame describes the longitudinal and lateral axes of the vehicle.
[in] suspensionParams describes the suspension and wheel frames.
[in] camberAngle is the camber angle in radian sinduced by suspension compliance.
[in] toeAngle is the toe angle in radians induced by suspension compliance.
[in] steerAngle is the steer angle in radians applied to the wheel.
[in] rotationAngle is the angle around the wheel's lateral axis.
Returns
The quaterion of the wheel in the rigid body frame.
See also
PxVehicleComputeWheelOrientation
References PxVehicleComputeRotation(), PxTransformT< Type >::q, PxVehicleSuspensionParams::suspensionAttachment, and PxVehicleSuspensionParams::wheelAttachment.
Referenced by PxVehicleComputeWheelOrientation().
PxVehicleComputeWheelLocalPose() [1/2]
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelLocalPose (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionState & suspensionState, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxReal rotationAngle)
Compute the pose of the wheel in the rigid body frame.
Parameters
[in] frame describes the longitudinal and lateral axes of the vehicle.
[in] suspensionParams describes the suspension and wheel frames.
[in] suspensionState is the compression state of the suspenson.
[in] camberAngle is the camber angle in radian induced by suspension compliance.
[in] toeAngle is the toe angle in radians induced by suspension compliance.
[in] steerAngle is the steer angle in radians applied to the wheel.
[in] rotationAngle is the angle around the wheel's lateral axis.
Returns
The pose of the wheel in the rigid body frame.
References PxVehicleSuspensionState::jounce, PxTransformT< Type >::p, PX_VEHICLE_UNSPECIFIED_JOUNCE, PxVehicleComputeRotation(), PxTransformT< Type >::q, PxVehicleSuspensionParams::suspensionAttachment, PxVehicleSuspensionParams::suspensionTravelDir, PxVehicleSuspensionParams::suspensionTravelDist, and PxVehicleSuspensionParams::wheelAttachment.
Referenced by PxVehicleComputeWheelLocalPose(), PxVehicleComputeWheelPose(), and PxVehicleWheelComponent::update().
PxVehicleComputeWheelLocalPose() [2/2]
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelLocalPose (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionState & suspensionState, const PxVehicleSuspensionComplianceState & suspensionComplianceState, const PxReal steerAngle, const PxVehicleWheelRigidBody1dState & wheelState)
Compute the pose of the wheel in the rigid body frame.
Parameters
[in] frame describes the longitudinal and lateral axes of the vehicle.
[in] suspensionParams describes the suspension and wheel frames.
[in] suspensionState is the compression state of the suspenson.
[in] suspensionComplianceState is the camber and toe angles induced by suspension compliance.
[in] steerAngle is the steer angle in radians applied to the wheel.
[in] wheelState is angle around the wheel's lateral axis.
Returns
The pose of the wheel in the rigid body frame.
References PxVehicleSuspensionComplianceState::camber, PxVehicleComputeWheelLocalPose(), PxVehicleWheelRigidBody1dState::rotationAngle, and PxVehicleSuspensionComplianceState::toe.
PxVehicleComputeWheelOrientation()
PX_FORCE_INLINE PxQuat PxVehicleComputeWheelOrientation (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxQuat & rigidBodyOrientation, const PxReal rotationAngle)
Compute the quaternion of a wheel in the world frame.
Parameters
[in] frame describes the longitudinal and lateral axes of the vehicle.
[in] suspensionParams describes the suspension and wheel frames.
[in] camberAngle is the camber angle in radian induced by suspension compliance.
[in] toeAngle is the toe angle in radians induced by suspension compliance.
[in] steerAngle is the steer angle in radians applied to the wheel.
[in] rigidBodyOrientation is the quaterion of the rigid body in the world frame.
[in] rotationAngle is the angle around the wheel's lateral axis.
Returns
The quaterion of the wheel in the world frame.
See also
PxVehicleComputeWheelLocalOrientation
References PxVehicleComputeWheelLocalOrientation().
PxVehicleComputeWheelPose() [1/2]
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelPose (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionState & suspensionState, const PxReal camberAngle, const PxReal toeAngle, const PxReal steerAngle, const PxTransform & rigidBodyPose, const PxReal rotationAngle)
Compute the pose of the wheel in the world frame.
Parameters
[in] frame describes the longitudinal and lateral axes of the vehicle.
[in] suspensionParams describes the suspension and wheel frames.
[in] suspensionState is the compression state of the suspenson.
[in] camberAngle is the camber angle in radian induced by suspension compliance.
[in] toeAngle is the toe angle in radians induced by suspension compliance.
[in] steerAngle is the steer angle in radians applied to the wheel.
[in] rigidBodyPose is the pose of the rigid body in the world frame.
[in] rotationAngle is the angle around the wheel's lateral axis.
Returns
The pose of the wheel in the world frame.
References PxVehicleComputeWheelLocalPose().
Referenced by PxVehicleComputeWheelPose(), and PxVehicleComputeWheelPoseForSuspensionQuery().
PxVehicleComputeWheelPose() [2/2]
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelPose (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionState & suspensionState, const PxVehicleSuspensionComplianceState & suspensionComplianceState, const PxReal steerAngle, const PxTransform & rigidBodyPose, const PxVehicleWheelRigidBody1dState & wheelState)
Compute the pose of the wheel in the world frame.
Parameters
[in] frame describes the longitudinal and lateral axes of the vehicle.
[in] suspensionParams describes the suspension and wheel frames.
[in] suspensionState is the compression state of the suspenson.
[in] suspensionComplianceState is the camber and toe angles induced by suspension compliance.
[in] steerAngle is the steer angle in radians applied to the wheel.
[in] rigidBodyPose is the pose of the rigid body in the world frame.
[in] wheelState is angle around the wheel's lateral axis.
Returns
The pose of the wheel in the world frame.
References PxVehicleSuspensionComplianceState::camber, PxVehicleComputeWheelPose(), PxVehicleWheelRigidBody1dState::rotationAngle, and PxVehicleSuspensionComplianceState::toe.
PxVehicleComputeWheelPoseForSuspensionQuery()
PX_FORCE_INLINE PxTransform PxVehicleComputeWheelPoseForSuspensionQuery (const PxVehicleFrame & frame, const PxVehicleSuspensionParams & suspensionParams, const PxReal steerAngle, const PxTransform & rigidBodyPose)
Compute the start pose of a suspension query.
Parameters
[in] frame is a description of the longitudinal, lateral and vertical axes.
[in] suspensionParams is a description of the suspension frame.
[in] steerAngle is the yaw angle of the wheel in radians.
[in] rigidBodyPose is the pose of the rigid body in the world frame.
References PxVehicleComputeWheelPose(), and PxVehicleSuspensionState::setToDefault().
Referenced by PxVehicleComputeSuspensionRaycast(), and PxVehicleComputeSuspensionSweep().
PxVehicleConstraintsCreate()
void PxVehicleConstraintsCreate (const PxVehicleAxleDescription & axleDescription, PxPhysics & physics, PxRigidBody & physxActor, PxVehiclePhysXConstraints & vehicleConstraints)
Instantiate the PhysX custom constraints that will resolve excess suspension compression and velocity constraints that serve as a replacement low speed tire model.
Parameters
[in] axleDescription describes the axles of the vehicle and the wheels on each axle.
[in] physics is a PxPhysics instance.
[in] physxActor is the vehicle's PhysX representation as a PxRigidBody
[in] vehicleConstraints is a wrapper class that holds pointers to PhysX objects required to implement the custom constraint.
PxVehicleConstraintsDestroy()
void PxVehicleConstraintsDestroy (PxVehiclePhysXConstraints & vehicleConstraints)
Destroy the PhysX custom constraints.
Parameters
[in,out] vehicleConstraints describes the PhysX custom constraints to be released.
See also
PxVehicleConstraintsCreate
PxVehicleConstraintsDirtyStateUpdate()
void PxVehicleConstraintsDirtyStateUpdate (PxVehiclePhysXConstraints & vehicleConstraints)
To ensure the constraints are processed by the PhysX scene they are marked as dirty prior to each simulate step.
Parameters
[in] vehicleConstraints is a wrapper class that holds pointers to PhysX objects required to implement the custom constraint.
See also
PxVehicleConstraintsCreate
Referenced by PxVehiclePhysXConstraintComponent::update().
PxVehicleDifferentialStateUpdate() [1/4]
void PxVehicleDifferentialStateUpdate (const PxVehicleFourWheelDriveDifferentialLegacyParams & diffParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelStates, PxVehicleDifferentialState & diffState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential.
Parameters
[in] diffParams specifies the operation of a differential that can be connected to up to four wheels.
[in] wheelStates describes the angular speed of each wheel
[out] diffState contains the fraction of available drive torque to be delivered to each wheel.
Note
If the handbrake is on then torque is only delivered to the wheels specified as the front wheels of the differential.
Referenced by PxVehicleMultiWheelDriveDifferentialStateComponent::update(), PxVehicleFourWheelDriveDifferentialStateComponent::update(), PxVehicleTankDriveDifferentialStateComponent::update(), and PxVehicleLegacyFourWheelDriveDifferentialStateComponent::update().
PxVehicleDifferentialStateUpdate() [2/4]
void PxVehicleDifferentialStateUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleFourWheelDriveDifferentialParams & diffParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelStates, const PxReal dt, PxVehicleDifferentialState & diffState, PxVehicleWheelConstraintGroupState & wheelConstraintGroupState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential. Additionally, add wheel constraints for wheel pairs whose rotational speed ratio exceeds the corresponding differential bias.
Parameters
[in] axleDescription is a decription of the axles of the vehicle and the wheels on each axle.
[in] diffParams describe the division of available drive torque and the biases of the limited slip differential.
[in] wheelStates describes the rotational speeds of each wheel.
[in] dt is the simulation time that has passes since the last call to PxVehicleDifferentialStateUpdate()
[out] diffState contains the fraction of available drive torque to be delivered to each wheel.
[out] wheelConstraintGroupState describes the groups of wheels that have exceeded their corresponding differential biases.
PxVehicleDifferentialStateUpdate() [3/4]
void PxVehicleDifferentialStateUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleMultiWheelDriveDifferentialParams & diffParams, PxVehicleDifferentialState & diffState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential.
Parameters
[in] axleDescription is a decription of the axles of the vehicle and the wheels on each axle.
[in] diffParams specifies the operation of a differential that can be connected to any combination of wheels.
[out] diffState contains the fraction of available drive torque to be delivered to each wheel connected to the differential.
PxVehicleDifferentialStateUpdate() [4/4]
void PxVehicleDifferentialStateUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, const PxVehicleTankDriveDifferentialParams & diffParams, const PxReal thrustCommand0, PxReal thrustCommand1, PxVehicleDifferentialState & diffState, PxVehicleWheelConstraintGroupState & wheelConstraintGroupState)
Compute the fraction of available torque to be delivered to each wheel and gather a list of all wheels connected to the differential.
Parameters
[in] axleDescription is a decription of the axles of the vehicle and the wheels on each axle.
[in] wheelParams is an array that describes the wheel radius of each wheel.
[in] diffParams specifies the operation of a tank differential.
[in] thrustCommand0 is the state of one of the two thrust controllers.
[in] thrustCommand1 is the state of one of the two thrust controllers.
[out] diffState contains the fraction of available drive torque to be delivered to each wheel connected to the differential.
[out] wheelConstraintGroupState describes the groups of wheels connected by sharing a tank track.
PxVehicleDirectDriveActuationStateUpdate()
void PxVehicleDirectDriveActuationStateUpdate (const PxReal brakeTorque, const PxReal driveTorque, PxVehicleWheelActuationState & actuationState)
Determine the actuation state of a wheel given the brake torque, handbrake torque and drive torque applied to it.
Parameters
[in] brakeTorque is the brake torque to be applied to the wheel.
[in] driveTorque is the drive torque to be applied to the wheel.
[out] actuationState contains a binary record of whether brake or drive torque is applied to the wheel.
Referenced by PxVehicleDirectDriveActuationStateComponent::update().
PxVehicleDirectDriveThrottleCommandResponseUpdate()
void PxVehicleDirectDriveThrottleCommandResponseUpdate (const PxReal throttle, const PxVehicleDirectDriveTransmissionCommandState & transmissionCommands, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleDirectDriveThrottleCommandResponseParams & throttleResponseParams, PxReal & throttleResponseState)
Compute the drive torque response to a throttle command.
Parameters
[in] throttle is the throttle command.
[in] transmissionCommands is the gearing command to apply to the direct drive tranmission.
[in] longitudinalSpeed is the longitudinal speed of the vehicle's rigid body.
[in] wheelId specifies the wheel that is to have its throttle response computed.
[in] throttleResponseParams specifies the per wheel drive torque response to the throttle command as a nonlinear function of throttle command and longitudinal speed.
[out] throttleResponseState is the drive torque response to the input throttle command.
Referenced by PxVehicleDirectDriveCommandResponseComponent::update().
PxVehicleDirectDriveUpdate()
void PxVehicleDirectDriveUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleWheelActuationState & actuationState, const PxReal brakeTorque, const PxReal driveTorque, const PxVehicleTireForce & tireForce, const PxF32 dt, PxVehicleWheelRigidBody1dState & wheelRigidBody1dState)
Forward integrate the angular speed of a wheel given the brake and drive torque applied to it.
Parameters
[in] wheelParams specifies the moment of inertia of the wheel.
[in] actuationState is a binary record of whether brake and drive torque are to be applied to the wheel.
[in] brakeTorque is the brake torque to be applied to the wheel.
[in] driveTorque is the drive torque to be applied to the wheel.
[in] tireForce specifies the torque to apply to the wheel as a response to the longitudinal tire force.
[in] dt is the timestep of the forward integration.
[out] wheelRigidBody1dState describes the angular speed of the wheel.
Referenced by PxVehicleDirectDrivetrainComponent::update().
PxVehicleEngineDampingRateCompute()
PX_FORCE_INLINE PxReal PxVehicleEngineDampingRateCompute (const PxVehicleEngineParams & engineParams, const PxVehicleGearboxParams & gearboxParams, const PxVehicleGearboxState & gearboxState, const PxVehicleClutchCommandResponseState & clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState & throttleResponseState)
Compute the damping rate of the engine.
Parameters
[in] engineParams describes various damping rates of the engine in different operational states.
[in] gearboxParams holds the index of neutral gear.
[in] gearboxState describes the current gear.
[in] clutchResponseState is the response of the clutch to the clutch command.
[in] throttleResponseState is the response of the throttle to the throttle command.
Note
Engines typically have different damping rates with clutch engaged and disengaged.
Engines typically have different damping rates at different throttle pedal values.
See also
PxVehicleClutchStrengthCompute()
Note
In neutral gear the clutch is considered to be fully disengaged.
References PxVehicleEngineDriveThrottleCommandResponseState::commandResponse, PxVehicleGearboxState::currentGear, PxVehicleEngineParams::dampingRateFullThrottle, PxVehicleEngineParams::dampingRateZeroThrottleClutchDisengaged, PxVehicleEngineParams::dampingRateZeroThrottleClutchEngaged, PxVehicleGearboxParams::neutralGear, and PxVehicleClutchCommandResponseState::normalisedCommandResponse.
PxVehicleEngineDriveActuationStateUpdate()
void PxVehicleEngineDriveActuationStateUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleGearboxParams & gearboxParams, const PxVehicleArrayData< const PxReal > & brakeResponseStates, const PxVehicleEngineDriveThrottleCommandResponseState & throttleResponseState, const PxVehicleGearboxState & gearboxState, const PxVehicleDifferentialState & diffState, const PxVehicleClutchCommandResponseState & clutchResponseState, PxVehicleArrayData< PxVehicleWheelActuationState > & actuationStates)
Determine the actuation state of all wheels on a vehicle.
Parameters
[in] axleDescription is a decription of the axles of the vehicle and the wheels on each axle.
[in] gearboxParams specifies the index of the neutral gear of the gearbox.
[in] brakeResponseStates specifies the response of each wheel to the input brake command.
[in] throttleResponseState specifies the response of the engine to the input throttle command.
[in] gearboxState specifies the current gear.
[in] diffState specifies the fraction of available drive torque to be delivered to each wheel.
[in] clutchResponseState specifies the response of the clutch to the input throttle command.
[out] actuationStates is an array of binary records determining whether brake and drive torque are to be applied to each wheel.
Note
Drive torque is not applied to a wheel if a) the gearbox is in neutral b) the differential delivers no torque to the wheel c) no throttle is applied to the engine c) the clutch is fully disengaged.
Referenced by PxVehicleEngineDriveActuationStateComponent::update().
PxVehicleEngineDriveThrottleCommandResponseLinearUpdate()
void PxVehicleEngineDriveThrottleCommandResponseLinearUpdate (const PxVehicleCommandState & commands, PxVehicleEngineDriveThrottleCommandResponseState & throttleResponse)
Propagate the input throttle command to the throttle response state.
Parameters
[in] commands specifies the state of the throttle pedal.
[out] throttleResponse specifies how the clutch responds to the input throttle command.
Referenced by PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleEngineDriveTorqueCompute()
PX_FORCE_INLINE PxReal PxVehicleEngineDriveTorqueCompute (const PxVehicleEngineParams & engineParams, const PxVehicleEngineState & engineState, const PxVehicleEngineDriveThrottleCommandResponseState & throttleCommandResponseState)
Compute the drive torque to deliver to the engine.
Parameters
[in] engineParams describes the profile of maximum available torque across the full range of engine rotational speed.
[in] engineState describes the engine rotational speed.
[in] throttleCommandResponseState describes the engine's response to input throttle command.
References PxVehicleEngineDriveThrottleCommandResponseState::commandResponse, PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >::interpolate(), PxVehicleEngineParams::maxOmega, PxVehicleEngineParams::peakTorque, PxVehicleEngineState::rotationSpeed, and PxVehicleEngineParams::torqueCurve.
PxVehicleEngineDrivetrainUpdate()
void PxVehicleEngineDrivetrainUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, const PxVehicleEngineParams & engineParams, const PxVehicleClutchParams & clutchParams, const PxVehicleGearboxParams & gearboxParams, const PxVehicleArrayData< const PxReal > & brakeResponseStates, const PxVehicleArrayData< const PxVehicleWheelActuationState > & actuationStates, const PxVehicleArrayData< const PxVehicleTireForce > & tireForces, const PxVehicleGearboxState & gearboxState, const PxVehicleEngineDriveThrottleCommandResponseState & throttleResponse, const PxVehicleClutchCommandResponseState & clutchResponse, const PxVehicleDifferentialState & diffState, const PxVehicleWheelConstraintGroupState * constraintGroupState, const PxReal dt, PxVehicleArrayData< PxVehicleWheelRigidBody1dState > & wheelRigidbody1dStates, PxVehicleEngineState & engineState, PxVehicleClutchSlipState & clutchState)
Forward integrate the angular speed of the vehicle's wheels and engine, given the state of clutch, differential and gearbox.
Parameters
[in] axleDescription is a decription of the axles of the vehicle and the wheels on each axle.
[in] wheelParams specifies the moment of inertia of each wheel.
[in] engineParams specifies the torque curve of the engine and its moment of inertia.
[in] clutchParams specifies the maximum clutch strength that happens when the clutch is fully engaged.
[in] gearboxParams specifies the gearing ratios of the gearbox.
[in] brakeResponseStates describes the per wheel response to the input brake command.
[in] actuationStates is a binary record of whether brake or drive torque is applied to each wheel.
[in] tireForces describes the torque to apply to each wheel as a response to the longitudinal tire force.
[in] gearboxState describes the current gear.
[in] throttleResponse describes the engine response to the input throttle pedal.
[in] clutchResponse describes the clutch response to the input clutch pedal.
[in] diffState describes the fraction of available drive torque to be delivered to each wheel.
[in] constraintGroupState describes groups of wheels with rotational speed constrained to the same value.
[in] dt is the time that has lapsed since the last call to PxVehicleEngineDrivetrainUpdate
[out] wheelRigidbody1dStates describes the angular speed of each wheel.
[out] engineState describes the angular speed of the engine.
[out] clutchState describes the clutch slip.
Note
If constraintGroupState is NULL then it is assumed that there are no wheels subject to rotational speed constraints.
Referenced by PxVehicleEngineDrivetrainComponent::update().
PxVehicleGearboxUpdate()
void PxVehicleGearboxUpdate (const PxVehicleGearboxParams & gearboxParams, const PxF32 dt, PxVehicleGearboxState & gearboxState)
Update the current gear of the gearbox. If a gear change is ongoing then complete the gear change if a threshold time has passed since the beginning of the gear change.
Parameters
[in] gearboxParams describes the time required to complete a gear change.
[in] dt is the time that has lapsed since the last call to PxVehicleGearboxUpdate.
[out] gearboxState is the gearbox state to be updated.
Note
A gear change is considered as ongoing for as long as PxVehicleGearboxState::currentGear is different from PxVehicleGearboxState::targetGear.
Referenced by PxVehicleEngineDrivetrainComponent::update().
PxVehicleGearCommandResponseUpdate()
void PxVehicleGearCommandResponseUpdate (const PxU32 targetGearCommand, const PxVehicleGearboxParams & gearboxParams, PxVehicleGearboxState & gearboxState)
Propagate input gear commands to the gearbox state.
Parameters
[in] targetGearCommand specifies the target gear for the gearbox.
[in] gearboxParams specifies the number of gears and the index of neutral gear.
[out] gearboxState contains a record of the current and target gear.
Note
Any ongoing gear change must complete before starting another.
A gear change is considered as ongoing for as long as PxVehicleGearboxState::currentGear is different from PxVehicleGearboxState::targetGear.
The gearbox remains in neutral for the duration of the gear change.
A gear change begins if PxVehicleCommandState::targetGear is different from PxVehicleGearboxState::currentGear.
Referenced by PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleGearRatioCompute()
PX_FORCE_INLINE PxReal PxVehicleGearRatioCompute (const PxVehicleGearboxParams & gearboxParams, const PxVehicleGearboxState & gearboxState)
Compute the gear ratio delivered by the gearbox in the current gear.
Parameters
[in] gearboxParams describes the gear ratio of each gear and the final ratio.
[in] gearboxState describes the current gear.
Note
The gear ratio is the product of the gear ratio of the current gear and the final gear ratio of the gearbox.
References PxVehicleGearboxState::currentGear, PxVehicleGearboxParams::finalRatio, and PxVehicleGearboxParams::ratios.
PxVehicleIsWheelOnGround()
PX_FORCE_INLINE bool PxVehicleIsWheelOnGround (const PxVehicleSuspensionState & suspState)
Check if the suspension could place the wheel on the ground or not.
Parameters
[in] suspState The state of the suspension to check.
Returns
True if the wheel connects to the ground, else false.
See also
PxVehicleSuspensionState
References PxVehicleSuspensionState::separation.
PxVehicleLegacyDifferentialTorqueRatiosCompute()
void PxVehicleLegacyDifferentialTorqueRatiosCompute (const PxVehicleFourWheelDriveDifferentialLegacyParams & diffParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelOmegas, PxReal diffTorqueRatios[PxVehicleLimits::eMAX_NB_WHEELS])
Compute the fraction of available torque that is delivered to each wheel through the differential.
Parameters
[in] diffParams describes the wheels coupled to the differential and the operation of the torque split at the differential.
[in] wheelOmegas describes the rotational speeds of the wheels.
[out] diffTorqueRatios describes the fraction of available torque delivered to each wheel.
Note
Any wheel on an axle connected to the diff could receive a non-zero ratio, depending on the way the differential couples to the wheels.
Any wheel not on an axle connected to the diff will have a zero value.
The sum of all the ratios adds to 1.0.
Slipping wheels driven by the differential will typically receive less torque than non-slipping wheels in the event that the differential has a limited slip configuration.
If the handbrake is engaged then torque will be diverted from the rear wheels to the front wheels in the event that the differential is configured to deliver torque to the front wheels.
PxVehicleLegacyDifferentialWheelSpeedContributionsCompute()
void PxVehicleLegacyDifferentialWheelSpeedContributionsCompute (const PxVehicleFourWheelDriveDifferentialLegacyParams & diffParams, PxReal diffAveWheelSpeedContributions[PxVehicleLimits::eMAX_NB_WHEELS])
Compute the contribution that each wheel makes to the averaged wheel speed at the clutch plate connected to the wheels driven by the differential.
Parameters
[in] diffParams describes the wheels coupled to the differential and the operation of the torque split at the differential.
[out] diffAveWheelSpeedContributions describes the contribution that each wheel makes to the averaged wheel speed at the clutch.
Note
Any wheel on an axle connected to the differential could have a non-zero value, depending on the way the differential couples to the wheels.
Any wheel on an axle not connected to the differential will have a zero contribution to the averaged wheel speed.
If the handbrake is engaged then torque will be diverted from the rear wheels to the front wheels in the event that the differential is configured to deliver torque to the front wheels. The contribution from the rear wheels in this set of circumstances will be 0.
PxVehicleLinearResponseCompute()
PX_FORCE_INLINE PxReal PxVehicleLinearResponseCompute (const PxReal command, const PxU32 wheelId, const PxVehicleCommandResponseParams & responseParams)
Compute the linear response to a command.
Parameters
[in] command is a normalised command value.
[in] wheelId specifies the wheel that is to respond to the command.
[in] responseParams specifies the wheel responses for all wheels on a vehicle.
Returns
The linear response of the specified wheel to the command.
References PxVehicleCommandResponseParams::maxResponse, and PxVehicleCommandResponseParams::wheelResponseMultipliers.
PxVehicleNonLinearResponseCompute()
PxReal PxVehicleNonLinearResponseCompute (const PxReal command, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleCommandResponseParams & responseParams)
Compute the non-linear response to a command.
Parameters
[in] command is a normalised command value.
[in] longitudinalSpeed is the longitudional speed of the vehicle.
[in] wheelId specifies the wheel that is to respond to the command.
[in] responseParams specifies the wheel responses for all wheels on a vehicle.
Note
responseParams is used to compute an interpolated normalized response to the combination of command and longitudinalSpeed. The interpolated normalized response is then used in place of the command as input to PxVehicleComputeLinearResponse().
Referenced by PxVehicleBrakeCommandResponseUpdate().
PxVehiclePhysXActorConfigure()
void PxVehiclePhysXActorConfigure (const PxVehiclePhysXRigidActorParams & rigidActorParams, const PxTransform & rigidActorCmassLocalPose, PxRigidBody & rigidBody)
Configure an actor so that it is ready for vehicle simulation.
Parameters
[in] rigidActorParams describes the mass and moment of inertia of the rigid body.
[in] rigidActorCmassLocalPose specifies the mapping between actor and rigid body frame.
[out] rigidBody is the body to be prepared for simulation.
PxVehiclePhysXActorCreate()
void PxVehiclePhysXActorCreate (const PxVehicleFrame & vehicleFrame, const PxVehiclePhysXRigidActorParams & rigidActorParams, const PxTransform & rigidActorCmassLocalPose, const PxVehiclePhysXRigidActorShapeParams & rigidActorShapeParams, const PxVehiclePhysXWheelParams & wheelParams, const PxVehiclePhysXWheelShapeParams & wheelShapeParams, PxPhysics & physics, const PxCookingParams & params, PxVehiclePhysXActor & vehiclePhysXActor)
Create a PxRigidDynamic instance, instantiate it with desired properties and populate it with PxShape instances.
Parameters
[in] vehicleFrame describes the frame of the vehicle.
[in] rigidActorParams describes the mass and moment of inertia of the rigid body.
[in] rigidActorCmassLocalPose specifies the mapping between actor and rigid body frame.
[in] rigidActorShapeParams describes the collision geometry associated with the rigid body.
[in] wheelParams describes the radius and half-width of the wheels.
[in] wheelShapeParams describes the PxMaterial and PxShapeFlags to apply to the wheel shapes.
[in] physics is a PxPhysics instance.
[in] params is a PxCookingParams instance
[in] vehiclePhysXActor is a record of the PxRigidDynamic and PxShape instances instantiated.
Note
This is an alternative to PxVehiclePhysXArticulationLinkCreate.
PxVehiclePhysXActorCreate primarily serves as an illustration of the instantiation of the PhysX class instances required to simulate a vehicle with a PxRigidDynamic.
See also
PxVehiclePhysXActorDestroy
PxVehiclePhysXActorDestroy()
void PxVehiclePhysXActorDestroy (PxVehiclePhysXActor & vehiclePhysXActor)
Release the PxRigidDynamic, PxArticulationReducedCoordinate, PxArticulationLink and PxShape instances instantiated by PxVehiclePhysXActorCreate or PxVehiclePhysXArticulationLinkCreate.
Parameters
[in] vehiclePhysXActor is a description of the PhysX instances to be released.
PxVehiclePhysxActorKeepAwakeCheck()
void PxVehiclePhysxActorKeepAwakeCheck (const PxVehicleAxleDescription & axleDescription, const PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, const PxReal wakeCounterThreshold, const PxReal wakeCounterResetValue, const PxVehicleGearboxState * gearState, PxRigidBody & physxActor)
Check if the physx actor has to be kept awake.
Certain criteria should keep the vehicle physx actor awake, for example, if the (mass normalized) rotational kinetic energy of the wheels is above a certain threshold or if a gear change is pending. This method will reset the wake counter of the physx actor to a specified value, if any of the mentioned criterias are met.
Note
The physx actor's sleep threshold will be used as threshold to test against for the energy criteria.
Parameters
[in] axleDescription identifies the wheels on each axle.
[in] wheelParams describes the radius, mass etc. of the wheels.
[in] wheelRigidBody1dStates describes the angular speed of the wheels.
[in] wakeCounterThreshold Once the wake counter of the physx actor falls below this threshold, the method will start testing if the wake counter needs to be reset.
[in] wakeCounterResetValue The value to set the physx actor wake counter to, if any of the criteria to do so are met.
[in] gearState The gear state. Can be set to NULL if the vehicle does not have gears or if the mentioned behavior is not desired.
[in] physxActor is the PxRigidBody instance associated with the vehicle.
Referenced by PxVehiclePhysXActorEndComponent::update().
PxVehiclePhysxActorSleepCheck()
bool PxVehiclePhysxActorSleepCheck (const PxVehicleAxleDescription & axleDescription, const PxRigidBody & physxActor, const PxVehicleEngineParams * engineParams, PxVehicleRigidBodyState & rigidBodyState, PxVehiclePhysXConstraints & physxConstraints, PxVehicleArrayData< PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, PxVehicleEngineState * engineState)
Check if the physx actor is sleeping and clear certain vehicle states if it is.
Parameters
[in] axleDescription identifies the wheels on each axle.
[in] physxActor is the PxRigidBody instance associated with the vehicle.
[in] engineParams The engine parameters. Can be set to NULL if the vehicle does not have an engine. Must be specified, if engineState is specified.
[in,out] rigidBodyState is the state of the rigid body used by the Vehicle SDK.
[in,out] physxConstraints The state of the suspension limit and low speed tire constraints. If the vehicle actor is sleeping and constraints are active, they will be deactivated and marked as dirty.
[in,out] wheelRigidBody1dStates describes the angular speed of the wheels.
[out] engineState The engine state. Can be set to NULL if the vehicle does not have an engine. If specified, then engineParams has to be specifed too. The engine rotation speed will get set to the idle rotation speed if the actor is sleeping.
Returns
True if the actor was sleeping, else false.
Referenced by PxVehiclePhysXActorBeginComponent::update().
PxVehiclePhysxActorWakeup()
void PxVehiclePhysxActorWakeup (const PxVehicleCommandState & commands, const PxVehicleEngineDriveTransmissionCommandState * transmissionCommands, const PxVehicleGearboxParams * gearParams, const PxVehicleGearboxState * gearState, PxRigidBody & physxActor, PxVehiclePhysXSteerState & physxSteerState)
Wake up the physx actor if the actor is asleep and the commands signal an intent to change the state of the vehicle.
Parameters
[in] commands are the brake, throttle and steer values that will drive the vehicle.
[in] transmissionCommands are the target gear and clutch values that will control the transmission. If the target gear is different from the current gearbox target gear, then the physx actor will get woken up. Can be set to NULL if the vehicle does not have a gearbox or if this is not a desired behavior. If specified, then gearParams and gearState has to be specifed too.
[in] gearParams The gearbox parameters. Can be set to NULL if the vehicle does not have a gearbox and transmissionCommands is NULL.
[in] gearState The state of the gearbox. Can be set to NULL if the vehicle does not have a gearbox and transmissionCommands is NULL.
[in] physxActor is the PxRigidBody instance associated with the vehicle.
[in,out] physxSteerState and commands are compared to determine if the steering state has changed since the last call to PxVehiclePhysxActorWakeup().
Note
If the steering has changed, the actor will be woken up.
On exit from PxVehiclePhysxActorWakeup, physxSteerState.previousSteerCommand is assigned to the value of commands.steer so that the steer state may be propagated to the subsequent call to PxVehiclePhysxActorWakeup().
If physxSteerState.previousSteerCommand has value PX_VEHICLE_UNSPECIFIED_STEER_STATE, the steering state is treated as though it has not changed.
Referenced by PxVehiclePhysXActorBeginComponent::update().
PxVehiclePhysXArticulationLinkCreate()
void PxVehiclePhysXArticulationLinkCreate (const PxVehicleFrame & vehicleFrame, const PxVehiclePhysXRigidActorParams & rigidActorParams, const PxTransform & rigidActorCmassLocalPose, const PxVehiclePhysXRigidActorShapeParams & rigidActorShapeParams, const PxVehiclePhysXWheelParams & wheelParams, const PxVehiclePhysXWheelShapeParams & wheelShapeParams, PxPhysics & physics, const PxCookingParams & params, PxVehiclePhysXActor & vehiclePhysXActor)
Create a PxArticulationReducedCoordinate and a single PxArticulationLink, instantiate the PxArticulationLink with desired properties and populate it with PxShape instances.
Parameters
[in] vehicleFrame describes the frame of the vehicle.
[in] rigidActorParams describes the mass and moment of inertia of the rigid body.
[in] rigidActorCmassLocalPose specifies the mapping between actor and rigid body frame.
[in] rigidActorShapeParams describes the collision geometry associated with the rigid body.
[in] wheelParams describes the radius and half-width of the wheels.
[in] wheelShapeParams describes the PxMaterial and PxShapeFlags to apply to the wheel shapes.
[in] physics is a PxPhysics instance.
[in] params is a PxCookingParams instance
[in] vehiclePhysXActor is a record of the PxArticulationReducedCoordinate, PxArticulationLink and PxShape instances instantiated.
Note
This is an alternative to PxVehiclePhysXActorCreate.
PxVehiclePhysXArticulationLinkCreate primarily serves as an illustration of the instantiation of the PhysX class instances required to simulate a vehicle as part of an articulated ensemble.
See also
PxVehiclePhysXActorDestroy
PxVehiclePhysXConstraintStatesUpdate()
void PxVehiclePhysXConstraintStatesUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxVehiclePhysXSuspensionLimitConstraintParams & suspensionLimitParams, const PxVehicleSuspensionState & suspensionState, const PxVehicleSuspensionComplianceState & suspensionComplianceState, const PxVec3 & groundPlaneNormal, const PxReal tireStickyDampingLong, const PxReal tireStickyDampingLat, const PxVehicleTireDirectionState & tireDirectionState, const PxVehicleTireStickyState & tireStickyState, const PxVehicleRigidBodyState & rigidBodyState, PxVehiclePhysXConstraintState & constraintState)
Read constraint data from the vehicle's internal state for a single wheel and write it to a structure that will be read by the associated PxScene and used to impose the constraints during the next PxScene::simulate() step.
Parameters
[in] suspensionParams describes the suspension frame.
[in] suspensionLimitParams describes the restitution value applied to any constraint triggered by the suspension travel limit.
[in] suspensionState describes the excess suspension compression beyond the suspension travel limit that will be resolved with a constraint.
[in] suspensionComplianceState describes the effect of suspension compliance on the effective application point of the suspension force.
[in] groundPlaneNormal The normal direction of the ground plane the wheel is driving on. A normalized vector is expected.
[in] tireStickyDampingLong The damping coefficient to use in the constraint to approach a zero target velocity along the longitudinal tire axis.
[in] tireStickyDampingLat Same concept as tireStickyDampingLong but for the lateral tire axis.
[in] tireDirectionState describes the longitudinal and lateral directions of the tire in the world frame.
[in] tireStickyState describes the low speed state of the tire in the longitudinal and lateral directions.
[in] rigidBodyState describes the pose of the rigid body.
[out] constraintState is the data structure that will be read by the associated PxScene in the next call to PxScene::simulate().
Note
Constraints include suspension constraints to account for suspension travel limit and sticky tire constraints that bring the vehicle to rest at low longitudinal and lateral speed.
Referenced by PxVehiclePhysXConstraintComponent::update().
PxVehiclePhysXRoadGeometryQueryUpdate()
void PxVehiclePhysXRoadGeometryQueryUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleSuspensionParams & suspParams, const PxVehiclePhysXRoadGeometryQueryParams & roadGeomParams, const PxVehiclePhysXMaterialFrictionParams & materialFrictionParams, const PxReal wheelYawAngle, const PxVehicleRigidBodyState & rigidBodyState, const PxScene & scene, const PxConvexMesh * unitCylinderSweepMesh, const PxVehicleFrame & frame, PxVehicleRoadGeometryState & roadGeomState, PxVehiclePhysXRoadGeometryQueryState * physxRoadGeometryState)
Compute the plane of the road geometry under a wheel and the tire friction of the contact.
Parameters
[in] wheelParams describes the radius and halfwidth of the wheel.
[in] suspParams describes the frame of the suspension and wheel and the maximum suspension travel.
[in] roadGeomParams describes the operation of the PhysX scene query.
[in] materialFrictionParams describes a mapping between PxMaterial and friction in order to compute a tire friction value.
[in] wheelYawAngle is the yaw angle (in radians) of the wheel.
[in] rigidBodyState describes the pose of the rigid body.
[in] scene is the PhysX scene that will be queried by the scene query.
[in] unitCylinderSweepMesh is a convex cylindrical mesh of unit radius and half-width to be used in the event that a sweep query is to be used.
[in] frame describes the lateral, longitudinal and vertical axes and is used to scale unitCylinderSweepMesh by the wheel's radius and half-width.
[out] roadGeomState contains the plane and friction of the road geometry under the wheel.
[out] physxRoadGeometryState Optional buffer to store additional information about the query (like actor/shape that got hit etc.). Set to NULL if not needed.
Note
PxVehicleRoadGeometryState::hitState will have value false in the event that the there is no reachable road geometry under the wheel and true if there is reachable road geometry under the wheel. Road geometry is considered reachable if the suspension can elongate from its reference pose far enough to place wheel on the ground.
Referenced by PxVehiclePhysXRoadGeometrySceneQueryComponent::update().
PxVehiclePvdAntiRollsRegister()
void PxVehiclePvdAntiRollsRegister (const PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > & antiRollForceParams, const PxVehicleAntiRollTorque * antiRollTorque, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register object instances in omnipvd that will be used to reflect the antiroll bars of a vehicle instance.
Parameters
[in] antiRollForceParams is an array of antiroll parameters.
[in] antiRollTorque describes the instantaneous accumulated torque from all antiroll bas.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If antiRollForceParams is empty, the corresponding data will not be reflected in omnipvd.
If antiRollTorque is NULL, the corresponding data will not be reflected in omnipvd.
objectHandles must be non-NULL
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdAntiRollsWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdAntiRollsWrite()
void PxVehiclePvdAntiRollsWrite (const PxVehicleSizedArrayData< const PxVehicleAntiRollForceParams > & antiRollForceParams, const PxVehicleAntiRollTorque * antiRollTorque, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write antiroll data to omnipvd.
Parameters
[in] antiRollForceParams is an array of antiroll parameters.
[in] antiRollTorque describes the instantaneous accumulated torque from all antiroll bas.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If antiRollForceParams is empty but the corresponding argument was not empty, the corresponding data will not be updated in omnipvd.
If antiRollTorque is NULL but the corresponding argument was not NULL, the corresponding data will not be updated in omnipvd.
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdAntiRollsRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdAttributesCreate()
PxVehiclePvdAttributeHandles* PxVehiclePvdAttributesCreate (PxAllocatorCallback & allocator, OmniPvdWriter * omniWriter)
Create the attribute handles necessary to reflect vehicles in omnipvd.
Parameters
[in] allocator is used to allocate the memory used to store the attribute handles.
[in] omniWriter is used to register the attribute handles with omnipvd.
Note
omniWriter must be a valid pointer to an instance of OmniPvdWriter.
See also
PxVehicleSimulationContext
PxVehiclePVDComponent
PxVehiclePvdAttributesRelease
PxVehiclePvdAttributesRelease()
void PxVehiclePvdAttributesRelease (PxAllocatorCallback & allocator, OmniPvdWriter * omniWriter, PxVehiclePvdAttributeHandles * attributeHandles)
Destory the attribute handles created by PxVehiclePvdAttributesCreate().
Parameters
[in] allocator must be the instance used by PxVehiclePvdObjectCreate().
[in] omniWriter must point to the same OmniPvdWriter instance used for the complementary call to PxVehiclePvdAttributesCreate().
[in] attributeHandles is the PxVehiclePvdAttributeHandles created by PxVehiclePvdAttributesCreate().
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdCommandResponseRegister()
void PxVehiclePvdCommandResponseRegister (const PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > & brakeResponseParams, const PxVehicleSteerCommandResponseParams * steerResponseParams, const PxVehicleArrayData< PxReal > & brakeResponseStates, const PxVehicleArrayData< PxReal > & steerResponseStates, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register object instances in omnipvd that will be used to reflect the brake and steer command response parameters of a vehicle instance.
Parameters
[in] brakeResponseParams is an array of brake command response parameters.
[in] steerResponseParams describes the steer command response parameters.
[in] brakeResponseStates is an array of brake responses torqyes,
[in] steerResponseStates is an array of steer response angles.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If brakeResponseParams is empty, omnipvd will not reflect any brake command response parameters.
If steerResponseParams is NULL, omnipvd will not reflect the steer command response parameters.
If brakeResponseStates is empty, omnipvd will not reflect any brake command response state.
If steerResponseStates is empty, omnipvd will not reflect any steer command response state.
objectHandles must be non-NULL
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdCommandResponseWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdCommandResponseWrite()
void PxVehiclePvdCommandResponseWrite (const PxVehicleAxleDescription & axleDesc, const PxVehicleSizedArrayData< const PxVehicleBrakeCommandResponseParams > & brakeResponseParams, const PxVehicleSteerCommandResponseParams * steerResponseParams, const PxVehicleArrayData< PxReal > & brakeResponseStates, const PxVehicleArrayData< PxReal > & steerResponseStates, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write brake and steer command response parameters to omnipvd.
Parameters
[in] axleDesc is a description of the wheels and axles of a vehicle.
[in] brakeResponseParams is an array of brake command response parameters.
[in] steerResponseParams describes the steer command response parameters.
[in] brakeResponseStates is an array of brake response torques.
[in] steerResponseStates is an array of steer response angles.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If brakeResponseParams is empty but a non-empty array was used in PxVehiclePvdCommandResponseRegister(), the brake command response parameters will not be updated in omnipvd.
If steerResponseParams is non-NULL but a NULL value was used in PxVehiclePvdCommandResponseRegister(), the steer command parameters will not be updated in omnipvd.
If brakeResponseStates is empty but a non-empty array was used in PxVehiclePvdCommandResponseRegister(), the brake response states will not be updated in omnipvd.
If steerResponseStates is empty but a non-empty array was used in PxVehiclePvdCommandResponseRegister(), the steer response states will not be updated in omnipvd.
omniWriter must be non-NULL and must be the same instance used in PxVehiclePvdCommandResponseRegister().
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdCommandResponseRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdDirectDrivetrainRegister()
void PxVehiclePvdDirectDrivetrainRegister (const PxVehicleCommandState * commandState, const PxVehicleDirectDriveTransmissionCommandState * transmissionCommandState, const PxVehicleDirectDriveThrottleCommandResponseParams * directDriveThrottleResponseParams, const PxVehicleArrayData< PxReal > & directDriveThrottleResponseState, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register object instances in omnipvd that will be used to reflect the direct drivetrain of a vehicle instance.
Parameters
[in] commandState describes the control values applied to the vehicle.
[in] transmissionCommandState describes the state of the direct drive transmission.
[in] directDriveThrottleResponseParams describes the vehicle's torque response to a throttle command.
[in] directDriveThrottleResponseState is the instantaneous torque response of each wheel to a throttle command.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If commandState is NULL, the corresponding data will not be reflected in omnipvd.
If transmissionCommandState is NULL, the corresponding data will not be reflected in omnipvd.
If directDriveThrottleResponseParams is NULL, the corresponding data will not be reflected in omnipvd.
If directDriveThrottleResponseState is empty, the corresponding data will not be reflected in omnipvd.
objectHandles must be non-NULL
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdDirectDrivetrainWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdDirectDrivetrainWrite()
void PxVehiclePvdDirectDrivetrainWrite (const PxVehicleAxleDescription & axleDesc, const PxVehicleCommandState * commandState, const PxVehicleDirectDriveTransmissionCommandState * transmissionCommandState, const PxVehicleDirectDriveThrottleCommandResponseParams * directDriveThrottleResponseParams, const PxVehicleArrayData< PxReal > & directDriveThrottleResponseState, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write direct drivetrain data to omnipvd.
Parameters
[in] axleDesc is a description of the wheels and axles of a vehicle.
[in] commandState describes the control values applied to the vehicle.
[in] transmissionCommandState describes the state of the direct drive transmission.
[in] directDriveThrottleResponseParams describes the vehicle's torque response to a throttle command.
[in] directDriveThrottleResponseState is the instantaneous torque response of each wheel to a throttle command.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If commandState is NULL but the corresponding entry in PxVehiclePvdDirectDrivetrainRegister() was not NULL, the corresponding data will not be updated in omnipvd.
If transmissionCommandState is NULL but the corresponding entry in PxVehiclePvdDirectDrivetrainRegister() was not NULL, the corresponding data will not be updated in omnipvd.
If directDriveThrottleResponseParams is NULL but the corresponding entry in PxVehiclePvdDirectDrivetrainRegister() was not NULL, the corresponding data will not be updated in omnipvd.
If directDriveThrottleResponseState is empty but the corresponding entry in PxVehiclePvdDirectDrivetrainRegister() was not empty, the corresponding data will not be updated in omnipvd.
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdDirectDrivetrainRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdEngineDrivetrainRegister()
void PxVehiclePvdEngineDrivetrainRegister (const PxVehicleCommandState * commandState, const PxVehicleEngineDriveTransmissionCommandState * transmissionCommandState, const PxVehicleClutchCommandResponseParams * clutchResponseParams, const PxVehicleClutchParams * clutchParams, const PxVehicleEngineParams * engineParams, const PxVehicleGearboxParams * gearboxParams, const PxVehicleAutoboxParams * autoboxParams, const PxVehicleMultiWheelDriveDifferentialParams * multiWheelDiffParams, const PxVehicleFourWheelDriveDifferentialParams * fourWheelDiffPrams, const PxVehicleClutchCommandResponseState * clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState * throttleResponseState, const PxVehicleEngineState * engineState, const PxVehicleGearboxState * gearboxState, const PxVehicleAutoboxState * autoboxState, const PxVehicleDifferentialState * diffState, const PxVehicleClutchSlipState * clutchSlipState, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register object instances in omnipvd that will be used to reflect the engine drivetrain of a vehicle instance.
Parameters
[in] commandState describes the control values applied to the vehicle.
[in] transmissionCommandState describes the state of the engine drive transmission.
[in] clutchResponseParams describes the vehicle's response to a clutch command.
[in] clutchParams describes the vehicle's clutch.
[in] engineParams describes the engine.
[in] gearboxParams describes the gearbox.
[in] autoboxParams describes the automatic gearbox.
[in] multiWheelDiffParams describes a multiwheel differential without limited slip compensation.
[in] fourWheelDiffPrams describes a differential that delivers torque to four drive wheels with limited slip compensation.
[in] clutchResponseState is the instantaneous reponse of the clutch to a clutch command.
[in] throttleResponseState is the instantaneous response to a throttle command.
[in] engineState is the instantaneous state of the engine.
[in] gearboxState is the instantaneous state of the gearbox.
[in] autoboxState is the instantaneous state of the automatic gearbox.
[in] diffState is the instantaneous state of the differential.
[in] clutchSlipState is the instantaneous slip recorded at the clutch.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If any pointer is NULL, the corresponding data will not be reflected in omnipvd.
objectHandles must be non-NULL
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdEngineDrivetrainWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdEngineDrivetrainWrite()
void PxVehiclePvdEngineDrivetrainWrite (const PxVehicleCommandState * commandState, const PxVehicleEngineDriveTransmissionCommandState * transmissionCommandState, const PxVehicleClutchCommandResponseParams * clutchResponseParams, const PxVehicleClutchParams * clutchParams, const PxVehicleEngineParams * engineParams, const PxVehicleGearboxParams * gearboxParams, const PxVehicleAutoboxParams * autoboxParams, const PxVehicleMultiWheelDriveDifferentialParams * multiWheelDiffParams, const PxVehicleFourWheelDriveDifferentialParams * fourWheelDiffPrams, const PxVehicleClutchCommandResponseState * clutchResponseState, const PxVehicleEngineDriveThrottleCommandResponseState * throttleResponseState, const PxVehicleEngineState * engineState, const PxVehicleGearboxState * gearboxState, const PxVehicleAutoboxState * autoboxState, const PxVehicleDifferentialState * diffState, const PxVehicleClutchSlipState * clutchSlipState, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write engine drivetrain data of a vehicle instance to omnipvd.
Parameters
[in] commandState describes the control values applied to the vehicle.
[in] transmissionCommandState describes the state of the engine drive transmission.
[in] clutchResponseParams describes the vehicle's response to a clutch command.
[in] clutchParams describes the vehicle's clutch.
[in] engineParams describes the engine.
[in] gearboxParams describes the gearbox.
[in] autoboxParams describes the automatic gearbox.
[in] multiWheelDiffParams describes a multiwheel differential without limited slip compensation.
[in] fourWheelDiffPrams describes a differential that delivers torque to four drive wheels with limited slip compensation.
[in] clutchResponseState is the instantaneous reponse of the clutch to a clutch command.
[in] throttleResponseState is the instantaneous response to a throttle command.
[in] engineState is the instantaneous state of the engine.
[in] gearboxState is the instantaneous state of the gearbox.
[in] autoboxState is the instantaneous state of the automatic gearbox.
[in] diffState is the instantaneous state of the differential.
[in] clutchSlipState is the instantaneous slip recorded at the clutch.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If any pointer is NULL and the corresponding argument in PxVehiclePvdEngineDrivetrainRegister() was not NULL, the corresponding data will not be reflected in omnipvd.
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdEngineDrivetrainRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdObjectCreate()
PxVehiclePvdObjectHandles* PxVehiclePvdObjectCreate (const PxU32 nbWheels, const PxU32 nbAntirolls, const PxU32 maxNbPhysxMaterialFrictions, const PxU64 contextHandle, const PxVehiclePvdAttributeHandles & attributeHandles, OmniPvdWriter * omniWriter, PxAllocatorCallback & allocator)
Create omnipvd objects that will be used to reflect an individual veicle in omnipvd.
Parameters
[in] nbWheels must be greater than or equal to the number of wheels on the vehicle.
[in] nbAntirolls must be greater than or equal to the number of antiroll bars on the vehicle.
[in] maxNbPhysxMaterialFrictions must be greater than or equal to the number of PxPhysXMaterialFriction instances associated with any wheel of the vehicle.
[in] contextHandle is typically used to associated vehicles with a particular scene or group.
[in] attributeHandles is the PxVehiclePvdAttributeHandles instance returned by PxVehiclePvdAttributesCreate()
[in] omniWriter is used to register the attribute handles with omnipvd.
[in] allocator is used to allocate the memory used to store handles to the created omnipvd objects.
Note
PxVehiclePvdObjectCreate() must be called after PxVehiclePvdAttributesCreate().
See also
PxVehicleAxleDescription
PxVehicleAntiRollForceParams
PxVehiclePhysXMaterialFrictionParams
PxVehiclePVDComponent
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectRelease()
void PxVehiclePvdObjectRelease (const PxVehiclePvdAttributeHandles & attributeHandles, OmniPvdWriter * omniWriter, PxAllocatorCallback & allocator, PxVehiclePvdObjectHandles * objectHandles)
Destroy the PxVehiclePvdObjectHandles instance created by PxVehiclePvdObjectCreate().
Parameters
[in] attributeHandles is the PxVehiclePvdAttributeHandles created by PxVehiclePvdAttributesCreate().
[in] omniWriter is used to register the attribute handles with omnipvd.
[in] allocator must be the instance used by PxVehiclePvdObjectCreate().
[in] objectHandles is the PxVehiclePvdObjectHandles that was created by PxVehiclePvdObjectCreate().
PxVehiclePvdPhysXRigidActorRegister()
void PxVehiclePvdPhysXRigidActorRegister (const PxVehiclePhysXActor * physxActor, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register the PxRigidActor instance that represents the vehicle's rigid body in a PhysX scene.
Parameters
[in] physxActor describes the PxRigidActor instance that is used to represent the vehicle's rigid body in PhysX.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If physxActor is NULL, the corresponding data will not be reflected in omnipvd.
objectHandles must be non-NULL.
omniWriter must be non-NULL.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdPhysXRigidActorWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdPhysXRigidActorWrite()
void PxVehiclePvdPhysXRigidActorWrite (const PxVehiclePhysXActor * physxActor, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write the PxRigidActor instance to omnipvd.
Parameters
[in] physxActor describes the PxRigidActor instance that is used to represent the vehicle's rigid body in PhysX.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If physxActor is NULL and the corresponding argument in PxVehiclePvdPhysXRigidActorRegister was not NULL, the corresponding data will not be updated in omnipvd.
objectHandles must be non-NULL.
omniWriter must be non-NULL.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdPhysXRigidActorRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdPhysXWheelAttachmentRegister()
void PxVehiclePvdPhysXWheelAttachmentRegister (const PxVehicleAxleDescription & axleDesc, const PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > & physxSuspLimitConstraintParams, const PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > & physxMaterialFrictionParams, const PxVehiclePhysXActor * physxActor, const PxVehiclePhysXRoadGeometryQueryParams * physxRoadGeometryQueryParams, const PxVehicleArrayData< const PxVehiclePhysXRoadGeometryQueryState > & physxRoadGeomState, const PxVehicleArrayData< const PxVehiclePhysXConstraintState > & physxConstraintStates, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register per wheel attachment data that involves the vehicle's integration with a PhysX scene.
Parameters
[in] axleDesc is a description of the wheels and axles of a vehicle.
[in] physxSuspLimitConstraintParams describes the method used by PhysX to enforce suspension travel limits.
[in] physxMaterialFrictionParams describes the friction response of each wheel to a set of PxMaterial instances.
[in] physxActor describes the PxRigidActor and PxShape instances that are used to represent the vehicle's rigid body and wheel shapes in PhysX.
[in] physxRoadGeometryQueryParams describes the physx scene query method used to place each wheel on the ground.
[in] physxRoadGeomState is an array of per wheel physx scene query results.
[in] physxConstraintStates is an array of constraints states used by PhysX to enforce sticky tire and suspension travel limit constraints.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If any array is empty, the corresponding data will not be reflected in omnipvd.
If physxActor is NULL, the corresponding data will not be reflected in omnipvd.
If physxRoadGeometryQueryParams is NULL, the corresponding data will not be reflected in omnipvd.
Each array must either be empty or contain an entry for each wheel present in axleDesc.
objectHandles must be non-NULL.
omniWriter must be non-NULL.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdPhysXWheelAttachmentWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdPhysXWheelAttachmentWrite()
void PxVehiclePvdPhysXWheelAttachmentWrite (const PxVehicleAxleDescription & axleDesc, const PxVehicleArrayData< const PxVehiclePhysXSuspensionLimitConstraintParams > & physxSuspLimitConstraintParams, const PxVehicleArrayData< const PxVehiclePhysXMaterialFrictionParams > & physxMaterialFrictionParams, const PxVehiclePhysXActor * physxActor, const PxVehiclePhysXRoadGeometryQueryParams * physxRoadGeometryQueryParams, const PxVehicleArrayData< const PxVehiclePhysXRoadGeometryQueryState > & physxRoadGeomState, const PxVehicleArrayData< const PxVehiclePhysXConstraintState > & physxConstraintStates, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write to omnipvd the per wheel attachment data that involves the vehicle's integration with a PhysX scene.
Parameters
[in] axleDesc is a description of the wheels and axles of a vehicle.
[in] physxSuspLimitConstraintParams describes the method used by PhysX to enforce suspension travel limits.
[in] physxMaterialFrictionParams describes the friction response of each wheel to a set of PxMaterial instances.
[in] physxActor describes the PxShape instances that are used to represent the vehicle's wheel shapes in PhysX.
[in] physxRoadGeometryQueryParams describes the physx scene query method used to place each wheel on the ground.
[in] physxRoadGeomState is an array of per wheel physx scene query results.
[in] physxConstraintStates is an array of constraints states used by PhysX to enforce sticky tire and suspension travel limit constraints.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If any array is empty but the corresponding array in PxVehiclePvdPhysXWheelAttachmentRegister() was not empty, the corresponding data will not be updated in omnipvd.
If physxActor is NULL but the corresponding argument in PxVehiclePvdPhysXWheelAttachmentRegister was not NULL, the corresponding data will not be reflected in omnipvd.
If physxRoadGeometryQueryParams is NULL but the corresponding argument in PxVehiclePvdPhysXWheelAttachmentRegister was not NULL, the corresponding data will not be reflected in omnipvd.
Each array must either be empty or contain an entry for each wheel present in axleDesc.
omniWriter must be non-NULL.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdPhysXWheelAttachmentWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdRigidBodyRegister()
void PxVehiclePvdRigidBodyRegister (const PxVehicleRigidBodyParams * rbodyParams, const PxVehicleRigidBodyState * rbodyState, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Create object instances in omnipvd that will be used to reflect the parameters and state of the rigid body of a vehicle instance. Handles to the created object instances will be stored in a PxVehiclePvdObjectHandles instance.
Parameters
[in] rbodyParams describes the parameters of the vehicle's rigid body.
[in] rbodyState describes the state of the vehicle's rigid body.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If rbodyParams is NULL, omnipvd will not reflect rigid body parameters.
If rbodyState is NULL, omnipvd will not reflect rigid body state.
objectHandles must be non-NULL
omniWriter must be non-NULL
PxVehiclePvdRigidBodyRegister should be called once for each vehicle instance.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdRigidBodyWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdRigidBodyWrite()
void PxVehiclePvdRigidBodyWrite (const PxVehicleRigidBodyParams * rbodyParams, const PxVehicleRigidBodyState * rbodyState, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write the parameters and state of the rigid body of a vehicle instance to omnipvd.
Parameters
[in] rbodyParams describes the parameters of the vehicle's rigid body.
[in] rbodyState describes the state of the vehicle's rigid body.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If rbodyParams is NULL but a non-NULL value was used in PxVehiclePvdRigidBodyRegister(), the rigid body parameters will not be updated in omnipvd.
If rbodyState is NULL but a non-NULL value was used in PxVehiclePvdRigidBodyRegister(), the rigid body state will not be updated in omnipvd.
omniWriter must be non-NULL and must be the same instance used in PxVehiclePvdRigidBodyRegister().
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdRigidBodyRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdSuspensionStateCalculationParamsRegister()
void PxVehiclePvdSuspensionStateCalculationParamsRegister (const PxVehicleSuspensionStateCalculationParams * suspStateCalcParams, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register object instances in omnipvd that will be used to reflect the suspension state calculation parameters of a vehicle instance.
Parameters
[in] suspStateCalcParams describes parameters used to calculate suspension state.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If suspStateCalcParams is NULL, omnipvd will not reflect the suspension state calculation parameters.
objectHandles must be non-NULL
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdSuspensionStateCalculationParamsWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdSuspensionStateCalculationParamsWrite()
void PxVehiclePvdSuspensionStateCalculationParamsWrite (const PxVehicleSuspensionStateCalculationParams * suspStateCalcParams, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write the parameters and state of the rigid body of a vehicle instance to omnipvd.
Parameters
[in] suspStateCalcParams describes parameters used to calculate suspension state.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If suspStateCalcParams is NULL but a non-NULL value was used in void PxVehiclePvdSuspensionStateCalculationParamsRegister(), the suspension state calculation parameters will not be updated in omnipvd.
omniWriter must be non-NULL and must be the same instance used in PxVehiclePvdSuspensionStateCalculationParamsRegister().
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdSuspensionStateCalculationParamsRegister
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdWheelAttachmentsRegister()
void PxVehiclePvdWheelAttachmentsRegister (const PxVehicleAxleDescription & axleDesc, const PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, const PxVehicleArrayData< const PxVehicleWheelActuationState > & wheelActuationStates, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, const PxVehicleArrayData< const PxVehicleWheelLocalPose > & wheelLocalPoses, const PxVehicleArrayData< const PxVehicleRoadGeometryState > & roadGeometryStates, const PxVehicleArrayData< const PxVehicleSuspensionParams > & suspParams, const PxVehicleArrayData< const PxVehicleSuspensionComplianceParams > & suspCompParams, const PxVehicleArrayData< const PxVehicleSuspensionForceParams > & suspForceParams, const PxVehicleArrayData< const PxVehicleSuspensionState > & suspStates, const PxVehicleArrayData< const PxVehicleSuspensionComplianceState > & suspCompStates, const PxVehicleArrayData< const PxVehicleSuspensionForce > & suspForces, const PxVehicleArrayData< const PxVehicleTireForceParams > & tireForceParams, const PxVehicleArrayData< const PxVehicleTireDirectionState > & tireDirectionStates, const PxVehicleArrayData< const PxVehicleTireSpeedState > & tireSpeedStates, const PxVehicleArrayData< const PxVehicleTireSlipState > & tireSlipStates, const PxVehicleArrayData< const PxVehicleTireStickyState > & tireStickyStates, const PxVehicleArrayData< const PxVehicleTireGripState > & tireGripStates, const PxVehicleArrayData< const PxVehicleTireCamberAngleState > & tireCamberStates, const PxVehicleArrayData< const PxVehicleTireForce > & tireForces, const PxVehiclePvdAttributeHandles & attributeHandles, PxVehiclePvdObjectHandles * objectHandles, OmniPvdWriter * omniWriter)
Register object instances in omnipvd that will be used to reflect wheel attachment data such as tires, suspensions and wheels.
Parameters
[in] axleDesc is a description of the wheels and axles of a vehicle.
[in] wheelParams is an array of wheel parameters.
[in] wheelActuationStates is an array of wheel actuation states.
[in] wheelRigidBody1dStates is an array of wheel rigid body states.
[in] wheelLocalPoses is an array of wheel local poses.
[in] roadGeometryStates is an array of road geometry states.
[in] suspParams is an array of suspension parameters.
[in] suspCompParams is an array of suspension compliance parameters.
[in] suspForceParams is an array of suspension force parameters.
[in] suspStates is an array of suspension states.
[in] suspCompStates is an array of suspension compliance states.
[in] suspForces is an array of suspension forces.
[in] tireForceParams is an array of tire force parameters.
[in] tireDirectionStates is an array of tire direction states.
[in] tireSpeedStates is an array of tire speed states.
[in] tireSlipStates is an array of tire slip states.
[in] tireStickyStates is an array of tire sticky states.
[in] tireGripStates is an array of tire grip states.
[in] tireCamberStates is an array of tire camber states.
[in] tireForces is an array of tire forces.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If any array is empty, the corresponding data will not be reflected in omnipvd.
Each array must either be empty or contain an entry for each wheel present in axleDesc.
objectHandles must be non-NULL
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdWheelAttachmentsWrite
Referenced by PxVehiclePVDComponent::update().
PxVehiclePvdWheelAttachmentsWrite()
void PxVehiclePvdWheelAttachmentsWrite (const PxVehicleAxleDescription & axleDesc, const PxVehicleArrayData< const PxVehicleWheelParams > & wheelParams, const PxVehicleArrayData< const PxVehicleWheelActuationState > & wheelActuationStates, const PxVehicleArrayData< const PxVehicleWheelRigidBody1dState > & wheelRigidBody1dStates, const PxVehicleArrayData< const PxVehicleWheelLocalPose > & wheelLocalPoses, const PxVehicleArrayData< const PxVehicleRoadGeometryState > & roadGeometryStates, const PxVehicleArrayData< const PxVehicleSuspensionParams > & suspParams, const PxVehicleArrayData< const PxVehicleSuspensionComplianceParams > & suspCompParams, const PxVehicleArrayData< const PxVehicleSuspensionForceParams > & suspForceParams, const PxVehicleArrayData< const PxVehicleSuspensionState > & suspStates, const PxVehicleArrayData< const PxVehicleSuspensionComplianceState > & suspCompStates, const PxVehicleArrayData< const PxVehicleSuspensionForce > & suspForces, const PxVehicleArrayData< const PxVehicleTireForceParams > & tireForceParams, const PxVehicleArrayData< const PxVehicleTireDirectionState > & tireDirectionStates, const PxVehicleArrayData< const PxVehicleTireSpeedState > & tireSpeedStates, const PxVehicleArrayData< const PxVehicleTireSlipState > & tireSlipStates, const PxVehicleArrayData< const PxVehicleTireStickyState > & tireStickyStates, const PxVehicleArrayData< const PxVehicleTireGripState > & tireGripStates, const PxVehicleArrayData< const PxVehicleTireCamberAngleState > & tireCamberStates, const PxVehicleArrayData< const PxVehicleTireForce > & tireForces, const PxVehiclePvdAttributeHandles & attributeHandles, const PxVehiclePvdObjectHandles & objectHandles, OmniPvdWriter * omniWriter)
Write wheel attachment data such as tire, suspension and wheel data to omnipvd.
Parameters
[in] axleDesc is a description of the wheels and axles of a vehicle.
[in] wheelParams is an array of wheel parameters.
[in] wheelActuationStates is an array of wheel actuation states.
[in] wheelRigidBody1dStates is an array of wheel rigid body states.
[in] wheelLocalPoses is an array of wheel local poses.
[in] roadGeometryStates is an array of road geometry states.
[in] suspParams is an array of suspension parameters.
[in] suspCompParams is an array of suspension compliance parameters.
[in] suspForceParams is an array of suspension force parameters.
[in] suspStates is an array of suspension states.
[in] suspCompStates is an array of suspension compliance states.
[in] suspForces is an array of suspension forces.
[in] tireForceParams is an array of tire force parameters.
[in] tireDirectionStates is an array of tire direction states.
[in] tireSpeedStates is an array of tire speed states.
[in] tireSlipStates is an array of tire slip states.
[in] tireStickyStates is an array of tire sticky states.
[in] tireGripStates is an array of tire grip states.
[in] tireCamberStates is an array of tire camber states.
[in] tireForces is an array of tire forces.
[in] attributeHandles contains a general description of vehicle parameters and states that will be reflected in omnipvd.
[in] objectHandles contains unique handles for the parameters and states of each vehicle instance.
[in] omniWriter is an OmniPvdWriter instance used to communicate state and parameter data to omnipvd.
Note
If any array is empty but the corresponding argument in PxVehiclePvdWheelAttachmentsRegister was not empty, the corresponding data will not be updated in omnipvd.
Each array must either be empty or contain an entry for each wheel present in axleDesc.
omniWriter must be non-NULL
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdObjectCreate
PxVehiclePvdWheelAttachmentsRegister
Referenced by PxVehiclePVDComponent::update().
PxVehicleReadRigidBodyStateFromPhysXActor()
void PxVehicleReadRigidBodyStateFromPhysXActor (const PxRigidBody & physxActor, PxVehicleRigidBodyState & rigidBodyState)
Read the rigid body state from a PhysX actor.
Parameters
[in] physxActor is a reference to a PhysX actor.
[out] rigidBodyState is the state of the rigid body used by the Vehicle SDK.
Referenced by PxVehiclePhysXActorBeginComponent::update().
PxVehicleRigidBodyUpdate()
void PxVehicleRigidBodyUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleRigidBodyParams & rigidBodyParams, const PxVehicleArrayData< const PxVehicleSuspensionForce > & suspensionForces, const PxVehicleArrayData< const PxVehicleTireForce > & tireForces, const PxVehicleAntiRollTorque * antiRollTorque, const PxReal dt, const PxVec3 & gravity, PxVehicleRigidBodyState & rigidBodyState)
Forward integrate rigid body state.
Parameters
[in] axleDescription is a description of the axles of the vehicle and the wheels on each axle.
[in] rigidBodyParams is a description of rigid body mass and moment of inertia.
[in] suspensionForces is an array of suspension forces and torques in the world frame to be applied to the rigid body.
[in] tireForces is an array of tire forces and torques in the world frame to be applied to the rigid body.
[in] antiRollTorque is an optional pointer to a single PxVehicleAntiRollTorque instance that contains the accumulated anti-roll torque to apply to the rigid body.
[in] dt is the timestep of the forward integration.
[in] gravity is gravitational acceleration.
[in,out] rigidBodyState is the rigid body state that is to be updated.
Note
The suspensionForces array must contain an entry for each wheel listed as an active wheel in axleDescription.
The tireForces array must contain an entry for each wheel listed as an active wheel in axleDescription.
If antiRollTorque is a null pointer then zero anti-roll torque will be applied to the rigid body.
Referenced by PxVehicleRigidBodyComponent::update().
PxVehicleShiftOrigin()
PX_FORCE_INLINE void PxVehicleShiftOrigin (const PxVehicleAxleDescription & axleDesc, const PxVec3 & shift, PxVehicleRigidBodyState & rigidBodyState, PxVehicleRoadGeometryState * roadGeometryStates, PxVehiclePhysXActor * physxActor = NULL, PxVehiclePhysXRoadGeometryQueryState * physxQueryStates = NULL)
Shift the origin of a vehicle by the specified vector.
Call this method to adjust the internal data structures of vehicles to reflect the shifted origin location (the shift vector will get subtracted from all world space spatial data).
Parameters
[in] axleDesc is a description of the wheels on the vehicle.
[in] shift is the translation vector used to shift the origin.
[in] rigidBodyState stores the current position of the vehicle
[in] roadGeometryStates stores the hit plane under each wheel.
[in] physxActor stores the PxRigidActor that is the vehicle's PhysX representation.
[in] physxQueryStates stores the hit point of the most recent execution of PxVehiclePhysXRoadGeometryQueryUpdate() for each wheel.
Note
It is the user's responsibility to keep track of the summed total origin shift and adjust all input/output to/from the vehicle accordingly.
This call will not automatically shift the PhysX scene and its objects. PxScene::shiftOrigin() must be called seperately to keep the systems in sync.
If there is no associated PxRigidActor then set physxActor to NULL.
If there is an associated PxRigidActor and it is already in a PxScene then the complementary call to PxScene::shiftOrigin() will take care of shifting the associated PxRigidActor. This being the case, set physxActor to NULL. physxActor should be a non-NULL pointer only when there is an associated PxRigidActor and it is not part of a PxScene. This can occur if the associated PxRigidActor is updated using PhysX immediate mode.
If scene queries are independent of PhysX geometry then set queryStates to NULL.
References PxPlane::d, PxVec3T< Type >::dot(), PxPlane::n, PxVehicleAxleDescription::nbWheels, PxTransformT< Type >::p, PxVehicleRoadGeometryState::plane, PxVehicleRigidBodyState::pose, PxAbs(), PxZero, PxTransformT< Type >::q, PxVehicleAxleDescription::wheelIdsInAxleOrder, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
PxVehicleSteerCommandResponseUpdate()
void PxVehicleSteerCommandResponseUpdate (const PxReal steer, const PxReal longitudinalSpeed, const PxU32 wheelId, const PxVehicleSteerCommandResponseParams & steerResponseParmas, PxReal & steerResponseState)
Compute the yaw angle response to a steer command.
Parameters
[in] steer is the input steer command value.
[in] longitudinalSpeed is the longitudinal speed of the vehicle.
[in] wheelId specifies the wheel to have its steer response computed.
[in] steerResponseParmas specifies the per wheel yaw angle response to the steer command as a nonlinear function of steer command and longitudinal speed.
[out] steerResponseState is the yaw angle response to the input steer command.
Referenced by PxVehicleDirectDriveCommandResponseComponent::update(), and PxVehicleEngineDriveCommandResponseComponent::update().
PxVehicleSuspensionComplianceUpdate()
void PxVehicleSuspensionComplianceUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionComplianceParams & complianceParams, const PxVehicleSuspensionState & suspensionState, PxVehicleSuspensionComplianceState & complianceState)
Compute the toe, camber and force application points that are affected by suspension compression.
Parameters
[in] suspensionParams is a description of the suspension and wheel frames.
[in] complianceParams describes how toe, camber and force application points are affected by suspension compression.
[in] suspensionState describes the current suspension compression.
[in] complianceState is the computed toe, camber and force application points.
Referenced by PxVehicleSuspensionComponent::update(), and PxVehicleLegacySuspensionComponent::update().
PxVehicleSuspensionForceUpdate()
void PxVehicleSuspensionForceUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionForceParams & suspensionForceParams, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleSuspensionState & suspensionState, const PxVehicleSuspensionComplianceState & complianceState, const PxVehicleRigidBodyState & rigidBodyState, const PxVec3 & gravity, const PxReal vehicleMass, PxVehicleSuspensionForce & suspensionForce)
Compute the suspension force and torque arising from suspension compression and speed.
Parameters
[in] suspensionParams is a description of the suspension and wheel frames.
[in] suspensionForceParams describes the conversion of suspension state to suspension force.
[in] roadGeometryState describes the plane under the wheel of the suspension.
[in] suspensionState is the current compression state of the suspension.
[in] complianceState is the current compliance state of the suspension.
[in] rigidBodyState describes the current pose of the rigid body.
[in] gravity is the gravitational acceleration.
[in] vehicleMass is the rigid body mass.
[out] suspensionForce is the force and torque to apply to the rigid body arising from the suspension state.
Referenced by PxVehicleSuspensionComponent::update().
PxVehicleSuspensionLegacyForceUpdate()
PX_DEPRECATED void PxVehicleSuspensionLegacyForceUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionForceLegacyParams & suspensionForceParams, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleSuspensionState & suspensionState, const PxVehicleSuspensionComplianceState & complianceState, const PxVehicleRigidBodyState & rigidBodyState, const PxVec3 & gravity, PxVehicleSuspensionForce & suspensionForce)
Compute the suspension force and torque arising from suspension compression and speed.
Parameters
[in] suspensionParams is a description of the suspension and wheel frames.
[in] suspensionForceParams describes the conversion of suspension state to suspension force.
[in] roadGeometryState describes the plane under the wheel of the suspension.
[in] suspensionState is the current compression state of the suspension.
[in] complianceState is the current compliance state of the suspension.
[in] rigidBodyState describes the current pose of the rigid body.
[in] gravity is the gravitational acceleration.
[out] suspensionForce is the force and torque to apply to the rigid body arising from the suspension state.
Note
PxVehicleSuspensionLegacyForceUpdate implements the legacy force computation of PhysX 5.0 and earlier.
Referenced by PxVehicleLegacySuspensionComponent::update().
PxVehicleSuspensionStateUpdate()
void PxVehicleSuspensionStateUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleSuspensionParams & suspensionParams, const PxVehicleSuspensionStateCalculationParams & suspensionStateCalcParams, const PxReal suspensionStiffness, const PxReal suspensionDamping, const PxReal steerAngle, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleRigidBodyState & rigidBodyState, const PxReal dt, const PxVehicleFrame & frame, const PxVec3 & gravity, PxVehicleSuspensionState & suspState)
Compute the suspension compression and compression speed for a single suspension.
Parameters
[in] wheelParams is a description of the radius and half-width of the wheel on the suspension.
[in] suspensionParams is a description of the suspension and wheel frames.
[in] suspensionStateCalcParams specifies whether to compute the suspension compression by either raycasting or sweeping against the plane of the road geometry under the wheel.
[in] suspensionStiffness is the stiffness of the suspension
[in] suspensionDamping is the damping rate of the suspension. or whether to apply a limit to the expansion speed so that the wheel may not reach the ground.
[in] steerAngle is the yaw angle (in radians) of the wheel.
[in] roadGeometryState describes the plane under the wheel.
[in] rigidBodyState describes the pose of the rigid body.
[in] dt is the simulation time that has lapsed since the last call to PxVehicleSuspensionStateUpdate
[in] frame describes the longitudinal, lateral and vertical axes of the vehicle.
[in] gravity is the gravitational acceleration that acts on the suspension sprung mass.
[in,out] suspState is the compression (jounce) and compression speed of the suspension.
Referenced by PxVehicleSuspensionComponent::update(), and PxVehicleLegacySuspensionComponent::update().
PxVehicleTireCamberAnglesUpdate()
void PxVehicleTireCamberAnglesUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxReal steerAngle, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleSuspensionComplianceState & complianceState, const PxVehicleRigidBodyState & rigidBodyState, const PxVehicleFrame & frame, PxVehicleTireCamberAngleState & tireCamberAngleState)
Compute the camber angle of the wheel.
Parameters
[in] suspensionParams describes the frame of the suspension and wheel.
[in] steerAngle is the steer angle in radians to be applied to the wheel.
[in] roadGeometryState describes the plane of the road geometry under the wheel.
[in] complianceState is a description of the camber and toe angle that arise from suspension compliance.
[in] rigidBodyState describes the current pose of the vehicle's rigid body in the world frame.
[in] frame is a description of the vehicle's lateral and longitudinal axes.
[out] tireCamberAngleState is the computed camber angle of the tire expressed in radians.
Referenced by PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
PxVehicleTireDirsLegacyUpdate()
PX_DEPRECATED void PxVehicleTireDirsLegacyUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxReal steerAngle, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleRigidBodyState & rigidBodyState, const PxVehicleFrame & frame, PxVehicleTireDirectionState & tireDirectionState)
Compute the longitudinal and lateral tire directions in the ground plane.
Parameters
[in] suspensionParams describes the frame of the suspension and wheel.
[in] steerAngle is the steer angle in radians to be applied to the wheel.
[in] roadGeometryState describes the plane of the road geometry under the wheel
[in] rigidBodyState describes the current pose of the vehicle's rigid body in the world frame.
[in] frame is a description of the vehicle's lateral and longitudinal axes.
[out] tireDirectionState is the computed tire longitudinal and lateral directions in the world frame.
Note
PxVehicleTireDirsLegacyUpdate replicates the tire direction calculation of PhysX 5.0 and earlier.
Referenced by PxVehicleLegacyTireComponent::update().
PxVehicleTireDirsUpdate()
void PxVehicleTireDirsUpdate (const PxVehicleSuspensionParams & suspensionParams, const PxReal steerAngle, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleSuspensionComplianceState & complianceState, const PxVehicleRigidBodyState & rigidBodyState, const PxVehicleFrame & frame, PxVehicleTireDirectionState & tireDirectionState)
Compute the longitudinal and lateral tire directions in the ground plane.
Parameters
[in] suspensionParams describes the frame of the suspension and wheel.
[in] steerAngle is the steer angle in radians to be applied to the wheel.
[in] roadGeometryState describes the plane of the road geometry under the wheel.
[in] rigidBodyState describes the current pose of the vehicle's rigid body in the world frame.
[in] complianceState is a description of the camber and toe angle that arise from suspension compliance.
[in] frame is a description of the vehicle's lateral and longitudinal axes.
[out] tireDirectionState is the computed tire longitudinal and lateral directions in the world frame.
Note
The difference between PxVehicleTireDirsUpdate and PxVehicleTireDirsLegacyUpdate is that PxVehicleTireDirsUpdate accounts for suspension compliance while PxVehicleTireDirsLegacyUpdate does not.
Referenced by PxVehicleTireComponent::update().
PxVehicleTireForcesUpdate()
void PxVehicleTireForcesUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleSuspensionParams & suspensionParams, const PxVehicleTireForceParams & tireForceParams, const PxVehicleSuspensionComplianceState & complianceState, const PxVehicleTireGripState & tireGripState, const PxVehicleTireDirectionState & tireDirectionState, const PxVehicleTireSlipState & tireSlipState, const PxVehicleTireCamberAngleState & tireCamberAngleState, const PxVehicleRigidBodyState & rigidBodyState, PxVehicleTireForce & tireForce)
Compute the longitudinal and lateral forces in the world frame that develop on the tire as a consequence of the tire's slip angles, friction and load.
Parameters
[in] wheelParams describes the radius and half-width of the wheel.
[in] suspensionParams describes the frame of the suspension and wheel.
[in] tireForceParams describes the conversion of slip angle, friction and load to a force along the longitudinal and lateral directions of the tire.
[in] complianceState is a description of the camber and toe angle that arise from suspension compliance.
[out] tireGripState is the load and friction experienced by the tire.
[in] tireDirectionState is the tire's longitudinal and lateral directions in the ground plane.
[in] tireSlipState is the longitudinal and lateral slip angles.
[in] tireCamberAngleState is the camber angle of the tire expressed in radians.
[in] rigidBodyState describes the current pose of the vehicle's rigid body in the world frame.
[out] tireForce is the computed tire forces in the world frame.
Referenced by PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
PxVehicleTireGripUpdate()
void PxVehicleTireGripUpdate (const PxVehicleTireForceParams & tireForceParams, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleSuspensionState & suspensionState, const PxVehicleSuspensionForce & suspensionForce, const PxVehicleTireSlipState & tireSlipState, PxVehicleTireGripState & tireGripState)
Compute the load and friction experienced by the tire.
Parameters
[in] tireForceParams describes the tire's friction response to longitudinal lip angle and its load response.
[in] roadGeometryState describes the plane of the road geometry under the wheel.
[in] suspensionState is the current suspension compression state.
[in] suspensionForce is the force that the suspension exerts on the sprung mass of the suspension.
[in] tireSlipState is the tire longitudinal and lateral slip angles.
[out] tireGripState is the computed load and friction experienced by the tire.
Note
If the suspension cannot place the wheel on the ground the tire load and friction will be 0.0.
Referenced by PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
PxVehicleTireSlipsAccountingForStickyStatesUpdate()
void PxVehicleTireSlipsAccountingForStickyStatesUpdate (const PxVehicleTireStickyState & tireStickyState, PxVehicleTireSlipState & tireSlipState)
Set the tire longitudinal and lateral slip values to 0.0 in the event that the tire has entred tire sticky state. This is necessary to avoid both tire models being simultaneously active and interfering with each other.
Parameters
[in] tireStickyState is a description of the sticky state of the tire in the longitudinal and lateral directions.
[out] tireSlipState is the updated lateral and longudinal slip with either set to 0.0 in the event that the correspoinding sticky state is active.
Note
This function should not be invoked if there is no subsequent component to implement the sticky tire model.
Referenced by PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
PxVehicleTireSlipsLegacyUpdate()
void PxVehicleTireSlipsLegacyUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleTireSlipParams & tireSlipParams, const PxVehicleWheelActuationState & actuationState, PxVehicleTireSpeedState & tireSpeedState, const PxVehicleWheelRigidBody1dState & wheelRigidBody1dState, PxVehicleTireSlipState & tireSlipState)
Compute a tire's longitudinal and lateral slip angles.
Parameters
[in] wheelParams describes the radius of the wheel.
[in] tireSlipParams describes how to manage small longitudinal speeds by setting minimum values on the denominator of the quotients used to calculate lateral and longitudinal slip.
[in] actuationState describes whether a wheel is to be driven by a drive torque or not.
[in] tireSpeedState is the component of rigid body velocity at the tire contact point projected along the tire's longitudinal and lateral axes.
[in] wheelRigidBody1dState is the wheel rotation speed.
[out] tireSlipState is the computed tire longitudinal and lateral slips.
Note
Longitudinal slip angle has the following theoretical form: (wheelRotationSpeed*wheelRadius - longitudinalSpeed)/|longitudinalSpeed|
Lateral slip angle has the following theoretical form: atan(lateralSpeed/|longitudinalSpeed|)
The calculation of both longitudinal and lateral slip angles avoid a zero denominator using minimum values for the denominator set in tireSlipParams.
Referenced by PxVehicleLegacyTireComponent::update().
PxVehicleTireSlipSpeedsUpdate()
void PxVehicleTireSlipSpeedsUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleSuspensionParams & suspensionParams, const PxF32 steerAngle, const PxVehicleSuspensionState & suspensionStates, const PxVehicleTireDirectionState & tireDirectionState, const PxVehicleRigidBodyState & rigidBodyState, const PxVehicleRoadGeometryState & roadGeometryState, const PxVehicleFrame & frame, PxVehicleTireSpeedState & tireSpeedState)
Project the rigid body velocity at the tire contact point along the tire longitudinal directions.
Parameters
[in] wheelParams is a description of the wheel's radius and half-width.
[in] suspensionParams describes the frame of the suspension and wheel.
[in] steerAngle is the steer angle in radians to be applied to the wheel.
[in] suspensionStates is the current suspension compression state.
[in] tireDirectionState is the tire's longitudinal and lateral directions in the ground plane.
[in] rigidBodyState describes the current pose and velocity of the vehicle's rigid body in the world frame.
[in] roadGeometryState describes the current velocity of the road geometry under each wheel.
[in] frame is a description of the vehicle's lateral and longitudinal axes.
[out] tireSpeedState is the components of rigid body velocity at the tire contact point along the tire's longitudinal and lateral axes.
See also
PxVehicleTireDirsUpdate
PxVehicleTireDirsLegacyUpdate
Referenced by PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
PxVehicleTireSlipsUpdate()
void PxVehicleTireSlipsUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleTireSlipParams & tireSlipParams, const PxVehicleWheelActuationState & actuationState, PxVehicleTireSpeedState & tireSpeedState, const PxVehicleWheelRigidBody1dState & wheelRigidBody1dState, PxVehicleTireSlipState & tireSlipState)
Compute a tire's longitudinal and lateral slip angles.
Parameters
[in] wheelParams describes the radius of the wheel.
[in] tireSlipParams describes how to manage small longitudinal speeds by setting minimum values on the denominator of the quotients used to calculate lateral and longitudinal slip.
[in] actuationState describes whether a wheel is to be driven by a drive torque or not.
[in] tireSpeedState is the component of rigid body velocity at the tire contact point projected along the tire's longitudinal and lateral axes.
[in] wheelRigidBody1dState is the wheel rotation speed.
[out] tireSlipState is the computed tire longitudinal and lateral slips.
Note
Longitudinal slip angle has the following theoretical form: (wheelRotationSpeed*wheelRadius - longitudinalSpeed)/|longitudinalSpeed|
Lateral slip angle has the following theoretical form: atan(lateralSpeed/|longitudinalSpeed|)
The calculation of both longitudinal and lateral slip angles avoid a zero denominator using minimum values for the denominator set in tireSlipParams.
Referenced by PxVehicleTireComponent::update().
PxVehicleTireStickyStateReset()
void PxVehicleTireStickyStateReset (const bool poweredVehicleIntentionToAccelerate, const PxVehicleAxleDescription & unpoweredVehicleAxleDesc, PxVehicleArrayData< PxVehicleTireStickyState > & unpoweredVehicleStickyState)
Reset the sticky tire states of an unpowered vehicle if it is in a jointed ensemble of vehicles with at least one powered vehicle.
Parameters
[in] poweredVehicleIntentionToAccelerate describes the state of the powered vehicle in an ensemble of jointed vehicles.
[in] unpoweredVehicleAxleDesc describes the axles and wheels of an unpowered vehicle towed by a powered vehicle.
[out] unpoweredVehicleStickyState is the sticky state of the wheels of an unpowered vehicle towed by a powered vehicle.
Note
If any wheel on the powered vehicle is to receive a drive torque, the sticky tire states of the towed vehicle will be reset to the deactivated state.
poweredVehicleIntentionToAccelerate may be computed using PxVehicleAccelerationIntentCompute().
See also
PxVehicleAccelerationIntentCompute
PxVehicleTireStickyStateUpdate()
void PxVehicleTireStickyStateUpdate (const PxVehicleAxleDescription & axleDescription, const PxVehicleWheelParams & wheelParams, const PxVehicleTireStickyParams & tireStickyParams, const PxVehicleArrayData< const PxVehicleWheelActuationState > & actuationStates, const PxVehicleTireGripState & tireGripState, const PxVehicleTireSpeedState & tireSpeedState, const PxVehicleWheelRigidBody1dState & wheelRigidBody1dState, const PxReal dt, PxVehicleTireStickyState & tireStickyState)
When a tire has been at a very low speed for a threshold time without application of drive torque, a secondary tire model is applied to bring the tire to rest using velocity constraints that asymptotically approach zero speed along the tire's lateral and longitudinal directions. This secondary tire model is referred to as the sticky tire model and the tire is considered to be in the sticky tire state when the speed and time conditions are satisfied. The purpose of PxVehicleTireStickyStateUpdate is to compute the target speeds of the sticky state and to record whether sticky state is active or not.
Parameters
[in] axleDescription is the axles of the vehicle and the wheels on each axle.
[in] wheelParams describes the radius of the wheel
[in] tireStickyParams describe the threshold speeds and times for the lateral and longitudinal sticky states.
[in] actuationStates describes whether each wheel experiences a drive torque.
[in] tireGripState is the load and friction experienced by the tire.
[in] tireSpeedState is the component of rigid body velocity at the tire contact point projected along the tire's longitudinal and lateral axes.
[in] wheelRigidBody1dState is the wheel rotation speed.
[in] dt is the simulation time that has lapsed since the last call to PxVehicleTireStickyStateUpdate
[out] tireStickyState is a description of the sticky state of the tire in the longitudinal and lateral directions.
Note
The velocity constraints are maintained through integration with the PhysX scene using the function PxVehiclePhysXConstraintStatesUpdate. Alternative implementations independent of PhysX are possible.
See also
PxVehiclePhysXConstraintStatesUpdate
PxVehicleTireSlipsAccountingForStickyStatesUpdate
Referenced by PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
PxVehicleTransformFrameToFrame() [1/3]
PX_FORCE_INLINE PxVec3 PxVehicleTransformFrameToFrame (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVec3 & v)
References PxVehicleFrame::getFrame(), PxMat33T< Type >::getTranspose(), PxVehicleFrame::latAxis, PxVehicleFrame::lngAxis, and PxVehicleFrame::vrtAxis.
Referenced by PxVehicleTransformFrameToFrame(), PxVehicleRigidBodyParams::transformAndScale(), PxVehicleSuspensionParams::transformAndScale(), and PxVehicleSuspensionComplianceParams::transformAndScale().
PxVehicleTransformFrameToFrame() [2/3]
PX_FORCE_INLINE PxVec3 PxVehicleTransformFrameToFrame (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale, const PxVec3 & v)
References PxVehicleTransformFrameToFrame(), and PxVehicleScale::scale.
PxVehicleTransformFrameToFrame() [3/3]
PX_FORCE_INLINE PxTransform PxVehicleTransformFrameToFrame (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale, const PxTransform & v)
References PxVehicleFrame::latAxis, PxVehicleFrame::lngAxis, PxTransformT< Type >::p, PxVehicleTransformFrameToFrame(), PxTransformT< Type >::q, PxQuatT< Type >::toRadiansAndUnitAxis(), and PxVehicleFrame::vrtAxis.
PxVehicleUnitCylinderSweepMeshCreate()
PxConvexMesh* PxVehicleUnitCylinderSweepMeshCreate (const PxVehicleFrame & vehicleFrame, PxPhysics & physics, const PxCookingParams & params)
Create a cylindrical mesh with unit radius and half-width.
Parameters
[in] vehicleFrame is a description of the lateral and longitudinal axes.
[in] physics is a PxPhysics instance.
[in] params is a PxCookingParams instance
Returns
Return a PxConvexMesh instance that represents a convex hull with unit radius and half-width.
See also
PxVehicleUnitCylinderSweepMeshDestroy
PxVehicleUnitCylinderSweepMeshDestroy()
void PxVehicleUnitCylinderSweepMeshDestroy (PxConvexMesh * mesh)
Release the mesh created with PxVehicleUnitCylinderSweepMeshCreate.
Parameters
[in] mesh is a PxConvexMesh instance.
See also
PxVehicleUnitCylinderSweepMeshCreate
PxVehicleWheelRotationAngleUpdate()
void PxVehicleWheelRotationAngleUpdate (const PxVehicleWheelParams & wheelParams, const PxVehicleWheelActuationState & actuationState, const PxVehicleSuspensionState & suspensionState, const PxVehicleTireSpeedState & tireSpeedState, const PxReal thresholdForwardSpeedForWheelAngleIntegration, const PxReal dt, PxVehicleWheelRigidBody1dState & wheelRigidBody1dState)
Forward integrate the rotation angle of a wheel.
Note
The rotation angle of the wheel plays no role in simulation but is important to compute the pose of the wheel for rendering.
Parameters
[in] wheelParams describes the radius and half-width of the wheel
[in] actuationState describes whether the wheel has drive or brake torque applied to it.
[in] suspensionState describes whether the wheel touches the ground.
[in] tireSpeedState describes the components of rigid body velocity at the ground contact point along the tire's lateral and longitudinal directions.
[in] thresholdForwardSpeedForWheelAngleIntegration Forward wheel speed below which the wheel rotation speed gets blended with the rolling speed (based on the forward wheel speed) which is then used to integrate the wheel rotation angle. At low forward wheel speed, the wheel rotation speed can get unstable (depending on the tire model used) and, for example, oscillate. If brake or throttle is applied, there will be no blending.
[in] dt is the simulation time that has lapsed since the last call to PxVehicleWheelRotationAngleUpdate
[in,out] wheelRigidBody1dState describes the current angular speed and angle of the wheel.
Note
At low speeds and large timesteps, wheel rotation speed can become noisy due to singularities in the tire slip computations. At low speeds, therefore, the wheel speed used for integrating the angle is a blend of current angular speed and rolling angular speed if the wheel experiences neither brake nor drive torque and can be placed on the ground. The blended rotation speed gets stored in PxVehicleWheelRigidBody1dState::correctedRotationSpeed.
Referenced by PxVehicleWheelComponent::update().
PxVehicleWriteRigidBodyStateToPhysXActor()
void PxVehicleWriteRigidBodyStateToPhysXActor (const PxVehiclePhysXActorUpdateMode::Enum physxActorUpdateMode, const PxVehicleRigidBodyState & rigidBodyState, const PxReal dt, PxRigidBody & physXActor)
Write the rigid body state to a PhysX actor.
Parameters
[in] physxActorUpdateMode controls whether the PhysX actor is to be updated with instantaneous velocity changes or with accumulated accelerations to be applied in the next simulation step of the associated PxScene.
[in] rigidBodyState is the state of the rigid body.
[in] dt is the simulation time that has elapsed since the last call to PxVehicleWriteRigidBodyStateToPhysXActor().
[out] physXActor is a reference to the PhysX actor.
Referenced by PxVehiclePhysXActorEndComponent::update().
PxVehicleWriteWheelLocalPoseToPhysXWheelShape()
void PxVehicleWriteWheelLocalPoseToPhysXWheelShape (const PxTransform & wheelLocalPose, const PxTransform & wheelShapeLocalPose, PxShape * shape)
Update the local pose of a PxShape that is associated with a wheel.
Parameters
[in] wheelLocalPose describes the local pose of each wheel in the rigid body frame.
[in] wheelShapeLocalPose describes the local pose to apply to the PxShape instance in the wheel's frame.
[in] shape is the target PxShape.
Referenced by PxVehiclePhysXActorEndComponent::update().
vehicleConstraintSolverPrep()
PX_FORCE_INLINE PxU32 vehicleConstraintSolverPrep (Px1DConstraint * constraints, PxVec3p & body0WorldOffset, PxU32 maxConstraints, PxConstraintInvMassScale & , const void * constantBlock, const PxTransform & bodyAToWorld, const PxTransform & bodyBToWorld, bool , PxVec3p & cA2w, PxVec3p & cB2w)
References Px1DConstraint::angular0, Px1DConstraint::angular1, Px1DConstraint::bounce, Px1DConstraintFlag::eACCELERATION_SPRING, Px1DConstraintFlag::eANGULAR_CONSTRAINT, PxConstraintSolveHint::eINEQUALITY, PxVehicleTireDirectionModes::eLATERAL, PxVehicleTireDirectionModes::eLONGITUDINAL, PxVehiclePhysXConstraintLimits::eNB_WHEELS_PER_PXCONSTRAINT, Px1DConstraintFlag::eRESTITUTION, Px1DConstraintFlag::eSPRING, Px1DConstraint::flags, Px1DConstraint::geometricError, PxTransformT< Type >::isValid(), Px1DConstraint::linear0, Px1DConstraint::linear1, Px1DConstraint::maxImpulse, Px1DConstraint::minImpulse, Px1DConstraint::mods, PxTransformT< Type >::p, PX_ASSERT, PX_UNUSED(), Px1DConstraint::solveHint, Px1DConstraint::spring, and Px1DConstraint::velocityTarget.
Referenced by PxVehicleConstraintConnector::getPrep().
visualiseVehicleConstraint()
PX_FORCE_INLINE void visualiseVehicleConstraint (PxConstraintVisualizer & viz, const void * constantBlock, const PxTransform & body0Transform, const PxTransform & body1Transform, PxU32 flags)
References PxTransformT< Type >::isValid(), PX_ASSERT, and PX_UNUSED().