Cooking
Cooking
Classes
struct PxMeshCookingHint
Enumeration for mesh cooking hints.
struct PxBVH33MidphaseDesc
Structure describing parameters affecting BVH33 midphase mesh structure.
struct PxBVH34BuildStrategy
Desired build strategy for PxMeshMidPhase::eBVH34.
struct PxBVH34MidphaseDesc
Structure describing parameters affecting BVH34 midphase mesh structure.
class PxBVHDesc
Descriptor class for PxBVH.
struct PxConvexFlag
Flags which describe the format and behavior of a convex mesh.
class PxConvexMeshDesc
Descriptor class for PxConvexMesh.
struct PxConvexMeshCookingResult
Result from convex cooking.
struct PxConvexMeshCookingType
Enumeration for convex mesh cooking algorithms.
struct PxTriangleMeshCookingResult
Result from triangle mesh cooking.
struct PxMeshPreprocessingFlag
Enum for the set of mesh pre-processing parameters.
struct PxCookingParams
Structure describing parameters affecting mesh cooking.
class PxCooking
Provides methods to cook (where cooking means to prepare the data and convert it to the right format potentially including the construction of acceleration structures and other support data) all kind of simulation data.
class PxMidphaseDesc
Structure describing parameters affecting midphase mesh structure.
struct PxDim3
A helper structure to define dimensions in 3D.
class PxSdfBitsPerSubgridPixel
Defines the number of bits per subgrid pixel.
class PxSDFDesc
A structure describing signed distance field for mesh.
class PxTetrahedronMeshDesc
Descriptor class for PxTetrahedronMesh (contains only pure geometric data).
class PxSoftBodySimulationDataDesc
Descriptor class for PxSoftBodyMesh (contains only additional data used for softbody simulation).
class PxTriangleMeshDesc
Descriptor class for PxTriangleMesh.
Typedefs
typedef PX_DEPRECATED PxBVHDesc PxBVHStructureDesc
typedef PxFlags< PxConvexFlag::Enum, PxU16 > PxConvexFlags
collection of set bits defined in PxConvexFlag.
typedef PxFlags< PxMeshPreprocessingFlag::Enum, PxU32 > PxMeshPreprocessingFlags
Functions
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCooking *PX_CALL_CONV PxCreateCooking (physx::PxU32 version, physx::PxFoundation &foundation, const physx::PxCookingParams &params)
Create an instance of the cooking interface.
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxInsertionCallback * PxGetStandaloneInsertionCallback ()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookBVH (const physx::PxBVHDesc &desc, physx::PxOutputStream &stream)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxBVH * PxCreateBVH (const physx::PxBVHDesc &desc, physx::PxInsertionCallback &insertionCallback)
PX_FORCE_INLINE physx::PxBVH * PxCreateBVH (const physx::PxBVHDesc &desc)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookHeightField (const physx::PxHeightFieldDesc &desc, physx::PxOutputStream &stream)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxHeightField * PxCreateHeightField (const physx::PxHeightFieldDesc &desc, physx::PxInsertionCallback &insertionCallback)
PX_FORCE_INLINE physx::PxHeightField * PxCreateHeightField (const physx::PxHeightFieldDesc &desc)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookConvexMesh (const physx::PxCookingParams &params, const physx::PxConvexMeshDesc &desc, physx::PxOutputStream &stream, physx::PxConvexMeshCookingResult::Enum *condition=NULL)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxConvexMesh * PxCreateConvexMesh (const physx::PxCookingParams &params, const physx::PxConvexMeshDesc &desc, physx::PxInsertionCallback &insertionCallback, physx::PxConvexMeshCookingResult::Enum *condition=NULL)
PX_FORCE_INLINE physx::PxConvexMesh * PxCreateConvexMesh (const physx::PxCookingParams &params, const physx::PxConvexMeshDesc &desc)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxValidateConvexMesh (const physx::PxCookingParams &params, const physx::PxConvexMeshDesc &desc)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxComputeHullPolygons (const physx::PxCookingParams &params, const physx::PxSimpleTriangleMesh &mesh, physx::PxAllocatorCallback &inCallback, physx::PxU32 &nbVerts, physx::PxVec3 *&vertices, physx::PxU32 &nbIndices, physx::PxU32 *&indices, physx::PxU32 &nbPolygons, physx::PxHullPolygon *&hullPolygons)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxValidateTriangleMesh (const physx::PxCookingParams &params, const physx::PxTriangleMeshDesc &desc)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxTriangleMesh * PxCreateTriangleMesh (const physx::PxCookingParams &params, const physx::PxTriangleMeshDesc &desc, physx::PxInsertionCallback &insertionCallback, physx::PxTriangleMeshCookingResult::Enum *condition=NULL)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookTriangleMesh (const physx::PxCookingParams &params, const physx::PxTriangleMeshDesc &desc, physx::PxOutputStream &stream, physx::PxTriangleMeshCookingResult::Enum *condition=NULL)
PX_FORCE_INLINE physx::PxTriangleMesh * PxCreateTriangleMesh (const physx::PxCookingParams &params, const physx::PxTriangleMeshDesc &desc)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookTetrahedronMesh (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &meshDesc, physx::PxOutputStream &stream)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxTetrahedronMesh * PxCreateTetrahedronMesh (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &meshDesc, physx::PxInsertionCallback &insertionCallback)
PX_FORCE_INLINE physx::PxTetrahedronMesh * PxCreateTetrahedronMesh (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &meshDesc)
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookSoftBodyMesh (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &simulationMeshDesc, const physx::PxTetrahedronMeshDesc &collisionMeshDesc, const physx::PxSoftBodySimulationDataDesc &softbodyDataDesc, physx::PxOutputStream &stream)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSoftBodyMesh * PxCreateSoftBodyMesh (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &simulationMeshDesc, const physx::PxTetrahedronMeshDesc &collisionMeshDesc, const physx::PxSoftBodySimulationDataDesc &softbodyDataDesc, physx::PxInsertionCallback &insertionCallback)
PX_FORCE_INLINE physx::PxSoftBodyMesh * PxCreateSoftBodyMesh (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &simulationMeshDesc, const physx::PxTetrahedronMeshDesc &collisionMeshDesc, const physx::PxSoftBodySimulationDataDesc &softbodyDataDesc)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCollisionMeshMappingData * PxComputeModelsMapping (const physx::PxCookingParams &params, physx::PxTetrahedronMeshData &simulationMesh, const physx::PxTetrahedronMeshData &collisionMesh, const physx::PxSoftBodyCollisionData &collisionData, const physx::PxBoundedData *vertexToTet=NULL)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCollisionTetrahedronMeshData * PxComputeCollisionData (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &collisionMeshDesc)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSimulationTetrahedronMeshData * PxComputeSimulationData (const physx::PxCookingParams &params, const physx::PxTetrahedronMeshDesc &simulationMeshDesc)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSoftBodyMesh * PxAssembleSoftBodyMesh (physx::PxTetrahedronMeshData &simulationMesh, physx::PxSoftBodySimulationData &simulationData, physx::PxTetrahedronMeshData &collisionMesh, physx::PxSoftBodyCollisionData &collisionData, physx::PxCollisionMeshMappingData &mappingData, physx::PxInsertionCallback &insertionCallback)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSoftBodyMesh * PxAssembleSoftBodyMesh_Sim (physx::PxSimulationTetrahedronMeshData &simulationMesh, physx::PxCollisionTetrahedronMeshData &collisionMesh, physx::PxCollisionMeshMappingData &mappingData, physx::PxInsertionCallback &insertionCallback)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxTriangleMesh *PX_CALL_CONV PxCreateTriangleMeshInternal (const physx::PxTriangleMeshInternalData &data, const physx::PxCooking &cooking)
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxBVH *PX_CALL_CONV PxCreateBVHInternal (const physx::PxBVHInternalData &data, const physx::PxCooking &cooking)
PX_INLINE PxBVHDesc::PxBVHDesc ()
PX_INLINE void PxBVHDesc::setToDefault ()
Initialize the BVH descriptor.
PX_INLINE bool PxBVHDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxConvexMeshDesc::PxConvexMeshDesc ()
constructor sets to default.
PX_INLINE void PxConvexMeshDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxConvexMeshDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxSDFDesc::PxSDFDesc ()
Constructor.
PX_INLINE bool PxSDFDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxTriangleMeshDesc::PxTriangleMeshDesc ()
Constructor sets to default.
PX_INLINE void PxTriangleMeshDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxTriangleMeshDesc::isValid () const
Returns true if the descriptor is valid.
Detailed Description
Typedef Documentation
PxBVHStructureDesc
typedef PX_DEPRECATED PxBVHDesc PxBVHStructureDesc
PxConvexFlags
typedef PxFlags<PxConvexFlag::Enum,PxU16> PxConvexFlags
collection of set bits defined in PxConvexFlag.
See also
PxConvexFlag
PxMeshPreprocessingFlags
typedef PxFlags<PxMeshPreprocessingFlag::Enum,PxU32> PxMeshPreprocessingFlags
Function Documentation
isValid() [1/4]
PX_INLINE bool PxTriangleMeshDesc::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid
References PxSimpleTriangleMesh::isValid().
isValid() [2/4]
PX_INLINE bool PxBVHDesc::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid.
References PxBVHDesc::bounds, PxBoundedData::count, PxStridedData::data, PxBVHDesc::enlargement, PxBVHDesc::numPrimsPerLeaf, and PxStridedData::stride.
isValid() [3/4]
PX_INLINE bool PxSDFDesc::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid
Referenced by PxConvexMeshDesc::isValid().
isValid() [4/4]
PX_INLINE bool PxConvexMeshDesc::isValid () const
Returns true if the descriptor is valid.
Returns
True if the current settings are valid
References PxBoundedData::count, PxStridedData::data, PxConvexFlag::e16_BIT_INDICES, PxConvexFlag::eCOMPUTE_CONVEX, PxConvexFlag::ePLANE_SHIFTING, PxConvexMeshDesc::flags, PxConvexMeshDesc::indices, PxSDFDesc::isValid(), PxConvexMeshDesc::points, PxConvexMeshDesc::polygons, PxConvexMeshDesc::quantizedCount, PxConvexMeshDesc::sdfDesc, PxStridedData::stride, and PxConvexMeshDesc::vertexLimit.
PxAssembleSoftBodyMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSoftBodyMesh* PxAssembleSoftBodyMesh (physx::PxTetrahedronMeshData & simulationMesh, physx::PxSoftBodySimulationData & simulationData, physx::PxTetrahedronMeshData & collisionMesh, physx::PxSoftBodyCollisionData & collisionData, physx::PxCollisionMeshMappingData & mappingData, physx::PxInsertionCallback & insertionCallback)
PxAssembleSoftBodyMesh_Sim()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSoftBodyMesh* PxAssembleSoftBodyMesh_Sim (physx::PxSimulationTetrahedronMeshData & simulationMesh, physx::PxCollisionTetrahedronMeshData & collisionMesh, physx::PxCollisionMeshMappingData & mappingData, physx::PxInsertionCallback & insertionCallback)
PxBVHDesc()
PX_INLINE PxBVHDesc::PxBVHDesc ()
Referenced by PxBVHDesc::setToDefault().
PxComputeCollisionData()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCollisionTetrahedronMeshData* PxComputeCollisionData (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & collisionMeshDesc)
PxComputeHullPolygons()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxComputeHullPolygons (const physx::PxCookingParams & params, const physx::PxSimpleTriangleMesh & mesh, physx::PxAllocatorCallback & inCallback, physx::PxU32 & nbVerts, physx::PxVec3 *& vertices, physx::PxU32 & nbIndices, physx::PxU32 *& indices, physx::PxU32 & nbPolygons, physx::PxHullPolygon *& hullPolygons)
PxComputeModelsMapping()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCollisionMeshMappingData* PxComputeModelsMapping (const physx::PxCookingParams & params, physx::PxTetrahedronMeshData & simulationMesh, const physx::PxTetrahedronMeshData & collisionMesh, const physx::PxSoftBodyCollisionData & collisionData, const physx::PxBoundedData * vertexToTet = NULL)
PxComputeSimulationData()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSimulationTetrahedronMeshData* PxComputeSimulationData (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & simulationMeshDesc)
PxConvexMeshDesc()
PX_INLINE PxConvexMeshDesc::PxConvexMeshDesc ()
constructor sets to default.
Referenced by PxConvexMeshDesc::setToDefault().
PxCookBVH()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookBVH (const physx::PxBVHDesc & desc, physx::PxOutputStream & stream)
PxCookConvexMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookConvexMesh (const physx::PxCookingParams & params, const physx::PxConvexMeshDesc & desc, physx::PxOutputStream & stream, physx::PxConvexMeshCookingResult::Enum * condition = NULL)
PxCookHeightField()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookHeightField (const physx::PxHeightFieldDesc & desc, physx::PxOutputStream & stream)
PxCookSoftBodyMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookSoftBodyMesh (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & simulationMeshDesc, const physx::PxTetrahedronMeshDesc & collisionMeshDesc, const physx::PxSoftBodySimulationDataDesc & softbodyDataDesc, physx::PxOutputStream & stream)
PxCookTetrahedronMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookTetrahedronMesh (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & meshDesc, physx::PxOutputStream & stream)
PxCookTriangleMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxCookTriangleMesh (const physx::PxCookingParams & params, const physx::PxTriangleMeshDesc & desc, physx::PxOutputStream & stream, physx::PxTriangleMeshCookingResult::Enum * condition = NULL)
PxCreateBVH() [1/2]
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxBVH* PxCreateBVH (const physx::PxBVHDesc & desc, physx::PxInsertionCallback & insertionCallback)
Referenced by PxCreateBVH().
PxCreateBVH() [2/2]
PX_FORCE_INLINE physx::PxBVH* PxCreateBVH (const physx::PxBVHDesc & desc)
References PxCreateBVH(), and PxGetStandaloneInsertionCallback().
PxCreateBVHInternal()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxBVH* PX_CALL_CONV PxCreateBVHInternal (const physx::PxBVHInternalData & data, const physx::PxCooking & cooking)
PxCreateConvexMesh() [1/2]
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxConvexMesh* PxCreateConvexMesh (const physx::PxCookingParams & params, const physx::PxConvexMeshDesc & desc, physx::PxInsertionCallback & insertionCallback, physx::PxConvexMeshCookingResult::Enum * condition = NULL)
Referenced by PxCreateConvexMesh().
PxCreateConvexMesh() [2/2]
PX_FORCE_INLINE physx::PxConvexMesh* PxCreateConvexMesh (const physx::PxCookingParams & params, const physx::PxConvexMeshDesc & desc)
References PxCreateConvexMesh(), and PxGetStandaloneInsertionCallback().
PxCreateCooking()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxCooking* PX_CALL_CONV PxCreateCooking (physx::PxU32 version, physx::PxFoundation & foundation, const physx::PxCookingParams & params)
Create an instance of the cooking interface.
Note that the foundation object is handled as an application-wide singleton in statically linked executables and a DLL-wide singleton in dynamically linked executables. Therefore, if you are using the runtime SDK in the same executable as cooking, you should pass the Physics's copy of foundation (acquired with PxPhysics::getFoundation()) to the cooker. This will also ensure correct handling of memory for objects passed from the cooker to the SDK.
To use cooking in standalone mode, create an instance of the Foundation object with PxCreateFoundation. You should pass the same foundation object to all instances of the cooking interface.
Parameters
[in] version The SDK version number
[in] foundation The foundation object associated with this instance of the cooking interface.
[in] params The parameters for this instance of the cooking interface
Returns
true on success.
PxCreateHeightField() [1/2]
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxHeightField* PxCreateHeightField (const physx::PxHeightFieldDesc & desc, physx::PxInsertionCallback & insertionCallback)
Referenced by PxCreateHeightField().
PxCreateHeightField() [2/2]
PX_FORCE_INLINE physx::PxHeightField* PxCreateHeightField (const physx::PxHeightFieldDesc & desc)
References PxCreateHeightField(), and PxGetStandaloneInsertionCallback().
PxCreateSoftBodyMesh() [1/2]
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxSoftBodyMesh* PxCreateSoftBodyMesh (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & simulationMeshDesc, const physx::PxTetrahedronMeshDesc & collisionMeshDesc, const physx::PxSoftBodySimulationDataDesc & softbodyDataDesc, physx::PxInsertionCallback & insertionCallback)
Referenced by PxCreateSoftBodyMesh().
PxCreateSoftBodyMesh() [2/2]
PX_FORCE_INLINE physx::PxSoftBodyMesh* PxCreateSoftBodyMesh (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & simulationMeshDesc, const physx::PxTetrahedronMeshDesc & collisionMeshDesc, const physx::PxSoftBodySimulationDataDesc & softbodyDataDesc)
References PxCreateSoftBodyMesh(), and PxGetStandaloneInsertionCallback().
PxCreateTetrahedronMesh() [1/2]
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxTetrahedronMesh* PxCreateTetrahedronMesh (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & meshDesc, physx::PxInsertionCallback & insertionCallback)
Referenced by PxCreateTetrahedronMesh().
PxCreateTetrahedronMesh() [2/2]
PX_FORCE_INLINE physx::PxTetrahedronMesh* PxCreateTetrahedronMesh (const physx::PxCookingParams & params, const physx::PxTetrahedronMeshDesc & meshDesc)
References PxCreateTetrahedronMesh(), and PxGetStandaloneInsertionCallback().
PxCreateTriangleMesh() [1/2]
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxTriangleMesh* PxCreateTriangleMesh (const physx::PxCookingParams & params, const physx::PxTriangleMeshDesc & desc, physx::PxInsertionCallback & insertionCallback, physx::PxTriangleMeshCookingResult::Enum * condition = NULL)
Referenced by PxCreateTriangleMesh().
PxCreateTriangleMesh() [2/2]
PX_FORCE_INLINE physx::PxTriangleMesh* PxCreateTriangleMesh (const physx::PxCookingParams & params, const physx::PxTriangleMeshDesc & desc)
References PxCreateTriangleMesh(), and PxGetStandaloneInsertionCallback().
PxCreateTriangleMeshInternal()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxTriangleMesh* PX_CALL_CONV PxCreateTriangleMeshInternal (const physx::PxTriangleMeshInternalData & data, const physx::PxCooking & cooking)
PxGetStandaloneInsertionCallback()
PX_C_EXPORT PX_PHYSX_COOKING_API physx::PxInsertionCallback* PxGetStandaloneInsertionCallback ()
Referenced by PxCreateBVH(), PxCreateConvexMesh(), PxCreateHeightField(), PxCreateSoftBodyMesh(), PxCreateTetrahedronMesh(), and PxCreateTriangleMesh().
PxSDFDesc()
PX_INLINE PxSDFDesc::PxSDFDesc ()
Constructor.
References PxSdfBitsPerSubgridPixel::e16_BIT_PER_PIXEL, PxBounds3::empty(), and PxZero.
PxTriangleMeshDesc()
PX_INLINE PxTriangleMeshDesc::PxTriangleMeshDesc ()
Constructor sets to default.
References PxSimpleTriangleMesh::setToDefault().
PxValidateConvexMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxValidateConvexMesh (const physx::PxCookingParams & params, const physx::PxConvexMeshDesc & desc)
PxValidateTriangleMesh()
PX_C_EXPORT PX_PHYSX_COOKING_API bool PxValidateTriangleMesh (const physx::PxCookingParams & params, const physx::PxTriangleMeshDesc & desc)
setToDefault() [1/3]
PX_INLINE void PxTriangleMeshDesc::setToDefault ()
(re)sets the structure to the default.
setToDefault() [2/3]
PX_INLINE void PxBVHDesc::setToDefault ()
Initialize the BVH descriptor.
References PxBVHDesc::PxBVHDesc().
setToDefault() [3/3]
PX_INLINE void PxConvexMeshDesc::setToDefault ()
(re)sets the structure to the default.
References PxConvexMeshDesc::PxConvexMeshDesc().