Physics
Physics
Classes
struct PxMetaDataEntry
Struct to store meta data definitions.
class PxStringTable
a table to manage strings. Strings allocated through this object are expected to be owned by this object.
struct PxActorFlag
Flags which control the behavior of an actor.
struct PxActorType
Identifies each type of actor.
class PxActor
PxActor is the base class for the main simulation objects in the physics SDK.
struct PxActorCacheFlag
Identifies each type of information for retrieving from actor.
struct PxGpuBodyData
State of a body used when interfacing with the GPU rigid body pipeline.
struct PxGpuActorProperties
Inertia properties of an actor used when interfacing with the GPU rigid body pipeline.
struct PxGpuActorPair
Pair correspondence used for matching array indices with body node indices.
struct PxIndexDataPair
Maps numeric index to a data pointer.
struct PxAggregateType
class PxAggregate
Class to aggregate actors into a single broad-phase entry.
class PxArticulationJointReducedCoordinate
A joint between two links in an articulation.
class PxArticulationLink
A component of an articulation that represents a rigid body.
struct PxSpatialForce
Data structure to represent spatial forces.
struct PxSpatialVelocity
Data structure to represent spatial velocities.
struct PxArticulationRootLinkData
Data structure used to access the root link state and acceleration.
class PxArticulationCache
Data structure used to read and write internal articulation data.
struct PxArticulationSensorFlag
Flags to configure the forces reported by articulation link sensors.
class PxArticulationSensor
A force sensor that can be attached to articulation links to measure spatial force.
struct PxArticulationKinematicFlag
Flag that configures articulation-state updates by PxArticulationReducedCoordinate::updateKinematic.
class PxArticulationReducedCoordinate
A tree structure of bodies connected by joints that is treated as a unit by the dynamics solver. Parametrized in reduced (joint) coordinates.
class PxArticulationTendonLimit
Defines the low/high limits of a spatial tendon attachment or a fixed tendon.
class PxArticulationAttachment
Defines a spatial tendon attachment point on a link.
class PxArticulationTendonJoint
Defines a fixed-tendon joint between a parent and child link.
class PxArticulationTendon
Common base class shared by PxArticulationSpatialTendon and PxArticulationFixedTendon.
class PxArticulationSpatialTendon
A spatial tendon that attaches to an articulation.
class PxArticulationFixedTendon
A fixed tendon that can be used to link multiple degrees of freedom of multiple articulation joints via length and limit constraints.
struct PxParticleRigidAttachment
Struct to specify attachment between a particle/vertex and a rigid.
class PxBaseMaterial
Base material class.
struct PxBroadPhaseType
Broad phase algorithm used in the simulation.
class PxBroadPhaseCallback
Broad-phase callback to receive broad-phase related events.
struct PxBroadPhaseRegion
"Region of interest" for the broad-phase.
struct PxBroadPhaseRegionInfo
Information & stats structure for a region.
struct PxBroadPhaseCaps
Caps class for broad phase.
struct PxBufferType
Specifies memory space for a PxBuffer instance.
class PxBuffer
Buffer for delayed bulk read and write operations supporting host and GPU device memory spaces.
struct PxConeLimitedConstraint
A constraint descriptor for limiting movement to a conical region.
struct PxConeLimitParams
Compressed form of cone limit parameters.
struct PxConstraintFlag
constraint flags
struct PxConstraintShaderTable
a table of function pointers for a constraint
class PxConstraint
A plugin class for implementing constraints.
struct Px1DConstraintFlag
Constraint row flags.
struct PxConstraintSolveHint
Constraint type hints which the solver uses to optimize constraint handling.
struct Px1DConstraint
A one-dimensional constraint.
struct PxConstraintVisualizationFlag
Flags for determining which components of the constraint should be visualized.
struct PxConstraintInvMassScale
Struct for specifying mass scaling for a pair of rigids.
class PxConstraintVisualizer
API used to visualize details about a constraint.
struct PxPvdUpdateType
Flags for determining how PVD should serialize a constraint update.
class PxConstraintConnector
This class connects a custom constraint to the SDK.
struct PxMassModificationProps
Struct for specifying mass modification for a pair of rigids.
struct PxContactPatch
Header for a contact patch where all points share same material and normal.
struct PxContact
Contact point data.
struct PxExtendedContact
Contact point data with additional target and max impulse values.
struct PxModifiableContact
A modifiable contact point. This has additional fields per-contact to permit modification by user.
struct PxContactStreamIterator
A class to iterate over a compressed contact stream. This supports read-only access to the various contact formats.
struct PxGpuContactPair
Contains contact information for a contact reported by the direct-GPU contact report API. See PxScene::copyContactData().
class PxContactSet
An array of contact points, as passed to contact modification.
class PxContactModifyPair
An array of instances of this class is passed to PxContactModifyCallback::onContactModify().
class PxContactModifyCallback
An interface class that the user can implement in order to modify contact constraints.
class PxCCDContactModifyCallback
An interface class that the user can implement in order to modify CCD contact constraints.
class PxCustomParticleSystemSolverCallback
struct PxDeletionEventFlag
Flags specifying deletion event types.
class PxDeletionListener
interface to get notification on object deletion
class PxFEMClothMaterial
Material class to represent a set of FEM material properties.
class PxFEMMaterial
Material class to represent a set of FEM material properties.
class PxFEMSoftBodyMaterial
Material class to represent a set of softbody FEM material properties.
struct PxPairFlag
Collection of flags describing the actions to take for a collision pair.
struct PxFilterFlag
Collection of flags describing the filter actions to take for a collision pair.
struct PxFilterData
PxFilterData is user-definable data which gets passed into the collision filtering shader and/or callback.
struct PxFilterObjectType
Identifies each type of filter object.
struct PxFilterObjectFlag
class PxSimulationFilterCallback
Filter callback to specify handling of collision pairs.
struct PxPairFilteringMode
struct PxParticleRigidFilterPair
Struct for storing a particle/vertex - rigid filter pair with comparison operators.
class PxFLIPMaterial
Material class to represent a set of FLIP particle material properties.
struct PxForceMode
Parameter to addForce() and addTorque() calls, determines the exact operation that is carried out.
struct PxDataAccessFlag
class PxLockedData
Parent class for bulk data that is shared between the SDK and the application.
struct PxMaterialFlag
Flags which control the behavior of a material.
struct PxCombineMode
Enumeration that determines the way in which two material properties will be combined to yield a friction or restitution coefficient for a collision.
class PxMaterial
Material class to represent a set of surface properties.
struct PxMPMMaterialModel
MPM material models.
struct PxMPMSurfaceType
MPM surface types that influence interaction between particles and obstacles.
struct PxMPMCuttingFlag
Optional MPM modes that improve the quality of fracture and/or cutting.
class PxMPMMaterial
Material class to represent a set of MPM particle material properties.
struct PxParticleVolume
Particle volume structure. Used to track the bounding volume of a user-specified set of particles. The particles are required to be laid out contiguously within the same PxParticleBuffer.
class PxParticleBuffer
The shared base class for all particle buffers, can be instantiated directly to specify granular and fluid particles.
class PxDiffuseParticleParams
Parameters to configure the behavior of diffuse particles.
class PxParticleAndDiffuseBuffer
A particle buffer used to simulate diffuse particles.
struct PxParticleCloth
Particle cloth structure. Holds information about a single piece of cloth that is part of a PxParticleClothBuffer.
struct PxParticleClothDesc
Structure to describe the set of particle cloths in the same PxParticleClothBuffer. Used an input for the cloth preprocessing.
struct PxPartitionedParticleCloth
Structure to describe the output of the particle cloth preprocessing. Used as an input to specify cloth data for a PxParticleClothBuffer. All the pointers point to pinned host memory.
class PxParticleClothBuffer
A particle buffer used to simulate particle cloth.
class PxParticleRigidBuffer
A particle buffer used to simulate rigid bodies using shape matching with particles.
class PxParticleClothPreProcessor
Preprocessor to prepare particle cloths for simulation.
struct PxsParticleMaterialData
class PxParticleMaterial
Material class to represent a set of particle material properties.
struct PxParticlePhaseFlag
Identifies per-particle behavior for PxParticleSystem.
class PxParticlePhase
A per particle identifier to define the particles behavior, its group and to reference a material.
struct PxParticleSolverType
Identifies the solver to use for a particle system.
struct PxGpuMirroredPointer< Type >
Container to hold a pair of corresponding device and host pointers. These pointers should point to GPU / CPU mirrors of the same data, but this is not enforced.
class PxParticleSystemCallback
Particle system callback base class to schedule work that should be done before, while or after the particle system updates. A call to fetchResultsParticleSystem() on the PxScene will synchronize the work such that the caller knows that all tasks of this callback completed.
struct PxParticleFlag
Flags which control the behaviour of a particle system.
class PxParticleSystem
The shared base class for all particle systems.
class PxPBDMaterial
Material class to represent a set of PBD particle material properties.
class PxCustomMaterial
class PxPBDParticleSystem
A particle system that uses the position based dynamics solver.
class PxPhysics
Abstract singleton factory class used for instancing objects in the Physics SDK.
class PxPruningStructure
A precomputed pruning structure to accelerate scene queries against newly added actors.
class PxRigidActor
PxRigidActor represents a base class shared between dynamic and static rigid bodies in the physics SDK.
struct PxRigidBodyFlag
Collection of flags describing the behavior of a rigid body.
class PxRigidBody
PxRigidBody is a base class shared between dynamic rigid body objects.
struct PxRigidDynamicLockFlag
Collection of flags providing a mechanism to lock motion along/around a specific axis.
class PxRigidDynamic
PxRigidDynamic represents a dynamic rigid simulation object in the physics SDK.
class PxRigidStatic
PxRigidStatic represents a static rigid body simulation object in the physics SDK.
struct PxDominanceGroupPair
Expresses the dominance relationship of a contact. For the time being only three settings are permitted:
struct PxActorTypeFlag
Identifies each type of actor for retrieving actors from a scene.
class PxScene
A scene is a collection of bodies and constraints which can interact.
struct PxFrictionType
Enum for selecting the friction algorithm used for simulation.
struct PxSolverType
Enum for selecting the type of solver used for the simulation.
struct PxSceneFlag
flags for configuring properties of the scene
class PxSceneLimits
Class used to retrieve limits(e.g. maximum number of bodies) for a scene. The limits are used as a hint to the size of the scene, not as a hard limit (i.e. it will be possible to create more objects than specified in the scene limits).
struct PxgDynamicsMemoryConfig
Sizes of pre-allocated buffers use for GPU dynamics.
class PxSceneDesc
Descriptor class for scenes. See PxScene.
class PxSceneReadLock
RAII wrapper for the PxScene read lock.
class PxSceneWriteLock
RAII wrapper for the PxScene write lock.
struct PxPruningStructureType
Pruning structure used to accelerate scene queries.
struct PxDynamicTreeSecondaryPruner
Secondary pruning structure used for newly added objects in dynamic trees.
struct PxSceneQueryUpdateMode
Scene query update mode.
class PxSceneQueryDesc
Descriptor class for scene query system. See PxSceneQuerySystem.
class PxSceneQuerySystemBase
Base class for the scene-query system.
class PxSceneSQSystem
Traditional SQ system for PxScene.
class PxSceneQuerySystem
Scene-queries external sub-system for PxScene-based objects.
struct PxShapeFlag
Flags which affect the behavior of PxShapes.
class PxShape
Abstract class for collision shapes.
struct PxContactPairExtraDataType
Extra data item types for contact pairs.
struct PxContactPairExtraDataItem
Base class for items in the extra data stream of contact pairs.
struct PxContactPairVelocity
Velocities of the contact pair rigid bodies.
struct PxContactPairPose
World space actor poses of the contact pair rigid bodies.
struct PxContactPairIndex
Marker for the beginning of a new item set in the extra data stream.
struct PxContactPairExtraDataIterator
A class to iterate over a contact pair extra data stream.
struct PxContactPairHeaderFlag
Collection of flags providing information on contact report pairs.
struct PxContactPairHeader
An Instance of this class is passed to PxSimulationEventCallback.onContact().
struct PxContactPairFlag
Collection of flags providing information on contact report pairs.
struct PxContactPairPoint
A contact point as used by contact notification.
struct PxContactPair
Contact report pair information.
struct PxTriggerPairFlag
Collection of flags providing information on trigger report pairs.
struct PxTriggerPair
Descriptor for a trigger pair.
struct PxConstraintInfo
Descriptor for a broken constraint.
class PxSimulationEventCallback
An interface class that the user can implement in order to receive simulation events.
class PxSimulationStatistics
Class used to retrieve statistics for a simulation step.
struct PxSoftBodyData
Identifies input and output buffers for PxSoftBody.
struct PxSoftBodyFlag
Flags to enable or disable special modes of a SoftBody.
class PxSoftBody
Represents a FEM softbody including everything to calculate its definition like geometry and material properties.
struct PxSparseGridParams
Parameters to define the sparse grid settings like grid spacing, maximal number of subgrids etc.
struct PxVisualizationParameter
Debug visualization parameters.
struct PxArticulationAxis
struct PxArticulationMotion
struct PxArticulationJointType
struct PxArticulationFlag
struct PxArticulationDriveType
struct PxArticulationLimit
Data structure to set articulation joint limits.
struct PxArticulationDrive
Data structure for articulation joint drive configuration.
Macros
#define PX_STORE_METADATA(stream, metaData) stream.write(&metaData, sizeof(PxMetaDataEntry))
#define PX_SIZE_OF(Class, Member) sizeof((reinterpret_cast<Class*>(0))->Member)
#define PX_DEF_BIN_METADATA_ITEM(stream, Class, type, name, flags)
specifies a binary metadata entry for a member variable of a class
#define PX_DEF_BIN_METADATA_ITEMS(stream, Class, type, name, flags, count)
specifies a binary metadata entry for a member array variable of a class
#define PX_DEF_BIN_METADATA_ITEMS_AUTO(stream, Class, type, name, flags)
specifies a binary metadata entry for a member array variable of a class
#define PX_DEF_BIN_METADATA_CLASS(stream, Class)
specifies a binary metadata entry for a class
#define PX_DEF_BIN_METADATA_VCLASS(stream, Class)
specifies a binary metadata entry for a virtual class
#define PX_DEF_BIN_METADATA_TYPEDEF(stream, newType, oldType)
specifies a binary metadata entry for a typedef
#define PX_DEF_BIN_METADATA_BASE_CLASS(stream, Class, BaseClass)
specifies a binary metadata entry for declaring a base class
#define PX_DEF_BIN_METADATA_UNION(stream, Class, name)
specifies a binary metadata entry for a union
#define PX_DEF_BIN_METADATA_UNION_TYPE(stream, Class, type, enumValue)
specifies a binary metadata entry for a particular member type of a union
#define PX_DEF_BIN_METADATA_EXTRA_ITEM(stream, Class, type, control, align)
specifies a binary metadata entry for extra data
#define PX_DEF_BIN_METADATA_EXTRA_ITEMS(stream, Class, type, control, count, flags, align)
specifies a binary metadata entry for an array of extra data
#define PX_DEF_BIN_METADATA_EXTRA_ITEMS_MASKED_CONTROL(stream, Class, type, control, controlMask, count, flags, align)
specifies a binary metadata entry for an array of extra data additional to PX_DEF_BIN_METADATA_EXTRA_ITEMS a mask can be specified to interpret the control value
#define PX_DEF_BIN_METADATA_EXTRA_ARRAY(stream, Class, type, dyn_count, align, flags)
specifies a binary metadata entry for an array of extra data
#define PX_DEF_BIN_METADATA_EXTRA_NAME(stream, Class, control, align)
specifies a binary metadata entry for an string of extra data
#define PX_DEF_BIN_METADATA_EXTRA_ALIGN(stream, Class, align)
specifies a binary metadata entry declaring an extra data alignment for a class
#define PXC_CONTACT_NO_FACE_INDEX 0xffffffff
#define PX_MAX_TETID 0x000fffff
The maximum tetrahedron index supported in the model.
Typedefs
typedef PxU8 PxDominanceGroup
Group index which allows to specify 1- or 2-way interaction.
typedef PxFlags< PxActorFlag::Enum, PxU8 > PxActorFlags
collection of set bits defined in PxActorFlag.
typedef PxFlags< PxActorCacheFlag::Enum, PxU16 > PxActorCacheFlags
Collection of set bits defined in PxActorCacheFlag.
typedef PxU32 PxAggregateFilterHint
typedef physx::PxFlags< PxArticulationSensorFlag::Enum, PxU8 > PxArticulationSensorFlags
typedef physx::PxFlags< PxArticulationKinematicFlag::Enum, PxU8 > PxArticulationKinematicFlags
typedef PxFlags< PxConstraintFlag::Enum, PxU16 > PxConstraintFlags
constraint flags
typedef PxFlags< Px1DConstraintFlag::Type, PxU16 > Px1DConstraintFlags
typedef PxU32(* PxConstraintSolverPrep) (Px1DConstraint *constraints, PxVec3p &bodyAWorldOffset, PxU32 maxConstraints, PxConstraintInvMassScale &invMassScale, const void *constantBlock, const PxTransform &bodyAToWorld, const PxTransform &bodyBToWorld, bool useExtendedLimits, PxVec3p &cAtW, PxVec3p &cBtW)
Solver constraint generation shader.
typedef void(* PxConstraintProject) (const void *constantBlock, PxTransform &bodyAToWorld, PxTransform &bodyBToWorld, bool projectToA)
Solver constraint projection shader.
typedef void(* PxConstraintVisualize) (PxConstraintVisualizer &visualizer, const void *constantBlock, const PxTransform &body0Transform, const PxTransform &body1Transform, PxU32 flags)
Solver constraint visualization function.
typedef PxFlags< PxDeletionEventFlag::Enum, PxU8 > PxDeletionEventFlags
Collection of set bits defined in PxDeletionEventFlag.
typedef PxFlags< PxPairFlag::Enum, PxU16 > PxPairFlags
Bitfield that contains a set of raised flags defined in PxPairFlag.
typedef PxFlags< PxFilterFlag::Enum, PxU16 > PxFilterFlags
Bitfield that contains a set of raised flags defined in PxFilterFlag.
typedef PxU32 PxFilterObjectAttributes
Structure which gets passed into the collision filtering shader and/or callback providing additional information on objects of a collision pair.
typedef PxFilterFlags(* PxSimulationFilterShader) (PxFilterObjectAttributes attributes0, PxFilterData filterData0, PxFilterObjectAttributes attributes1, PxFilterData filterData1, PxPairFlags &pairFlags, const void *constantBlock, PxU32 constantBlockSize)
Filter method to specify how a pair of potentially colliding objects should be processed.
typedef PxFlags< PxDataAccessFlag::Enum, PxU8 > PxDataAccessFlags
collection of set bits defined in PxDataAccessFlag.
typedef PxFlags< PxMaterialFlag::Enum, PxU16 > PxMaterialFlags
collection of set bits defined in PxMaterialFlag.
typedef PxFlags< PxMPMCuttingFlag::Enum, PxU16 > PxMPMCuttingFlags
typedef PxFlags< PxParticlePhaseFlag::Enum, PxU32 > PxParticlePhaseFlags
typedef PxFlags< PxParticleFlag::Enum, PxU32 > PxParticleFlags
typedef PX_DEPRECATED PxBVH PxBVHStructure
typedef PxFlags< PxRigidBodyFlag::Enum, PxU16 > PxRigidBodyFlags
collection of set bits defined in PxRigidBodyFlag.
typedef PxFlags< PxRigidDynamicLockFlag::Enum, PxU8 > PxRigidDynamicLockFlags
typedef PxU8 PxDominanceGroup
typedef PxFlags< PxActorTypeFlag::Enum, PxU16 > PxActorTypeFlags
Collection of set bits defined in PxActorTypeFlag.
typedef PxFlags< PxSceneFlag::Enum, PxU32 > PxSceneFlags
collection of set bits defined in PxSceneFlag.
typedef PxU32 PxSQCompoundHandle
typedef PxU32 PxSQPrunerHandle
typedef void * PxSQBuildStepHandle
typedef PxFlags< PxShapeFlag::Enum, PxU8 > PxShapeFlags
collection of set bits defined in PxShapeFlag.
typedef PxFlags< PxContactPairHeaderFlag::Enum, PxU16 > PxContactPairHeaderFlags
Bitfield that contains a set of raised flags defined in PxContactPairHeaderFlag.
typedef PxFlags< PxContactPairFlag::Enum, PxU16 > PxContactPairFlags
Bitfield that contains a set of raised flags defined in PxContactPairFlag.
typedef PxFlags< PxTriggerPairFlag::Enum, PxU8 > PxTriggerPairFlags
Bitfield that contains a set of raised flags defined in PxTriggerPairFlag.
typedef PxFlags< PxSoftBodyData::Enum, PxU32 > PxSoftBodyDataFlags
typedef PxFlags< PxSoftBodyFlag::Enum, PxU32 > PxSoftBodyFlags
typedef PxFlags< PxArticulationMotion::Enum, PxU8 > PxArticulationMotions
typedef PxFlags< PxArticulationFlag::Enum, PxU8 > PxArticulationFlags
Enumerations
enum PxScenePrunerIndex { PX_SCENE_PRUNER_STATIC = 0, PX_SCENE_PRUNER_DYNAMIC = 1, PX_SCENE_COMPOUND_PRUNER = 0xffffffff }
Built-in enum for default PxScene pruners.
Functions
PX_CUDA_CALLABLE PX_FORCE_INLINE PxAggregateFilterHint PxGetAggregateFilterHint (PxAggregateType::Enum type, bool enableSelfCollision)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU32 PxGetAggregateSelfCollisionBit (PxAggregateFilterHint hint)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxAggregateType::Enum PxGetAggregateType (PxAggregateFilterHint hint)
PX_INLINE PxFilterObjectType::Enum PxGetFilterObjectType (PxFilterObjectAttributes attr)
Extract filter object type from the filter attributes of a collision pair object.
PX_INLINE bool PxFilterObjectIsKinematic (PxFilterObjectAttributes attr)
Specifies whether the collision object belongs to a kinematic rigid body.
PX_INLINE bool PxFilterObjectIsTrigger (PxFilterObjectAttributes attr)
Specifies whether the collision object is a trigger shape.
struct PX_ALIGN_PREFIX (8) PxParticleSpring
Holds all the information for a spring constraint between two particles. Used for particle cloth simulation.
PX_C_EXPORT PX_PHYSX_CORE_API physx::PxParticleClothPreProcessor *PX_CALL_CONV PxCreateParticleClothPreProcessor (physx::PxCudaContextManager *cudaContextManager)
Create a particle cloth preprocessor.
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxRegisterArticulationsReducedCoordinate (physx::PxPhysics &physics)
Enables the usage of the reduced coordinate articulations feature. This function is called automatically inside PxCreatePhysics(). On resource constrained platforms, it is possible to call PxCreateBasePhysics() and then NOT call this function to save on code memory if your application does not use reduced coordinate articulations. In this case the linker should strip out the relevant implementation code from the library. If you need to use reduced coordinate articulations but not some other optional component, you shoud call PxCreateBasePhysics() followed by this call.
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxRegisterHeightFields (physx::PxPhysics &physics)
Enables the usage of the heightfield feature.
PX_C_EXPORT PX_PHYSX_CORE_API physx::PxPhysics *PX_CALL_CONV PxCreateBasePhysics (physx::PxU32 version, physx::PxFoundation &foundation, const physx::PxTolerancesScale &scale, bool trackOutstandingAllocations=false, physx::PxPvd *pvd=NULL, physx::PxOmniPvd *omniPvd=NULL)
Creates an instance of the physics SDK with minimal additional components registered.
PX_INLINE physx::PxPhysics * PxCreatePhysics (physx::PxU32 version, physx::PxFoundation &foundation, const physx::PxTolerancesScale &scale, bool trackOutstandingAllocations=false, physx::PxPvd *pvd=NULL, physx::PxOmniPvd *omniPvd=NULL)
Creates an instance of the physics SDK.
PX_C_EXPORT PX_PHYSX_CORE_API physx::PxPhysics &PX_CALL_CONV PxGetPhysics ()
Retrieves the Physics SDK after it has been created.
PX_INLINE PxSceneLimits::PxSceneLimits ()
constructor sets to default
PX_INLINE void PxSceneLimits::setToDefault ()
(re)sets the structure to the default
PX_INLINE bool PxSceneLimits::isValid () const
Returns true if the descriptor is valid.
PX_PHYSX_CORE_API bool PxgDynamicsMemoryConfig::isValid () const
PX_INLINE PxSceneDesc::PxSceneDesc (const PxTolerancesScale &scale)
constructor sets to default.
PX_INLINE void PxSceneDesc::setToDefault (const PxTolerancesScale &scale)
(re)sets the structure to the default.
PX_INLINE bool PxSceneDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxSceneQueryDesc::PxSceneQueryDesc ()
constructor sets to default.
PX_INLINE void PxSceneQueryDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxSceneQueryDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE PxU32 PxContactPair::extractContacts (PxContactPairPoint *userBuffer, PxU32 bufferSize) const
Extracts the contact points from the stream and stores them in a convenient format.
PX_INLINE void PxContactPair::bufferContacts (PxContactPair *newPair, PxU8 *bufferMemory) const
Helper method to clone the contact pair and copy the contact data stream into a user buffer.
PX_INLINE const PxU32 * PxContactPair::getInternalFaceIndices () const
Variables
static const PxU32 INVALID_FILTER_PAIR_INDEX = 0xffffffff
Detailed Description
Configuration include file for PhysX SDK
Macro Definition Documentation
PX_DEF_BIN_METADATA_BASE_CLASS
#define PX_DEF_BIN_METADATA_BASE_CLASS (stream, Class, BaseClass)
Value:
{ \
        Class* myClass = reinterpret_cast<Class*>(42);                                                          \
        BaseClass* s = static_cast<BaseClass*>(myClass);                                                        \
        const PxU32 offset = PxU32(size_t(s) - size_t(myClass));                                                \
        PxMetaDataEntry tmp = { #Class, #BaseClass, offset, sizeof(Class), 0, 0, PxMetaDataFlag::eCLASS, 0 };   \
        PX_STORE_METADATA(stream, tmp);                                                                         \
    }
specifies a binary metadata entry for declaring a base class
PX_DEF_BIN_METADATA_CLASS
#define PX_DEF_BIN_METADATA_CLASS (stream, Class)
Value:
{ \
        PxMetaDataEntry tmp = { #Class, 0, 0, sizeof(Class), 0, 0, PxMetaDataFlag::eCLASS, 0 }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a class
PX_DEF_BIN_METADATA_EXTRA_ALIGN
#define PX_DEF_BIN_METADATA_EXTRA_ALIGN (stream, Class, align)
Value:
{ \
        PxMetaDataEntry tmp = { "PxU8", "Alignment", 0, 0, 0, 0, PxMetaDataFlag::eEXTRA_DATA|PxMetaDataFlag::eALIGNMENT, align}; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry declaring an extra data alignment for a class
PX_DEF_BIN_METADATA_EXTRA_ARRAY
#define PX_DEF_BIN_METADATA_EXTRA_ARRAY (stream, Class, type, dyn_count, align, flags)
Value:
{ \
        PxMetaDataEntry tmp = { #type, 0, PxU32(PX_OFFSET_OF_RT(Class, dyn_count)), PX_SIZE_OF(Class, dyn_count), align, 0, \
                            PxMetaDataFlag::eEXTRA_DATA|flags, align }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for an array of extra data
similar to PX_DEF_BIN_METADATA_EXTRA_ITEMS, but supporting no control - PxMetaDataFlag::ePTR is also not supported
PX_DEF_BIN_METADATA_EXTRA_ITEM
#define PX_DEF_BIN_METADATA_EXTRA_ITEM (stream, Class, type, control, align)
Value:
{ \
        PxMetaDataEntry tmp = { #type, 0, PxU32(PX_OFFSET_OF_RT(Class, control)), sizeof(type), 0, PxU32(PX_SIZE_OF(Class, control)), \
                            PxMetaDataFlag::eEXTRA_DATA|PxMetaDataFlag::eEXTRA_ITEM, align }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for extra data
PX_DEF_BIN_METADATA_EXTRA_ITEMS
#define PX_DEF_BIN_METADATA_EXTRA_ITEMS (stream, Class, type, control, count, flags, align)
Value:
{ \
        PxMetaDataEntry tmp = { #type, 0, PxU32(PX_OFFSET_OF_RT(Class, control)), PxU32(PX_SIZE_OF(Class, control)), \
                            PxU32(PX_OFFSET_OF_RT(Class, count)), PxU32(PX_SIZE_OF(Class, count)), \
                            PxMetaDataFlag::eEXTRA_DATA|PxMetaDataFlag::eEXTRA_ITEMS|flags, align }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for an array of extra data
PX_DEF_BIN_METADATA_EXTRA_ITEMS_MASKED_CONTROL
#define PX_DEF_BIN_METADATA_EXTRA_ITEMS_MASKED_CONTROL (stream, Class, type, control, controlMask, count, flags, align)
Value:
{ \
        PxMetaDataEntry tmp = { #type, 0, PxU32(PX_OFFSET_OF_RT(Class, control)), PxU32(PX_SIZE_OF(Class, control)), \
                            PxU32(PX_OFFSET_OF_RT(Class, count)), PxU32(PX_SIZE_OF(Class, count)), \
                            PxMetaDataFlag::eCONTROL_MASK|PxMetaDataFlag::eEXTRA_DATA|PxMetaDataFlag::eEXTRA_ITEMS|flags|(controlMask & PxMetaDataFlag::eCONTROL_MASK_RANGE) << 16, \
                            align}; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for an array of extra data additional to PX_DEF_BIN_METADATA_EXTRA_ITEMS a mask can be specified to interpret the control value
See also
PxMetaDataFlag::eCONTROL_MASK
PX_DEF_BIN_METADATA_EXTRA_NAME
#define PX_DEF_BIN_METADATA_EXTRA_NAME (stream, Class, control, align)
Value:
{ \
        PxMetaDataEntry tmp = { "char", "string", 0, 0, 0, 0, PxMetaDataFlag::eEXTRA_DATA|PxMetaDataFlag::eEXTRA_NAME, align }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for an string of extra data
PX_DEF_BIN_METADATA_ITEM
#define PX_DEF_BIN_METADATA_ITEM (stream, Class, type, name, flags)
Value:
{ \
        PxMetaDataEntry tmp = { #type, #name, PxU32(PX_OFFSET_OF_RT(Class, name)), PX_SIZE_OF(Class, name), \
                                1, 0, flags, 0}; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a member variable of a class
PX_DEF_BIN_METADATA_ITEMS
#define PX_DEF_BIN_METADATA_ITEMS (stream, Class, type, name, flags, count)
Value:
{ \
        PxMetaDataEntry tmp = { #type, #name, PxU32(PX_OFFSET_OF_RT(Class, name)), PX_SIZE_OF(Class, name), \
                            count, 0, flags, 0}; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a member array variable of a class
similar to PX_DEF_BIN_METADATA_ITEMS_AUTO but for cases with mismatch between specified type and array type
PX_DEF_BIN_METADATA_ITEMS_AUTO
#define PX_DEF_BIN_METADATA_ITEMS_AUTO (stream, Class, type, name, flags)
Value:
{ \
        PxMetaDataEntry tmp = { #type, #name, PxU32(PX_OFFSET_OF_RT(Class, name)), PX_SIZE_OF(Class, name), \
                            sizeof((reinterpret_cast<Class*>(0))->name)/sizeof(type), 0, flags, 0}; \
                            PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a member array variable of a class
similar to PX_DEF_BIN_METADATA_ITEMS but automatically detects the array length, which only works when the specified type matches the type of the array - does not support PxMetaDataFlag::ePTR
PX_DEF_BIN_METADATA_TYPEDEF
#define PX_DEF_BIN_METADATA_TYPEDEF (stream, newType, oldType)
Value:
{ \
        PxMetaDataEntry tmp = { #newType, #oldType, 0, 0, 0, 0, PxMetaDataFlag::eTYPEDEF, 0 }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a typedef
PX_DEF_BIN_METADATA_UNION
#define PX_DEF_BIN_METADATA_UNION (stream, Class, name)
Value:
{ \
        PxMetaDataEntry tmp = { #Class, 0, PxU32(PX_OFFSET_OF_RT(Class, name)), PX_SIZE_OF(Class, name), \
                            1, 0, PxMetaDataFlag::eUNION, 0 }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a union
PX_DEF_BIN_METADATA_UNION_TYPE
#define PX_DEF_BIN_METADATA_UNION_TYPE (stream, Class, type, enumValue)
Value:
{ \
        PxMetaDataEntry tmp = { #Class, #type, enumValue, 0, 0, 0, PxMetaDataFlag::eUNION, 0 }; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a particular member type of a union
PX_DEF_BIN_METADATA_VCLASS
#define PX_DEF_BIN_METADATA_VCLASS (stream, Class)
Value:
{ \
        PxMetaDataEntry tmp = { #Class, 0, 0, sizeof(Class), 0, 0, PxMetaDataFlag::eCLASS|PxMetaDataFlag::eVIRTUAL, 0}; \
        PX_STORE_METADATA(stream, tmp); \
    }
specifies a binary metadata entry for a virtual class
PX_MAX_TETID
#define PX_MAX_TETID 0x000fffff
The maximum tetrahedron index supported in the model.
PX_SIZE_OF
#define PX_SIZE_OF (Class, Member) sizeof((reinterpret_cast<Class*>(0))->Member)
PX_STORE_METADATA
#define PX_STORE_METADATA (stream, metaData) stream.write(&metaData, sizeof(PxMetaDataEntry))
PXC_CONTACT_NO_FACE_INDEX
#define PXC_CONTACT_NO_FACE_INDEX 0xffffffff
Referenced by PxContactStreamIterator::getFaceIndex0(), PxContactStreamIterator::getFaceIndex1(), PxContactSet::getInternalFaceIndex0(), and PxContactSet::getInternalFaceIndex1().
Typedef Documentation
Px1DConstraintFlags
typedef PxFlags<Px1DConstraintFlag::Type, PxU16> Px1DConstraintFlags
PxActorCacheFlags
typedef PxFlags<PxActorCacheFlag::Enum, PxU16> PxActorCacheFlags
Collection of set bits defined in PxActorCacheFlag.
See also
PxActorCacheFlag
PxActorFlags
typedef PxFlags<PxActorFlag::Enum,PxU8> PxActorFlags
collection of set bits defined in PxActorFlag.
See also
PxActorFlag
PxActorTypeFlags
typedef PxFlags<PxActorTypeFlag::Enum,PxU16> PxActorTypeFlags
Collection of set bits defined in PxActorTypeFlag.
See also
PxActorTypeFlag
PxAggregateFilterHint
typedef PxU32 PxAggregateFilterHint
PxArticulationFlags
typedef PxFlags<PxArticulationFlag::Enum, PxU8> PxArticulationFlags
PxArticulationKinematicFlags
typedef physx::PxFlags<PxArticulationKinematicFlag::Enum, PxU8> PxArticulationKinematicFlags
PxArticulationMotions
typedef PxFlags<PxArticulationMotion::Enum, PxU8> PxArticulationMotions
PxArticulationSensorFlags
typedef physx::PxFlags<PxArticulationSensorFlag::Enum, PxU8> PxArticulationSensorFlags
PxBVHStructure
typedef PX_DEPRECATED PxBVH PxBVHStructure
PxConstraintFlags
typedef PxFlags<PxConstraintFlag::Enum, PxU16> PxConstraintFlags
constraint flags
See also
PxConstraintFlag
PxConstraintProject
typedef void(* PxConstraintProject) (const void *constantBlock, PxTransform &bodyAToWorld, PxTransform &bodyBToWorld, bool projectToA)
Solver constraint projection shader.
This function is called by the constraint post-solver framework. The function must be reentrant, since it may be called simultaneously from multiple threads and should access only the arguments passed into it.
Parameters
[in] constantBlock The constant data block
[out] bodyAToWorld The center of mass frame of the first constrained body (the identity if the actor is static or a NULL pointer was provided for it)
[out] bodyBToWorld The center of mass frame of the second constrained body (the identity if the actor is static or a NULL pointer was provided for it)
[in] projectToA True if the constraint should be projected by moving the second body towards the first, false if the converse
PxConstraintSolverPrep
typedef PxU32(* PxConstraintSolverPrep) (Px1DConstraint *constraints, PxVec3p &bodyAWorldOffset, PxU32 maxConstraints, PxConstraintInvMassScale &invMassScale, const void *constantBlock, const PxTransform &bodyAToWorld, const PxTransform &bodyBToWorld, bool useExtendedLimits, PxVec3p &cAtW, PxVec3p &cBtW)
Solver constraint generation shader.
This function is called by the constraint solver framework. The function must be reentrant, since it may be called simultaneously from multiple threads, and should access only the arguments passed into it.
Developers writing custom constraints are encouraged to read the documentation in the user guide and the implementation code in PhysXExtensions.
Parameters
[out] constraints An array of solver constraint rows to be filled in
[out] bodyAWorldOffset The origin point (offset from the position vector of bodyA's center of mass) at which the constraint is resolved. This value does not affect how constraints are solved, only the constraint force reported.
[in] maxConstraints The size of the constraint buffer. At most this many constraints rows may be written
[out] invMassScale The inverse mass and inertia scales for the constraint
[in] constantBlock The constant data block
[in] bodyAToWorld The center of mass frame of the first constrained body (the identity transform if the first actor is static, or if a NULL actor pointer was provided for it)
[in] bodyBToWorld The center of mass frame of the second constrained body (the identity transform if the second actor is static, or if a NULL actor pointer was provided for it)
[in] useExtendedLimits Enables limit ranges outside of (-PI, PI)
[out] cAtW The world space location of body A's joint frame (position only)
[out] cBtW The world space location of body B's joint frame (position only)
Returns
the number of constraint rows written.
PxConstraintVisualize
typedef void(* PxConstraintVisualize) (PxConstraintVisualizer &visualizer, const void *constantBlock, const PxTransform &body0Transform, const PxTransform &body1Transform, PxU32 flags)
Solver constraint visualization function.
This function is called by the constraint post-solver framework to visualize the constraint
Parameters
[out] visualizer The render buffer to render to
[in] constantBlock The constant data block
[in] body0Transform The center of mass frame of the first constrained body (the identity if the actor is static, or a NULL pointer was provided for it)
[in] body1Transform The center of mass frame of the second constrained body (the identity if the actor is static, or a NULL pointer was provided for it)
[in] flags The visualization flags (PxConstraintVisualizationFlag)
See also
PxRenderBuffer
PxContactPairFlags
typedef PxFlags<PxContactPairFlag::Enum, PxU16> PxContactPairFlags
Bitfield that contains a set of raised flags defined in PxContactPairFlag.
See also
PxContactPairFlag
PxContactPairHeaderFlags
typedef PxFlags<PxContactPairHeaderFlag::Enum, PxU16> PxContactPairHeaderFlags
Bitfield that contains a set of raised flags defined in PxContactPairHeaderFlag.
See also
PxContactPairHeaderFlag
PxDataAccessFlags
typedef PxFlags<PxDataAccessFlag::Enum,PxU8> PxDataAccessFlags
collection of set bits defined in PxDataAccessFlag.
See also
PxDataAccessFlag
PxDeletionEventFlags
typedef PxFlags<PxDeletionEventFlag::Enum,PxU8> PxDeletionEventFlags
Collection of set bits defined in PxDeletionEventFlag.
See also
PxDeletionEventFlag
PxDominanceGroup [1/2]
typedef PxU8 PxDominanceGroup
Group index which allows to specify 1- or 2-way interaction.
PxDominanceGroup [2/2]
typedef PxU8 PxDominanceGroup
PxFilterFlags
typedef PxFlags<PxFilterFlag::Enum, PxU16> PxFilterFlags
Bitfield that contains a set of raised flags defined in PxFilterFlag.
See also
PxFilterFlag
PxFilterObjectAttributes
typedef PxU32 PxFilterObjectAttributes
Structure which gets passed into the collision filtering shader and/or callback providing additional information on objects of a collision pair.
See also
PxSimulationFilterShader PxSimulationFilterCallback getActorType() PxFilterObjectIsKinematic() PxFilterObjectIsTrigger()
PxMaterialFlags
typedef PxFlags<PxMaterialFlag::Enum,PxU16> PxMaterialFlags
collection of set bits defined in PxMaterialFlag.
See also
PxMaterialFlag
PxMPMCuttingFlags
typedef PxFlags<PxMPMCuttingFlag::Enum,PxU16> PxMPMCuttingFlags
PxPairFlags
typedef PxFlags<PxPairFlag::Enum, PxU16> PxPairFlags
Bitfield that contains a set of raised flags defined in PxPairFlag.
See also
PxPairFlag
PxParticleFlags
typedef PxFlags<PxParticleFlag::Enum, PxU32> PxParticleFlags
PxParticlePhaseFlags
typedef PxFlags<PxParticlePhaseFlag::Enum, PxU32> PxParticlePhaseFlags
PxRigidBodyFlags
typedef PxFlags<PxRigidBodyFlag::Enum,PxU16> PxRigidBodyFlags
collection of set bits defined in PxRigidBodyFlag.
See also
PxRigidBodyFlag
PxRigidDynamicLockFlags
typedef PxFlags<PxRigidDynamicLockFlag::Enum, PxU8> PxRigidDynamicLockFlags
PxSceneFlags
typedef PxFlags<PxSceneFlag::Enum,PxU32> PxSceneFlags
collection of set bits defined in PxSceneFlag.
See also
PxSceneFlag
PxShapeFlags
typedef PxFlags<PxShapeFlag::Enum,PxU8> PxShapeFlags
collection of set bits defined in PxShapeFlag.
See also
PxShapeFlag
PxSimulationFilterShader
typedef PxFilterFlags(* PxSimulationFilterShader) (PxFilterObjectAttributes attributes0, PxFilterData filterData0, PxFilterObjectAttributes attributes1, PxFilterData filterData1, PxPairFlags &pairFlags, const void *constantBlock, PxU32 constantBlockSize)
Filter method to specify how a pair of potentially colliding objects should be processed.
Collision filtering is a mechanism to specify how a pair of potentially colliding objects should be processed by the simulation. A pair of objects is potentially colliding if the bounding volumes of the two objects overlap. In short, a collision filter decides whether a collision pair should get processed, temporarily ignored or discarded. If a collision pair should get processed, the filter can additionally specify how it should get processed, for instance, whether contacts should get resolved, which callbacks should get invoked or which reports should be sent etc. The function returns the PxFilterFlag flags and sets the PxPairFlag flags to define what the simulation should do with the given collision pair.
Note
A default implementation of a filter shader is provided in the PhysX extensions library, see PxDefaultSimulationFilterShader.
This methods gets called when:
The bounding volumes of two objects start to overlap.
The bounding volumes of two objects overlap and the filter data or filter attributes of one of the objects changed
A re-filtering was forced through resetFiltering() (see PxScene::resetFiltering())
Filtering is requested in scene queries
Note
Certain pairs of objects are always ignored and this method does not get called. This is the case for the following pairs:
Pair of static rigid actors
A static rigid actor and a kinematic actor (unless one is a trigger or if explicitly enabled through PxPairFilteringMode::eKEEP)
Two kinematic actors (unless one is a trigger or if explicitly enabled through PxPairFilteringMode::eKEEP)
Two jointed rigid bodies and the joint was defined to disable collision
Two articulation links if connected through an articulation joint
Note
This is a performance critical method and should be stateless. You should neither access external objects from within this method nor should you call external methods that are not inlined. If you need a more complex logic to filter a collision pair then use the filter callback mechanism for this pair (see PxSimulationFilterCallback, PxFilterFlag::eCALLBACK, PxFilterFlag::eNOTIFY).
Parameters
[in] attributes0 The filter attribute of the first object
[in] filterData0 The custom filter data of the first object
[in] attributes1 The filter attribute of the second object
[in] filterData1 The custom filter data of the second object
[out] pairFlags Flags giving additional information on how an accepted pair should get processed
[in] constantBlock The constant global filter data (see PxSceneDesc.filterShaderData)
[in] constantBlockSize Size of the global filter data (see PxSceneDesc.filterShaderDataSize)
Returns
Filter flags defining whether the pair should be discarded, temporarily ignored, processed and whether the filter callback should get invoked for this pair.
See also
PxSimulationFilterCallback PxFilterData PxFilterObjectAttributes PxFilterFlag PxFilterFlags PxPairFlag PxPairFlags PxSceneDesc.filterShader
PxSoftBodyDataFlags
typedef PxFlags<PxSoftBodyData::Enum, PxU32> PxSoftBodyDataFlags
PxSoftBodyFlags
typedef PxFlags<PxSoftBodyFlag::Enum, PxU32> PxSoftBodyFlags
PxSQBuildStepHandle
typedef void* PxSQBuildStepHandle
PxSQCompoundHandle
typedef PxU32 PxSQCompoundHandle
PxSQPrunerHandle
typedef PxU32 PxSQPrunerHandle
PxTriggerPairFlags
typedef PxFlags<PxTriggerPairFlag::Enum, PxU8> PxTriggerPairFlags
Bitfield that contains a set of raised flags defined in PxTriggerPairFlag.
See also
PxTriggerPairFlag
Enumeration Type Documentation
PxScenePrunerIndex
enum PxScenePrunerIndex
Built-in enum for default PxScene pruners.
This is passed as a pruner index to various functions in the following APIs.
See also
PxSceneQuerySystemBase::forceRebuildDynamicTree PxSceneQuerySystem::preallocate
PxSceneQuerySystem::visualize PxSceneQuerySystem::sync PxSceneQuerySystem::prepareSceneQueryBuildStep
Enumerator
PX_SCENE_PRUNER_STATIC
PX_SCENE_PRUNER_DYNAMIC
PX_SCENE_COMPOUND_PRUNER
Function Documentation
bufferContacts()
PX_INLINE void PxContactPair::bufferContacts (PxContactPair * newPair, PxU8 * bufferMemory) const
Helper method to clone the contact pair and copy the contact data stream into a user buffer.
The contact data stream is only accessible during the contact report callback. This helper function provides copy functionality to buffer the contact stream information such that it can get accessed at a later stage.
Parameters
[out] newPair The contact pair info will get copied to this instance. The contact data stream pointer of the copy will be redirected to the provided user buffer. Use NULL to skip the contact pair copy operation.
[out] bufferMemory Memory block to store the contact data stream to. At most requiredBufferSize bytes will get written to the buffer.
References PxContactPair::contactPatches, PxContactPair::contactPoints, and PxMemCopy().
extractContacts()
PX_INLINE PxU32 PxContactPair::extractContacts (PxContactPairPoint * userBuffer, PxU32 bufferSize) const
Extracts the contact points from the stream and stores them in a convenient format.
Parameters
[out] userBuffer Array of PxContactPairPoint structures to extract the contact points to. The number of contacts for a pair is defined by contactCount
[in] bufferSize Number of PxContactPairPoint structures the provided buffer can store.
Returns
Number of contact points written to the buffer.
See also
PxContactPairPoint
References PxContactPairFlag::eINTERNAL_CONTACTS_ARE_FLIPPED, PxContactPairFlag::eINTERNAL_HAS_IMPULSES, PxContactStreamIterator::getContactNormal(), PxContactStreamIterator::getContactPoint(), PxContactStreamIterator::getFaceIndex0(), PxContactStreamIterator::getFaceIndex1(), PxContactStreamIterator::getSeparation(), PxContactStreamIterator::hasNextContact(), PxContactStreamIterator::hasNextPatch(), PxContactPairPoint::impulse, PxContactPairPoint::internalFaceIndex0, PxContactPairPoint::internalFaceIndex1, PxContactStreamIterator::nextContact(), PxContactStreamIterator::nextPatch(), PxContactPairPoint::normal, PxContactPairPoint::position, and PxContactPairPoint::separation.
getInternalFaceIndices()
PX_INLINE const PxU32 * PxContactPair::getInternalFaceIndices () const
isValid() [1/4]
PX_INLINE bool PxSceneQueryDesc::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid.
References PxSceneQueryDesc::dynamicTreeRebuildRateHint, PxPruningStructureType::eDYNAMIC_AABB_TREE, PxPruningStructureType::eSTATIC_AABB_TREE, and PxSceneQueryDesc::staticStructure.
Referenced by PxSceneDesc::isValid().
isValid() [2/4]
PX_INLINE bool PxSceneLimits::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid.
References PxSceneLimits::maxNbRegions.
Referenced by PxSceneDesc::isValid().
isValid() [3/4]
PX_INLINE bool PxgDynamicsMemoryConfig::isValid () const
References PxgDynamicsMemoryConfig::heapCapacity, and PxIsPowerOfTwo().
Referenced by PxSceneDesc::isValid().
isValid() [4/4]
PX_INLINE bool PxSceneDesc::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid.
References PxSceneDesc::bounceThresholdVelocity, PxSceneDesc::broadPhaseType, PxSceneDesc::ccdMaxPasses, PxSceneDesc::ccdMaxSeparation, PxSceneDesc::ccdThreshold, PxSceneDesc::contactPairSlabSize, PxSceneDesc::contactReportStreamBufferSize, PxSceneDesc::cpuDispatcher, PxSceneFlag::eENABLE_GPU_DYNAMICS, PxBroadPhaseType::eGPU, PxSceneFlag::eSUPPRESS_READBACK, PxSceneDesc::filterShader, PxSceneDesc::filterShaderData, PxSceneDesc::filterShaderDataSize, PxSceneDesc::flags, PxSceneDesc::frictionCorrelationDistance, PxSceneDesc::frictionOffsetThreshold, PxSceneDesc::gpuDynamicsConfig, PxSceneDesc::gpuMaxNumPartitions, PxBounds3::isValid(), PxSceneQueryDesc::isValid(), PxSceneLimits::isValid(), PxgDynamicsMemoryConfig::isValid(), PxSceneDesc::limits, PxSceneDesc::maxBiasCoefficient, PxSceneDesc::maxNbContactDataBlocks, PxSceneDesc::nbContactDataBlocks, PxIsPowerOfTwo(), PxSceneDesc::sanityBounds, and PxSceneDesc::wakeCounterResetValue.
PX_ALIGN_PREFIX()
struct PX_ALIGN_PREFIX (8)
Holds all the information for a spring constraint between two particles. Used for particle cloth simulation.
< particle index of first particle
< particle index of second particle
< spring length
< spring stiffness
< spring damping factor
< padding bytes.
PxCreateBasePhysics()
PX_C_EXPORT PX_PHYSX_CORE_API physx::PxPhysics* PX_CALL_CONV PxCreateBasePhysics (physx::PxU32 version, physx::PxFoundation & foundation, const physx::PxTolerancesScale & scale, bool trackOutstandingAllocations = false, physx::PxPvd * pvd = NULL, physx::PxOmniPvd * omniPvd = NULL)
Creates an instance of the physics SDK with minimal additional components registered.
Creates an instance of this class. May not be a class member to avoid name mangling. Pass the constant PX_PHYSICS_VERSION as the argument. There may be only one instance of this class per process. Calling this method after an instance has been created already will result in an error message and NULL will be returned.
Parameters
version Version number we are expecting(should be PX_PHYSICS_VERSION)
foundation Foundation instance (see PxFoundation)
scale values used to determine default tolerances for objects at creation time
trackOutstandingAllocations true if you want to track memory allocations so a debugger connection partway through your physics simulation will get an accurate map of everything that has been allocated so far. This could have a memory and performance impact on your simulation hence it defaults to off.
pvd When pvd points to a valid PxPvd instance (PhysX Visual Debugger), a connection to the specified PxPvd instance is created. If pvd is NULL no connection will be attempted.
omniPvd When omniPvd points to a valid PxOmniPvd instance PhysX will sample its internal structures to the defined OmniPvd output streams set in the PxOmniPvd object.
Returns
PxPhysics instance on success, NULL if operation failed
See also
PxPhysics, PxFoundation, PxTolerancesScale, PxPvd
Referenced by PxCreatePhysics().
PxCreateParticleClothPreProcessor()
PX_C_EXPORT PX_PHYSX_CORE_API physx::PxParticleClothPreProcessor* PX_CALL_CONV PxCreateParticleClothPreProcessor (physx::PxCudaContextManager * cudaContextManager)
Create a particle cloth preprocessor.
Parameters
[in] cudaContextManager A cuda context manager.
See PxParticleClothDesc, PxPartitionedParticleCloth.
PxCreatePhysics()
PX_INLINE physx::PxPhysics* PxCreatePhysics (physx::PxU32 version, physx::PxFoundation & foundation, const physx::PxTolerancesScale & scale, bool trackOutstandingAllocations = false, physx::PxPvd * pvd = NULL, physx::PxOmniPvd * omniPvd = NULL)
Creates an instance of the physics SDK.
Creates an instance of this class. May not be a class member to avoid name mangling. Pass the constant PX_PHYSICS_VERSION as the argument. There may be only one instance of this class per process. Calling this method after an instance has been created already will result in an error message and NULL will be returned.
Calling this will register all optional code modules (Articulations and HeightFields), preparing them for use. If you do not need some of these modules, consider calling PxCreateBasePhysics() instead and registering needed modules manually.
Parameters
version Version number we are expecting(should be PX_PHYSICS_VERSION)
foundation Foundation instance (see PxFoundation)
scale values used to determine default tolerances for objects at creation time
trackOutstandingAllocations true if you want to track memory allocations so a debugger connection partway through your physics simulation will get an accurate map of everything that has been allocated so far. This could have a memory and performance impact on your simulation hence it defaults to off.
pvd When pvd points to a valid PxPvd instance (PhysX Visual Debugger), a connection to the specified PxPvd instance is created. If pvd is NULL no connection will be attempted.
omniPvd When omniPvd points to a valid PxOmniPvd instance PhysX will sample its internal structures to the defined OmniPvd output streams set in the PxOmniPvd object.
Returns
PxPhysics instance on success, NULL if operation failed
See also
PxPhysics, PxCreateBasePhysics, PxRegisterArticulationsReducedCoordinate, PxRegisterHeightFields
References PxCreateBasePhysics(), PxRegisterArticulationsReducedCoordinate(), and PxRegisterHeightFields().
PxFilterObjectIsKinematic()
PX_INLINE bool PxFilterObjectIsKinematic (PxFilterObjectAttributes attr)
Specifies whether the collision object belongs to a kinematic rigid body.
Parameters
[in] attr The filter attribute of a collision pair object
Returns
True if the object belongs to a kinematic rigid body, else false
See also
PxRigidBodyFlag::eKINEMATIC
References PxFilterObjectFlag::eKINEMATIC.
PxFilterObjectIsTrigger()
PX_INLINE bool PxFilterObjectIsTrigger (PxFilterObjectAttributes attr)
Specifies whether the collision object is a trigger shape.
Parameters
[in] attr The filter attribute of a collision pair object
Returns
True if the object is a trigger shape, else false
See also
PxShapeFlag::eTRIGGER_SHAPE
References PxFilterObjectFlag::eTRIGGER.
PxGetAggregateFilterHint()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxAggregateFilterHint PxGetAggregateFilterHint (PxAggregateType::Enum type, bool enableSelfCollision)
PxGetAggregateSelfCollisionBit()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU32 PxGetAggregateSelfCollisionBit (PxAggregateFilterHint hint)
PxGetAggregateType()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxAggregateType::Enum PxGetAggregateType (PxAggregateFilterHint hint)
PxGetFilterObjectType()
PX_INLINE PxFilterObjectType::Enum PxGetFilterObjectType (PxFilterObjectAttributes attr)
Extract filter object type from the filter attributes of a collision pair object.
Parameters
[in] attr The filter attribute of a collision pair object
Returns
The type of the collision pair object.
See also
PxFilterObjectType
References PxFilterObjectType::eMAX_TYPE_COUNT.
PxGetPhysics()
PX_C_EXPORT PX_PHYSX_CORE_API physx::PxPhysics& PX_CALL_CONV PxGetPhysics ()
Retrieves the Physics SDK after it has been created.
Before using this function the user must call PxCreatePhysics().
Note
The behavior of this method is undefined if the Physics SDK instance has not been created already.
Referenced by PxRigidActorExt::createExclusiveShape().
PxRegisterArticulationsReducedCoordinate()
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxRegisterArticulationsReducedCoordinate (physx::PxPhysics & physics)
Enables the usage of the reduced coordinate articulations feature. This function is called automatically inside PxCreatePhysics(). On resource constrained platforms, it is possible to call PxCreateBasePhysics() and then NOT call this function to save on code memory if your application does not use reduced coordinate articulations. In this case the linker should strip out the relevant implementation code from the library. If you need to use reduced coordinate articulations but not some other optional component, you shoud call PxCreateBasePhysics() followed by this call.
Referenced by PxCreatePhysics().
PxRegisterHeightFields()
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxRegisterHeightFields (physx::PxPhysics & physics)
Enables the usage of the heightfield feature.
This call will link the default 'unified' implementation of heightfields which is identical to the narrow phase of triangle meshes. This function is called automatically inside PxCreatePhysics().
On resource constrained platforms, it is possible to call PxCreateBasePhysics() and then NOT call this function to save on code memory if your application does not use heightfields. In this case the linker should strip out the relevant implementation code from the library. If you need to use heightfield but not some other optional component, you shoud call PxCreateBasePhysics() followed by this call.
You must call this function at a time where no PxScene instance exists, typically before calling PxPhysics::createScene(). This is to prevent a change to the heightfield implementation code at runtime which would have undefined results.
Calling PxCreateBasePhysics() and then attempting to create a heightfield shape without first calling PxRegisterHeightFields(), will result in an error.
Referenced by PxCreatePhysics().
PxSceneDesc()
PX_INLINE PxSceneDesc::PxSceneDesc (const PxTolerancesScale & scale)
constructor sets to default.
Parameters
[in] scale scale values for the tolerances in the scene, these must be the same values passed into PxCreatePhysics(). The affected tolerances are bounceThresholdVelocity and frictionOffsetThreshold.
See also
PxCreatePhysics() PxTolerancesScale bounceThresholdVelocity frictionOffsetThreshold
Referenced by PxSceneDesc::setToDefault().
PxSceneLimits()
PX_INLINE PxSceneLimits::PxSceneLimits ()
constructor sets to default
Referenced by PxSceneLimits::setToDefault().
PxSceneQueryDesc()
PX_INLINE PxSceneQueryDesc::PxSceneQueryDesc ()
constructor sets to default.
Referenced by PxSceneQueryDesc::setToDefault().
setToDefault() [1/3]
PX_INLINE void PxSceneQueryDesc::setToDefault ()
(re)sets the structure to the default.
References PxSceneQueryDesc::PxSceneQueryDesc().
setToDefault() [2/3]
PX_INLINE void PxSceneLimits::setToDefault ()
(re)sets the structure to the default
References PxSceneLimits::PxSceneLimits().
setToDefault() [3/3]
PX_INLINE void PxSceneDesc::setToDefault (const PxTolerancesScale & scale)
(re)sets the structure to the default.
Parameters
[in] scale scale values for the tolerances in the scene, these must be the same values passed into PxCreatePhysics(). The affected tolerances are bounceThresholdVelocity and frictionOffsetThreshold.
See also
PxCreatePhysics() PxTolerancesScale bounceThresholdVelocity frictionOffsetThreshold
References PxSceneDesc::PxSceneDesc().
Variable Documentation
INVALID_FILTER_PAIR_INDEX
const PxU32 INVALID_FILTER_PAIR_INDEX = 0xffffffff static