Common
Common
Classes
struct PxBaseFlag
Flags for PxBase.
class PxBase
Base class for objects that can be members of a PxCollection.
class PxRefCounted
Base class for ref-counted objects.
class PxCollection
Collection class for serialization.
struct PxStridedData
struct PxTypedStridedData< TDataType >
struct PxBoundedData
struct PxPadding< TNumBytes >
class PxFixedSizeLookupTable< NB_ELEMENTS >
class PxInsertionCallback
Callback interface that permits TriangleMesh, Heightfield, ConvexMesh or BVH to be used directly without the need to store the cooking results into a stream.
struct PxDebugColor
Default color values used for debug rendering.
struct PxDebugPoint
Used to store a single point and colour for debug rendering.
struct PxDebugLine
Used to store a single line and colour for debug rendering.
struct PxDebugTriangle
Used to store a single triangle and colour for debug rendering.
struct PxDebugText
Used to store a text for debug rendering. Doesn't own 'string' array.
class PxRenderBuffer
Interface for points, lines, triangles, and text buffer.
class PxProcessPxBaseCallback
Callback class used to process PxBase objects.
class PxSerializationContext
Binary serialization context class.
class PxDeserializationContext
Binary deserialization context class.
class PxSerializationRegistry
Class serving as a registry for XML (RepX) and binary serializable types.
class PxTolerancesScale
Class to define the scale at which simulation runs. Most simulation tolerances are calculated in terms of the values here.
struct PxConcreteType
an enumeration of concrete classes inheriting from PxBase
struct PxTypeInfo< T >
a structure containing per-type information for types inheriting from PxBase
class PxInputStream
Input stream class for I/O.
class PxInputData
Input data class for I/O which provides random read access.
class PxOutputStream
Output stream class for I/O.
struct Interpolation
Macros
#define PX_PHYSX_CORE_API
#define PX_PHYSX_GPU_API
#define PX_PHYSX_COMMON_API
#define PX_INVALID_U32 0xffffffff
#define PX_INVALID_U16 0xffff
#define PX_ENABLE_DEBUG_VISUALIZATION 1
#define PX_CATCH_UNDEFINED_ENABLE_DEBUG_VISUALIZATION
#define PX_ENABLE_SIM_STATS 1
#define PX_CATCH_UNDEFINED_ENABLE_SIM_STATS
#define PX_SERIAL_ALIGN 16
Default serialization alignment.
#define PX_SERIAL_FILE_ALIGN 128
Serialized input data must be aligned to this value.
#define PX_SERIAL_OBJECT_ID_INVALID 0
PxSerialObjectId value for objects that do not have an ID.
#define PX_SERIAL_REF_KIND_PTR_TYPE_BIT (1u<<31)
Bit to mark pointer type references,.
#define PX_SERIAL_REF_KIND_PXBASE (0 | PX_SERIAL_REF_KIND_PTR_TYPE_BIT)
Reference kind value for PxBase objects.
#define PX_SERIAL_REF_KIND_MATERIAL_IDX (1)
Reference kind value for material indices.
#define PX_MAKE_FOURCC(a, b, c, d) ((a) | ((b)<<8) | ((c)<<16) | ((d)<<24))
Used to fix multi-byte characters warning from gcc for situations like: PxU32 foo = 'CCTS';.
#define PX_DEFINE_TYPEINFO(_name, _fastType)
Typedefs
typedef PxU16 PxType
typedef PxFlags< PxBaseFlag::Enum, PxU16 > PxBaseFlags
typedef PxInsertionCallback PxPhysicsInsertionCallback
typedef PxU32 PxTriangleID
typedef PxU16 PxMaterialTableIndex
typedef PxU16 PxFEMMaterialTableIndex
typedef PxU16 PxType
typedef PxU64 PxSerialObjectId
ID type for PxBase objects in a PxCollection.
typedef void(* PxBinaryMetaDataCallback) (PxOutputStream &stream)
Callback type for exporting binary meta data for a serializable type.
Functions
PX_C_EXPORT PX_PHYSX_COMMON_API physx::PxCollection *PX_CALL_CONV PxCreateCollection ()
Creates a collection object.
PX_FOUNDATION_API PxQuat PxShortestRotation (const PxVec3 &from, const PxVec3 &target)
finds the shortest rotation between two vectors.
PX_FOUNDATION_API PxVec3 PxDiagonalize (const PxMat33 &m, PxQuat &axes)
PX_FOUNDATION_API PxTransform PxTransformFromSegment (const PxVec3 &p0, const PxVec3 &p1, PxReal *halfHeight=NULL)
creates a transform from the endpoints of a segment, suitable for an actor transform for a PxCapsuleGeometry
PX_FOUNDATION_API PxTransform PxTransformFromPlaneEquation (const PxPlane &plane)
creates a transform from a plane equation, suitable for an actor transform for a PxPlaneGeometry
PX_INLINE PxPlane PxPlaneEquationFromTransform (const PxTransform &pose)
creates a plane equation from a transform, such as the actor transform for a PxPlaneGeometry
PX_FOUNDATION_API PxQuat PxSlerp (const PxReal t, const PxQuat &left, const PxQuat &right)
Spherical linear interpolation of two quaternions.
PX_FOUNDATION_API void PxIntegrateTransform (const PxTransform &curTrans, const PxVec3 &linvel, const PxVec3 &angvel, PxReal timeStep, PxTransform &result)
integrate transform.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuat PxExp (const PxVec3 &v)
Compute the exponent of a PxVec3.
PX_FOUNDATION_API PxVec3 PxOptimizeBoundingBox (PxMat33 &basis)
computes a oriented bounding box around the scaled basis.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxLog (const PxQuat &q)
return Returns the log of a PxQuat
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU32 PxLargestAxis (const PxVec3 &v)
return Returns 0 if v.x is largest element of v, 1 if v.y is largest element, 2 if v.z is largest element.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxReal PxTanHalf (PxReal sin, PxReal cos)
Compute tan(theta/2) given sin(theta) and cos(theta) as inputs.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxEllipseClamp (const PxVec3 &point, const PxVec3 &radii)
Compute the closest point on an 2d ellipse to a given 2d point.
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxSeparateSwingTwist (const PxQuat &q, PxQuat &swing, PxQuat &twist)
Compute from an input quaternion q a pair of quaternions (swing, twist) such that q = swing * twist with the caveats that swing.x = twist.y = twist.z = 0.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxF32 PxComputeAngle (const PxVec3 &v0, const PxVec3 &v1)
Compute the angle between two non-unit vectors.
PX_INLINE void PxComputeBasisVectors (const PxVec3 &dir, PxVec3 &right, PxVec3 &up)
Compute two normalized vectors (right and up) that are perpendicular to an input normalized vector (dir).
PX_INLINE void PxComputeBasisVectors (const PxVec3 &p0, const PxVec3 &p1, PxVec3 &dir, PxVec3 &right, PxVec3 &up)
Compute three normalized vectors (dir, right and up) that are parallel to (dir) and perpendicular to (right, up) the normalized direction vector (p1 - p0)/||p1 - p0||.
PX_INLINE PxU32 PxGetNextIndex3 (PxU32 i)
Compute (i+1)%3.
PX_INLINE PX_CUDA_CALLABLE void computeBarycentric (const PxVec3 &a, const PxVec3 &b, const PxVec3 &c, const PxVec3 &d, const PxVec3 &p, PxVec4 &bary)
PX_INLINE PX_CUDA_CALLABLE void computeBarycentric (const PxVec3 &a, const PxVec3 &b, const PxVec3 &c, const PxVec3 &p, PxVec4 &bary)
PX_INLINE PX_CUDA_CALLABLE PxReal PxSdfSample (const PxReal *PX_RESTRICT sdf, const PxVec3 &localPos, const PxVec3 &sdfBoxLower, const PxVec3 &sdfBoxHigher, const PxReal sdfDx, const PxReal invSdfDx, const PxU32 dimX, const PxU32 dimY, const PxU32 dimZ, PxVec3 &gradient, PxReal tolerance=PX_MAX_F32)
PX_INLINE PxTolerancesScale::PxTolerancesScale (float defaultLength=1.0f, float defaultSpeed=10.0f)
constructor sets to default
PX_INLINE bool PxTolerancesScale::isValid () const
Returns true if the descriptor is valid.
Detailed Description
Macro Definition Documentation
PX_CATCH_UNDEFINED_ENABLE_DEBUG_VISUALIZATION
#define PX_CATCH_UNDEFINED_ENABLE_DEBUG_VISUALIZATION
PX_CATCH_UNDEFINED_ENABLE_SIM_STATS
#define PX_CATCH_UNDEFINED_ENABLE_SIM_STATS
PX_DEFINE_TYPEINFO
#define PX_DEFINE_TYPEINFO (_name, _fastType)
Value:
class _name; \
    template <> struct PxTypeInfo<_name>    {   static const char* name() { return #_name;  }   enum { eFastTypeId = _fastType };   };
PX_ENABLE_DEBUG_VISUALIZATION
#define PX_ENABLE_DEBUG_VISUALIZATION 1
PX_ENABLE_SIM_STATS
#define PX_ENABLE_SIM_STATS 1
PX_INVALID_U16
#define PX_INVALID_U16 0xffff
PX_INVALID_U32
#define PX_INVALID_U32 0xffffffff
PX_MAKE_FOURCC
#define PX_MAKE_FOURCC (a, b, c, d) ((a) | ((b)<<8) | ((c)<<16) | ((d)<<24))
Used to fix multi-byte characters warning from gcc for situations like: PxU32 foo = 'CCTS';.
PX_PHYSX_COMMON_API
#define PX_PHYSX_COMMON_API
PX_PHYSX_CORE_API
#define PX_PHYSX_CORE_API
PX_PHYSX_GPU_API
#define PX_PHYSX_GPU_API
PX_SERIAL_ALIGN
#define PX_SERIAL_ALIGN 16
Default serialization alignment.
PX_SERIAL_FILE_ALIGN
#define PX_SERIAL_FILE_ALIGN 128
Serialized input data must be aligned to this value.
PX_SERIAL_OBJECT_ID_INVALID
#define PX_SERIAL_OBJECT_ID_INVALID 0
PxSerialObjectId value for objects that do not have an ID.
PX_SERIAL_REF_KIND_MATERIAL_IDX
#define PX_SERIAL_REF_KIND_MATERIAL_IDX (1)
Reference kind value for material indices.
PX_SERIAL_REF_KIND_PTR_TYPE_BIT
#define PX_SERIAL_REF_KIND_PTR_TYPE_BIT (1u<<31)
Bit to mark pointer type references,.
See also
PxDeserializationContext
PX_SERIAL_REF_KIND_PXBASE
#define PX_SERIAL_REF_KIND_PXBASE (0 | PX_SERIAL_REF_KIND_PTR_TYPE_BIT)
Reference kind value for PxBase objects.
Referenced by PxSerializerDefaultAdapter< T >::registerReferences(), and PxDeserializationContext::translatePxBase().
Typedef Documentation
PxBaseFlags
typedef PxFlags<PxBaseFlag::Enum, PxU16> PxBaseFlags
PxBinaryMetaDataCallback
typedef void(* PxBinaryMetaDataCallback) (PxOutputStream &stream)
Callback type for exporting binary meta data for a serializable type.
See also
PxSerializationRegistry::registerBinaryMetaDataCallback
Parameters
stream Stream to store binary meta data.
PxFEMMaterialTableIndex
typedef PxU16 PxFEMMaterialTableIndex
PxMaterialTableIndex
typedef PxU16 PxMaterialTableIndex
PxPhysicsInsertionCallback
typedef PxInsertionCallback PxPhysicsInsertionCallback
PxSerialObjectId
typedef PxU64 PxSerialObjectId
ID type for PxBase objects in a PxCollection.
PxTriangleID
typedef PxU32 PxTriangleID
PxType [1/2]
typedef PxU16 PxType
PxType [2/2]
typedef PxU16 PxType
Function Documentation
computeBarycentric() [1/2]
PX_INLINE PX_CUDA_CALLABLE void computeBarycentric (const PxVec3 & a, const PxVec3 & b, const PxVec3 & c, const PxVec3 & d, const PxVec3 & p, PxVec4 & bary)
References PxVec3T< Type >::cross(), PxVec3T< Type >::dot(), PxVec4T< Type >::w, PxVec4T< Type >::x, PxVec4T< Type >::y, and PxVec4T< Type >::z.
computeBarycentric() [2/2]
PX_INLINE PX_CUDA_CALLABLE void computeBarycentric (const PxVec3 & a, const PxVec3 & b, const PxVec3 & c, const PxVec3 & p, PxVec4 & bary)
References PxVec3T< Type >::dot(), PxVec4T< Type >::w, PxVec4T< Type >::x, PxVec4T< Type >::y, and PxVec4T< Type >::z.
isValid()
PX_INLINE bool PxTolerancesScale::isValid () const
Returns true if the descriptor is valid.
Returns
true if the current settings are valid (returns always true).
References PxTolerancesScale::length.
PxComputeAngle()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxF32 PxComputeAngle (const PxVec3 & v0, const PxVec3 & v1)
Compute the angle between two non-unit vectors.
Parameters
[in] v0 is one of the non-unit vectors
[in] v1 is the other of the two non-unit vectors
Returns
Returns the angle (in radians) between the two vector v0 and v1.
References cos(), PxVec3T< Type >::cross(), PxVec3T< Type >::dot(), PxAtan2(), and sin().
PxComputeBasisVectors() [1/2]
PX_INLINE void PxComputeBasisVectors (const PxVec3 & dir, PxVec3 & right, PxVec3 & up)
Compute two normalized vectors (right and up) that are perpendicular to an input normalized vector (dir).
Parameters
[in] dir is a normalized vector that is used to compute the perpendicular vectors.
[out] right is the first of the two vectors perpendicular to dir
[out] up is the second of the two vectors perpendicular to dir
References PxVec3T< Type >::normalize(), PxAbs(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by PxComputeBasisVectors().
PxComputeBasisVectors() [2/2]
PX_INLINE void PxComputeBasisVectors (const PxVec3 & p0, const PxVec3 & p1, PxVec3 & dir, PxVec3 & right, PxVec3 & up)
Compute three normalized vectors (dir, right and up) that are parallel to (dir) and perpendicular to (right, up) the normalized direction vector (p1 - p0)/||p1 - p0||.
Parameters
[in] p0 is used to compute the normalized vector dir = (p1 - p0)/||p1 - p0||.
[in] p1 is used to compute the normalized vector dir = (p1 - p0)/||p1 - p0||.
[out] dir is the normalized vector (p1 - p0)/||p1 - p0||.
[out] right is the first of the two normalized vectors perpendicular to dir
[out] up is the second of the two normalized vectors perpendicular to dir
References PxVec3T< Type >::normalize(), and PxComputeBasisVectors().
PxCreateCollection()
PX_C_EXPORT PX_PHYSX_COMMON_API physx::PxCollection* PX_CALL_CONV PxCreateCollection ()
Creates a collection object.
Objects can only be serialized or deserialized through a collection. For serialization, users must add objects to the collection and serialize the collection as a whole. For deserialization, the system gives back a collection of deserialized objects to users.
Returns
The new collection object.
See also
PxCollection, PxCollection::release()
PxDiagonalize()
PX_FOUNDATION_API PxVec3 PxDiagonalize (const PxMat33 & m, PxQuat & axes)
Referenced by PxMassProperties::getMassSpaceInertia().
PxEllipseClamp()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxEllipseClamp (const PxVec3 & point, const PxVec3 & radii)
Compute the closest point on an 2d ellipse to a given 2d point.
Parameters
[in] point is a 2d point in the y-z plane represented by (point.y, point.z)
[in] radii are the radii of the ellipse (radii.y and radii.z) in the y-z plane.
Returns
Returns the 2d position on the surface of the ellipse that is closest to point.
References PxVec3T< Type >::dot(), PxVec3T< Type >::multiply(), PxAbs(), PxMax(), PxRecipSqrt(), PxSqr(), PxVec3T< Type >::y, and PxVec3T< Type >::z.
PxExp()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxQuat PxExp (const PxVec3 & v)
Compute the exponent of a PxVec3.
References PxVec3T< Type >::magnitudeSquared(), PxIdentity, PxRecipSqrt(), and PxSqrt().
PxGetNextIndex3()
PX_INLINE PxU32 PxGetNextIndex3 (PxU32 i)
Compute (i+1)%3.
PxIntegrateTransform()
PX_FOUNDATION_API void PxIntegrateTransform (const PxTransform & curTrans, const PxVec3 & linvel, const PxVec3 & angvel, PxReal timeStep, PxTransform & result)
integrate transform.
Parameters
[in] curTrans The current transform
[in] linvel Linear velocity
[in] angvel Angular velocity
[in] timeStep The time-step for integration
[out] result The integrated transform
PxLargestAxis()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU32 PxLargestAxis (const PxVec3 & v)
return Returns 0 if v.x is largest element of v, 1 if v.y is largest element, 2 if v.z is largest element.
References PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
PxLog()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxLog (const PxQuat & q)
return Returns the log of a PxQuat
References PxQuatT< Type >::getImaginaryPart(), PxVec3T< Type >::getNormalized(), PxVec3T< Type >::magnitude(), PX_ASSERT, PxAtan2(), PxPi, and PxQuatT< Type >::w.
PxOptimizeBoundingBox()
PX_FOUNDATION_API PxVec3 PxOptimizeBoundingBox (PxMat33 & basis)
computes a oriented bounding box around the scaled basis.
Parameters
basis Input = skewed basis, Output = (normalized) orthogonal basis.
Returns
Bounding box extent.
PxPlaneEquationFromTransform()
PX_INLINE PxPlane PxPlaneEquationFromTransform (const PxTransform & pose)
creates a plane equation from a transform, such as the actor transform for a PxPlaneGeometry
Parameters
[in] pose the transform
Returns
the plane
References PxPlane::transform().
PxSdfSample()
PX_INLINE PX_CUDA_CALLABLE PxReal PxSdfSample (const PxReal *PX_RESTRICT sdf, const PxVec3 & localPos, const PxVec3 & sdfBoxLower, const PxVec3 & sdfBoxHigher, const PxReal sdfDx, const PxReal invSdfDx, const PxU32 dimX, const PxU32 dimY, const PxU32 dimZ, PxVec3 & gradient, PxReal tolerance = PX_MAX_F32)
References Interpolation::PxSDFSampleImpl(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
PxSeparateSwingTwist()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxSeparateSwingTwist (const PxQuat & q, PxQuat & swing, PxQuat & twist)
Compute from an input quaternion q a pair of quaternions (swing, twist) such that q = swing * twist with the caveats that swing.x = twist.y = twist.z = 0.
Parameters
[in] q is the quaternion to be decomposed into swing and twist quaternions.
[out] swing is the swing component of the quaternion decomposition.
[out] twist is the twist component of the quaternion decomposition.
References PxQuatT< Type >::getConjugate(), PxQuatT< Type >::getNormalized(), PxIdentity, PxQuatT< Type >::w, and PxQuatT< Type >::x.
PxShortestRotation()
PX_FOUNDATION_API PxQuat PxShortestRotation (const PxVec3 & from, const PxVec3 & target)
finds the shortest rotation between two vectors.
Parameters
[in] from the vector to start from
[in] target the vector to rotate to
Returns
a rotation about an axis normal to the two vectors which takes one to the other via the shortest path
PxSlerp()
PX_FOUNDATION_API PxQuat PxSlerp (const PxReal t, const PxQuat & left, const PxQuat & right)
Spherical linear interpolation of two quaternions.
Parameters
[in] t is the interpolation parameter in range (0, 1)
[in] left is the start of the interpolation
[in] right is the end of the interpolation
Returns
Returns left when t=0, right when t=1 and a linear interpolation of left and right when 0 < t < 1. Returns angle between -PI and PI in radians
PxTanHalf()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxReal PxTanHalf (PxReal sin, PxReal cos)
Compute tan(theta/2) given sin(theta) and cos(theta) as inputs.
Parameters
[in] sin has value sin(theta)
[in] cos has value cos(theta)
Returns
Returns tan(theta/2)
References cos(), and sin().
PxTolerancesScale()
PX_INLINE PxTolerancesScale::PxTolerancesScale (float defaultLength = 1.0f, float defaultSpeed = 10.0f)
constructor sets to default
Parameters
[in] defaultLength Default length
[in] defaultSpeed Default speed
PxTransformFromPlaneEquation()
PX_FOUNDATION_API PxTransform PxTransformFromPlaneEquation (const PxPlane & plane)
creates a transform from a plane equation, suitable for an actor transform for a PxPlaneGeometry
Parameters
[in] plane the desired plane equation
Returns
a PxTransform which will transform the plane PxPlane(1,0,0,0) to the specified plane
PxTransformFromSegment()
PX_FOUNDATION_API PxTransform PxTransformFromSegment (const PxVec3 & p0, const PxVec3 & p1, PxReal * halfHeight = NULL)
creates a transform from the endpoints of a segment, suitable for an actor transform for a PxCapsuleGeometry
Parameters
[in] p0 one end of major axis of the capsule
[in] p1 the other end of the axis of the capsule
[out] halfHeight the halfHeight of the capsule. This parameter is optional.
Returns
A PxTransform which will transform the vector (1,0,0) to the capsule axis shrunk by the halfHeight