Geomutils
Geomutils
Namespaces
Gu
Classes
class PxBoxGeometry
Class representing the geometry of a box.
class PxBVH
Class representing a bounding volume hierarchy.
struct PxBVHBuildStrategy
Desired build strategy for bounding-volume hierarchies.
class PxCapsuleGeometry
Class representing the geometry of a capsule.
struct PxHullPolygon
Polygon data.
class PxConvexMesh
A convex mesh.
struct PxConvexMeshGeometryFlag
Flags controlling the simulated behavior of the convex mesh geometry.
class PxConvexMeshGeometry
Convex mesh geometry class.
class PxCustomGeometry
Custom geometry class. This class allows user to create custom geometries by providing a set of virtual callback functions.
struct PxGeometryType
A geometry type.
class PxGeometry
A geometry object.
class PxGeometryHolder
Geometry holder class.
struct PxTriangleMeshInternalData
struct PxBVHInternalData
class PxGeometryQuery
Collection of geometry object queries (sweeps, raycasts, overlaps, ...).
class PxHairSystemGeometry
Hair system geometry class.
class PxHeightField
A height field class.
class PxHeightFieldDesc
Descriptor class for PxHeightField.
struct PxHeightFieldFormat
Describes the format of height field samples.
struct PxHeightFieldTessFlag
Determines the tessellation of height field cells.
struct PxHeightFieldFlag
Enum with flag values to be used in PxHeightFieldDesc.flags.
class PxHeightFieldGeometry
Height field geometry class.
struct PxHeightFieldMaterial
Special material index values for height field samples.
struct PxHeightFieldSample
Heightfield sample format.
struct PxMeshMeshQueryFlag
class PxMeshQuery
class PxMeshScale
A class expressing a nonuniform scaling transformation.
class PxParticleSystemGeometry
Particle system geometry class.
class PxPlaneGeometry
Class describing a plane geometry.
class PxReportCallback< T >
Base class for callback reporting an unknown number of items to users.
class PxRegularReportCallback< T >
Regular report callback.
class PxLocalStorageReportCallback< T, capacityT >
Local storage report callback.
class PxExternalStorageReportCallback< T >
External storage report callback.
class PxDynamicArrayReportCallback< T >
Dynamic array report callback.
struct PxMeshFlag
Enum with flag values to be used in PxSimpleTriangleMesh::flags.
class PxSimpleTriangleMesh
A structure describing a triangle mesh.
class PxSphereGeometry
A class representing the geometry of a sphere.
class PxTetrahedron
Tetrahedron class.
struct PxTetrahedronMeshFlag
class PxSoftBodyAuxData
A data container providing mass, rest pose and other information required for softbody simulation.
class PxTetrahedronMesh
A tetramedron mesh, also called a 'tetrahedron soup'.
class PxSoftBodyMesh
A softbody mesh, containing structures to store collision shape, simulation shape and deformation state.
class PxCollisionMeshMappingData
Contains information about how to update the collision mesh's vertices given a deformed simulation tetmesh.
class PxSoftBodyCollisionData
Stores data to accelerate collision detection of a tetrahedral mesh.
class PxTetrahedronMeshData
Contains raw geometry information describing the tetmesh's vertices and its elements (tetrahedra)
class PxSoftBodySimulationData
Stores data to compute and store the state of a deformed tetrahedral mesh.
class PxCollisionTetrahedronMeshData
Conbines PxTetrahedronMeshData and PxSoftBodyCollisionData.
class PxSimulationTetrahedronMeshData
Conbines PxTetrahedronMeshData and PxSoftBodyCollisionData.
class PxTetrahedronMeshGeometry
Tetrahedron mesh geometry class.
class PxTriangle
Triangle class.
class PxTrianglePadded
A padded version of PxTriangle, to safely load its data using SIMD.
struct PxMeshMidPhase
Mesh midphase structure. This enum is used to select the desired acceleration structure for midphase queries (i.e. raycasts, overlaps, sweeps vs triangle meshes).
struct PxTriangleMeshFlag
Flags for the mesh geometry properties.
class PxTriangleMesh
A triangle mesh, also called a 'polygon soup'.
class PxBVH33TriangleMesh
A triangle mesh containing the PxMeshMidPhase::eBVH33 structure.
class PxBVH34TriangleMesh
A triangle mesh containing the PxMeshMidPhase::eBVH34 structure.
struct PxMeshGeometryFlag
Flags controlling the simulated behavior of the triangle mesh geometry.
class PxTriangleMeshGeometry
Triangle mesh geometry class.
Macros
#define DECLARE_CUSTOM_GEOMETRY_TYPE
Used in pair with IMPLEMENT_CUSTOM_GEOMETRY_TYPE to overwrite Callbacks::getCustomType() callback.
#define IMPLEMENT_CUSTOM_GEOMETRY_TYPE(CLASS)
Used in pair with DECLARE_CUSTOM_GEOMETRY_TYPE to overwrite Callbacks::getCustomType() callback.
#define PX_MIN_HEIGHTFIELD_XZ_SCALE 1e-8f
#define PX_MIN_HEIGHTFIELD_Y_SCALE (0.0001f / PxReal(0xFFFF))
#define PX_MESH_SCALE_MIN 1e-6f
Minimum allowed absolute magnitude for each of mesh scale's components (x,y,z).
#define PX_MESH_SCALE_MAX 1e6f
Maximum allowed absolute magnitude for each of mesh scale's components (x,y,z).
Typedefs
typedef PX_DEPRECATED PxBVH PxBVHStructure
typedef PxFlags< PxConvexMeshGeometryFlag::Enum, PxU8 > PxConvexMeshGeometryFlags
collection of set bits defined in PxConvexMeshGeometryFlag.
typedef PxFlags< PxHeightFieldFlag::Enum, PxU16 > PxHeightFieldFlags
collection of set bits defined in PxHeightFieldFlag.
typedef PxFlags< PxMeshFlag::Enum, PxU16 > PxMeshFlags
collection of set bits defined in PxMeshFlag.
typedef PxFlags< PxTetrahedronMeshFlag::Enum, PxU8 > PxTetrahedronMeshFlags
collection of set bits defined in PxTetrahedronMeshFlag.
typedef PxFlags< PxTriangleMeshFlag::Enum, PxU8 > PxTriangleMeshFlags
collection of set bits defined in PxTriangleMeshFlag.
typedef PxFlags< PxMeshGeometryFlag::Enum, PxU8 > PxMeshGeometryFlags
collection of set bits defined in PxMeshGeometryFlag.
Functions
PX_C_EXPORT PX_PHYSX_COMMON_API bool PX_CALL_CONV PxFindOverlap (PxReportCallback< PxGeomIndexPair > &callback, const PxBVH &bvh0, const PxBVH &bvh1)
BVH-vs-BVH overlap test.
PX_C_EXPORT PX_PHYSX_COMMON_API bool PX_CALL_CONV PxGetTriangleMeshInternalData (PxTriangleMeshInternalData &data, const PxTriangleMesh &mesh, bool takeOwnership)
PX_C_EXPORT PX_PHYSX_COMMON_API bool PX_CALL_CONV PxGetBVHInternalData (PxBVHInternalData &data, const PxBVH &bvh, bool takeOwnership)
PX_INLINE bool PxBoxGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE bool PxCapsuleGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE bool PxConvexMeshGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE bool PxCustomGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE PxHeightFieldDesc::PxHeightFieldDesc ()
Constructor sets to default.
PX_INLINE void PxHeightFieldDesc::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxHeightFieldDesc::isValid () const
Returns true if the descriptor is valid.
PX_INLINE bool PxHeightFieldGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE bool PxPlaneGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE PxSimpleTriangleMesh::PxSimpleTriangleMesh ()
constructor sets to default.
PX_INLINE void PxSimpleTriangleMesh::setToDefault ()
(re)sets the structure to the default.
PX_INLINE bool PxSimpleTriangleMesh::isValid () const
returns true if the current settings are valid
PX_INLINE bool PxSphereGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE bool PxTetrahedronMeshGeometry::isValid () const
Returns true if the geometry is valid.
PX_INLINE bool PxTriangleMeshGeometry::isValid () const
Returns true if the geometry is valid.
Detailed Description
Macro Definition Documentation
DECLARE_CUSTOM_GEOMETRY_TYPE
#define DECLARE_CUSTOM_GEOMETRY_TYPE
Value:
static ::physx::PxCustomGeometry::Type TYPE();                  \
    virtual ::physx::PxCustomGeometry::Type getCustomType() const;
Used in pair with IMPLEMENT_CUSTOM_GEOMETRY_TYPE to overwrite Callbacks::getCustomType() callback.
IMPLEMENT_CUSTOM_GEOMETRY_TYPE
#define IMPLEMENT_CUSTOM_GEOMETRY_TYPE (CLASS)
Value:
::physx::PxCustomGeometry::Type CLASS::TYPE()                       \
{                                                                   \
    static ::physx::PxCustomGeometry::Type customType;              \
    return customType;                                              \
}                                                                   \
::physx::PxCustomGeometry::Type CLASS::getCustomType() const        \
{                                                                   \
    return TYPE();                                                  \
}
Used in pair with DECLARE_CUSTOM_GEOMETRY_TYPE to overwrite Callbacks::getCustomType() callback.
PX_MESH_SCALE_MAX
#define PX_MESH_SCALE_MAX 1e6f
Maximum allowed absolute magnitude for each of mesh scale's components (x,y,z).
Note
Only positive scale values are allowed for convex meshes.
Referenced by PxMeshScale::isValidForConvexMesh(), and PxMeshScale::isValidForTriangleMesh().
PX_MESH_SCALE_MIN
#define PX_MESH_SCALE_MIN 1e-6f
Minimum allowed absolute magnitude for each of mesh scale's components (x,y,z).
Note
Only positive scale values are allowed for convex meshes.
Referenced by PxMeshScale::isValidForConvexMesh(), and PxMeshScale::isValidForTriangleMesh().
PX_MIN_HEIGHTFIELD_XZ_SCALE
#define PX_MIN_HEIGHTFIELD_XZ_SCALE 1e-8f
Referenced by PxHeightFieldGeometry::isValid().
PX_MIN_HEIGHTFIELD_Y_SCALE
#define PX_MIN_HEIGHTFIELD_Y_SCALE (0.0001f / PxReal(0xFFFF))
Referenced by PxHeightFieldGeometry::isValid().
Typedef Documentation
PxBVHStructure
typedef PX_DEPRECATED PxBVH PxBVHStructure
PxConvexMeshGeometryFlags
typedef PxFlags<PxConvexMeshGeometryFlag::Enum,PxU8> PxConvexMeshGeometryFlags
collection of set bits defined in PxConvexMeshGeometryFlag.
See also
PxConvexMeshGeometryFlag
PxHeightFieldFlags
typedef PxFlags<PxHeightFieldFlag::Enum,PxU16> PxHeightFieldFlags
collection of set bits defined in PxHeightFieldFlag.
See also
PxHeightFieldFlag
PxMeshFlags
typedef PxFlags<PxMeshFlag::Enum,PxU16> PxMeshFlags
collection of set bits defined in PxMeshFlag.
See also
PxMeshFlag
PxMeshGeometryFlags
typedef PxFlags<PxMeshGeometryFlag::Enum,PxU8> PxMeshGeometryFlags
collection of set bits defined in PxMeshGeometryFlag.
See also
PxMeshGeometryFlag
PxTetrahedronMeshFlags
typedef PxFlags<PxTetrahedronMeshFlag::Enum, PxU8> PxTetrahedronMeshFlags
collection of set bits defined in PxTetrahedronMeshFlag.
See also
PxTetrahedronMeshFlag
PxTriangleMeshFlags
typedef PxFlags<PxTriangleMeshFlag::Enum,PxU8> PxTriangleMeshFlags
collection of set bits defined in PxTriangleMeshFlag.
See also
PxTriangleMeshFlag
Function Documentation
isValid() [1/11]
PX_INLINE bool PxSphereGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid
Note
A valid sphere has radius > 0. It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a sphere that has zero radius.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eSPHERE, and PxIsFinite().
isValid() [2/11]
PX_INLINE bool PxPlaneGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid
References PxGeometryType::ePLANE.
isValid() [3/11]
PX_INLINE bool PxCapsuleGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid.
Note
A valid capsule has radius > 0, halfHeight >= 0. It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a capsule that has zero radius or height.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eCAPSULE, and PxIsFinite().
isValid() [4/11]
PX_INLINE bool PxTetrahedronMeshGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid for shape creation.
Note
A valid tetrahedron mesh has a positive scale value in each direction (scale.scale.x > 0, scale.scale.y > 0, scale.scale.z > 0). It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a tetrahedron mesh that has zero extents in any direction.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eTETRAHEDRONMESH.
isValid() [5/11]
PX_INLINE bool PxBoxGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid
Note
A valid box has a positive extent in each direction (halfExtents.x > 0, halfExtents.y > 0, halfExtents.z > 0). It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a box that has zero extent in any direction.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eBOX.
isValid() [6/11]
PX_INLINE bool PxHeightFieldGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid
Note
A valid height field has a positive scale value in each direction (heightScale > 0, rowScale > 0, columnScale > 0). It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a height field that has zero extents in any direction.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eHEIGHTFIELD, PX_MIN_HEIGHTFIELD_XZ_SCALE, PX_MIN_HEIGHTFIELD_Y_SCALE, and PxIsFinite().
isValid() [7/11]
PX_INLINE bool PxSimpleTriangleMesh::isValid () const
returns true if the current settings are valid
References PxMeshFlag::e16_BIT_INDICES.
Referenced by PxTriangleMeshDesc::isValid().
isValid() [8/11]
PX_INLINE bool PxTriangleMeshGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid for shape creation.
Note
A valid triangle mesh has a positive scale value in each direction (scale.scale.x > 0, scale.scale.y > 0, scale.scale.z > 0). It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a triangle mesh that has zero extents in any direction.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eTRIANGLEMESH.
isValid() [9/11]
PX_INLINE bool PxConvexMeshGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid for shape creation.
Note
A valid convex mesh has a positive scale value in each direction (scale.x > 0, scale.y > 0, scale.z > 0). It is illegal to call PxRigidActor::createShape and PxPhysics::createShape with a convex that has zero extent in any direction.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eCONVEXMESH.
isValid() [10/11]
PX_INLINE bool PxHeightFieldDesc::isValid () const
Returns true if the descriptor is valid.
Returns
True if the current settings are valid.
References PxHeightFieldFlag::eNO_BOUNDARY_EDGES, and PxHeightFieldFormat::eS16_TM.
isValid() [11/11]
PX_INLINE bool PxCustomGeometry::isValid () const
Returns true if the geometry is valid.
Returns
True if the current settings are valid for shape creation.
See also
PxRigidActor::createShape, PxPhysics::createShape
References PxGeometryType::eCUSTOM.
PxFindOverlap()
PX_C_EXPORT PX_PHYSX_COMMON_API bool PX_CALL_CONV PxFindOverlap (PxReportCallback< PxGeomIndexPair > & callback, const PxBVH & bvh0, const PxBVH & bvh1)
BVH-vs-BVH overlap test.
This function returns pairs of box indices that belong to both the first & second input bvhs.
Parameters
[in] callback The callback object used to report results
[in] bvh0 First bvh
[in] bvh1 Second bvh
Returns
true if an overlap has been detected
See also
PxBVH PxReportCallback
PxGetBVHInternalData()
PX_C_EXPORT PX_PHYSX_COMMON_API bool PX_CALL_CONV PxGetBVHInternalData (PxBVHInternalData & data, const PxBVH & bvh, bool takeOwnership)
PxGetTriangleMeshInternalData()
PX_C_EXPORT PX_PHYSX_COMMON_API bool PX_CALL_CONV PxGetTriangleMeshInternalData (PxTriangleMeshInternalData & data, const PxTriangleMesh & mesh, bool takeOwnership)
PxHeightFieldDesc()
PX_INLINE PxHeightFieldDesc::PxHeightFieldDesc ()
Constructor sets to default.
References PxHeightFieldFormat::eS16_TM.
PxSimpleTriangleMesh()
PX_INLINE PxSimpleTriangleMesh::PxSimpleTriangleMesh ()
constructor sets to default.
setToDefault() [1/2]
PX_INLINE void PxSimpleTriangleMesh::setToDefault ()
(re)sets the structure to the default.
Referenced by PxTriangleMeshDesc::PxTriangleMeshDesc().
setToDefault() [2/2]
PX_INLINE void PxHeightFieldDesc::setToDefault ()
(re)sets the structure to the default.