Foundation
Foundation
Classes
class PxDelayLoadHook
PxDelayLoadHook.
class PxFileBuf
Callback class for data serialization.
class PxVec2T< Type >
2 Element vector class.
class PxVec3T< Type >
3 Element vector class.
class PxVec4T< Type >
4 Element vector class.
class PxQuatT< Type >
This is a quaternion class. For more information on quaternion mathematics consult a mathematics source on complex numbers.
class PxMat33T< Type >
3x3 matrix class
class PxMat34T< Type >
class PxMat44T< Type >
4x4 matrix class
class PxTransformT< Type >
class representing a rigid euclidean transform as a quaternion and a vector
class PxAllocatorCallback
Abstract base class for an application defined memory allocator that can be used by the Nv library.
class PxAssertHandler
class PxBitAndDataT< storageType, bitMask >
class PxBounds3
Class representing 3D range or axis aligned bounding box.
class PxErrorCallback
User defined interface class. Used by the library to emit debug information.
struct PxErrorCode
Error codes.
class PxFlags< enumtype, storagetype >
Container for bitfield flag variables associated with a specific enum type.
class PxFoundation
Foundation SDK singleton class.
class PxMat34Padded
A padded version of PxMat34, to safely load its data using SIMD.
class PxPlane
Representation of a plane.
struct PxPackValidation
class PxStack< PxAllocator >
class PxStrideIterator< T >
Iterator class for iterating over arrays of data that may be interleaved with other data.
class PxVec3Padded
A padded version of PxVec3, to safely load its data using SIMD.
Macros
#define PX_ASSERT(exp) ((void)0)
#define PX_ALWAYS_ASSERT_MESSAGE(exp) ((void)0)
#define PX_ASSERT_WITH_MESSAGE(condition, message) ((void)0)
#define PX_ALWAYS_ASSERT() PX_ASSERT(0)
#define PX_MAX_BOUNDS_EXTENTS (PX_MAX_REAL * 0.25f)
#define PX_CHECK_MSG(exp, msg)
#define PX_CHECK(exp)
#define PX_CHECK_AND_RETURN(exp, msg)
#define PX_CHECK_AND_RETURN_NULL(exp, msg)
#define PX_CHECK_AND_RETURN_VAL(exp, msg, r)
#define PX_WARN ::physx::PxErrorCode::eDEBUG_WARNING, __FILE__, __LINE__
#define PX_INFO ::physx::PxErrorCode::eDEBUG_INFO, __FILE__, __LINE__
#define PX_WARN_ONCE(string) ((void)0)
#define PX_WARN_ONCE_IF(condition, string) ((void)0)
#define PX_IMPLEMENT_OUTPUT_ERROR
#define PX_FOUNDATION_API
#define PX_PHYSICS_VERSION_MAJOR 5
#define PX_PHYSICS_VERSION_MINOR 1
#define PX_PHYSICS_VERSION_BUGFIX 0
#define PX_PHYSICS_VERSION ((PX_PHYSICS_VERSION_MAJOR<<24) + (PX_PHYSICS_VERSION_MINOR<<16) + (PX_PHYSICS_VERSION_BUGFIX<<8) + 0)
#define PX_STRINGIZE_HELPER(X) #X
#define PX_STRINGIZE(X) PX_STRINGIZE_HELPER(X)
#define PX_CONCAT_HELPER(X, Y) X##Y
#define PX_CONCAT(X, Y) PX_CONCAT_HELPER(X, Y)
#define PX_VC 0
#define PX_CLANG 0
#define PX_GCC 0
#define PX_WIN64 0
#define PX_WIN32 0
#define PX_LINUX 0
#define PX_OSX 0
#define PX_SWITCH 0
#define PX_X64 0
#define PX_X86 0
#define PX_A64 0
#define PX_ARM 0
#define PX_PPC 0
#define PX_SSE2 0
#define PX_NEON 0
#define PX_VMX 0
#define PX_DEBUG 0
#define PX_CHECKED 0
#define PX_PROFILE 0
#define PX_DEBUG_CRT 0
#define PX_NVTX 0
#define PX_GCC_FAMILY (PX_CLANG || PX_GCC)
#define PX_WINDOWS_FAMILY (PX_WIN32 || PX_WIN64)
#define PX_LINUX_FAMILY PX_LINUX
#define PX_APPLE_FAMILY PX_OSX
#define PX_UNIX_FAMILY (PX_LINUX_FAMILY || PX_APPLE_FAMILY)
#define PX_EMSCRIPTEN 0
#define PX_INTEL_FAMILY (PX_X64 || PX_X86)
#define PX_ARM_FAMILY (PX_ARM || PX_A64)
#define PX_P64_FAMILY (PX_X64 || PX_A64)
#define PX_LIBCPP 0
#define PX_WINDOWS (PX_WINDOWS_FAMILY && !PX_ARM_FAMILY)
#define PX_ENABLE_ASSERTS 0
#define PX_C_EXPORT
#define PX_UNIX_EXPORT
#define PX_DLL_EXPORT PX_UNIX_EXPORT
#define PX_DLL_IMPORT
#define PX_CALL_CONV
#define PX_PUSH_PACK_DEFAULT
#define PX_POP_PACK
#define PX_INLINE inline
#define PX_FORCE_INLINE inline
#define PX_NOINLINE
#define PX_RESTRICT __restrict
#define PX_NOALIAS
#define PX_OVERRIDE
#define PX_DEPRECATED
#define PX_COMPILE_TIME_ASSERT(exp) typedef char PxCompileTimeAssert_Dummy[(exp) ? 1 : -1]
#define PX_OFFSET_OF(X, Y) offsetof(X, Y)
#define PX_OFFSETOF_BASE 0x100
#define PX_OFFSET_OF_RT(Class, Member) (reinterpret_cast<size_t>(&reinterpret_cast<Class*>(PX_OFFSETOF_BASE)->Member) - size_t(PX_OFFSETOF_BASE))
#define PX_CUDA_CALLABLE
#define PX_DUMMY_SYMBOL
#define PX_WEAK_SYMBOL
#define PX_NOCOPY(Class)
#define PX_SUPPORT_GPU_PHYSX ((PX_X64 && (PX_WINDOWS_FAMILY || PX_LINUX)) || (PX_A64 && PX_LINUX))
#define PX_SUPPORT_EXTERN_TEMPLATE (PX_VC != 11)
#define PX_FL __FILE__, __LINE__
#define __STDC_FORMAT_MACROS
#define PX_PRIu64 PRIu64
#define PX_SIGN_BITMASK 0x80000000
#define PX_MAX_F32 3.4028234663852885981170418348452e+38F
#define PX_MAX_F64 DBL_MAX
#define PX_EPS_F32 FLT_EPSILON
#define PX_EPS_F64 DBL_EPSILON
#define PX_MAX_REAL PX_MAX_F32
#define PX_EPS_REAL PX_EPS_F32
#define PX_NORMALIZATION_EPSILON float(1e-20f)
#define PX_MAX_I8 INT8_MAX
#define PX_MIN_I8 INT8_MIN
#define PX_MAX_U8 UINT8_MAX
#define PX_MIN_U8 UINT8_MIN
#define PX_MAX_I16 INT16_MAX
#define PX_MIN_I16 INT16_MIN
#define PX_MAX_U16 UINT16_MAX
#define PX_MIN_U16 UINT16_MIN
#define PX_MAX_I32 INT32_MAX
#define PX_MIN_I32 INT32_MIN
#define PX_MAX_U32 UINT32_MAX
#define PX_MIN_U32 UINT32_MIN
#define PX_SORT_PARANOIA PX_DEBUG
#define USE_VOLATILE_UNION
Typedefs
typedef uint32_t PxU32
typedef PxVec2T< float > PxVec2
typedef PxVec3T< float > PxVec3
typedef PxVec4T< float > PxVec4
typedef PxQuatT< float > PxQuat
typedef PxMat33T< float > PxMat33
typedef PxMat34T< float > PxMat34
typedef PxMat44T< float > PxMat44
typedef PxTransformT< float > PxTransform
typedef PxBitAndDataT< PxU8, 0x80 > PxBitAndByte
typedef PxBitAndDataT< PxU16, 0x8000 > PxBitAndWord
typedef PxBitAndDataT< PxU32, 0x80000000 > PxBitAndDword
typedef PxMat33T< float > PxMat33
typedef PxMat33T< double > PxMat33d
typedef PxMat34T< float > PxMat34
typedef PxMat34T< double > PxMat34d
typedef PxMat44T< float > PxMat44
typedef PxMat44T< double > PxMat44d
typedef PxQuatT< float > PxQuat
typedef PxQuatT< double > PxQuatd
typedef int64_t PxI64
typedef uint64_t PxU64
typedef int32_t PxI32
typedef uint32_t PxU32
typedef int16_t PxI16
typedef uint16_t PxU16
typedef int8_t PxI8
typedef uint8_t PxU8
typedef float PxF32
typedef double PxF64
typedef float PxReal
typedef PxI32 PxIntBool
typedef PxTransformT< float > PxTransform
typedef PxTransformT< double > PxTransformd
typedef PxTransformPadded PxTransform32
typedef PxVec2T< float > PxVec2
typedef PxVec2T< double > PxVec2d
typedef PxVec3T< float > PxVec3
typedef PxVec3T< double > PxVec3d
typedef PxVec3Padded PxVec3p
typedef PxVec4T< float > PxVec4
typedef PxVec4T< double > PxVec4d
Enumerations
enum PxEMPTY { PxEmpty }
enum PxZERO { PxZero }
enum PxIDENTITY { PxIdentity }
Functions
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxSetPhysXDelayLoadHook (const physx::PxDelayLoadHook *hook)
Sets delay load hook instance for PhysX dll.
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxSetPhysXCookingDelayLoadHook (const physx::PxDelayLoadHook *hook)
Sets delay load hook instance for PhysXCooking dll.
PX_C_EXPORT PX_PHYSX_COMMON_API void PX_CALL_CONV PxSetPhysXCommonDelayLoadHook (const physx::PxDelayLoadHook *hook)
Sets delay load hook instance for PhysXCommon dll.
PX_FOUNDATION_API PX_DEPRECATED PxAssertHandler & PxGetAssertHandler ()
PX_FOUNDATION_API PX_DEPRECATED void PxSetAssertHandler (PxAssertHandler &handler)
PX_C_EXPORT PX_FOUNDATION_API physx::PxFoundation *PX_CALL_CONV PxCreateFoundation (physx::PxU32 version, physx::PxAllocatorCallback &allocator, physx::PxErrorCallback &errorCallback)
Creates an instance of the foundation class.
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxSetFoundationInstance (physx::PxFoundation &foundation)
PX_C_EXPORT PX_FOUNDATION_API physx::PxFoundation &PX_CALL_CONV PxGetFoundation ()
Retrieves the Foundation SDK after it has been created.
PX_C_EXPORT PX_FOUNDATION_API physx::PxProfilerCallback *PX_CALL_CONV PxGetProfilerCallback ()
Get the callback that will be used for all profiling.
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxSetProfilerCallback (physx::PxProfilerCallback *profiler)
Set the callback that will be used for all profiling.
PX_C_EXPORT PX_FOUNDATION_API physx::PxAllocatorCallback *PX_CALL_CONV PxGetAllocatorCallback ()
Get the allocator callback.
PX_C_EXPORT PX_FOUNDATION_API physx::PxAllocatorCallback *PX_CALL_CONV PxGetBroadcastAllocator ()
Get the broadcasting allocator callback.
PX_C_EXPORT PX_FOUNDATION_API physx::PxErrorCallback *PX_CALL_CONV PxGetErrorCallback ()
Get the error callback.
PX_C_EXPORT PX_FOUNDATION_API physx::PxErrorCallback *PX_CALL_CONV PxGetBroadcastError ()
Get the broadcasting error callback.
PX_C_EXPORT PX_FOUNDATION_API physx::PxU32 PX_CALL_CONV PxGetWarnOnceTimeStamp ()
Get the warn once timestamp.
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxDecFoundationRefCount ()
Decrement the ref count of PxFoundation.
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxIncFoundationRefCount ()
Increment the ref count of PxFoundation.
template<class Type >
PX_CUDA_CALLABLE PX_INLINE PxMat33T< Type > operator* (Type scalar, const PxMat33T< Type > &m)
template<class Type >
PX_INLINE PxMat34T< Type > operator* (const PxMat33T< Type > &a, const PxMat34T< Type > &b)
Multiply a*b, a is extended.
PX_COMPILE_TIME_ASSERT (0==(sizeof(PxMat34Padded)==16))
template<class T >
PX_CUDA_CALLABLE PX_FORCE_INLINE T PxMax (T a, T b)
The return value is the greater of the two specified values.
template<>
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxMax (float a, float b)
overload for float to use fsel on xbox
template<class T >
PX_CUDA_CALLABLE PX_FORCE_INLINE T PxMin (T a, T b)
The return value is the lesser of the two specified values.
template<>
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxMin (float a, float b)
overload for float to use fsel on xbox
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAbs (float a)
abs returns the absolute value of its argument.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxEquals (float a, float b, float eps)
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAbs (double a)
abs returns the absolute value of its argument.
PX_CUDA_CALLABLE PX_FORCE_INLINE int32_t PxAbs (int32_t a)
abs returns the absolute value of its argument.
template<class T >
PX_CUDA_CALLABLE PX_FORCE_INLINE T PxClamp (T v, T lo, T hi)
Clamps v to the range [hi,lo].
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSqrt (float a)
Square root.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxSqrt (double a)
Square root.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxRecipSqrt (float a)
reciprocal square root.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxRecipSqrt (double a)
reciprocal square root.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxF32 PxSqr (const PxF32 a)
square of the argument
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSin (float a)
trigonometry – all angles are in radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxSin (double a)
Sine of an angle (Unit: Radians)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxCos (float a)
Cosine of an angle (Unit: Radians)
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxCos (double a)
Cosine of an angle (Unit: Radians)
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxSinCos (const PxF32 a, PxF32 &sin, PxF32 &cos)
compute sine and cosine at the same time
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxSinCos (const double a, double &sin, double &cos)
compute sine and cosine at the same time
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxTan (float a)
Tangent of an angle. Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxTan (double a)
Tangent of an angle. Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAsin (float f)
Arcsine. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAsin (double f)
Arcsine. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAcos (float f)
Arccosine. Returns angle between 0 and PI in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAcos (double f)
Arccosine. Returns angle between 0 and PI in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAtan (float a)
ArcTangent. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAtan (double a)
ArcTangent. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAtan2 (float x, float y)
Arctangent of (x/y) with correct sign. Returns angle between -PI and PI in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAtan2 (double x, double y)
Arctangent of (x/y) with correct sign. Returns angle between -PI and PI in radians Unit: Radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxF32 PxDegToRad (const PxF32 a)
Converts degrees to radians.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxIsFinite (float f)
returns true if the passed number is a finite floating point number as opposed to INF, NAN, etc.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxIsFinite (double f)
returns true if the passed number is a finite floating point number as opposed to INF, NAN, etc.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxFloor (float a)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxExp (float a)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxCeil (float a)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSign (float a)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSign2 (float a, float eps=FLT_EPSILON)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxPow (float x, float y)
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxLog (float x)
PX_FORCE_INLINE void * PxMemZero (void *dest, PxU32 count)
Sets the bytes of the provided buffer to zero.
PX_FORCE_INLINE void * PxMemSet (void *dest, PxI32 c, PxU32 count)
Sets the bytes of the provided buffer to the specified value.
PX_FORCE_INLINE void * PxMemCopy (void *dest, const void *src, PxU32 count)
Copies the bytes of one memory block to another. The memory blocks must not overlap.
PX_FORCE_INLINE void * PxMemMove (void *dest, const void *src, PxU32 count)
Copies the bytes of one memory block to another. The memory blocks can overlap.
template<class T >
PX_CUDA_CALLABLE PX_INLINE void PX_UNUSED (T const &)
PX_COMPILE_TIME_ASSERT (PX_OFFSET_OF(PxPackValidation, a)==8)
template<class T , class Predicate , class PxAllocator >
void PxSort (T *elements, uint32_t count, const Predicate &compare, const PxAllocator &inAllocator, const uint32_t initialStackSize=32)
Sorts an array of objects in ascending order, assuming that the predicate implements the < operator:
template<class T , class Predicate >
void PxSort (T *elements, uint32_t count, const Predicate &compare)
template<class T >
void PxSort (T *elements, uint32_t count)
template<class T , class Predicate >
PX_INLINE void PxMedian3 (T *elements, int32_t first, int32_t last, Predicate &compare)
template<class T , class Predicate >
PX_INLINE int32_t PxPartition (T *elements, int32_t first, int32_t last, Predicate &compare)
template<class T , class Predicate >
PX_INLINE void PxSmallSort (T *elements, int32_t first, int32_t last, Predicate &compare)
template<typename T >
PX_INLINE PxStrideIterator< T > operator+ (int i, PxStrideIterator< T > it)
Addition operator.
template<typename T >
PX_INLINE PxStrideIterator< T > PxMakeIterator (T *ptr, PxU32 stride=sizeof(T))
Stride iterator factory function which infers the iterator type.
template<typename T >
PX_INLINE PxStrideIterator< const T > PxMakeIterator (const T *ptr, PxU32 stride=sizeof(T))
Stride iterator factory function which infers the iterator type.
struct PX_ALIGN_PREFIX (16) PxTransformPadded
A generic padded & aligned transform class.
PX_COMPILE_TIME_ASSERT (sizeof(PxTransformPadded)==32)
template<class A , class B >
PX_FORCE_INLINE A PxUnionCast (B b)
template<class Type >
static PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec2T< Type > operator* (Type f, const PxVec2T< Type > &v)
template<class Type >
static PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T< Type > operator* (Type f, const PxVec3T< Type > &v)
PX_COMPILE_TIME_ASSERT (sizeof(PxVec3Padded)==16)
template<class Type >
static PX_CUDA_CALLABLE PX_INLINE PxVec4T< Type > operator* (Type f, const PxVec4T< Type > &v)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3::PxBounds3 (const PxVec3 &minimum, const PxVec3 &maximum)
Construct from two bounding points.
static PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3 PxBounds3::empty ()
Return empty bounds.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isFinite () const
static PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3 PxBounds3::boundsOfPoints (const PxVec3 &v0, const PxVec3 &v1)
returns the AABB containing v0 and v1.
static PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3 PxBounds3::centerExtents (const PxVec3 &center, const PxVec3 &extent)
returns the AABB from center and extents vectors.
static PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::basisExtent (const PxVec3 &center, const PxMat33 &basis, const PxVec3 &extent)
Construct from center, extent, and (not necessarily orthogonal) basis.
static PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::poseExtent (const PxTransform &pose, const PxVec3 &extent)
Construct from pose and extent.
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::setEmpty ()
Sets empty to true.
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::setMaximal ()
Sets the bounds to maximum size [-PX_MAX_BOUNDS_EXTENTS, PX_MAX_BOUNDS_EXTENTS].
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::include (const PxVec3 &v)
expands the volume to include v
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::include (const PxBounds3 &b)
expands the volume to include b.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isEmpty () const
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::intersects (const PxBounds3 &b) const
indicates whether the intersection of this and b is empty or not.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::intersects1D (const PxBounds3 &a, uint32_t axis) const
computes the 1D-intersection between two AABBs, on a given axis.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::contains (const PxVec3 &v) const
indicates if these bounds contain v.
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isInside (const PxBounds3 &box) const
checks a box is inside another box.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::getCenter () const
returns the center of this axis aligned box.
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxBounds3::getCenter (uint32_t axis) const
get component of the box's center along a given axis
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxBounds3::getExtents (uint32_t axis) const
get component of the box's extents along a given axis
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::getDimensions () const
returns the dimensions (width/height/depth) of this axis aligned box.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::getExtents () const
returns the extents, which are half of the width/height/depth.
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::scaleSafe (float scale)
scales the AABB.
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::scaleFast (float scale)
scales the AABB.
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::fattenSafe (float distance)
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::fattenFast (float distance)
static PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformSafe (const PxMat33 &matrix, const PxBounds3 &bounds)
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
static PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformFast (const PxMat33 &matrix, const PxBounds3 &bounds)
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
static PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformSafe (const PxTransform &transform, const PxBounds3 &bounds)
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
static PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformFast (const PxTransform &transform, const PxBounds3 &bounds)
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isValid () const
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::closestPoint (const PxVec3 &p) const
PX_CUDA_CALLABLE PX_INLINE PxQuatT< Type >::PxQuatT (const PxMat33T< Type > &m)
Creates from orientation matrix.
PX_CUDA_CALLABLE PX_FORCE_INLINE PxTransformT< Type >::PxTransformT (const PxMat44T< Type > &m)
Variables
static const float PxPi = float(3.141592653589793)
static const float PxHalfPi = float(1.57079632679489661923)
static const float PxTwoPi = float(6.28318530717958647692)
static const float PxInvPi = float(0.31830988618379067154)
static const float PxInvTwoPi = float(0.15915494309189533577)
static const float PxPiDivTwo = float(1.57079632679489661923)
static const float PxPiDivFour = float(0.78539816339744830962)
static const float PxSqrt2 = float(1.4142135623730951)
static const float PxInvSqrt2 = float(0.7071067811865476)
static const PxIntBool PxIntFalse = 0
static const PxIntBool PxIntTrue = 1
Detailed Description
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
PX_A64
#define PX_A64 0
PX_ALWAYS_ASSERT
#define PX_ALWAYS_ASSERT () PX_ASSERT(0)
Referenced by PxVehiclePhysXRoadGeometrySceneQueryComponent::update(), and PxVehiclePhysXActorEndComponent::update().
PX_ALWAYS_ASSERT_MESSAGE
#define PX_ALWAYS_ASSERT_MESSAGE (exp) ((void)0)
PX_APPLE_FAMILY
#define PX_APPLE_FAMILY PX_OSX
PX_ARM
#define PX_ARM 0
PX_ARM_FAMILY
#define PX_ARM_FAMILY (PX_ARM || PX_A64)
PX_ASSERT
#define PX_ASSERT (exp) ((void)0)
Referenced by physx::__declspec(), ExtGpu::_testLaunch(), PxVehicleAxleDescription::addAxle(), PxVehicleWheelConstraintGroupState::addConstraintGroup(), PxFixedSizeLookupTable< eMAX_NB_ENGINE_TORQUE_CURVE_ENTRIES >::addPair(), PxTask::addReference(), PxVehicleTankDriveDifferentialParams::addTankTrack(), PxContactStreamIterator::advanceToIndex(), PxDefaultAllocator::allocate(), PxVirtualAllocator::allocate(), PxBitMapBase< PxAllocator >::andNibbleFast(), physx::PxArray< void *, Alloc >::back(), PxHashBase< Entry, Key, HashFn, GetKey, PxAllocator, compacting >::Iter::check(), Gu::ContactBuffer::contact(), PxBounds3::contains(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::copy(), physx::PxPoolBase< T, Alloc >::deallocate(), PxVirtualAllocator::deallocate(), PxBounds3::fattenFast(), PxBounds3::fattenSafe(), PxTask::finishBefore(), PxRegularReportCallback< T >::flushResults(), PxLocalStorageReportCallback< T, capacityT >::flushResults(), PxExternalStorageReportCallback< T >::flushResults(), PxDynamicArrayReportCallback< T >::flushResults(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::freeListAdd(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::freeListGetNext(), physx::PxArray< void *, Alloc >::front(), PxVehicleMatrixNN::get(), PxGeometryHolder::get(), PxHitBuffer< PxSweepHit >::getAnyHit(), PxMat44T< float >::getBasis(), PxBounds3::getCenter(), PxBounds3::getDimensions(), PxContactStreamIterator::getExtendedContact(), PxBounds3::getExtents(), aos::PxTransformV::getInverse(), PxTransformT< float >::getInverse(), PxBroadcast< PxErrorCallback, PxErrorCallback >::getListener(), PxMassProperties::getMassSpaceInertia(), PxBitMapBase< PxAllocator >::PxLoopIterator::getNext(), PxBitMapBase< PxAllocator >::getNibbleFast(), PxSimulationStatistics::getRbPairStats(), PxHitBuffer< PxSweepHit >::getTouch(), PxFixedSizeLookupTable< eMAX_NB_ENGINE_TORQUE_CURVE_ENTRIES >::getYVal(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::grow(), physx::PxArray< void *, Alloc >::grow(), physx::PxArray< void *, Alloc >::growAndPushBack(), PxBitMapBase< PxAllocator >::PxLoopIterator::hasBits(), PxBounds3::include(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::insertUnique(), PxVehicleFixedSizeLookupTable< PxVec3T, 3 >::interpolate(), PxBounds3::intersects(), PxBounds3::intersects1D(), PxBounds3::isEmpty(), PxBounds3::isInside(), PxContactStreamIterator::nextContact(), PxContactPairExtraDataIterator::nextItemSet(), PxContactStreamIterator::nextPatch(), PxVec3T< float >::normalizeFast(), PxStrideIterator< T >::operator!=(), aos::PxTransformV::operator*(), PxTransformT< float >::operator*(), PxMassProperties::operator*(), PxStrideIterator< T >::operator-(), PxStrideIterator< T >::operator<(), PxStrideIterator< T >::operator<=(), PxBitMapBase< PxAllocator >::Iterator::operator=(), PxStrideIterator< T >::operator==(), PxStrideIterator< T >::operator>(), PxStrideIterator< T >::operator>=(), PxVehicleVectorN::operator[](), PxVec2T< Type >::operator[](), PxVec3T< float >::operator[](), PxVec4T< float >::operator[](), physx::PxArray< void *, Alloc >::operator[](), PxExtendedVec3::operator[](), PxBitMapBase< PxAllocator >::orNibbleFast(), PxStack< PxAllocator >::pop(), PxBase::PxBase(), PxClamp(), PxCreateRepXObject(), physx::PxDebugBreak(), PxHighestSetBit(), PxILog2(), PxLog(), PxLowestSetBit(), PxMassProperties::PxMassProperties(), physx::aos::PxMat33_From_Mat33V(), PxMeshScale::PxMeshScale(), PxPartition(), PxQuatT< float >::PxQuatT(), PxRegularReportCallback< T >::PxRegularReportCallback(), physx::PxSListT< Alloc >::PxSListT(), PxSort(), PxStrideIterator< T >::PxStrideIterator(), physx::PxTo16(), physx::PxTo32(), physx::PxTo8(), physx::PxToI8(), PxTransformT< float >::PxTransformT(), aos::PxTransformV::PxTransformV(), PxVehicleMatrixNN::PxVehicleMatrixNN(), PxVehicleVectorN::PxVehicleVectorN(), physx::PxArray< void *, Alloc >::recreate(), PxSerializerDefaultAdapter< T >::registerReferences(), PxTask::release(), PxTask::removeReference(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::replaceWithLast(), PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::reserveInternal(), PxBitMapBase< PxAllocator >::reset(), PxBitMapBase< PxAllocator >::resize(), aos::PxTransformV::rotate(), PxTransformT< float >::rotate(), PxMassProperties::rotateInertia(), aos::PxTransformV::rotateInv(), PxTransformT< float >::rotateInv(), PxBounds3::scaleFast(), PxMassProperties::scaleInertia(), PxBounds3::scaleSafe(), PxBitMapBase< PxAllocator >::set(), PxVehicleMatrixNN::set(), PxLightCpuTask::setContinuation(), PxVehicleMatrixNN::setSize(), PxVehicleComponentSequence::setSubsteps(), PxTask::startAfter(), PxMassProperties::sum(), PxBitMapBase< PxAllocator >::test(), aos::PxTransformV::transform(), PxTransformT< float >::transform(), PxBounds3::transformFast(), aos::PxTransformV::transformInv(), PxTransformT< float >::transformInv(), PxBounds3::transformSafe(), PxMassProperties::translate(), PxMassProperties::translateInertia(), PxVehicleComponentSequence::update(), PxVehicleEngineDriveCommandResponseComponent::update(), PxVehicleComponentSequence::updateSubGroup(), physx::aos::V4ConvertToU32VSaturate(), vehicleConstraintSolverPrep(), and visualiseVehicleConstraint().
PX_ASSERT_WITH_MESSAGE
#define PX_ASSERT_WITH_MESSAGE (condition, message) ((void)0)
Referenced by PxSimulationStatistics::getRbPairStats(), and PxGeometryHolder::storeAny().
PX_C_EXPORT
#define PX_C_EXPORT
DLL export macros
PX_CALL_CONV
#define PX_CALL_CONV
Calling convention
PX_CHECK
#define PX_CHECK (exp)
PX_CHECK_AND_RETURN
#define PX_CHECK_AND_RETURN (exp, msg)
Referenced by PxVehicleBrakeCommandResponseUpdate().
PX_CHECK_AND_RETURN_NULL
#define PX_CHECK_AND_RETURN_NULL (exp, msg)
PX_CHECK_AND_RETURN_VAL
#define PX_CHECK_AND_RETURN_VAL (exp, msg, r)
Referenced by PxVehicleFixedSizeLookupTable< PxVec3T, 3 >::addPair(), PxVehicleCommandNonLinearResponseParams::addResponse(), PxVehicleBrakeCommandResponseParams::isValid(), PxVehicleDirectDriveThrottleCommandResponseParams::isValid(), PxVehicleSteerCommandResponseParams::isValid(), PxVehicleRigidBodyParams::isValid(), PxVehicleSuspensionParams::isValid(), PxVehicleAckermannParams::isValid(), PxVehiclePhysXSuspensionLimitConstraintParams::isValid(), PxVehiclePhysXRoadGeometryQueryParams::isValid(), PxVehicleWheelParams::isValid(), PxVehicleClutchCommandResponseParams::isValid(), PxVehiclePhysXMaterialFriction::isValid(), PxVehicleAxleDescription::isValid(), PxVehicleTireForceParams::isValid(), PxVehiclePhysXMaterialFrictionParams::isValid(), PxVehicleClutchParams::isValid(), PxVehicleSuspensionComplianceParams::isValid(), PxVehicleFrame::isValid(), PxVehicleScale::isValid(), PxVehicleSuspensionForceParams::isValid(), PxVehicleEngineParams::isValid(), PxVehicleSuspensionForceLegacyParams::isValid(), PxVehicleGearboxParams::isValid(), PxVehicleAutoboxParams::isValid(), PxVehicleTireSlipParams::isValid(), PxVehicleFourWheelDriveDifferentialLegacyParams::isValid(), PxVehicleTireAxisStickyParams::isValid(), PxVehicleMultiWheelDriveDifferentialParams::isValid(), PxVehicleFourWheelDriveDifferentialParams::isValid(), PxVehicleFixedSizeLookupTable< PxVec3T, 3 >::isValid(), PxVehicleTankDriveDifferentialParams::isValid(), and PxInitVehicleExtension().
PX_CHECK_MSG
#define PX_CHECK_MSG (exp, msg)
PX_CHECKED
#define PX_CHECKED 0
PX_CLANG
#define PX_CLANG 0
PX_COMPILE_TIME_ASSERT
#define PX_COMPILE_TIME_ASSERT (exp) typedef char PxCompileTimeAssert_Dummy[(exp) ? 1 : -1]
General defines
Referenced by physx::PxPoolBase< T, Alloc >::PxPoolBase().
PX_CONCAT
#define PX_CONCAT (X, Y) PX_CONCAT_HELPER(X, Y)
PX_CONCAT_HELPER
#define PX_CONCAT_HELPER (X, Y) X##Y
PX_CUDA_CALLABLE
#define PX_CUDA_CALLABLE
PX_DEBUG
#define PX_DEBUG 0
PX_DEBUG_CRT
#define PX_DEBUG_CRT 0
PX_DEPRECATED
#define PX_DEPRECATED
Alignment macros
PX_ALIGN_PREFIX and PX_ALIGN_SUFFIX can be used for type alignment instead of aligning individual variables as follows: PX_ALIGN_PREFIX(16) struct A { ... } PX_ALIGN_SUFFIX(16); This declaration style is parsed correctly by Visual Assist. Deprecated macro
To deprecate a function: Place PX_DEPRECATED at the start of the function header (leftmost word).
To deprecate a 'typedef', a 'struct' or a 'class': Place PX_DEPRECATED directly after the keywords ('typedef', 'struct', 'class').
Use these macro definitions to create warnings for deprecated functions #define PX_DEPRECATED __declspec(deprecated) // Microsoft #define PX_DEPRECATED __attribute__((deprecated())) // GCC
PX_DLL_EXPORT
#define PX_DLL_EXPORT PX_UNIX_EXPORT
PX_DLL_IMPORT
#define PX_DLL_IMPORT
PX_DUMMY_SYMBOL
#define PX_DUMMY_SYMBOL
PX_EMSCRIPTEN
#define PX_EMSCRIPTEN 0
PX_ENABLE_ASSERTS
#define PX_ENABLE_ASSERTS 0
Assert macro
PX_EPS_F32
#define PX_EPS_F32 FLT_EPSILON
PX_EPS_F64
#define PX_EPS_F64 DBL_EPSILON
PX_EPS_REAL
#define PX_EPS_REAL PX_EPS_F32
Referenced by physx::aos::FEps(), physx::aos::V3Eps(), physx::aos::V3NormalizeSafe(), physx::aos::V4Eps(), and physx::aos::V4NormalizeSafe().
PX_FL
#define PX_FL __FILE__, __LINE__
Referenced by ExtGpu::PxStatelessKernelLauncher::launchKernel().
PX_FORCE_INLINE
#define PX_FORCE_INLINE inline
Force inline macro
PX_FOUNDATION_API
#define PX_FOUNDATION_API
PX_GCC
#define PX_GCC 0
PX_GCC_FAMILY
#define PX_GCC_FAMILY (PX_CLANG || PX_GCC)
family shortcuts
PX_IMPLEMENT_OUTPUT_ERROR
#define PX_IMPLEMENT_OUTPUT_ERROR
Value:
template<const int errorCode>                                                               \
static PX_NOINLINE bool outputError(int line, const char* message)                          \
{                                                                                           \
    return PxGetFoundation().error(PxErrorCode::Enum(errorCode), __FILE__, line, message);  \
}
PX_INFO
#define PX_INFO ::physx::PxErrorCode::eDEBUG_INFO, __FILE__, __LINE__
PX_INLINE
#define PX_INLINE inline
Inline macro
Referenced by PxBitMapBase< PxAllocator >::OR::operator()(), PxBitMapBase< PxAllocator >::AND::operator()(), and PxBitMapBase< PxAllocator >::XOR::operator()().
PX_INTEL_FAMILY
#define PX_INTEL_FAMILY (PX_X64 || PX_X86)
PX_LIBCPP
#define PX_LIBCPP 0
C++ standard library defines
PX_LINUX
#define PX_LINUX 0
PX_LINUX_FAMILY
#define PX_LINUX_FAMILY PX_LINUX
PX_MAX_BOUNDS_EXTENTS
#define PX_MAX_BOUNDS_EXTENTS (PX_MAX_REAL * 0.25f)
Referenced by PxBounds3::empty(), PxBounds3::isValid(), PxBounds3::setEmpty(), and PxBounds3::setMaximal().
PX_MAX_F32
#define PX_MAX_F32 3.4028234663852885981170418348452e+38F
Referenced by Interpolation::PxSDFSampleImpl().
PX_MAX_F64
#define PX_MAX_F64 DBL_MAX
PX_MAX_I16
#define PX_MAX_I16 INT16_MAX
PX_MAX_I32
#define PX_MAX_I32 INT32_MAX
PX_MAX_I8
#define PX_MAX_I8 INT8_MAX
PX_MAX_REAL
#define PX_MAX_REAL PX_MAX_F32
Referenced by physx::aos::FMax(), physx::aos::FNegMax(), and PxContactStreamIterator::getMaxImpulse().
PX_MAX_U16
#define PX_MAX_U16 UINT16_MAX
PX_MAX_U32
#define PX_MAX_U32 UINT32_MAX
Referenced by PxPhysics::createAggregate().
PX_MAX_U8
#define PX_MAX_U8 UINT8_MAX
Referenced by PxVehicleCopyDynamicsMap::PxVehicleCopyDynamicsMap().
PX_MIN_I16
#define PX_MIN_I16 INT16_MIN
PX_MIN_I32
#define PX_MIN_I32 INT32_MIN
PX_MIN_I8
#define PX_MIN_I8 INT8_MIN
PX_MIN_U16
#define PX_MIN_U16 UINT16_MIN
PX_MIN_U32
#define PX_MIN_U32 UINT32_MIN
PX_MIN_U8
#define PX_MIN_U8 UINT8_MIN
PX_NEON
#define PX_NEON 0
PX_NOALIAS
#define PX_NOALIAS
Noalias macro
PX_NOCOPY
#define PX_NOCOPY (Class)
Value:
protected:                  \
    Class(const Class&);    \
    Class& operator=(const Class&);
PX_NOINLINE
#define PX_NOINLINE
Noinline macro
PX_NORMALIZATION_EPSILON
#define PX_NORMALIZATION_EPSILON float(1e-20f)
Referenced by PxVec3T< float >::normalizeFast(), and PxVec3T< float >::normalizeSafe().
PX_NVTX
#define PX_NVTX 0
PX_OFFSET_OF
#define PX_OFFSET_OF (X, Y) offsetof(X, Y)
PX_OFFSET_OF_RT
#define PX_OFFSET_OF_RT (Class, Member) (reinterpret_cast<size_t>(&reinterpret_cast<Class*>(PX_OFFSETOF_BASE)->Member) - size_t(PX_OFFSETOF_BASE))
PX_OFFSETOF_BASE
#define PX_OFFSETOF_BASE 0x100
PX_OSX
#define PX_OSX 0
PX_OVERRIDE
#define PX_OVERRIDE
Override macro
PX_P64_FAMILY
#define PX_P64_FAMILY (PX_X64 || PX_A64)
PX_PHYSICS_VERSION
#define PX_PHYSICS_VERSION ((PX_PHYSICS_VERSION_MAJOR<<24) + (PX_PHYSICS_VERSION_MINOR<<16) + (PX_PHYSICS_VERSION_BUGFIX<<8) + 0)
The constant PX_PHYSICS_VERSION is used when creating certain PhysX module objects. This is to ensure that the application is using the same header version as the library was built with.
PX_PHYSICS_VERSION_BUGFIX
#define PX_PHYSICS_VERSION_BUGFIX 0
PX_PHYSICS_VERSION_MAJOR
#define PX_PHYSICS_VERSION_MAJOR 5
PX_PHYSICS_VERSION_MINOR
#define PX_PHYSICS_VERSION_MINOR 1
PX_POP_PACK
#define PX_POP_PACK
PX_PPC
#define PX_PPC 0
PX_PRIu64
#define PX_PRIu64 PRIu64
PX_PROFILE
#define PX_PROFILE 0
PX_PUSH_PACK_DEFAULT
#define PX_PUSH_PACK_DEFAULT
Pack macros - disabled on SPU because they are not supported
PX_RESTRICT
#define PX_RESTRICT __restrict
Restrict macro
Referenced by PxPrefetchLine().
PX_SIGN_BITMASK
#define PX_SIGN_BITMASK 0x80000000
Referenced by PxBitMapBase< PxAllocator >::getWordCount(), PxBitMapBase< PxAllocator >::isInUserMemory(), physx::PxArray< void *, Alloc >::isInUserMemory(), physx::PxArray< void *, Alloc >::PxArray(), PxBitMapBase< PxAllocator >::PxBitMapBase(), and PxBitMapBase< PxAllocator >::setWords().
PX_SORT_PARANOIA
#define PX_SORT_PARANOIA PX_DEBUG
PX_SSE2
#define PX_SSE2 0
PX_STRINGIZE
#define PX_STRINGIZE (X) PX_STRINGIZE_HELPER(X)
PX_STRINGIZE_HELPER
#define PX_STRINGIZE_HELPER (X) #X
PX_SUPPORT_EXTERN_TEMPLATE
#define PX_SUPPORT_EXTERN_TEMPLATE (PX_VC != 11)
PX_SUPPORT_GPU_PHYSX
#define PX_SUPPORT_GPU_PHYSX ((PX_X64 && (PX_WINDOWS_FAMILY || PX_LINUX)) || (PX_A64 && PX_LINUX))
PX_SWITCH
#define PX_SWITCH 0
PX_UNIX_EXPORT
#define PX_UNIX_EXPORT
PX_UNIX_FAMILY
#define PX_UNIX_FAMILY (PX_LINUX_FAMILY || PX_APPLE_FAMILY)
PX_VC
#define PX_VC 0
Compiler defines, see http://sourceforge.net/p/predef/wiki/Compilers/ Operating system defines, see http://sourceforge.net/p/predef/wiki/OperatingSystems/ Architecture defines, see http://sourceforge.net/p/predef/wiki/Architectures/ SIMD defines define anything not defined on this platform to 0
PX_VMX
#define PX_VMX 0
PX_WARN
#define PX_WARN ::physx::PxErrorCode::eDEBUG_WARNING, __FILE__, __LINE__
PX_WARN_ONCE
#define PX_WARN_ONCE (string) ((void)0)
PX_WARN_ONCE_IF
#define PX_WARN_ONCE_IF (condition, string) ((void)0)
PX_WEAK_SYMBOL
#define PX_WEAK_SYMBOL
PX_WIN32
#define PX_WIN32 0
PX_WIN64
#define PX_WIN64 0
PX_WINDOWS
#define PX_WINDOWS (PX_WINDOWS_FAMILY && !PX_ARM_FAMILY)
PX_WINDOWS_FAMILY
#define PX_WINDOWS_FAMILY (PX_WIN32 || PX_WIN64)
PX_X64
#define PX_X64 0
PX_X86
#define PX_X86 0
USE_VOLATILE_UNION
#define USE_VOLATILE_UNION
Referenced by PxUnionCast().
Typedef Documentation
PxBitAndByte
typedef PxBitAndDataT<PxU8, 0x80> PxBitAndByte
PxBitAndDword
typedef PxBitAndDataT<PxU32, 0x80000000> PxBitAndDword
PxBitAndWord
typedef PxBitAndDataT<PxU16, 0x8000> PxBitAndWord
PxF32
typedef float PxF32
PxF64
typedef double PxF64
PxI16
typedef int16_t PxI16
PxI32
typedef int32_t PxI32
PxI64
typedef int64_t PxI64
PxI8
typedef int8_t PxI8
PxIntBool
typedef PxI32 PxIntBool
PxMat33 [1/2]
typedef PxMat33T<float> PxMat33
PxMat33 [2/2]
typedef PxMat33T<float> PxMat33
PxMat33d
typedef PxMat33T<double> PxMat33d
PxMat34 [1/2]
typedef PxMat34T<float> PxMat34
PxMat34 [2/2]
typedef PxMat34T<float> PxMat34
PxMat34d
typedef PxMat34T<double> PxMat34d
PxMat44 [1/2]
typedef PxMat44T<float> PxMat44
PxMat44 [2/2]
typedef PxMat44T<float> PxMat44
PxMat44d
typedef PxMat44T<double> PxMat44d
PxQuat [1/2]
typedef PxQuatT<float> PxQuat
PxQuat [2/2]
typedef PxQuatT<float> PxQuat
PxQuatd
typedef PxQuatT<double> PxQuatd
PxReal
typedef float PxReal
PxTransform [1/2]
typedef PxTransformT<float> PxTransform
PxTransform [2/2]
typedef PxTransformT<float> PxTransform
PxTransform32
typedef PxTransformPadded PxTransform32
PxTransformd
typedef PxTransformT<double> PxTransformd
PxU16
typedef uint16_t PxU16
PxU32 [1/2]
typedef uint32_t PxU32
files to always include
PxU32 [2/2]
typedef uint32_t PxU32
PxU64
typedef uint64_t PxU64
PxU8
typedef uint8_t PxU8
PxVec2 [1/2]
typedef PxVec2T<float> PxVec2
PxVec2 [2/2]
typedef PxVec2T<float> PxVec2
PxVec2d
typedef PxVec2T<double> PxVec2d
PxVec3 [1/2]
typedef PxVec3T<float> PxVec3
PxVec3 [2/2]
typedef PxVec3T<float> PxVec3
PxVec3d
typedef PxVec3T<double> PxVec3d
PxVec3p
typedef PxVec3Padded PxVec3p
PxVec4 [1/2]
typedef PxVec4T<float> PxVec4
PxVec4 [2/2]
typedef PxVec4T<float> PxVec4
PxVec4d
typedef PxVec4T<double> PxVec4d
Enumeration Type Documentation
PxEMPTY
enum PxEMPTY
enum for empty constructor tag
Enumerator
PxEmpty
PxIDENTITY
enum PxIDENTITY
enum for identity constructor flag for quaternions, transforms, and matrices
Enumerator
PxIdentity
PxZERO
enum PxZERO
enum for zero constructor tag for vectors and matrices
Enumerator
PxZero
Function Documentation
basisExtent()
PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::basisExtent (const PxVec3 & center, const PxMat33 & basis, const PxVec3 & extent) static
Construct from center, extent, and (not necessarily orthogonal) basis.
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, PxAbs(), PxBounds3::PxBounds3(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by PxBounds3::poseExtent(), and PxBounds3::transformFast().
boundsOfPoints()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3 PxBounds3::boundsOfPoints (const PxVec3 & v0, const PxVec3 & v1) static
returns the AABB containing v0 and v1.
Parameters
v0 first point included in the AABB.
v1 second point included in the AABB.
References PxVec3T< Type >::maximum(), PxVec3T< Type >::minimum(), and PxBounds3::PxBounds3().
centerExtents()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3 PxBounds3::centerExtents (const PxVec3 & center, const PxVec3 & extent) static
returns the AABB from center and extents vectors.
Parameters
center Center vector
extent Extents vector
References PxBounds3::PxBounds3().
Referenced by PxBounds3::scaleFast().
closestPoint()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::closestPoint (const PxVec3 & p) const
Finds the closest point in the box to the point p. If p is contained, this will be p, otherwise it will be the closest point on the surface of the box.
References PxBounds3::maximum, PxVec3T< Type >::maximum(), PxBounds3::minimum, and PxVec3T< Type >::minimum().
contains()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::contains (const PxVec3 & v) const
indicates if these bounds contain v.
Parameters
v Point to test against bounds.
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, PX_ASSERT, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
empty()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3 PxBounds3::empty () static
Return empty bounds.
References PX_MAX_BOUNDS_EXTENTS, and PxBounds3::PxBounds3().
Referenced by PxSDFDesc::PxSDFDesc().
fattenFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::fattenFast (float distance)
fattens the AABB in all 3 dimensions by the given distance.
Calling this method for empty bounds leads to undefined behavior. Use fattenSafe() instead.
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, PX_ASSERT, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by PxBounds3::fattenSafe().
fattenSafe()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::fattenSafe (float distance)
fattens the AABB in all 3 dimensions by the given distance.
This version is safe to call for empty bounds.
References PxBounds3::fattenFast(), PxBounds3::isEmpty(), PxBounds3::isValid(), and PX_ASSERT.
getCenter() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::getCenter () const
returns the center of this axis aligned box.
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, and PX_ASSERT.
Referenced by PxBounds3::scaleFast(), and PxBounds3::transformFast().
getCenter() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxBounds3::getCenter (uint32_t axis) const
get component of the box's center along a given axis
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, and PX_ASSERT.
getDimensions()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::getDimensions () const
returns the dimensions (width/height/depth) of this axis aligned box.
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, and PX_ASSERT.
Referenced by PxBounds3::getExtents().
getExtents() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxBounds3::getExtents (uint32_t axis) const
get component of the box's extents along a given axis
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, and PX_ASSERT.
Referenced by PxBounds3::transformFast().
getExtents() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3 PxBounds3::getExtents () const
returns the extents, which are half of the width/height/depth.
References PxBounds3::getDimensions(), PxBounds3::isValid(), and PX_ASSERT.
Referenced by PxBounds3::scaleFast().
include() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::include (const PxVec3 & v)
expands the volume to include v
Parameters
v Point to expand to.
References PxBounds3::isValid(), PxBounds3::maximum, PxVec3T< Type >::maximum(), PxBounds3::minimum, PxVec3T< Type >::minimum(), and PX_ASSERT.
include() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::include (const PxBounds3 & b)
expands the volume to include b.
Parameters
b Bounds to perform union with.
References PxBounds3::isValid(), PxBounds3::maximum, PxVec3T< Type >::maximum(), PxBounds3::minimum, PxVec3T< Type >::minimum(), and PX_ASSERT.
intersects()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::intersects (const PxBounds3 & b) const
indicates whether the intersection of this and b is empty or not.
Parameters
b Bounds to test for intersection.
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, PX_ASSERT, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
intersects1D()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::intersects1D (const PxBounds3 & a, uint32_t axis) const
computes the 1D-intersection between two AABBs, on a given axis.
Parameters
a the other AABB
axis the axis (0, 1, 2)
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, and PX_ASSERT.
isEmpty()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isEmpty () const
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, PX_ASSERT, and PxVec3T< Type >::x.
Referenced by PxBounds3::fattenSafe(), PxBounds3::scaleSafe(), and PxBounds3::transformSafe().
isFinite()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isFinite () const
checks that the AABB values are not NaN
References PxVec3T< Type >::isFinite(), PxBounds3::maximum, and PxBounds3::minimum.
Referenced by PxBounds3::isValid().
isInside()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isInside (const PxBounds3 & box) const
checks a box is inside another box.
Parameters
box the other AABB
References PxBounds3::isValid(), PxBounds3::maximum, PxBounds3::minimum, PX_ASSERT, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
isValid()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxBounds3::isValid () const
checks that the AABB values describe a valid configuration.
References PxBounds3::isFinite(), PxBounds3::maximum, PxBounds3::minimum, PX_MAX_BOUNDS_EXTENTS, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by PxBounds3::contains(), PxBounds3::fattenFast(), PxBounds3::fattenSafe(), PxBounds3::getCenter(), PxBounds3::getDimensions(), PxBounds3::getExtents(), PxBounds3::include(), PxBounds3::intersects(), PxBounds3::intersects1D(), PxBounds3::isEmpty(), PxBounds3::isInside(), PxSceneDesc::isValid(), PxBounds3::scaleFast(), PxBounds3::scaleSafe(), PxBounds3::transformFast(), and PxBounds3::transformSafe().
operator*() [1/5]
template<class Type > PX_INLINE PxMat34T<Type> operator* (const PxMat33T< Type > & a, const PxMat34T< Type > & b)
Multiply a*b, a is extended.
References PxMat34T< Type >::m, and PxMat34T< Type >::p.
operator*() [2/5]
template<class Type > static PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec2T<Type> operator* (Type f, const PxVec2T< Type > & v) static
References PxVec2T< Type >::x, and PxVec2T< Type >::y.
operator*() [3/5]
template<class Type > static PX_CUDA_CALLABLE PX_INLINE PxVec4T<Type> operator* (Type f, const PxVec4T< Type > & v) static
References PxVec4T< Type >::w, PxVec4T< Type >::x, PxVec4T< Type >::y, and PxVec4T< Type >::z.
operator*() [4/5]
template<class Type > PX_CUDA_CALLABLE PX_INLINE PxMat33T<Type> operator* (Type scalar, const PxMat33T< Type > & m)
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, and PxMat33T< Type >::column2.
operator*() [5/5]
template<class Type > static PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3T<Type> operator* (Type f, const PxVec3T< Type > & v) static
References PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
operator+()
template<typename T > PX_INLINE PxStrideIterator<T> operator+ (int i, PxStrideIterator< T > it)
Addition operator.
poseExtent()
PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::poseExtent (const PxTransform & pose, const PxVec3 & extent) static
Construct from pose and extent.
References PxBounds3::basisExtent(), PxTransformT< Type >::p, and PxTransformT< Type >::q.
PX_ALIGN_PREFIX()
PX_ALIGN_PREFIX (16)
A generic padded & aligned transform class.
An bundle of four integer vectors with 4 components each.
This can be used for safe faster loads & stores, and faster address computations (the default PxTransformT often generating imuls for this otherwise). Padding bytes can be reused to store useful data if needed.
PX_COMPILE_TIME_ASSERT() [1/4]
PX_COMPILE_TIME_ASSERT (sizeof(PxTransformPadded) = =32)
PX_COMPILE_TIME_ASSERT() [2/4]
PX_COMPILE_TIME_ASSERT (0 = =(sizeof(PxMat34Padded)==16))
PX_COMPILE_TIME_ASSERT() [3/4]
PX_COMPILE_TIME_ASSERT (sizeof(PxVec3Padded) = =16)
PX_COMPILE_TIME_ASSERT() [4/4]
PX_COMPILE_TIME_ASSERT (PX_OFFSET_OF(PxPackValidation, a) = =8)
PX_UNUSED()
template<class T > PX_CUDA_CALLABLE PX_INLINE void PX_UNUSED (T const &)
Referenced by PxContactSet::getInternalFaceIndex0(), PxVehicleAckermannParams::isValid(), PxVehicleFourWheelDriveDifferentialLegacyParams::isValid(), PxVehicleConstraintConnector::onComShift(), PxVehicleConstraintConnector::onOriginShift(), PxUserAllocated::operator delete(), PxUserAllocated::operator delete [](), PxQueryFilterCallback::postFilter(), PxHitBuffer< PxSweepHit >::processTouches(), PxInitVehicleExtension(), PxBitMapBase< PxAllocator >::resize(), PxVehicleBrakeCommandResponseParams::transformAndScale(), PxVehicleDirectDriveThrottleCommandResponseParams::transformAndScale(), PxVehicleSteerCommandResponseParams::transformAndScale(), PxVehiclePhysXSuspensionLimitConstraintParams::transformAndScale(), PxVehicleWheelParams::transformAndScale(), PxVehiclePhysXRoadGeometryQueryParams::transformAndScale(), PxVehicleClutchCommandResponseParams::transformAndScale(), PxVehicleAckermannParams::transformAndScale(), PxVehicleSuspensionStateCalculationParams::transformAndScale(), PxVehicleTireForceParams::transformAndScale(), PxVehicleClutchParams::transformAndScale(), PxVehicleSuspensionComplianceParams::transformAndScale(), PxVehicleSuspensionForceParams::transformAndScale(), PxVehicleEngineParams::transformAndScale(), PxVehicleSuspensionForceLegacyParams::transformAndScale(), PxVehicleGearboxParams::transformAndScale(), PxVehicleAntiRollForceParams::transformAndScale(), PxVehicleAutoboxParams::transformAndScale(), PxVehicleTireSlipParams::transformAndScale(), PxVehicleFourWheelDriveDifferentialLegacyParams::transformAndScale(), PxVehicleTireAxisStickyParams::transformAndScale(), PxVehicleMultiWheelDriveDifferentialParams::transformAndScale(), PxVehicleFourWheelDriveDifferentialParams::transformAndScale(), PxVehicleTankDriveDifferentialParams::transformAndScale(), PxVehiclePhysXConstraintComponent::update(), PxVehiclePhysXRoadGeometrySceneQueryComponent::update(), PxVehiclePhysXActorBeginComponent::update(), PxVehicleDirectDriveCommandResponseComponent::update(), PxVehiclePVDComponent::update(), PxVehiclePhysXActorEndComponent::update(), PxVehicleDirectDriveActuationStateComponent::update(), PxVehicleDirectDrivetrainComponent::update(), PxVehicleEngineDriveCommandResponseComponent::update(), PxVehicleMultiWheelDriveDifferentialStateComponent::update(), PxVehicleFourWheelDriveDifferentialStateComponent::update(), PxVehicleTankDriveDifferentialStateComponent::update(), PxVehicleLegacyFourWheelDriveDifferentialStateComponent::update(), PxVehicleEngineDriveActuationStateComponent::update(), PxVehicleEngineDrivetrainComponent::update(), PxVehicleConstraintConnector::updatePvdProperties(), physx::aos::V4ConvertToU32VSaturate(), vehicleConstraintSolverPrep(), and visualiseVehicleConstraint().
PxAbs() [1/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAbs (float a)
abs returns the absolute value of its argument.
References intrinsics::abs().
Referenced by PxVec3T< float >::abs(), PxBounds3::basisExtent(), Gu::ContactBuffer::contact(), PxPlane::contains(), physx::aos::FAbs(), PxVec2T< Type >::isNormalized(), PxVec3T< float >::isNormalized(), PxVec4T< float >::isNormalized(), PxQuatT< float >::isSane(), PxQuatT< float >::isUnit(), PxVehicleSteerCommandResponseParams::isValid(), PxVehicleMultiWheelDriveDifferentialParams::isValid(), normalToTangents(), PxComputeBasisVectors(), PxEllipseClamp(), PxEquals(), PxQuatT< float >::PxQuatT(), PxVehicleShiftOrigin(), and PxQuatT< float >::toRadiansAndUnitAxis().
PxAbs() [2/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAbs (double a)
abs returns the absolute value of its argument.
PxAbs() [3/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE int32_t PxAbs (int32_t a)
abs returns the absolute value of its argument.
References abs().
PxAcos() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAcos (float f)
Arccosine. Returns angle between 0 and PI in radians Unit: Radians.
References PxClamp().
Referenced by PxQuatT< float >::getAngle().
PxAcos() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAcos (double f)
Arccosine. Returns angle between 0 and PI in radians Unit: Radians.
References PxClamp().
PxAsin() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAsin (float f)
Arcsine. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
References PxClamp().
PxAsin() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAsin (double f)
Arcsine. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
References PxClamp().
PxAtan() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAtan (float a)
ArcTangent. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
PxAtan() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAtan (double a)
ArcTangent. Returns angle between -PI/2 and PI/2 in radians Unit: Radians.
PxAtan2() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxAtan2 (float x, float y)
Arctangent of (x/y) with correct sign. Returns angle between -PI and PI in radians Unit: Radians.
Referenced by PxComputeAngle(), PxLog(), and PxQuatT< float >::toRadiansAndUnitAxis().
PxAtan2() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxAtan2 (double x, double y)
Arctangent of (x/y) with correct sign. Returns angle between -PI and PI in radians Unit: Radians.
PxBounds3()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxBounds3::PxBounds3 (const PxVec3 & minimum, const PxVec3 & maximum)
Construct from two bounding points.
PxCeil()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxCeil (float a)
PxClamp()
template<class T > PX_CUDA_CALLABLE PX_FORCE_INLINE T PxClamp (T v, T lo, T hi)
Clamps v to the range [hi,lo].
References PX_ASSERT, PxMax(), and PxMin().
Referenced by PxAcos(), and PxAsin().
PxCos() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxCos (float a)
Cosine of an angle (Unit: Radians)
References intrinsics::cos().
Referenced by operator<<(), and PxSinCos().
PxCos() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxCos (double a)
Cosine of an angle (Unit: Radians)
References cos().
PxCreateFoundation()
PX_C_EXPORT PX_FOUNDATION_API physx::PxFoundation* PX_CALL_CONV PxCreateFoundation (physx::PxU32 version, physx::PxAllocatorCallback & allocator, physx::PxErrorCallback & errorCallback)
Creates an instance of the foundation class.
The foundation class is needed to initialize higher level SDKs. There may be only one instance per process. Calling this method after an instance has been created already will result in an error message and NULL will be returned.
Parameters
version Version number we are expecting (should be PX_PHYSICS_VERSION)
allocator User supplied interface for allocating memory(see PxAllocatorCallback)
errorCallback User supplied interface for reporting errors and displaying messages(see PxErrorCallback)
Returns
Foundation instance on success, NULL if operation failed
See also
PxFoundation
PxDecFoundationRefCount()
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxDecFoundationRefCount ()
Decrement the ref count of PxFoundation.
Referenced by PxCloseVehicleExtension().
PxDegToRad()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxF32 PxDegToRad (const PxF32 a)
Converts degrees to radians.
PxEquals()
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxEquals (float a, float b, float eps)
References PxAbs().
PxExp()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxExp (float a)
PxFloor()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxFloor (float a)
PxGetAllocatorCallback()
PX_C_EXPORT PX_FOUNDATION_API physx::PxAllocatorCallback* PX_CALL_CONV PxGetAllocatorCallback ()
Get the allocator callback.
Referenced by PxSerializerDefaultAdapter< T >::exportData().
PxGetAssertHandler()
PX_FOUNDATION_API PX_DEPRECATED PxAssertHandler& PxGetAssertHandler ()
PxGetBroadcastAllocator()
PX_C_EXPORT PX_FOUNDATION_API physx::PxAllocatorCallback* PX_CALL_CONV PxGetBroadcastAllocator ()
Get the broadcasting allocator callback.
Referenced by PxAllocator::allocate(), PxReflectionAllocator< T >::allocate(), PxAllocator::deallocate(), and PxReflectionAllocator< T >::deallocate().
PxGetBroadcastError()
PX_C_EXPORT PX_FOUNDATION_API physx::PxErrorCallback* PX_CALL_CONV PxGetBroadcastError ()
Get the broadcasting error callback.
PxGetErrorCallback()
PX_C_EXPORT PX_FOUNDATION_API physx::PxErrorCallback* PX_CALL_CONV PxGetErrorCallback ()
Get the error callback.
PxGetFoundation()
PX_C_EXPORT PX_FOUNDATION_API physx::PxFoundation& PX_CALL_CONV PxGetFoundation ()
Retrieves the Foundation SDK after it has been created.
Note
The behavior of this method is undefined if the foundation instance has not been created already.
See also
PxCreateFoundation()
Referenced by ExtGpu::_testLaunch(), PxReflectionAllocator< T >::getName(), ExtGpu::outputKernelLaunchDebugInfo(), ExtGpu::outputKernelLaunchError(), PxInitVehicleExtension(), and PxVehicleComponentSequence::update().
PxGetProfilerCallback()
PX_C_EXPORT PX_FOUNDATION_API physx::PxProfilerCallback* PX_CALL_CONV PxGetProfilerCallback ()
Get the callback that will be used for all profiling.
PxGetWarnOnceTimeStamp()
PX_C_EXPORT PX_FOUNDATION_API physx::PxU32 PX_CALL_CONV PxGetWarnOnceTimeStamp ()
Get the warn once timestamp.
PxIncFoundationRefCount()
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxIncFoundationRefCount ()
Increment the ref count of PxFoundation.
Referenced by PxInitVehicleExtension().
PxIsFinite() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxIsFinite (float f)
returns true if the passed number is a finite floating point number as opposed to INF, NAN, etc.
References intrinsics::isFinite().
Referenced by PxExtendedVec3::isFinite(), PxQuatT< float >::isFinite(), PxVec2T< Type >::isFinite(), PxVec3T< float >::isFinite(), PxVec4T< float >::isFinite(), physx::aos::isFiniteFloatV(), physx::aos::isFiniteVec3V(), physx::aos::isFiniteVec4V(), PxVehicleDirectDriveThrottleCommandResponseParams::isValid(), PxSphereGeometry::isValid(), PxCapsuleGeometry::isValid(), PxHeightFieldGeometry::isValid(), PxJointLimitParameters::isValid(), PxD6JointDrive::isValid(), PxJointLinearLimit::isValid(), PxJointLinearLimitPair::isValid(), PxJointAngularLimitPair::isValid(), PxVehicleAntiRollForceParams::isValid(), PxJointLimitCone::isValid(), PxJointLimitPyramid::isValid(), PxMassProperties::operator*(), PxMassProperties::PxMassProperties(), PxMassProperties::sum(), and PxMassProperties::translateInertia().
PxIsFinite() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool PxIsFinite (double f)
returns true if the passed number is a finite floating point number as opposed to INF, NAN, etc.
References intrinsics::isFinite().
PxLog()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxLog (float x)
PxMakeIterator() [1/2]
template<typename T > PX_INLINE PxStrideIterator<T> PxMakeIterator (T * ptr, PxU32 stride = sizeof(T))
Stride iterator factory function which infers the iterator type.
PxMakeIterator() [2/2]
template<typename T > PX_INLINE PxStrideIterator<const T> PxMakeIterator (const T * ptr, PxU32 stride = sizeof(T))
Stride iterator factory function which infers the iterator type.
PxMax() [1/2]
template<class T > PX_CUDA_CALLABLE PX_FORCE_INLINE T PxMax (T a, T b)
The return value is the greater of the two specified values.
Referenced by PxBitMapBase< PxAllocator >::combine2(), PxVec2T< Type >::maxElement(), PxVec3T< float >::maxElement(), PxVec2T< Type >::maximum(), PxVec4T< float >::maximum(), PxVec3T< float >::maximum(), PxClamp(), PxEllipseClamp(), and physx::PxOrder().
PxMax() [2/2]
template<> PX_CUDA_CALLABLE PX_FORCE_INLINE float PxMax (float a, float b)
overload for float to use fsel on xbox
References intrinsics::selectMax().
PxMedian3()
template<class T , class Predicate > PX_INLINE void PxMedian3 (T * elements, int32_t first, int32_t last, Predicate & compare)
References PxSwap().
Referenced by PxPartition().
PxMemCopy()
PX_FORCE_INLINE void* PxMemCopy (void * dest, const void * src, PxU32 count)
Copies the bytes of one memory block to another. The memory blocks must not overlap.
Note
Use PxMemMove if memory blocks overlap.
Parameters
dest Pointer to block of memory to copy to.
src Pointer to block of memory to copy from.
count Number of bytes to copy.
Returns
Pointer to destination memory block
References memCopy().
Referenced by PxVehicleCommandNonLinearResponseParams::addResponse(), PxContactPair::bufferContacts(), PxBitMapBase< PxAllocator >::copy(), PxSerializerDefaultAdapter< T >::exportData(), PxBitMapBase< PxAllocator >::extend(), PxFixedSizeLookupTable< eMAX_NB_ENGINE_TORQUE_CURVE_ENTRIES >::operator=(), PxVehicleFixedSizeLookupTable< PxVec3T, 3 >::operator=(), PxFixedSizeLookupTable< eMAX_NB_ENGINE_TORQUE_CURVE_ENTRIES >::PxFixedSizeLookupTable(), and PxVehicleFixedSizeLookupTable< PxVec3T, 3 >::PxVehicleFixedSizeLookupTable().
PxMemMove()
PX_FORCE_INLINE void* PxMemMove (void * dest, const void * src, PxU32 count)
Copies the bytes of one memory block to another. The memory blocks can overlap.
Note
Use PxMemCopy if memory blocks do not overlap.
Parameters
dest Pointer to block of memory to copy to.
src Pointer to block of memory to copy from.
count Number of bytes to copy.
Returns
Pointer to destination memory block
References memMove().
PxMemSet()
PX_FORCE_INLINE void* PxMemSet (void * dest, PxI32 c, PxU32 count)
Sets the bytes of the provided buffer to the specified value.
Parameters
dest Pointer to block of memory to set to the specified value.
c Value to set the bytes of the block of memory to.
count Number of bytes to set to the specified value.
Returns
Pointer to memory block (same as input)
References memSet().
Referenced by PxBitMapBase< PxAllocator >::clear(), PxFixedSizeLookupTable< eMAX_NB_ENGINE_TORQUE_CURVE_ENTRIES >::clear(), PxVehicleFixedSizeLookupTable< PxVec3T, 3 >::clear(), PxBitMapBase< PxAllocator >::copy(), PxBitMapBase< PxAllocator >::extend(), PxArticulationJointDataRC::initData(), PxVehicleDifferentialNWData::PxVehicleDifferentialNWData(), and PxBitMapBase< PxAllocator >::resizeAndClear().
PxMemZero()
PX_FORCE_INLINE void* PxMemZero (void * dest, PxU32 count)
Sets the bytes of the provided buffer to zero.
Parameters
dest Pointer to block of memory to set zero.
count Number of bytes to set to zero.
Returns
Pointer to memory block (same as input)
References memZero().
Referenced by PxVehicleMatrixNN::PxVehicleMatrixNN(), PxVehicleVectorN::PxVehicleVectorN(), PxWheelQueryResult::PxWheelQueryResult(), PxVehicleClutchCommandResponseState::setToDefault(), PxVehicleRoadGeometryState::setToDefault(), PxVehicleAxleDescription::setToDefault(), PxVehicleWheelActuationState::setToDefault(), PxVehicleTireDirectionState::setToDefault(), PxVehiclePhysXRoadGeometryQueryState::setToDefault(), PxVehicleCommandState::setToDefault(), PxVehicleEngineDriveThrottleCommandResponseState::setToDefault(), PxVehiclePhysXActor::setToDefault(), PxVehicleTireSpeedState::setToDefault(), PxVehicleEngineState::setToDefault(), PxVehicleDirectDriveTransmissionCommandState::setToDefault(), PxVehicleTireSlipState::setToDefault(), PxVehicleWheelRigidBody1dState::setToDefault(), PxVehicleTireGripState::setToDefault(), PxVehicleEngineDriveTransmissionCommandState::setToDefault(), PxVehicleTireCamberAngleState::setToDefault(), PxVehicleSuspensionComplianceState::setToDefault(), PxVehiclePhysXConstraintState::setToDefault(), PxVehicleTankDriveTransmissionCommandState::setToDefault(), PxVehicleTireStickyState::setToDefault(), PxVehicleSuspensionForce::setToDefault(), PxVehicleDifferentialState::setToDefault(), PxVehicleTireForce::setToDefault(), PxVehicleAntiRollTorque::setToDefault(), PxVehicleWheelConstraintGroupState::setToDefault(), PxVehicleClutchSlipState::setToDefault(), and PxVehicleMultiWheelDriveDifferentialParams::setToDefault().
PxMin() [1/2]
template<class T > PX_CUDA_CALLABLE PX_FORCE_INLINE T PxMin (T a, T b)
The return value is the lesser of the two specified values.
Referenced by PxBitMapBase< PxAllocator >::combine1(), PxBitMapBase< PxAllocator >::combine2(), PxBitMapBase< PxAllocator >::count(), PxVec2T< Type >::minElement(), PxVec3T< float >::minElement(), PxVec2T< Type >::minimum(), PxVec4T< float >::minimum(), PxVec3T< float >::minimum(), PxClamp(), PxJointAngularLimitPair::PxJointAngularLimitPair(), PxJointLimitCone::PxJointLimitCone(), PxJointLimitPyramid::PxJointLimitPyramid(), PxJointLinearLimitPair::PxJointLinearLimitPair(), and physx::PxOrder().
PxMin() [2/2]
template<> PX_CUDA_CALLABLE PX_FORCE_INLINE float PxMin (float a, float b)
overload for float to use fsel on xbox
References intrinsics::selectMin().
PxPartition()
template<class T , class Predicate > PX_INLINE int32_t PxPartition (T * elements, int32_t first, int32_t last, Predicate & compare)
References PX_ASSERT, PxMedian3(), and PxSwap().
Referenced by PxSort().
PxPow()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxPow (float x, float y)
PxQuatT()
template<class Type> PX_CUDA_CALLABLE PX_INLINE PxQuatT< Type >::PxQuatT (const PxMat33T< Type > & m) explicit
Creates from orientation matrix.
Parameters
[in] m Rotation matrix to extract quaternion from.
PxRecipSqrt() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxRecipSqrt (float a)
reciprocal square root.
References intrinsics::recipSqrt().
Referenced by physx::aos::FRsqrt(), physx::aos::FRsqrtFast(), PxVec2T< Type >::getNormalized(), PxVec3T< float >::getNormalized(), PxVec4T< float >::getNormalized(), PxEllipseClamp(), PxExp(), PxQuatT< float >::toRadiansAndUnitAxis(), physx::aos::V3Rsqrt(), physx::aos::V3RsqrtFast(), physx::aos::V4Rsqrt(), and physx::aos::V4RsqrtFast().
PxRecipSqrt() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxRecipSqrt (double a)
reciprocal square root.
References sqrt().
PxSetAssertHandler()
PX_FOUNDATION_API PX_DEPRECATED void PxSetAssertHandler (PxAssertHandler & handler)
PxSetFoundationInstance()
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxSetFoundationInstance (physx::PxFoundation & foundation)
PxSetPhysXCommonDelayLoadHook()
PX_C_EXPORT PX_PHYSX_COMMON_API void PX_CALL_CONV PxSetPhysXCommonDelayLoadHook (const physx::PxDelayLoadHook * hook)
Sets delay load hook instance for PhysXCommon dll.
Parameters
[in] hook Delay load hook.
See also
PxDelayLoadHook
PxSetPhysXCookingDelayLoadHook()
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxSetPhysXCookingDelayLoadHook (const physx::PxDelayLoadHook * hook)
Sets delay load hook instance for PhysXCooking dll.
Parameters
[in] hook Delay load hook.
See also
PxDelayLoadHook
PxSetPhysXDelayLoadHook()
PX_C_EXPORT PX_PHYSX_CORE_API void PX_CALL_CONV PxSetPhysXDelayLoadHook (const physx::PxDelayLoadHook * hook)
Sets delay load hook instance for PhysX dll.
Parameters
[in] hook Delay load hook.
See also
PxDelayLoadHook
PxSetProfilerCallback()
PX_C_EXPORT PX_FOUNDATION_API void PX_CALL_CONV PxSetProfilerCallback (physx::PxProfilerCallback * profiler)
Set the callback that will be used for all profiling.
PxSign()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSign (float a)
References sign().
PxSign2()
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSign2 (float a, float eps = FLT_EPSILON)
PxSin() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSin (float a)
trigonometry – all angles are in radians.
Sine of an angle (Unit: Radians)
References intrinsics::sin().
Referenced by operator<<(), and PxSinCos().
PxSin() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxSin (double a)
Sine of an angle (Unit: Radians)
References sin().
PxSinCos() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxSinCos (const PxF32 a, PxF32 & sin, PxF32 & cos)
compute sine and cosine at the same time
References cos(), PxCos(), PxSin(), and sin().
Referenced by PxQuatT< float >::PxQuatT().
PxSinCos() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxSinCos (const double a, double & sin, double & cos)
compute sine and cosine at the same time
References cos(), PxCos(), PxSin(), and sin().
PxSmallSort()
template<class T , class Predicate > PX_INLINE void PxSmallSort (T * elements, int32_t first, int32_t last, Predicate & compare)
References PxSwap().
Referenced by PxSort().
PxSort() [1/3]
template<class T , class Predicate , class PxAllocator > void PxSort (T * elements, uint32_t count, const Predicate & compare, const PxAllocator & inAllocator, const uint32_t initialStackSize = 32)
Sorts an array of objects in ascending order, assuming that the predicate implements the < operator:
See also
PxLess, PxGreater
References PxStack< PxAllocator >::empty(), PxStack< PxAllocator >::pop(), PxStack< PxAllocator >::push(), PX_ALLOCA, PX_ASSERT, PxPartition(), and PxSmallSort().
Referenced by physx::PxPoolBase< T, Alloc >::disposeElements(), and PxSort().
PxSort() [2/3]
template<class T , class Predicate > void PxSort (T * elements, uint32_t count, const Predicate & compare)
References PxSort().
PxSort() [3/3]
template<class T > void PxSort (T * elements, uint32_t count)
References PxSort().
PxSqr()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxF32 PxSqr (const PxF32 a)
square of the argument
Referenced by PxEllipseClamp().
PxSqrt() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxSqrt (float a)
Square root.
References intrinsics::sqrt().
Referenced by physx::aos::FSqrt(), PxSparseGridParams::getSqrt3dx(), PxExtendedVec3::magnitude(), PxVec2T< Type >::magnitude(), PxVec3T< float >::magnitude(), PxVec4T< float >::magnitude(), PxQuatT< float >::magnitude(), operator<<(), PxExp(), PxQuatT< float >::PxQuatT(), physx::aos::V3Length(), physx::aos::V3Normalize(), physx::aos::V3NormalizeFast(), physx::aos::V3NormalizeSafe(), physx::aos::V4Length(), and physx::aos::V4Sqrt().
PxSqrt() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxSqrt (double a)
Square root.
References sqrt().
PxTan() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE float PxTan (float a)
Tangent of an angle. Unit: Radians.
PxTan() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE double PxTan (double a)
Tangent of an angle. Unit: Radians.
PxTransformT()
template<class Type> PX_CUDA_CALLABLE PX_FORCE_INLINE PxTransformT< Type >::PxTransformT (const PxMat44T< Type > & m) explicit
PxUnionCast()
template<class A , class B > PX_FORCE_INLINE A PxUnionCast (B b)
References USE_VOLATILE_UNION.
scaleFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::scaleFast (float scale)
scales the AABB.
Calling this method for empty bounds leads to undefined behavior. Use scaleSafe() instead.
Parameters
scale Factor to scale AABB by.
References PxBounds3::centerExtents(), PxBounds3::getCenter(), PxBounds3::getExtents(), PxBounds3::isValid(), and PX_ASSERT.
Referenced by PxBounds3::scaleSafe().
scaleSafe()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::scaleSafe (float scale)
scales the AABB.
This version is safe to call for empty bounds.
Parameters
scale Factor to scale AABB by.
References PxBounds3::isEmpty(), PxBounds3::isValid(), PX_ASSERT, and PxBounds3::scaleFast().
setEmpty()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::setEmpty ()
Sets empty to true.
References PxBounds3::maximum, PxBounds3::minimum, and PX_MAX_BOUNDS_EXTENTS.
setMaximal()
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxBounds3::setMaximal ()
Sets the bounds to maximum size [-PX_MAX_BOUNDS_EXTENTS, PX_MAX_BOUNDS_EXTENTS].
References PxBounds3::maximum, PxBounds3::minimum, and PX_MAX_BOUNDS_EXTENTS.
transformFast() [1/2]
PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformFast (const PxMat33 & matrix, const PxBounds3 & bounds) static
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
Calling this method for empty bounds leads to undefined behavior. Use transformSafe() instead.
Parameters
[in] matrix Transform to apply, can contain scaling as well
[in] bounds The bounds to transform.
References PxBounds3::basisExtent(), PxBounds3::getCenter(), PxBounds3::getExtents(), PxBounds3::isValid(), and PX_ASSERT.
Referenced by PxBounds3::transformSafe().
transformFast() [2/2]
PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformFast (const PxTransform & transform, const PxBounds3 & bounds) static
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
Calling this method for empty bounds leads to undefined behavior. Use transformSafe() instead.
Parameters
[in] transform Transform to apply, can contain scaling as well
[in] bounds The bounds to transform.
References PxBounds3::basisExtent(), PxBounds3::getCenter(), PxBounds3::getExtents(), PxBounds3::isValid(), PX_ASSERT, PxTransformT< Type >::q, and PxTransformT< Type >::transform().
transformSafe() [1/2]
PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformSafe (const PxMat33 & matrix, const PxBounds3 & bounds) static
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
This version is safe to call for empty bounds.
Parameters
[in] matrix Transform to apply, can contain scaling as well
[in] bounds The bounds to transform.
References PxBounds3::isEmpty(), PxBounds3::isValid(), PX_ASSERT, and PxBounds3::transformFast().
transformSafe() [2/2]
PX_CUDA_CALLABLE PX_INLINE PxBounds3 PxBounds3::transformSafe (const PxTransform & transform, const PxBounds3 & bounds) static
gets the transformed bounds of the passed AABB (resulting in a bigger AABB).
This version is safe to call for empty bounds.
Parameters
[in] transform Transform to apply, can contain scaling as well
[in] bounds The bounds to transform.
References PxBounds3::isEmpty(), PxBounds3::isValid(), PX_ASSERT, and PxBounds3::transformFast().
Variable Documentation
PxHalfPi
const float PxHalfPi = float(1.57079632679489661923) static
PxIntFalse
const PxIntBool PxIntFalse = 0 static
Referenced by PxBitMapBase< PxAllocator >::boundedTest().
PxIntTrue
const PxIntBool PxIntTrue = 1 static
PxInvPi
const float PxInvPi = float(0.31830988618379067154) static
PxInvSqrt2
const float PxInvSqrt2 = float(0.7071067811865476) static
PxInvTwoPi
const float PxInvTwoPi = float(0.15915494309189533577) static
PxPi
const float PxPi = float(3.141592653589793) static
Referenced by PxVehicleSteerCommandResponseParams::isValid(), PxVehicleSuspensionComplianceParams::isValid(), PxJointLimitCone::isValid(), PxJointLimitPyramid::isValid(), PxRenderOutput::outputCapsule(), PxLog(), PxMassProperties::PxMassProperties(), and PxQuatT< float >::toRadiansAndUnitAxis().
PxPiDivFour
const float PxPiDivFour = float(0.78539816339744830962) static
PxPiDivTwo
const float PxPiDivTwo = float(1.57079632679489661923) static
PxSqrt2
const float PxSqrt2 = float(1.4142135623730951) static
PxTwoPi
const float PxTwoPi = float(6.28318530717958647692) static
Referenced by operator<<(), and PxRenderOutput::outputCapsule().