physx::aos::internalWindowsSimd Namespace Reference
physx::aos::internalWindowsSimd Namespace Reference
Functions
PX_FORCE_INLINE __m128 m128_I2F (__m128i n)
PX_FORCE_INLINE __m128i m128_F2I (__m128 n)
PX_FORCE_INLINE PxU32 BAllTrue4_R (const BoolV a)
PX_FORCE_INLINE PxU32 BAllTrue3_R (const BoolV a)
PX_FORCE_INLINE PxU32 BAnyTrue4_R (const BoolV a)
PX_FORCE_INLINE PxU32 BAnyTrue3_R (const BoolV a)
PX_FORCE_INLINE PxU32 FiniteTestEq (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE bool hasZeroElementinFloatV (const FloatV a)
PX_FORCE_INLINE bool hasZeroElementInVec3V (const Vec3V a)
PX_FORCE_INLINE bool hasZeroElementInVec4V (const Vec4V a)
Variables
const PxU32 gMaskXYZ [4] = { 0xffffffff, 0xffffffff, 0xffffffff, 0 }
Function Documentation
BAllTrue3_R()
PX_FORCE_INLINE PxU32 physx::aos::internalWindowsSimd::BAllTrue3_R (const BoolV a)
BAllTrue4_R()
PX_FORCE_INLINE PxU32 physx::aos::internalWindowsSimd::BAllTrue4_R (const BoolV a)
BAnyTrue3_R()
PX_FORCE_INLINE PxU32 physx::aos::internalWindowsSimd::BAnyTrue3_R (const BoolV a)
BAnyTrue4_R()
PX_FORCE_INLINE PxU32 physx::aos::internalWindowsSimd::BAnyTrue4_R (const BoolV a)
FiniteTestEq()
PX_FORCE_INLINE PxU32 physx::aos::internalWindowsSimd::FiniteTestEq (const Vec4V a, const Vec4V b)
References physx::aos::FOne(), physx::aos::FZero(), and physx::aos::V4Sel().
hasZeroElementinFloatV()
PX_FORCE_INLINE bool physx::aos::internalWindowsSimd::hasZeroElementinFloatV (const FloatV a)
References ASSERT_ISVALIDFLOATV, and physx::aos::FZero().
hasZeroElementInVec3V()
PX_FORCE_INLINE bool physx::aos::internalWindowsSimd::hasZeroElementInVec3V (const Vec3V a)
References physx::aos::FZero().
hasZeroElementInVec4V()
PX_FORCE_INLINE bool physx::aos::internalWindowsSimd::hasZeroElementInVec4V (const Vec4V a)
References physx::aos::FZero().
m128_F2I()
PX_FORCE_INLINE __m128i physx::aos::internalWindowsSimd::m128_F2I (__m128 n)
Referenced by physx::aos::V4ConvertFromI32V().
m128_I2F()
PX_FORCE_INLINE __m128 physx::aos::internalWindowsSimd::m128_I2F (__m128i n)
Variable Documentation
gMaskXYZ
const PxU32 physx::aos::internalWindowsSimd::gMaskXYZ[4] = { 0xffffffff, 0xffffffff, 0xffffffff, 0 }