physx Namespace Reference
physx Namespace Reference
Vehicle2
Namespaces
aos
vehicle2
Classes
class PxArray
class PxPool
class PxPool2
class PxPoolBase
struct PxSListImpl
class PxSListT
Typedefs
typedef PxSListT PxSList
Functions
template<class T , class Alloc >
PX_INLINE void swap (PxArray< T, Alloc > &x, PxArray< T, Alloc > &y)
__declspec (align(PX_SLIST_ALIGNMENT)) class PxSListEntry
PX_INLINE char PxLittleEndian ()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU32 PxTo32 (PxU64 value)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU16 PxTo16 (PxU32 value)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU8 PxTo8 (PxU16 value)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU8 PxTo8 (PxU32 value)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU8 PxTo8 (PxI32 value)
PX_CUDA_CALLABLE PX_FORCE_INLINE PxI8 PxToI8 (PxU32 value)
template<typename T , size_t N>
char(& PxArraySizeHelper (T(&array)[N]))[N]
template<class T >
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxOrder (T &x, T &y)
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxOrder (PxReal &x, PxReal &y)
template<class T , class E1 >
PX_CUDA_CALLABLE PX_FORCE_INLINE void PxOrder (T &x, T &y, E1 &xe1, E1 &ye1)
PX_INLINE void PxDebugBreak ()
Typedef Documentation
PxSList
typedef PxSListT physx::PxSList
Function Documentation
__declspec()
physx::__declspec (align(PX_SLIST_ALIGNMENT))
References PX_ASSERT, and PX_SLIST_ALIGNMENT.
PxArraySizeHelper()
template<typename T , size_t N> char(& physx::PxArraySizeHelper (T(&) array[N]))[N]
Get number of elements in array
PxDebugBreak()
PX_INLINE void physx::PxDebugBreak ()
References PX_ASSERT.
PxLittleEndian()
PX_INLINE char physx::PxLittleEndian ()
PxOrder() [1/3]
template<class T > PX_CUDA_CALLABLE PX_FORCE_INLINE void physx::PxOrder (T & x, T & y)
Sort two elements using operator<
On return x will be the smaller of the two
References PxSwap().
PxOrder() [2/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE void physx::PxOrder (PxReal & x, PxReal & y)
References PxMax(), and PxMin().
PxOrder() [3/3]
template<class T , class E1 > PX_CUDA_CALLABLE PX_FORCE_INLINE void physx::PxOrder (T & x, T & y, E1 & xe1, E1 & ye1)
Sort two elements using operator< and also keep order of any extra data
References swap().
PxTo16()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU16 physx::PxTo16 (PxU32 value)
References PX_ASSERT.
PxTo32()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU32 physx::PxTo32 (PxU64 value)
References PX_ASSERT.
PxTo8() [1/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU8 physx::PxTo8 (PxU16 value)
References PX_ASSERT.
PxTo8() [2/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU8 physx::PxTo8 (PxU32 value)
References PX_ASSERT.
PxTo8() [3/3]
PX_CUDA_CALLABLE PX_FORCE_INLINE PxU8 physx::PxTo8 (PxI32 value)
References PX_ASSERT.
PxToI8()
PX_CUDA_CALLABLE PX_FORCE_INLINE PxI8 physx::PxToI8 (PxU32 value)
References PX_ASSERT.
swap()
template<class T , class Alloc > PX_INLINE void physx::swap (PxArray< T, Alloc > & x, PxArray< T, Alloc > & y)
References physx::PxArray< T, Alloc >::swap().
Referenced by PxOrder().