physx::aos::vecMathTests Namespace Reference
physx::aos::vecMathTests Namespace Reference
Functions
PX_FORCE_INLINE Vec3V getInvalidVec3V ()
PX_FORCE_INLINE bool allElementsEqualFloatV (const FloatV a, const FloatV b)
PX_FORCE_INLINE bool allElementsEqualVec3V (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE bool allElementsEqualVec4V (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE bool allElementsEqualBoolV (const BoolV a, const BoolV b)
PX_FORCE_INLINE bool allElementsEqualVecU32V (const VecU32V a, const VecU32V b)
PX_FORCE_INLINE bool allElementsEqualVecI32V (const VecI32V a, const VecI32V b)
PX_FORCE_INLINE bool allElementsEqualMat33V (const Mat33V &a, const Mat33V &b)
PX_FORCE_INLINE bool allElementsEqualMat34V (const Mat34V &a, const Mat34V &b)
PX_FORCE_INLINE bool allElementsEqualMat44V (const Mat44V &a, const Mat44V &b)
PX_FORCE_INLINE bool allElementsNearEqualFloatV (const FloatV a, const FloatV b)
PX_FORCE_INLINE bool allElementsNearEqualVec3V (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE bool allElementsNearEqualVec4V (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE bool allElementsNearEqualMat33V (const Mat33V &a, const Mat33V &b)
PX_FORCE_INLINE bool allElementsNearEqualMat34V (const Mat34V &a, const Mat34V &b)
PX_FORCE_INLINE bool allElementsNearEqualMat44V (const Mat44V &a, const Mat44V &b)
PX_FORCE_INLINE PxU32 V4U32AllEq (const VecU32V a, const VecU32V b)
PX_FORCE_INLINE BoolV V4IsEqI32 (const VecI32V a, const VecI32V b)
PX_FORCE_INLINE PxU32 V4I32AllEq (const VecI32V a, const VecI32V b)
Variables
static const FloatV minFError = FLoad(-VECMATH_AOS_EPSILON)
static const FloatV maxFError = FLoad(VECMATH_AOS_EPSILON)
static const Vec3V minV3Error = V3Load(-VECMATH_AOS_EPSILON)
static const Vec3V maxV3Error = V3Load(VECMATH_AOS_EPSILON)
static const Vec4V minV4Error = V4Load(-VECMATH_AOS_EPSILON)
static const Vec4V maxV4Error = V4Load(VECMATH_AOS_EPSILON)
Function Documentation
allElementsEqualBoolV()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualBoolV (const BoolV a, const BoolV b)
allElementsEqualFloatV()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualFloatV (const FloatV a, const FloatV b)
allElementsEqualMat33V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualMat33V (const Mat33V & a, const Mat33V & b)
References allElementsEqualVec3V(), physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, and physx::aos::Mat33V::col2.
allElementsEqualMat34V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualMat34V (const Mat34V & a, const Mat34V & b)
References allElementsEqualVec3V(), physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, and physx::aos::Mat34V::col3.
allElementsEqualMat44V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualMat44V (const Mat44V & a, const Mat44V & b)
References allElementsEqualVec4V(), physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, and physx::aos::Mat44V::col3.
allElementsEqualVec3V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualVec3V (const Vec3V a, const Vec3V b)
Referenced by allElementsEqualMat33V(), and allElementsEqualMat34V().
allElementsEqualVec4V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualVec4V (const Vec4V a, const Vec4V b)
Referenced by allElementsEqualMat44V().
allElementsEqualVecI32V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualVecI32V (const VecI32V a, const VecI32V b)
allElementsEqualVecU32V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsEqualVecU32V (const VecU32V a, const VecU32V b)
allElementsNearEqualFloatV()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsNearEqualFloatV (const FloatV a, const FloatV b)
References VECMATH_AOS_EPSILON.
allElementsNearEqualMat33V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsNearEqualMat33V (const Mat33V & a, const Mat33V & b)
References allElementsNearEqualVec3V(), physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, and physx::aos::Mat33V::col2.
allElementsNearEqualMat34V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsNearEqualMat34V (const Mat34V & a, const Mat34V & b)
References allElementsNearEqualVec3V(), physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, and physx::aos::Mat34V::col3.
allElementsNearEqualMat44V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsNearEqualMat44V (const Mat44V & a, const Mat44V & b)
References allElementsNearEqualVec4V(), physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, and physx::aos::Mat44V::col3.
allElementsNearEqualVec3V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsNearEqualVec3V (const Vec3V a, const Vec3V b)
References VECMATH_AOS_EPSILON.
Referenced by allElementsNearEqualMat33V(), and allElementsNearEqualMat34V().
allElementsNearEqualVec4V()
PX_FORCE_INLINE bool physx::aos::vecMathTests::allElementsNearEqualVec4V (const Vec4V a, const Vec4V b)
References VECMATH_AOS_EPSILON.
Referenced by allElementsNearEqualMat44V().
getInvalidVec3V()
PX_FORCE_INLINE Vec3V physx::aos::vecMathTests::getInvalidVec3V ()
V4I32AllEq()
PX_FORCE_INLINE PxU32 physx::aos::vecMathTests::V4I32AllEq (const VecI32V a, const VecI32V b)
References physx::aos::internalUnitNeonSimd::BAllTrue4_R(), and V4IsEqI32().
V4IsEqI32()
PX_FORCE_INLINE BoolV physx::aos::vecMathTests::V4IsEqI32 (const VecI32V a, const VecI32V b)
Referenced by V4I32AllEq().
V4U32AllEq()
PX_FORCE_INLINE PxU32 physx::aos::vecMathTests::V4U32AllEq (const VecU32V a, const VecU32V b)
References physx::aos::internalUnitNeonSimd::BAllTrue4_R(), and physx::aos::V4IsEqU32().
Variable Documentation
maxFError
const FloatV physx::aos::vecMathTests::maxFError = FLoad(VECMATH_AOS_EPSILON) static
maxV3Error
const Vec3V physx::aos::vecMathTests::maxV3Error = V3Load(VECMATH_AOS_EPSILON) static
maxV4Error
const Vec4V physx::aos::vecMathTests::maxV4Error = V4Load(VECMATH_AOS_EPSILON) static
minFError
const FloatV physx::aos::vecMathTests::minFError = FLoad(-VECMATH_AOS_EPSILON) static
minV3Error
const Vec3V physx::aos::vecMathTests::minV3Error = V3Load(-VECMATH_AOS_EPSILON) static
minV4Error
const Vec4V physx::aos::vecMathTests::minV4Error = V4Load(-VECMATH_AOS_EPSILON) static