ExtGpu Namespace Reference
ExtGpu Namespace Reference
Extensions
Classes
class PxGpuRadixSort
Performs a sort operation on the GPU.
class PxGpuScan
Performs a scan operation (exclusive or inclusive cumulative sum) on the GPU.
struct PxKernelArgumentPacker
struct PxKernelIds
class PxKernelLauncher
class PxKernelWrangler
struct PxLennardJonesMaterialData
Defines interaction properties for Lennard Jones molecular dynamics simulations.
struct PxParticleAndDiffuseBufferDesc
Structure to define user-defined particle state when constructing a new particle system that includes diffuse particles.
class PxParticleAttachmentBuffer
Holds user-defined attachment data to attach particles to other bodies.
struct PxParticleBufferDesc
Structure to define user-defined particle state when constructing a new particle system.
class PxParticleClothBufferHelper
Helper class to manage PxParticleClothDesc buffers used for communicating particle based cloths to PxParticleClothBuffer.
struct PxParticleClothConstraint
Holds all the information for a particle cloth constraint used in the PxParticleClothCooker.
class PxParticleClothCooker
class PxParticleRigidBufferHelper
Helper class to manage PxParticleRigidDesc buffers used for communicating particle based rigids to PxPaticleSystem.
struct PxParticleRigidDesc
Structure to define user-defined particle state when constructing a new particle system that includes shape-matched rigid bodies.
class PxParticleVolumeBufferHelper
Helper class to manage communicating PxParticleVolumes data to PxParticleBuffer.
struct PxParticleVolumeMesh
Helper struct that holds information about a specific mesh in a PxParticleVolumeBufferHelper.
class PxSparseGridBuilder
Constructs a sparse grid structure given an array of particle positions.
class PxStatelessKernelLauncher
Functions
static PX_NOINLINE void outputKernelLaunchDebugInfo (PxKernelWrangler *kernelWrangler, PxU16 id, const char *file, PxU32 line)
static PX_NOINLINE void outputKernelLaunchError (PxKernelWrangler *kernelWrangler, PxU16 id, const char *file, PxU32 line)
template<const bool debugExecution>
static PX_FORCE_INLINE physx::PxCUresult _testLaunch (physx::PxCUresult resultR, PxKernelWrangler *kernelWrangler, PxCudaContext *ctx, PxU16 id, CUstream hStream, const char *file, PxU32 line)
template<const bool debugExecution>
static PX_FORCE_INLINE physx::PxCUresult _launch (PxKernelWrangler *kernelWrangler, PxCudaContext *ctx, PxU16 id, PxU32 gridDimX, PxU32 gridDimY, PxU32 gridDimZ, PxU32 blockDimX, PxU32 blockDimY, PxU32 blockDimZ, PxU32 sharedMemBytes, CUstream hStream, PxCudaKernelParam *kernelParams, size_t kernelParamsSizeInBytes, const char *file, PxU32 line)
template<const bool debugExecution>
static PX_FORCE_INLINE physx::PxCUresult _launch (PxKernelWrangler *kernelWrangler, PxCudaContext *ctx, PxU16 id, PxU32 gridDimX, PxU32 gridDimY, PxU32 gridDimZ, PxU32 blockDimX, PxU32 blockDimY, PxU32 blockDimZ, PxU32 sharedMemBytes, CUstream hStream, void **kernelParams, const char *file, PxU32 line)
void initAlgorithmsKernels0 ()
void initAnisotropyKernels0 ()
void initIsosurfaceExtractionKernels0 ()
void initMolecularDynamicsKernels0 ()
void initSoftbodyExtensionKernels0 ()
void initSparseGridKernels0 ()
void initUtilityKernels0 ()
void initializeKernelModules ()
PxParticleRigidBufferHelper * PxCreateParticleRigidBufferHelper (PxU32 maxRigids, PxU32 maxParticles, PxCudaContextManager *cudaContextManager)
Creates a PxParticleRigidBufferHelper.
PxParticleClothBufferHelper * PxCreateParticleClothBufferHelper (const PxU32 maxCloths, const PxU32 maxTriangles, const PxU32 maxSprings, const PxU32 maxParticles, PxCudaContextManager *cudaContextManager)
Creates a PxParticleClothBufferHelper helper.
PxParticleVolumeBufferHelper * PxCreateParticleVolumeBufferHelper (PxU32 maxVolumes, PxU32 maxTriangles, PxCudaContextManager *cudaContextManager)
Creates a PxParticleVolumeBufferHelper.
PxParticleAttachmentBuffer * PxCreateParticleAttachmentBuffer (PxParticleBuffer &particleBuffer, PxParticleSystem &particleSystem)
Creates a particle attachment buffer.
PxParticleBuffer * PxCreateAndPopulateParticleBuffer (const ExtGpu::PxParticleBufferDesc &desc, PxCudaContextManager *cudaContextManager)
Creates and populates a particle buffer.
PxParticleAndDiffuseBuffer * PxCreateAndPopulateParticleAndDiffuseBuffer (const ExtGpu::PxParticleAndDiffuseBufferDesc &desc, PxCudaContextManager *cudaContextManager)
Creates and populates a particle buffer that includes support for diffuse particles.
PxParticleClothBuffer * PxCreateAndPopulateParticleClothBuffer (const ExtGpu::PxParticleBufferDesc &desc, const PxParticleClothDesc &clothDesc, PxPartitionedParticleCloth &output, PxCudaContextManager *cudaContextManager)
Creates and populates a particle cloth buffer.
PxParticleRigidBuffer * PxCreateAndPopulateParticleRigidBuffer (const ExtGpu::PxParticleBufferDesc &desc, const ExtGpu::PxParticleRigidDesc &rigidDesc, PxCudaContextManager *cudaContextManager)
Creates and populates a particle rigid buffer. Particle rigids are particles that try to keep their relative positions. They are a bit commpressible similar to softbodies.
Variables
const PxU32 CUDA_SUCCESS = 0
Function Documentation
_launch() [1/2]
template<const bool debugExecution> static PX_FORCE_INLINE physx::PxCUresult ExtGpu::_launch (PxKernelWrangler * kernelWrangler, PxCudaContext * ctx, PxU16 id, PxU32 gridDimX, PxU32 gridDimY, PxU32 gridDimZ, PxU32 blockDimX, PxU32 blockDimY, PxU32 blockDimZ, PxU32 sharedMemBytes, CUstream hStream, PxCudaKernelParam * kernelParams, size_t kernelParamsSizeInBytes, const char * file, PxU32 line) static
References ExtGpu::PxKernelWrangler::getCuFunction(), and outputKernelLaunchDebugInfo().
_launch() [2/2]
template<const bool debugExecution> static PX_FORCE_INLINE physx::PxCUresult ExtGpu::_launch (PxKernelWrangler * kernelWrangler, PxCudaContext * ctx, PxU16 id, PxU32 gridDimX, PxU32 gridDimY, PxU32 gridDimZ, PxU32 blockDimX, PxU32 blockDimY, PxU32 blockDimZ, PxU32 sharedMemBytes, CUstream hStream, void ** kernelParams, const char * file, PxU32 line) static
References ExtGpu::PxKernelWrangler::getCuFunction(), and outputKernelLaunchDebugInfo().
_testLaunch()
template<const bool debugExecution> static PX_FORCE_INLINE physx::PxCUresult ExtGpu::_testLaunch (physx::PxCUresult resultR, PxKernelWrangler * kernelWrangler, PxCudaContext * ctx, PxU16 id, CUstream hStream, const char * file, PxU32 line) static
References CUDA_SUCCESS, PxErrorCode::eINTERNAL_ERROR, ExtGpu::PxKernelWrangler::getCuFunctionName(), outputKernelLaunchError(), PX_ASSERT, PxGetFoundation(), and Pxsnprintf().
initAlgorithmsKernels0()
void ExtGpu::initAlgorithmsKernels0 ()
Referenced by initializeKernelModules().
initAnisotropyKernels0()
void ExtGpu::initAnisotropyKernels0 ()
Referenced by initializeKernelModules().
initializeKernelModules()
void ExtGpu::initializeKernelModules ()
References initAlgorithmsKernels0(), initAnisotropyKernels0(), initIsosurfaceExtractionKernels0(), initMolecularDynamicsKernels0(), initSoftbodyExtensionKernels0(), initSparseGridKernels0(), and initUtilityKernels0().
initIsosurfaceExtractionKernels0()
void ExtGpu::initIsosurfaceExtractionKernels0 ()
Referenced by initializeKernelModules().
initMolecularDynamicsKernels0()
void ExtGpu::initMolecularDynamicsKernels0 ()
Referenced by initializeKernelModules().
initSoftbodyExtensionKernels0()
void ExtGpu::initSoftbodyExtensionKernels0 ()
Referenced by initializeKernelModules().
initSparseGridKernels0()
void ExtGpu::initSparseGridKernels0 ()
Referenced by initializeKernelModules().
initUtilityKernels0()
void ExtGpu::initUtilityKernels0 ()
Referenced by initializeKernelModules().
outputKernelLaunchDebugInfo()
static PX_NOINLINE void ExtGpu::outputKernelLaunchDebugInfo (PxKernelWrangler * kernelWrangler, PxU16 id, const char * file, PxU32 line) static
References PxErrorCode::eDEBUG_INFO, ExtGpu::PxKernelWrangler::getCuFunctionName(), PxGetFoundation(), and Pxsnprintf().
Referenced by _launch().
outputKernelLaunchError()
static PX_NOINLINE void ExtGpu::outputKernelLaunchError (PxKernelWrangler * kernelWrangler, PxU16 id, const char * file, PxU32 line) static
References PxErrorCode::eINTERNAL_ERROR, ExtGpu::PxKernelWrangler::getCuFunctionName(), PxGetFoundation(), and Pxsnprintf().
Referenced by _testLaunch().
PxCreateAndPopulateParticleAndDiffuseBuffer()
PxParticleAndDiffuseBuffer* ExtGpu::PxCreateAndPopulateParticleAndDiffuseBuffer (const ExtGpu::PxParticleAndDiffuseBufferDesc & desc, PxCudaContextManager * cudaContextManager)
Creates and populates a particle buffer that includes support for diffuse particles.
Parameters
[in] desc The particle buffer descriptor
[in] cudaContextManager A cuda context manager
Returns
A fully populated particle buffer ready to use
PxCreateAndPopulateParticleBuffer()
PxParticleBuffer* ExtGpu::PxCreateAndPopulateParticleBuffer (const ExtGpu::PxParticleBufferDesc & desc, PxCudaContextManager * cudaContextManager)
Creates and populates a particle buffer.
Parameters
[in] desc The particle buffer descriptor
[in] cudaContextManager A cuda context manager
Returns
A fully populated particle buffer ready to use
PxCreateAndPopulateParticleClothBuffer()
PxParticleClothBuffer* ExtGpu::PxCreateAndPopulateParticleClothBuffer (const ExtGpu::PxParticleBufferDesc & desc, const PxParticleClothDesc & clothDesc, PxPartitionedParticleCloth & output, PxCudaContextManager * cudaContextManager)
Creates and populates a particle cloth buffer.
Parameters
[in] desc The particle buffer descriptor
[in] clothDesc The cloth descriptor
[out] output A cloth output object to further configure the behavior of the cloth
[in] cudaContextManager A cuda context manager
Returns
A fully populated particle cloth buffer ready to use
PxCreateAndPopulateParticleRigidBuffer()
PxParticleRigidBuffer* ExtGpu::PxCreateAndPopulateParticleRigidBuffer (const ExtGpu::PxParticleBufferDesc & desc, const ExtGpu::PxParticleRigidDesc & rigidDesc, PxCudaContextManager * cudaContextManager)
Creates and populates a particle rigid buffer. Particle rigids are particles that try to keep their relative positions. They are a bit commpressible similar to softbodies.
Parameters
[in] desc The particle buffer descriptor
[in] rigidDesc The rigid descriptor
[in] cudaContextManager A cuda context manager
Returns
A fully populated particle rigid buffer ready to use
PxCreateParticleAttachmentBuffer()
PxParticleAttachmentBuffer* ExtGpu::PxCreateParticleAttachmentBuffer (PxParticleBuffer & particleBuffer, PxParticleSystem & particleSystem)
Creates a particle attachment buffer.
Parameters
[in] particleBuffer The particle buffer that contains particles that should get attached to something
[in] particleSystem The particle system that is used to simulate the userBuffer
Returns
An attachment buffer ready to use
PxCreateParticleClothBufferHelper()
PxParticleClothBufferHelper* ExtGpu::PxCreateParticleClothBufferHelper (const PxU32 maxCloths, const PxU32 maxTriangles, const PxU32 maxSprings, const PxU32 maxParticles, PxCudaContextManager * cudaContextManager)
Creates a PxParticleClothBufferHelper helper.
Parameters
[in] maxCloths The maximum number of cloths this PxParticleClothBufferHelper should hold.
[in] maxTriangles The maximum number of triangles this PxParticleClothBufferHelper should hold.
[in] maxSprings The maximum number of springs this PxParticleClothBufferHelper should hold.
[in] maxParticles The maximum number of particles this PxParticleClothBufferHelper should hold.
[in] cudaContextManager A pointer to a PxCudaContextManager.
Returns
A pointer to the PxParticleClothBufferHelper that was created.
PxCreateParticleRigidBufferHelper()
PxParticleRigidBufferHelper* ExtGpu::PxCreateParticleRigidBufferHelper (PxU32 maxRigids, PxU32 maxParticles, PxCudaContextManager * cudaContextManager)
Creates a PxParticleRigidBufferHelper.
Parameters
[in] maxRigids The maximum number of rigids this PxParticleRigidsBuffers instance should hold.
[in] maxParticles The maximum number of particles this PxParticleRigidBufferHelper instance should hold.
[in] cudaContextManager A pointer to a PxCudaContextManager.
Returns
A pointer to the new PxParticleRigidBufferHelper.
PxCreateParticleVolumeBufferHelper()
PxParticleVolumeBufferHelper* ExtGpu::PxCreateParticleVolumeBufferHelper (PxU32 maxVolumes, PxU32 maxTriangles, PxCudaContextManager * cudaContextManager)
Creates a PxParticleVolumeBufferHelper.
Parameters
[in] maxVolumes The maximum number of PxParticleVolume s this PxParticleVolumeBufferHelper instance should hold.
[in] maxTriangles The maximum number of triangles this PxParticleVolumeBufferHelper instance should hold.
[in] cudaContextManager A pointer to a PxCudaContextManager.
Returns
A pointer to the new PxParticleVolumeBufferHelper.
Variable Documentation
CUDA_SUCCESS
const PxU32 ExtGpu::CUDA_SUCCESS = 0
Referenced by _testLaunch().