aos Namespace Reference
aos Namespace Reference
Classes
struct BoolV
struct FloatV
struct Mat33V
struct Mat34V
struct Mat43V
struct Mat44V
class PxMatTransformV
class PxTransformV
struct Vec3V
struct Vec4V
struct VecCrossV
struct VecI16V
struct VecI32V
struct VecShiftV
struct VecU16V
struct VecU32V
Typedefs
typedef Vec4V QuatV
typedef VecI32V VecShiftV
typedef __m128 FloatV
typedef __m128 Vec3V
typedef __m128 Vec4V
typedef __m128 BoolV
typedef __m128 VecU32V
typedef __m128 VecI32V
typedef __m128 VecU16V
typedef __m128 VecI16V
Functions
PX_FORCE_INLINE void QuatGetMat33V (const QuatVArg q, Vec3V &column0, Vec3V &column1, Vec3V &column2)
PX_FORCE_INLINE QuatV QuatVLoadXYZW (const PxF32 x, const PxF32 y, const PxF32 z, const PxF32 w)
PX_FORCE_INLINE QuatV QuatVLoadU (const PxF32 *v)
PX_FORCE_INLINE QuatV QuatVLoadA (const PxF32 *v)
PX_FORCE_INLINE QuatV QuatV_From_RotationAxisAngle (const Vec3V u, const FloatV a)
PX_FORCE_INLINE QuatV QuatNormalize (const QuatV q)
PX_FORCE_INLINE FloatV QuatLength (const QuatV q)
PX_FORCE_INLINE FloatV QuatLengthSq (const QuatV q)
PX_FORCE_INLINE FloatV QuatDot (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatConjugate (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetImaginaryPart (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetBasisVector0 (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetBasisVector1 (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetBasisVector2 (const QuatV q)
PX_FORCE_INLINE Vec3V QuatRotate (const QuatV q, const Vec3V v)
PX_FORCE_INLINE Vec3V QuatTransform (const QuatV q, const Vec3V p, const Vec3V v)
PX_FORCE_INLINE Vec3V QuatRotateInv (const QuatV q, const Vec3V v)
PX_FORCE_INLINE QuatV QuatMul (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatAdd (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatNeg (const QuatV q)
PX_FORCE_INLINE QuatV QuatSub (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatScale (const QuatV a, const FloatV b)
PX_FORCE_INLINE QuatV QuatMerge (const FloatV *const floatVArray)
PX_FORCE_INLINE QuatV QuatMerge (const FloatVArg x, const FloatVArg y, const FloatVArg z, const FloatVArg w)
PX_FORCE_INLINE QuatV QuatIdentity ()
PX_FORCE_INLINE bool isFiniteQuatV (const QuatV q)
PX_FORCE_INLINE bool isValidQuatV (const QuatV q)
PX_FORCE_INLINE bool isSaneQuatV (const QuatV q)
PX_FORCE_INLINE Mat33V QuatGetMat33V (const QuatVArg q)
PX_FORCE_INLINE QuatV Mat33GetQuatV (const Mat33V &a)
PX_FORCE_INLINE PxTransformV loadTransformA (const PxTransform &transform)
PX_FORCE_INLINE PxTransformV loadTransformU (const PxTransform &transform)
Typedef Documentation
BoolV
typedef __m128 aos::BoolV
FloatV
typedef __m128 aos::FloatV
QuatV
typedef __m128 aos::QuatV
Vec3V
typedef __m128 aos::Vec3V
Vec4V
typedef __m128 aos::Vec4V
VecI16V
typedef __m128 aos::VecI16V
VecI32V
typedef __m128 aos::VecI32V
VecShiftV
typedef VecI32V aos::VecShiftV
VecU16V
typedef __m128 aos::VecU16V
VecU32V
typedef __m128 aos::VecU32V
Function Documentation
isFiniteQuatV()
PX_FORCE_INLINE bool aos::isFiniteQuatV (const QuatV q)
References physx::aos::isFiniteVec4V().
isSaneQuatV()
PX_FORCE_INLINE bool aos::isSaneQuatV (const QuatV q)
References physx::aos::BAllEqTTTT(), physx::aos::FAbs(), physx::aos::FIsGrtr(), physx::aos::FLoad(), physx::aos::FOne(), physx::aos::FSub(), physx::aos::isFiniteVec4V(), and physx::aos::QuatLength().
isValidQuatV()
PX_FORCE_INLINE bool aos::isValidQuatV (const QuatV q)
References physx::aos::BAllEqTTTT(), physx::aos::FAbs(), physx::aos::FIsGrtr(), physx::aos::FLoad(), physx::aos::FOne(), physx::aos::FSub(), physx::aos::isFiniteVec4V(), and physx::aos::QuatLength().
loadTransformA()
PX_FORCE_INLINE PxTransformV aos::loadTransformA (const PxTransform & transform)
References PxTransformT< Type >::p, PxTransformT< Type >::q, physx::aos::QuatVLoadA(), physx::aos::V3LoadA(), PxVec3T< Type >::x, and PxQuatT< Type >::x.
loadTransformU()
PX_FORCE_INLINE PxTransformV aos::loadTransformU (const PxTransform & transform)
References PxTransformT< Type >::p, PxTransformT< Type >::q, physx::aos::QuatVLoadU(), physx::aos::V3LoadU(), PxVec3T< Type >::x, and PxQuatT< Type >::x.
Mat33GetQuatV()
PX_FORCE_INLINE QuatV aos::Mat33GetQuatV (const Mat33V & a)
References physx::aos::BAllTrue3(), aos::Mat33V::col0, aos::Mat33V::col1, aos::Mat33V::col2, physx::aos::FAdd(), physx::aos::FAllGrtrOrEq(), physx::aos::FLoad(), physx::aos::FMul(), physx::aos::FNeg(), physx::aos::FOne(), physx::aos::FRecip(), physx::aos::FScaleAdd(), physx::aos::FSel(), physx::aos::FSqrt(), physx::aos::FZero(), physx::aos::V3Add(), physx::aos::V3GetX(), physx::aos::V3GetY(), physx::aos::V3GetZ(), physx::aos::V3IsGrtrOrEq(), physx::aos::V3Merge(), physx::aos::V3Scale(), physx::aos::V3Splat(), physx::aos::V3Sub(), physx::aos::V4Merge(), physx::aos::V4Sel(), physx::aos::V4SetW(), and physx::aos::Vec4V_From_Vec3V().
QuatAdd()
PX_FORCE_INLINE QuatV aos::QuatAdd (const QuatV a, const QuatV b)
References physx::aos::V4Add().
QuatConjugate()
PX_FORCE_INLINE QuatV aos::QuatConjugate (const QuatV q)
References physx::aos::V4GetW(), physx::aos::V4Neg(), and physx::aos::V4SetW().
QuatDot()
PX_FORCE_INLINE FloatV aos::QuatDot (const QuatV a, const QuatV b)
References physx::aos::V4Dot().
QuatGetBasisVector0()
PX_FORCE_INLINE Vec3V aos::QuatGetBasisVector0 (const QuatV q)
brief computes rotation of x-axis
References physx::aos::FLoad(), physx::aos::FMul(), physx::aos::FNeg(), physx::aos::FOne(), physx::aos::FSub(), physx::aos::V3GetX(), physx::aos::V3GetY(), physx::aos::V3GetZ(), physx::aos::V3Merge(), physx::aos::V3Scale(), physx::aos::V3ScaleAdd(), physx::aos::V3SetX(), physx::aos::V4GetW(), and physx::aos::Vec3V_From_Vec4V().
QuatGetBasisVector1()
PX_FORCE_INLINE Vec3V aos::QuatGetBasisVector1 (const QuatV q)
brief computes rotation of y-axis
References physx::aos::FLoad(), physx::aos::FMul(), physx::aos::FNeg(), physx::aos::FOne(), physx::aos::FSub(), physx::aos::V3GetX(), physx::aos::V3GetY(), physx::aos::V3GetZ(), physx::aos::V3Merge(), physx::aos::V3Scale(), physx::aos::V3ScaleAdd(), physx::aos::V3SetY(), physx::aos::V4GetW(), and physx::aos::Vec3V_From_Vec4V().
QuatGetBasisVector2()
PX_FORCE_INLINE Vec3V aos::QuatGetBasisVector2 (const QuatV q)
brief computes rotation of z-axis
References physx::aos::FLoad(), physx::aos::FMul(), physx::aos::FNeg(), physx::aos::FOne(), physx::aos::FSub(), physx::aos::V3GetX(), physx::aos::V3GetY(), physx::aos::V3GetZ(), physx::aos::V3Merge(), physx::aos::V3Scale(), physx::aos::V3ScaleAdd(), physx::aos::V3SetZ(), physx::aos::V4GetW(), and physx::aos::Vec3V_From_Vec4V().
QuatGetImaginaryPart()
PX_FORCE_INLINE Vec3V aos::QuatGetImaginaryPart (const QuatV q)
References physx::aos::Vec3V_From_Vec4V().
QuatGetMat33V() [1/2]
PX_FORCE_INLINE void aos::QuatGetMat33V (const QuatVArg q, Vec3V & column0, Vec3V & column1, Vec3V & column2)
References physx::aos::V4Add(), physx::aos::V4GetW(), physx::aos::V4GetX(), physx::aos::V4GetY(), physx::aos::V4GetZ(), physx::aos::V4MulAdd(), physx::aos::V4Neg(), and physx::aos::Vec3V_From_Vec4V().
QuatGetMat33V() [2/2]
PX_FORCE_INLINE Mat33V aos::QuatGetMat33V (const QuatVArg q)
References physx::aos::FAdd(), physx::aos::FMul(), physx::aos::FOne(), physx::aos::FSub(), physx::aos::V3Merge(), physx::aos::V4GetW(), physx::aos::V4GetX(), physx::aos::V4GetY(), and physx::aos::V4GetZ().
Referenced by PxMat33Padded::PxMat33Padded(), and aos::PxMatTransformV::PxMatTransformV().
QuatIdentity()
PX_FORCE_INLINE QuatV aos::QuatIdentity ()
References physx::aos::FOne(), physx::aos::V4SetW(), and physx::aos::V4Zero().
Referenced by aos::PxTransformV::Invalidate(), and aos::PxTransformV::normalize().
QuatLength()
PX_FORCE_INLINE FloatV aos::QuatLength (const QuatV q)
References physx::aos::V4Length().
QuatLengthSq()
PX_FORCE_INLINE FloatV aos::QuatLengthSq (const QuatV q)
References physx::aos::V4LengthSq().
QuatMerge() [1/2]
PX_FORCE_INLINE QuatV aos::QuatMerge (const FloatV *const floatVArray)
References physx::aos::V4Merge().
QuatMerge() [2/2]
PX_FORCE_INLINE QuatV aos::QuatMerge (const FloatVArg x, const FloatVArg y, const FloatVArg z, const FloatVArg w)
References physx::aos::V4Merge().
QuatMul()
PX_FORCE_INLINE QuatV aos::QuatMul (const QuatV a, const QuatV b)
References physx::aos::FMul(), physx::aos::FSub(), physx::aos::V3Add(), physx::aos::V3Cross(), physx::aos::V3Dot(), physx::aos::V3Scale(), physx::aos::V4GetW(), physx::aos::V4SetW(), physx::aos::Vec3V_From_Vec4V(), and physx::aos::Vec4V_From_Vec3V().
QuatNeg()
PX_FORCE_INLINE QuatV aos::QuatNeg (const QuatV q)
References physx::aos::V4Neg().
QuatNormalize()
PX_FORCE_INLINE QuatV aos::QuatNormalize (const QuatV q)
References physx::aos::V4Normalize().
QuatRotate()
PX_FORCE_INLINE Vec3V aos::QuatRotate (const QuatV q, const Vec3V v)
References physx::aos::FLoad(), physx::aos::FScaleAdd(), physx::aos::V3Cross(), physx::aos::V3Dot(), physx::aos::V3Scale(), physx::aos::V3ScaleAdd(), physx::aos::V4GetW(), and physx::aos::Vec3V_From_Vec4V().
QuatRotateInv()
PX_FORCE_INLINE Vec3V aos::QuatRotateInv (const QuatV q, const Vec3V v)
References physx::aos::FLoad(), physx::aos::FScaleAdd(), physx::aos::V3Cross(), physx::aos::V3Dot(), physx::aos::V3NegScaleSub(), physx::aos::V3Scale(), physx::aos::V3ScaleAdd(), physx::aos::V4GetW(), and physx::aos::Vec3V_From_Vec4V().
QuatScale()
PX_FORCE_INLINE QuatV aos::QuatScale (const QuatV a, const FloatV b)
References physx::aos::V4Scale().
QuatSub()
PX_FORCE_INLINE QuatV aos::QuatSub (const QuatV a, const QuatV b)
References physx::aos::V4Sub().
QuatTransform()
PX_FORCE_INLINE Vec3V aos::QuatTransform (const QuatV q, const Vec3V p, const Vec3V v)
References physx::aos::FLoad(), physx::aos::FScaleAdd(), physx::aos::V3Cross(), physx::aos::V3Dot(), physx::aos::V3Scale(), physx::aos::V3ScaleAdd(), physx::aos::V4GetW(), and physx::aos::Vec3V_From_Vec4V().
Referenced by aos::PxTransformV::transform().
QuatV_From_RotationAxisAngle()
PX_FORCE_INLINE QuatV aos::QuatV_From_RotationAxisAngle (const Vec3V u, const FloatV a)
References physx::aos::FLoad(), physx::aos::FMul(), physx::aos::FSub(), PX_PIDIV2, physx::aos::V3Merge(), physx::aos::V3Scale(), physx::aos::V4GetX(), physx::aos::V4GetY(), physx::aos::V4SetW(), physx::aos::V4Sin(), and physx::aos::Vec4V_From_Vec3V().
QuatVLoadA()
PX_FORCE_INLINE QuatV aos::QuatVLoadA (const PxF32 * v)
References physx::aos::V4LoadA().
Referenced by loadTransformA().
QuatVLoadU()
PX_FORCE_INLINE QuatV aos::QuatVLoadU (const PxF32 * v)
References physx::aos::V4LoadU().
Referenced by loadTransformU().
QuatVLoadXYZW()
PX_FORCE_INLINE QuatV aos::QuatVLoadXYZW (const PxF32 x, const PxF32 y, const PxF32 z, const PxF32 w)
References physx::aos::V4LoadXYZW().
Referenced by aos::PxTransformV::PxTransformV().