physx::aos Namespace Reference
physx::aos Namespace Reference
Namespaces
internalScalarSimd
internalUnitNeonSimd
internalUnitSSE2Simd
internalWindowsSimd
vecMathTests
Classes
struct Mat33V
struct Mat34V
struct Mat43V
struct Mat44V
struct PX_VECTORF32
union UnionM128
struct VecCrossV
struct VecShiftV
Typedefs
typedef float32x2_t FloatV
typedef float32x4_t Vec3V
typedef float32x4_t Vec4V
typedef uint32x4_t BoolV
typedef float32x4_t QuatV
typedef uint32x4_t VecU32V
typedef int32x4_t VecI32V
typedef uint16x8_t VecU16V
typedef int16x8_t VecI16V
typedef uint8x16_t VecU8V
typedef VecI32V VecShiftV
typedef union physx::aos::UnionM128 UnionM128
Functions
PX_FORCE_INLINE FloatV FLoad (const PxF32 f)
PX_FORCE_INLINE Vec3V V3Load (const PxF32 f)
PX_FORCE_INLINE Vec3V V3LoadU (const PxVec3 &f)
PX_FORCE_INLINE Vec3V V3LoadA (const PxVec3 &f)
PX_FORCE_INLINE Vec3V V3LoadUnsafeA (const PxVec3 &f)
PX_FORCE_INLINE Vec3V V3LoadU (const PxF32 *f)
PX_FORCE_INLINE Vec3V V3LoadA (const PxF32 *f)
PX_FORCE_INLINE Vec4V V4Load (const PxF32 f)
PX_FORCE_INLINE Vec4V V4LoadU (const PxF32 *const f)
PX_FORCE_INLINE Vec4V V4LoadA (const PxF32 *const f)
PX_FORCE_INLINE Vec4V V4LoadXYZW (const PxF32 &x, const PxF32 &y, const PxF32 &z, const PxF32 &w)
PX_FORCE_INLINE BoolV BLoad (const bool f)
PX_FORCE_INLINE BoolV BLoad (const bool *const f)
PX_FORCE_INLINE VecU32V U4Load (const PxU32 f)
PX_FORCE_INLINE VecU32V U4LoadU (const PxU32 *f)
PX_FORCE_INLINE VecU32V U4LoadA (const PxU32 *f)
PX_FORCE_INLINE VecU32V U4LoadXYZW (PxU32 x, PxU32 y, PxU32 z, PxU32 w)
PX_FORCE_INLINE VecI32V I4Load (const PxI32 i)
PX_FORCE_INLINE VecI32V I4LoadU (const PxI32 *i)
PX_FORCE_INLINE VecI32V I4LoadA (const PxI32 *i)
PX_FORCE_INLINE QuatV QuatVLoadU (const PxF32 *v)
PX_FORCE_INLINE QuatV QuatVLoadA (const PxF32 *v)
PX_FORCE_INLINE QuatV QuatVLoadXYZW (const PxF32 x, const PxF32 y, const PxF32 z, const PxF32 w)
Vec4V Vec4V_From_PxVec3_WUndefined (const PxVec3 &v)
PX_FORCE_INLINE Vec3V Vec3V_From_Vec4V (Vec4V v)
PX_FORCE_INLINE Vec3V Vec3V_From_Vec4V_WUndefined (const Vec4V v)
PX_FORCE_INLINE Vec4V Vec4V_From_Vec3V (Vec3V f)
PX_FORCE_INLINE Vec4V Vec4V_From_VecU32V (VecU32V a)
PX_FORCE_INLINE Vec4V Vec4V_From_VecI32V (VecI32V a)
PX_FORCE_INLINE Vec4V Vec4V_ReinterpretFrom_VecU32V (VecU32V a)
PX_FORCE_INLINE Vec4V Vec4V_ReinterpretFrom_VecI32V (VecI32V a)
PX_FORCE_INLINE VecU32V VecU32V_ReinterpretFrom_Vec4V (Vec4V a)
PX_FORCE_INLINE VecU32V VecU32V_From_BoolV (const BoolVArg b)
PX_FORCE_INLINE VecI32V VecI32V_ReinterpretFrom_Vec4V (Vec4V a)
PX_FORCE_INLINE VecI32V VecI32V_From_Vec4V (Vec4V a)
PX_FORCE_INLINE VecI32V VecI32V_From_BoolV (const BoolVArg b)
PX_FORCE_INLINE void FStore (const FloatV a, PxF32 *PX_RESTRICT f)
PX_FORCE_INLINE void V3StoreA (const Vec3V a, PxVec3 &f)
PX_FORCE_INLINE void V3StoreU (const Vec3V a, PxVec3 &f)
PX_FORCE_INLINE void V4StoreA (const Vec4V a, PxF32 *f)
PX_FORCE_INLINE void V4StoreU (const Vec4V a, PxF32 *f)
PX_FORCE_INLINE void BStoreA (const BoolV b, PxU32 *f)
PX_FORCE_INLINE void U4StoreA (const VecU32V uv, PxU32 *u)
PX_FORCE_INLINE void I4StoreA (const VecI32V iv, PxI32 *i)
PX_FORCE_INLINE bool isFiniteFloatV (const FloatV a)
PX_FORCE_INLINE bool isFiniteVec3V (const Vec3V a)
PX_FORCE_INLINE bool isFiniteVec4V (const Vec4V a)
PX_FORCE_INLINE bool isValidVec3V (const Vec3V a)
PX_FORCE_INLINE FloatV FZero ()
PX_FORCE_INLINE FloatV FOne ()
PX_FORCE_INLINE FloatV FHalf ()
PX_FORCE_INLINE FloatV FEps ()
PX_FORCE_INLINE FloatV FMax ()
PX_FORCE_INLINE FloatV FNegMax ()
PX_FORCE_INLINE FloatV FEps6 ()
PX_FORCE_INLINE FloatV FNeg (const FloatV f)
PX_FORCE_INLINE FloatV FAdd (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FSub (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FMul (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FDiv (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FDivFast (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FRecip (const FloatV a)
PX_FORCE_INLINE FloatV FRecipFast (const FloatV a)
PX_FORCE_INLINE FloatV FRsqrt (const FloatV a)
PX_FORCE_INLINE FloatV FRsqrtFast (const FloatV a)
PX_FORCE_INLINE FloatV FSqrt (const FloatV a)
PX_FORCE_INLINE FloatV FScaleAdd (const FloatV a, const FloatV b, const FloatV c)
PX_FORCE_INLINE FloatV FNegScaleSub (const FloatV a, const FloatV b, const FloatV c)
PX_FORCE_INLINE FloatV FAbs (const FloatV a)
PX_FORCE_INLINE FloatV FSel (const BoolV c, const FloatV a, const FloatV b)
PX_FORCE_INLINE BoolV FIsGrtr (const FloatV a, const FloatV b)
PX_FORCE_INLINE BoolV FIsGrtrOrEq (const FloatV a, const FloatV b)
PX_FORCE_INLINE BoolV FIsEq (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FMax (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FMin (const FloatV a, const FloatV b)
PX_FORCE_INLINE FloatV FClamp (const FloatV a, const FloatV minV, const FloatV maxV)
PX_FORCE_INLINE PxU32 FAllGrtr (const FloatV a, const FloatV b)
PX_FORCE_INLINE PxU32 FAllGrtrOrEq (const FloatV a, const FloatV b)
PX_FORCE_INLINE PxU32 FAllEq (const FloatV a, const FloatV b)
PX_FORCE_INLINE PxU32 FOutOfBounds (const FloatV a, const FloatV min, const FloatV max)
PX_FORCE_INLINE PxU32 FInBounds (const FloatV a, const FloatV min, const FloatV max)
PX_FORCE_INLINE PxU32 FOutOfBounds (const FloatV a, const FloatV bounds)
PX_FORCE_INLINE PxU32 FInBounds (const FloatV a, const FloatV bounds)
PX_FORCE_INLINE FloatV FRound (const FloatV a)
PX_FORCE_INLINE FloatV FSin (const FloatV a)
PX_FORCE_INLINE FloatV FCos (const FloatV a)
PX_FORCE_INLINE Vec3V V3Splat (const FloatV f)
PX_FORCE_INLINE Vec3V V3Merge (const FloatVArg x, const FloatVArg y, const FloatVArg z)
PX_FORCE_INLINE Vec3V V3UnitX ()
PX_FORCE_INLINE Vec3V V3UnitY ()
PX_FORCE_INLINE Vec3V V3UnitZ ()
PX_FORCE_INLINE FloatV V3GetX (const Vec3V f)
PX_FORCE_INLINE FloatV V3GetY (const Vec3V f)
PX_FORCE_INLINE FloatV V3GetZ (const Vec3V f)
PX_FORCE_INLINE Vec3V V3SetX (const Vec3V v, const FloatV f)
PX_FORCE_INLINE Vec3V V3SetY (const Vec3V v, const FloatV f)
PX_FORCE_INLINE Vec3V V3SetZ (const Vec3V v, const FloatV f)
PX_FORCE_INLINE void V3WriteX (Vec3V &v, const PxF32 f)
PX_FORCE_INLINE void V3WriteY (Vec3V &v, const PxF32 f)
PX_FORCE_INLINE void V3WriteZ (Vec3V &v, const PxF32 f)
PX_FORCE_INLINE void V3WriteXYZ (Vec3V &v, const PxVec3 &f)
PX_FORCE_INLINE PxF32 V3ReadX (const Vec3V &v)
PX_FORCE_INLINE PxF32 V3ReadY (const Vec3V &v)
PX_FORCE_INLINE PxF32 V3ReadZ (const Vec3V &v)
PX_FORCE_INLINE const PxVec3 & V3ReadXYZ (const Vec3V &v)
PX_FORCE_INLINE Vec3V V3ColX (const Vec3V a, const Vec3V b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3ColY (const Vec3V a, const Vec3V b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3ColZ (const Vec3V a, const Vec3V b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3Zero ()
PX_FORCE_INLINE Vec3V V3One ()
PX_FORCE_INLINE Vec3V V3Eps ()
PX_FORCE_INLINE Vec3V V3Neg (const Vec3V c)
PX_FORCE_INLINE Vec3V V3Add (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Sub (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Scale (const Vec3V a, const FloatV b)
PX_FORCE_INLINE Vec3V V3Mul (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3ScaleInv (const Vec3V a, const FloatV b)
PX_FORCE_INLINE Vec3V V3Div (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3ScaleInvFast (const Vec3V a, const FloatV b)
PX_FORCE_INLINE Vec3V V3DivFast (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Recip (const Vec3V a)
PX_FORCE_INLINE Vec3V V3RecipFast (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Rsqrt (const Vec3V a)
PX_FORCE_INLINE Vec3V V3RsqrtFast (const Vec3V a)
PX_FORCE_INLINE Vec3V V3ScaleAdd (const Vec3V a, const FloatV b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3NegScaleSub (const Vec3V a, const FloatV b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3MulAdd (const Vec3V a, const Vec3V b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3NegMulSub (const Vec3V a, const Vec3V b, const Vec3V c)
PX_FORCE_INLINE Vec3V V3Abs (const Vec3V a)
PX_FORCE_INLINE FloatV V3Dot (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Cross (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE FloatV V3Length (const Vec3V a)
PX_FORCE_INLINE FloatV V3LengthSq (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Normalize (const Vec3V a)
PX_FORCE_INLINE Vec3V V3NormalizeSafe (const Vec3V a, const Vec3V unsafeReturnValue)
PX_FORCE_INLINE FloatV V3SumElems (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Sel (const BoolV c, const Vec3V a, const Vec3V b)
PX_FORCE_INLINE BoolV V3IsGrtr (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE BoolV V3IsGrtrOrEq (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE BoolV V3IsEq (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Max (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Min (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE FloatV V3ExtractMax (const Vec3V a)
PX_FORCE_INLINE FloatV V3ExtractMin (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Clamp (const Vec3V a, const Vec3V minV, const Vec3V maxV)
PX_FORCE_INLINE Vec3V V3Sign (const Vec3V a)
PX_FORCE_INLINE PxU32 V3AllGrtr (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE PxU32 V3AllGrtrOrEq (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE PxU32 V3AllEq (const Vec3V a, const Vec3V b)
PX_FORCE_INLINE PxU32 V3OutOfBounds (const Vec3V a, const Vec3V min, const Vec3V max)
PX_FORCE_INLINE PxU32 V3InBounds (const Vec3V a, const Vec3V min, const Vec3V max)
PX_FORCE_INLINE PxU32 V3OutOfBounds (const Vec3V a, const Vec3V bounds)
PX_FORCE_INLINE PxU32 V3InBounds (const Vec3V a, const Vec3V bounds)
PX_FORCE_INLINE Vec3V V3Round (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Sin (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Cos (const Vec3V a)
PX_FORCE_INLINE Vec3V V3PermYZZ (const Vec3V a)
PX_FORCE_INLINE Vec3V V3PermXYX (const Vec3V a)
PX_FORCE_INLINE Vec3V V3PermYZX (const Vec3V a)
PX_FORCE_INLINE Vec3V V3PermZXY (const Vec3V a)
PX_FORCE_INLINE Vec3V V3PermZZY (const Vec3V a)
PX_FORCE_INLINE Vec3V V3PermYXX (const Vec3V a)
PX_FORCE_INLINE Vec3V V3Perm_Zero_1Z_0Y (const Vec3V v0, const Vec3V v1)
PX_FORCE_INLINE Vec3V V3Perm_0Z_Zero_1X (const Vec3V v0, const Vec3V v1)
PX_FORCE_INLINE Vec3V V3Perm_1Y_0X_Zero (const Vec3V v0, const Vec3V v1)
PX_FORCE_INLINE void V3Transpose (Vec3V &col0, Vec3V &col1, Vec3V &col2)
PX_FORCE_INLINE Vec4V V4Splat (const FloatV f)
PX_FORCE_INLINE Vec4V V4Merge (const FloatV *const f)
PX_FORCE_INLINE Vec4V V4Merge (const FloatVArg x, const FloatVArg y, const FloatVArg z, const FloatVArg w)
PX_FORCE_INLINE Vec4V V4MergeW (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
PX_FORCE_INLINE Vec4V V4MergeZ (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
PX_FORCE_INLINE Vec4V V4MergeY (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
PX_FORCE_INLINE Vec4V V4MergeX (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
PX_FORCE_INLINE Vec4V V4UnpackXY (const Vec4VArg a, const Vec4VArg b)
PX_FORCE_INLINE Vec4V V4UnpackZW (const Vec4VArg a, const Vec4VArg b)
PX_FORCE_INLINE Vec4V V4UnitW ()
PX_FORCE_INLINE Vec4V V4UnitY ()
PX_FORCE_INLINE Vec4V V4UnitZ ()
PX_FORCE_INLINE FloatV V4GetX (const Vec4V f)
PX_FORCE_INLINE FloatV V4GetY (const Vec4V f)
PX_FORCE_INLINE FloatV V4GetZ (const Vec4V f)
PX_FORCE_INLINE FloatV V4GetW (const Vec4V f)
PX_FORCE_INLINE Vec4V V4SetX (const Vec4V v, const FloatV f)
PX_FORCE_INLINE Vec4V V4SetY (const Vec4V v, const FloatV f)
PX_FORCE_INLINE Vec4V V4SetZ (const Vec4V v, const FloatV f)
PX_FORCE_INLINE Vec4V V4SetW (const Vec4V v, const FloatV f)
PX_FORCE_INLINE Vec4V V4ClearW (const Vec4V v)
template<int elementIndex>
PX_FORCE_INLINE Vec4V V4SplatElement (Vec4V a)
PX_FORCE_INLINE void V4WriteX (Vec4V &v, const PxF32 f)
PX_FORCE_INLINE void V4WriteY (Vec4V &v, const PxF32 f)
PX_FORCE_INLINE void V4WriteZ (Vec4V &v, const PxF32 f)
PX_FORCE_INLINE void V4WriteW (Vec4V &v, const PxF32 f)
PX_FORCE_INLINE void V4WriteXYZ (Vec4V &v, const PxVec3 &f)
PX_FORCE_INLINE PxF32 V4ReadX (const Vec4V &v)
PX_FORCE_INLINE PxF32 V4ReadY (const Vec4V &v)
PX_FORCE_INLINE PxF32 V4ReadZ (const Vec4V &v)
PX_FORCE_INLINE PxF32 V4ReadW (const Vec4V &v)
PX_FORCE_INLINE const PxVec3 & V4ReadXYZ (const Vec4V &v)
PX_FORCE_INLINE Vec4V V4Zero ()
PX_FORCE_INLINE Vec4V V4One ()
PX_FORCE_INLINE Vec4V V4Eps ()
PX_FORCE_INLINE Vec4V V4Neg (const Vec4V c)
PX_FORCE_INLINE Vec4V V4Add (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Sub (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Scale (const Vec4V a, const FloatV b)
PX_FORCE_INLINE Vec4V V4Mul (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4ScaleInv (const Vec4V a, const FloatV b)
PX_FORCE_INLINE Vec4V V4Div (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4ScaleInvFast (const Vec4V a, const FloatV b)
PX_FORCE_INLINE Vec4V V4DivFast (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Recip (const Vec4V a)
PX_FORCE_INLINE Vec4V V4RecipFast (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Rsqrt (const Vec4V a)
PX_FORCE_INLINE Vec4V V4RsqrtFast (const Vec4V a)
PX_FORCE_INLINE Vec4V V4ScaleAdd (const Vec4V a, const FloatV b, const Vec4V c)
PX_FORCE_INLINE Vec4V V4NegScaleSub (const Vec4V a, const FloatV b, const Vec4V c)
PX_FORCE_INLINE Vec4V V4MulAdd (const Vec4V a, const Vec4V b, const Vec4V c)
PX_FORCE_INLINE Vec4V V4NegMulSub (const Vec4V a, const Vec4V b, const Vec4V c)
PX_FORCE_INLINE Vec4V V4Abs (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Andc (const Vec4V a, const VecU32V b)
PX_FORCE_INLINE FloatV V4Dot (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE FloatV V4Dot3 (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Cross (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE FloatV V4Length (const Vec4V a)
PX_FORCE_INLINE FloatV V4LengthSq (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Normalize (const Vec4V a)
PX_FORCE_INLINE Vec4V V4NormalizeSafe (const Vec4V a, const Vec4V unsafeReturnValue)
PX_FORCE_INLINE Vec4V V4NormalizeFast (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Sel (const BoolV c, const Vec4V a, const Vec4V b)
PX_FORCE_INLINE BoolV V4IsGrtr (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE BoolV V4IsGrtrOrEq (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE BoolV V4IsEq (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Max (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Min (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE FloatV V4ExtractMax (const Vec4V a)
PX_FORCE_INLINE FloatV V4ExtractMin (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Clamp (const Vec4V a, const Vec4V minV, const Vec4V maxV)
PX_FORCE_INLINE PxU32 V4AllGrtr (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE PxU32 V4AllGrtrOrEq (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE PxU32 V4AllGrtrOrEq3 (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE PxU32 V4AllEq (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE PxU32 V4AnyGrtr3 (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Vec4V V4Round (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Sin (const Vec4V a)
PX_FORCE_INLINE Vec4V V4Cos (const Vec4V a)
PX_FORCE_INLINE Vec4V V4PermYXWZ (const Vec4V v)
PX_FORCE_INLINE Vec4V V4PermXZXZ (const Vec4V v)
PX_FORCE_INLINE Vec4V V4PermYWYW (const Vec4V v)
PX_FORCE_INLINE Vec4V V4PermYZXW (const Vec4V v)
PX_FORCE_INLINE Vec4V V4PermZWXY (const Vec4V a)
template<PxU8 x, PxU8 y, PxU8 z, PxU8 w>
PX_FORCE_INLINE Vec4V V4Perm (const Vec4V a)
PX_FORCE_INLINE QuatV QuatV_From_RotationAxisAngle (const Vec3V u, const FloatV a)
PX_FORCE_INLINE QuatV QuatNormalize (const QuatV q)
PX_FORCE_INLINE FloatV QuatLength (const QuatV q)
PX_FORCE_INLINE FloatV QuatLengthSq (const QuatV q)
PX_FORCE_INLINE FloatV QuatDot (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatConjugate (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetImaginaryPart (const QuatV q)
PX_FORCE_INLINE Mat33V QuatGetMat33V (const QuatVArg q)
PX_FORCE_INLINE void QuatGetMat33V (const QuatVArg q, Vec3V &column0, Vec3V &column1, Vec3V &column2)
PX_FORCE_INLINE QuatV Mat33GetQuatV (const Mat33V &a)
PX_FORCE_INLINE Vec3V QuatGetBasisVector0 (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetBasisVector1 (const QuatV q)
PX_FORCE_INLINE Vec3V QuatGetBasisVector2 (const QuatV q)
PX_FORCE_INLINE Vec3V QuatRotate (const QuatV q, const Vec3V v)
PX_FORCE_INLINE Vec3V QuatRotateInv (const QuatV q, const Vec3V v)
PX_FORCE_INLINE QuatV QuatMul (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatAdd (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatNeg (const QuatV q)
PX_FORCE_INLINE QuatV QuatSub (const QuatV a, const QuatV b)
PX_FORCE_INLINE QuatV QuatScale (const QuatV a, const FloatV b)
PX_FORCE_INLINE QuatV QuatMerge (const FloatV *const v)
PX_FORCE_INLINE QuatV QuatMerge (const FloatVArg x, const FloatVArg y, const FloatVArg z, const FloatVArg w)
PX_FORCE_INLINE QuatV QuatIdentity ()
PX_FORCE_INLINE bool isFiniteQuatV (const QuatV q)
PX_FORCE_INLINE bool isValidQuatV (const QuatV q)
PX_FORCE_INLINE bool isSaneQuatV (const QuatV q)
PX_FORCE_INLINE BoolV BFFFF ()
PX_FORCE_INLINE BoolV BFFFT ()
PX_FORCE_INLINE BoolV BFFTF ()
PX_FORCE_INLINE BoolV BFFTT ()
PX_FORCE_INLINE BoolV BFTFF ()
PX_FORCE_INLINE BoolV BFTFT ()
PX_FORCE_INLINE BoolV BFTTF ()
PX_FORCE_INLINE BoolV BFTTT ()
PX_FORCE_INLINE BoolV BTFFF ()
PX_FORCE_INLINE BoolV BTFFT ()
PX_FORCE_INLINE BoolV BTFTF ()
PX_FORCE_INLINE BoolV BTFTT ()
PX_FORCE_INLINE BoolV BTTFF ()
PX_FORCE_INLINE BoolV BTTFT ()
PX_FORCE_INLINE BoolV BTTTF ()
PX_FORCE_INLINE BoolV BTTTT ()
PX_FORCE_INLINE BoolV BWMask ()
PX_FORCE_INLINE BoolV BXMask ()
PX_FORCE_INLINE BoolV BYMask ()
PX_FORCE_INLINE BoolV BZMask ()
PX_FORCE_INLINE BoolV BGetX (const BoolV f)
PX_FORCE_INLINE BoolV BGetY (const BoolV f)
PX_FORCE_INLINE BoolV BGetZ (const BoolV f)
PX_FORCE_INLINE BoolV BGetW (const BoolV f)
template<int elementIndex>
PX_FORCE_INLINE BoolV BSplatElement (Vec4V a)
PX_FORCE_INLINE BoolV BAnd (const BoolV a, const BoolV b)
PX_FORCE_INLINE BoolV BOr (const BoolV a, const BoolV b)
PX_FORCE_INLINE BoolV BNot (const BoolV a)
PX_FORCE_INLINE BoolV BAllTrue4 (const BoolV a)
PX_FORCE_INLINE BoolV BAnyTrue4 (const BoolV a)
PX_FORCE_INLINE BoolV BAllTrue3 (const BoolV a)
PX_FORCE_INLINE BoolV BAnyTrue3 (const BoolV a)
PX_FORCE_INLINE PxU32 BAllEq (const BoolV a, const BoolV b)
PX_FORCE_INLINE PxU32 BAllEqTTTT (const BoolV a)
PX_FORCE_INLINE PxU32 BAllEqFFFF (const BoolV a)
PX_FORCE_INLINE PxU32 BGetBitMask (const BoolV a)
PX_FORCE_INLINE VecI32V VecI32V_Zero ()
PX_FORCE_INLINE VecI32V VecI32V_One ()
PX_FORCE_INLINE VecI32V VecI32V_Two ()
PX_FORCE_INLINE VecI32V VecI32V_MinusOne ()
PX_FORCE_INLINE VecShiftV VecI32V_PrepareShift (const VecI32VArg shift)
PX_FORCE_INLINE VecI32V VecI32V_LeftShift (const VecI32VArg a, const VecShiftVArg shift)
PX_FORCE_INLINE VecI32V VecI32V_RightShift (const VecI32VArg a, const VecShiftVArg shift)
PX_FORCE_INLINE VecI32V VecI32V_Add (const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE VecI32V VecI32V_Or (const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE VecI32V VecI32V_GetX (const VecI32VArg a)
PX_FORCE_INLINE VecI32V VecI32V_GetY (const VecI32VArg a)
PX_FORCE_INLINE VecI32V VecI32V_GetZ (const VecI32VArg a)
PX_FORCE_INLINE VecI32V VecI32V_GetW (const VecI32VArg a)
PX_FORCE_INLINE VecI32V VecI32V_Sub (const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE BoolV VecI32V_IsGrtr (const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE BoolV VecI32V_IsEq (const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE VecI32V V4I32Sel (const BoolV c, const VecI32V a, const VecI32V b)
PX_FORCE_INLINE VecU32V U4Zero ()
PX_FORCE_INLINE VecU32V U4One ()
PX_FORCE_INLINE VecU32V U4Two ()
PX_FORCE_INLINE BoolV V4IsEqU32 (const VecU32V a, const VecU32V b)
PX_FORCE_INLINE VecU32V V4U32Sel (const BoolV c, const VecU32V a, const VecU32V b)
PX_FORCE_INLINE VecU32V V4U32or (VecU32V a, VecU32V b)
PX_FORCE_INLINE VecU32V V4U32xor (VecU32V a, VecU32V b)
PX_FORCE_INLINE VecU32V V4U32and (VecU32V a, VecU32V b)
PX_FORCE_INLINE VecU32V V4U32Andc (VecU32V a, VecU32V b)
PX_FORCE_INLINE VecU32V V4IsGrtrV32u (const Vec4V a, const Vec4V b)
PX_FORCE_INLINE Mat33V M33Load (const PxMat33 &m)
PX_FORCE_INLINE Vec3V M33MulV3 (const Mat33V &a, const Vec3V b)
PX_FORCE_INLINE Vec3V M33MulV3AddV3 (const Mat33V &A, const Vec3V b, const Vec3V c)
PX_FORCE_INLINE Vec3V M33TrnspsMulV3 (const Mat33V &a, const Vec3V b)
PX_FORCE_INLINE Mat33V M33MulM33 (const Mat33V &a, const Mat33V &b)
PX_FORCE_INLINE Mat33V M33Add (const Mat33V &a, const Mat33V &b)
PX_FORCE_INLINE Mat33V M33Sub (const Mat33V &a, const Mat33V &b)
PX_FORCE_INLINE Mat33V M33Neg (const Mat33V &a)
PX_FORCE_INLINE Mat33V M33Abs (const Mat33V &a)
PX_FORCE_INLINE Mat33V M33Inverse (const Mat33V &a)
PX_FORCE_INLINE Mat33V M33Trnsps (const Mat33V &a)
PX_FORCE_INLINE Mat33V M33Identity ()
PX_FORCE_INLINE Mat33V M33Diagonal (const Vec3VArg)
PX_FORCE_INLINE Vec4V V3Dot4 (const Vec3VArg a0, const Vec3VArg b0, const Vec3VArg a1, const Vec3VArg b1, const Vec3VArg a2, const Vec3VArg b2, const Vec3VArg a3, const Vec3VArg b3)
PX_FORCE_INLINE Vec3V V3LoadU_SafeReadW (const PxVec3 &f)
PX_FORCE_INLINE Vec4V Vec4V_From_FloatV (FloatV f)
PX_FORCE_INLINE Vec3V Vec3V_From_FloatV (FloatV f)
PX_FORCE_INLINE Vec3V Vec3V_From_FloatV_WUndefined (FloatV f)
PX_FORCE_INLINE void Store_From_BoolV (const BoolV b, PxU32 *b2)
PX_FORCE_INLINE VecCrossV V3PrepareCross (const Vec3VArg normal)
PX_FORCE_INLINE Vec3V V3NormalizeFast (const Vec3V a)
PX_FORCE_INLINE Vec4V V4UnitX ()
PX_FORCE_INLINE Vec4V V4Sqrt (const Vec4V a)
PX_FORCE_INLINE FloatV V4SumElements (const Vec4V a)
PX_FORCE_INLINE void V4Transpose (Vec4V &col0, Vec4V &col1, Vec4V &col2, Vec4V &col3)
PX_FORCE_INLINE BoolV BSetX (const BoolV v, const BoolV f)
PX_FORCE_INLINE BoolV BSetY (const BoolV v, const BoolV f)
PX_FORCE_INLINE BoolV BSetZ (const BoolV v, const BoolV f)
PX_FORCE_INLINE BoolV BSetW (const BoolV v, const BoolV f)
template<int index>
BoolV BSplatElement (BoolV a)
PX_FORCE_INLINE BoolV BAndNot (const BoolV a, const BoolV b)
PX_FORCE_INLINE Mat33V M33Scale (const Mat33V &a, const FloatV &b)
PX_FORCE_INLINE Mat33V Mat33V_From_PxMat33 (const PxMat33 &m)
PX_FORCE_INLINE void PxMat33_From_Mat33V (const Mat33V &m, PxMat33 &out)
PX_FORCE_INLINE Vec3V M34MulV3 (const Mat34V &a, const Vec3V b)
PX_FORCE_INLINE Vec3V M34Mul33V3 (const Mat34V &a, const Vec3V b)
PX_FORCE_INLINE Vec3V M34TrnspsMul33V3 (const Mat34V &a, const Vec3V b)
PX_FORCE_INLINE Mat34V M34MulM34 (const Mat34V &a, const Mat34V &b)
PX_FORCE_INLINE Mat33V M34MulM33 (const Mat34V &a, const Mat33V &b)
PX_FORCE_INLINE Mat33V M34Mul33V3 (const Mat34V &a, const Mat33V &b)
PX_FORCE_INLINE Mat33V M34Mul33MM34 (const Mat34V &a, const Mat34V &b)
PX_FORCE_INLINE Mat34V M34Add (const Mat34V &a, const Mat34V &b)
PX_FORCE_INLINE Mat33V M34Trnsps33 (const Mat34V &a)
PX_FORCE_INLINE Vec4V M44MulV4 (const Mat44V &a, const Vec4V b)
PX_FORCE_INLINE Vec4V M44TrnspsMulV4 (const Mat44V &a, const Vec4V b)
PX_FORCE_INLINE Mat44V M44MulM44 (const Mat44V &a, const Mat44V &b)
PX_FORCE_INLINE Mat44V M44Add (const Mat44V &a, const Mat44V &b)
PX_FORCE_INLINE Mat44V M44Inverse (const Mat44V &a)
PX_FORCE_INLINE Mat44V M44Trnsps (const Mat44V &a)
PX_FORCE_INLINE void V4U32StoreAligned (VecU32V val, VecU32V *address)
PX_FORCE_INLINE VecU16V V4U16LoadAligned (VecU16V *addr)
PX_FORCE_INLINE VecU16V V4U16LoadUnaligned (VecU16V *addr)
PX_FORCE_INLINE VecU16V V4U16CompareGt (VecU16V a, VecU16V b)
PX_FORCE_INLINE VecU16V V4I16CompareGt (VecU16V a, VecU16V b)
template<int index>
PX_FORCE_INLINE VecU32V V4U32SplatElement (VecU32V a)
PX_FORCE_INLINE VecI32V I4LoadXYZW (const PxI32 &x, const PxI32 &y, const PxI32 &z, const PxI32 &w)
PX_FORCE_INLINE VecI32V VecI32V_LeftShift (const VecI32VArg a, const PxU32 count)
PX_FORCE_INLINE VecI32V VecI32V_RightShift (const VecI32VArg a, const PxU32 count)
PX_FORCE_INLINE VecI32V VecI32V_And (const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE VecI32V VecI32V_Sel (const BoolV c, const VecI32VArg a, const VecI32VArg b)
PX_FORCE_INLINE VecI32V VecI32V_Merge (const VecI32VArg a, const VecI32VArg b, const VecI32VArg c, const VecI32VArg d)
PX_FORCE_INLINE void PxI32_From_VecI32V (const VecI32VArg a, PxI32 *i)
PX_FORCE_INLINE bool isValidFloatV (const FloatV a)
PX_FORCE_INLINE bool isAligned16 (const void *a)
PX_FORCE_INLINE bool hasZeroElementinFloatV (const FloatV a)
PX_FORCE_INLINE bool hasZeroElementInVec3V (const Vec3V a)
PX_FORCE_INLINE bool hasZeroElementInVec4V (const Vec4V a)
PX_FORCE_INLINE FloatV FLoadA (const PxF32 *const f)
PX_FORCE_INLINE void Store_From_BoolV (const BoolV a, PxU32 *PX_RESTRICT f)
PX_FORCE_INLINE FloatV IZero ()
PX_FORCE_INLINE FloatV IOne ()
PX_FORCE_INLINE FloatV ITwo ()
PX_FORCE_INLINE FloatV IThree ()
PX_FORCE_INLINE FloatV IFour ()
template<int n>
PX_FORCE_INLINE float32x2_t recip_newton (const float32x2_t &in)
template<int n>
PX_FORCE_INLINE float32x4_t recipq_newton (const float32x4_t &in)
template<int n>
PX_FORCE_INLINE float32x2_t rsqrt_newton (const float32x2_t &in)
template<int n>
PX_FORCE_INLINE float32x4_t rsqrtq_newton (const float32x4_t &in)
PX_FORCE_INLINE Vec3V V3Add (const Vec3V a, const FloatV b)
PX_FORCE_INLINE Vec3V V3Sub (const Vec3V a, const FloatV b)
PX_FORCE_INLINE VecCrossV V3PrepareCross (const Vec3V a)
PX_FORCE_INLINE Mat33V PromoteVec3V (const Vec3V v)
PX_FORCE_INLINE Vec4V V4LoadAligned (Vec4V *addr)
PX_FORCE_INLINE Vec4V V4LoadUnaligned (Vec4V *addr)
PX_FORCE_INLINE VecU16V V4I16CompareGt (VecI16V a, VecI16V b)
template<int index>
PX_FORCE_INLINE BoolV BSplatElement (BoolV a)
PX_FORCE_INLINE Vec4V V4Ceil (const Vec4V in)
PX_FORCE_INLINE Vec4V V4Floor (const Vec4V in)
PX_FORCE_INLINE VecU32V V4ConvertToU32VSaturate (const Vec4V in, PxU32 power)
PX_FORCE_INLINE __m128 m128_I2F (__m128i n)
PX_FORCE_INLINE __m128i m128_F2I (__m128 n)
PX_FORCE_INLINE bool isFiniteLength (const Vec3V a)
PX_FORCE_INLINE bool isAligned16 (void *a)
PX_FORCE_INLINE Vec3V V3Cross (const VecCrossV &a, const Vec3V b)
PX_FORCE_INLINE Vec3V V3Cross (const Vec3V a, const VecCrossV &b)
PX_FORCE_INLINE Vec3V V3Cross (const VecCrossV &a, const VecCrossV &b)
PX_FORCE_INLINE Mat34V M34Inverse (const Mat34V &a)
PX_FORCE_INLINE Vec4V V4ConvertFromI32V (const VecI32V in)
__declspec (align(16)) struct PX_VECTORF32
Variables
PX_GLOBALCONST PX_VECTORF32 g_PXSinCoefficients0 = { { 1.0f, -0.166666667f, 8.333333333e-3f, -1.984126984e-4f } }
PX_GLOBALCONST PX_VECTORF32 g_PXSinCoefficients1 = { { 2.755731922e-6f, -2.505210839e-8f, 1.605904384e-10f, -7.647163732e-13f } }
PX_GLOBALCONST PX_VECTORF32 g_PXSinCoefficients2 = { { 2.811457254e-15f, -8.220635247e-18f, 1.957294106e-20f, -3.868170171e-23f } }
PX_GLOBALCONST PX_VECTORF32 g_PXCosCoefficients0 = { { 1.0f, -0.5f, 4.166666667e-2f, -1.388888889e-3f } }
PX_GLOBALCONST PX_VECTORF32 g_PXCosCoefficients1 = { { 2.480158730e-5f, -2.755731922e-7f, 2.087675699e-9f, -1.147074560e-11f } }
PX_GLOBALCONST PX_VECTORF32 g_PXCosCoefficients2 = { { 4.779477332e-14f, -1.561920697e-16f, 4.110317623e-19f, -8.896791392e-22f } }
PX_GLOBALCONST PX_VECTORF32 g_PXReciprocalTwoPi = { { PxInvTwoPi, PxInvTwoPi, PxInvTwoPi, PxInvTwoPi } }
PX_GLOBALCONST PX_VECTORF32 g_PXTwoPi = { { PxTwoPi, PxTwoPi, PxTwoPi, PxTwoPi } }
Typedef Documentation
BoolV
typedef __m128 physx::aos::BoolV
FloatV
typedef __m128 physx::aos::FloatV
QuatV
typedef __m128 physx::aos::QuatV
UnionM128
typedef union physx::aos::UnionM128 physx::aos::UnionM128
Vec3V
typedef __m128 physx::aos::Vec3V
Vec4V
typedef __m128 physx::aos::Vec4V
VecI16V
typedef UnionM128 physx::aos::VecI16V
VecI32V
typedef __m128i physx::aos::VecI32V
VecShiftV
typedef VecI32V physx::aos::VecShiftV
VecU16V
typedef UnionM128 physx::aos::VecU16V
VecU32V
typedef UnionM128 physx::aos::VecU32V
VecU8V
typedef UnionM128 physx::aos::VecU8V
Function Documentation
__declspec()
physx::aos::__declspec (align(16))
BAllEq()
PX_FORCE_INLINE PxU32 physx::aos::BAllEq (const BoolV a, const BoolV b)
Referenced by BAllEqFFFF(), and BAllEqTTTT().
BAllEqFFFF()
PX_FORCE_INLINE PxU32 physx::aos::BAllEqFFFF (const BoolV a)
References BAllEq(), and BFFFF().
BAllEqTTTT()
PX_FORCE_INLINE PxU32 physx::aos::BAllEqTTTT (const BoolV a)
References BAllEq(), and BTTTT().
Referenced by aos::isSaneQuatV(), and aos::isValidQuatV().
BAllTrue3()
PX_FORCE_INLINE BoolV physx::aos::BAllTrue3 (const BoolV a)
References BFFFF(), and BTTTT().
Referenced by aos::Mat33GetQuatV().
BAllTrue4()
PX_FORCE_INLINE BoolV physx::aos::BAllTrue4 (const BoolV a)
References BFFFF(), and BTTTT().
BAnd()
PX_FORCE_INLINE BoolV physx::aos::BAnd (const BoolV a, const BoolV b)
References BOOL_TO_U32.
BAndNot()
PX_FORCE_INLINE BoolV physx::aos::BAndNot (const BoolV a, const BoolV b)
BAnyTrue3()
PX_FORCE_INLINE BoolV physx::aos::BAnyTrue3 (const BoolV a)
References BFFFF(), and BTTTT().
BAnyTrue4()
PX_FORCE_INLINE BoolV physx::aos::BAnyTrue4 (const BoolV a)
References BFFFF(), and BTTTT().
BFFFF()
PX_FORCE_INLINE BoolV physx::aos::BFFFF ()
References FALSE_TO_U32.
Referenced by BAllEqFFFF(), BAllTrue3(), BAllTrue4(), BAnyTrue3(), BAnyTrue4(), and BLoad().
BFFFT()
PX_FORCE_INLINE BoolV physx::aos::BFFFT ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by BWMask().
BFFTF()
PX_FORCE_INLINE BoolV physx::aos::BFFTF ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by BZMask().
BFFTT()
PX_FORCE_INLINE BoolV physx::aos::BFFTT ()
References FALSE_TO_U32, and TRUE_TO_U32.
BFTFF()
PX_FORCE_INLINE BoolV physx::aos::BFTFF ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by BYMask(), and PromoteVec3V().
BFTFT()
PX_FORCE_INLINE BoolV physx::aos::BFTFT ()
References FALSE_TO_U32, and TRUE_TO_U32.
BFTTF()
PX_FORCE_INLINE BoolV physx::aos::BFTTF ()
References FALSE_TO_U32, and TRUE_TO_U32.
BFTTT()
PX_FORCE_INLINE BoolV physx::aos::BFTTT ()
References FALSE_TO_U32, and TRUE_TO_U32.
BGetBitMask()
PX_FORCE_INLINE PxU32 physx::aos::BGetBitMask (const BoolV a)
Get BoolV as bits set in an PxU32. A bit in the output is set if the element is 'true' in the input. There is a bit for each element in a, with element 0s value held in bit0, element 1 in bit 1s and so forth. If nothing is true in the input it will return 0, and if all are true if will return 0xf. NOTE! That performance of the function varies considerably by platform, thus it is recommended to use where your algorithm really needs a BoolV in an integer variable.
BGetW()
PX_FORCE_INLINE BoolV physx::aos::BGetW (const BoolV f)
BGetX()
PX_FORCE_INLINE BoolV physx::aos::BGetX (const BoolV f)
BGetY()
PX_FORCE_INLINE BoolV physx::aos::BGetY (const BoolV f)
BGetZ()
PX_FORCE_INLINE BoolV physx::aos::BGetZ (const BoolV f)
BLoad() [1/2]
PX_FORCE_INLINE BoolV physx::aos::BLoad (const bool f)
References BFFFF(), BOOL_TO_U32, and BTTTT().
Referenced by FIsEq(), FIsGrtr(), and FIsGrtrOrEq().
BLoad() [2/2]
PX_FORCE_INLINE BoolV physx::aos::BLoad (const bool *const f)
References BOOL_TO_U32.
BNot()
PX_FORCE_INLINE BoolV physx::aos::BNot (const BoolV a)
BOr()
PX_FORCE_INLINE BoolV physx::aos::BOr (const BoolV a, const BoolV b)
References BOOL_TO_U32.
BSetW()
PX_FORCE_INLINE BoolV physx::aos::BSetW (const BoolV v, const BoolV f)
BSetX()
PX_FORCE_INLINE BoolV physx::aos::BSetX (const BoolV v, const BoolV f)
BSetY()
PX_FORCE_INLINE BoolV physx::aos::BSetY (const BoolV v, const BoolV f)
BSetZ()
PX_FORCE_INLINE BoolV physx::aos::BSetZ (const BoolV v, const BoolV f)
BSplatElement() [1/3]
template<int elementIndex> PX_FORCE_INLINE BoolV physx::aos::BSplatElement (Vec4V a)
BSplatElement() [2/3]
template<int index> BoolV physx::aos::BSplatElement (BoolV a)
BSplatElement() [3/3]
template<int index> PX_FORCE_INLINE BoolV physx::aos::BSplatElement (BoolV a)
BStoreA()
PX_FORCE_INLINE void physx::aos::BStoreA (const BoolV b, PxU32 * f)
BTFFF()
PX_FORCE_INLINE BoolV physx::aos::BTFFF ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by BXMask(), and PromoteVec3V().
BTFFT()
PX_FORCE_INLINE BoolV physx::aos::BTFFT ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by M34Inverse().
BTFTF()
PX_FORCE_INLINE BoolV physx::aos::BTFTF ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by PromoteVec3V().
BTFTT()
PX_FORCE_INLINE BoolV physx::aos::BTFTT ()
References FALSE_TO_U32, and TRUE_TO_U32.
BTTFF()
PX_FORCE_INLINE BoolV physx::aos::BTTFF ()
References FALSE_TO_U32, and TRUE_TO_U32.
BTTFT()
PX_FORCE_INLINE BoolV physx::aos::BTTFT ()
References FALSE_TO_U32, and TRUE_TO_U32.
BTTTF()
PX_FORCE_INLINE BoolV physx::aos::BTTTF ()
References FALSE_TO_U32, and TRUE_TO_U32.
Referenced by M34Inverse().
BTTTT()
PX_FORCE_INLINE BoolV physx::aos::BTTTT ()
References TRUE_TO_U32.
Referenced by BAllEqTTTT(), BAllTrue3(), BAllTrue4(), BAnyTrue3(), BAnyTrue4(), and BLoad().
BWMask()
PX_FORCE_INLINE BoolV physx::aos::BWMask ()
References BFFFT().
BXMask()
PX_FORCE_INLINE BoolV physx::aos::BXMask ()
References BTFFF().
BYMask()
PX_FORCE_INLINE BoolV physx::aos::BYMask ()
References BFTFF().
BZMask()
PX_FORCE_INLINE BoolV physx::aos::BZMask ()
References BFFTF().
FAbs()
PX_FORCE_INLINE FloatV physx::aos::FAbs (const FloatV a)
References PxAbs().
Referenced by aos::isSaneQuatV(), and aos::isValidQuatV().
FAdd()
PX_FORCE_INLINE FloatV physx::aos::FAdd (const FloatV a, const FloatV b)
Referenced by FScaleAdd(), aos::Mat33GetQuatV(), aos::QuatGetMat33V(), and QuatGetMat33V().
FAllEq()
PX_FORCE_INLINE PxU32 physx::aos::FAllEq (const FloatV a, const FloatV b)
References BOOL_TO_U32.
Referenced by isFiniteLength().
FAllGrtr()
PX_FORCE_INLINE PxU32 physx::aos::FAllGrtr (const FloatV a, const FloatV b)
References BOOL_TO_U32.
FAllGrtrOrEq()
PX_FORCE_INLINE PxU32 physx::aos::FAllGrtrOrEq (const FloatV a, const FloatV b)
References BOOL_TO_U32.
Referenced by aos::Mat33GetQuatV().
FClamp()
PX_FORCE_INLINE FloatV physx::aos::FClamp (const FloatV a, const FloatV minV, const FloatV maxV)
References FMax(), and FMin().
FCos()
PX_FORCE_INLINE FloatV physx::aos::FCos (const FloatV a)
FDiv()
PX_FORCE_INLINE FloatV physx::aos::FDiv (const FloatV a, const FloatV b)
References VECMATHAOS_ASSERT.
FDivFast()
PX_FORCE_INLINE FloatV physx::aos::FDivFast (const FloatV a, const FloatV b)
References VECMATHAOS_ASSERT.
FEps()
PX_FORCE_INLINE FloatV physx::aos::FEps ()
References FLoad(), and PX_EPS_REAL.
FEps6()
PX_FORCE_INLINE FloatV physx::aos::FEps6 ()
References FLoad().
FHalf()
PX_FORCE_INLINE FloatV physx::aos::FHalf ()
References FLoad().
FInBounds() [1/2]
PX_FORCE_INLINE PxU32 physx::aos::FInBounds (const FloatV a, const FloatV min, const FloatV max)
References BOOL_TO_U32.
Referenced by FInBounds().
FInBounds() [2/2]
PX_FORCE_INLINE PxU32 physx::aos::FInBounds (const FloatV a, const FloatV bounds)
References FInBounds(), and FNeg().
FIsEq()
PX_FORCE_INLINE BoolV physx::aos::FIsEq (const FloatV a, const FloatV b)
References BLoad().
FIsGrtr()
PX_FORCE_INLINE BoolV physx::aos::FIsGrtr (const FloatV a, const FloatV b)
References BLoad().
Referenced by aos::isSaneQuatV(), and aos::isValidQuatV().
FIsGrtrOrEq()
PX_FORCE_INLINE BoolV physx::aos::FIsGrtrOrEq (const FloatV a, const FloatV b)
References BLoad().
FLoad()
PX_FORCE_INLINE FloatV physx::aos::FLoad (const PxF32 f)
Referenced by FEps(), FEps6(), FHalf(), FMax(), FNegMax(), FOne(), FZero(), aos::isSaneQuatV(), aos::isValidQuatV(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatRotate(), aos::QuatRotateInv(), aos::QuatTransform(), and aos::QuatV_From_RotationAxisAngle().
FLoadA()
PX_FORCE_INLINE FloatV physx::aos::FLoadA (const PxF32 *const f)
References ASSERT_ISALIGNED16.
FMax() [1/2]
PX_FORCE_INLINE FloatV physx::aos::FMax ()
References FLoad(), and PX_MAX_REAL.
Referenced by FClamp(), and aos::PxTransformV::Invalidate().
FMax() [2/2]
PX_FORCE_INLINE FloatV physx::aos::FMax (const FloatV a, const FloatV b)
FMin()
PX_FORCE_INLINE FloatV physx::aos::FMin (const FloatV a, const FloatV b)
Referenced by FClamp().
FMul()
PX_FORCE_INLINE FloatV physx::aos::FMul (const FloatV a, const FloatV b)
Referenced by FNegScaleSub(), FScaleAdd(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatGetMat33V(), QuatGetMat33V(), aos::QuatMul(), and aos::QuatV_From_RotationAxisAngle().
FNeg()
PX_FORCE_INLINE FloatV physx::aos::FNeg (const FloatV f)
Referenced by FInBounds(), FOutOfBounds(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), and aos::QuatGetBasisVector2().
FNegMax()
PX_FORCE_INLINE FloatV physx::aos::FNegMax ()
References FLoad(), and PX_MAX_REAL.
FNegScaleSub()
PX_FORCE_INLINE FloatV physx::aos::FNegScaleSub (const FloatV a, const FloatV b, const FloatV c)
References FMul(), and FSub().
FOne()
PX_FORCE_INLINE FloatV physx::aos::FOne ()
References FLoad().
Referenced by physx::aos::internalWindowsSimd::FiniteTestEq(), physx::aos::internalUnitSSE2Simd::FiniteTestEq(), aos::isSaneQuatV(), aos::isValidQuatV(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatGetMat33V(), QuatGetMat33V(), and aos::QuatIdentity().
FOutOfBounds() [1/2]
PX_FORCE_INLINE PxU32 physx::aos::FOutOfBounds (const FloatV a, const FloatV min, const FloatV max)
References BOOL_TO_U32.
Referenced by FOutOfBounds().
FOutOfBounds() [2/2]
PX_FORCE_INLINE PxU32 physx::aos::FOutOfBounds (const FloatV a, const FloatV bounds)
References FNeg(), and FOutOfBounds().
FRecip()
PX_FORCE_INLINE FloatV physx::aos::FRecip (const FloatV a)
References VECMATHAOS_ASSERT.
Referenced by aos::Mat33GetQuatV().
FRecipFast()
PX_FORCE_INLINE FloatV physx::aos::FRecipFast (const FloatV a)
References VECMATHAOS_ASSERT.
FRound()
PX_FORCE_INLINE FloatV physx::aos::FRound (const FloatV a)
FRsqrt()
PX_FORCE_INLINE FloatV physx::aos::FRsqrt (const FloatV a)
References PxRecipSqrt(), and VECMATHAOS_ASSERT.
FRsqrtFast()
PX_FORCE_INLINE FloatV physx::aos::FRsqrtFast (const FloatV a)
References PxRecipSqrt(), and VECMATHAOS_ASSERT.
FScaleAdd()
PX_FORCE_INLINE FloatV physx::aos::FScaleAdd (const FloatV a, const FloatV b, const FloatV c)
References FAdd(), and FMul().
Referenced by aos::Mat33GetQuatV(), aos::QuatRotate(), aos::QuatRotateInv(), and aos::QuatTransform().
FSel()
PX_FORCE_INLINE FloatV physx::aos::FSel (const BoolV c, const FloatV a, const FloatV b)
Referenced by aos::Mat33GetQuatV().
FSin()
PX_FORCE_INLINE FloatV physx::aos::FSin (const FloatV a)
FSqrt()
PX_FORCE_INLINE FloatV physx::aos::FSqrt (const FloatV a)
References PxSqrt().
Referenced by aos::Mat33GetQuatV().
FStore()
PX_FORCE_INLINE void physx::aos::FStore (const FloatV a, PxF32 *PX_RESTRICT f)
FSub()
PX_FORCE_INLINE FloatV physx::aos::FSub (const FloatV a, const FloatV b)
Referenced by FNegScaleSub(), aos::isSaneQuatV(), aos::isValidQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatGetMat33V(), QuatGetMat33V(), aos::QuatMul(), and aos::QuatV_From_RotationAxisAngle().
FZero()
PX_FORCE_INLINE FloatV physx::aos::FZero ()
References FLoad().
Referenced by physx::aos::internalWindowsSimd::FiniteTestEq(), physx::aos::internalUnitSSE2Simd::FiniteTestEq(), physx::aos::internalWindowsSimd::hasZeroElementinFloatV(), physx::aos::internalWindowsSimd::hasZeroElementInVec3V(), physx::aos::internalWindowsSimd::hasZeroElementInVec4V(), isFiniteLength(), and aos::Mat33GetQuatV().
hasZeroElementinFloatV()
PX_FORCE_INLINE bool physx::aos::hasZeroElementinFloatV (const FloatV a)
References ASSERT_ISVALIDFLOATV.
hasZeroElementInVec3V()
PX_FORCE_INLINE bool physx::aos::hasZeroElementInVec3V (const Vec3V a)
hasZeroElementInVec4V()
PX_FORCE_INLINE bool physx::aos::hasZeroElementInVec4V (const Vec4V a)
I4Load()
PX_FORCE_INLINE VecI32V physx::aos::I4Load (const PxI32 i)
I4LoadA()
PX_FORCE_INLINE VecI32V physx::aos::I4LoadA (const PxI32 * i)
I4LoadU()
PX_FORCE_INLINE VecI32V physx::aos::I4LoadU (const PxI32 * i)
I4LoadXYZW()
PX_FORCE_INLINE VecI32V physx::aos::I4LoadXYZW (const PxI32 & x, const PxI32 & y, const PxI32 & z, const PxI32 & w)
I4StoreA()
PX_FORCE_INLINE void physx::aos::I4StoreA (const VecI32V iv, PxI32 * i)
IFour()
PX_FORCE_INLINE FloatV physx::aos::IFour ()
IOne()
PX_FORCE_INLINE FloatV physx::aos::IOne ()
isAligned16() [1/2]
PX_FORCE_INLINE bool physx::aos::isAligned16 (const void * a)
isAligned16() [2/2]
PX_FORCE_INLINE bool physx::aos::isAligned16 (void * a)
isFiniteFloatV()
PX_FORCE_INLINE bool physx::aos::isFiniteFloatV (const FloatV a)
References PxIsFinite().
isFiniteLength()
PX_FORCE_INLINE bool physx::aos::isFiniteLength (const Vec3V a)
References FAllEq(), FZero(), and V4LengthSq().
isFiniteQuatV()
PX_FORCE_INLINE bool physx::aos::isFiniteQuatV (const QuatV q)
Referenced by aos::PxTransformV::isFinite(), and aos::PxTransformV::isValid().
isFiniteVec3V()
PX_FORCE_INLINE bool physx::aos::isFiniteVec3V (const Vec3V a)
References PxIsFinite().
Referenced by aos::PxTransformV::isFinite(), and aos::PxTransformV::isValid().
isFiniteVec4V()
PX_FORCE_INLINE bool physx::aos::isFiniteVec4V (const Vec4V a)
References PxIsFinite().
Referenced by aos::isFiniteQuatV(), aos::isSaneQuatV(), and aos::isValidQuatV().
isSaneQuatV()
PX_FORCE_INLINE bool physx::aos::isSaneQuatV (const QuatV q)
Referenced by aos::PxTransformV::isSane(), and aos::PxTransformV::PxTransformV().
isValidFloatV()
PX_FORCE_INLINE bool physx::aos::isValidFloatV (const FloatV a)
isValidQuatV()
PX_FORCE_INLINE bool physx::aos::isValidQuatV (const QuatV q)
Referenced by aos::PxTransformV::isValid().
isValidVec3V()
PX_FORCE_INLINE bool physx::aos::isValidVec3V (const Vec3V a)
IThree()
PX_FORCE_INLINE FloatV physx::aos::IThree ()
ITwo()
PX_FORCE_INLINE FloatV physx::aos::ITwo ()
IZero()
PX_FORCE_INLINE FloatV physx::aos::IZero ()
m128_F2I()
PX_FORCE_INLINE __m128i physx::aos::m128_F2I (__m128 n)
m128_I2F()
PX_FORCE_INLINE __m128 physx::aos::m128_I2F (__m128i n)
M33Abs()
PX_FORCE_INLINE Mat33V physx::aos::M33Abs (const Mat33V & a)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and V3Abs().
M33Add()
PX_FORCE_INLINE Mat33V physx::aos::M33Add (const Mat33V & a, const Mat33V & b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and V3Add().
M33Diagonal()
PX_FORCE_INLINE Mat33V physx::aos::M33Diagonal (const Vec3VArg d)
References V3Mul(), V3UnitX(), V3UnitY(), and V3UnitZ().
M33Identity()
PX_FORCE_INLINE Mat33V physx::aos::M33Identity ()
References V3UnitX(), V3UnitY(), and V3UnitZ().
Referenced by aos::PxMatTransformV::PxMatTransformV().
M33Inverse()
PX_FORCE_INLINE Mat33V physx::aos::M33Inverse (const Mat33V & a)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, and physx::aos::Mat33V::col2.
M33Load()
PX_FORCE_INLINE Mat33V physx::aos::M33Load (const PxMat33 & m)
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, V3LoadU(), V4LoadU(), and Vec3V_From_Vec4V().
M33MulM33()
PX_FORCE_INLINE Mat33V physx::aos::M33MulM33 (const Mat33V & a, const Mat33V & b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and M33MulV3().
Referenced by aos::PxMatTransformV::transformInv().
M33MulV3()
PX_FORCE_INLINE Vec3V physx::aos::M33MulV3 (const Mat33V & a, const Vec3V b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, and physx::aos::Mat33V::col2.
Referenced by M33MulM33(), aos::PxMatTransformV::rotate(), and aos::PxMatTransformV::transform().
M33MulV3AddV3()
PX_FORCE_INLINE Vec3V physx::aos::M33MulV3AddV3 (const Mat33V & A, const Vec3V b, const Vec3V c)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, V3GetX(), V3GetY(), V3GetZ(), and V3ScaleAdd().
M33Neg()
PX_FORCE_INLINE Mat33V physx::aos::M33Neg (const Mat33V & a)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and V3Neg().
M33Scale()
PX_FORCE_INLINE Mat33V physx::aos::M33Scale (const Mat33V & a, const FloatV & b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and V3Scale().
M33Sub()
PX_FORCE_INLINE Mat33V physx::aos::M33Sub (const Mat33V & a, const Mat33V & b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and V3Sub().
M33Trnsps()
PX_FORCE_INLINE Mat33V physx::aos::M33Trnsps (const Mat33V & a)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, and physx::aos::Mat33V::col2.
Referenced by aos::PxMatTransformV::transformInv().
M33TrnspsMulV3()
PX_FORCE_INLINE Vec3V physx::aos::M33TrnspsMulV3 (const Mat33V & a, const Vec3V b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, and physx::aos::Mat33V::col2.
Referenced by aos::PxMatTransformV::rotateInv(), and aos::PxMatTransformV::transformInv().
M34Add()
PX_FORCE_INLINE Mat34V physx::aos::M34Add (const Mat34V & a, const Mat34V & b)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, physx::aos::Mat34V::col3, and V3Add().
M34Inverse()
PX_FORCE_INLINE Mat34V physx::aos::M34Inverse (const Mat34V & a)
References BTFFT(), BTTTF(), physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, physx::aos::Mat34V::col3, M34Mul33V3(), V3Cross(), V3Dot(), V3Neg(), and V3Zero().
M34Mul33MM34()
PX_FORCE_INLINE Mat33V physx::aos::M34Mul33MM34 (const Mat34V & a, const Mat34V & b)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, and M34Mul33V3().
M34Mul33V3() [1/2]
PX_FORCE_INLINE Vec3V physx::aos::M34Mul33V3 (const Mat34V & a, const Vec3V b)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, and physx::aos::Mat34V::col2.
Referenced by M34Inverse(), M34Mul33MM34(), M34Mul33V3(), M34MulM33(), and M34MulM34().
M34Mul33V3() [2/2]
PX_FORCE_INLINE Mat33V physx::aos::M34Mul33V3 (const Mat34V & a, const Mat33V & b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and M34Mul33V3().
M34MulM33()
PX_FORCE_INLINE Mat33V physx::aos::M34MulM33 (const Mat34V & a, const Mat33V & b)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, and M34Mul33V3().
M34MulM34()
PX_FORCE_INLINE Mat34V physx::aos::M34MulM34 (const Mat34V & a, const Mat34V & b)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, physx::aos::Mat34V::col3, M34Mul33V3(), and M34MulV3().
M34MulV3()
PX_FORCE_INLINE Vec3V physx::aos::M34MulV3 (const Mat34V & a, const Vec3V b)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, physx::aos::Mat34V::col2, and physx::aos::Mat34V::col3.
Referenced by M34MulM34().
M34Trnsps33()
PX_FORCE_INLINE Mat33V physx::aos::M34Trnsps33 (const Mat34V & a)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, and physx::aos::Mat34V::col2.
M34TrnspsMul33V3()
PX_FORCE_INLINE Vec3V physx::aos::M34TrnspsMul33V3 (const Mat34V & a, const Vec3V b)
References physx::aos::Mat34V::col0, physx::aos::Mat34V::col1, and physx::aos::Mat34V::col2.
M44Add()
PX_FORCE_INLINE Mat44V physx::aos::M44Add (const Mat44V & a, const Mat44V & b)
References physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, physx::aos::Mat44V::col3, and V4Add().
M44Inverse()
PX_FORCE_INLINE Mat44V physx::aos::M44Inverse (const Mat44V & a)
References physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, and physx::aos::Mat44V::col3.
M44MulM44()
PX_FORCE_INLINE Mat44V physx::aos::M44MulM44 (const Mat44V & a, const Mat44V & b)
References physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, physx::aos::Mat44V::col3, and M44MulV4().
M44MulV4()
PX_FORCE_INLINE Vec4V physx::aos::M44MulV4 (const Mat44V & a, const Vec4V b)
References physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, and physx::aos::Mat44V::col3.
Referenced by M44MulM44().
M44Trnsps()
PX_FORCE_INLINE Mat44V physx::aos::M44Trnsps (const Mat44V & a)
References physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, and physx::aos::Mat44V::col3.
M44TrnspsMulV4()
PX_FORCE_INLINE Vec4V physx::aos::M44TrnspsMulV4 (const Mat44V & a, const Vec4V b)
References physx::aos::Mat44V::col0, physx::aos::Mat44V::col1, physx::aos::Mat44V::col2, and physx::aos::Mat44V::col3.
Mat33GetQuatV()
PX_FORCE_INLINE QuatV physx::aos::Mat33GetQuatV (const Mat33V & a)
Mat33V_From_PxMat33()
PX_FORCE_INLINE Mat33V physx::aos::Mat33V_From_PxMat33 (const PxMat33 & m)
References PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, and V3LoadU().
PromoteVec3V()
PX_FORCE_INLINE Mat33V physx::aos::PromoteVec3V (const Vec3V v)
References BFTFF(), BTFFF(), BTFTF(), V3Sel(), and V3Zero().
PxI32_From_VecI32V()
PX_FORCE_INLINE void physx::aos::PxI32_From_VecI32V (const VecI32VArg a, PxI32 * i)
PxMat33_From_Mat33V()
PX_FORCE_INLINE void physx::aos::PxMat33_From_Mat33V (const Mat33V & m, PxMat33 & out)
References physx::aos::Mat33V::col0, physx::aos::Mat33V::col1, physx::aos::Mat33V::col2, PxMat33T< Type >::column0, PxMat33T< Type >::column1, PxMat33T< Type >::column2, PX_ASSERT, and V3StoreU().
QuatAdd()
PX_FORCE_INLINE QuatV physx::aos::QuatAdd (const QuatV a, const QuatV b)
QuatConjugate()
PX_FORCE_INLINE QuatV physx::aos::QuatConjugate (const QuatV q)
Referenced by aos::PxTransformV::getInverse(), and aos::PxTransformV::transformInv().
QuatDot()
PX_FORCE_INLINE FloatV physx::aos::QuatDot (const QuatV a, const QuatV b)
QuatGetBasisVector0()
PX_FORCE_INLINE Vec3V physx::aos::QuatGetBasisVector0 (const QuatV q)
QuatGetBasisVector1()
PX_FORCE_INLINE Vec3V physx::aos::QuatGetBasisVector1 (const QuatV q)
QuatGetBasisVector2()
PX_FORCE_INLINE Vec3V physx::aos::QuatGetBasisVector2 (const QuatV q)
QuatGetImaginaryPart()
PX_FORCE_INLINE Vec3V physx::aos::QuatGetImaginaryPart (const QuatV q)
QuatGetMat33V() [1/2]
PX_FORCE_INLINE Mat33V physx::aos::QuatGetMat33V (const QuatVArg q)
References FAdd(), FMul(), FOne(), FSub(), V3Merge(), V4GetW(), V4GetX(), V4GetY(), and V4GetZ().
Referenced by PxMat33Padded::PxMat33Padded(), and aos::PxMatTransformV::PxMatTransformV().
QuatGetMat33V() [2/2]
PX_FORCE_INLINE void physx::aos::QuatGetMat33V (const QuatVArg q, Vec3V & column0, Vec3V & column1, Vec3V & column2)
References FAdd(), FMul(), FOne(), FSub(), V3Merge(), V4GetW(), V4GetX(), V4GetY(), and V4GetZ().
QuatIdentity()
PX_FORCE_INLINE QuatV physx::aos::QuatIdentity ()
References FOne(), V4SetW(), and V4Zero().
Referenced by aos::PxTransformV::Invalidate(), and aos::PxTransformV::normalize().
QuatLength()
PX_FORCE_INLINE FloatV physx::aos::QuatLength (const QuatV q)
Referenced by aos::isSaneQuatV(), and aos::isValidQuatV().
QuatLengthSq()
PX_FORCE_INLINE FloatV physx::aos::QuatLengthSq (const QuatV q)
QuatMerge() [1/2]
PX_FORCE_INLINE QuatV physx::aos::QuatMerge (const FloatV *const v)
QuatMerge() [2/2]
PX_FORCE_INLINE QuatV physx::aos::QuatMerge (const FloatVArg x, const FloatVArg y, const FloatVArg z, const FloatVArg w)
References V4Merge().
QuatMul()
PX_FORCE_INLINE QuatV physx::aos::QuatMul (const QuatV a, const QuatV b)
Referenced by aos::PxTransformV::transform(), and aos::PxTransformV::transformInv().
QuatNeg()
PX_FORCE_INLINE QuatV physx::aos::QuatNeg (const QuatV q)
QuatNormalize()
PX_FORCE_INLINE QuatV physx::aos::QuatNormalize (const QuatV q)
QuatRotate()
PX_FORCE_INLINE Vec3V physx::aos::QuatRotate (const QuatV q, const Vec3V v)
Referenced by aos::PxTransformV::rotate(), aos::PxTransformV::transform(), and aos::PxTransformV::transformInv().
QuatRotateInv()
PX_FORCE_INLINE Vec3V physx::aos::QuatRotateInv (const QuatV q, const Vec3V v)
Referenced by aos::PxTransformV::getInverse(), aos::PxTransformV::rotateInv(), and aos::PxTransformV::transformInv().
QuatScale()
PX_FORCE_INLINE QuatV physx::aos::QuatScale (const QuatV a, const FloatV b)
QuatSub()
PX_FORCE_INLINE QuatV physx::aos::QuatSub (const QuatV a, const QuatV b)
QuatV_From_RotationAxisAngle()
PX_FORCE_INLINE QuatV physx::aos::QuatV_From_RotationAxisAngle (const Vec3V u, const FloatV a)
QuatVLoadA()
PX_FORCE_INLINE QuatV physx::aos::QuatVLoadA (const PxF32 * v)
References V4LoadA().
Referenced by aos::loadTransformA().
QuatVLoadU()
PX_FORCE_INLINE QuatV physx::aos::QuatVLoadU (const PxF32 * v)
References V4LoadU().
Referenced by aos::loadTransformU().
QuatVLoadXYZW()
PX_FORCE_INLINE QuatV physx::aos::QuatVLoadXYZW (const PxF32 x, const PxF32 y, const PxF32 z, const PxF32 w)
References V4LoadXYZW().
Referenced by aos::PxTransformV::PxTransformV().
recip_newton()
template<int n> PX_FORCE_INLINE float32x2_t physx::aos::recip_newton (const float32x2_t & in)
References recip().
recipq_newton()
template<int n> PX_FORCE_INLINE float32x4_t physx::aos::recipq_newton (const float32x4_t & in)
References recip().
rsqrt_newton()
template<int n> PX_FORCE_INLINE float32x2_t physx::aos::rsqrt_newton (const float32x2_t & in)
rsqrtq_newton()
template<int n> PX_FORCE_INLINE float32x4_t physx::aos::rsqrtq_newton (const float32x4_t & in)
Store_From_BoolV() [1/2]
PX_FORCE_INLINE void physx::aos::Store_From_BoolV (const BoolV b, PxU32 * b2)
Store_From_BoolV() [2/2]
PX_FORCE_INLINE void physx::aos::Store_From_BoolV (const BoolV a, PxU32 *PX_RESTRICT f)
U4Load()
PX_FORCE_INLINE VecI32V physx::aos::U4Load (const PxU32 f)
U4LoadA()
PX_FORCE_INLINE VecU32V physx::aos::U4LoadA (const PxU32 * f)
U4LoadU()
PX_FORCE_INLINE VecU32V physx::aos::U4LoadU (const PxU32 * f)
U4LoadXYZW()
PX_FORCE_INLINE VecU32V physx::aos::U4LoadXYZW (PxU32 x, PxU32 y, PxU32 z, PxU32 w)
U4One()
PX_FORCE_INLINE VecU32V physx::aos::U4One ()
U4StoreA()
PX_FORCE_INLINE void physx::aos::U4StoreA (const VecU32V uv, PxU32 * u)
U4Two()
PX_FORCE_INLINE VecU32V physx::aos::U4Two ()
U4Zero()
PX_FORCE_INLINE VecU32V physx::aos::U4Zero ()
V3Abs()
PX_FORCE_INLINE Vec3V physx::aos::V3Abs (const Vec3V a)
References V3Max(), and V3Neg().
Referenced by M33Abs().
V3Add() [1/2]
PX_FORCE_INLINE Vec3V physx::aos::V3Add (const Vec3V a, const Vec3V b)
Referenced by M33Add(), M34Add(), aos::Mat33GetQuatV(), aos::QuatMul(), aos::PxTransformV::transform(), aos::PxMatTransformV::transform(), V3MulAdd(), and V3ScaleAdd().
V3Add() [2/2]
PX_FORCE_INLINE Vec3V physx::aos::V3Add (const Vec3V a, const FloatV b)
References ASSERT_ISVALIDFLOATV, ASSERT_ISVALIDVEC3V, and Vec3V_From_FloatV().
V3AllEq()
PX_FORCE_INLINE PxU32 physx::aos::V3AllEq (const Vec3V a, const Vec3V b)
References BOOL_TO_U32.
V3AllGrtr()
PX_FORCE_INLINE PxU32 physx::aos::V3AllGrtr (const Vec3V a, const Vec3V b)
References BOOL_TO_U32.
V3AllGrtrOrEq()
PX_FORCE_INLINE PxU32 physx::aos::V3AllGrtrOrEq (const Vec3V a, const Vec3V b)
References BOOL_TO_U32.
V3Clamp()
PX_FORCE_INLINE Vec3V physx::aos::V3Clamp (const Vec3V a, const Vec3V minV, const Vec3V maxV)
References V3Max(), and V3Min().
V3ColX()
PX_FORCE_INLINE Vec3V physx::aos::V3ColX (const Vec3V a, const Vec3V b, const Vec3V c)
V3ColY()
PX_FORCE_INLINE Vec3V physx::aos::V3ColY (const Vec3V a, const Vec3V b, const Vec3V c)
V3ColZ()
PX_FORCE_INLINE Vec3V physx::aos::V3ColZ (const Vec3V a, const Vec3V b, const Vec3V c)
V3Cos()
PX_FORCE_INLINE Vec3V physx::aos::V3Cos (const Vec3V a)
V3Cross() [1/4]
PX_FORCE_INLINE Vec3V physx::aos::V3Cross (const Vec3V a, const Vec3V b)
Referenced by M34Inverse(), aos::QuatMul(), aos::QuatRotate(), aos::QuatRotateInv(), and aos::QuatTransform().
V3Cross() [2/4]
PX_FORCE_INLINE Vec3V physx::aos::V3Cross (const VecCrossV & a, const Vec3V b)
References ASSERT_ISVALIDVEC3V, physx::aos::VecCrossV::mL1, and physx::aos::VecCrossV::mR1.
V3Cross() [3/4]
PX_FORCE_INLINE Vec3V physx::aos::V3Cross (const Vec3V a, const VecCrossV & b)
References ASSERT_ISVALIDVEC3V, physx::aos::VecCrossV::mL1, and physx::aos::VecCrossV::mR1.
V3Cross() [4/4]
PX_FORCE_INLINE Vec3V physx::aos::V3Cross (const VecCrossV & a, const VecCrossV & b)
References physx::aos::VecCrossV::mL1, and physx::aos::VecCrossV::mR1.
V3Div()
PX_FORCE_INLINE Vec3V physx::aos::V3Div (const Vec3V a, const Vec3V b)
V3DivFast()
PX_FORCE_INLINE Vec3V physx::aos::V3DivFast (const Vec3V a, const Vec3V b)
V3Dot()
PX_FORCE_INLINE FloatV physx::aos::V3Dot (const Vec3V a, const Vec3V b)
Referenced by M34Inverse(), aos::QuatMul(), aos::QuatRotate(), aos::QuatRotateInv(), and aos::QuatTransform().
V3Dot4()
PX_FORCE_INLINE Vec4V physx::aos::V3Dot4 (const Vec3VArg a0, const Vec3VArg b0, const Vec3VArg a1, const Vec3VArg b1, const Vec3VArg a2, const Vec3VArg b2, const Vec3VArg a3, const Vec3VArg b3)
References PX_TRANSPOSE_44_34, V3Mul(), V4Add(), and Vec4V_From_Vec3V().
V3Eps()
PX_FORCE_INLINE Vec3V physx::aos::V3Eps ()
References PX_EPS_REAL, and V3Load().
V3ExtractMax()
PX_FORCE_INLINE FloatV physx::aos::V3ExtractMax (const Vec3V a)
V3ExtractMin()
PX_FORCE_INLINE FloatV physx::aos::V3ExtractMin (const Vec3V a)
V3GetX()
PX_FORCE_INLINE FloatV physx::aos::V3GetX (const Vec3V f)
Referenced by M33MulV3AddV3(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), and aos::QuatGetBasisVector2().
V3GetY()
PX_FORCE_INLINE FloatV physx::aos::V3GetY (const Vec3V f)
Referenced by M33MulV3AddV3(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), and aos::QuatGetBasisVector2().
V3GetZ()
PX_FORCE_INLINE FloatV physx::aos::V3GetZ (const Vec3V f)
Referenced by M33MulV3AddV3(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), and aos::QuatGetBasisVector2().
V3InBounds() [1/2]
PX_FORCE_INLINE PxU32 physx::aos::V3InBounds (const Vec3V a, const Vec3V min, const Vec3V max)
References BOOL_TO_U32.
Referenced by V3InBounds().
V3InBounds() [2/2]
PX_FORCE_INLINE PxU32 physx::aos::V3InBounds (const Vec3V a, const Vec3V bounds)
References V3InBounds(), and V3Neg().
V3IsEq()
PX_FORCE_INLINE BoolV physx::aos::V3IsEq (const Vec3V a, const Vec3V b)
References BOOL_TO_U32, and TRUE_TO_U32.
V3IsGrtr()
PX_FORCE_INLINE BoolV physx::aos::V3IsGrtr (const Vec3V a, const Vec3V b)
References BOOL_TO_U32, and FALSE_TO_U32.
V3IsGrtrOrEq()
PX_FORCE_INLINE BoolV physx::aos::V3IsGrtrOrEq (const Vec3V a, const Vec3V b)
References BOOL_TO_U32, and TRUE_TO_U32.
Referenced by aos::Mat33GetQuatV().
V3Length()
PX_FORCE_INLINE FloatV physx::aos::V3Length (const Vec3V a)
References PxSqrt().
V3LengthSq()
PX_FORCE_INLINE FloatV physx::aos::V3LengthSq (const Vec3V a)
V3Load()
PX_FORCE_INLINE Vec3V physx::aos::V3Load (const PxF32 f)
Referenced by V3Eps(), V3One(), and V3Zero().
V3LoadA() [1/2]
PX_FORCE_INLINE Vec3V physx::aos::V3LoadA (const PxVec3 & f)
References PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by aos::loadTransformA().
V3LoadA() [2/2]
PX_FORCE_INLINE Vec3V physx::aos::V3LoadA (const PxF32 * f)
V3LoadU() [1/2]
PX_FORCE_INLINE Vec3V physx::aos::V3LoadU (const PxVec3 & f)
References PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by aos::loadTransformU(), M33Load(), Mat33V_From_PxMat33(), and aos::PxTransformV::PxTransformV().
V3LoadU() [2/2]
PX_FORCE_INLINE Vec3V physx::aos::V3LoadU (const PxF32 * f)
V3LoadU_SafeReadW()
PX_FORCE_INLINE Vec3V physx::aos::V3LoadU_SafeReadW (const PxVec3 & f)
References V4LoadU(), Vec3V_From_Vec4V(), and PxVec3T< Type >::x.
V3LoadUnsafeA()
PX_FORCE_INLINE Vec3V physx::aos::V3LoadUnsafeA (const PxVec3 & f)
References PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
V3Max()
PX_FORCE_INLINE Vec3V physx::aos::V3Max (const Vec3V a, const Vec3V b)
Referenced by V3Abs(), and V3Clamp().
V3Merge()
PX_FORCE_INLINE Vec3V physx::aos::V3Merge (const FloatVArg x, const FloatVArg y, const FloatVArg z)
Referenced by aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatGetMat33V(), QuatGetMat33V(), and aos::QuatV_From_RotationAxisAngle().
V3Min()
PX_FORCE_INLINE Vec3V physx::aos::V3Min (const Vec3V a, const Vec3V b)
Referenced by V3Clamp().
V3Mul()
PX_FORCE_INLINE Vec3V physx::aos::V3Mul (const Vec3V a, const Vec3V b)
Referenced by M33Diagonal(), V3Dot4(), V3MulAdd(), and V3NegMulSub().
V3MulAdd()
PX_FORCE_INLINE Vec3V physx::aos::V3MulAdd (const Vec3V a, const Vec3V b, const Vec3V c)
References V3Add(), and V3Mul().
V3Neg()
PX_FORCE_INLINE Vec3V physx::aos::V3Neg (const Vec3V c)
Referenced by aos::PxTransformV::getInverse(), M33Neg(), M34Inverse(), V3Abs(), V3InBounds(), and V3OutOfBounds().
V3NegMulSub()
PX_FORCE_INLINE Vec3V physx::aos::V3NegMulSub (const Vec3V a, const Vec3V b, const Vec3V c)
References V3Mul(), and V3Sub().
V3NegScaleSub()
PX_FORCE_INLINE Vec3V physx::aos::V3NegScaleSub (const Vec3V a, const FloatV b, const Vec3V c)
References V3Scale(), and V3Sub().
Referenced by aos::QuatRotateInv().
V3Normalize()
PX_FORCE_INLINE Vec3V physx::aos::V3Normalize (const Vec3V a)
References PxSqrt(), and VECMATHAOS_ASSERT.
V3NormalizeFast()
PX_FORCE_INLINE Vec3V physx::aos::V3NormalizeFast (const Vec3V a)
References PxSqrt(), and VECMATHAOS_ASSERT.
V3NormalizeSafe()
PX_FORCE_INLINE Vec3V physx::aos::V3NormalizeSafe (const Vec3V a, const Vec3V unsafeReturnValue)
References PX_EPS_REAL, and PxSqrt().
V3One()
PX_FORCE_INLINE Vec3V physx::aos::V3One ()
References V3Load().
V3OutOfBounds() [1/2]
PX_FORCE_INLINE PxU32 physx::aos::V3OutOfBounds (const Vec3V a, const Vec3V min, const Vec3V max)
References BOOL_TO_U32.
Referenced by V3OutOfBounds().
V3OutOfBounds() [2/2]
PX_FORCE_INLINE PxU32 physx::aos::V3OutOfBounds (const Vec3V a, const Vec3V bounds)
References V3Neg(), and V3OutOfBounds().
V3Perm_0Z_Zero_1X()
PX_FORCE_INLINE Vec3V physx::aos::V3Perm_0Z_Zero_1X (const Vec3V v0, const Vec3V v1)
V3Perm_1Y_0X_Zero()
PX_FORCE_INLINE Vec3V physx::aos::V3Perm_1Y_0X_Zero (const Vec3V v0, const Vec3V v1)
V3Perm_Zero_1Z_0Y()
PX_FORCE_INLINE Vec3V physx::aos::V3Perm_Zero_1Z_0Y (const Vec3V v0, const Vec3V v1)
V3PermXYX()
PX_FORCE_INLINE Vec3V physx::aos::V3PermXYX (const Vec3V a)
V3PermYXX()
PX_FORCE_INLINE Vec3V physx::aos::V3PermYXX (const Vec3V a)
V3PermYZX()
PX_FORCE_INLINE Vec3V physx::aos::V3PermYZX (const Vec3V a)
V3PermYZZ()
PX_FORCE_INLINE Vec3V physx::aos::V3PermYZZ (const Vec3V a)
V3PermZXY()
PX_FORCE_INLINE Vec3V physx::aos::V3PermZXY (const Vec3V a)
V3PermZZY()
PX_FORCE_INLINE Vec3V physx::aos::V3PermZZY (const Vec3V a)
V3PrepareCross() [1/2]
PX_FORCE_INLINE VecCrossV physx::aos::V3PrepareCross (const Vec3VArg normal)
V3PrepareCross() [2/2]
PX_FORCE_INLINE VecCrossV physx::aos::V3PrepareCross (const Vec3V a)
References ASSERT_ISVALIDVEC3V.
V3ReadX()
PX_FORCE_INLINE PxF32 physx::aos::V3ReadX (const Vec3V & v)
V3ReadXYZ()
PX_FORCE_INLINE const PxVec3 & physx::aos::V3ReadXYZ (const Vec3V & v)
V3ReadY()
PX_FORCE_INLINE PxF32 physx::aos::V3ReadY (const Vec3V & v)
V3ReadZ()
PX_FORCE_INLINE PxF32 physx::aos::V3ReadZ (const Vec3V & v)
V3Recip()
PX_FORCE_INLINE Vec3V physx::aos::V3Recip (const Vec3V a)
V3RecipFast()
PX_FORCE_INLINE Vec3V physx::aos::V3RecipFast (const Vec3V a)
V3Round()
PX_FORCE_INLINE Vec3V physx::aos::V3Round (const Vec3V a)
V3Rsqrt()
PX_FORCE_INLINE Vec3V physx::aos::V3Rsqrt (const Vec3V a)
References PxRecipSqrt().
V3RsqrtFast()
PX_FORCE_INLINE Vec3V physx::aos::V3RsqrtFast (const Vec3V a)
References PxRecipSqrt().
V3Scale()
PX_FORCE_INLINE Vec3V physx::aos::V3Scale (const Vec3V a, const FloatV b)
Referenced by M33Scale(), aos::Mat33GetQuatV(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatMul(), aos::QuatRotate(), aos::QuatRotateInv(), aos::QuatTransform(), aos::QuatV_From_RotationAxisAngle(), V3NegScaleSub(), and V3ScaleAdd().
V3ScaleAdd()
PX_FORCE_INLINE Vec3V physx::aos::V3ScaleAdd (const Vec3V a, const FloatV b, const Vec3V c)
References V3Add(), and V3Scale().
Referenced by M33MulV3AddV3(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatRotate(), aos::QuatRotateInv(), and aos::QuatTransform().
V3ScaleInv()
PX_FORCE_INLINE Vec3V physx::aos::V3ScaleInv (const Vec3V a, const FloatV b)
V3ScaleInvFast()
PX_FORCE_INLINE Vec3V physx::aos::V3ScaleInvFast (const Vec3V a, const FloatV b)
V3Sel()
PX_FORCE_INLINE Vec3V physx::aos::V3Sel (const BoolV c, const Vec3V a, const Vec3V b)
Referenced by PromoteVec3V().
V3SetX()
PX_FORCE_INLINE Vec3V physx::aos::V3SetX (const Vec3V v, const FloatV f)
Referenced by aos::QuatGetBasisVector0().
V3SetY()
PX_FORCE_INLINE Vec3V physx::aos::V3SetY (const Vec3V v, const FloatV f)
Referenced by aos::QuatGetBasisVector1().
V3SetZ()
PX_FORCE_INLINE Vec3V physx::aos::V3SetZ (const Vec3V v, const FloatV f)
Referenced by aos::QuatGetBasisVector2().
V3Sign()
PX_FORCE_INLINE Vec3V physx::aos::V3Sign (const Vec3V a)
V3Sin()
PX_FORCE_INLINE Vec3V physx::aos::V3Sin (const Vec3V a)
V3Splat()
PX_FORCE_INLINE Vec3V physx::aos::V3Splat (const FloatV f)
Referenced by aos::PxTransformV::Invalidate(), and aos::Mat33GetQuatV().
V3StoreA()
PX_FORCE_INLINE void physx::aos::V3StoreA (const Vec3V a, PxVec3 & f)
V3StoreU()
PX_FORCE_INLINE void physx::aos::V3StoreU (const Vec3V a, PxVec3 & f)
Referenced by PxMat33_From_Mat33V(), and PxMat33Padded::PxMat33Padded().
V3Sub() [1/2]
PX_FORCE_INLINE Vec3V physx::aos::V3Sub (const Vec3V a, const Vec3V b)
Referenced by M33Sub(), aos::Mat33GetQuatV(), aos::PxTransformV::transformInv(), aos::PxMatTransformV::transformInv(), V3NegMulSub(), and V3NegScaleSub().
V3Sub() [2/2]
PX_FORCE_INLINE Vec3V physx::aos::V3Sub (const Vec3V a, const FloatV b)
References ASSERT_ISVALIDFLOATV, ASSERT_ISVALIDVEC3V, and Vec3V_From_FloatV().
V3SumElems()
PX_FORCE_INLINE FloatV physx::aos::V3SumElems (const Vec3V a)
V3Transpose()
PX_FORCE_INLINE void physx::aos::V3Transpose (Vec3V & col0, Vec3V & col1, Vec3V & col2)
V3UnitX()
PX_FORCE_INLINE Vec3V physx::aos::V3UnitX ()
Referenced by M33Diagonal(), and M33Identity().
V3UnitY()
PX_FORCE_INLINE Vec3V physx::aos::V3UnitY ()
Referenced by M33Diagonal(), and M33Identity().
V3UnitZ()
PX_FORCE_INLINE Vec3V physx::aos::V3UnitZ ()
Referenced by M33Diagonal(), and M33Identity().
V3WriteX()
PX_FORCE_INLINE void physx::aos::V3WriteX (Vec3V & v, const PxF32 f)
V3WriteXYZ()
PX_FORCE_INLINE void physx::aos::V3WriteXYZ (Vec3V & v, const PxVec3 & f)
V3WriteY()
PX_FORCE_INLINE void physx::aos::V3WriteY (Vec3V & v, const PxF32 f)
V3WriteZ()
PX_FORCE_INLINE void physx::aos::V3WriteZ (Vec3V & v, const PxF32 f)
V3Zero()
PX_FORCE_INLINE Vec3V physx::aos::V3Zero ()
References V3Load().
Referenced by aos::PxTransformV::createIdentity(), M34Inverse(), aos::PxTransformV::normalize(), PromoteVec3V(), and aos::PxMatTransformV::PxMatTransformV().
V4Abs()
PX_FORCE_INLINE Vec4V physx::aos::V4Abs (const Vec4V a)
References V4Max(), and V4Neg().
V4Add()
PX_FORCE_INLINE Vec4V physx::aos::V4Add (const Vec4V a, const Vec4V b)
Referenced by M44Add(), aos::QuatAdd(), aos::QuatGetMat33V(), V3Dot4(), V4MulAdd(), and V4ScaleAdd().
V4AllEq()
PX_FORCE_INLINE PxU32 physx::aos::V4AllEq (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4AllGrtr()
PX_FORCE_INLINE PxU32 physx::aos::V4AllGrtr (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4AllGrtrOrEq()
PX_FORCE_INLINE PxU32 physx::aos::V4AllGrtrOrEq (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4AllGrtrOrEq3()
PX_FORCE_INLINE PxU32 physx::aos::V4AllGrtrOrEq3 (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4Andc()
PX_FORCE_INLINE Vec4V physx::aos::V4Andc (const Vec4V a, const VecU32V b)
References V4U32Andc().
V4AnyGrtr3()
PX_FORCE_INLINE PxU32 physx::aos::V4AnyGrtr3 (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4Ceil()
PX_FORCE_INLINE Vec4V physx::aos::V4Ceil (const Vec4V in)
V4Clamp()
PX_FORCE_INLINE Vec4V physx::aos::V4Clamp (const Vec4V a, const Vec4V minV, const Vec4V maxV)
References V4Max(), and V4Min().
V4ClearW()
PX_FORCE_INLINE Vec4V physx::aos::V4ClearW (const Vec4V v)
V4ConvertFromI32V()
PX_FORCE_INLINE Vec4V physx::aos::V4ConvertFromI32V (const VecI32V in)
References physx::aos::internalWindowsSimd::m128_F2I().
V4ConvertToU32VSaturate()
PX_FORCE_INLINE VecU32V physx::aos::V4ConvertToU32VSaturate (const Vec4V in, PxU32 power)
References PX_ASSERT, and PX_UNUSED().
V4Cos()
PX_FORCE_INLINE Vec4V physx::aos::V4Cos (const Vec4V a)
V4Cross()
PX_FORCE_INLINE Vec4V physx::aos::V4Cross (const Vec4V a, const Vec4V b)
V4Div()
PX_FORCE_INLINE Vec4V physx::aos::V4Div (const Vec4V a, const Vec4V b)
References VECMATHAOS_ASSERT.
V4DivFast()
PX_FORCE_INLINE Vec4V physx::aos::V4DivFast (const Vec4V a, const Vec4V b)
V4Dot()
PX_FORCE_INLINE FloatV physx::aos::V4Dot (const Vec4V a, const Vec4V b)
Referenced by aos::QuatDot(), and V4LengthSq().
V4Dot3()
PX_FORCE_INLINE FloatV physx::aos::V4Dot3 (const Vec4V a, const Vec4V b)
V4Eps()
PX_FORCE_INLINE Vec4V physx::aos::V4Eps ()
References PX_EPS_REAL, and V4Load().
V4ExtractMax()
PX_FORCE_INLINE FloatV physx::aos::V4ExtractMax (const Vec4V a)
V4ExtractMin()
PX_FORCE_INLINE FloatV physx::aos::V4ExtractMin (const Vec4V a)
V4Floor()
PX_FORCE_INLINE Vec4V physx::aos::V4Floor (const Vec4V in)
V4GetW()
PX_FORCE_INLINE FloatV physx::aos::V4GetW (const Vec4V f)
Referenced by aos::QuatConjugate(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatGetMat33V(), QuatGetMat33V(), aos::QuatMul(), aos::QuatRotate(), aos::QuatRotateInv(), and aos::QuatTransform().
V4GetX()
PX_FORCE_INLINE FloatV physx::aos::V4GetX (const Vec4V f)
Referenced by aos::QuatGetMat33V(), QuatGetMat33V(), and aos::QuatV_From_RotationAxisAngle().
V4GetY()
PX_FORCE_INLINE FloatV physx::aos::V4GetY (const Vec4V f)
Referenced by aos::QuatGetMat33V(), QuatGetMat33V(), and aos::QuatV_From_RotationAxisAngle().
V4GetZ()
PX_FORCE_INLINE FloatV physx::aos::V4GetZ (const Vec4V f)
Referenced by aos::QuatGetMat33V(), and QuatGetMat33V().
V4I16CompareGt() [1/2]
PX_FORCE_INLINE VecU16V physx::aos::V4I16CompareGt (VecU16V a, VecU16V b)
References BOOL_TO_U16.
V4I16CompareGt() [2/2]
PX_FORCE_INLINE VecU16V physx::aos::V4I16CompareGt (VecI16V a, VecI16V b)
V4I32Sel()
PX_FORCE_INLINE VecI32V physx::aos::V4I32Sel (const BoolV c, const VecI32V a, const VecI32V b)
V4IsEq()
PX_FORCE_INLINE BoolV physx::aos::V4IsEq (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4IsEqU32()
PX_FORCE_INLINE BoolV physx::aos::V4IsEqU32 (const VecU32V a, const VecU32V b)
References BOOL_TO_U32.
Referenced by physx::aos::vecMathTests::V4U32AllEq().
V4IsGrtr()
PX_FORCE_INLINE BoolV physx::aos::V4IsGrtr (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4IsGrtrOrEq()
PX_FORCE_INLINE BoolV physx::aos::V4IsGrtrOrEq (const Vec4V a, const Vec4V b)
References BOOL_TO_U32.
V4IsGrtrV32u()
PX_FORCE_INLINE VecU32V physx::aos::V4IsGrtrV32u (const Vec4V a, const Vec4V b)
V4Length()
PX_FORCE_INLINE FloatV physx::aos::V4Length (const Vec4V a)
References PxSqrt().
Referenced by aos::QuatLength(), V4Normalize(), V4NormalizeFast(), and V4NormalizeSafe().
V4LengthSq()
PX_FORCE_INLINE FloatV physx::aos::V4LengthSq (const Vec4V a)
References V4Dot().
Referenced by isFiniteLength(), and aos::QuatLengthSq().
V4Load()
PX_FORCE_INLINE Vec4V physx::aos::V4Load (const PxF32 f)
Referenced by V4Eps(), V4One(), and V4Zero().
V4LoadA()
PX_FORCE_INLINE Vec4V physx::aos::V4LoadA (const PxF32 *const f)
Referenced by aos::QuatVLoadA().
V4LoadAligned()
PX_FORCE_INLINE Vec4V physx::aos::V4LoadAligned (Vec4V * addr)
V4LoadU()
PX_FORCE_INLINE Vec4V physx::aos::V4LoadU (const PxF32 *const f)
Referenced by M33Load(), PxMat33Padded::PxMat33Padded(), aos::QuatVLoadU(), and V3LoadU_SafeReadW().
V4LoadUnaligned()
PX_FORCE_INLINE Vec4V physx::aos::V4LoadUnaligned (Vec4V * addr)
V4LoadXYZW()
PX_FORCE_INLINE Vec4V physx::aos::V4LoadXYZW (const PxF32 & x, const PxF32 & y, const PxF32 & z, const PxF32 & w)
Referenced by aos::QuatVLoadXYZW().
V4Max()
PX_FORCE_INLINE Vec4V physx::aos::V4Max (const Vec4V a, const Vec4V b)
Referenced by V4Abs(), and V4Clamp().
V4Merge() [1/2]
PX_FORCE_INLINE Vec4V physx::aos::V4Merge (const FloatV *const f)
Referenced by aos::Mat33GetQuatV(), and aos::QuatMerge().
V4Merge() [2/2]
PX_FORCE_INLINE Vec4V physx::aos::V4Merge (const FloatVArg x, const FloatVArg y, const FloatVArg z, const FloatVArg w)
V4MergeW()
PX_FORCE_INLINE Vec4V physx::aos::V4MergeW (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
V4MergeX()
PX_FORCE_INLINE Vec4V physx::aos::V4MergeX (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
V4MergeY()
PX_FORCE_INLINE Vec4V physx::aos::V4MergeY (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
V4MergeZ()
PX_FORCE_INLINE Vec4V physx::aos::V4MergeZ (const Vec4VArg x, const Vec4VArg y, const Vec4VArg z, const Vec4VArg w)
V4Min()
PX_FORCE_INLINE Vec4V physx::aos::V4Min (const Vec4V a, const Vec4V b)
Referenced by V4Clamp().
V4Mul()
PX_FORCE_INLINE Vec4V physx::aos::V4Mul (const Vec4V a, const Vec4V b)
Referenced by V4MulAdd(), and V4NegMulSub().
V4MulAdd()
PX_FORCE_INLINE Vec4V physx::aos::V4MulAdd (const Vec4V a, const Vec4V b, const Vec4V c)
References V4Add(), and V4Mul().
Referenced by aos::QuatGetMat33V().
V4Neg()
PX_FORCE_INLINE Vec4V physx::aos::V4Neg (const Vec4V c)
Referenced by aos::QuatConjugate(), aos::QuatGetMat33V(), aos::QuatNeg(), and V4Abs().
V4NegMulSub()
PX_FORCE_INLINE Vec4V physx::aos::V4NegMulSub (const Vec4V a, const Vec4V b, const Vec4V c)
References V4Mul(), and V4Sub().
V4NegScaleSub()
PX_FORCE_INLINE Vec4V physx::aos::V4NegScaleSub (const Vec4V a, const FloatV b, const Vec4V c)
References V4Scale(), and V4Sub().
V4Normalize()
PX_FORCE_INLINE Vec4V physx::aos::V4Normalize (const Vec4V a)
References V4Length(), V4ScaleInv(), and VECMATHAOS_ASSERT.
Referenced by aos::QuatNormalize().
V4NormalizeFast()
PX_FORCE_INLINE Vec4V physx::aos::V4NormalizeFast (const Vec4V a)
References V4Length(), V4ScaleInv(), and VECMATHAOS_ASSERT.
V4NormalizeSafe()
PX_FORCE_INLINE Vec4V physx::aos::V4NormalizeSafe (const Vec4V a, const Vec4V unsafeReturnValue)
References PX_EPS_REAL, V4Length(), and V4ScaleInv().
V4One()
PX_FORCE_INLINE Vec4V physx::aos::V4One ()
References V4Load().
V4Perm()
template<PxU8 x, PxU8 y, PxU8 z, PxU8 w> PX_FORCE_INLINE Vec4V physx::aos::V4Perm (const Vec4V a)
V4PermXZXZ()
PX_FORCE_INLINE Vec4V physx::aos::V4PermXZXZ (const Vec4V v)
V4PermYWYW()
PX_FORCE_INLINE Vec4V physx::aos::V4PermYWYW (const Vec4V v)
V4PermYXWZ()
PX_FORCE_INLINE Vec4V physx::aos::V4PermYXWZ (const Vec4V v)
V4PermYZXW()
PX_FORCE_INLINE Vec4V physx::aos::V4PermYZXW (const Vec4V v)
V4PermZWXY()
PX_FORCE_INLINE Vec4V physx::aos::V4PermZWXY (const Vec4V a)
V4ReadW()
PX_FORCE_INLINE PxF32 physx::aos::V4ReadW (const Vec4V & v)
V4ReadX()
PX_FORCE_INLINE PxF32 physx::aos::V4ReadX (const Vec4V & v)
V4ReadXYZ()
PX_FORCE_INLINE const PxVec3 & physx::aos::V4ReadXYZ (const Vec4V & v)
V4ReadY()
PX_FORCE_INLINE PxF32 physx::aos::V4ReadY (const Vec4V & v)
V4ReadZ()
PX_FORCE_INLINE PxF32 physx::aos::V4ReadZ (const Vec4V & v)
V4Recip()
PX_FORCE_INLINE Vec4V physx::aos::V4Recip (const Vec4V a)
V4RecipFast()
PX_FORCE_INLINE Vec4V physx::aos::V4RecipFast (const Vec4V a)
V4Round()
PX_FORCE_INLINE Vec4V physx::aos::V4Round (const Vec4V a)
V4Rsqrt()
PX_FORCE_INLINE Vec4V physx::aos::V4Rsqrt (const Vec4V a)
References PxRecipSqrt().
V4RsqrtFast()
PX_FORCE_INLINE Vec4V physx::aos::V4RsqrtFast (const Vec4V a)
References PxRecipSqrt().
V4Scale()
PX_FORCE_INLINE Vec4V physx::aos::V4Scale (const Vec4V a, const FloatV b)
Referenced by aos::QuatScale(), V4NegScaleSub(), and V4ScaleAdd().
V4ScaleAdd()
PX_FORCE_INLINE Vec4V physx::aos::V4ScaleAdd (const Vec4V a, const FloatV b, const Vec4V c)
References V4Add(), and V4Scale().
V4ScaleInv()
PX_FORCE_INLINE Vec4V physx::aos::V4ScaleInv (const Vec4V a, const FloatV b)
Referenced by V4Normalize(), V4NormalizeFast(), and V4NormalizeSafe().
V4ScaleInvFast()
PX_FORCE_INLINE Vec4V physx::aos::V4ScaleInvFast (const Vec4V a, const FloatV b)
V4Sel()
PX_FORCE_INLINE Vec4V physx::aos::V4Sel (const BoolV c, const Vec4V a, const Vec4V b)
Referenced by physx::aos::internalWindowsSimd::FiniteTestEq(), physx::aos::internalUnitSSE2Simd::FiniteTestEq(), and aos::Mat33GetQuatV().
V4SetW()
PX_FORCE_INLINE Vec4V physx::aos::V4SetW (const Vec4V v, const FloatV f)
Referenced by aos::Mat33GetQuatV(), aos::QuatConjugate(), aos::QuatIdentity(), aos::QuatMul(), and aos::QuatV_From_RotationAxisAngle().
V4SetX()
PX_FORCE_INLINE Vec4V physx::aos::V4SetX (const Vec4V v, const FloatV f)
V4SetY()
PX_FORCE_INLINE Vec4V physx::aos::V4SetY (const Vec4V v, const FloatV f)
V4SetZ()
PX_FORCE_INLINE Vec4V physx::aos::V4SetZ (const Vec4V v, const FloatV f)
V4Sin()
PX_FORCE_INLINE Vec4V physx::aos::V4Sin (const Vec4V a)
Referenced by aos::QuatV_From_RotationAxisAngle().
V4Splat()
PX_FORCE_INLINE Vec4V physx::aos::V4Splat (const FloatV f)
V4SplatElement()
template<int elementIndex> PX_FORCE_INLINE Vec4V physx::aos::V4SplatElement (Vec4V a)
V4Sqrt()
PX_FORCE_INLINE Vec4V physx::aos::V4Sqrt (const Vec4V a)
References PxSqrt().
V4StoreA()
PX_FORCE_INLINE void physx::aos::V4StoreA (const Vec4V a, PxF32 * f)
V4StoreU()
PX_FORCE_INLINE void physx::aos::V4StoreU (const Vec4V a, PxF32 * f)
Referenced by PxMat33Padded::PxMat33Padded().
V4Sub()
PX_FORCE_INLINE Vec4V physx::aos::V4Sub (const Vec4V a, const Vec4V b)
Referenced by aos::QuatSub(), V4NegMulSub(), and V4NegScaleSub().
V4SumElements()
PX_FORCE_INLINE FloatV physx::aos::V4SumElements (const Vec4V a)
V4Transpose()
PX_FORCE_INLINE void physx::aos::V4Transpose (Vec4V & col0, Vec4V & col1, Vec4V & col2, Vec4V & col3)
V4U16CompareGt()
PX_FORCE_INLINE VecU16V physx::aos::V4U16CompareGt (VecU16V a, VecU16V b)
References BOOL_TO_U16.
V4U16LoadAligned()
PX_FORCE_INLINE VecU16V physx::aos::V4U16LoadAligned (VecU16V * addr)
V4U16LoadUnaligned()
PX_FORCE_INLINE VecU16V physx::aos::V4U16LoadUnaligned (VecU16V * addr)
V4U32and()
PX_FORCE_INLINE VecU32V physx::aos::V4U32and (VecU32V a, VecU32V b)
V4U32Andc()
PX_FORCE_INLINE VecU32V physx::aos::V4U32Andc (VecU32V a, VecU32V b)
Referenced by V4Andc().
V4U32or()
PX_FORCE_INLINE VecU32V physx::aos::V4U32or (VecU32V a, VecU32V b)
V4U32Sel()
PX_FORCE_INLINE VecU32V physx::aos::V4U32Sel (const BoolV c, const VecU32V a, const VecU32V b)
V4U32SplatElement()
template<int index> PX_FORCE_INLINE VecU32V physx::aos::V4U32SplatElement (VecU32V a)
V4U32StoreAligned()
PX_FORCE_INLINE void physx::aos::V4U32StoreAligned (VecU32V val, VecU32V * address)
V4U32xor()
PX_FORCE_INLINE VecU32V physx::aos::V4U32xor (VecU32V a, VecU32V b)
V4UnitW()
PX_FORCE_INLINE Vec4V physx::aos::V4UnitW ()
V4UnitX()
PX_FORCE_INLINE Vec4V physx::aos::V4UnitX ()
V4UnitY()
PX_FORCE_INLINE Vec4V physx::aos::V4UnitY ()
V4UnitZ()
PX_FORCE_INLINE Vec4V physx::aos::V4UnitZ ()
V4UnpackXY()
PX_FORCE_INLINE Vec4V physx::aos::V4UnpackXY (const Vec4VArg a, const Vec4VArg b)
V4UnpackZW()
PX_FORCE_INLINE Vec4V physx::aos::V4UnpackZW (const Vec4VArg a, const Vec4VArg b)
V4WriteW()
PX_FORCE_INLINE void physx::aos::V4WriteW (Vec4V & v, const PxF32 f)
V4WriteX()
PX_FORCE_INLINE void physx::aos::V4WriteX (Vec4V & v, const PxF32 f)
V4WriteXYZ()
PX_FORCE_INLINE void physx::aos::V4WriteXYZ (Vec4V & v, const PxVec3 & f)
V4WriteY()
PX_FORCE_INLINE void physx::aos::V4WriteY (Vec4V & v, const PxF32 f)
V4WriteZ()
PX_FORCE_INLINE void physx::aos::V4WriteZ (Vec4V & v, const PxF32 f)
V4Zero()
PX_FORCE_INLINE Vec4V physx::aos::V4Zero ()
References V4Load().
Referenced by aos::QuatIdentity().
Vec3V_From_FloatV()
PX_FORCE_INLINE Vec3V physx::aos::Vec3V_From_FloatV (FloatV f)
Referenced by V3Add(), and V3Sub().
Vec3V_From_FloatV_WUndefined()
PX_FORCE_INLINE Vec3V physx::aos::Vec3V_From_FloatV_WUndefined (FloatV f)
Vec3V_From_Vec4V()
PX_FORCE_INLINE Vec3V physx::aos::Vec3V_From_Vec4V (Vec4V v)
Referenced by M33Load(), aos::QuatGetBasisVector0(), aos::QuatGetBasisVector1(), aos::QuatGetBasisVector2(), aos::QuatGetImaginaryPart(), aos::QuatGetMat33V(), aos::QuatMul(), aos::QuatRotate(), aos::QuatRotateInv(), aos::QuatTransform(), and V3LoadU_SafeReadW().
Vec3V_From_Vec4V_WUndefined()
PX_FORCE_INLINE Vec3V physx::aos::Vec3V_From_Vec4V_WUndefined (const Vec4V v)
Vec4V_From_FloatV()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_From_FloatV (FloatV f)
Vec4V_From_PxVec3_WUndefined()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_From_PxVec3_WUndefined (const PxVec3 & v)
Vec4V_From_Vec3V()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_From_Vec3V (Vec3V f)
Referenced by aos::Mat33GetQuatV(), aos::QuatMul(), aos::QuatV_From_RotationAxisAngle(), and V3Dot4().
Vec4V_From_VecI32V()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_From_VecI32V (VecI32V a)
Vec4V_From_VecU32V()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_From_VecU32V (VecU32V a)
Vec4V_ReinterpretFrom_VecI32V()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_ReinterpretFrom_VecI32V (VecI32V a)
Vec4V_ReinterpretFrom_VecU32V()
PX_FORCE_INLINE Vec4V physx::aos::Vec4V_ReinterpretFrom_VecU32V (VecU32V a)
VecI32V_Add()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Add (const VecI32VArg a, const VecI32VArg b)
VecI32V_And()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_And (const VecI32VArg a, const VecI32VArg b)
VecI32V_From_BoolV()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_From_BoolV (const BoolVArg b)
VecI32V_From_Vec4V()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_From_Vec4V (Vec4V a)
VecI32V_GetW()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_GetW (const VecI32VArg a)
VecI32V_GetX()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_GetX (const VecI32VArg a)
VecI32V_GetY()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_GetY (const VecI32VArg a)
VecI32V_GetZ()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_GetZ (const VecI32VArg a)
VecI32V_IsEq()
PX_FORCE_INLINE BoolV physx::aos::VecI32V_IsEq (const VecI32VArg a, const VecI32VArg b)
References BOOL_TO_U32.
VecI32V_IsGrtr()
PX_FORCE_INLINE BoolV physx::aos::VecI32V_IsGrtr (const VecI32VArg a, const VecI32VArg b)
References BOOL_TO_U32.
VecI32V_LeftShift() [1/2]
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_LeftShift (const VecI32VArg a, const VecShiftVArg shift)
VecI32V_LeftShift() [2/2]
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_LeftShift (const VecI32VArg a, const PxU32 count)
VecI32V_Merge()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Merge (const VecI32VArg a, const VecI32VArg b, const VecI32VArg c, const VecI32VArg d)
VecI32V_MinusOne()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_MinusOne ()
VecI32V_One()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_One ()
VecI32V_Or()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Or (const VecI32VArg a, const VecI32VArg b)
VecI32V_PrepareShift()
PX_FORCE_INLINE VecShiftV physx::aos::VecI32V_PrepareShift (const VecI32VArg shift)
VecI32V_ReinterpretFrom_Vec4V()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_ReinterpretFrom_Vec4V (Vec4V a)
VecI32V_RightShift() [1/2]
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_RightShift (const VecI32VArg a, const VecShiftVArg shift)
VecI32V_RightShift() [2/2]
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_RightShift (const VecI32VArg a, const PxU32 count)
VecI32V_Sel()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Sel (const BoolV c, const VecI32VArg a, const VecI32VArg b)
VecI32V_Sub()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Sub (const VecI32VArg a, const VecI32VArg b)
VecI32V_Two()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Two ()
VecI32V_Zero()
PX_FORCE_INLINE VecI32V physx::aos::VecI32V_Zero ()
VecU32V_From_BoolV()
PX_FORCE_INLINE VecU32V physx::aos::VecU32V_From_BoolV (const BoolVArg b)
VecU32V_ReinterpretFrom_Vec4V()
PX_FORCE_INLINE VecU32V physx::aos::VecU32V_ReinterpretFrom_Vec4V (Vec4V a)
Variable Documentation
g_PXCosCoefficients0
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXCosCoefficients0 = { { 1.0f, -0.5f, 4.166666667e-2f, -1.388888889e-3f } }
g_PXCosCoefficients1
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXCosCoefficients1 = { { 2.480158730e-5f, -2.755731922e-7f, 2.087675699e-9f, -1.147074560e-11f } }
g_PXCosCoefficients2
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXCosCoefficients2 = { { 4.779477332e-14f, -1.561920697e-16f, 4.110317623e-19f, -8.896791392e-22f } }
g_PXReciprocalTwoPi
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXReciprocalTwoPi = { { PxInvTwoPi, PxInvTwoPi, PxInvTwoPi, PxInvTwoPi } }
g_PXSinCoefficients0
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXSinCoefficients0 = { { 1.0f, -0.166666667f, 8.333333333e-3f, -1.984126984e-4f } }
g_PXSinCoefficients1
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXSinCoefficients1 = { { 2.755731922e-6f, -2.505210839e-8f, 1.605904384e-10f, -7.647163732e-13f } }
g_PXSinCoefficients2
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXSinCoefficients2 = { { 2.811457254e-15f, -8.220635247e-18f, 1.957294106e-20f, -3.868170171e-23f } }
g_PXTwoPi
PX_GLOBALCONST PX_VECTORF32 physx::aos::g_PXTwoPi = { { PxTwoPi, PxTwoPi, PxTwoPi, PxTwoPi } }