physx::aos::internalUnitSSE2Simd Namespace Reference
physx::aos::internalUnitSSE2Simd Namespace Reference
Functions
PX_FORCE_INLINE PxU32 BAllTrue4_R (const BoolV a)
PX_FORCE_INLINE PxU32 BAllTrue3_R (const BoolV a)
PX_FORCE_INLINE PxU32 BAnyTrue4_R (const BoolV a)
PX_FORCE_INLINE PxU32 BAnyTrue3_R (const BoolV a)
PX_FORCE_INLINE PxU32 FiniteTestEq (const Vec4V a, const Vec4V b)
Variables
const PxF32 gMaskXYZ [4]
Function Documentation
BAllTrue3_R()
PX_FORCE_INLINE PxU32 physx::aos::internalUnitSSE2Simd::BAllTrue3_R (const BoolV a)
BAllTrue4_R()
PX_FORCE_INLINE PxU32 physx::aos::internalUnitSSE2Simd::BAllTrue4_R (const BoolV a)
BAnyTrue3_R()
PX_FORCE_INLINE PxU32 physx::aos::internalUnitSSE2Simd::BAnyTrue3_R (const BoolV a)
BAnyTrue4_R()
PX_FORCE_INLINE PxU32 physx::aos::internalUnitSSE2Simd::BAnyTrue4_R (const BoolV a)
FiniteTestEq()
PX_FORCE_INLINE PxU32 physx::aos::internalUnitSSE2Simd::FiniteTestEq (const Vec4V a, const Vec4V b)
References physx::aos::FOne(), physx::aos::FZero(), and physx::aos::V4Sel().
Variable Documentation
gMaskXYZ
const PxF32 physx::aos::internalUnitSSE2Simd::gMaskXYZ[4]
Initial value:
= { physx::PxUnionCast<PxF32>(0xffffffff), physx::PxUnionCast<PxF32>(0xffffffff),
                                          physx::PxUnionCast<PxF32>(0xffffffff), 0 }