PxBasicTemplates.h File Reference
PxBasicTemplates.h File Reference
#include "foundation/PxPreprocessor.h"
Classes
struct PxEqual< A >
struct PxLess< A >
struct PxGreater< A >
class PxPair< F, S >
struct PxLogTwo< A >
struct PxLogTwo< 1 >
struct PxUnConst< T >
struct PxUnConst< const T >
Functions
template<typename T >
T PxPointerOffset (void *p, ptrdiff_t offset)
template<typename T >
T PxPointerOffset (const void *p, ptrdiff_t offset)
template<class T >
PX_CUDA_CALLABLE PX_INLINE void PxSwap (T &x, T &y)
Function Documentation
PxPointerOffset() [1/2]
template<typename T > T PxPointerOffset (void * p, ptrdiff_t offset)
PxPointerOffset() [2/2]
template<typename T > T PxPointerOffset (const void * p, ptrdiff_t offset)
PxSwap()
template<class T > PX_CUDA_CALLABLE PX_INLINE void PxSwap (T & x, T & y)
Referenced by PxRenderOutput::outputCapsule(), PxMedian3(), physx::PxOrder(), PxPartition(), and PxSmallSort().