PxBitUtils.h File Reference
PxBitUtils.h File Reference
#include "foundation/PxMathIntrinsics.h"
#include "foundation/PxAssert.h"
#include "foundation/PxIntrinsics.h"
Functions
PX_INLINE uint32_t PxBitCount (uint32_t v)
PX_INLINE bool PxIsPowerOfTwo (uint32_t x)
PX_INLINE uint32_t PxNextPowerOfTwo (uint32_t x)
PX_INLINE uint32_t PxLowestSetBit (uint32_t x)
PX_INLINE uint32_t PxHighestSetBit (uint32_t x)
PX_INLINE uint32_t PxILog2 (uint32_t num)
Function Documentation
PxBitCount()
PX_INLINE uint32_t PxBitCount (uint32_t v)
Referenced by PxBitMapBase< PxAllocator >::count().
PxHighestSetBit()
PX_INLINE uint32_t PxHighestSetBit (uint32_t x)
Return the index of the highest set bit. Not valid for zero arg.
References PX_ASSERT, and PxHighestSetBitUnsafe().
Referenced by PxBitMapBase< PxAllocator >::findLast().
PxILog2()
PX_INLINE uint32_t PxILog2 (uint32_t num)
References PX_ASSERT.
PxIsPowerOfTwo()
PX_INLINE bool PxIsPowerOfTwo (uint32_t x)
Referenced by PxgDynamicsMemoryConfig::isValid(), PxSceneDesc::isValid(), and PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::reserveInternal().
PxLowestSetBit()
PX_INLINE uint32_t PxLowestSetBit (uint32_t x)
Return the index of the highest set bit. Not valid for zero arg.
References PX_ASSERT, and PxLowestSetBitUnsafe().
Referenced by PxBitMapBase< PxAllocator >::Iterator::getNext(), PxBitMapBase< PxAllocator >::PxLoopIterator::getNext(), and PxBitMapBase< PxAllocator >::PxCircularIterator::getNext().
PxNextPowerOfTwo()
PX_INLINE uint32_t PxNextPowerOfTwo (uint32_t x)
Referenced by PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::reserveInternal().