PxHash.h File Reference
PxHash.h File Reference
#include "foundation/PxBasicTemplates.h"
#include "foundation/PxString.h"
Classes
struct PxHash< Key >
struct PxHash< const char * >
Functions
PX_FORCE_INLINE uint32_t PxComputeHash (const uint32_t key)
PX_FORCE_INLINE uint32_t PxComputeHash (const int32_t key)
PX_FORCE_INLINE uint32_t PxComputeHash (const uint64_t key)
PX_INLINE uint32_t PxComputeHash (const void *ptr)
template<typename F , typename S >
PX_INLINE uint32_t PxComputeHash (const PxPair< F, S > &p)
Function Documentation
PxComputeHash() [1/5]
PX_FORCE_INLINE uint32_t PxComputeHash (const uint32_t key)
Central definition of hash functions
Referenced by PxHash< Key >::operator()(), and PxComputeHash().
PxComputeHash() [2/5]
PX_FORCE_INLINE uint32_t PxComputeHash (const int32_t key)
References PxComputeHash().
PxComputeHash() [3/5]
PX_FORCE_INLINE uint32_t PxComputeHash (const uint64_t key)
PxComputeHash() [4/5]
PX_INLINE uint32_t PxComputeHash (const void * ptr)
References PxComputeHash().
PxComputeHash() [5/5]
template<typename F , typename S > PX_INLINE uint32_t PxComputeHash (const PxPair< F, S > & p)
References PxPair< F, S >::first, PxComputeHash(), and PxPair< F, S >::second.