PxRenderOutput.h File Reference
PxRenderOutput.h File Reference
#include "foundation/PxMat44.h"
#include "foundation/PxBasicTemplates.h"
#include "PxRenderBuffer.h"
Classes
class PxRenderOutput
struct PxDebugBox
struct PxDebugArrow
struct PxDebugBasis
struct PxDebugCircle
struct PxDebugArc
Functions
PX_FORCE_INLINE PxRenderOutput & operator<< (PxRenderOutput &out, const PxDebugBox &box)
PX_FORCE_INLINE void normalToTangents (const PxVec3 &normal, PxVec3 &tangent0, PxVec3 &tangent1)
PX_FORCE_INLINE PxRenderOutput & operator<< (PxRenderOutput &out, const PxDebugArrow &arrow)
PX_FORCE_INLINE PxRenderOutput & operator<< (PxRenderOutput &out, const PxDebugBasis &basis)
PX_FORCE_INLINE PxRenderOutput & operator<< (PxRenderOutput &out, const PxDebugCircle &circle)
PX_FORCE_INLINE PxRenderOutput & operator<< (PxRenderOutput &out, const PxDebugArc &arc)
Function Documentation
normalToTangents()
PX_FORCE_INLINE void normalToTangents (const PxVec3 & normal, PxVec3 & tangent0, PxVec3 & tangent1)
References PxVec3T< Type >::cross(), PxVec3T< Type >::normalize(), PxAbs(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by operator<<().
operator<<() [1/5]
PX_FORCE_INLINE PxRenderOutput& operator<< (PxRenderOutput & out, const PxDebugBox & box)
References PxRenderOutput::LINES, PxRenderOutput::LINESTRIP, PxDebugBox::maximum, PxDebugBox::minimum, PxRenderOutput::TRIANGLESTRIP, PxDebugBox::wireframe, PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
operator<<() [2/5]
PX_FORCE_INLINE PxRenderOutput& operator<< (PxRenderOutput & out, const PxDebugArrow & arrow)
References PxDebugArrow::base, PxDebugArrow::headLength, PxRenderOutput::LINES, PxVec3T< Type >::normalize(), normalToTangents(), PxSqrt(), PxDebugArrow::tip, and PxRenderOutput::TRIANGLESTRIP.
operator<<() [3/5]
PX_FORCE_INLINE PxRenderOutput& operator<< (PxRenderOutput & out, const PxDebugBasis & basis)
References PxDebugBasis::colorX, PxDebugBasis::colorY, PxDebugBasis::colorZ, PxDebugBasis::extends, PxVec3T< Type >::magnitude(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
operator<<() [4/5]
PX_FORCE_INLINE PxRenderOutput& operator<< (PxRenderOutput & out, const PxDebugCircle & circle)
References PxRenderOutput::LINESTRIP, PxDebugCircle::nSegments, PxCos(), PxSin(), PxTwoPi, and PxDebugCircle::radius.
operator<<() [5/5]
PX_FORCE_INLINE PxRenderOutput& operator<< (PxRenderOutput & out, const PxDebugArc & arc)
References PxRenderOutput::LINESTRIP, PxDebugArc::maxAngle, PxDebugArc::minAngle, PxDebugArc::nSegments, PxCos(), PxSin(), and PxDebugArc::radius.