PxString.h File Reference
PxString.h File Reference
#include "foundation/PxPreprocessor.h"
#include "foundation/PxSimpleTypes.h"
#include "foundation/PxFoundationConfig.h"
#include <stdarg.h>
Functions
PX_FOUNDATION_API int32_t Pxsscanf (const char *buffer, const char *format,...)
PX_FOUNDATION_API int32_t Pxstrcmp (const char *str1, const char *str2)
PX_FOUNDATION_API int32_t Pxstrncmp (const char *str1, const char *str2, size_t count)
PX_FOUNDATION_API int32_t Pxsnprintf (char *dst, size_t dstSize, const char *format,...)
PX_FOUNDATION_API int32_t Pxvsnprintf (char *dst, size_t dstSize, const char *src, va_list arg)
PX_FOUNDATION_API size_t Pxstrlcat (char *dst, size_t dstSize, const char *src)
PX_FOUNDATION_API size_t Pxstrlcpy (char *dst, size_t dstSize, const char *src)
PX_FOUNDATION_API int32_t Pxstricmp (const char *str1, const char *str2)
PX_FOUNDATION_API int32_t Pxstrnicmp (const char *str1, const char *str2, size_t count)
PX_FOUNDATION_API void Pxstrlwr (char *str)
PX_FOUNDATION_API void Pxstrupr (char *str)
PX_FOUNDATION_API void PxPrintString (const char *)
Prints the string literally (does not consume % specifier), trying to make sure it's visible to the app programmer.
Function Documentation
PxPrintString()
PX_FOUNDATION_API void PxPrintString (const char *)
Prints the string literally (does not consume % specifier), trying to make sure it's visible to the app programmer.
Pxsnprintf()
PX_FOUNDATION_API int32_t Pxsnprintf (char * dst, size_t dstSize, const char * format, ...)
Referenced by ExtGpu::_testLaunch(), ExtGpu::outputKernelLaunchDebugInfo(), and ExtGpu::outputKernelLaunchError().
Pxsscanf()
PX_FOUNDATION_API int32_t Pxsscanf (const char * buffer, const char * format, ...)
Pxstrcmp()
PX_FOUNDATION_API int32_t Pxstrcmp (const char * str1, const char * str2)
Referenced by PxHash< const char * >::equal().
Pxstricmp()
PX_FOUNDATION_API int32_t Pxstricmp (const char * str1, const char * str2)
Pxstrlcat()
PX_FOUNDATION_API size_t Pxstrlcat (char * dst, size_t dstSize, const char * src)
Pxstrlcpy()
PX_FOUNDATION_API size_t Pxstrlcpy (char * dst, size_t dstSize, const char * src)
Pxstrlwr()
PX_FOUNDATION_API void Pxstrlwr (char * str)
Pxstrncmp()
PX_FOUNDATION_API int32_t Pxstrncmp (const char * str1, const char * str2, size_t count)
Pxstrnicmp()
PX_FOUNDATION_API int32_t Pxstrnicmp (const char * str1, const char * str2, size_t count)
Pxstrupr()
PX_FOUNDATION_API void Pxstrupr (char * str)
Pxvsnprintf()
PX_FOUNDATION_API int32_t Pxvsnprintf (char * dst, size_t dstSize, const char * src, va_list arg)