PxSwitchIntrinsics.h File Reference
PxSwitchIntrinsics.h File Reference
#include "foundation/PxAssert.h"
#include <math.h>
Functions
PX_FORCE_INLINE void PxMemoryBarrier ()
PX_FORCE_INLINE PxU32 PxHighestSetBitUnsafe (PxU32 v)
PX_FORCE_INLINE PxU32 PxLowestSetBitUnsafe (PxU32 v)
PX_FORCE_INLINE PxU32 PxCountLeadingZeros (PxU32 v)
PX_FORCE_INLINE void PxPrefetchLine (const void *ptr, PxU32 offset=0)
PX_FORCE_INLINE void PxPrefetch (const void *ptr, PxU32 count=1)
Function Documentation
PxCountLeadingZeros()
PX_FORCE_INLINE PxU32 PxCountLeadingZeros (PxU32 v)
Returns the number of leading zeros in v. Returns 32 for v=0.
PxHighestSetBitUnsafe()
PX_FORCE_INLINE PxU32 PxHighestSetBitUnsafe (PxU32 v)
Returns the index of the highest set bit. Not valid for zero arg.
Referenced by PxHighestSetBit().
PxLowestSetBitUnsafe()
PX_FORCE_INLINE PxU32 PxLowestSetBitUnsafe (PxU32 v)
Returns the index of the highest set bit. Undefined for zero arg.
Referenced by PxLowestSetBit().
PxMemoryBarrier()
PX_FORCE_INLINE void PxMemoryBarrier ()
PxPrefetch()
PX_FORCE_INLINE void PxPrefetch (const void * ptr, PxU32 count = 1)
Prefetch count bytes starting at ptr.
References PxPrefetchLine().
PxPrefetchLine()
PX_FORCE_INLINE void PxPrefetchLine (const void * ptr, PxU32 offset = 0)
Prefetch aligned cache size around ptr+offset.
References PX_RESTRICT.
Referenced by PxHashBase< Key, Key, HashFn, GetKey, PxAllocator, Coalesced >::clear(), and PxPrefetch().