PxSwitchMathIntrinsics.h File Reference
PxSwitchMathIntrinsics.h File Reference
#include "foundation/Px.h"
#include "foundation/PxAssert.h"
#include <math.h>
#include <float.h>
#include "nn/cstd/cstd_CMath.h"
Functions
PX_CUDA_CALLABLE PX_FORCE_INLINE float abs (float a)
platform-specific absolute value
PX_CUDA_CALLABLE PX_FORCE_INLINE float fsel (float a, float b, float c)
platform-specific select float
PX_CUDA_CALLABLE PX_FORCE_INLINE float sign (float a)
platform-specific sign
PX_CUDA_CALLABLE PX_FORCE_INLINE float recip (float a)
platform-specific reciprocal
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipFast (float a)
platform-specific reciprocal estimate
PX_CUDA_CALLABLE PX_FORCE_INLINE float sqrt (float a)
platform-specific square root
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrt (float a)
platform-specific reciprocal square root
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrtFast (float a)
platform-specific reciprocal square root estimate
PX_CUDA_CALLABLE PX_FORCE_INLINE float sin (float a)
platform-specific sine
PX_CUDA_CALLABLE PX_FORCE_INLINE float cos (float a)
platform-specific cosine
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMin (float a, float b)
platform-specific minimum
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMax (float a, float b)
platform-specific maximum
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (float a)
platform-specific finiteness check
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (double a)
platform-specific finiteness check
PX_FORCE_INLINE void * memZero (void *dest, uint32_t count)
PX_FORCE_INLINE void * memSet (void *dest, int32_t c, uint32_t count)
PX_FORCE_INLINE void * memCopy (void *dest, const void *src, uint32_t count)
PX_FORCE_INLINE void * memMove (void *dest, const void *src, uint32_t count)
Function Documentation
abs()
PX_CUDA_CALLABLE PX_FORCE_INLINE float abs (float a)
platform-specific absolute value
Referenced by PxStrideIterator< T >::isCompatible(), and PxAbs().
cos()
PX_CUDA_CALLABLE PX_FORCE_INLINE float cos (float a)
platform-specific cosine
Referenced by PxComputeAngle(), PxCos(), PxSinCos(), and PxTanHalf().
fsel()
PX_CUDA_CALLABLE PX_FORCE_INLINE float fsel (float a, float b, float c)
platform-specific select float
Referenced by PxVehicleComputeSign().
isFinite() [1/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (float a)
platform-specific finiteness check
Referenced by aos::PxTransformV::getInverse(), PxTransformT< float >::getInverse(), PxVec2T< Type >::isNormalized(), PxVec3T< float >::isNormalized(), PxVec4T< float >::isNormalized(), PxQuatT< float >::isSane(), aos::PxTransformV::isSane(), PxTransformT< float >::isSane(), PxQuatT< float >::isUnit(), PxControllerDesc::isValid(), aos::PxTransformV::rotate(), PxTransformT< float >::rotate(), aos::PxTransformV::rotateInv(), PxTransformT< float >::rotateInv(), aos::PxTransformV::transform(), PxTransformT< float >::transform(), aos::PxTransformV::transformInv(), and PxTransformT< float >::transformInv().
isFinite() [2/2]
PX_CUDA_CALLABLE PX_FORCE_INLINE bool isFinite (double a)
platform-specific finiteness check
memCopy()
PX_FORCE_INLINE void* memCopy (void * dest, const void * src, uint32_t count)
Copies count bytes from src to dst. User memMove if regions overlap.
Referenced by PxMemCopy().
memMove()
PX_FORCE_INLINE void* memMove (void * dest, const void * src, uint32_t count)
Copies count bytes from src to dst. Supports overlapping regions.
Referenced by PxMemMove().
memSet()
PX_FORCE_INLINE void* memSet (void * dest, int32_t c, uint32_t count)
Sets count bytes starting at dst to c.
Referenced by PxMemSet().
memZero()
PX_FORCE_INLINE void* memZero (void * dest, uint32_t count)
Sets count bytes starting at dst to zero.
Referenced by PxMemZero().
recip()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recip (float a)
platform-specific reciprocal
Referenced by physx::aos::recip_newton(), and physx::aos::recipq_newton().
recipFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipFast (float a)
platform-specific reciprocal estimate
recipSqrt()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrt (float a)
platform-specific reciprocal square root
recipSqrtFast()
PX_CUDA_CALLABLE PX_FORCE_INLINE float recipSqrtFast (float a)
platform-specific reciprocal square root estimate
selectMax()
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMax (float a, float b)
platform-specific maximum
selectMin()
PX_CUDA_CALLABLE PX_FORCE_INLINE float selectMin (float a, float b)
platform-specific minimum
sign()
PX_CUDA_CALLABLE PX_FORCE_INLINE float sign (float a)
platform-specific sign
Referenced by PxSign().
sin()
PX_CUDA_CALLABLE PX_FORCE_INLINE float sin (float a)
platform-specific sine
Referenced by PxComputeAngle(), PxSin(), PxSinCos(), and PxTanHalf().
sqrt()
PX_CUDA_CALLABLE PX_FORCE_INLINE float sqrt (float a)
platform-specific square root
Referenced by PxRecipSqrt(), and PxSqrt().