PxVehicleFrame Struct Reference
PxVehicleFrame Struct Reference
Vehicle2
#include <PxVehicleParams.h>
Public Member Functions
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxMat33 getFrame () const
PX_FORCE_INLINE PxVec3 getLngAxis () const
PX_FORCE_INLINE PxVec3 getLatAxis () const
PX_FORCE_INLINE PxVec3 getVrtAxis () const
PX_FORCE_INLINE bool isValid () const
Public Attributes
PxVehicleAxes::Enum lngAxis
The axis defining the longitudinal (forward) direction of the vehicle.
PxVehicleAxes::Enum latAxis
The axis defining the lateral (side) direction of the vehicle.
PxVehicleAxes::Enum vrtAxis
The axis defining the vertical (up) direction of the vehicle.
Member Function Documentation
getFrame()
PX_FORCE_INLINE PxMat33 PxVehicleFrame::getFrame () const inline
Referenced by PxVehicleComputeRotation(), PxVehicleComputeTranslation(), PxVehicleTransformFrameToFrame(), and PxVehicleSimulationContext::transformAndScale().
getLatAxis()
PX_FORCE_INLINE PxVec3 PxVehicleFrame::getLatAxis () const inline
Referenced by PxVehicleRigidBodyState::getLateralSpeed().
getLngAxis()
PX_FORCE_INLINE PxVec3 PxVehicleFrame::getLngAxis () const inline
Referenced by PxVehicleRigidBodyState::getLongitudinalSpeed().
getVrtAxis()
PX_FORCE_INLINE PxVec3 PxVehicleFrame::getVrtAxis () const inline
Referenced by PxVehicleRigidBodyState::getVerticalSpeed(), and PxVehicleSimulationContext::setToDefault().
isValid()
PX_FORCE_INLINE bool PxVehicleFrame::isValid () const inline
References PxVehicleAxes::eMAX_NB_AXES, PxQuatT< Type >::isFinite(), PxQuatT< Type >::isSane(), PxQuatT< Type >::isUnit(), and PX_CHECK_AND_RETURN_VAL.
setToDefault()
PX_FORCE_INLINE void PxVehicleFrame::setToDefault () inline
References PxVehicleAxes::ePosX, PxVehicleAxes::ePosY, and PxVehicleAxes::ePosZ.
Referenced by PxVehicleSimulationContext::setToDefault().
Member Data Documentation
latAxis
PxVehicleAxes::Enum PxVehicleFrame::latAxis
The axis defining the lateral (side) direction of the vehicle.
Referenced by PxVehicleTransformFrameToFrame().
lngAxis
PxVehicleAxes::Enum PxVehicleFrame::lngAxis
The axis defining the longitudinal (forward) direction of the vehicle.
Referenced by PxVehicleTransformFrameToFrame().
vrtAxis
PxVehicleAxes::Enum PxVehicleFrame::vrtAxis
The axis defining the vertical (up) direction of the vehicle.
Referenced by PxVehicleTransformFrameToFrame().
The documentation for this struct was generated from the following file:
PxVehicleParams.h