PxVehicleMultiWheelDriveDifferentialParams Struct Reference
PxVehicleMultiWheelDriveDifferentialParams Struct Reference
Vehicle2
PxVehicleMultiWheelDriveDifferentialParams specifies the wheels that are to receive drive torque from the differential and the division of torque between the wheels that are connected to the differential.
#include <PxVehicleDrivetrainParams.h>
Public Member Functions
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxVehicleMultiWheelDriveDifferentialParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid (const PxVehicleAxleDescription &axleDesc) const
Public Attributes
PxReal torqueRatios [PxVehicleLimits::eMAX_NB_WHEELS]
torqueRatios describes the fraction of torque delivered to each wheel through the differential.
PxReal aveWheelSpeedRatios [PxVehicleLimits::eMAX_NB_WHEELS]
aveWheelSpeedRatios describes the contribution of each wheel to the average wheel speed measured at the clutch.
Detailed Description
PxVehicleMultiWheelDriveDifferentialParams specifies the wheels that are to receive drive torque from the differential and the division of torque between the wheels that are connected to the differential.
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleMultiWheelDriveDifferentialParams::isValid (const PxVehicleAxleDescription & axleDesc) const inline
References PxVehicleAxleDescription::isValid(), PxVehicleAxleDescription::nbWheels, PX_CHECK_AND_RETURN_VAL, PxAbs(), and PxVehicleAxleDescription::wheelIdsInAxleOrder.
Referenced by PxVehicleFourWheelDriveDifferentialParams::isValid(), and PxVehicleTankDriveDifferentialParams::isValid().
setToDefault()
PX_FORCE_INLINE void PxVehicleMultiWheelDriveDifferentialParams::setToDefault () inline
References PxMemZero().
Referenced by PxVehicleFourWheelDriveDifferentialParams::setToDefault(), and PxVehicleTankDriveDifferentialParams::setToDefault().
transformAndScale()
PX_FORCE_INLINE PxVehicleMultiWheelDriveDifferentialParams PxVehicleMultiWheelDriveDifferentialParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PX_UNUSED().
Referenced by PxVehicleFourWheelDriveDifferentialParams::transformAndScale(), and PxVehicleTankDriveDifferentialParams::transformAndScale().
Member Data Documentation
aveWheelSpeedRatios
PxReal PxVehicleMultiWheelDriveDifferentialParams::aveWheelSpeedRatios[PxVehicleLimits::eMAX_NB_WHEELS]
aveWheelSpeedRatios describes the contribution of each wheel to the average wheel speed measured at the clutch.
Note
Wheels not connected to the differential do not contribute to the average wheel speed measured at the clutch.
Wheels connected to the differential may delivere a non-zero contribution to the average wheel speed measured at the clutch.
The sum of all ratios of all wheels must equal to 1.0.
Range: [0, 1]
torqueRatios
PxReal PxVehicleMultiWheelDriveDifferentialParams::torqueRatios[PxVehicleLimits::eMAX_NB_WHEELS]
torqueRatios describes the fraction of torque delivered to each wheel through the differential.
Note
Wheels not connected to the differential must receive zero torque.
Wheels connected to the differential may receive a non-zero torque.
The sum of the absolute of the ratios of all wheels must equal to 1.0.
A negative torque ratio simulates a wheel with negative gearing applied.
Range: [1, -1]
The documentation for this struct was generated from the following file:
PxVehicleDrivetrainParams.h