PxArticulationLinkDataRC Struct Reference
PxArticulationLinkDataRC Struct Reference
Immediatemode
#include <PxImmediateMode.h>
Public Member Functions
PxArticulationLinkDataRC ()
void initData ()
Public Member Functions inherited from PxArticulationLinkMutableDataRC
void initData ()
Public Attributes
PxArticulationJointDataRC inboundJoint
PxTransform pose
Public Attributes inherited from PxArticulationLinkMutableDataRC
PxVec3 inverseInertia
float inverseMass
float linearDamping
float angularDamping
float maxLinearVelocitySq
float maxAngularVelocitySq
float cfmScale
bool disableGravity
Constructor & Destructor Documentation
PxArticulationLinkDataRC()
PxArticulationLinkDataRC::PxArticulationLinkDataRC () inline
References initData().
Member Function Documentation
initData()
void PxArticulationLinkDataRC::initData () inline
References PxArticulationLinkMutableDataRC::initData(), and PxIdentity.
Referenced by PxArticulationLinkDataRC().
Member Data Documentation
inboundJoint
PxArticulationJointDataRC PxArticulationLinkDataRC::inboundJoint
pose
PxTransform PxArticulationLinkDataRC::pose
The documentation for this struct was generated from the following file:
PxImmediateMode.h