PxVehicleTireStickyParams Struct Reference
PxVehicleTireStickyParams Struct Reference
Vehicle2
For each tire, the forces of the tire model may be replaced by velocity constraints when the tire enters the "sticky tire" regime. The "sticky tire" regime of the lateral and longitudinal directions of the tire are managed separately.
#include <PxVehicleParams.h>
Public Member Functions
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxVehicleTireStickyParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid () const
Public Attributes
PxVehicleTireAxisStickyParams stickyParams [PxVehicleTireDirectionModes::eMAX_NB_PLANAR_DIRECTIONS]
Detailed Description
For each tire, the forces of the tire model may be replaced by velocity constraints when the tire enters the "sticky tire" regime. The "sticky tire" regime of the lateral and longitudinal directions of the tire are managed separately.
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleTireStickyParams::isValid () const inline
References PxVehicleTireDirectionModes::eLATERAL, and PxVehicleTireDirectionModes::eLONGITUDINAL.
setToDefault()
PX_FORCE_INLINE void PxVehicleTireStickyParams::setToDefault () inline
References PxVehicleTireAxisStickyParams::damping, PxVehicleTireDirectionModes::eLATERAL, PxVehicleTireDirectionModes::eLONGITUDINAL, PxVehicleTireAxisStickyParams::thresholdSpeed, and PxVehicleTireAxisStickyParams::thresholdTime.
Referenced by PxVehicleSimulationContext::setToDefault().
transformAndScale()
PX_FORCE_INLINE PxVehicleTireStickyParams PxVehicleTireStickyParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PxVehicleTireDirectionModes::eLATERAL, PxVehicleTireDirectionModes::eLONGITUDINAL, stickyParams, and PxVehicleTireAxisStickyParams::transformAndScale().
Referenced by PxVehicleSimulationContext::transformAndScale().
Member Data Documentation
stickyParams
PxVehicleTireAxisStickyParams PxVehicleTireStickyParams::stickyParams[PxVehicleTireDirectionModes::eMAX_NB_PLANAR_DIRECTIONS]
The "sticky tire" regime of the lateral and longitudinal directions of the tire are managed separately and are individually parameterized.
Referenced by transformAndScale(), and PxVehiclePhysXConstraintComponent::update().
The documentation for this struct was generated from the following file:
PxVehicleParams.h