PxVehicleSuspensionComplianceParams Struct Reference
PxVehicleSuspensionComplianceParams Struct Reference
Vehicle2
Compliance describes how toe and camber angle and force application points are affected by suspension compression.
#include <PxVehicleSuspensionParams.h>
Public Member Functions
PX_FORCE_INLINE PxVehicleSuspensionComplianceParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid () const
Public Attributes
PxVehicleFixedSizeLookupTable< PxReal, 3 > wheelToeAngle
A graph of toe angle against jounce/suspensionTravelDist with the toe angle expressed in radians.
PxVehicleFixedSizeLookupTable< PxReal, 3 > wheelCamberAngle
A graph of camber angle against jounce/suspensionTravelDist with the camber angle expressed in radians.
PxVehicleFixedSizeLookupTable< PxVec3, 3 > suspForceAppPoint
Suspension forces are applied at an offset from the suspension frame. suspForceAppPoint specifies the (X, Y, Z) components of that offset as a function of jounce/suspensionTravelDist.
PxVehicleFixedSizeLookupTable< PxVec3, 3 > tireForceAppPoint
Tire forces are applied at an offset from the suspension frame. tireForceAppPoint specifies the (X, Y, Z) components of that offset as a function of jounce/suspensionTravelDist.
Detailed Description
Compliance describes how toe and camber angle and force application points are affected by suspension compression.
Note
Each compliance term is in the form of a graph with up to 3 points.
Each point in the graph has form (jounce/suspensionTravelDist, complianceValue).
The sequence of points must respresent monotonically increasing values of jounce.
The compliance value can be computed by linear interpolation.
If any graph has zero points in it, a value of 0.0 is used for the compliance value.
If any graph has 1 point in it, the compliance value of that point is used directly.
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleSuspensionComplianceParams::isValid () const inline
References PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >::isValid(), PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >::nbDataPairs, PX_CHECK_AND_RETURN_VAL, PxPi, PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >::xVals, and PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >::yVals.
transformAndScale()
PX_FORCE_INLINE PxVehicleSuspensionComplianceParams PxVehicleSuspensionComplianceParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PX_UNUSED(), PxVehicleTransformFrameToFrame(), PxVehicleScale::scale, suspForceAppPoint, tireForceAppPoint, and PxVehicleFixedSizeLookupTable< T, NB_ELEMENTS >::yVals.
Member Data Documentation
suspForceAppPoint
PxVehicleFixedSizeLookupTable<PxVec3, 3> PxVehicleSuspensionComplianceParams::suspForceAppPoint
Suspension forces are applied at an offset from the suspension frame. suspForceAppPoint specifies the (X, Y, Z) components of that offset as a function of jounce/suspensionTravelDist.
Referenced by transformAndScale().
tireForceAppPoint
PxVehicleFixedSizeLookupTable<PxVec3, 3> PxVehicleSuspensionComplianceParams::tireForceAppPoint
Tire forces are applied at an offset from the suspension frame. tireForceAppPoint specifies the (X, Y, Z) components of that offset as a function of jounce/suspensionTravelDist.
Referenced by transformAndScale().
wheelCamberAngle
PxVehicleFixedSizeLookupTable<PxReal, 3> PxVehicleSuspensionComplianceParams::wheelCamberAngle
A graph of camber angle against jounce/suspensionTravelDist with the camber angle expressed in radians.
Note
The camber angle is applied in the suspension frame.
wheelToeAngle
PxVehicleFixedSizeLookupTable<PxReal, 3> PxVehicleSuspensionComplianceParams::wheelToeAngle
A graph of toe angle against jounce/suspensionTravelDist with the toe angle expressed in radians.
Note
The toe angle is applied in the suspension frame.
The documentation for this struct was generated from the following file:
PxVehicleSuspensionParams.h