PxVehicleTankDriveDifferentialParams Struct Reference
PxVehicleTankDriveDifferentialParams Struct Reference
Vehicle2
A description of a tank differential.
#include <PxVehicleDrivetrainParams.h>
Public Member Functions
PX_FORCE_INLINE void setToDefault ()
void addTankTrack (const PxU32 nbWheelsInTrackToAdd, const PxU32 *const wheelIdsInTrackToAdd, const PxU32 thrustControllerIndex)
Add a tank track by specifying the number of wheels along the track track and an array of wheel ids specifying each wheel in the tank track.
PX_FORCE_INLINE PxU32 getNbTracks () const
Return the number of tracks.
PX_FORCE_INLINE PxU32 getNbWheelsInTrack (const PxU32 i) const
Return the number of wheels in the ith track.
PX_FORCE_INLINE const PxU32 * getWheelsInTrack (const PxU32 i) const
Return the array of all wheels in the ith track.
PX_FORCE_INLINE PxU32 getWheelInTrack (const PxU32 j, const PxU32 i) const
Return the wheel id of the jth wheel in the ith track.
PX_FORCE_INLINE PxU32 getThrustControllerIndex (const PxU32 i) const
Return the index of the thrust controller that will control a specified track.
PX_FORCE_INLINE PxVehicleTankDriveDifferentialParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid (const PxVehicleAxleDescription &axleDesc) const
Public Member Functions inherited from PxVehicleMultiWheelDriveDifferentialParams
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxVehicleMultiWheelDriveDifferentialParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid (const PxVehicleAxleDescription &axleDesc) const
Public Attributes
PxU32 nbTracks
The number of tracks.
PxU32 thrustIdPerTrack [PxVehicleLimits::eMAX_NB_WHEELS]
The id of the thrust that will control the track. Must have value 0 or 1.
PxU32 nbWheelsPerTrack [PxVehicleLimits::eMAX_NB_WHEELS]
The number of wheels in each track.
PxU32 trackToWheelIds [PxVehicleLimits::eMAX_NB_WHEELS]
The list of wheel ids for the ith tank track begins at wheelIdsInTrackOrder[trackToWheelIds[i]].
PxU32 wheelIdsInTrackOrder [PxVehicleLimits::eMAX_NB_WHEELS]
The list of all wheel ids in all tracks.
PxU32 nbWheelsInTracks
The number of wheels in all tracks.
Public Attributes inherited from PxVehicleMultiWheelDriveDifferentialParams
PxReal torqueRatios [PxVehicleLimits::eMAX_NB_WHEELS]
torqueRatios describes the fraction of torque delivered to each wheel through the differential.
PxReal aveWheelSpeedRatios [PxVehicleLimits::eMAX_NB_WHEELS]
aveWheelSpeedRatios describes the contribution of each wheel to the average wheel speed measured at the clutch.
Detailed Description
A description of a tank differential.
Note
The wheels on a tank may be connected to the differential or not connected to the differential.
The wheels on a tank track may be connected to a tank track or not connected to a tank track.
Wheels connected to the differential but not to a tank track receive the torque split specified by the corresponding elements of PxVehicleMultiWheelDriveDifferentialParams::torqueRatios[].
Wheels connected to a tank track but not to the differential receive no torque from the engine.
Wheels connected to a tank track and to the differential receive the torque split specified by the corresponding elements of PxVehicleMultiWheelDriveDifferentialParams::torqueRatios[] multiplied by the corresponding thrust controller value. If the thrust controller has a negative value, the wheels will receive a torque that is negative with respect to the gearing ratio.
The wheels in each tank track have a constraint applied to them to enforce the rule that they all have the same longitudinal speed at the contact point between the wheel and the tank track.
Member Function Documentation
addTankTrack()
void PxVehicleTankDriveDifferentialParams::addTankTrack (const PxU32 nbWheelsInTrackToAdd, const PxU32 *const wheelIdsInTrackToAdd, const PxU32 thrustControllerIndex) inline
Add a tank track by specifying the number of wheels along the track track and an array of wheel ids specifying each wheel in the tank track.
Parameters
[in] nbWheelsInTrackToAdd is the number of wheels in the track to be added.
[in] wheelIdsInTrackToAdd is an array of wheel ids specifying all the wheels in the track to be added.
[in] thrustControllerIndex specifies the index of the thrust controller that will be used to control the tank track.
References PxVehicleLimits::eMAX_NB_WHEELS, and PX_ASSERT.
getNbTracks()
PX_FORCE_INLINE PxU32 PxVehicleTankDriveDifferentialParams::getNbTracks () const inline
Return the number of tracks.
Returns
The number of tracks.
See also
getNbWheelsInTrack()
getNbWheelsInTrack()
PX_FORCE_INLINE PxU32 PxVehicleTankDriveDifferentialParams::getNbWheelsInTrack (const PxU32 i) const inline
Return the number of wheels in the ith track.
Parameters
[in] i specifies the track to be queried for its wheel count.
Returns
The number of wheels in the specified track.
See also
getWheelInTrack()
getThrustControllerIndex()
PX_FORCE_INLINE PxU32 PxVehicleTankDriveDifferentialParams::getThrustControllerIndex (const PxU32 i) const inline
Return the index of the thrust controller that will control a specified track.
Parameters
[in] i specifies the track to be queried for its thrust controller index
Returns
The index of the thrust controller that will control the ith track.
getWheelInTrack()
PX_FORCE_INLINE PxU32 PxVehicleTankDriveDifferentialParams::getWheelInTrack (const PxU32 j, const PxU32 i) const inline
Return the wheel id of the jth wheel in the ith track.
Parameters
[in] j specifies that the wheel id to be returned is the jth wheel in the list of wheels on the specified track.
[in] i specifies the track to be queried.
Returns
The wheel id of the jth wheel in the ith track.
See also
getNbWheelsInTrack()
getWheelsInTrack()
PX_FORCE_INLINE const PxU32* PxVehicleTankDriveDifferentialParams::getWheelsInTrack (const PxU32 i) const inline
Return the array of all wheels in the ith track.
Parameters
[in] i specifies the track to be queried for its wheels.
Returns
The array of wheels in the specified track.
isValid()
PX_FORCE_INLINE bool PxVehicleTankDriveDifferentialParams::isValid (const PxVehicleAxleDescription & axleDesc) const inline
References PxVehicleLimits::eMAX_NB_WHEELS, PxVehicleMultiWheelDriveDifferentialParams::isValid(), PxVehicleAxleDescription::nbWheels, PX_CHECK_AND_RETURN_VAL, and PxVehicleAxleDescription::wheelIdsInAxleOrder.
setToDefault()
PX_FORCE_INLINE void PxVehicleTankDriveDifferentialParams::setToDefault () inline
References PxVehicleMultiWheelDriveDifferentialParams::setToDefault().
transformAndScale()
PX_FORCE_INLINE PxVehicleTankDriveDifferentialParams PxVehicleTankDriveDifferentialParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PX_UNUSED(), and PxVehicleMultiWheelDriveDifferentialParams::transformAndScale().
Member Data Documentation
nbTracks
PxU32 PxVehicleTankDriveDifferentialParams::nbTracks
The number of tracks.
nbWheelsInTracks
PxU32 PxVehicleTankDriveDifferentialParams::nbWheelsInTracks
The number of wheels in all tracks.
nbWheelsPerTrack
PxU32 PxVehicleTankDriveDifferentialParams::nbWheelsPerTrack[PxVehicleLimits::eMAX_NB_WHEELS]
The number of wheels in each track.
thrustIdPerTrack
PxU32 PxVehicleTankDriveDifferentialParams::thrustIdPerTrack[PxVehicleLimits::eMAX_NB_WHEELS]
The id of the thrust that will control the track. Must have value 0 or 1.
trackToWheelIds
PxU32 PxVehicleTankDriveDifferentialParams::trackToWheelIds[PxVehicleLimits::eMAX_NB_WHEELS]
The list of wheel ids for the ith tank track begins at wheelIdsInTrackOrder[trackToWheelIds[i]].
wheelIdsInTrackOrder
PxU32 PxVehicleTankDriveDifferentialParams::wheelIdsInTrackOrder[PxVehicleLimits::eMAX_NB_WHEELS]
The list of all wheel ids in all tracks.
The documentation for this struct was generated from the following file:
PxVehicleDrivetrainParams.h