PxVehicleTireSlipParams Struct Reference
PxVehicleTireSlipParams Struct Reference
Vehicle2
Tire slip values are computed using ratios with potential for divide-by-zero errors. PxVehicleTireSlipParams introduces a minimum value for the denominator of each of these ratios.
#include <PxVehicleParams.h>
Public Member Functions
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxVehicleTireSlipParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid () const
Public Attributes
PxReal minLatSlipDenominator
The lateral slip angle is typically computed as a function of the ratio of lateral and longitudinal speeds of the rigid body in the tire's frame. This leads to a divide-by-zero in the event that the longitudinal speed approaches zero. The parameter minLatSlipDenominator sets a minimum denominator for the ratio of speeds used to compute the lateral slip angle.
PxReal minPassiveLongSlipDenominator
The longitudinal slip represents the difference between the longitudinal speed of the rigid body in the tire's frame and the linear speed arising from the rotation of the wheel. This is typically normalized using the reciprocal of the longitudinal speed of the rigid body in the tire's frame. This leads to a divide-by-zero in the event that the longitudinal speed approaches zero. The parameter minPassiveLongSlipDenominator sets a minimum denominator for the normalized longitudinal slip when the wheel experiences zero drive torque and zero brake torque and zero handbrake torque. The aim is to bring the vehicle to rest without experiencing wheel rotational speeds that oscillate around zero.
PxReal minActiveLongSlipDenominator
The longitudinal slip represents the difference between the longitudinal speed of the rigid body in the tire's frame and the linear speed arising from the rotation of the wheel. This is typically normalized using the reciprocal of the longitudinal speed of the rigid body in the tire's frame. This leads to a divide-by-zero in the event that the longitudinal speed approaches zero. The parameter minActiveLongSlipDenominator sets a minimum denominator for the normalized longitudinal slip when the wheel experiences either a non-zero drive torque or a non-zero brake torque or a non-zero handbrake torque.
Detailed Description
Tire slip values are computed using ratios with potential for divide-by-zero errors. PxVehicleTireSlipParams introduces a minimum value for the denominator of each of these ratios.
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleTireSlipParams::isValid () const inline
References PX_CHECK_AND_RETURN_VAL.
setToDefault()
PX_FORCE_INLINE void PxVehicleTireSlipParams::setToDefault () inline
Referenced by PxVehicleSimulationContext::setToDefault().
transformAndScale()
PX_FORCE_INLINE PxVehicleTireSlipParams PxVehicleTireSlipParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References minActiveLongSlipDenominator, minLatSlipDenominator, minPassiveLongSlipDenominator, PX_UNUSED(), and PxVehicleScale::scale.
Referenced by PxVehicleSimulationContext::transformAndScale().
Member Data Documentation
minActiveLongSlipDenominator
PxReal PxVehicleTireSlipParams::minActiveLongSlipDenominator
The longitudinal slip represents the difference between the longitudinal speed of the rigid body in the tire's frame and the linear speed arising from the rotation of the wheel. This is typically normalized using the reciprocal of the longitudinal speed of the rigid body in the tire's frame. This leads to a divide-by-zero in the event that the longitudinal speed approaches zero. The parameter minActiveLongSlipDenominator sets a minimum denominator for the normalized longitudinal slip when the wheel experiences either a non-zero drive torque or a non-zero brake torque or a non-zero handbrake torque.
Note
Larger timesteps typically require larger values of minActiveLongSlipDenominator to avoid instabilities occurring when the vehicle is aggressively throttled from rest.
It is recommended that minActiveLongSlipDenominator < minPassiveLongSlipDenominator.
Range: (0, inf)
Unit: velocity = length / time
Referenced by transformAndScale().
minLatSlipDenominator
PxReal PxVehicleTireSlipParams::minLatSlipDenominator
The lateral slip angle is typically computed as a function of the ratio of lateral and longitudinal speeds of the rigid body in the tire's frame. This leads to a divide-by-zero in the event that the longitudinal speed approaches zero. The parameter minLatSlipDenominator sets a minimum denominator for the ratio of speeds used to compute the lateral slip angle.
Note
Larger timesteps typically require larger values of minLatSlipDenominator.
Range: (0, inf)
Unit: velocity = length / time
Referenced by transformAndScale().
minPassiveLongSlipDenominator
PxReal PxVehicleTireSlipParams::minPassiveLongSlipDenominator
The longitudinal slip represents the difference between the longitudinal speed of the rigid body in the tire's frame and the linear speed arising from the rotation of the wheel. This is typically normalized using the reciprocal of the longitudinal speed of the rigid body in the tire's frame. This leads to a divide-by-zero in the event that the longitudinal speed approaches zero. The parameter minPassiveLongSlipDenominator sets a minimum denominator for the normalized longitudinal slip when the wheel experiences zero drive torque and zero brake torque and zero handbrake torque. The aim is to bring the vehicle to rest without experiencing wheel rotational speeds that oscillate around zero.
Note
The vehicle will come to rest more smoothly with larger values of minPassiveLongSlipDenominator, particularly with large timesteps that often lead to oscillation in wheel rotation speeds when the wheel rotation speed approaches zero.
It is recommended that minActiveLongSlipDenominator < minPassiveLongSlipDenominator.
Range: (0, inf)
Unit: velocity = length / time
Referenced by transformAndScale().
The documentation for this struct was generated from the following file:
PxVehicleParams.h