PxVehicleAckermannParams Struct Reference
PxVehicleAckermannParams Struct Reference
Vehicle2
A description of a single axle that is to be affected by Ackermann steer correction.
#include <PxVehicleSteeringParams.h>
Public Member Functions
PX_FORCE_INLINE bool isValid (const PxVehicleAxleDescription &axleDesc) const
PX_FORCE_INLINE PxVehicleAckermannParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
Public Attributes
PxU32 wheelIds [2]
wheelIds[0] is the id of the wheel that is negative along the lateral axis, wheelIds[1] is the wheel id that is positive along the lateral axis.
PxReal wheelBase
wheelBase is the longitudinal distance between the axle that is affected by Ackermann correction and a reference axle.
PxReal trackWidth
trackWidth is the width of the axle specified by wheelIds
PxReal strength
is the strength of the correction with 0 denoting no correction and 1 denoting perfect correction.
Detailed Description
A description of a single axle that is to be affected by Ackermann steer correction.
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleAckermannParams::isValid (const PxVehicleAxleDescription & axleDesc) const inline
References PxVehicleAxleDescription::getNbWheels(), PX_CHECK_AND_RETURN_VAL, and PX_UNUSED().
transformAndScale()
PX_FORCE_INLINE PxVehicleAckermannParams PxVehicleAckermannParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PX_UNUSED(), PxVehicleScale::scale, trackWidth, and wheelBase.
Member Data Documentation
strength
PxReal PxVehicleAckermannParams::strength
is the strength of the correction with 0 denoting no correction and 1 denoting perfect correction.
trackWidth
PxReal PxVehicleAckermannParams::trackWidth
trackWidth is the width of the axle specified by wheelIds
Referenced by transformAndScale().
wheelBase
PxReal PxVehicleAckermannParams::wheelBase
wheelBase is the longitudinal distance between the axle that is affected by Ackermann correction and a reference axle.
Referenced by transformAndScale().
wheelIds
PxU32 PxVehicleAckermannParams::wheelIds[2]
wheelIds[0] is the id of the wheel that is negative along the lateral axis, wheelIds[1] is the wheel id that is positive along the lateral axis.
The documentation for this struct was generated from the following file:
PxVehicleSteeringParams.h