PxVehicleRigidBodyState Struct Reference
PxVehicleRigidBodyState Struct Reference
Vehicle2
#include <PxVehicleRigidBodyStates.h>
Public Member Functions
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxReal getVerticalSpeed (const PxVehicleFrame &frame) const
Compute the vertical speed of the rigid body transformed to the world frame.
PX_FORCE_INLINE PxReal getLateralSpeed (const PxVehicleFrame &frame) const
Compute the lateral speed of the rigid body transformed to the world frame.
PX_FORCE_INLINE PxReal getLongitudinalSpeed (const PxVehicleFrame &frame) const
Compute the longitudinal speed of the rigid body transformed to the world frame.
Public Attributes
PxTransform pose
the body's pose (in world space)
PxVec3 linearVelocity
the body's linear velocity (in world space)
PxVec3 angularVelocity
the body's angular velocity (in world space)
PxVec3 previousLinearVelocity
the previous linear velocity of the body (in world space)
PxVec3 previousAngularVelocity
the previous angular velocity of the body (in world space)
PxVec3 externalForce
external force (in world space) affecting the rigid body (usually excluding gravitational force)
PxVec3 externalTorque
external torque (in world space) affecting the rigid body
Member Function Documentation
getLateralSpeed()
PX_FORCE_INLINE PxReal PxVehicleRigidBodyState::getLateralSpeed (const PxVehicleFrame & frame) const inline
Compute the lateral speed of the rigid body transformed to the world frame.
Parameters
[in] frame describes the axes of the vehicle
References PxVec3T< Type >::dot(), PxVehicleFrame::getLatAxis(), PxTransformT< Type >::q, and PxQuatT< Type >::rotate().
getLongitudinalSpeed()
PX_FORCE_INLINE PxReal PxVehicleRigidBodyState::getLongitudinalSpeed (const PxVehicleFrame & frame) const inline
Compute the longitudinal speed of the rigid body transformed to the world frame.
Parameters
[in] frame describes the axes of the vehicle
References PxVec3T< Type >::dot(), PxVehicleFrame::getLngAxis(), PxTransformT< Type >::q, and PxQuatT< Type >::rotate().
Referenced by PxVehicleDirectDriveCommandResponseComponent::update(), and PxVehicleEngineDriveCommandResponseComponent::update().
getVerticalSpeed()
PX_FORCE_INLINE PxReal PxVehicleRigidBodyState::getVerticalSpeed (const PxVehicleFrame & frame) const inline
Compute the vertical speed of the rigid body transformed to the world frame.
Parameters
[in] frame describes the axes of the vehicle
References PxVec3T< Type >::dot(), PxVehicleFrame::getVrtAxis(), PxTransformT< Type >::q, and PxQuatT< Type >::rotate().
setToDefault()
PX_FORCE_INLINE void PxVehicleRigidBodyState::setToDefault () inline
References PxIdentity, and PxZero.
Member Data Documentation
angularVelocity
PxVec3 PxVehicleRigidBodyState::angularVelocity
the body's angular velocity (in world space)
externalForce
PxVec3 PxVehicleRigidBodyState::externalForce
external force (in world space) affecting the rigid body (usually excluding gravitational force)
externalTorque
PxVec3 PxVehicleRigidBodyState::externalTorque
external torque (in world space) affecting the rigid body
linearVelocity
PxVec3 PxVehicleRigidBodyState::linearVelocity
the body's linear velocity (in world space)
pose
PxTransform PxVehicleRigidBodyState::pose
the body's pose (in world space)
Referenced by PxVehicleShiftOrigin().
previousAngularVelocity
PxVec3 PxVehicleRigidBodyState::previousAngularVelocity
the previous angular velocity of the body (in world space)
previousLinearVelocity
PxVec3 PxVehicleRigidBodyState::previousLinearVelocity
the previous linear velocity of the body (in world space)
The documentation for this struct was generated from the following file:
PxVehicleRigidBodyStates.h