Interpolation Struct Reference
Interpolation Struct Reference
Common
#include <PxMathUtils.h>
Static Public Member Functions
PX_INLINE static PX_CUDA_CALLABLE float PxLerp (float a, float b, float t)
PX_INLINE static PX_CUDA_CALLABLE PxReal PxBiLerp (const PxReal f00, const PxReal f10, const PxReal f01, const PxReal f11, const PxReal tx, const PxReal ty)
PX_INLINE static PX_CUDA_CALLABLE PxReal PxTriLerp (const PxReal f000, const PxReal f100, const PxReal f010, const PxReal f110, const PxReal f001, const PxReal f101, const PxReal f011, const PxReal f111, const PxReal tx, const PxReal ty, const PxReal tz)
PX_INLINE static PX_CUDA_CALLABLE PxU32 PxSDFIdx (PxU32 i, PxU32 j, PxU32 k, PxU32 nbX, PxU32 nbY)
PX_INLINE static PX_CUDA_CALLABLE PxReal PxSDFSampleImpl (const PxReal *PX_RESTRICT sdf, const PxVec3 &localPos, const PxVec3 &sdfBoxLower, const PxVec3 &sdfBoxHigher, const PxReal sdfDx, const PxReal invSdfDx, const PxU32 dimX, const PxU32 dimY, const PxU32 dimZ, PxReal tolerance)
Member Function Documentation
PxBiLerp()
PX_INLINE static PX_CUDA_CALLABLE PxReal Interpolation::PxBiLerp (const PxReal f00, const PxReal f10, const PxReal f01, const PxReal f11, const PxReal tx, const PxReal ty) inline static
PxLerp()
PX_INLINE static PX_CUDA_CALLABLE float Interpolation::PxLerp (float a, float b, float t) inline static
PxSDFIdx()
PX_INLINE static PX_CUDA_CALLABLE PxU32 Interpolation::PxSDFIdx (PxU32 i, PxU32 j, PxU32 k, PxU32 nbX, PxU32 nbY) inline static
Referenced by PxSDFSampleImpl().
PxSDFSampleImpl()
PX_INLINE static PX_CUDA_CALLABLE PxReal Interpolation::PxSDFSampleImpl (const PxReal *PX_RESTRICT sdf, const PxVec3 & localPos, const PxVec3 & sdfBoxLower, const PxVec3 & sdfBoxHigher, const PxReal sdfDx, const PxReal invSdfDx, const PxU32 dimX, const PxU32 dimY, const PxU32 dimZ, PxReal tolerance) inline static
References PxVec3T< Type >::magnitude(), PxVec3T< Type >::magnitudeSquared(), PxVec3T< Type >::maximum(), PxVec3T< Type >::minimum(), PX_MAX_F32, PxSDFIdx(), PxVec3T< Type >::x, PxVec3T< Type >::y, and PxVec3T< Type >::z.
Referenced by PxSdfSample().
PxTriLerp()
PX_INLINE static PX_CUDA_CALLABLE PxReal Interpolation::PxTriLerp (const PxReal f000, const PxReal f100, const PxReal f010, const PxReal f110, const PxReal f001, const PxReal f101, const PxReal f011, const PxReal f111, const PxReal tx, const PxReal ty, const PxReal tz) inline static
The documentation for this struct was generated from the following file:
PxMathUtils.h