PxVehicleFourWheelDriveDifferentialLegacyParams Struct Reference
PxVehicleFourWheelDriveDifferentialLegacyParams Struct Reference
Vehicle2
#include <PxVehicleDrivetrainParams.h>
Public Types
enum Enum { eDIFF_TYPE_LS_4WD, eDIFF_TYPE_LS_FRONTWD, eDIFF_TYPE_LS_REARWD, eMAX_NB_DIFF_TYPES }
Public Member Functions
PX_FORCE_INLINE PxVehicleFourWheelDriveDifferentialLegacyParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid (const PxVehicleAxleDescription &axleDesc) const
Public Attributes
PxU32 frontWheelIds [2]
The two front wheels are specified by the array frontWheelIds.
PxU32 rearWheelIds [2]
The two rear wheels are specified by the array rearWheelIds.
PxReal frontRearSplit
Ratio of torque split between front and rear wheels (>0.5 means more front, <0.5 means more to rear).
PxReal frontNegPosSplit
Ratio of torque split between front-negative and front-positive wheels (>0.5 means more to frontWheelIds[0], <0.5 means more to frontWheelIds[1]).
PxReal rearNegPosSplit
Ratio of torque split between rear-negative wheel and rear-positive wheels (>0.5 means more to rearWheelIds[0], <0.5 means more to rearWheelIds[1]).
PxReal centerBias
Maximum allowed ratio of average front wheel rotation speed and rear wheel rotation speeds. The differential will divert more torque to the slower wheels when the bias is exceeded.
PxReal frontBias
Maximum allowed ratio of front-left and front-right wheel rotation speeds. The differential will divert more torque to the slower wheel when the bias is exceeded.
PxReal rearBias
Maximum allowed ratio of rear-left and rear-right wheel rotation speeds. The differential will divert more torque to the slower wheel when the bias is exceeded.
Enum type
Type of differential.
Member Enumeration Documentation
Enum
enum PxVehicleFourWheelDriveDifferentialLegacyParams::Enum
Enumerator
eDIFF_TYPE_LS_4WD
eDIFF_TYPE_LS_FRONTWD
eDIFF_TYPE_LS_REARWD
eMAX_NB_DIFF_TYPES
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleFourWheelDriveDifferentialLegacyParams::isValid (const PxVehicleAxleDescription & axleDesc) const inline
References eMAX_NB_DIFF_TYPES, PxVehicleAxleDescription::getAxle(), PX_CHECK_AND_RETURN_VAL, and PX_UNUSED().
transformAndScale()
PX_FORCE_INLINE PxVehicleFourWheelDriveDifferentialLegacyParams PxVehicleFourWheelDriveDifferentialLegacyParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PX_UNUSED().
Member Data Documentation
centerBias
PxReal PxVehicleFourWheelDriveDifferentialLegacyParams::centerBias
Maximum allowed ratio of average front wheel rotation speed and rear wheel rotation speeds. The differential will divert more torque to the slower wheels when the bias is exceeded.
Note
Only applied to DIFF_TYPE_LS_4WD
Range: [1, inf)
frontBias
PxReal PxVehicleFourWheelDriveDifferentialLegacyParams::frontBias
Maximum allowed ratio of front-left and front-right wheel rotation speeds. The differential will divert more torque to the slower wheel when the bias is exceeded.
Note
Only applied to DIFF_TYPE_LS_4WD and DIFF_TYPE_LS_FRONTWD
Range: [1, inf)
frontNegPosSplit
PxReal PxVehicleFourWheelDriveDifferentialLegacyParams::frontNegPosSplit
Ratio of torque split between front-negative and front-positive wheels (>0.5 means more to frontWheelIds[0], <0.5 means more to frontWheelIds[1]).
Note
Only applied to DIFF_TYPE_LS_4WD and DIFF_TYPE_LS_FRONTWD
Range: [0, 1]
frontRearSplit
PxReal PxVehicleFourWheelDriveDifferentialLegacyParams::frontRearSplit
Ratio of torque split between front and rear wheels (>0.5 means more front, <0.5 means more to rear).
Note
Only applied to DIFF_TYPE_LS_4WD
Range: [0, 1]
frontWheelIds
PxU32 PxVehicleFourWheelDriveDifferentialLegacyParams::frontWheelIds[2]
The two front wheels are specified by the array frontWheelIds.
Note
The states eDIFF_TYPE_LS_4WD, eDIFF_TYPE_LS_FRONTWD require knowledge of the front wheels to allow torque splits between front and rear axles as well as torque splits across the front axle.
frontWheelIds[0] should specify the wheel on the front axle that is negatively placed on the lateral axis.
frontWheelIds[1] should specify the wheel on the front axle that is positively placed on the lateral axis.
If frontNegPosSplit > 0.5, more torque will be delivered to the wheel specified by frontWheelIds[0] than to the wheel specified by frontWheelIds[1]. The converse is true if frontNegPosSplit < 0.5.
rearBias
PxReal PxVehicleFourWheelDriveDifferentialLegacyParams::rearBias
Maximum allowed ratio of rear-left and rear-right wheel rotation speeds. The differential will divert more torque to the slower wheel when the bias is exceeded.
Note
Only applied to DIFF_TYPE_LS_4WD and DIFF_TYPE_LS_REARWD
Range: [1, inf)
rearNegPosSplit
PxReal PxVehicleFourWheelDriveDifferentialLegacyParams::rearNegPosSplit
Ratio of torque split between rear-negative wheel and rear-positive wheels (>0.5 means more to rearWheelIds[0], <0.5 means more to rearWheelIds[1]).
Note
Only applied to DIFF_TYPE_LS_4WD and eDIFF_TYPE_LS_REARWD
Range: [0, 1]
rearWheelIds
PxU32 PxVehicleFourWheelDriveDifferentialLegacyParams::rearWheelIds[2]
The two rear wheels are specified by the array rearWheelIds.
Note
The states eDIFF_TYPE_LS_4WD, eDIFF_TYPE_LS_REARWD require knowledge of the rear wheels to allow torque splits between front and rear axles as well as torque splits across the rear axle.
rearWheelIds[0] should specify the wheel on the rear axle that is negatively placed on the lateral axis.
rearWheelIds[1] should specify the wheel on the rear axle that is positively placed on the lateral axis.
If rearNegPosSplit > 0.5, more torque will be delivered to the wheel specified by rearWheelIds[0] than to the wheel specified by rearWheelIds[1]. The converse is true if rearNegPosSplit < 0.5.
type
Enum PxVehicleFourWheelDriveDifferentialLegacyParams::type
Type of differential.
Range: [DIFF_TYPE_LS_4WD, eDIFF_TYPE_LS_REARWD]
The documentation for this struct was generated from the following file:
PxVehicleDrivetrainParams.h