PxVehicleSimulationContext Struct Reference
PxVehicleSimulationContext Struct Reference
Vehicle2
#include <PxVehicleParams.h>
Public Member Functions
PxVehicleSimulationContext ()
PX_FORCE_INLINE PxVehicleSimulationContextType::Enum getType () const
PX_FORCE_INLINE void setToDefault ()
PX_FORCE_INLINE PxVehicleSimulationContext transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
Public Attributes
PxVec3 gravity
PxVehicleFrame frame
PxVehicleScale scale
PxVehicleTireSlipParams tireSlipParams
PxVehicleTireStickyParams tireStickyParams
PxReal thresholdForwardSpeedForWheelAngleIntegration
Forward wheel speed below which the wheel rotation speed gets blended with the rolling speed.
const struct PxVehiclePvdAttributeHandles * attributeHandles
The attribute handles used to reflect vehicle parameter and state data in omnipvd.
OmniPvdWriter * omniWriter
An instance of OmniPvdWriter used to write vehicle prameter and state data to omnipvd.
Protected Attributes
PxVehicleSimulationContextType::Enum type
Constructor & Destructor Documentation
PxVehicleSimulationContext()
PxVehicleSimulationContext::PxVehicleSimulationContext () inline
Member Function Documentation
getType()
PX_FORCE_INLINE PxVehicleSimulationContextType::Enum PxVehicleSimulationContext::getType () const inline
Referenced by PxVehiclePhysXRoadGeometrySceneQueryComponent::update(), and PxVehiclePhysXActorEndComponent::update().
setToDefault()
PX_FORCE_INLINE void PxVehicleSimulationContext::setToDefault () inline
References PxVehicleFrame::getVrtAxis(), PxVehicleScale::scale, PxVehicleFrame::setToDefault(), PxVehicleScale::setToDefault(), PxVehicleTireSlipParams::setToDefault(), and PxVehicleTireStickyParams::setToDefault().
Referenced by PxVehiclePhysXSimulationContext::setToDefault().
transformAndScale()
PX_FORCE_INLINE PxVehicleSimulationContext PxVehicleSimulationContext::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References frame, PxVehicleFrame::getFrame(), PxMat33T< Type >::getTranspose(), gravity, PxVehicleScale::scale, scale, thresholdForwardSpeedForWheelAngleIntegration, tireSlipParams, tireStickyParams, PxVehicleTireSlipParams::transformAndScale(), and PxVehicleTireStickyParams::transformAndScale().
Referenced by PxVehiclePhysXSimulationContext::transformAndScale().
Member Data Documentation
attributeHandles
const struct PxVehiclePvdAttributeHandles* PxVehicleSimulationContext::attributeHandles
The attribute handles used to reflect vehicle parameter and state data in omnipvd.
Note
A null value will result in no values being reflected in omnipvd.
attributeHandles and omniWriter both need to be non-NULL to reflect vehicle values in omnipvd.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdAttributesRelease
PxVehiclePVDComponent
Referenced by PxVehiclePVDComponent::update().
frame
PxVehicleFrame PxVehicleSimulationContext::frame
Referenced by transformAndScale(), PxVehicleWheelComponent::update(), PxVehicleTireComponent::update(), PxVehiclePhysXRoadGeometrySceneQueryComponent::update(), PxVehicleDirectDriveCommandResponseComponent::update(), PxVehicleSuspensionComponent::update(), PxVehicleLegacyTireComponent::update(), PxVehicleLegacySuspensionComponent::update(), and PxVehicleEngineDriveCommandResponseComponent::update().
gravity
PxVec3 PxVehicleSimulationContext::gravity
Referenced by transformAndScale(), PxVehicleRigidBodyComponent::update(), PxVehicleSuspensionComponent::update(), and PxVehicleLegacySuspensionComponent::update().
omniWriter
OmniPvdWriter* PxVehicleSimulationContext::omniWriter
An instance of OmniPvdWriter used to write vehicle prameter and state data to omnipvd.
Note
A null value will result in no values being reflected in omnipvd.
attributeHandles and omniWriter both need to be non-NULL to reflect vehicle values in omnipvd.
See also
PxVehiclePvdAttributesCreate
PxVehiclePvdAttributesRelease
PxVehiclePVDComponent
Referenced by PxVehiclePVDComponent::update().
scale
PxVehicleScale PxVehicleSimulationContext::scale
Referenced by transformAndScale().
thresholdForwardSpeedForWheelAngleIntegration
PxReal PxVehicleSimulationContext::thresholdForwardSpeedForWheelAngleIntegration
Forward wheel speed below which the wheel rotation speed gets blended with the rolling speed.
The blended rotation speed is used to integrate the wheel rotation angle. At low forward wheel speed, the wheel rotation speed can get unstable (depending on the tire model used) and, for example, oscillate.
Note
If brake or throttle is applied, there will be no blending.
Unit: velocity = length / time
Referenced by transformAndScale(), and PxVehicleWheelComponent::update().
tireSlipParams
PxVehicleTireSlipParams PxVehicleSimulationContext::tireSlipParams
Referenced by transformAndScale(), PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
tireStickyParams
PxVehicleTireStickyParams PxVehicleSimulationContext::tireStickyParams
Referenced by transformAndScale(), PxVehiclePhysXConstraintComponent::update(), PxVehicleTireComponent::update(), and PxVehicleLegacyTireComponent::update().
type
PxVehicleSimulationContextType::Enum PxVehicleSimulationContext::type protected
The documentation for this struct was generated from the following file:
PxVehicleParams.h