PxVehicleSteerCommandResponseParams Struct Reference
PxVehicleSteerCommandResponseParams Struct Reference
Vehicle2
Distribute a steer response to the wheels of a vehicle.
#include <PxVehicleSteeringParams.h>
Public Member Functions
PX_FORCE_INLINE PxVehicleSteerCommandResponseParams transformAndScale (const PxVehicleFrame &srcFrame, const PxVehicleFrame &trgFrame, const PxVehicleScale &srcScale, const PxVehicleScale &trgScale) const
PX_FORCE_INLINE bool isValid (const PxVehicleAxleDescription &axleDesc) const
Additional Inherited Members
Public Attributes inherited from PxVehicleCommandResponseParams
PxVehicleCommandNonLinearResponseParams nonlinearResponse
A nonlinear response to command value expressed as a lookup table of normalized response as a function of command value and longitudinal speed.
PxReal wheelResponseMultipliers [PxVehicleLimits::eMAX_NB_WHEELS]
A description of the per wheel response multiplier to an input command.
PxF32 maxResponse
The maximum response that occurs when the wheel response multiplier has value 1.0 and nonlinearResponse is in the default state of linear response.
Detailed Description
Distribute a steer response to the wheels of a vehicle.
Note
The steer angle applied to each wheel on the ith wheel is steerCommand * maxResponse * wheelResponseMultipliers[i].
A typical use case is to set maxResponse to be the vehicle's maximum achievable steer angle that occurs when the steer command is equal to 1.0. The array wheelResponseMultipliers[i] would then be used to specify the maximum achievable steer angle per wheel as a fractional multiplier of the vehicle's maximum achievable steer angle.
Member Function Documentation
isValid()
PX_FORCE_INLINE bool PxVehicleSteerCommandResponseParams::isValid (const PxVehicleAxleDescription & axleDesc) const inline
References PxVehicleAxleDescription::isValid(), PxVehicleAxleDescription::nbWheels, PX_CHECK_AND_RETURN_VAL, PxAbs(), PxPi, and PxVehicleAxleDescription::wheelIdsInAxleOrder.
transformAndScale()
PX_FORCE_INLINE PxVehicleSteerCommandResponseParams PxVehicleSteerCommandResponseParams::transformAndScale (const PxVehicleFrame & srcFrame, const PxVehicleFrame & trgFrame, const PxVehicleScale & srcScale, const PxVehicleScale & trgScale) const inline
References PX_UNUSED().
The documentation for this struct was generated from the following file:
PxVehicleSteeringParams.h