PxVehicleArrayData< T > Struct Template Reference
PxVehicleArrayData< T > Struct Template Reference
Vehicle2
Helper struct to pass array type data to vehice components and functions.
#include <PxVehicleParams.h>
Public Types
enum DataFormat { eARRAY_OF_STRUCTS = 0, eARRAY_OF_POINTERS }
Public Member Functions
PX_FORCE_INLINE void setData (T *data)
Set the data as an array of structs.
PX_FORCE_INLINE void setData (T *const *data)
Set the data as an array of pointers.
PX_FORCE_INLINE PxVehicleArrayData ()
PX_FORCE_INLINE PxVehicleArrayData (T *data)
PX_FORCE_INLINE PxVehicleArrayData (T *const *data)
PX_FORCE_INLINE T & getData (PxU32 index)
Get the data entry at a given index.
PX_FORCE_INLINE T & operator[] (PxU32 index)
PX_FORCE_INLINE const T & getData (PxU32 index) const
Get the data entry at a given index.
PX_FORCE_INLINE const T & operator[] (PxU32 index) const
PX_FORCE_INLINE void setEmpty ()
Set as empty.
PX_FORCE_INLINE bool isEmpty () const
Check if declared as empty.
PX_FORCE_INLINE const PxVehicleArrayData< const T > & getConst () const
Get a reference to the array but read only.
Public Attributes
union {
T * arrayOfStructs
T *const * arrayOfPointers
};
PxU8 dataFormat
Detailed Description
template<typename T>
struct PxVehicleArrayData< T >
Helper struct to pass array type data to vehice components and functions.
The Vehicle SDK tries to give the user a certain freedom in how the parameters and states are stored. This helper struct presents a way to either use array of structs or array of pointers to structs to pass data into the provided vehicle components and functions.
Member Enumeration Documentation
DataFormat
template<typename T> enum PxVehicleArrayData::DataFormat
Enumerator
eARRAY_OF_STRUCTS
The data is provided as an array of structs and stored in arrayOfStructs.
eARRAY_OF_POINTERS
The data is provided as an array of pointers and stored in arrayOfPointers.
Constructor & Destructor Documentation
PxVehicleArrayData() [1/3]
template<typename T> PX_FORCE_INLINE PxVehicleArrayData< T >::PxVehicleArrayData () inline
PxVehicleArrayData() [2/3]
template<typename T> PX_FORCE_INLINE PxVehicleArrayData< T >::PxVehicleArrayData (T * data) inline explicit
PxVehicleArrayData() [3/3]
template<typename T> PX_FORCE_INLINE PxVehicleArrayData< T >::PxVehicleArrayData (T *const * data) inline explicit
Member Function Documentation
getConst()
template<typename T> PX_FORCE_INLINE const PxVehicleArrayData<const T>& PxVehicleArrayData< T >::getConst () const inline
Get a reference to the array but read only.
Returns
Read only version of the data.
Referenced by PxVehicleSuspensionComponent::update(), and PxVehicleLegacySuspensionComponent::update().
getData() [1/2]
template<typename T> PX_FORCE_INLINE T& PxVehicleArrayData< T >::getData (PxU32 index) inline
Get the data entry at a given index.
Parameters
[in] index The index to retrieve the data entry for.
Returns
Reference to the requested data entry.
getData() [2/2]
template<typename T> PX_FORCE_INLINE const T& PxVehicleArrayData< T >::getData (PxU32 index) const inline
Get the data entry at a given index.
Parameters
[in] index The index to retrieve the data entry for.
Returns
Reference to the requested data entry.
isEmpty()
template<typename T> PX_FORCE_INLINE bool PxVehicleArrayData< T >::isEmpty () const inline
Check if declared as empty.
Returns
True if empty, else false.
Referenced by PxVehiclePhysXRoadGeometrySceneQueryComponent::update().
operator[]() [1/2]
template<typename T> PX_FORCE_INLINE T& PxVehicleArrayData< T >::operator[] (PxU32 index) inline
operator[]() [2/2]
template<typename T> PX_FORCE_INLINE const T& PxVehicleArrayData< T >::operator[] (PxU32 index) const inline
setData() [1/2]
template<typename T> PX_FORCE_INLINE void PxVehicleArrayData< T >::setData (T * data) inline
Set the data as an array of structs.
Parameters
[in] data The data as an array of structs.
Referenced by PxVehicleSizedArrayData< T >::setDataAndCount().
setData() [2/2]
template<typename T> PX_FORCE_INLINE void PxVehicleArrayData< T >::setData (T *const * data) inline
Set the data as an array of pointers.
Parameters
[in] data The data as an array of pointers.
setEmpty()
template<typename T> PX_FORCE_INLINE void PxVehicleArrayData< T >::setEmpty () inline
Set as empty.
Referenced by PxVehicleSizedArrayData< T >::setEmpty().
Member Data Documentation
@21
union { ... }
arrayOfPointers
template<typename T> T* const* PxVehicleArrayData< T >::arrayOfPointers
arrayOfStructs
template<typename T> T* PxVehicleArrayData< T >::arrayOfStructs
dataFormat
template<typename T> PxU8 PxVehicleArrayData< T >::dataFormat
The documentation for this struct was generated from the following file:
PxVehicleParams.h