// Copyright (c) 2001-2004 NovodeX AG. All rights reserved.
// Copyright (c) 2004-2008 AGEIA Technologies, Inc. All rights reserved.
// SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0


#undef OMNI_PVD_CLASS_BEGIN
#undef OMNI_PVD_CLASS_DERIVED_BEGIN
#undef OMNI_PVD_CLASS_UNTYPED_BEGIN
#undef OMNI_PVD_CLASS_UNTYPED_DERIVED_BEGIN
#undef OMNI_PVD_CLASS_END
#undef OMNI_PVD_ENUM_BEGIN
#undef OMNI_PVD_ENUM_END
#undef OMNI_PVD_ATTRIBUTE
#undef OMNI_PVD_ATTRIBUTE_ARRAY_FIXED_SIZE
#undef OMNI_PVD_ATTRIBUTE_ARRAY_VARIABLE_SIZE
#undef OMNI_PVD_ATTRIBUTE_STRING
#undef OMNI_PVD_ATTRIBUTE_UNIQUE_LIST
#undef OMNI_PVD_ATTRIBUTE_FLAG
#undef OMNI_PVD_ENUM_VALUE_EXPLICIT
#undef OMNI_PVD_ENUM_VALUE
