## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build SnippetRender
#

IF(CMAKE_CXX_PLATFORM_ID STREQUAL "Linux")
	# Cross compiling from linux
	FIND_PACKAGE(OpenGL REQUIRED) # Pull in OpenGL from system libraries
	FIND_PACKAGE(GLUT REQUIRED) # Pull in GLUT from system libraries
ELSEIF(NOT FREEGLUT_PATH)
	SET(FREEGLUT_PATH $ENV{PM_freeglut_PATH} CACHE INTERNAL "Freeglut package path")
ENDIF()

SET(SNIPPETRENDER_COMPILE_DEFS
	# Common to all configurations

	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;GLUT_NO_LIB_PRAGMA;${PHYSX_LIBTYPE_DEFS};${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(CMAKE_CXX_PLATFORM_ID STREQUAL "Linux")
	# Cross compiling from linux
	SET(SNIPPETRENDER_PLATFORM_LINKED_LIBS OpenGL::GL OpenGL::GLU GLUT::GLUT)
ELSE()
	SET(SNIPPETRENDER_PLATFORM_FILES ${FREEGLUT_PATH}/include/GL/freeglut.h)

	# Include OpenGL
	SET(SNIPPETRENDER_PLATFORM_INCLUDES ${FREEGLUT_PATH}/include)
	SET(SNIPPETRENDER_PLATFORM_LINKED_LIBS opengl32.lib glu32.lib)
ENDIF()

IF(PX_GENERATE_GPU_PROJECTS OR PX_GENERATE_GPU_PROJECTS_ONLY)
	LIST(APPEND SNIPPETRENDER_PLATFORM_INCLUDES ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
	LIST(APPEND SNIPPETRENDER_PLATFORM_LINKED_LIBS CUDA::cuda_driver)
ENDIF()

