# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

include_guard(GLOBAL)

# Append a set() command using a bracket delimiter that cannot collide with the
# value. This preserves CMake list separators, spaces, commas, backslashes, and
# quotes without putting toolchain data on a nested command line.
function(_ovphysx_append_source_link_context_value output_file name value)
    set(_equals "")
    while(TRUE)
        set(_closing_bracket "]${_equals}]")
        # Check the value plus the intended closing delimiter so a delimiter
        # cannot begin in the value's suffix and finish at the boundary.
        string(LENGTH "${value}" _value_length)
        string(FIND "${value}${_closing_bracket}" "${_closing_bracket}" _closing_bracket_position)
        if(_closing_bracket_position EQUAL _value_length)
            break()
        endif()
        string(APPEND _equals "=")
    endwhile()

    file(APPEND "${output_file}" "set(${name} [${_equals}[${value}]${_equals}])\n")
endfunction()

function(_ovphysx_resolve_source_link_tool_path output_variable input_path description)
    if(input_path STREQUAL "" OR IS_ABSOLUTE "${input_path}")
        set(${output_variable} "${input_path}" PARENT_SCOPE)
        return()
    endif()

    get_filename_component(_input_directory "${input_path}" DIRECTORY)
    if(_input_directory STREQUAL "")
        find_program(_resolved_tool_path NAMES "${input_path}")
        if(NOT _resolved_tool_path)
            message(FATAL_ERROR
                "Cannot reproduce source-link toolchain: ${description} '${input_path}' "
                "could not be resolved to an absolute path")
        endif()
    elseif(EXISTS "${CMAKE_BINARY_DIR}/${input_path}")
        get_filename_component(_resolved_tool_path "${input_path}" ABSOLUTE
            BASE_DIR "${CMAKE_BINARY_DIR}")
    elseif(EXISTS "${CMAKE_SOURCE_DIR}/${input_path}")
        get_filename_component(_resolved_tool_path "${input_path}" ABSOLUTE
            BASE_DIR "${CMAKE_SOURCE_DIR}")
    else()
        get_filename_component(_resolved_tool_path "${input_path}" ABSOLUTE
            BASE_DIR "${CMAKE_BINARY_DIR}")
    endif()

    set(${output_variable} "${_resolved_tool_path}" PARENT_SCOPE)
    unset(_resolved_tool_path CACHE)
endfunction()

function(_ovphysx_resolve_source_link_file_path output_variable input_path)
    if(input_path STREQUAL "" OR IS_ABSOLUTE "${input_path}")
        set(${output_variable} "${input_path}" PARENT_SCOPE)
    elseif(EXISTS "${CMAKE_BINARY_DIR}/${input_path}")
        get_filename_component(_resolved_file_path "${input_path}" ABSOLUTE
            BASE_DIR "${CMAKE_BINARY_DIR}")
        set(${output_variable} "${_resolved_file_path}" PARENT_SCOPE)
    else()
        get_filename_component(_resolved_file_path "${input_path}" ABSOLUTE
            BASE_DIR "${CMAKE_SOURCE_DIR}")
        set(${output_variable} "${_resolved_file_path}" PARENT_SCOPE)
    endif()
endfunction()

# Serialize the effective outer configure context used by the nested
# add_subdirectory source-link test. The generated file is build-tree state;
# only an allowlist of compiler/generator and Packman toolchain environment
# values is captured, never arbitrary environment variables or credentials.
function(ovphysx_write_source_link_context output_file)
    _ovphysx_resolve_source_link_tool_path(
        _make_program "${CMAKE_MAKE_PROGRAM}" "CMAKE_MAKE_PROGRAM")
    _ovphysx_resolve_source_link_tool_path(
        _c_compiler "${CMAKE_C_COMPILER}" "CMAKE_C_COMPILER")
    _ovphysx_resolve_source_link_tool_path(
        _cxx_compiler "${CMAKE_CXX_COMPILER}" "CMAKE_CXX_COMPILER")
    _ovphysx_resolve_source_link_tool_path(
        _cuda_compiler "${CMAKE_CUDA_COMPILER}" "CMAKE_CUDA_COMPILER")
    _ovphysx_resolve_source_link_tool_path(
        _cuda_host_compiler "${CMAKE_CUDA_HOST_COMPILER}" "CMAKE_CUDA_HOST_COMPILER")
    _ovphysx_resolve_source_link_file_path(
        _toolchain_file "${CMAKE_TOOLCHAIN_FILE}")

    get_filename_component(_output_directory "${output_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_directory}")
    file(WRITE "${output_file}"
        "# Generated by ovphysx_write_source_link_context(). Do not edit.\n")

    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_GENERATOR "${CMAKE_GENERATOR}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_GENERATOR_PLATFORM "${CMAKE_GENERATOR_PLATFORM}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_GENERATOR_TOOLSET "${CMAKE_GENERATOR_TOOLSET}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_GENERATOR_INSTANCE "${CMAKE_GENERATOR_INSTANCE}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_MAKE_PROGRAM "${_make_program}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_C_COMPILER "${_c_compiler}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CXX_COMPILER "${_cxx_compiler}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_TOOLCHAIN_FILE "${_toolchain_file}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_SYSTEM_VERSION "${CMAKE_SYSTEM_VERSION}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_SYSROOT "${CMAKE_SYSROOT}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_C_COMPILER_TARGET "${CMAKE_C_COMPILER_TARGET}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CXX_COMPILER_TARGET "${CMAKE_CXX_COMPILER_TARGET}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_C_COMPILER_EXTERNAL_TOOLCHAIN "${CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CXX_COMPILER_EXTERNAL_TOOLCHAIN "${CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN}")

    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_COMPILER "${_cuda_compiler}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_HOST_COMPILER "${_cuda_host_compiler}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_ARCHITECTURES "${CMAKE_CUDA_ARCHITECTURES}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_FLAGS "${CMAKE_CUDA_FLAGS}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_FLAGS_DEBUG "${CMAKE_CUDA_FLAGS_DEBUG}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_FLAGS_RELEASE "${CMAKE_CUDA_FLAGS_RELEASE}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_FLAGS_RELWITHDEBINFO "${CMAKE_CUDA_FLAGS_RELWITHDEBINFO}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_FLAGS_MINSIZEREL "${CMAKE_CUDA_FLAGS_MINSIZEREL}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDA_FLAGS_CHECKED "${CMAKE_CUDA_FLAGS_CHECKED}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDATOOLKIT_ROOT "${CUDAToolkit_ROOT}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_CUDATOOLKIT_ROOT_DIR "${CUDAToolkit_ROOT_DIR}")

    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_SDK_INCLUDE_DIRECTORIES "${CMAKE_VS_SDK_INCLUDE_DIRECTORIES}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_SDK_LIBRARY_DIRECTORIES "${CMAKE_VS_SDK_LIBRARY_DIRECTORIES}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_PLATFORM_TOOLSET_VERSION "${CMAKE_VS_PLATFORM_TOOLSET_VERSION}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_PLATFORM_TOOLSET_CUDA "${CMAKE_VS_PLATFORM_TOOLSET_CUDA}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_PLATFORM_TOOLSET_CUDA_CUSTOM_DIR "${CMAKE_VS_PLATFORM_TOOLSET_CUDA_CUSTOM_DIR}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_WINDOWS_TARGET_PLATFORM_VERSION "${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM "${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM}")

    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_PATH "$ENV{PATH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_INCLUDE "$ENV{INCLUDE}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_LIB "$ENV{LIB}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_LIBPATH "$ENV{LIBPATH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VCINSTALLDIR "$ENV{VCINSTALLDIR}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VCTOOLSINSTALLDIR "$ENV{VCToolsInstallDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VCTOOLSVERSION "$ENV{VCToolsVersion}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VSINSTALLDIR "$ENV{VSINSTALLDIR}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_DEVENVDIR "$ENV{DevEnvDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_WINDOWSSDKDIR "$ENV{WindowsSdkDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_WINDOWSSDKVERSION "$ENV{WindowsSDKVersion}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_UNIVERSALCRTSDKDIR "$ENV{UniversalCRTSdkDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_UCRTVERSION "$ENV{UCRTVersion}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_FRAMEWORKDIR "$ENV{FrameworkDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_FRAMEWORKVERSION "$ENV{FrameworkVersion}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_FRAMEWORKDIR32 "$ENV{FrameworkDir32}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_FRAMEWORKVERSION32 "$ENV{FrameworkVersion32}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_NETFXSDKDIR "$ENV{NETFXSDKDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_EXTENSIONSDKDIR "$ENV{ExtensionSdkDir}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VSCMD_ARG_TGT_ARCH "$ENV{VSCMD_ARG_TGT_ARCH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VSCMD_ARG_HOST_ARCH "$ENV{VSCMD_ARG_HOST_ARCH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VSCMD_VER "$ENV{VSCMD_VER}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_VSCMD_PREINIT_PATH "$ENV{__VSCMD_PREINIT_PATH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_CUDA_PATH "$ENV{CUDA_PATH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_NVTOOLSEXT_PATH "$ENV{NVTOOLSEXT_PATH}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_PM_PACKAGES_ROOT "$ENV{PM_PACKAGES_ROOT}")
    _ovphysx_append_source_link_context_value("${output_file}" SOURCE_LINK_CONTEXT_ENV_PM_SECURELOADLIBRARY_PATH "$ENV{PM_SECURELOADLIBRARY_PATH}")
endfunction()

function(_ovphysx_restore_source_link_environment_variable environment_name context_variable)
    # An empty capture means the variable was not set when the context was
    # written (for example a generator-triggered re-configure from a shell
    # without the Packman environment). Applying it would clear a live
    # value in the invoking shell, so skip empty captures instead of
    # restoring them.
    if(DEFINED ${context_variable} AND NOT "${${context_variable}}" STREQUAL "")
        set(ENV{${environment_name}} "${${context_variable}}")
    endif()
endfunction()

# Restore the Packman compiler environment before any helper calls find_program
# and before the nested configure/build processes are launched.
function(ovphysx_apply_source_link_environment)
    _ovphysx_restore_source_link_environment_variable(PATH SOURCE_LINK_CONTEXT_ENV_PATH)
    _ovphysx_restore_source_link_environment_variable(INCLUDE SOURCE_LINK_CONTEXT_ENV_INCLUDE)
    _ovphysx_restore_source_link_environment_variable(LIB SOURCE_LINK_CONTEXT_ENV_LIB)
    _ovphysx_restore_source_link_environment_variable(LIBPATH SOURCE_LINK_CONTEXT_ENV_LIBPATH)
    _ovphysx_restore_source_link_environment_variable(VCINSTALLDIR SOURCE_LINK_CONTEXT_ENV_VCINSTALLDIR)
    _ovphysx_restore_source_link_environment_variable(VCToolsInstallDir SOURCE_LINK_CONTEXT_ENV_VCTOOLSINSTALLDIR)
    _ovphysx_restore_source_link_environment_variable(VCToolsVersion SOURCE_LINK_CONTEXT_ENV_VCTOOLSVERSION)
    _ovphysx_restore_source_link_environment_variable(VSINSTALLDIR SOURCE_LINK_CONTEXT_ENV_VSINSTALLDIR)
    _ovphysx_restore_source_link_environment_variable(DevEnvDir SOURCE_LINK_CONTEXT_ENV_DEVENVDIR)
    _ovphysx_restore_source_link_environment_variable(WindowsSdkDir SOURCE_LINK_CONTEXT_ENV_WINDOWSSDKDIR)
    _ovphysx_restore_source_link_environment_variable(WindowsSDKVersion SOURCE_LINK_CONTEXT_ENV_WINDOWSSDKVERSION)
    _ovphysx_restore_source_link_environment_variable(UniversalCRTSdkDir SOURCE_LINK_CONTEXT_ENV_UNIVERSALCRTSDKDIR)
    _ovphysx_restore_source_link_environment_variable(UCRTVersion SOURCE_LINK_CONTEXT_ENV_UCRTVERSION)
    _ovphysx_restore_source_link_environment_variable(FrameworkDir SOURCE_LINK_CONTEXT_ENV_FRAMEWORKDIR)
    _ovphysx_restore_source_link_environment_variable(FrameworkVersion SOURCE_LINK_CONTEXT_ENV_FRAMEWORKVERSION)
    _ovphysx_restore_source_link_environment_variable(FrameworkDir32 SOURCE_LINK_CONTEXT_ENV_FRAMEWORKDIR32)
    _ovphysx_restore_source_link_environment_variable(FrameworkVersion32 SOURCE_LINK_CONTEXT_ENV_FRAMEWORKVERSION32)
    _ovphysx_restore_source_link_environment_variable(NETFXSDKDir SOURCE_LINK_CONTEXT_ENV_NETFXSDKDIR)
    _ovphysx_restore_source_link_environment_variable(ExtensionSdkDir SOURCE_LINK_CONTEXT_ENV_EXTENSIONSDKDIR)
    _ovphysx_restore_source_link_environment_variable(VSCMD_ARG_TGT_ARCH SOURCE_LINK_CONTEXT_ENV_VSCMD_ARG_TGT_ARCH)
    _ovphysx_restore_source_link_environment_variable(VSCMD_ARG_HOST_ARCH SOURCE_LINK_CONTEXT_ENV_VSCMD_ARG_HOST_ARCH)
    _ovphysx_restore_source_link_environment_variable(VSCMD_VER SOURCE_LINK_CONTEXT_ENV_VSCMD_VER)
    _ovphysx_restore_source_link_environment_variable(__VSCMD_PREINIT_PATH SOURCE_LINK_CONTEXT_ENV_VSCMD_PREINIT_PATH)
    _ovphysx_restore_source_link_environment_variable(CUDA_PATH SOURCE_LINK_CONTEXT_ENV_CUDA_PATH)
    _ovphysx_restore_source_link_environment_variable(NVTOOLSEXT_PATH SOURCE_LINK_CONTEXT_ENV_NVTOOLSEXT_PATH)
    _ovphysx_restore_source_link_environment_variable(PM_PACKAGES_ROOT SOURCE_LINK_CONTEXT_ENV_PM_PACKAGES_ROOT)
    _ovphysx_restore_source_link_environment_variable(PM_SECURELOADLIBRARY_PATH SOURCE_LINK_CONTEXT_ENV_PM_SECURELOADLIBRARY_PATH)
endfunction()

function(_ovphysx_get_source_link_value output_variable explicit_variable context_variable)
    if(DEFINED ${explicit_variable} AND NOT "${${explicit_variable}}" STREQUAL "")
        set(${output_variable} "${${explicit_variable}}" PARENT_SCOPE)
    elseif(DEFINED ${context_variable} AND NOT "${${context_variable}}" STREQUAL "")
        set(${output_variable} "${${context_variable}}" PARENT_SCOPE)
    else()
        set(${output_variable} "" PARENT_SCOPE)
    endif()
endfunction()

function(_ovphysx_append_source_link_cache_value output_file name type value)
    set(_equals "")
    while(TRUE)
        set(_closing_bracket "]${_equals}]")
        string(LENGTH "${value}" _value_length)
        string(FIND "${value}${_closing_bracket}" "${_closing_bracket}" _closing_bracket_position)
        if(_closing_bracket_position EQUAL _value_length)
            break()
        endif()
        string(APPEND _equals "=")
    endwhile()

    file(APPEND "${output_file}"
        "set(${name} [${_equals}[${value}]${_equals}] CACHE ${type} \"\" FORCE)\n")
endfunction()

function(ovphysx_write_source_link_initial_cache output_file)
    get_filename_component(_output_directory "${output_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_directory}")
    file(WRITE "${output_file}"
        "# Generated source-link initial cache. Do not edit.\n")

    _ovphysx_get_source_link_value(_make_program CMAKE_MAKE_PROGRAM SOURCE_LINK_CONTEXT_MAKE_PROGRAM)
    _ovphysx_get_source_link_value(_c_compiler CMAKE_C_COMPILER SOURCE_LINK_CONTEXT_C_COMPILER)
    _ovphysx_get_source_link_value(_cxx_compiler CMAKE_CXX_COMPILER SOURCE_LINK_CONTEXT_CXX_COMPILER)
    _ovphysx_get_source_link_value(_toolchain_file CMAKE_TOOLCHAIN_FILE SOURCE_LINK_CONTEXT_TOOLCHAIN_FILE)
    _ovphysx_get_source_link_value(_cuda_compiler CMAKE_CUDA_COMPILER SOURCE_LINK_CONTEXT_CUDA_COMPILER)
    _ovphysx_get_source_link_value(_cuda_host_compiler CMAKE_CUDA_HOST_COMPILER SOURCE_LINK_CONTEXT_CUDA_HOST_COMPILER)

    _ovphysx_resolve_source_link_tool_path(
        _make_program "${_make_program}" "CMAKE_MAKE_PROGRAM")
    _ovphysx_resolve_source_link_tool_path(
        _c_compiler "${_c_compiler}" "CMAKE_C_COMPILER")
    _ovphysx_resolve_source_link_tool_path(
        _cxx_compiler "${_cxx_compiler}" "CMAKE_CXX_COMPILER")
    _ovphysx_resolve_source_link_tool_path(
        _cuda_compiler "${_cuda_compiler}" "CMAKE_CUDA_COMPILER")
    _ovphysx_resolve_source_link_tool_path(
        _cuda_host_compiler "${_cuda_host_compiler}" "CMAKE_CUDA_HOST_COMPILER")
    _ovphysx_resolve_source_link_file_path(
        _toolchain_file "${_toolchain_file}")

    if(NOT _make_program STREQUAL "")
        _ovphysx_append_source_link_cache_value("${output_file}" CMAKE_MAKE_PROGRAM FILEPATH "${_make_program}")
    endif()
    if(NOT _c_compiler STREQUAL "")
        _ovphysx_append_source_link_cache_value("${output_file}" CMAKE_C_COMPILER FILEPATH "${_c_compiler}")
    endif()
    if(NOT _cxx_compiler STREQUAL "")
        _ovphysx_append_source_link_cache_value("${output_file}" CMAKE_CXX_COMPILER FILEPATH "${_cxx_compiler}")
    endif()
    if(NOT _toolchain_file STREQUAL "")
        _ovphysx_append_source_link_cache_value("${output_file}" CMAKE_TOOLCHAIN_FILE FILEPATH "${_toolchain_file}")
    endif()
    if(NOT _cuda_compiler STREQUAL "")
        _ovphysx_append_source_link_cache_value("${output_file}" CMAKE_CUDA_COMPILER FILEPATH "${_cuda_compiler}")
    endif()
    if(NOT _cuda_host_compiler STREQUAL "")
        _ovphysx_append_source_link_cache_value("${output_file}" CMAKE_CUDA_HOST_COMPILER FILEPATH "${_cuda_host_compiler}")
    endif()

    set(_source_link_cache_mappings
        "CMAKE_SYSTEM_VERSION|SOURCE_LINK_CONTEXT_SYSTEM_VERSION|STRING"
        "CMAKE_SYSROOT|SOURCE_LINK_CONTEXT_SYSROOT|PATH"
        "CMAKE_C_COMPILER_TARGET|SOURCE_LINK_CONTEXT_C_COMPILER_TARGET|STRING"
        "CMAKE_CXX_COMPILER_TARGET|SOURCE_LINK_CONTEXT_CXX_COMPILER_TARGET|STRING"
        "CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN|SOURCE_LINK_CONTEXT_C_COMPILER_EXTERNAL_TOOLCHAIN|PATH"
        "CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN|SOURCE_LINK_CONTEXT_CXX_COMPILER_EXTERNAL_TOOLCHAIN|PATH"
        "CMAKE_CUDA_ARCHITECTURES|SOURCE_LINK_CONTEXT_CUDA_ARCHITECTURES|STRING"
        "CMAKE_CUDA_FLAGS|SOURCE_LINK_CONTEXT_CUDA_FLAGS|STRING"
        "CMAKE_CUDA_FLAGS_DEBUG|SOURCE_LINK_CONTEXT_CUDA_FLAGS_DEBUG|STRING"
        "CMAKE_CUDA_FLAGS_RELEASE|SOURCE_LINK_CONTEXT_CUDA_FLAGS_RELEASE|STRING"
        "CMAKE_CUDA_FLAGS_RELWITHDEBINFO|SOURCE_LINK_CONTEXT_CUDA_FLAGS_RELWITHDEBINFO|STRING"
        "CMAKE_CUDA_FLAGS_MINSIZEREL|SOURCE_LINK_CONTEXT_CUDA_FLAGS_MINSIZEREL|STRING"
        "CMAKE_CUDA_FLAGS_CHECKED|SOURCE_LINK_CONTEXT_CUDA_FLAGS_CHECKED|STRING"
        "CUDAToolkit_ROOT|SOURCE_LINK_CONTEXT_CUDATOOLKIT_ROOT|PATH"
        "CUDAToolkit_ROOT_DIR|SOURCE_LINK_CONTEXT_CUDATOOLKIT_ROOT_DIR|PATH"
        "CMAKE_VS_SDK_INCLUDE_DIRECTORIES|SOURCE_LINK_CONTEXT_VS_SDK_INCLUDE_DIRECTORIES|STRING"
        "CMAKE_VS_SDK_LIBRARY_DIRECTORIES|SOURCE_LINK_CONTEXT_VS_SDK_LIBRARY_DIRECTORIES|STRING"
        "CMAKE_VS_PLATFORM_TOOLSET_VERSION|SOURCE_LINK_CONTEXT_VS_PLATFORM_TOOLSET_VERSION|STRING"
        "CMAKE_VS_PLATFORM_TOOLSET_CUDA|SOURCE_LINK_CONTEXT_VS_PLATFORM_TOOLSET_CUDA|STRING"
        "CMAKE_VS_PLATFORM_TOOLSET_CUDA_CUSTOM_DIR|SOURCE_LINK_CONTEXT_VS_PLATFORM_TOOLSET_CUDA_CUSTOM_DIR|PATH"
        "CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION|SOURCE_LINK_CONTEXT_VS_WINDOWS_TARGET_PLATFORM_VERSION|STRING"
        "CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM|SOURCE_LINK_CONTEXT_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM|STRING"
    )
    foreach(_mapping IN LISTS _source_link_cache_mappings)
        string(REPLACE "|" ";" _mapping_fields "${_mapping}")
        list(GET _mapping_fields 0 _cache_name)
        list(GET _mapping_fields 1 _context_name)
        list(GET _mapping_fields 2 _cache_type)
        _ovphysx_get_source_link_value(_cache_value "${_cache_name}" "${_context_name}")
        if(NOT _cache_value STREQUAL "")
            _ovphysx_append_source_link_cache_value(
                "${output_file}" "${_cache_name}" "${_cache_type}" "${_cache_value}")
        endif()
    endforeach()
endfunction()

# Return generator-selection arguments separately from the initial cache. -T is
# valid only for a confirmed Visual Studio generator. In generated-context mode
# the exact outer toolset wins and no CUDA toolset is synthesized.
function(ovphysx_get_source_link_generator_args output_args output_generator)
    set(_generator "")
    set(_generator_source "ambient")
    if(DEFINED SOURCE_LINK_GENERATOR AND NOT SOURCE_LINK_GENERATOR STREQUAL "")
        set(_generator "${SOURCE_LINK_GENERATOR}")
        set(_generator_source "explicit")
    elseif(DEFINED SOURCE_LINK_CONTEXT_GENERATOR AND
            NOT SOURCE_LINK_CONTEXT_GENERATOR STREQUAL "")
        set(_generator "${SOURCE_LINK_CONTEXT_GENERATOR}")
        set(_generator_source "context")
    elseif(DEFINED ENV{CMAKE_GENERATOR} AND NOT "$ENV{CMAKE_GENERATOR}" STREQUAL "")
        set(_generator "$ENV{CMAKE_GENERATOR}")
    endif()

    set(_platform "")
    set(_toolset "")
    set(_instance "")
    if(_generator_source STREQUAL "explicit")
        if(DEFINED SOURCE_LINK_GENERATOR_PLATFORM)
            set(_platform "${SOURCE_LINK_GENERATOR_PLATFORM}")
        elseif(DEFINED CMAKE_GENERATOR_PLATFORM)
            set(_platform "${CMAKE_GENERATOR_PLATFORM}")
        endif()
        if(DEFINED SOURCE_LINK_GENERATOR_TOOLSET)
            set(_toolset "${SOURCE_LINK_GENERATOR_TOOLSET}")
        elseif(DEFINED CMAKE_GENERATOR_TOOLSET)
            set(_toolset "${CMAKE_GENERATOR_TOOLSET}")
        endif()
        if(DEFINED SOURCE_LINK_GENERATOR_INSTANCE)
            set(_instance "${SOURCE_LINK_GENERATOR_INSTANCE}")
        elseif(DEFINED CMAKE_GENERATOR_INSTANCE)
            set(_instance "${CMAKE_GENERATOR_INSTANCE}")
        endif()
    elseif(_generator_source STREQUAL "context")
        set(_platform "${SOURCE_LINK_CONTEXT_GENERATOR_PLATFORM}")
        set(_toolset "${SOURCE_LINK_CONTEXT_GENERATOR_TOOLSET}")
        set(_instance "${SOURCE_LINK_CONTEXT_GENERATOR_INSTANCE}")
    endif()

    set(_args)
    if(NOT _generator STREQUAL "")
        list(APPEND _args -G "${_generator}")
        if(_generator MATCHES "^Visual Studio")
            if(NOT _platform STREQUAL "")
                list(APPEND _args -A "${_platform}")
            endif()
            if(NOT _toolset STREQUAL "")
                list(APPEND _args -T "${_toolset}")
            elseif(NOT _generator_source STREQUAL "context" AND
                    WIN32 AND OVPHYSX_DEV_PHYSX AND
                    DEFINED SOURCE_LINK_CUDA_TOOLSET_DIR AND
                    EXISTS "${SOURCE_LINK_CUDA_TOOLSET_DIR}/bin/nvcc.exe")
                list(APPEND _args -T "cuda=${SOURCE_LINK_CUDA_TOOLSET_DIR}")
            endif()
            if(NOT _instance STREQUAL "")
                list(APPEND _args "-DCMAKE_GENERATOR_INSTANCE=${_instance}")
            endif()
        endif()
    endif()
    if(ARGC GREATER 2 AND NOT "${ARGV2}" STREQUAL "")
        list(APPEND _args -C "${ARGV2}")
    endif()

    set(${output_args} "${_args}" PARENT_SCOPE)
    set(${output_generator} "${_generator}" PARENT_SCOPE)
endfunction()
