## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXGPU_LIBTYPE STATIC)
	SET(PXPHYSXGPU_LIBTYPE_DEFS 
		PX_PHYSX_GPU_STATIC;PX_PHYSX_STATIC_LIB;
	)
ELSE()
	SET(PHYSXGPU_LIBTYPE SHARED)
	SET(PXPHYSXGPU_LIBTYPE_DEFS 
		PX_PHYSX_GPU_EXPORTS;
	)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_LINUX_COMPILE_DEFS};${PXPHYSXGPU_LIBTYPE_DEFS};

	$<$<CONFIG:debug>:${PHYSX_LINUX_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_LINUX_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_LINUX_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_LINUX_RELEASE_COMPILE_DEFS};>
)

SET(PHYSXGPU_LINK_FLAGS " ")
SET(PHYSXGPU_LINK_FLAGS_DEBUG " ")
SET(PHYSXGPU_LINK_FLAGS_CHECKED " ")
SET(PHYSXGPU_LINK_FLAGS_PROFILE " ")
SET(PHYSXGPU_LINK_FLAGS_RELEASE " ")

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXGPU_PLATFORM_OBJECT_FILES
		$<TARGET_OBJECTS:PhysXBroadphaseGpu>
		$<TARGET_OBJECTS:PhysXNarrowphaseGpu>
		$<TARGET_OBJECTS:PhysXSimulationControllerGpu>
		$<TARGET_OBJECTS:PhysXSolverGpu>
		$<TARGET_OBJECTS:PhysXCommonGpu>
		$<TARGET_OBJECTS:PhysXCudaContextManager>
		$<TARGET_OBJECTS:PhysXArticulationGpu>
	)
ELSE()
	SET(PHYSXGPU_PRIVATE_PLATFORM_LINKED_LIBS
		PhysXBroadphaseGpu
		PhysXNarrowphaseGpu
		PhysXSimulationControllerGpu
		PhysXSolverGpu
		PhysXCommonGpu
		PhysXCudaContextManager
		PhysXArticulationGpu
	)
ENDIF()

SET(PHYSXGPU_PLATFORM_SOURCES
	${PHYSXGPU_PLATFORM_OBJECT_FILES}
)
