## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXCudaContextManager
#

# Removed -malign_double


IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(CUDACONTEXTMANAGER_LIBTYPE OBJECT)
	SET(CUDACONTEXTMANAGER_LIBTYPE_DEFS 
		PX_PHYSX_STATIC_LIB;PX_PHYSX_GPU_STATIC;
	)
ELSE()
	SET(CUDACONTEXTMANAGER_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(CUDACONTEXTMANAGER_COMPILE_DEFS
	# Common to all configurations
	PRIVATE ${PHYSX_LINUX_COMPILE_DEFS};${CUDACONTEXTMANAGER_LIBTYPE_DEFS}

	PRIVATE $<$<CONFIG:debug>:${PHYSX_LINUX_DEBUG_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:checked>:${PHYSX_LINUX_CHECKED_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:profile>:${PHYSX_LINUX_PROFILE_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:release>:${PHYSX_LINUX_RELEASE_COMPILE_DEFS};>
)
