# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#

from ..utils import Limits
from pxr import Gf
import math

axes = ["X", "Y", "Z"]

class InfoData:
    def __init__(self, min=None, max=None, step=0.1, multiply_meter_fn=None, multiply_kg_fn=None):
        self.min = min
        self.max = max
        self.step = step
        self.multiply_meter_fn = multiply_meter_fn
        self.multiply_kg_fn = multiply_kg_fn


INFO_FLT_NONNEG = InfoData(*Limits.RANGE_FLT_NONNEG)
INFO_DEG = InfoData(*Limits.RANGE_DEG, 1)
INFO_RAD = InfoData(*Limits.RANGE_RAD)
INFO_FLT_NONNEG_VEC = InfoData(Gf.Vec3f(0), Gf.Vec3f(Limits.FLT_INF))
INFO_DEG_VEC = InfoData(Gf.Vec3f(-Limits.DEG_MAX), Gf.Vec3f(Limits.DEG_MAX))
INFO_BYTE_POS = InfoData(1, 255, 1)
INFO_BYTE_VEL = InfoData(0, 255, 1)
INFO_FLT_FINITE = InfoData(Limits.FLT_NMAX, Limits.FLT_MAX)

property_info = {
    "physics:gravityMagnitude": INFO_FLT_NONNEG,
    "physics:mass": INFO_FLT_NONNEG,
    "physics:density": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, multiply_meter_fn=lambda mpu: mpu * mpu * mpu, multiply_kg_fn=lambda kgpu: 1.0 / kgpu),
    "physics:diagonalInertia": INFO_FLT_NONNEG_VEC,
    "physics:dynamicFriction": INFO_FLT_NONNEG,
    "physics:staticFriction": INFO_FLT_NONNEG,
    "physics:restitution": InfoData(0, 1),
    "physics:breakForce": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, multiply_meter_fn=lambda mpu: 1.0 / mpu, multiply_kg_fn=lambda kgpu: 1.0 / kgpu),
    "physics:breakTorque": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, multiply_meter_fn=lambda mpu: 1.0 / (mpu * mpu), multiply_kg_fn=lambda kgpu: 1.0 / kgpu),
    "physics:coneAngle0Limit": InfoData(0, 180, 1),
    "physics:coneAngle1Limit": InfoData(0, 180, 1),
    "physics:minDistance": INFO_FLT_NONNEG,
    "physics:maxDistance": INFO_FLT_NONNEG,
    "physics:low": {"rot": INFO_DEG, "trans": None, "distance": None},
    "physics:high": {"rot": INFO_DEG, "trans": None, "distance": None},
    "physics:maxForce": INFO_FLT_NONNEG,  # for now we are not going to scale this with a multiply function, since it scales differently based on whether this is a linear or angular drive
    "physics:damping": INFO_FLT_NONNEG,
    "physics:stiffness": INFO_FLT_NONNEG,
    "maxActuatorVelocity": INFO_FLT_NONNEG,
    "velocityDependentResistance": INFO_FLT_NONNEG,
    "speedEffortGradient": INFO_FLT_NONNEG,
    "armature": INFO_FLT_NONNEG,
    "maxJointVelocity": INFO_FLT_NONNEG,
    "staticFrictionEffort": INFO_FLT_NONNEG,
    "dynamicFrictionEffort": INFO_FLT_NONNEG,
    "viscousFrictionCoefficient": INFO_FLT_NONNEG,
    "slopeLimit": InfoData(0, 0.5 * math.pi),
    "physxScene:bounceThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: 10 / mpu),
    "physxScene:frictionOffsetThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: 1 / mpu),
    "physxScene:minPositionIterationCount": INFO_BYTE_POS,
    "physxScene:maxPositionIterationCount": INFO_BYTE_POS,
    "physxScene:minVelocityIterationCount": INFO_BYTE_VEL,
    "physxScene:maxVelocityIterationCount": INFO_BYTE_VEL,
    "physxScene:envIdInBoundsBitCount": InfoData(-1, 16, step=1),
    "physxRigidBody:linearDamping": INFO_FLT_NONNEG,
    "physxRigidBody:angularDamping": INFO_FLT_NONNEG,
    "physxRigidBody:maxLinearVelocity": INFO_FLT_NONNEG,
    "physxRigidBody:maxAngularVelocity": INFO_FLT_NONNEG,
    "physxRigidBody:sleepThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: (10 / mpu) * (10 / mpu)),
    "physxRigidBody:stabilizationThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: (10 / mpu) * (10 / mpu)),
    "physxRigidBody:maxDepenetrationVelocity": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_meter_fn=lambda mpu: 1.0 / mpu),
    "physxRigidBody:maxContactImpulse": INFO_FLT_NONNEG,
    "physxRigidBody:solverPositionIterationCount": INFO_BYTE_POS,
    "physxRigidBody:solverVelocityIterationCount": INFO_BYTE_VEL,
    "physxContactReport:threshold": InfoData(multiply_meter_fn=lambda mpu: 1 / mpu),
    "physxCollision:contactOffset": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: 1 / mpu),
    "physxCollision:torsionalPatchRadius": INFO_FLT_NONNEG,
    "physxCollision:minTorsionalPatchRadius": INFO_FLT_NONNEG,
    "physxConvexHullCollision:hullVertexLimit": InfoData(8, 64, 1),
    "physxConvexHullCollision:minThickness": InfoData(0.001, 10.0, 0.1, lambda mpu: 1 / mpu),
    "physxConvexDecompositionCollision:hullVertexLimit": InfoData(8, 64, 1),
    "physxConvexDecompositionCollision:maxConvexHulls": InfoData(1, 2048, 1),
    "physxConvexDecompositionCollision:minThickness": InfoData(0.001, 10.0, 0.1, lambda mpu: 1 / mpu),
    "physxConvexDecompositionCollision:voxelResolution": InfoData(50000, 5000000, 10000),
    "physxConvexDecompositionCollision:errorPercentage": InfoData(0, 20, 0.25),
    "physxTriangleMeshSimplificationCollision:metric": InfoData(0, 1, 0.02),
    "physxJoint:jointFriction": INFO_FLT_NONNEG,
    "physxPhysicsDistanceJoint:springStiffness": INFO_FLT_NONNEG,
    "physxPhysicsDistanceJoint:springDamping": INFO_FLT_NONNEG,
    "restitution": INFO_FLT_NONNEG,
    "bounceThreshold": INFO_FLT_NONNEG,
    "stiffness": INFO_FLT_NONNEG,
    "damping": INFO_FLT_NONNEG,
    "physxArticulation:solverPositionIterationCount": INFO_BYTE_POS,
    "physxArticulation:solverVelocityIterationCount": INFO_BYTE_VEL,
    "physxArticulation:sleepThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: (10 / mpu) * (10 / mpu)),
    "physxArticulation:stabilizationThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: (10 / mpu) * (10 / mpu)),
    "physxArticulationJoint:maxJointVelocity": INFO_FLT_NONNEG,
    "physxArticulationJoint:frictionCoefficient": INFO_FLT_NONNEG,
    "physxCharacterController:invisibleWallHeight": INFO_FLT_NONNEG,
    "physxCharacterController:maxJumpHeight": INFO_FLT_NONNEG,
    "physxCharacterController:contactOffset": INFO_FLT_NONNEG,
    "physxCharacterController:stepOffset": INFO_FLT_NONNEG,
    "physxCharacterController:scaleCoeff": INFO_FLT_NONNEG,
    "physxCharacterController:volumeGrowth": INFO_FLT_NONNEG,
    "limitStiffness": INFO_FLT_NONNEG,
    "restLength": INFO_FLT_NONNEG,
    # DEPRECATED
    "physxDeformable:simulationHexahedralResolution": InfoData(4, 64, 1),
    "physxDeformable:collisionSimplificationRemeshingResolution": InfoData(10, 1000, 1),
    "physxDeformable:collisionSimplificationTargetTriangleCount": InfoData(0, 100000, 1),
    "physxDeformable:sleepThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, lambda mpu: 1.0 / mpu),
    "physxDeformable:settlingThreshold": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, lambda mpu: 1.0 / mpu),
    "physxDeformable:selfCollisionFilterDistance": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, lambda mpu: 1.0 / mpu),
    "physxDeformable:solverPositionIterationCount": INFO_BYTE_POS,
    "physxDeformableBodyMaterial:dampingScale": InfoData(0, 1),
    "physxDeformableBodyMaterial:density": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, multiply_meter_fn=lambda mpu: mpu * mpu * mpu, multiply_kg_fn=lambda kgpu: 1.0 / kgpu),
    "physxDeformableBodyMaterial:dynamicFriction": INFO_FLT_NONNEG,
    "physxDeformableBodyMaterial:elasticityDamping": INFO_FLT_NONNEG,
    "physxDeformableBodyMaterial:poissonsRatio": InfoData(0, 0.499),
    "physxDeformableBodyMaterial:youngsModulus": InfoData(*Limits.RANGE_FLT_NONNEG, 1, lambda mpu: mpu),
    "physxDeformableSurfaceMaterial:bendingDamping": InfoData(0, 1, multiply_meter_fn=lambda mpu: 1.0 / mpu / mpu),
    "physxDeformableSurfaceMaterial:density": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, multiply_meter_fn=lambda mpu: mpu * mpu * mpu, multiply_kg_fn=lambda kgpu: 1.0 / kgpu),
    "physxDeformableSurfaceMaterial:dynamicFriction": INFO_FLT_NONNEG,
    "physxDeformableSurfaceMaterial:elasticityDamping": INFO_FLT_NONNEG,
    "physxDeformableSurfaceMaterial:poissonsRatio": InfoData(0, 0.499),
    "physxDeformableSurfaceMaterial:thickness": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, lambda mpu: 1.0 / mpu),
    "physxDeformableSurfaceMaterial:youngsModulus": InfoData(*Limits.RANGE_FLT_NONNEG, 1, lambda mpu: mpu),
    #~DEPRECATED
    "contactOffset": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, multiply_meter_fn=lambda mpu: 1 / mpu), ## particle system is not an API, does not have a prefix
    "restOffset": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, multiply_meter_fn=lambda mpu: 1 / mpu),
    "particleContactOffset": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, multiply_meter_fn=lambda mpu: 1 / mpu),
    "solidRestOffset": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, multiply_meter_fn=lambda mpu: 1 / mpu),
    "fluidRestOffset": InfoData(*Limits.RANGE_FLT_NONNEG, 0.01, multiply_meter_fn=lambda mpu: 1 / mpu),
    "solverPositionIterationCount": INFO_BYTE_POS,
    "maxDepenetrationVelocity": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_meter_fn=lambda mpu: 1.0 / mpu),
    "maxVelocity": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_meter_fn=lambda mpu: 1.0 / mpu), ## end particle system attributes
    "physxParticleIsosurface:maxVertices": InfoData(3, Limits.INT_MAX),
    "physxParticleIsosurface:maxTriangles": InfoData(1, Limits.INT_MAX),
    "physxParticleIsosurface:maxSubgrids": InfoData(1, Limits.INT_MAX),
    "physxParticleIsosurface:gridSpacing": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_meter_fn=lambda mpu: 1 / mpu),
    "physxParticleIsosurface:surfaceDistance": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_meter_fn=lambda mpu: 1 / mpu),
    "physxParticleIsosurface:gridSmoothingRadius": INFO_FLT_NONNEG,
    "physxParticleIsosurface:numMeshSmoothingPasses": InfoData(0, Limits.INT_MAX),
    "physxParticleIsosurface:numMeshNormalSmoothingPasses": InfoData(0, Limits.INT_MAX),
    "physxParticleSmoothing:strength": InfoData(0, 1),
    "physxParticleAnisotropy:scale": INFO_FLT_NONNEG,
    "physxParticleAnisotropy:min": INFO_FLT_NONNEG,
    "physxParticleAnisotropy:max": INFO_FLT_NONNEG,
    "physxDiffuseParticles:maxDiffuseParticleMultiplier": InfoData(0, 4),
    "physxDiffuseParticles:threshold": InfoData(0, Limits.FLT_MAX, multiply_meter_fn=lambda mpu: mpu * mpu, multiply_kg_fn=lambda kpu: 1 / kpu),
    "physxDiffuseParticles:lifetime": INFO_FLT_NONNEG,
    "physxDiffuseParticles:airDrag": INFO_FLT_NONNEG,
    "physxDiffuseParticles:bubbleDrag": INFO_FLT_NONNEG,
    "physxDiffuseParticles:buoyancy": INFO_FLT_NONNEG,
    "physxDiffuseParticles:kineticEnergyWeight": INFO_FLT_NONNEG,
    "physxDiffuseParticles:pressureWeight": INFO_FLT_NONNEG,
    "physxDiffuseParticles:divergenceWeight": INFO_FLT_NONNEG,
    "physxDiffuseParticles:collisionDecay": InfoData(0, 1),
    "physxPBDMaterial:friction": INFO_FLT_NONNEG,
    "physxPBDMaterial:particleFrictionScale": INFO_FLT_NONNEG,
    "physxPBDMaterial:damping": INFO_FLT_NONNEG,
    "physxPBDMaterial:viscosity": INFO_FLT_NONNEG,
    "physxPBDMaterial:vorticityConfinement": INFO_FLT_NONNEG,
    "physxPBDMaterial:surfaceTension": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_meter_fn=lambda mpu: mpu * mpu * mpu),
    "physxPBDMaterial:cohesion": INFO_FLT_NONNEG,
    "physxPBDMaterial:adhesion": INFO_FLT_NONNEG,
    "physxPBDMaterial:particleAdhesionScale": INFO_FLT_NONNEG,
    "physxPBDMaterial:adhesionOffsetScale": INFO_FLT_NONNEG,
    "physxPBDMaterial:lift": INFO_FLT_NONNEG,
    "physxPBDMaterial:drag": INFO_FLT_NONNEG,
    "physxPBDMaterial:density": InfoData(*Limits.RANGE_FLT_NONNEG, 0.1, multiply_meter_fn=lambda mpu: mpu * mpu * mpu, multiply_kg_fn=lambda kgpu: 1.0 / kgpu),
    "physxPBDMaterial:cflCoefficient": InfoData(0, Limits.FLT_MAX),
    "physxParticle:particleGroup": InfoData(1, 2 ** 20, 1),
    "physxParticleSampling:samplingDistance": INFO_FLT_NONNEG,
    "physxParticleSampling:maxSamples": InfoData(0, Limits.INT_MAX, 1000),
    # DEPRECATED
    "physxParticle:pressure": INFO_FLT_NONNEG,
    "physxAutoParticleCloth:springStretchStiffness": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_kg_fn=lambda kpu: 1 / kpu),
    "physxAutoParticleCloth:springBendStiffness": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_kg_fn=lambda kpu: 1 / kpu),
    "physxAutoParticleCloth:springShearStiffness": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_kg_fn=lambda kpu: 1 / kpu),
    "physxAutoParticleCloth:springDamping": InfoData(*Limits.RANGE_FLT_NONNEG, multiply_kg_fn=lambda kpu: 1 / kpu),
    #~DEPRECATED
    "physxMaterial:compliantContactStiffness": INFO_FLT_NONNEG,
    "physxMaterial:compliantContactDamping": INFO_FLT_NONNEG,
    "physxSDFMeshCollision:sdfResolution": InfoData(1, 1250),
    "physxSDFMeshCollision:sdfSubgridResolution": InfoData(0, 30),
    "physxSDFMeshCollision:sdfNarrowBandThickness": InfoData(0, 1),
    "physxSDFMeshCollision:sdfMargin": InfoData(0, 1),
    "physxScene:gpuTempBufferCapacity": InfoData(4096),
    "physxScene:gpuMaxRigidContactCount": InfoData(1),
    "physxScene:gpuMaxRigidPatchCount": InfoData(1),
    "physxScene:gpuHeapCapacity": InfoData(128),
    "physxScene:gpuFoundLostPairsCapacity": InfoData(1),
    "physxScene:gpuFoundLostAggregatePairsCapacity": InfoData(1),
    "physxScene:gpuTotalAggregatePairsCapacity": InfoData(1),
    "physxScene:gpuMaxSoftBodyContacts": InfoData(1),
    "physxScene:gpuMaxParticleContacts": InfoData(1),
    "physxScene:gpuMaxNumPartitions": InfoData(1, 32),
}

not_authored_token = "N/A"

property_sentinels = {
    "physics:gravityMagnitude": {lambda stage_info: str(9.81 / stage_info.mpu): Limits.FLT_NINF},
    "physics:gravityDirection": {lambda stage_info: {"Y": "(0.0, -1.0, 0.0)", "Z": "(0.0, 0.0, -1.0)"}.get(stage_info.up): Gf.Vec3f(0)},
    "physics:diagonalInertia": {"Ignore": Gf.Vec3f(0)},
    "physics:mass": {"Autocomputed": 0},
    "physics:density": {"Autocomputed": 0},
    "physxDeformableBodyMaterial:density": {"Autocomputed": 0},
    "physics:lowerLimit": {"Not Limited": Limits.FLT_NINF},
    "physics:upperLimit": {"Not Limited": Limits.FLT_INF},
    "physics:coneAngle0Limit": {"Not Limited": -1.0},
    "physics:coneAngle1Limit": {"Not Limited": -1.0},
    "physics:minDistance": {"Not Limited": -1.0},
    "physics:maxDistance": {"Not Limited": -1.0},
    "physics:low": {"Not Limited": Limits.FLT_NINF},
    "physics:high": {"Not Limited": Limits.FLT_INF},
    "physics:maxForce": {"Not Limited": Limits.FLT_INF},
    "restLength": {"Set to initial length": Limits.FLT_NINF},
    "physxCollision:contactOffset": {"Autocomputed": Limits.FLT_NINF},
    "physxCollision:restOffset": {"Autocomputed": Limits.FLT_NINF},
    "physxTriangleMeshCollision:weldTolerance": {"Autocomputed": Limits.FLT_NINF},
    # DEPRECATED
    "physxDeformable:collisionSimplificationRemeshingResolution": {"Autocomputed": 0},
    "physxDeformable:collisionSimplificationTargetTriangleCount": {"Autocomputed": 0},
    "physxAutoAttachment:rigidSurfaceSamplingDistance": {"Autocomputed": Limits.FLT_NINF},
    "physxAutoAttachment:collisionFilteringOffset": {"Autocomputed": Limits.FLT_NINF},
    #~DEPRECATED
    "omniphysics:mass": {"Autocomputed": 0},
    "physxDeformableBody:selfCollisionFilterDistance": {"Autocomputed": Limits.FLT_NINF},
    "physxDeformableBody:resolution": {"Autocomputed": 0},
    "physxDeformableBody:remeshingResolution": {"Autocomputed": 0},
    "physxDeformableBody:targetTriangleCount": {"Autocomputed": 0},
    "physxAutoDeformableAttachment:rigidSurfaceSamplingDistance": {"Autocomputed": Limits.FLT_NINF},
    "physxAutoDeformableAttachment:collisionFilteringOffset": {"Autocomputed": Limits.FLT_NINF},
    "physxParticleIsosurface:gridSpacing": {"Autocomputed": Limits.FLT_NINF},
    "physxParticleIsosurface:surfaceDistance": {"Autocomputed": Limits.FLT_NINF},
    "physxParticleIsosurface:gridSmoothingRadius": {"Autocomputed": Limits.FLT_NINF},
    "physxParticleSampling:samplingDistance": {"Autocomputed": 0},
    "physxDiffuseParticles:maxDiffuseParticleMultiplier": {"Autocomputed": Limits.FLT_NINF},
    "contactOffset": {"Autocomputed": Limits.FLT_NINF},  # particle system attribute do not have a prefix
    "restOffset": {"Autocomputed": Limits.FLT_NINF},
    "solidRestOffset": {"Autocomputed": Limits.FLT_NINF},
    "fluidRestOffset": {"Autocomputed": Limits.FLT_NINF},  # end particle system attributes
    "physics:centerOfMass": {"Autocomputed": not_authored_token},
    "physics:principalAxes": {"Autocomputed": not_authored_token},
    "physxMaterial:compliantContactStiffness": {"Compliance Disabled": 0.0},
    "physxVehicle:subStepThresholdLongitudinalSpeed": {"Autocomputed": not_authored_token},
    "physxVehicle:minLongitudinalSlipDenominator": {"Autocomputed": not_authored_token},
    "physxVehicle:minPassiveLongitudinalSlipDenominator": {"Use Deprecated Attribute": 0},
    "physxVehicle:minActiveLongitudinalSlipDenominator": {"Autocomputed": 0},
    "physxVehicle:minLateralSlipDenominator": {"Autocomputed": 0},
    "physxVehicle:longitudinalStickyTireThresholdSpeed": {"Autocomputed": -1.0},
    "physxVehicle:lateralStickyTireThresholdSpeed": {"Autocomputed": -1.0},
    "physxVehicleSuspension:sprungMass": {"Autocomputed": 0.0},
    "physxVehicleTire:restLoad": {"Autocomputed": 0.0},
    "physxVehicleTire:lateralStiffnessGraph": {"Use Deprecated Attributes": Gf.Vec2f(0)},
    "physxVehicleTire:longitudinalStiffness": {"Use Deprecated Attribute": 0},
    "physxVehicleTire:camberStiffness": {"Use Deprecated Attribute": -1.0},
    "physxVehicleEngine:peakTorque": {"Autocomputed": -1.0},
    "physxVehicleEngine:dampingRateFullThrottle": {"Autocomputed": -1.0},
    "physxVehicleEngine:dampingRateZeroThrottleClutchEngaged": {"Autocomputed": -1.0},
    "physxVehicleEngine:dampingRateZeroThrottleClutchDisengaged": {"Autocomputed": -1.0},
    "physxVehicleDriveBasic:peakTorque": {"Autocomputed": -1.0},
}

property_change_on_edit_end_override = {
    "physics:lowerLimit": False,
    "physics:upperLimit": False,
    "physics:localRot0": False,
    "physics:localRot1": False,
}

property_instance_type = {
    **{f"trans{axis}": "trans" for axis in axes},
    **{f"rot{axis}": "rot" for axis in axes},
    "linear": "linear",
    "angular": "angular",
    "distance": "distance",
}
