## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build Snippet linux template
#

SET(SNIPPET_COMPILE_DEFS
	# Common to all configurations

	${PHYSX_LINUX_COMPILE_DEFS};RENDER_SNIPPET

	$<$<CONFIG:debug>:${PHYSX_LINUX_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_LINUX_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_LINUX_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_LINUX_RELEASE_COMPILE_DEFS};>
)

SET(SNIPPET_PLATFORM_SOURCES
	${PHYSX_ROOT_DIR}/snippets/snippetcommon/ClassicMain.cpp
)

SET(SNIPPET_PLATFORM_INCLUDES
)

SET(SNIPPET_PLATFORM_LINKED_LIBS SnippetRender OpenGL::GL OpenGL::GLU GLUT::GLUT X11 rt pthread dl -Wl,-rpath='${ORIGIN}')

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	LIST(APPEND SNIPPET_PLATFORM_LINKED_LIBS PhysXGpu)

	IF(${SNIPPET_NAME} STREQUAL "ConvexDecomposition")
		LIST(APPEND SNIPPET_PLATFORM_LINKED_LIBS VHACD)
	ENDIF()
ENDIF()
