## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build SnippetRender
#

FIND_PACKAGE(OpenGL REQUIRED) # Pull in OpenGL from system libraries
FIND_PACKAGE(GLUT REQUIRED) # Pull in GLUT from system libraries

SET(SNIPPETRENDER_COMPILE_DEFS
	# Common to all configurations

	${PHYSX_LINUX_COMPILE_DEFS};

	$<$<CONFIG:debug>:${PHYSX_LINUX_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_LINUX_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_LINUX_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_LINUX_RELEASE_COMPILE_DEFS};>
)

SET(SNIPPETRENDER_PLATFORM_INCLUDES)

SET(SNIPPETRENDER_PLATFORM_LINKED_LIBS OpenGL::GL OpenGL::GLU GLUT::GLUT)

IF(PX_GENERATE_GPU_PROJECTS OR PX_GENERATE_GPU_PROJECTS_ONLY)
	LIST(APPEND SNIPPETRENDER_PLATFORM_INCLUDES ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
	LIST(APPEND SNIPPETRENDER_PLATFORM_LINKED_LIBS CUDA::cuda_driver)
ENDIF()
