# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# @implements REQ-PYTHON-OMNIPVD-LATE-001
# @covers AC-1
# @implements REQ-CAPI-OVSTAGE-SCHEMA-001
# @covers AC-3

"""ovphysx: PhysX simulation of ovstage-populated scenes with Warp-array output.

AI agent / LLM instructions:
    This package ships skills (step-by-step playbooks) and code samples.
    Start by reading the SKILLS.md index bundled alongside this file:

        from pathlib import Path
        skills_index = Path(__file__).parent / "SKILLS.md"
        skills_dir   = Path(__file__).parent / "skills"
        samples_dir  = Path(__file__).parent / "samples"

    Or call ``ovphysx.ai_skills_path()`` to get the same paths as a dict.

    Key classes: PhysX and ContactBinding. (TensorBindingSpec belongs to the deprecated
    tensor-binding API; new code should use ``PhysX.read`` / ``PhysX.write``.)
    Full docs are in the ``docs/`` subdirectory of this package.

Important notes for agents:
    - ovphysx ships no OpenUSD runtime and never loads one. Scenes are
      populated through the ``ovstage`` package (an exact-version dependency)
      and attached with ``PhysX.attach_ovstage()``. Any USD used to author
      scenes (stock ``usd-core`` or another OpenUSD build) belongs to the
      application, not to ovphysx.
    - ovphysx ships its PhysX USD schemas as codeless resources and only tells
      you where they are: ``ovphysx.codeless_schema_root()`` and
      ``ovphysx.codeless_schema_paths()``. Register them yourself, with
      ``ovstage.population.register_usd_schemas([str(ovphysx.codeless_schema_root())])``
      before the first ovstage population call, and/or with your own USD runtime.
    - ``PhysX.read()`` and ``read_tokens()`` return ``warp.array`` on CPU and
      CUDA. ``warp-lang`` is a package dependency and provides downstream
      DLPack interoperability. The remaining DLTensor typing belongs to the
      legacy compatibility APIs.
    - ``import ovphysx`` has no side effects on the process environment and
      loads no native library; native loading is deferred until a native
      attribute (``PhysX``, ``ContactBinding``, etc.) is first accessed.
"""

# =============================================================================
# Pure-Python exports (no native loading, no USD, no environment changes)
# =============================================================================
#
# Importing ovphysx exposes the IntEnum types, ``__version__`` and the schema,
# skills and bootstrap helpers. Native library loading (_bindings, api classes)
# is deferred to the first access of a native-dependent attribute via
# ``__getattr__``.

import logging as _logging

_logger = _logging.getLogger("ovphysx")
_logger.addHandler(_logging.NullHandler())
_dll_directory_handles: list[object] = []

from .types import (
    ApiStatus,
    BindingPrimMode,
    ConfigBool,
    ConfigFloat,
    ConfigInt32,
    ConfigString,
    LogLevel,
    SceneQueryGeometryType,
    SceneQueryMode,
    TensorType,
)
from .config import OmniPvdDestination, PhysXConfig
from .schemas import codeless_schema_paths, codeless_schema_root

# Package version resolution (PEP 440), tried in order:
#   1. _version.py, generated by build_wheel.cmake during wheel staging.
#      Present only in installed wheels, never checked into the source tree.
#   2. The repo VERSION file three directories up from this file
#      (python/ovphysx/__init__.py -> ovphysx/VERSION), for editable installs
#      and `uv run pytest` from the source tree.
#   3. "unknown" when neither is available.
try:
    from ._version import __version__
except Exception:  # noqa: BLE001
    try:
        from pathlib import Path as _Path
        __version__ = (_Path(__file__).parent.parent.parent / "VERSION").read_text().strip()
    except Exception:  # noqa: BLE001
        __version__ = "unknown"


def ai_skills_path():
    """Return paths to the bundled SKILLS.md index, skills/, samples/, and docs/.

    AI agents: call this function to locate the playbooks, code samples,
    and documentation shipped with this package. No native loading required.

    In an installed wheel all paths exist. In the source repo before a build
    these files live at the project root (``ovphysx/``) instead of under
    ``python/ovphysx/``. The function falls back to the project root when the
    wheel-side copies are absent.
    """
    from pathlib import Path
    pkg = Path(__file__).parent
    skills_index = pkg / "SKILLS.md"
    if skills_index.exists():
        return {
            "skills_index": skills_index,
            "skills_dir": pkg / "skills",
            "samples_dir": pkg / "samples",
            "docs_dir": pkg / "docs",
        }
    # Source-repo fallback: python/ovphysx/../../ == ovphysx project root
    project_root = pkg.parent.parent
    return {
        "skills_index": project_root / "SKILLS.md",
        "skills_dir": project_root / "skills",
        "samples_dir": project_root / "tests" / "python_samples",
        "docs_dir": project_root / "docs",
    }


# =============================================================================
# Lazy native loading, triggered on first access to PhysX and the other native names.
# =============================================================================

_native_bootstrapped = False
_native_bootstrap_error: BaseException | None = None

def _bootstrap_native():
    """One-time native library loading. Deferred until first access to a native attr.

    On failure the original exception is stored and re-raised on every subsequent
    call, so callers always see the real error (not a confusing AttributeError).
    """
    global _native_bootstrapped, _native_bootstrap_error
    if _native_bootstrapped:
        if _native_bootstrap_error is not None:
            raise _native_bootstrap_error
        return
    _native_bootstrapped = True

    try:
        _bootstrap_native_impl()
    except BaseException as exc:
        _native_bootstrap_error = exc
        raise


def _bootstrap_native_impl():
    """One-time native bootstrap. Loads libraries and populates module globals.

    Steps (in order):
      - Import and inject all native-dependent names into module globals.
      - Drift guard: assert every __all__ entry is now resolvable.

    Raises RuntimeError on any failure (for example, a missing native library).
    """
    import os
    import importlib
    import sys
    import warnings
    from pathlib import Path

    module_dir = Path(__file__).parent
    lib_dir = module_dir / "lib"
    plugins_dir = module_dir / "plugins"
    ovstage_bin_dir = module_dir.parent / "ovstage" / "bin"
    ovstage_plugins_dir = ovstage_bin_dir / "plugins"

    # Wheel mode: a bundled libovphysx.so in lib/ indicates an installed wheel.
    # Wheel structure: lib/ (libovphysx.so, libovphysx_internal.so), plugins/ (carbonite/physx
    # plugins), schemas/physx/ (codeless PhysX USD schemas).
    lib_file = lib_dir / ("ovphysx.dll" if sys.platform == "win32" else "libovphysx.so")
    is_wheel_mode = lib_file.exists()
    uses_bundled_lib = is_wheel_mode and not os.environ.get("OVPHYSX_LIB")

    if is_wheel_mode:
        ovstage_runtime_name = "ovstage.dll" if sys.platform == "win32" else "libovstage.so"
        if uses_bundled_lib and (ovstage_bin_dir / ovstage_runtime_name).exists():
            os.environ.setdefault("OVSTAGE_LIBRARY_PATH_HINT", str(ovstage_bin_dir))
            try:
                ovstage_bindings = importlib.import_module("ovstage._src.bindings")
                if not getattr(ovstage_bindings, "OVSTAGE_LIBRARY_PATH_HINT", None):
                    ovstage_bindings.OVSTAGE_LIBRARY_PATH_HINT = str(ovstage_bin_dir)
            except Exception as exc:  # noqa: BLE001 -- best-effort hint; ovstage import is optional
                _logger.debug("Could not hint ovstage runtime dir to %s: %s", ovstage_bin_dir, exc)

        if uses_bundled_lib and sys.platform == "win32":
            # OVStage's DLL import closure spans bin/ and bin/plugins/. Windows
            # DLL-directory registration is not recursive, so both are needed.
            for dll_dir in (lib_dir, plugins_dir, ovstage_bin_dir, ovstage_plugins_dir):
                if dll_dir.exists():
                    _dll_directory_handles.append(os.add_dll_directory(str(dll_dir)))

        def _warn_if_missing(path: Path, label: str) -> None:
            if not path.exists():
                warnings.warn(
                    f"[ovphysx] Missing bundled {label}: {path}. "
                    "Wheel installation may be incomplete.",
                    RuntimeWarning,
                )

        _warn_if_missing(lib_dir, "lib directory")
        _warn_if_missing(plugins_dir, "plugins directory")
        _warn_if_missing(ovstage_bin_dir, "ovstage/bin directory")
        _warn_if_missing(ovstage_plugins_dir, "ovstage/bin/plugins directory")
        if sys.platform == "win32":
            _warn_if_missing(lib_dir / "ovphysx_internal.dll", "ovphysx_internal.dll")
        else:
            _warn_if_missing(lib_dir / "libovphysx_internal.so", "libovphysx_internal.so")

    # Import native-dependent modules and inject their names into the module globals.
    g = globals()

    from ._bindings import OP_INDEX_ALL
    from .contact_types import ContactEventHeader, ContactPoint, FrictionAnchor
    g["OP_INDEX_ALL"] = OP_INDEX_ALL
    g["ContactEventHeader"] = ContactEventHeader
    g["ContactPoint"] = ContactPoint
    g["FrictionAnchor"] = FrictionAnchor

    from .api import (
        PhysX,
        ContactBinding,
        TensorBindingSpec,
        disable_python_logging,
        enable_default_log_output,
        enable_python_logging,
        flush_log,
        get_log_level,
        set_log_level,
    )
    g["PhysX"] = PhysX
    g["ContactBinding"] = ContactBinding
    g["TensorBindingSpec"] = TensorBindingSpec
    g["set_log_level"] = set_log_level
    g["get_log_level"] = get_log_level
    g["enable_default_log_output"] = enable_default_log_output
    g["enable_python_logging"] = enable_python_logging
    g["disable_python_logging"] = disable_python_logging
    g["flush_log"] = flush_log

    from .dlpack import (
        DLPACK_VERSION,
        DLDataType,
        DLDataTypeCode,
        DLDevice,
        DLDeviceType,
        DLManagedTensor,
        DLTensor,
    )
    g["DLPACK_VERSION"] = DLPACK_VERSION
    g["DLDataType"] = DLDataType
    g["DLDataTypeCode"] = DLDataTypeCode
    g["DLDevice"] = DLDevice
    g["DLDeviceType"] = DLDeviceType
    g["DLManagedTensor"] = DLManagedTensor
    g["DLTensor"] = DLTensor

    # Drift guard: every public name in __all__ must now be resolvable.
    missing = [name for name in __all__ if name not in g]
    if missing:
        raise RuntimeError(
            f"_bootstrap_native() did not populate these __all__ entries: {missing}"
        )


def bootstrap() -> None:
    """Explicitly trigger native library loading.

    Normally this happens automatically on first access to any native
    attribute (``PhysX``, ``ContactBinding``, etc.).  Call this
    when you need to control the exact moment loading occurs, for example
    to ensure it happens before other USD-aware code runs or before
    environment variables that affect USD plugin discovery are modified.

    Idempotent: safe to call multiple times. Loading happens at most once.

    Raises:
        RuntimeError: If native library loading fails (e.g. missing shared
            library, incompatible USD version already loaded in the process).
    """
    _bootstrap_native()


def __getattr__(name):
    if name in __all__:
        _bootstrap_native()
        try:
            return globals()[name]
        except KeyError:
            pass
    raise AttributeError(f"module 'ovphysx' has no attribute {name!r}")


# Kept explicit (not assembled from submodule __all__s) so the full public API
# surface is readable in one place. The drift guard in _bootstrap_native_impl()
# ensures this list stays in sync with what actually gets injected into globals.
__all__ = [
    "__version__",
    # IntEnum types and exceptions (pure Python, always available)
    "TensorType",
    "LogLevel",
    "ApiStatus",
    "BindingPrimMode",
    "SceneQueryMode",
    "SceneQueryGeometryType",
    # Config types (pure Python, always available)
    "OmniPvdDestination",
    "PhysXConfig",
    "ConfigBool",
    "ConfigInt32",
    "ConfigFloat",
    "ConfigString",
    # Eager initialization (module-level, always available)
    "bootstrap",
    "codeless_schema_paths",
    "codeless_schema_root",
    "ai_skills_path",
    # Core API (native, lazy-loaded)
    "PhysX",
    "ContactBinding",
    "TensorBindingSpec",
    # Logging API
    "set_log_level",
    "get_log_level",
    "enable_default_log_output",
    "enable_python_logging",
    "disable_python_logging",
    "flush_log",
    # Contact report structs (pure-Python ctypes mirrors of C ABI structs)
    "ContactEventHeader",
    "ContactPoint",
    "FrictionAnchor",
    # Operation index sentinel
    "OP_INDEX_ALL",
    # DLPack structures
    "DLDevice",
    "DLDataType",
    "DLDataTypeCode",
    "DLDeviceType",
    "DLTensor",
    "DLManagedTensor",
    "DLPACK_VERSION",
]
