# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#

"""ovphysx -- USD-based physics simulation with DLPack tensor interoperability.

AI agent / LLM instructions:
    This package ships skills (step-by-step playbooks) and code samples.
    Start by reading the SKILLS.md index bundled alongside this file:

        from pathlib import Path
        skills_index = Path(__file__).parent / "SKILLS.md"
        skills_dir   = Path(__file__).parent / "skills"
        samples_dir  = Path(__file__).parent / "samples"

    Or call ``ovphysx.ai_skills_path()`` to get the same paths as a dict.

    Key classes: PhysX, ContactBinding, tensors (submodule).
    Full docs are in the ``docs/`` subdirectory of this package.

Important notes for agents:
    - ovphysx bundles its own OpenUSD libraries. It is not needed to install
      ``usd-core`` as a dependency -- doing so may cause version conflicts.
      FIXME: re-evaluate this once USD namespace py-less lands; at that point
      the bundled USD may no longer conflict with a separate usd-core install.
    - ovphysx exchanges tensor data via DLPack, so any framework that
      understands DLPack can consume it. Common optional companions are
      numpy (CPU tensors) and torch (GPU tensors), but they are not
      dependencies of this package. Users should add whichever they need
      to their own project requirements.
"""

# =============================================================================
# Pure-Python exports (zero side effects, no native loading, no USD)
# =============================================================================
#
# Importing ovphysx ONLY makes the IntEnum types and __version__ available.
# Native library loading (libcarb, USD version checks, _bindings, api classes)
# is deferred to first access of a native-dependent attribute via __getattr__.

from .types import (
    ApiStatus,
    BindingPrimMode,
    ConfigBool,
    ConfigFloat,
    ConfigInt32,
    ConfigString,
    DeviceType,
    LogLevel,
    PhysXDeviceError,
    PhysXType,
    SceneQueryGeometryType,
    SceneQueryMode,
    TensorType,
)
from .config import PhysXConfig

# Package version resolution (PEP 440), tried in order:
#   1. _version.py -- generated by build_wheel.cmake during wheel staging.
#      Present only in installed wheels, never checked into the source tree.
#   2. Repo VERSION file -- three directories up from this file
#      (python/ovphysx/__init__.py -> omni/ovphysx/VERSION).
#      Works for editable installs and `uv run pytest` from the source tree.
#   3. "unknown" -- fallback if neither is available.
try:
    from ._version import __version__
except Exception:  # noqa: BLE001
    try:
        from pathlib import Path as _Path
        __version__ = (_Path(__file__).parent.parent.parent / "VERSION").read_text().strip()
    except Exception:  # noqa: BLE001
        __version__ = "unknown"


def ai_skills_path():
    """Return paths to the bundled SKILLS.md index, skills/, samples/, and docs/.

    AI agents: call this function to locate the playbooks, code samples,
    and documentation shipped with this package. No native loading required.

    In an installed wheel all paths exist. In the source repo before a build
    these files live at the project root (``omni/ovphysx/``) instead of under
    ``python/ovphysx/``; the function falls back to the project root when the
    wheel-side copies are absent.
    """
    from pathlib import Path
    pkg = Path(__file__).parent
    skills_index = pkg / "SKILLS.md"
    if skills_index.exists():
        return {
            "skills_index": skills_index,
            "skills_dir": pkg / "skills",
            "samples_dir": pkg / "samples",
            "docs_dir": pkg / "docs",
        }
    # Source-repo fallback: python/ovphysx/../../ == omni/ovphysx project root
    project_root = pkg.parent.parent
    return {
        "skills_index": project_root / "SKILLS.md",
        "skills_dir": project_root / "skills",
        "samples_dir": project_root / "tests" / "python_samples",
        "docs_dir": project_root / "docs",
    }


# =============================================================================
# Lazy native loading -- triggered on first access to PhysX, etc.
# =============================================================================

import logging as _logging

_logger = _logging.getLogger("ovphysx")
_logger.addHandler(_logging.NullHandler())

_native_bootstrapped = False
_native_bootstrap_error: BaseException | None = None

# PhysX instance registry for tensor plugin loading.
# Pure Python, no native deps -- defined at module level so api.py and
# tensors/ can reference them without triggering _bootstrap_native().
_physx_instance = None
_tensor_plugins_loaded = False


def _register_physx_instance(instance):
    """Called by PhysX.__init__ to register that Carbonite is ready."""
    global _physx_instance
    _physx_instance = instance


def _unregister_physx_instance(instance):
    """Called by PhysX.release() to unregister the active instance."""
    global _physx_instance
    if _physx_instance is instance:
        _physx_instance = None


def _is_framework_ready() -> bool:
    """Check if Carbonite framework is initialized (PhysX instance exists)."""
    return _physx_instance is not None


def _ensure_tensor_plugins_loaded():
    """Load tensor plugins on first use. Raises clear error if PhysX not created."""
    global _tensor_plugins_loaded
    if _tensor_plugins_loaded:
        return
    if not _is_framework_ready():
        raise RuntimeError(
            "Tensor operations require an active PhysX instance.\n"
            "Create one first:\n\n"
            "    from ovphysx import PhysX\n"
            "    physx = PhysX()\n"
        )
    from . import _bindings
    result = _bindings._lib.ovphysx_load_tensor_plugins()
    if result != 0:
        raise RuntimeError(f"Failed to load tensor plugins (error code: {result})")
    _tensor_plugins_loaded = True


def _bootstrap_native():
    """One-time native library loading. Deferred until first access to a native attr.

    On failure the original exception is stored and re-raised on every subsequent
    call, so callers always see the real error (not a confusing AttributeError).
    """
    global _native_bootstrapped, _native_bootstrap_error
    if _native_bootstrapped:
        if _native_bootstrap_error is not None:
            raise _native_bootstrap_error
        return
    _native_bootstrapped = True

    try:
        _bootstrap_native_impl()
    except BaseException as exc:
        _native_bootstrap_error = exc
        raise


def _bootstrap_native_impl():
    """One-time native bootstrap. Loads libraries and populates module globals.

    Steps (in order):
      - Pre-load libcarb.so with RTLD_GLOBAL so Carbonite plugins can resolve symbols.
      - Pre-load libpython.so with RTLD_GLOBAL (Linux only, best-effort workaround for
        omni.physics.tensors.plugin's transitive libpython dependency via libusd_python).
      - Run USD version compatibility check.
      - Import and inject all native-dependent names into module globals.
      - Drift guard: assert every __all__ entry is now resolvable.

    Raises RuntimeError on any failure (missing library, USD version mismatch, etc.).
    """
    import ctypes
    import os
    import sys
    import sysconfig
    import warnings
    from pathlib import Path

    module_dir = Path(__file__).parent
    lib_dir = module_dir / "lib"
    plugins_dir = module_dir / "plugins"

    # Wheel mode: libovphysx.so bundled in lib/ means we're running from an installed wheel.
    # Wheel structure: lib/ (libovphysx.so, config.toml), plugins/ (carbonite/physx plugins, usd/).
    lib_file = lib_dir / ("ovphysx.dll" if sys.platform == "win32" else "libovphysx.so")
    is_wheel_mode = lib_file.exists()

    if is_wheel_mode:
        if sys.platform == "win32":
            os.add_dll_directory(str(lib_dir))
            os.add_dll_directory(str(plugins_dir))

        def _warn_if_missing(path: Path, label: str) -> None:
            if not path.exists():
                warnings.warn(
                    f"[ovphysx] Missing bundled {label}: {path}. "
                    "Wheel installation may be incomplete.",
                    RuntimeWarning,
                )

        _warn_if_missing(lib_dir, "lib directory")
        _warn_if_missing(plugins_dir, "plugins directory")
        _warn_if_missing(lib_dir / "config.toml", "config.toml")
        if sys.platform == "win32":
            _warn_if_missing(lib_dir / "ovphysx_clone.dll", "ovphysx_clone.dll")
        else:
            _warn_if_missing(lib_dir / "libovphysx_clone.so", "libovphysx_clone.so")

        if "PYTHONHOME" not in os.environ:
            os.environ["PYTHONHOME"] = sys.prefix

    # Pre-load libraries with RTLD_GLOBAL so Carbonite plugins can find symbols.
    # Store references in sys to survive module cleanup.
    if not hasattr(sys, "_omni_physx_preloaded_libs"):
        sys._omni_physx_preloaded_libs = []

    if is_wheel_mode:
        carb_lib_name = "carb.dll" if sys.platform == "win32" else "libcarb.so"
        carb_lib_path = plugins_dir / carb_lib_name

        if carb_lib_path.exists():
            try:
                if sys.platform == "win32":
                    carb_lib = ctypes.CDLL(str(carb_lib_path))
                else:
                    RTLD_NODELETE = 0x01000
                    carb_lib = ctypes.CDLL(str(carb_lib_path), mode=ctypes.RTLD_GLOBAL | RTLD_NODELETE)
                sys._omni_physx_preloaded_libs.append(carb_lib)
            except OSError as e:
                raise RuntimeError(f"Failed to load {carb_lib_name}: {e}") from e
        else:
            raise RuntimeError(
                f"Required Carbonite library not found: {carb_lib_path}\n"
                "The wheel may be corrupted or incomplete. Try reinstalling:\n"
                "  pip uninstall ovphysx && pip install ovphysx"
            )

        # FIXME(legacy-tensorAPI): remove once omni.physics.tensors.plugin no longer
        # links libusd_python.so, or once the legacy TensorAPI plugin is no longer
        # shipped at all.
        # The tensor plugin's pybind11 Python bindings pull in libusd_python.so ->
        # libpython, but libpython is not loaded RTLD_GLOBAL by default on Linux, so
        # dlopen'd plugins fail to resolve PyObject_* symbols at runtime. Preloading it
        # here is a workaround for that transitive dependency. Not needed on Windows
        # (DLL loader handles symbol visibility differently).
        if sys.platform != "win32":
            def _preload_python_lib():
                vars = sysconfig.get_config_vars()
                lib_name = vars.get("LDLIBRARY") or vars.get("DLLLIBRARY")
                lib_dirs = [
                    vars.get("LIBDIR"),
                    vars.get("LIBPL"),
                    os.path.join(vars.get("prefix") or "", "lib"),
                ]
                for directory in filter(None, lib_dirs):
                    if not lib_name:
                        continue
                    full_path = os.path.join(directory, lib_name)
                    if os.path.exists(full_path):
                        RTLD_NODELETE = 0x01000
                        lib = ctypes.CDLL(full_path, mode=ctypes.RTLD_GLOBAL | RTLD_NODELETE)
                        sys._omni_physx_preloaded_libs.append(lib)
                        _logger.info("Pre-loaded %s", full_path)
                        return os.path.basename(full_path)
                return None

            try:
                _preload_python_lib()
            except OSError as e:
                _logger.warning("Failed to pre-load libpython: %s", e)

    # USD version check must happen BEFORE importing any code that uses USD.
    # Validates already-loaded USD; otherwise defers to C++ for USD loading.
    try:
        from .usd_version_check import check_usd_compatibility
        check_usd_compatibility()
    except Exception as e:
        raise RuntimeError(f"USD version compatibility check failed: {e}") from e

    # Import native-dependent modules and inject into our module globals
    g = globals()

    from . import tensors as _tensors
    g["tensors"] = _tensors

    from ._bindings import OP_INDEX_ALL, ContactEventHeader, ContactPoint
    g["OP_INDEX_ALL"] = OP_INDEX_ALL
    g["ContactEventHeader"] = ContactEventHeader
    g["ContactPoint"] = ContactPoint

    from .api import (
        PhysX,
        ContactBinding,
        configure_azure_sas,
        configure_s3,
        disable_python_logging,
        enable_default_log_output,
        enable_python_logging,
        get_log_level,
        set_log_level,
    )
    g["PhysX"] = PhysX
    g["ContactBinding"] = ContactBinding
    g["configure_s3"] = configure_s3
    g["configure_azure_sas"] = configure_azure_sas
    g["set_log_level"] = set_log_level
    g["get_log_level"] = get_log_level
    g["enable_default_log_output"] = enable_default_log_output
    g["enable_python_logging"] = enable_python_logging
    g["disable_python_logging"] = disable_python_logging

    from .dlpack import (
        DLPACK_VERSION,
        DLDataType,
        DLDataTypeCode,
        DLDevice,
        DLDeviceType,
        DLManagedTensor,
        DLTensor,
        ManagedDLTensor,
    )
    g["DLPACK_VERSION"] = DLPACK_VERSION
    g["DLDataType"] = DLDataType
    g["DLDataTypeCode"] = DLDataTypeCode
    g["DLDevice"] = DLDevice
    g["DLDeviceType"] = DLDeviceType
    g["DLManagedTensor"] = DLManagedTensor
    g["DLTensor"] = DLTensor
    g["ManagedDLTensor"] = ManagedDLTensor

    # Drift guard: every public name in __all__ must now be resolvable.
    missing = [name for name in __all__ if name not in g]
    if missing:
        raise RuntimeError(
            f"_bootstrap_native() did not populate these __all__ entries: {missing}"
        )


def bootstrap() -> None:
    """Explicitly trigger native library loading.

    Normally this happens automatically on first access to any native
    attribute (``PhysX``, ``ContactBinding``, etc.).  Call this
    when you need to control the exact moment loading occurs -- for example,
    to ensure it happens before other USD-aware code runs or before
    environment variables that affect USD plugin discovery are modified.

    Idempotent: safe to call multiple times; loading happens at most once.

    Raises:
        RuntimeError: If native library loading fails (e.g. missing shared
            library, incompatible USD version already loaded in the process).
    """
    _bootstrap_native()


def __getattr__(name):
    if name in __all__ or name == "tensors":
        _bootstrap_native()
        try:
            return globals()[name]
        except KeyError:
            pass
    raise AttributeError(f"module 'ovphysx' has no attribute {name!r}")


# Kept explicit (not assembled from submodule __all__s) so the full public API
# surface is readable in one place. The drift guard in _bootstrap_native_impl()
# ensures this list stays in sync with what actually gets injected into globals.
__all__ = [
    "__version__",
    # IntEnum types and exceptions (pure Python, always available)
    "TensorType",
    "LogLevel",
    "ApiStatus",
    "DeviceType",
    "BindingPrimMode",
    "PhysXType",
    "PhysXDeviceError",
    "SceneQueryMode",
    "SceneQueryGeometryType",
    # Config types (pure Python, always available)
    "PhysXConfig",
    "ConfigBool",
    "ConfigInt32",
    "ConfigFloat",
    "ConfigString",
    # Eager initialization (module-level, always available)
    "bootstrap",
    "ai_skills_path",
    # Core API (native, lazy-loaded)
    "PhysX",
    "ContactBinding",
    # Remote storage credentials
    "configure_s3",
    "configure_azure_sas",
    # Logging API
    "set_log_level",
    "get_log_level",
    "enable_default_log_output",
    "enable_python_logging",
    "disable_python_logging",
    # Contact report structs (ctypes, native-dependent)
    "ContactEventHeader",
    "ContactPoint",
    # Operation index sentinel
    "OP_INDEX_ALL",
    # DLPack structures
    "DLDevice",
    "DLDataType",
    "DLDataTypeCode",
    "DLDeviceType",
    "DLTensor",
    "DLManagedTensor",
    "ManagedDLTensor",
    "DLPACK_VERSION",
]
