// Copyright (c) 2001-2004 NovodeX AG. All rights reserved.
// Copyright (c) 2004-2008 AGEIA Technologies, Inc. All rights reserved.
// SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#ifndef PXG_SIMULATION_CORE_KERNEL_INDICES_H
#define PXG_SIMULATION_CORE_KERNEL_INDICES_H

namespace physx
{

struct PxgSimulationCoreKernelBlockDim
{
	enum
	{
		UPDATE_BODY_EXTERNAL_VELOCITIES				=	256,
		UPDATE_BODIES_AND_SHAPES					=	256,
		UPDATE_LINKS_AND_JOINTCORES					=	256,
		UPDATE_JOINTS								=	256,
		UPDATE_TRANSFORMCACHE_AND_BOUNDARRAY		=	256,
		MERGE_TRANSFORMCACHE_AND_BOUNDARRAY_CHANGES =	256,
		UPDATE_AABBMGR_HANDLES						=	256,
		COMPUTE_FROZEN_UNFROZEN_HISTOGRAM			=	256,
		OUTPUT_FROZEN_UNFROZEN_HISTOGRAM			=	256,
		CREATE_FROZEN_UNFROZEN_ARRAY				=	256,
		NEW_ARTICULATION							=	256,
		RIGID_DYNAMIC_GET_GLOBAL_POSE				=   256,
		RIGID_DYNAMIC_GET_LINVEL					=   256,
		RIGID_DYNAMIC_GET_ANGVEL					= 	256,
		RIGID_DYNAMIC_GET_LINACCEL					=   256,
		RIGID_DYNAMIC_GET_ANGACCEL					= 	256,
		RIGID_DYNAMIC_SET_GLOBAL_POSE				= 	256,
		RIGID_DYNAMIC_SET_LINVEL					= 	256,
		RIGID_DYNAMIC_SET_ANGVEL 					= 	256,
		RIGID_DYNAMIC_SET_FORCE						=	256,
		RIGID_DYNAMIC_SET_TORQUE					=	256,
		RIGID_DYNAMIC_GET_FORCE						=	256,
		RIGID_DYNAMIC_GET_TORQUE					=	256,
		RIGID_DYNAMIC_COMPUTE_ACCELERATIONS			=   256,
		RIGID_DYNAMIC_COPY_PREVIOUS_VELOCITIES		=	256,
		D6_JOINT_GET_FORCE							=	256,
		D6_JOINT_GET_TORQUE							=	256
	};
};

struct PxgSimulationCoreKernelGridDim
{
	enum
	{
		UPDATE_BODY_EXTERNAL_VELOCITIES				=   64,
		UPDATE_BODIES_AND_SHAPES					=	64,
		NEW_ARTICULATION							=	64,
		UPDATE_SOFTBODIES							=	64,
		UPDATE_PARTICLESYSTEMS						=	64,
		UPDATE_LINKS_AND_JOINTCORES					=	64,
		UPDATE_JOINTS								=	64,
		UPDATE_TRANSFORMCACHE_AND_BOUNDARRAY		=	256,
		UPDATE_AABBMGR_HANDLES						=	64,
		COMPUTE_FROZEN_UNFROZEN_HISTOGRAM			=	32,	//this has to be 32 because we are doing warp scan
		OUTPUT_FROZEN_UNFROZEN_HISTOGRAM			=	32, //this has to be 32
		CREATE_FROZEN_UNFROZEN_ARRAY				=	64,
		RIGID_DYNAMIC_COMPUTE_ACCELERATIONS			=	256,
		RIGID_DYNAMIC_COPY_PREVIOUS_VELOCITIES		=	256
	};
};

}

#endif
