## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXTask
#

SET(PHYSXTASK_COMPILE_DEFS 
	${PHYSX_LINUX_COMPILE_DEFS};
)

SET(PHYSXTASK_COMPILE_DEFS 
	${PHYSX_LINUX_COMPILE_DEFS};_LIB
	
	$<$<CONFIG:debug>:${PHYSX_LINUX_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_LINUX_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_LINUX_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_LINUX_RELEASE_COMPILE_DEFS};>
)

SET(PHYSXTASK_LIBTYPE OBJECT)
