## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXPvdSDK
#

SET(PHYSXPVDSDK_LIBTYPE STATIC)

# this is only needed for NVTX
IF (PX_GENERATE_GPU_PROJECTS AND PX_USE_NVTX)
	SET(PHYSXPVDSDK_PLATFORM_INCLUDES
		${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}
	)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXPVDSDK_COMPILE_DEFS 
	# Common to all configurations
	${PHYSX_LINUX_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSX_LIBTYPE_DEFS};${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_LINUX_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_LINUX_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_LINUX_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_LINUX_RELEASE_COMPILE_DEFS};>
)

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXPVDSDK_PLATFORM_LINKED_LIBS PhysXGpu)
ENDIF()
