// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file omniUsdPhysicsDeformableSchema/attachment.h
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSATTACHMENT_API_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSATTACHMENT_API_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>
#include <pxr/usd/usdGeom/imageable.h>

PXR_NAMESPACE_OPEN_SCOPE

/// \class OmniUsdPhysicsDeformableSchemaAttachment
///
/// Base class for attachments between two suitable deformable body
/// simulation meshes, or between a deformable body simulation mesh and
/// a UsdGeomXformable's coordinate frame.
///
class OmniUsdPhysicsDeformableSchemaAttachment : public UsdGeomImageable
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::ConcreteTyped;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsAttachment);
        return t;
    }

    /// Construct a OmniUsdPhysicsDeformableSchemaAttachment on UsdPrim \p prim .
    /// Equivalent to OmniUsdPhysicsDeformableSchemaAttachment::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit OmniUsdPhysicsDeformableSchemaAttachment(const UsdPrim& prim=UsdPrim()) : UsdGeomImageable(prim) {}

    /// Construct a OmniUsdPhysicsDeformableSchemaAttachment on the prim held by \p schemaObj .
    /// Should be preferred over OmniUsdPhysicsDeformableSchemaAttachment(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit OmniUsdPhysicsDeformableSchemaAttachment(const UsdSchemaBase& schemaObj) : UsdGeomImageable(schemaObj) {}

    /// Destructor.
    virtual ~OmniUsdPhysicsDeformableSchemaAttachment() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsAttachmentEnabled,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsStiffness,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDamping,
        };
        return localNames;
    }

    /// Return a OmniUsdPhysicsDeformableSchemaAttachment holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// OmniUsdPhysicsDeformableSchemaAttachment(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static OmniUsdPhysicsDeformableSchemaAttachment Get(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaAttachment(stage->GetPrimAtPath(path)); }

    /// Attempt to ensure a \a UsdPrim adhering to this schema at \p path
    /// is defined (according to UsdPrim::IsDefined()) on this stage.
    ///
    /// If a prim adhering to this schema at \p path is already defined on this
    /// stage, return that prim.  Otherwise author an \a SdfPrimSpec with
    /// \a specifier == \a SdfSpecifierDef and this schema's prim type name for
    /// the prim at \p path at the current EditTarget.  Author \a SdfPrimSpec s
    /// with \p specifier == \a SdfSpecifierDef and empty typeName at the
    /// current EditTarget for any nonexistent, or existing but not \a Defined
    /// ancestors.
    ///
    /// The given \a path must be an absolute prim path that does not contain
    /// any variant selections.
    ///
    /// If it is impossible to author any of the necessary PrimSpecs, (for
    /// example, in case \a path cannot map to the current UsdEditTarget's
    /// namespace) issue an error and return an invalid \a UsdPrim.
    ///
    /// Note that this method may return a defined prim whose typeName does not
    /// specify this schema class, in case a stronger typeName opinion overrides
    /// the opinion at the current EditTarget.
    static OmniUsdPhysicsDeformableSchemaAttachment Define(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaAttachment(stage->DefinePrim(path, OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsAttachment)); }

public:
    // --------------------------------------------------------------------- //
    // ATTACHMENTENABLED
    // --------------------------------------------------------------------- //
    /// Determines if this PhysicsAttachment is enabled.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool omniphysics:attachmentEnabled = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetAttachmentEnabledAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsAttachmentEnabled); }

    /// See GetAttachmentEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateAttachmentEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsAttachmentEnabled,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // STIFFNESS
    // --------------------------------------------------------------------- //
    /// Distance proportional factor for the attachment.
    /// "inf" implies a hard constraint if the simulator can support it.
    /// Range: [0, inf)
    /// Units: mass/second/second
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:stiffness = inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetStiffnessAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsStiffness); }

    /// See GetStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsStiffness,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // DAMPING
    // --------------------------------------------------------------------- //
    /// Proportional factor of the force acting against the direction
    /// of relative motion.
    /// Range: [0, inf)
    /// Units: mass/second
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:damping = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDampingAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDamping); }

    /// See GetDampingAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDampingAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDamping,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SRC0
    // --------------------------------------------------------------------- //
    /// Relationship to a single deformable body's simulation mesh.
    /// The attachment locations are specified in the derived attachment
    /// class.
    UsdRelationship GetSrc0Rel() const
    { return GetPrim().GetRelationship(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSrc0); }

    /// See GetSrc0Rel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateSrc0Rel() const
    { return GetPrim().CreateRelationship(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSrc0, /* custom = */ false); }

public:
    // --------------------------------------------------------------------- //
    // SRC1
    // --------------------------------------------------------------------- //
    /// Relationship to a single deformable body's simulation mesh or
    /// a single UsdGeomXformable. The attachment locations are specified in the
    /// derived attachment class.
    UsdRelationship GetSrc1Rel() const
    { return GetPrim().GetRelationship(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSrc1); }

    /// See GetSrc1Rel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateSrc1Rel() const
    { return GetPrim().CreateRelationship(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSrc1, /* custom = */ false); }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
