// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file omniUsdPhysicsDeformableSchema/baseMaterialAPI.h
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSBASEMATERIALAPI_API_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSBASEMATERIALAPI_API_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class OmniUsdPhysicsDeformableSchemaBaseMaterialAPI
///
/// Adds simulation material properties to a Material. All collisions
/// that have a relationship to this material will have their collision response
/// defined through this material.
///
class OmniUsdPhysicsDeformableSchemaBaseMaterialAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsBaseMaterialAPI);
        return t;
    }

    /// Construct a OmniUsdPhysicsDeformableSchemaBaseMaterialAPI on UsdPrim \p prim .
    /// Equivalent to OmniUsdPhysicsDeformableSchemaBaseMaterialAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit OmniUsdPhysicsDeformableSchemaBaseMaterialAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a OmniUsdPhysicsDeformableSchemaBaseMaterialAPI on the prim held by \p schemaObj .
    /// Should be preferred over OmniUsdPhysicsDeformableSchemaBaseMaterialAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit OmniUsdPhysicsDeformableSchemaBaseMaterialAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~OmniUsdPhysicsDeformableSchemaBaseMaterialAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDynamicFriction,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsStaticFriction,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDensity,
        };
        return localNames;
    }

    /// Return a OmniUsdPhysicsDeformableSchemaBaseMaterialAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// OmniUsdPhysicsDeformableSchemaBaseMaterialAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static OmniUsdPhysicsDeformableSchemaBaseMaterialAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaBaseMaterialAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsBaseMaterialAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "OmniPhysicsBaseMaterialAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid OmniUsdPhysicsDeformableSchemaBaseMaterialAPI object is returned upon success.
    /// An invalid (or empty) OmniUsdPhysicsDeformableSchemaBaseMaterialAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static OmniUsdPhysicsDeformableSchemaBaseMaterialAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsBaseMaterialAPI)) { return OmniUsdPhysicsDeformableSchemaBaseMaterialAPI(prim); }
        return OmniUsdPhysicsDeformableSchemaBaseMaterialAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // DYNAMICFRICTION
    // --------------------------------------------------------------------- //
    /// Dynamic friction coefficient.
    /// Units: None
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:dynamicFriction = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDynamicFrictionAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDynamicFriction); }

    /// See GetDynamicFrictionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDynamicFrictionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDynamicFriction,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // STATICFRICTION
    // --------------------------------------------------------------------- //
    /// Static friction coefficient.
    /// Units: None
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:staticFriction = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetStaticFrictionAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsStaticFriction); }

    /// See GetStaticFrictionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateStaticFrictionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsStaticFriction,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // DENSITY
    // --------------------------------------------------------------------- //
    /// If non-zero, defines the density of the material. This can be
    /// used for body mass computation, see PhysicsMassAPI.
    /// Note that if the density is 0.0 it is ignored.
    /// Units: mass/distance/distance/distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:density = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDensityAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDensity); }

    /// See GetDensityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDensityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsDensity,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
