// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file omniUsdPhysicsDeformableSchema/deformablePoseAPI.h
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSDEFORMABLEPOSEAPI_API_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSDEFORMABLEPOSEAPI_API_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class OmniUsdPhysicsDeformableSchemaDeformablePoseAPI
///
/// Defines a deformable mesh pose which can be used for one or
/// multiple purposes. Multiple pose APIs can be specified for different
/// purposes. The pose API instance name can be chosen arbitrarily.
///
class OmniUsdPhysicsDeformableSchemaDeformablePoseAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::MultipleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsDeformablePoseAPI);
        return t;
    }

    /// Construct a OmniUsdPhysicsDeformableSchemaDeformablePoseAPI on UsdPrim \p prim with
    /// name \p name . Equivalent to
    /// OmniUsdPhysicsDeformableSchemaDeformablePoseAPI::Get(
    ///    prim.GetStage(),
    ///    prim.GetPath().AppendProperty(
    ///        "deformablePose:name"));
    ///
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(const UsdPrim& prim=UsdPrim(), const TfToken &name=TfToken())
        : UsdAPISchemaBase(prim, name) {}

    /// Construct a OmniUsdPhysicsDeformableSchemaDeformablePoseAPI on the prim held by \p schemaObj with
    /// name \p name.  Should be preferred over
    /// OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(schemaObj.GetPrim(), name), as it preserves
    /// SchemaBase state.
    explicit OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(const UsdSchemaBase& schemaObj, const TfToken &name)
        : UsdAPISchemaBase(schemaObj, name) {}

    /// Returns the name of this multiple-apply schema instance
    TfToken GetName() const { return _GetInstanceName(); }

    /// Destructor.
    virtual ~OmniUsdPhysicsDeformableSchemaDeformablePoseAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPurposes,
            OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPoints,
        };
        return localNames;
    }

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes for a given instance name.  Does not
    /// include attributes that may be authored by custom/extended methods of
    /// the schemas involved. The names returned will have the proper namespace
    /// prefix.
    static TfTokenVector GetSchemaAttributeNames(bool includeInherited, const TfToken &instanceName)
    {
        const TfTokenVector &attrNames = GetSchemaAttributeNames(includeInherited);
        if (instanceName.IsEmpty()) {
            return attrNames;
        }
        TfTokenVector result;
        result.reserve(attrNames.size());
        for (const TfToken &attrName : attrNames) {
            result.push_back(UsdSchemaRegistry::MakeMultipleApplyNameInstance(attrName, instanceName));
        }
        return result;
    }

    /// Checks if the given name \p baseName is the base name of a property
    /// of OmniPhysicsDeformablePoseAPI.
    static bool IsSchemaPropertyBaseName(const TfToken &baseName)
    {
        static TfTokenVector attrsAndRels = {
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPurposes),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPoints),
        };
        return std::find(attrsAndRels.begin(), attrsAndRels.end(), baseName) != attrsAndRels.end();
    }

    /// Checks if the given path \p path is of an API schema of type
    /// OmniPhysicsDeformablePoseAPI. If so, it stores the instance name of
    /// the schema in \p name and returns true. Otherwise, it returns false.
    static bool IsOmniPhysicsDeformablePoseAPIPath(const SdfPath &path, TfToken *name)
    {
        if (!path.IsPropertyPath()) {
            return false;
        }
        const std::string propertyName = path.GetName();
        const TfTokenVector tokens = SdfPath::TokenizeIdentifierAsTokens(propertyName);
        if (tokens.empty()) {
            return false;
        }
        const TfToken &baseName = *tokens.rbegin();
        if (IsSchemaPropertyBaseName(baseName)) {
            return false;
        }
        if (tokens.size() >= 2
            && tokens[0] == OmniUsdPhysicsDeformableSchemaTokens->deformablePose) {
            if (name) {
                *name = TfToken(propertyName.substr(OmniUsdPhysicsDeformableSchemaTokens->deformablePose.GetString().size() + 1));
            }
            return true;
        }
        return false;
    }

    /// Return a OmniUsdPhysicsDeformableSchemaDeformablePoseAPI with name \p name holding the
    /// prim \p prim. Shorthand for OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(prim, name);
    static OmniUsdPhysicsDeformableSchemaDeformablePoseAPI Get(const UsdPrim &prim, const TfToken &name)
    { return OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(prim, name); }

    /// Return a OmniUsdPhysicsDeformableSchemaDeformablePoseAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  \p path must be of the format
    /// <path>.deformablePose:name .
    ///
    /// This is shorthand for the following:
    ///
    /// \code
    /// TfToken name = SdfPath::StripNamespace(path.GetToken());
    /// OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(
    ///     stage->GetPrimAtPath(path.GetPrimPath()), name);
    /// \endcode
    ///
    static OmniUsdPhysicsDeformableSchemaDeformablePoseAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    {
        if (!stage) {
            return OmniUsdPhysicsDeformableSchemaDeformablePoseAPI();
        }
        TfToken name;
        if (!IsOmniPhysicsDeformablePoseAPIPath(path, &name)) {
            return OmniUsdPhysicsDeformableSchemaDeformablePoseAPI();
        }
        return OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(stage->GetPrimAtPath(path.GetPrimPath()), name);
    }

    /// Return a vector of all named instances of OmniUsdPhysicsDeformableSchemaDeformablePoseAPI on the
    /// given \p prim.
    static std::vector<OmniUsdPhysicsDeformableSchemaDeformablePoseAPI> GetAll(const UsdPrim &prim)
    {
        std::vector<OmniUsdPhysicsDeformableSchemaDeformablePoseAPI> schemas;
        const TfType &type = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsDeformablePoseAPI);
        for (const auto &n : _GetMultipleApplyInstanceNames(prim, type)) {
            schemas.emplace_back(prim, n);
        }
        return schemas;
    }

    /// Returns true if this <b>multiple-apply</b> API schema can be applied,
    /// with the given instance name, \p name, to the given \p prim. If this
    /// schema can not be a applied the prim, this returns false and, if
    /// provided, populates \p whyNot with the reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, const TfToken &name, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsDeformablePoseAPI, name, whyNot); }

    /// Applies this <b>multiple-apply</b> API schema to the given \p prim
    /// along with the given instance name, \p name.
    ///
    /// This information is stored by adding "OmniPhysicsDeformablePoseAPI:<i>name</i>"
    /// to the token-valued, listOp metadata \em apiSchemas on the prim.
    /// For example, if \p name is 'instance1', the token
    /// 'OmniPhysicsDeformablePoseAPI:instance1' is added to 'apiSchemas'.
    ///
    /// \return A valid OmniUsdPhysicsDeformableSchemaDeformablePoseAPI object is returned upon success.
    /// An invalid (or empty) OmniUsdPhysicsDeformableSchemaDeformablePoseAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for
    /// conditions resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static OmniUsdPhysicsDeformableSchemaDeformablePoseAPI Apply(const UsdPrim &prim, const TfToken &name)
    {
        if (prim.ApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsDeformablePoseAPI, name)) { return OmniUsdPhysicsDeformableSchemaDeformablePoseAPI(prim, name); }
        return OmniUsdPhysicsDeformableSchemaDeformablePoseAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // PURPOSES
    // --------------------------------------------------------------------- //
    /// The set of purposes this pose is used for.
    /// "bindPose" - The pose in which graphical UsdGeomPointBased and
    /// deformable simulation meshes are bound to each other. The bindPose
    /// purpose needs to be specified on the simulation mesh and all graphical
    /// meshes if a specific bind pose is needed. If not specified, the default
    /// mesh points are used for the embedding.
    /// "selfCollisionFilterPose" - The pose used for self collision
    /// filtering. Ovelapping domains of the mesh in this pose are excluded
    /// from self collision. The selfCollisionFilterPose purpose needs to be
    /// specified on the simulation mesh only. If not specified, the default
    /// mesh points are used for self collision filtering.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `uniform token[] omniphysics:purposes` |
    /// | C++ Type | VtArray<TfToken> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->TokenArray |
    /// | \ref SdfVariability "Variability" | SdfVariabilityUniform |
    /// | \ref OmniUsdPhysicsDeformableSchemaTokens "Allowed Values" | bindPose, selfCollisionFilterPose |
    UsdAttribute GetPurposesAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPurposes, _GetInstanceName())); }

    /// See GetPurposesAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreatePurposesAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPurposes, _GetInstanceName()),
                   SdfValueTypeNames->TokenArray, /* custom = */ false,
                   SdfVariabilityUniform, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // POINTS
    // --------------------------------------------------------------------- //
    /// The points defining the pose of a mesh. The number of
    /// points needs to match the number of points in the mesh.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `point3f[] omniphysics:points` |
    /// | C++ Type | VtArray<GfVec3f> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Point3fArray |
    UsdAttribute GetPointsAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPoints, _GetInstanceName())); }

    /// See GetPointsAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreatePointsAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(OmniUsdPhysicsDeformableSchemaTokens->deformablePose_MultipleApplyTemplate_OmniphysicsPoints, _GetInstanceName()),
                   SdfValueTypeNames->Point3fArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
