// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- umbrella include for the codeless OmniUsdPhysicsDeformableSchema
// C++ API. Includes every header-only wrapper and the token table. DO NOT EDIT.
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIUSDPHYSICSDEFORMABLESCHEMA_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIUSDPHYSICSDEFORMABLESCHEMA_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include "omniUsdPhysicsDeformableSchema/attachment.h"
#include "omniUsdPhysicsDeformableSchema/baseMaterialAPI.h"
#include "omniUsdPhysicsDeformableSchema/bodyAPI.h"
#include "omniUsdPhysicsDeformableSchema/curvesDeformableMaterialAPI.h"
#include "omniUsdPhysicsDeformableSchema/curvesDeformableSimAPI.h"
#include "omniUsdPhysicsDeformableSchema/deformableBodyAPI.h"
#include "omniUsdPhysicsDeformableSchema/deformableMaterialAPI.h"
#include "omniUsdPhysicsDeformableSchema/deformablePoseAPI.h"
#include "omniUsdPhysicsDeformableSchema/elementCollisionFilter.h"
#include "omniUsdPhysicsDeformableSchema/surfaceDeformableMaterialAPI.h"
#include "omniUsdPhysicsDeformableSchema/surfaceDeformableSimAPI.h"
#include "omniUsdPhysicsDeformableSchema/tetXformAttachment.h"
#include "omniUsdPhysicsDeformableSchema/triTriAttachment.h"
#include "omniUsdPhysicsDeformableSchema/volumeDeformableSimAPI.h"
#include "omniUsdPhysicsDeformableSchema/vtxCrvAttachment.h"
#include "omniUsdPhysicsDeformableSchema/vtxTetAttachment.h"
#include "omniUsdPhysicsDeformableSchema/vtxTriAttachment.h"
#include "omniUsdPhysicsDeformableSchema/vtxVtxAttachment.h"
#include "omniUsdPhysicsDeformableSchema/vtxXformAttachment.h"

#endif
