// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file omniUsdPhysicsDeformableSchema/surfaceDeformableMaterialAPI.h
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSSURFACEDEFORMABLEMATERIALAPI_API_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSSURFACEDEFORMABLEMATERIALAPI_API_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI
///
/// Applied to Material in addition to PhysicsMaterialAPI and
/// DeformableMaterialAPI. Defines additional material properties for
/// surface deformable bodies.
///
class OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsSurfaceDeformableMaterialAPI);
        return t;
    }

    /// Construct a OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI on UsdPrim \p prim .
    /// Equivalent to OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI on the prim held by \p schemaObj .
    /// Should be preferred over OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceThickness,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceStretchStiffness,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceShearStiffness,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceBendStiffness,
        };
        return localNames;
    }

    /// Return a OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsSurfaceDeformableMaterialAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "OmniPhysicsSurfaceDeformableMaterialAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI object is returned upon success.
    /// An invalid (or empty) OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsSurfaceDeformableMaterialAPI)) { return OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI(prim); }
        return OmniUsdPhysicsDeformableSchemaSurfaceDeformableMaterialAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACETHICKNESS
    // --------------------------------------------------------------------- //
    /// Surface thickness.
    /// Units: distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:surfaceThickness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSurfaceThicknessAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceThickness); }

    /// See GetSurfaceThicknessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceThicknessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceThickness,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACESTRETCHSTIFFNESS
    // --------------------------------------------------------------------- //
    /// Optional override for stretching stiffness; by default derived
    /// from youngsModulus and surfaceThickness.
    /// Units are equivalent to Pascals or force per area.
    /// Range: [0, inf)
    /// Units: mass/(distance*seconds*seconds)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:surfaceStretchStiffness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSurfaceStretchStiffnessAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceStretchStiffness); }

    /// See GetSurfaceStretchStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceStretchStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceStretchStiffness,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACESHEARSTIFFNESS
    // --------------------------------------------------------------------- //
    /// Optional override for shearing stiffness; by default derived
    /// from youngsModulus and surfaceThickness.
    /// Units are equivalent to Pascals or force per area.
    /// Range: [0, inf)
    /// Units: mass/(distance*seconds*seconds)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:surfaceShearStiffness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSurfaceShearStiffnessAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceShearStiffness); }

    /// See GetSurfaceShearStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceShearStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceShearStiffness,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACEBENDSTIFFNESS
    // --------------------------------------------------------------------- //
    /// Optional override for bending stiffness; by default derived
    /// from youngsModulus and surfaceThickness.
    /// Units are equivalent to Pascals or force per area.
    /// Range: [0, inf)
    /// Units: mass/(distance*seconds*seconds)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float omniphysics:surfaceBendStiffness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSurfaceBendStiffnessAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceBendStiffness); }

    /// See GetSurfaceBendStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceBendStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsSurfaceBendStiffness,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
