// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file omniUsdPhysicsDeformableSchema/volumeDeformableSimAPI.h
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSVOLUMEDEFORMABLESIMAPI_API_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSVOLUMEDEFORMABLESIMAPI_API_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI
///
/// Identifies a UsdGeomTetMesh to be used as the simulation mesh for
/// a volume deformable body, distinguishing it from geometries used exclusively
/// for graphics or collision.
/// A volume deformable body requires exactly one tetrahedral simulation mesh,
/// which can either have both DeformableBodyAPI and VolumeDeformableSimAPI
/// applied, or, in a hierarchical setup, be the direct child of the root with
/// DeformableBodyAPI.
/// The simulation API also defines attributes to describe the rest shape of the
/// volume deformable body.
///
class OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsVolumeDeformableSimAPI);
        return t;
    }

    /// Construct a OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI on UsdPrim \p prim .
    /// Equivalent to OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI on the prim held by \p schemaObj .
    /// Should be preferred over OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsRestShapePoints,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsRestTetVtxIndices,
        };
        return localNames;
    }

    /// Return a OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsVolumeDeformableSimAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "OmniPhysicsVolumeDeformableSimAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI object is returned upon success.
    /// An invalid (or empty) OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsVolumeDeformableSimAPI)) { return OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI(prim); }
        return OmniUsdPhysicsDeformableSchemaVolumeDeformableSimAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // RESTSHAPEPOINTS
    // --------------------------------------------------------------------- //
    /// Describes the rest shape in (local) space for a deformable body
    /// simulation mesh.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `point3f[] omniphysics:restShapePoints` |
    /// | C++ Type | VtArray<GfVec3f> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Point3fArray |
    UsdAttribute GetRestShapePointsAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsRestShapePoints); }

    /// See GetRestShapePointsAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateRestShapePointsAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsRestShapePoints,
                   SdfValueTypeNames->Point3fArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // RESTTETVTXINDICES
    // --------------------------------------------------------------------- //
    /// Per tetrahedral element indices into restShapePoints to describe
    /// the rest shape of each tetrahedron. This allows for restTetIndices to
    /// have length up to 4*len(restShapePoints) to allow for disjoint
    /// per-element rest shape description, or a more compact array when all
    /// tetrahedra share coincident points to describe the rest shape of the
    /// deformable body simulation tetmesh.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int4[] omniphysics:restTetVtxIndices` |
    /// | C++ Type | VtArray<GfVec4i> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Int4Array |
    UsdAttribute GetRestTetVtxIndicesAttr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsRestTetVtxIndices); }

    /// See GetRestTetVtxIndicesAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateRestTetVtxIndicesAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsRestTetVtxIndices,
                   SdfValueTypeNames->Int4Array, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
