// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file omniUsdPhysicsDeformableSchema/vtxTetAttachment.h
#ifndef OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSVTXTETATTACHMENT_API_H
#define OMNIUSDPHYSICSDEFORMABLESCHEMA_GENERATED_OMNIPHYSICSVTXTETATTACHMENT_API_H

#include "omniUsdPhysicsDeformableSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>
#include "omniUsdPhysicsDeformableSchema/attachment.h"

PXR_NAMESPACE_OPEN_SCOPE

/// \class OmniUsdPhysicsDeformableSchemaVtxTetAttachment
///
/// Describes a fixed binding attachment between vertices and
/// tetrahedra of two suitable deformable body simulation meshes.
/// The src1 relationship should point to a UsdGeomTetMesh.
///
class OmniUsdPhysicsDeformableSchemaVtxTetAttachment : public OmniUsdPhysicsDeformableSchemaAttachment
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::ConcreteTyped;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsVtxTetAttachment);
        return t;
    }

    /// Construct a OmniUsdPhysicsDeformableSchemaVtxTetAttachment on UsdPrim \p prim .
    /// Equivalent to OmniUsdPhysicsDeformableSchemaVtxTetAttachment::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit OmniUsdPhysicsDeformableSchemaVtxTetAttachment(const UsdPrim& prim=UsdPrim()) : OmniUsdPhysicsDeformableSchemaAttachment(prim) {}

    /// Construct a OmniUsdPhysicsDeformableSchemaVtxTetAttachment on the prim held by \p schemaObj .
    /// Should be preferred over OmniUsdPhysicsDeformableSchemaVtxTetAttachment(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit OmniUsdPhysicsDeformableSchemaVtxTetAttachment(const UsdSchemaBase& schemaObj) : OmniUsdPhysicsDeformableSchemaAttachment(schemaObj) {}

    /// Destructor.
    virtual ~OmniUsdPhysicsDeformableSchemaVtxTetAttachment() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsVtxIndicesSrc0,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsTetIndicesSrc1,
            OmniUsdPhysicsDeformableSchemaTokens->omniphysicsTetCoordsSrc1,
        };
        return localNames;
    }

    /// Return a OmniUsdPhysicsDeformableSchemaVtxTetAttachment holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// OmniUsdPhysicsDeformableSchemaVtxTetAttachment(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static OmniUsdPhysicsDeformableSchemaVtxTetAttachment Get(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaVtxTetAttachment(stage->GetPrimAtPath(path)); }

    /// Attempt to ensure a \a UsdPrim adhering to this schema at \p path
    /// is defined (according to UsdPrim::IsDefined()) on this stage.
    ///
    /// If a prim adhering to this schema at \p path is already defined on this
    /// stage, return that prim.  Otherwise author an \a SdfPrimSpec with
    /// \a specifier == \a SdfSpecifierDef and this schema's prim type name for
    /// the prim at \p path at the current EditTarget.  Author \a SdfPrimSpec s
    /// with \p specifier == \a SdfSpecifierDef and empty typeName at the
    /// current EditTarget for any nonexistent, or existing but not \a Defined
    /// ancestors.
    ///
    /// The given \a path must be an absolute prim path that does not contain
    /// any variant selections.
    ///
    /// If it is impossible to author any of the necessary PrimSpecs, (for
    /// example, in case \a path cannot map to the current UsdEditTarget's
    /// namespace) issue an error and return an invalid \a UsdPrim.
    ///
    /// Note that this method may return a defined prim whose typeName does not
    /// specify this schema class, in case a stronger typeName opinion overrides
    /// the opinion at the current EditTarget.
    static OmniUsdPhysicsDeformableSchemaVtxTetAttachment Define(const UsdStagePtr &stage, const SdfPath &path)
    { return OmniUsdPhysicsDeformableSchemaVtxTetAttachment(stage->DefinePrim(path, OmniUsdPhysicsDeformableSchemaTokens->OmniPhysicsVtxTetAttachment)); }

public:
    // --------------------------------------------------------------------- //
    // VTXINDICESSRC0
    // --------------------------------------------------------------------- //
    /// Array of vertex indices from UsdGeomPointBased src0
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int[] omniphysics:vtxIndicesSrc0` |
    /// | C++ Type | VtArray<int> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->IntArray |
    UsdAttribute GetVtxIndicesSrc0Attr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsVtxIndicesSrc0); }

    /// See GetVtxIndicesSrc0Attr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateVtxIndicesSrc0Attr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsVtxIndicesSrc0,
                   SdfValueTypeNames->IntArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // TETINDICESSRC1
    // --------------------------------------------------------------------- //
    /// Array of tetrahedron indices from UsdGeomTetMesh src1.
    /// There should be exactly one tet index for each vertex index in
    /// vtxIndicesSrc0.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int[] omniphysics:tetIndicesSrc1` |
    /// | C++ Type | VtArray<int> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->IntArray |
    UsdAttribute GetTetIndicesSrc1Attr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsTetIndicesSrc1); }

    /// See GetTetIndicesSrc1Attr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateTetIndicesSrc1Attr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsTetIndicesSrc1,
                   SdfValueTypeNames->IntArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // TETCOORDSSRC1
    // --------------------------------------------------------------------- //
    /// Barycentric coordinates of the form U,V,W of the point wrt.
    /// the points of the tetrahedra. There should be exactly one
    /// set of tetrahedra coordinates corresponding to each vertex index and
    /// tet index.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `vector3f[] omniphysics:tetCoordsSrc1` |
    /// | C++ Type | VtArray<GfVec3f> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Vector3fArray |
    UsdAttribute GetTetCoordsSrc1Attr() const
    { return GetPrim().GetAttribute(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsTetCoordsSrc1); }

    /// See GetTetCoordsSrc1Attr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateTetCoordsSrc1Attr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(OmniUsdPhysicsDeformableSchemaTokens->omniphysicsTetCoordsSrc1,
                   SdfValueTypeNames->Vector3fArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
