## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

SET(ARCHITECTURE_TRIPLE x86_64-unknown-windows-gnu)

SET(CMAKE_CROSSCOMPILING TRUE)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_LIBRARY_ARCHITECTURE ${ARCHITECTURE_TRIPLE})

SET(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
SET(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
SET(CMAKE_C_COMPILER_TARGET ${ARCHITECTURE_TRIPLE})
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
SET(CMAKE_CXX_COMPILER_TARGET ${ARCHITECTURE_TRIPLE})
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

