# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#

"""Unit tests for scripts/verify_schema_package.py.

What this file guards against
-----------------------------
ovphysx consumes a codeless "physics schema" package (`usd_ext_physics`): USD
plugin data (`plugInfo.json` as `Type=resource` + `generatedSchema.usda`) and
Python, with no native binary of any kind. Because it carries no compiled code
it is platform- and USD-ABI-independent.

verify_schema_package.py is the guardrail against a regression to the old
codefull layout: any native artifact reappearing, or a `plugInfo.json` still
declaring `Type=library` / a `LibraryPath`. Either would reintroduce the ABI
hazard the codeless migration removed.

What these tests verify
-----------------------
1. A clean codeless tree (valid resource plugin + generatedSchema) passes.
2. The generated `#` header is tolerated; a `//` line is rejected (PXR rejects
   it at RegisterPlugins() time, so the verifier must too).
3. Any native artifact anywhere in the tree is rejected (retired helper lib,
   Python binding, versioned soname).
4. Type=library / a LibraryPath is rejected.
5. A missing generatedSchema.usda is rejected.
6. A package with no valid resource plugin is rejected ({}, {"Plugins": []},
   includes-only aggregator, entries missing Name/Info/Info.Types, ResourcePath
   mismatch).
7. A tree with no schema plugInfo at all is rejected.
"""

import json
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parents[2] / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

import verify_schema_package as vsp  # noqa: E402


def _valid_plugin(module: str) -> dict:
    return {
        "Name": module,
        "Type": "resource",
        "Root": "..",
        "ResourcePath": "resources",
        "Info": {"Types": {f"{module}FooAPI": {"bases": ["UsdAPISchemaBase"]}}},
    }


def _make_tree(root: Path, *, module: str = "PhysxSchema", plugins=None,
               raw: str | None = None, with_generated: bool = True,
               header: str = "") -> Path:
    """Stage a schema tree under root and return root.

    `plugins` overrides the plugin list; `raw` writes the plugInfo body verbatim
    (for malformed cases); `header` is prepended (e.g. a '#' or '//' comment).
    """
    resources = root / "share" / "usd" / "plugins" / module / "resources"
    resources.mkdir(parents=True)
    if raw is not None:
        body = raw
    else:
        body = json.dumps({"Plugins": plugins if plugins is not None else [_valid_plugin(module)]})
    (resources / "plugInfo.json").write_text(header + body, encoding="utf-8")
    if with_generated:
        (resources / "generatedSchema.usda").write_text("#usda 1.0\n", encoding="utf-8")
    return root


def test_verify_passes_for_clean_codeless_tree(tmp_path):
    _make_tree(tmp_path)
    assert vsp.verify_schema_package(tmp_path) == []


def test_verify_tolerates_usd_hash_header(tmp_path):
    _make_tree(tmp_path, header="# Portions auto-generated by usdGenSchema.\n")
    assert vsp.verify_schema_package(tmp_path) == []


def test_verify_rejects_double_slash_comment(tmp_path):
    # PXR rejects '//' in plugInfo.json at RegisterPlugins() time, so the
    # verifier must not normalize it into valid input -- it should fail parse.
    errors = vsp.verify_schema_package(_make_tree(tmp_path, header="// note\n"))
    assert any("could not parse" in e for e in errors)


def test_verify_rejects_retired_native_helper_and_binding(tmp_path):
    _make_tree(tmp_path)
    (tmp_path / "lib").mkdir()
    (tmp_path / "lib" / "libphysicsSchemaTools.so").write_bytes(b"\x7fELF")
    binding = tmp_path / "lib" / "python" / "PhysicsSchemaTools"
    binding.mkdir(parents=True)
    (binding / "_physicsSchemaTools.so").write_bytes(b"\x7fELF")

    errors = vsp.verify_schema_package(tmp_path)
    assert any("libphysicsSchemaTools.so" in e for e in errors)
    assert any("_physicsSchemaTools.so" in e for e in errors)


def test_verify_rejects_versioned_soname_anywhere(tmp_path):
    _make_tree(tmp_path)
    (tmp_path / "lib").mkdir()
    (tmp_path / "lib" / "libfoo.so.1.2").write_bytes(b"\x7fELF")
    assert any("native artifact" in e for e in vsp.verify_schema_package(tmp_path))


def test_verify_rejects_windows_and_pyd_artifacts(tmp_path):
    _make_tree(tmp_path)
    (tmp_path / "lib").mkdir()
    (tmp_path / "lib" / "physxSchema.dll").write_bytes(b"MZ")
    (tmp_path / "lib" / "_physxSchema.pyd").write_bytes(b"MZ")
    errors = vsp.verify_schema_package(tmp_path)
    assert any("physxSchema.dll" in e for e in errors)
    assert any("_physxSchema.pyd" in e for e in errors)


def test_verify_rejects_type_library(tmp_path):
    plugin = {"Name": "m", "Type": "library", "LibraryPath": "../../libusd.so",
              "Root": "..", "ResourcePath": "resources", "Info": {"Types": {"x": {}}}}
    errors = vsp.verify_schema_package(_make_tree(tmp_path, plugins=[plugin]))
    assert any("expected 'resource'" in e for e in errors)


def test_verify_rejects_resource_plugin_with_library_path(tmp_path):
    plugin = _valid_plugin("PhysxSchema")
    plugin["LibraryPath"] = "../../libusd.so"
    errors = vsp.verify_schema_package(_make_tree(tmp_path, plugins=[plugin]))
    assert any("LibraryPath" in e for e in errors)


def test_verify_rejects_missing_generated_schema(tmp_path):
    errors = vsp.verify_schema_package(_make_tree(tmp_path, with_generated=False))
    assert any("generatedSchema.usda missing" in e for e in errors)


def test_verify_rejects_empty_plugin_object(tmp_path):
    errors = vsp.verify_schema_package(_make_tree(tmp_path, raw="{}"))
    assert any("no valid resource schema plugin" in e for e in errors)


def test_verify_rejects_empty_plugins_list(tmp_path):
    errors = vsp.verify_schema_package(_make_tree(tmp_path, raw=json.dumps({"Plugins": []})))
    assert any("no valid resource schema plugin" in e for e in errors)


def test_verify_rejects_includes_only_aggregator(tmp_path):
    errors = vsp.verify_schema_package(_make_tree(tmp_path, raw=json.dumps({"Includes": ["a/", "b/"]})))
    assert any("no valid resource schema plugin" in e for e in errors)


def test_verify_rejects_plugin_missing_info_types(tmp_path):
    plugin = {"Name": "m", "Type": "resource", "Root": "..", "ResourcePath": "resources"}
    errors = vsp.verify_schema_package(_make_tree(tmp_path, plugins=[plugin]))
    assert any("missing required metadata" in e for e in errors)


def test_verify_rejects_resource_path_mismatch(tmp_path):
    plugin = _valid_plugin("PhysxSchema")
    plugin["ResourcePath"] = "elsewhere"
    errors = vsp.verify_schema_package(_make_tree(tmp_path, plugins=[plugin]))
    assert any("ResourcePath" in e for e in errors)


def test_verify_rejects_tree_without_pluginfo(tmp_path):
    errors = vsp.verify_schema_package(tmp_path)
    assert any("no schema plugInfo.json" in e for e in errors)
