// Copyright (c) 2001-2004 NovodeX AG. All rights reserved.
// Copyright (c) 2004-2008 AGEIA Technologies, Inc. All rights reserved.
// SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#ifndef PXG_ARTICULATION_CORE_KERNEL_INDICES_H
#define PXG_ARTICULATION_CORE_KERNEL_INDICES_H

namespace physx
{

	struct PxgArticulationCoreKernelBlockDim
	{
		enum
		{
			COMPUTE_UNCONSTRAINED_VELOCITES = 64,
			UPDATE_BODIES = 128,
			SOLVE_INTERNAL_CONSTRAINTS = 32,
			COMPUTE_UNCONSTRAINED_SPATIAL_INERTIA = 32,
			COMPUTE_UNCONSTRAINED_SPATIAL_INERTIA_PARTIAL = 64,
			COMPUTE_STATIC_CONTACT_CONSTRAINT_COUNT = 512,
			APPLY_ARTI_STATE = 512,
			ARTI_GET_DOF_STATES = 512,
			ARTI_GET_TRANSFORM_STATES = 512,
			ARTI_GET_VELOCITY_STATES = 480,
			ARTI_GET_SPATIAL_FORCE_STATES = 512,
			ARTI_GET_LINK_FORCE_STATE = 512,
			ARTI_GET_LINK_TORQUE_STATE = 512,
			ARTI_GET_TENDON_STATE = 512,
			ARTI_GET_SPATIAL_TENDON_ATTACHMENT_STATE = 512,
			ARTI_GET_FIXED_TENDON_JOINT_STATE = 512,
			ARTI_SET_DOF_STATES = 512,
			ARTI_SET_ROOT_GLOBAL_POSE_STATE = 512,
			ARTI_SET_ROOT_VELOCITY_STATE = 480,
			ARTI_SET_LINK_FORCE_STATE = 480,
			ARTI_SET_LINK_TORQUE_STATE = 512,
			ARTI_SET_TENDON_STATE = 512,
			ARTI_SET_SPATIAL_TENDON_ATTACHMENT_STATE = 512,
			ARTI_SET_FIXED_TENDON_JOINT_STATE = 512
		};
	};

	struct PxgArticulationCoreKernelGridDim
	{
		enum
		{
			COMPUTE_UNCONSTRAINED_VELOCITES = 64,
			UPDATE_BODIES = 64,
			UPDATE_KINEMATIC = 1024 // AD: see inline comment in PxgArticulationCore
		};
	};

}

#endif
