## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXTask common
#

SET(PHYSX_SOURCE_DIR ${PHYSX_ROOT_DIR}/source)
SET(LL_SOURCE_DIR ${PHYSX_SOURCE_DIR}/task)

# Include here after the directories are defined so that the platform specific file can use the variables.
include(${PHYSX_ROOT_DIR}/${PROJECT_CMAKE_FILES_DIR}/${TARGET_BUILD_PLATFORM}/PhysXTask.cmake)

SET(PHYSXTASK_HEADERS
	${PHYSX_ROOT_DIR}/include/task/PxCpuDispatcher.h
	${PHYSX_ROOT_DIR}/include/task/PxTask.h
	${PHYSX_ROOT_DIR}/include/task/PxTaskManager.h
)
SOURCE_GROUP(include FILES ${PHYSXTASK_HEADERS})

SET(PHYSXTASK_SOURCE
	${LL_SOURCE_DIR}/src/TaskManager.cpp
)
SOURCE_GROUP(src FILES ${PHYSXTASK_SOURCE})

ADD_LIBRARY(PhysXTask ${PHYSXTASK_LIBTYPE}
	${PHYSXTASK_HEADERS}
	${PHYSXTASK_SOURCE}
)

IF(NOT DEFINED PX_ENABLE_INSTALL OR PX_ENABLE_INSTALL)
	INSTALL(FILES ${PHYSXTASK_HEADERS} DESTINATION include/task)
ENDIF()

GET_TARGET_PROPERTY(PHYSXFOUNDATION_INCLUDES PhysXFoundation INTERFACE_INCLUDE_DIRECTORIES)

TARGET_INCLUDE_DIRECTORIES(PhysXTask 
	PRIVATE ${PHYSXTASK_PLATFORM_INCLUDES}
	
	PRIVATE ${PHYSXFOUNDATION_INCLUDES}
	
	PRIVATE ${PHYSX_ROOT_DIR}/include
	PRIVATE ${PHYSX_SOURCE_DIR}/cudamanager/include
)

TARGET_COMPILE_DEFINITIONS(PhysXTask 
	PRIVATE ${PHYSXTASK_COMPILE_DEFS}
)

SET_TARGET_PROPERTIES(PhysXTask PROPERTIES
	OUTPUT_NAME PhysXTask
)

IF(PHYSXTASK_LIBTYPE STREQUAL "STATIC")
	SET_TARGET_PROPERTIES(PhysXTask PROPERTIES 
		ARCHIVE_OUTPUT_NAME_DEBUG "PhysXTask_static"
		ARCHIVE_OUTPUT_NAME_CHECKED "PhysXTask_static"
		ARCHIVE_OUTPUT_NAME_PROFILE "PhysXTask_static"
		ARCHIVE_OUTPUT_NAME_RELEASE "PhysXTask_static"	
	)
ENDIF()

IF(PT_COMPILE_PDB_NAME_DEBUG)	
	SET_TARGET_PROPERTIES(PhysXTask PROPERTIES 
		COMPILE_PDB_NAME_DEBUG "${PT_COMPILE_PDB_NAME_DEBUG}"
		COMPILE_PDB_NAME_CHECKED "${PT_COMPILE_PDB_NAME_CHECKED}"
		COMPILE_PDB_NAME_PROFILE "${PT_COMPILE_PDB_NAME_PROFILE}"
		COMPILE_PDB_NAME_RELEASE "${PT_COMPILE_PDB_NAME_RELEASE}"
	)
ENDIF()

IF(PX_EXPORT_LOWLEVEL_PDB)
	SET_TARGET_PROPERTIES(PhysXTask PROPERTIES 
		COMPILE_PDB_OUTPUT_DIRECTORY_DEBUG "${PHYSX_ROOT_DIR}/${PX_ROOT_LIB_DIR}/debug/"
		COMPILE_PDB_OUTPUT_DIRECTORY_CHECKED "${PHYSX_ROOT_DIR}/${PX_ROOT_LIB_DIR}/checked/"
		COMPILE_PDB_OUTPUT_DIRECTORY_PROFILE "${PHYSX_ROOT_DIR}/${PX_ROOT_LIB_DIR}/profile/"
		COMPILE_PDB_OUTPUT_DIRECTORY_RELEASE "${PHYSX_ROOT_DIR}/${PX_ROOT_LIB_DIR}/release/"
	)
ENDIF()

IF(PX_GENERATE_SOURCE_DISTRO)		
	LIST(APPEND SOURCE_DISTRO_FILE_LIST ${PHYSXTASK_HEADERS})
	LIST(APPEND SOURCE_DISTRO_FILE_LIST ${PHYSXTASK_SOURCE})
ENDIF()

# enable -fPIC so we can link static libs with the editor
SET_TARGET_PROPERTIES(PhysXTask PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
