## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXPvdSDK
#

SOURCE_GROUP(resource FILES ${PHYSXPVDSDK_RESOURCE_FILE})

SOURCE_GROUP(include\\windows FILES ${PHYSXPVDSDK_PLATFORM_HEADERS})

SOURCE_GROUP(src\\src\\windows FILES ${PHYSXPVDSDK_PLATFORM_SOURCE})

SET(PHYSXPVDSDK_PLATFORM_FILES
	${PHYSXPVDSDK_RESOURCE_FILE}
	${PHYSXPVDSDK_PLATFORM_HEADERS}
	${PHYSXPVDSDK_PLATFORM_SOURCE}
)

IF (PX_GENERATE_GPU_PROJECTS AND PX_USE_NVTX)
	SET(PHYSXPVDSDK_PLATFORM_INCLUDES
		${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}
	)
ENDIF()

SET(PHYSXPVDSDK_LIBTYPE STATIC)

SET(PHYSXPVDSDK_PLATFORM_LINKED_LIBS)

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXPVDSDK_COMPILE_DEFS
	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSX_LIBTYPE_DEFS};${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(PHYSXPVDSDK_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_DEBUG "PhysXPvdSDK_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_CHECKED "PhysXPvdSDK_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_PROFILE "PhysXPvdSDK_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_RELEASE "PhysXPvdSDK_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_DEBUG "PhysXPvdSDK${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_CHECKED "PhysXPvdSDK${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_PROFILE "PhysXPvdSDK${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXPVDSDK_COMPILE_PDB_NAME_RELEASE "PhysXPvdSDK${CMAKE_RELEASE_POSTFIX}")
ENDIF()

IF(PHYSXPVDSDK_LIBTYPE STREQUAL "SHARED")
	INSTALL(FILES $<TARGET_PDB_FILE:PhysXPvdSDK> 
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ELSE()	
	INSTALL(FILES ${PHYSX_ROOT_DIR}/$<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile>/$<$<CONFIG:debug>:${PHYSXPVDSDK_COMPILE_PDB_NAME_DEBUG}>$<$<CONFIG:checked>:${PHYSXPVDSDK_COMPILE_PDB_NAME_CHECKED}>$<$<CONFIG:profile>:${PHYSXPVDSDK_COMPILE_PDB_NAME_PROFILE}>$<$<CONFIG:release>:${PHYSXPVDSDK_COMPILE_PDB_NAME_RELEASE}>.pdb
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ENDIF()


