## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXVehicle
#

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXVEHICLE_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSX_LIBTYPE_DEFS};${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

SET(PHYSXVEHICLE_LIBTYPE STATIC)

IF(PHYSXVEHICLE_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_DEBUG "PhysXVehicle_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_CHECKED "PhysXVehicle_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_PROFILE "PhysXVehicle_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_RELEASE "PhysXVehicle_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_DEBUG "PhysXVehicle${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_CHECKED "PhysXVehicle${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_PROFILE "PhysXVehicle${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXVEHICLE_COMPILE_PDB_NAME_RELEASE "PhysXVehicle${CMAKE_RELEASE_POSTFIX}")
ENDIF()

IF(PHYSXVEHICLE_LIBTYPE STREQUAL "SHARED")
	INSTALL(FILES $<TARGET_PDB_FILE:PhysXVehicle> 
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ELSE()	
	INSTALL(FILES ${PHYSX_ROOT_DIR}/$<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile>/$<$<CONFIG:debug>:${PHYSXVEHICLE_COMPILE_PDB_NAME_DEBUG}>$<$<CONFIG:checked>:${PHYSXVEHICLE_COMPILE_PDB_NAME_CHECKED}>$<$<CONFIG:profile>:${PHYSXVEHICLE_COMPILE_PDB_NAME_PROFILE}>$<$<CONFIG:release>:${PHYSXVEHICLE_COMPILE_PDB_NAME_RELEASE}>.pdb
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ENDIF()
