## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXExtensions
#


SET(PHYSXEXTENSIONS_PLATFORM_INCLUDES
	PRIVATE ${PHYSX_SOURCE_DIR}/Common/src/windows
)

SET(PHYSXEXTENSIONS_PLATFORM_SRC_FILES
	${PHYSXEXTENSIONS_PLATFORM_OBJECT_FILES}
)

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXEXTENSIONS_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};${PHYSX_LIBTYPE_DEFS};${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

SET(PHYSXEXTENSIONS_PRIVATE_PLATFORM_LINKED_LIBS

)

SET(PHYSXEXTENSIONS_LIBTYPE STATIC)

IF(PHYSXEXTENSIONS_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_DEBUG "PhysXExtensions_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_CHECKED "PhysXExtensions_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_PROFILE "PhysXExtensions_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_RELEASE "PhysXExtensions_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_DEBUG "PhysXExtensions${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_CHECKED "PhysXExtensions${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_PROFILE "PhysXExtensions${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXEXTENSIONS_COMPILE_PDB_NAME_RELEASE "PhysXExtensions${CMAKE_RELEASE_POSTFIX}")
ENDIF()

IF(PHYSXEXTENSIONS_LIBTYPE STREQUAL "SHARED")
	INSTALL(FILES $<TARGET_PDB_FILE:PhysXExtensions> 
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ELSE()	
	INSTALL(FILES ${PHYSX_ROOT_DIR}/$<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile>/$<$<CONFIG:debug>:${PHYSXEXTENSIONS_COMPILE_PDB_NAME_DEBUG}>$<$<CONFIG:checked>:${PHYSXEXTENSIONS_COMPILE_PDB_NAME_CHECKED}>$<$<CONFIG:profile>:${PHYSXEXTENSIONS_COMPILE_PDB_NAME_PROFILE}>$<$<CONFIG:release>:${PHYSXEXTENSIONS_COMPILE_PDB_NAME_RELEASE}>.pdb
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ENDIF()
