// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxPhysicsGearJoint.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXPHYSICSGEARJOINT_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXPHYSICSGEARJOINT_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>
#include <pxr/usd/usdPhysics/joint.h>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxPhysicsGearJoint
///
/// A gear joint connects two existing revolute (a.k.a. hinge) joints and constrains the angular velocities of involved rigid bodies. If omega0 is the angular velocity of the first rigid body around the PhysicsRevoluteJoint axis, omega1 is the angular velocity of the second rigid body around the PhysicsRevoluteJoint axis, and R is the gear ratio, then the enforced constraint is abs(omega1) = abs(omega0) * R. The equation is valid for the absolute values of angular velocities. The angular velocities may otherwise have opposite signs, depending on the orientations of the joint frames. Gear joints can be used with GPU simulation but in that case these specific joints will run through the CPU pipeline. If a gear joint is created between articulation revolute joints, excludeFromArticulation must be set to true for the gear joint itself, otherwise an error occurs. To include the gear joint in the articulation itself, please use PhysxMimicJointAPI instead to implement a gear joint. A known limitation is that current implementation does not work for planetary gears.
///
class PhysxSchemaPhysxPhysicsGearJoint : public UsdPhysicsJoint
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::ConcreteTyped;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxPhysicsGearJoint);
        return t;
    }

    /// Construct a PhysxSchemaPhysxPhysicsGearJoint on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxPhysicsGearJoint::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxPhysicsGearJoint(const UsdPrim& prim=UsdPrim()) : UsdPhysicsJoint(prim) {}

    /// Construct a PhysxSchemaPhysxPhysicsGearJoint on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxPhysicsGearJoint(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxPhysicsGearJoint(const UsdSchemaBase& schemaObj) : UsdPhysicsJoint(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxPhysicsGearJoint() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physicsGearRatio,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxPhysicsGearJoint holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxPhysicsGearJoint(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxPhysicsGearJoint Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxPhysicsGearJoint(stage->GetPrimAtPath(path)); }

    /// Attempt to ensure a \a UsdPrim adhering to this schema at \p path
    /// is defined (according to UsdPrim::IsDefined()) on this stage.
    ///
    /// If a prim adhering to this schema at \p path is already defined on this
    /// stage, return that prim.  Otherwise author an \a SdfPrimSpec with
    /// \a specifier == \a SdfSpecifierDef and this schema's prim type name for
    /// the prim at \p path at the current EditTarget.  Author \a SdfPrimSpec s
    /// with \p specifier == \a SdfSpecifierDef and empty typeName at the
    /// current EditTarget for any nonexistent, or existing but not \a Defined
    /// ancestors.
    ///
    /// The given \a path must be an absolute prim path that does not contain
    /// any variant selections.
    ///
    /// If it is impossible to author any of the necessary PrimSpecs, (for
    /// example, in case \a path cannot map to the current UsdEditTarget's
    /// namespace) issue an error and return an invalid \a UsdPrim.
    ///
    /// Note that this method may return a defined prim whose typeName does not
    /// specify this schema class, in case a stronger typeName opinion overrides
    /// the opinion at the current EditTarget.
    static PhysxSchemaPhysxPhysicsGearJoint Define(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxPhysicsGearJoint(stage->DefinePrim(path, PhysxSchemaTokens->PhysxPhysicsGearJoint)); }

public:
    // --------------------------------------------------------------------- //
    // GEARRATIO
    // --------------------------------------------------------------------- //
    /// Gear ratio. For two gears with N0 and N1 teeth respectively, the gear ratio should be N0/N1.
    /// Range: (-inf, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physics:gearRatio = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetGearRatioAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physicsGearRatio); }

    /// See GetGearRatioAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateGearRatioAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physicsGearRatio,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // HINGE0
    // --------------------------------------------------------------------- //
    /// Relationship to first hinge joint. It should be a PhysicsRevoluteJoint. It is mandatory to define one (and only one) relationship here.
    UsdRelationship GetHinge0Rel() const
    { return GetPrim().GetRelationship(PhysxSchemaTokens->physicsHinge0); }

    /// See GetHinge0Rel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateHinge0Rel() const
    { return GetPrim().CreateRelationship(PhysxSchemaTokens->physicsHinge0, /* custom = */ false); }

public:
    // --------------------------------------------------------------------- //
    // HINGE1
    // --------------------------------------------------------------------- //
    /// Relationship to second hinge joint. It should be a PhysicsRevoluteJoint. It is mandatory to define one (and only one) relationship here.
    UsdRelationship GetHinge1Rel() const
    { return GetPrim().GetRelationship(PhysxSchemaTokens->physicsHinge1); }

    /// See GetHinge1Rel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateHinge1Rel() const
    { return GetPrim().CreateRelationship(PhysxSchemaTokens->physicsHinge1, /* custom = */ false); }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
