// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxTendonAxisRootAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXTENDONAXISROOTAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXTENDONAXISROOTAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxTendonAxisRootAPI
///
/// WARNING: Draft API, this design is not fixed and may change in the future. At this point, we don't support
/// multi-axis joints (e.g. spherical, D6) yet.
///
/// Applied to a Physics Joint that must be part of an articulation, e.g. PhysicsRevoluteJoint or PhysicsPrismaticJoint.
///
/// In addition to creating a regular axis of the fixed tendon, the root API provides attributes that apply to the
/// entire tendon. The root API must be applied to the joint that is the common ancestor of all joint axes in the tendon.
///
/// For restrictions on tendon structure and grouping of axes into tendons, see PhysxTendonAxisAPI.
///
class PhysxSchemaPhysxTendonAxisRootAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::MultipleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxTendonAxisRootAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxTendonAxisRootAPI on UsdPrim \p prim with
    /// name \p name . Equivalent to
    /// PhysxSchemaPhysxTendonAxisRootAPI::Get(
    ///    prim.GetStage(),
    ///    prim.GetPath().AppendProperty(
    ///        "physxTendon:name"));
    ///
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxTendonAxisRootAPI(const UsdPrim& prim=UsdPrim(), const TfToken &name=TfToken())
        : UsdAPISchemaBase(prim, name) {}

    /// Construct a PhysxSchemaPhysxTendonAxisRootAPI on the prim held by \p schemaObj with
    /// name \p name.  Should be preferred over
    /// PhysxSchemaPhysxTendonAxisRootAPI(schemaObj.GetPrim(), name), as it preserves
    /// SchemaBase state.
    explicit PhysxSchemaPhysxTendonAxisRootAPI(const UsdSchemaBase& schemaObj, const TfToken &name)
        : UsdAPISchemaBase(schemaObj, name) {}

    /// Returns the name of this multiple-apply schema instance
    TfToken GetName() const { return _GetInstanceName(); }

    /// Destructor.
    virtual ~PhysxSchemaPhysxTendonAxisRootAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Stiffness,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Damping,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LimitStiffness,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Offset,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_RestLength,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LowerLimit,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_UpperLimit,
            PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_TendonEnabled,
        };
        return localNames;
    }

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes for a given instance name.  Does not
    /// include attributes that may be authored by custom/extended methods of
    /// the schemas involved. The names returned will have the proper namespace
    /// prefix.
    static TfTokenVector GetSchemaAttributeNames(bool includeInherited, const TfToken &instanceName)
    {
        const TfTokenVector &attrNames = GetSchemaAttributeNames(includeInherited);
        if (instanceName.IsEmpty()) {
            return attrNames;
        }
        TfTokenVector result;
        result.reserve(attrNames.size());
        for (const TfToken &attrName : attrNames) {
            result.push_back(UsdSchemaRegistry::MakeMultipleApplyNameInstance(attrName, instanceName));
        }
        return result;
    }

    /// Checks if the given name \p baseName is the base name of a property
    /// of PhysxTendonAxisRootAPI.
    static bool IsSchemaPropertyBaseName(const TfToken &baseName)
    {
        static TfTokenVector attrsAndRels = {
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Stiffness),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Damping),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LimitStiffness),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Offset),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_RestLength),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LowerLimit),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_UpperLimit),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_TendonEnabled),
        };
        return std::find(attrsAndRels.begin(), attrsAndRels.end(), baseName) != attrsAndRels.end();
    }

    /// Checks if the given path \p path is of an API schema of type
    /// PhysxTendonAxisRootAPI. If so, it stores the instance name of
    /// the schema in \p name and returns true. Otherwise, it returns false.
    static bool IsPhysxTendonAxisRootAPIPath(const SdfPath &path, TfToken *name)
    {
        if (!path.IsPropertyPath()) {
            return false;
        }
        const std::string propertyName = path.GetName();
        const TfTokenVector tokens = SdfPath::TokenizeIdentifierAsTokens(propertyName);
        if (tokens.empty()) {
            return false;
        }
        const TfToken &baseName = *tokens.rbegin();
        if (IsSchemaPropertyBaseName(baseName)) {
            return false;
        }
        if (tokens.size() >= 2
            && tokens[0] == PhysxSchemaTokens->physxTendon) {
            if (name) {
                *name = TfToken(propertyName.substr(PhysxSchemaTokens->physxTendon.GetString().size() + 1));
            }
            return true;
        }
        return false;
    }

    /// Return a PhysxSchemaPhysxTendonAxisRootAPI with name \p name holding the
    /// prim \p prim. Shorthand for PhysxSchemaPhysxTendonAxisRootAPI(prim, name);
    static PhysxSchemaPhysxTendonAxisRootAPI Get(const UsdPrim &prim, const TfToken &name)
    { return PhysxSchemaPhysxTendonAxisRootAPI(prim, name); }

    /// Return a PhysxSchemaPhysxTendonAxisRootAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  \p path must be of the format
    /// <path>.physxTendon:name .
    ///
    /// This is shorthand for the following:
    ///
    /// \code
    /// TfToken name = SdfPath::StripNamespace(path.GetToken());
    /// PhysxSchemaPhysxTendonAxisRootAPI(
    ///     stage->GetPrimAtPath(path.GetPrimPath()), name);
    /// \endcode
    ///
    static PhysxSchemaPhysxTendonAxisRootAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    {
        if (!stage) {
            return PhysxSchemaPhysxTendonAxisRootAPI();
        }
        TfToken name;
        if (!IsPhysxTendonAxisRootAPIPath(path, &name)) {
            return PhysxSchemaPhysxTendonAxisRootAPI();
        }
        return PhysxSchemaPhysxTendonAxisRootAPI(stage->GetPrimAtPath(path.GetPrimPath()), name);
    }

    /// Return a vector of all named instances of PhysxSchemaPhysxTendonAxisRootAPI on the
    /// given \p prim.
    static std::vector<PhysxSchemaPhysxTendonAxisRootAPI> GetAll(const UsdPrim &prim)
    {
        std::vector<PhysxSchemaPhysxTendonAxisRootAPI> schemas;
        const TfType &type = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxTendonAxisRootAPI);
        for (const auto &n : _GetMultipleApplyInstanceNames(prim, type)) {
            schemas.emplace_back(prim, n);
        }
        return schemas;
    }

    /// Returns true if this <b>multiple-apply</b> API schema can be applied,
    /// with the given instance name, \p name, to the given \p prim. If this
    /// schema can not be a applied the prim, this returns false and, if
    /// provided, populates \p whyNot with the reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, const TfToken &name, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxTendonAxisRootAPI, name, whyNot); }

    /// Applies this <b>multiple-apply</b> API schema to the given \p prim
    /// along with the given instance name, \p name.
    ///
    /// This information is stored by adding "PhysxTendonAxisRootAPI:<i>name</i>"
    /// to the token-valued, listOp metadata \em apiSchemas on the prim.
    /// For example, if \p name is 'instance1', the token
    /// 'PhysxTendonAxisRootAPI:instance1' is added to 'apiSchemas'.
    ///
    /// \return A valid PhysxSchemaPhysxTendonAxisRootAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxTendonAxisRootAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for
    /// conditions resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxTendonAxisRootAPI Apply(const UsdPrim &prim, const TfToken &name)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxTendonAxisRootAPI, name)) { return PhysxSchemaPhysxTendonAxisRootAPI(prim, name); }
        return PhysxSchemaPhysxTendonAxisRootAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // STIFFNESS
    // --------------------------------------------------------------------- //
    /// Tendon length spring stiffness.
    /// Range: [0, inf)
    /// Units: force / distance = mass / time / time
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float stiffness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetStiffnessAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Stiffness, _GetInstanceName())); }

    /// See GetStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Stiffness, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // DAMPING
    // --------------------------------------------------------------------- //
    /// Tendon length damping.
    /// Range: [0, inf)
    /// Units: force / distance * time = mass / time
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float damping = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDampingAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Damping, _GetInstanceName())); }

    /// See GetDampingAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDampingAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Damping, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // LIMITSTIFFNESS
    // --------------------------------------------------------------------- //
    /// Tendon length-limit spring stiffness.
    /// Range: [0, inf)
    /// Units: force / distance = mass / time / time
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float limitStiffness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetLimitStiffnessAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LimitStiffness, _GetInstanceName())); }

    /// See GetLimitStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateLimitStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LimitStiffness, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // OFFSET
    // --------------------------------------------------------------------- //
    /// Tendon length offset.
    /// Range: (-inf, inf)
    /// Units: distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float offset = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetOffsetAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Offset, _GetInstanceName())); }

    /// See GetOffsetAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateOffsetAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_Offset, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // RESTLENGTH
    // --------------------------------------------------------------------- //
    /// Tendon rest length.
    /// Range: (-inf, inf)
    /// Units: distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float restLength = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetRestLengthAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_RestLength, _GetInstanceName())); }

    /// See GetRestLengthAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateRestLengthAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_RestLength, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // LOWERLIMIT
    // --------------------------------------------------------------------- //
    /// Tendon length lower limit.
    /// Range: (-inf, upperLimit].
    /// Units: distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float lowerLimit = -inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetLowerLimitAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LowerLimit, _GetInstanceName())); }

    /// See GetLowerLimitAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateLowerLimitAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_LowerLimit, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // UPPERLIMIT
    // --------------------------------------------------------------------- //
    /// Tendon length upper limit.
    /// Range: [lowerLimit, inf)
    /// Units: distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float upperLimit = inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetUpperLimitAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_UpperLimit, _GetInstanceName())); }

    /// See GetUpperLimitAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateUpperLimitAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_UpperLimit, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // TENDONENABLED
    // --------------------------------------------------------------------- //
    /// Enables/disables the tendon from contributing to the articulation dynamics.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool tendonEnabled = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetTendonEnabledAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_TendonEnabled, _GetInstanceName())); }

    /// See GetTendonEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateTendonEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxTendon_MultipleApplyTemplate_TendonEnabled, _GetInstanceName()),
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
