// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxVehicleSuspensionAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXVEHICLESUSPENSIONAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXVEHICLESUSPENSIONAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxVehicleSuspensionAPI
///
/// Properties of a PhysX vehicle wheel suspension. If the suspension setup does not need to be shared
/// among vehicle instances, it can be applied to the prim which has PhysxVehicleWheelAttachmentAPI
/// applied. If the intent is to share the suspension setup, PhysxVehicleSuspensionAPI can be
/// applied to a separate prim which can be linked to (see PhysxVehicleWheelAttachmentAPI).
///
class PhysxSchemaPhysxVehicleSuspensionAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxVehicleSuspensionAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxVehicleSuspensionAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxVehicleSuspensionAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxVehicleSuspensionAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxVehicleSuspensionAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxVehicleSuspensionAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxVehicleSuspensionAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxVehicleSuspensionAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxVehicleSuspensionSpringStrength,
            PhysxSchemaTokens->physxVehicleSuspensionSpringDamperRate,
            PhysxSchemaTokens->physxVehicleSuspensionTravelDistance,
            PhysxSchemaTokens->physxVehicleSuspensionMaxCompression,
            PhysxSchemaTokens->physxVehicleSuspensionMaxDroop,
            PhysxSchemaTokens->physxVehicleSuspensionSprungMass,
            PhysxSchemaTokens->physxVehicleSuspensionCamberAtRest,
            PhysxSchemaTokens->physxVehicleSuspensionCamberAtMaxCompression,
            PhysxSchemaTokens->physxVehicleSuspensionCamberAtMaxDroop,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxVehicleSuspensionAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxVehicleSuspensionAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxVehicleSuspensionAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxVehicleSuspensionAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxVehicleSuspensionAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxVehicleSuspensionAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxVehicleSuspensionAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxVehicleSuspensionAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxVehicleSuspensionAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxVehicleSuspensionAPI)) { return PhysxSchemaPhysxVehicleSuspensionAPI(prim); }
        return PhysxSchemaPhysxVehicleSuspensionAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // SPRINGSTRENGTH
    // --------------------------------------------------------------------- //
    /// Spring strength of suspension unit.
    ///
    /// Units: force / distance = mass / seconds / seconds
    ///
    /// Note: this attribute has to be specified (there is no default).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:springStrength` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSpringStrengthAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionSpringStrength); }

    /// See GetSpringStrengthAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSpringStrengthAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionSpringStrength,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SPRINGDAMPERRATE
    // --------------------------------------------------------------------- //
    /// Spring damper rate of suspension unit.
    ///
    /// Units: force * seconds / distance = mass / seconds
    ///
    /// Note: this attribute has to be specified (there is no default).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:springDamperRate` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSpringDamperRateAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionSpringDamperRate); }

    /// See GetSpringDamperRateAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSpringDamperRateAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionSpringDamperRate,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // TRAVELDISTANCE
    // --------------------------------------------------------------------- //
    /// Distance the wheel can travel along the suspension when going from max compression to
    /// max droop. The value has to be positive.
    ///
    /// Units: distance
    ///
    /// Note: either this attribute or the deprecated maxCompression/maxDroop have to
    /// to be specified (with the former taking precedence). When migrating from the
    /// deprecated attributes, travelDistance can be set to the sum of maxCompression
    /// and maxDroop.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:travelDistance` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetTravelDistanceAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionTravelDistance); }

    /// See GetTravelDistanceAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateTravelDistanceAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionTravelDistance,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MAXCOMPRESSION
    // --------------------------------------------------------------------- //
    /// Deprecated. Please use travelDistance instead.
    ///
    /// Maximum compression from rest state allowed by suspension spring.
    /// The value has to be positive.
    ///
    /// Units: distance
    ///
    /// Note: will be ignored if travelDistance is authored.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:maxCompression` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxCompressionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionMaxCompression); }

    /// See GetMaxCompressionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxCompressionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionMaxCompression,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MAXDROOP
    // --------------------------------------------------------------------- //
    /// Deprecated. Please use travelDistance instead.
    ///
    /// Maximum elongation from rest state allowed by suspension spring.
    /// The value has to be positive unless it should get computed automatically in which case any
    /// negative number can be used to indicate as much. It is highly recommended to chose a value
    /// close to: sprungMass * gravity / springStrength.
    ///
    /// Units: distance
    ///
    /// Note: will be ignored if travelDistance is authored.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:maxDroop` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxDroopAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionMaxDroop); }

    /// See GetMaxDroopAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxDroopAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionMaxDroop,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SPRUNGMASS
    // --------------------------------------------------------------------- //
    /// Mass of vehicle that is supported by suspension spring.
    /// If set to 0, the sprung mass will get computed automatically.
    ///
    /// Units: mass
    ///
    /// Note: it is not possible for a vehicle to have some sprung mass values being user-defined and some
    /// being computed automatically. Either all values have to be user-defined or all have to be set to 0
    /// for auto-computation.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:sprungMass = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSprungMassAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionSprungMass); }

    /// See GetSprungMassAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSprungMassAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionSprungMass,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // CAMBERATREST
    // --------------------------------------------------------------------- //
    /// Deprecated. Please use PhysxVehicleSuspensionComplianceAPI instead.
    ///
    /// Camber angle (in radians) of wheel when the suspension is at its rest position.
    ///
    /// Note: will be ignored if PhysxVehicleSuspensionComplianceAPI is used.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:camberAtRest` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetCamberAtRestAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionCamberAtRest); }

    /// See GetCamberAtRestAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateCamberAtRestAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionCamberAtRest,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // CAMBERATMAXCOMPRESSION
    // --------------------------------------------------------------------- //
    /// Deprecated. Please use PhysxVehicleSuspensionComplianceAPI instead.
    ///
    /// Camber angle (in radians) of wheel when the suspension is at maximum compression.
    ///
    /// Note: will be ignored if PhysxVehicleSuspensionComplianceAPI is used.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:camberAtMaxCompression` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetCamberAtMaxCompressionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionCamberAtMaxCompression); }

    /// See GetCamberAtMaxCompressionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateCamberAtMaxCompressionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionCamberAtMaxCompression,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // CAMBERATMAXDROOP
    // --------------------------------------------------------------------- //
    /// Deprecated. Please use PhysxVehicleSuspensionComplianceAPI instead.
    ///
    /// Camber angle (in radians) of wheel when the suspension is at maximum droop.
    ///
    /// Note: will be ignored if PhysxVehicleSuspensionComplianceAPI is used.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSuspension:camberAtMaxDroop` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetCamberAtMaxDroopAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSuspensionCamberAtMaxDroop); }

    /// See GetCamberAtMaxDroopAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateCamberAtMaxDroopAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSuspensionCamberAtMaxDroop,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
