// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxPhysicsRackAndPinionJoint.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXPHYSICSRACKANDPINIONJOINT_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXPHYSICSRACKANDPINIONJOINT_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>
#include <pxr/usd/usdPhysics/joint.h>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxPhysicsRackAndPinionJoint
///
/// A rack-and-pinion joint connects an existing revolute/hinge joint to an existing prismatic joint, and constrains the angular and linear velocities of involved rigid bodies. If omega is the angular velocity of the pinion rigid body around the PhysicsRevoluteJoint axis, V is the linear velocity of the rack rigid body along the PhysicsPrismaticJoint axis, and R is the ratio, then the enforced constraint is abs(omega) = abs(V) * R. The equation is valid for the absolute values of velocities. The velocities may otherwise have opposite signs, depending on the orientations of the joint frames. Rack-and-pinion joints can be used with GPU simulation but in that case these specific joints will run through the CPU pipeline. If a rack-and-pinion joint is created between articulation joints, excludeFromArticulation must be set to true for the rack-and-pinion joint itself, otherwise an error occurs. To include the rack-and-pinion joint in the articulation itself, please use PhysxMimicJointAPI instead to implement a rack-and-pinion joint.
///
class PhysxSchemaPhysxPhysicsRackAndPinionJoint : public UsdPhysicsJoint
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::ConcreteTyped;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxPhysicsRackAndPinionJoint);
        return t;
    }

    /// Construct a PhysxSchemaPhysxPhysicsRackAndPinionJoint on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxPhysicsRackAndPinionJoint::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxPhysicsRackAndPinionJoint(const UsdPrim& prim=UsdPrim()) : UsdPhysicsJoint(prim) {}

    /// Construct a PhysxSchemaPhysxPhysicsRackAndPinionJoint on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxPhysicsRackAndPinionJoint(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxPhysicsRackAndPinionJoint(const UsdSchemaBase& schemaObj) : UsdPhysicsJoint(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxPhysicsRackAndPinionJoint() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physicsRatio,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxPhysicsRackAndPinionJoint holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxPhysicsRackAndPinionJoint(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxPhysicsRackAndPinionJoint Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxPhysicsRackAndPinionJoint(stage->GetPrimAtPath(path)); }

    /// Attempt to ensure a \a UsdPrim adhering to this schema at \p path
    /// is defined (according to UsdPrim::IsDefined()) on this stage.
    ///
    /// If a prim adhering to this schema at \p path is already defined on this
    /// stage, return that prim.  Otherwise author an \a SdfPrimSpec with
    /// \a specifier == \a SdfSpecifierDef and this schema's prim type name for
    /// the prim at \p path at the current EditTarget.  Author \a SdfPrimSpec s
    /// with \p specifier == \a SdfSpecifierDef and empty typeName at the
    /// current EditTarget for any nonexistent, or existing but not \a Defined
    /// ancestors.
    ///
    /// The given \a path must be an absolute prim path that does not contain
    /// any variant selections.
    ///
    /// If it is impossible to author any of the necessary PrimSpecs, (for
    /// example, in case \a path cannot map to the current UsdEditTarget's
    /// namespace) issue an error and return an invalid \a UsdPrim.
    ///
    /// Note that this method may return a defined prim whose typeName does not
    /// specify this schema class, in case a stronger typeName opinion overrides
    /// the opinion at the current EditTarget.
    static PhysxSchemaPhysxPhysicsRackAndPinionJoint Define(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxPhysicsRackAndPinionJoint(stage->DefinePrim(path, PhysxSchemaTokens->PhysxPhysicsRackAndPinionJoint)); }

public:
    // --------------------------------------------------------------------- //
    // RATIO
    // --------------------------------------------------------------------- //
    /// Ratio between angular and linear motion. For a rack of length L with N0 teeth and a pinion of N1 teeth, the ratio should be (PI * 2 * N0)/(L * N1).
    /// Range: (-inf, inf)
    /// Units: degrees / distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physics:ratio = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetRatioAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physicsRatio); }

    /// See GetRatioAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateRatioAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physicsRatio,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // HINGE
    // --------------------------------------------------------------------- //
    /// Relationship to the hinge joint. It should be a PhysicsRevoluteJoint. It is mandatory to define one (and only one) relationship here.
    UsdRelationship GetHingeRel() const
    { return GetPrim().GetRelationship(PhysxSchemaTokens->physicsHinge); }

    /// See GetHingeRel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateHingeRel() const
    { return GetPrim().CreateRelationship(PhysxSchemaTokens->physicsHinge, /* custom = */ false); }

public:
    // --------------------------------------------------------------------- //
    // PRISMATIC
    // --------------------------------------------------------------------- //
    /// Relationship to the prismatic joint. It should be a PhysicsPrismaticJoint. It is mandatory to define one (and only one) relationship here.
    UsdRelationship GetPrismaticRel() const
    { return GetPrim().GetRelationship(PhysxSchemaTokens->physicsPrismatic); }

    /// See GetPrismaticRel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreatePrismaticRel() const
    { return GetPrim().CreateRelationship(PhysxSchemaTokens->physicsPrismatic, /* custom = */ false); }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
