// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxVehicleClutchAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXVEHICLECLUTCHAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXVEHICLECLUTCHAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxVehicleClutchAPI
///
/// Properties of the PhysX vehicle clutch. If the clutch setup does not need to be shared among vehicle
/// instances, it can be applied to the prim which has PhysxVehicleDriveStandardAPI applied.
/// If the intent is to share the clutch setup, PhysxVehicleClutchAPI can be applied to a separate
/// prim which can be linked to (see PhysxVehicleDriveStandardAPI).
///
class PhysxSchemaPhysxVehicleClutchAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxVehicleClutchAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxVehicleClutchAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxVehicleClutchAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxVehicleClutchAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxVehicleClutchAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxVehicleClutchAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxVehicleClutchAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxVehicleClutchAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxVehicleClutchStrength,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxVehicleClutchAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxVehicleClutchAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxVehicleClutchAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxVehicleClutchAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxVehicleClutchAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxVehicleClutchAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxVehicleClutchAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxVehicleClutchAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxVehicleClutchAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxVehicleClutchAPI)) { return PhysxSchemaPhysxVehicleClutchAPI(prim); }
        return PhysxSchemaPhysxVehicleClutchAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // STRENGTH
    // --------------------------------------------------------------------- //
    /// Strength of clutch. The value has to be positive.
    ///
    /// The clutch is the mechanism that couples the engine to the wheels. A stronger clutch more
    /// strongly couples the engine to the wheels, while a clutch of strength zero completely
    /// decouples the engine from the wheels. Stronger clutches more quickly bring the wheels and
    /// engine into equilibrium, while weaker clutches take longer, resulting in periods of clutch
    /// slip and delays in power transmission from the engine to the wheels. The torque generated
    /// by the clutch is proportional to the clutch strength and the velocity difference between
    /// the engine's rotational speed and the rotational speed of the driven wheels after accounting
    /// for the gear ratio. The torque at the clutch is applied negatively to the engine and
    /// positively to the driven wheels.
    ///
    /// Units: torque * seconds = mass * distance * distance / seconds
    ///
    /// Note: if not defined, the value 10.0 will be used. This default value is in meter length scale
    /// and kilograms and will get adjusted if other units are used.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleClutch:strength` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetStrengthAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleClutchStrength); }

    /// See GetStrengthAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateStrengthAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleClutchStrength,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
