// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxPBDMaterialAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXPBDMATERIALAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXPBDMATERIALAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxPBDMaterialAPI
///
/// WARNING: This is a draft API; the design is not fixed and may change in the future.
/// Applied to a USD Material. PhysX position-based-dynamics (PBD) material for particles used to simulate fluids and granular materials.
/// Currently, only a single material per particle system is supported which applies to all objects that are associated with the system.
///
class PhysxSchemaPhysxPBDMaterialAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxPBDMaterialAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxPBDMaterialAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxPBDMaterialAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxPBDMaterialAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxPBDMaterialAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxPBDMaterialAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxPBDMaterialAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxPBDMaterialAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxPBDMaterialFriction,
            PhysxSchemaTokens->physxPBDMaterialParticleFrictionScale,
            PhysxSchemaTokens->physxPBDMaterialDamping,
            PhysxSchemaTokens->physxPBDMaterialViscosity,
            PhysxSchemaTokens->physxPBDMaterialVorticityConfinement,
            PhysxSchemaTokens->physxPBDMaterialSurfaceTension,
            PhysxSchemaTokens->physxPBDMaterialCohesion,
            PhysxSchemaTokens->physxPBDMaterialAdhesion,
            PhysxSchemaTokens->physxPBDMaterialParticleAdhesionScale,
            PhysxSchemaTokens->physxPBDMaterialAdhesionOffsetScale,
            PhysxSchemaTokens->physxPBDMaterialGravityScale,
            PhysxSchemaTokens->physxPBDMaterialDensity,
            PhysxSchemaTokens->physxPBDMaterialCflCoefficient,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxPBDMaterialAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxPBDMaterialAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxPBDMaterialAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxPBDMaterialAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxPBDMaterialAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxPBDMaterialAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxPBDMaterialAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxPBDMaterialAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxPBDMaterialAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxPBDMaterialAPI)) { return PhysxSchemaPhysxPBDMaterialAPI(prim); }
        return PhysxSchemaPhysxPBDMaterialAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // FRICTION
    // --------------------------------------------------------------------- //
    /// Friction coefficient. The maximal friction force tangential to the surface is equal to the normal force times
    /// the friction. The friction takes effect in all interactions between particles and rigids or deformables.
    /// For solid particle-particle interactions it is multiplied by the particle friction scale.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:friction = 0.2` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetFrictionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialFriction); }

    /// See GetFrictionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateFrictionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialFriction,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // PARTICLEFRICTIONSCALE
    // --------------------------------------------------------------------- //
    /// Coefficient that scales friction for solid particle-particle interations.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:particleFrictionScale = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetParticleFrictionScaleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialParticleFrictionScale); }

    /// See GetParticleFrictionScaleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateParticleFrictionScaleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialParticleFrictionScale,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // DAMPING
    // --------------------------------------------------------------------- //
    /// Global velocity damping coefficient.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:damping = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDampingAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialDamping); }

    /// See GetDampingAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDampingAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialDamping,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // VISCOSITY
    // --------------------------------------------------------------------- //
    /// Viscosity for fluid particles.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:viscosity = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetViscosityAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialViscosity); }

    /// See GetViscosityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateViscosityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialViscosity,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // VORTICITYCONFINEMENT
    // --------------------------------------------------------------------- //
    /// Vorticity confinement for fluid particles. Helps prevent energy loss due to numerical solver by adding vortex-like accelerations to the particles.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:vorticityConfinement = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetVorticityConfinementAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialVorticityConfinement); }

    /// See GetVorticityConfinementAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateVorticityConfinementAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialVorticityConfinement,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACETENSION
    // --------------------------------------------------------------------- //
    /// Surface tension for fluid particles.
    /// Range: [0, inf)
    /// Units: 1 / (distance * distance * distance)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:surfaceTension = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSurfaceTensionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialSurfaceTension); }

    /// See GetSurfaceTensionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceTensionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialSurfaceTension,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // COHESION
    // --------------------------------------------------------------------- //
    /// Cohesion for interaction between fluid particles.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:cohesion = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetCohesionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialCohesion); }

    /// See GetCohesionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateCohesionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialCohesion,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // ADHESION
    // --------------------------------------------------------------------- //
    /// Adhesion for interactions between particles (solid or fluid), and rigids or deformables.
    /// Adhesion also applies to solid-solid particle interactions, but is multiplied with the particle adhesion scale.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:adhesion = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetAdhesionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialAdhesion); }

    /// See GetAdhesionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateAdhesionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialAdhesion,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // PARTICLEADHESIONSCALE
    // --------------------------------------------------------------------- //
    /// Coefficient that scales adhesion for solid particle-particle interations.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:particleAdhesionScale = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetParticleAdhesionScaleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialParticleAdhesionScale); }

    /// See GetParticleAdhesionScaleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateParticleAdhesionScaleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialParticleAdhesionScale,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // ADHESIONOFFSETSCALE
    // --------------------------------------------------------------------- //
    /// Offset scale defining the offset at which adhesion ceases to take effect. For interactions between particles (fluid or solid),
    /// and rigids or deformables, the adhesion offset is defined relative to the rest offset. For solid particle-particle
    /// interactions, the adhesion offset is defined relative to the solid rest offset.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:adhesionOffsetScale = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetAdhesionOffsetScaleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialAdhesionOffsetScale); }

    /// See GetAdhesionOffsetScaleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateAdhesionOffsetScaleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialAdhesionOffsetScale,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // GRAVITYSCALE
    // --------------------------------------------------------------------- //
    /// Gravitational acceleration scaling factor, for example (-1.0 would invert gravity).
    /// Range: (-inf, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:gravityScale = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetGravityScaleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialGravityScale); }

    /// See GetGravityScaleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateGravityScaleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialGravityScale,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // DENSITY
    // --------------------------------------------------------------------- //
    /// Density used to compute particle object mass. If set to 0.0, the simulation determines a default density.
    /// A density or mass set with a PhysicsMassAPI on a particle object overrides the material density.
    /// Range: [0, inf)
    /// Units: mass / distance / distance / distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:density = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDensityAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialDensity); }

    /// See GetDensityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDensityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialDensity,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // CFLCOEFFICIENT
    // --------------------------------------------------------------------- //
    /// This coefficient scales the CFL term used to limit relative motion between approaching fluid particles. A very large value disables the limit.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPBDMaterial:cflCoefficient = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetCflCoefficientAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPBDMaterialCflCoefficient); }

    /// See GetCflCoefficientAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateCflCoefficientAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPBDMaterialCflCoefficient,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
