// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxParticleAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXPARTICLEAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXPARTICLEAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxParticleAPI
///
/// WARNING: This is a draft API; the design is not fixed and may change in the future.
/// Do not apply. Provides parameters shared among particle objects.
///
class PhysxSchemaPhysxParticleAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxParticleAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxParticleAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxParticleAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxParticleAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxParticleAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxParticleAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxParticleAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxParticleAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxParticleParticleEnabled,
            PhysxSchemaTokens->physxParticleSelfCollision,
            PhysxSchemaTokens->physxParticleParticleGroup,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxParticleAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxParticleAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxParticleAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxParticleAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxParticleAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxParticleAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxParticleAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxParticleAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxParticleAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxParticleAPI)) { return PhysxSchemaPhysxParticleAPI(prim); }
        return PhysxSchemaPhysxParticleAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // PARTICLEENABLED
    // --------------------------------------------------------------------- //
    /// Enable or disable the particle object.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxParticle:particleEnabled = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetParticleEnabledAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleParticleEnabled); }

    /// See GetParticleEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateParticleEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleParticleEnabled,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SELFCOLLISION
    // --------------------------------------------------------------------- //
    /// Enables self-collision of the particles or of the particle object.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxParticle:selfCollision = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetSelfCollisionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleSelfCollision); }

    /// See GetSelfCollisionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSelfCollisionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleSelfCollision,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // PARTICLEGROUP
    // --------------------------------------------------------------------- //
    /// Group Id of the particles. Particles / objects in different groups in the same system collide with each other.
    /// Within the same group in the same system, the collision behavior is controlled by the selfCollision parameter.
    /// Range: [0, 2^20)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int physxParticle:particleGroup = 0` |
    /// | C++ Type | int |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Int |
    UsdAttribute GetParticleGroupAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleParticleGroup); }

    /// See GetParticleGroupAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateParticleGroupAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleParticleGroup,
                   SdfValueTypeNames->Int, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // PARTICLESYSTEM
    // --------------------------------------------------------------------- //
    /// Single particle system that the particle-based object belongs to.
    UsdRelationship GetParticleSystemRel() const
    { return GetPrim().GetRelationship(PhysxSchemaTokens->physxParticleParticleSystem); }

    /// See GetParticleSystemRel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateParticleSystemRel() const
    { return GetPrim().CreateRelationship(PhysxSchemaTokens->physxParticleParticleSystem, /* custom = */ false); }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
