// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxJointAxisAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXJOINTAXISAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXJOINTAXISAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxJointAxisAPI
///
/// PhysX joint parameters defined per axis. Can be applied to a PhysicsJoint prim or
/// the derived classes PhysicsRevoluteJoint, PhysicsPrismaticJoint or PhysicsSphericalJoint.
/// For overlapping parameters with PhysxJointAPI, the parameters of PhysxJointAxisAPI take precedence for that axis.
///
class PhysxSchemaPhysxJointAxisAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::MultipleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxJointAxisAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxJointAxisAPI on UsdPrim \p prim with
    /// name \p name . Equivalent to
    /// PhysxSchemaPhysxJointAxisAPI::Get(
    ///    prim.GetStage(),
    ///    prim.GetPath().AppendProperty(
    ///        "physxJointAxis:name"));
    ///
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxJointAxisAPI(const UsdPrim& prim=UsdPrim(), const TfToken &name=TfToken())
        : UsdAPISchemaBase(prim, name) {}

    /// Construct a PhysxSchemaPhysxJointAxisAPI on the prim held by \p schemaObj with
    /// name \p name.  Should be preferred over
    /// PhysxSchemaPhysxJointAxisAPI(schemaObj.GetPrim(), name), as it preserves
    /// SchemaBase state.
    explicit PhysxSchemaPhysxJointAxisAPI(const UsdSchemaBase& schemaObj, const TfToken &name)
        : UsdAPISchemaBase(schemaObj, name) {}

    /// Returns the name of this multiple-apply schema instance
    TfToken GetName() const { return _GetInstanceName(); }

    /// Destructor.
    virtual ~PhysxSchemaPhysxJointAxisAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_MaxJointVelocity,
            PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_Armature,
            PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_StaticFrictionEffort,
            PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_DynamicFrictionEffort,
            PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_ViscousFrictionCoefficient,
        };
        return localNames;
    }

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes for a given instance name.  Does not
    /// include attributes that may be authored by custom/extended methods of
    /// the schemas involved. The names returned will have the proper namespace
    /// prefix.
    static TfTokenVector GetSchemaAttributeNames(bool includeInherited, const TfToken &instanceName)
    {
        const TfTokenVector &attrNames = GetSchemaAttributeNames(includeInherited);
        if (instanceName.IsEmpty()) {
            return attrNames;
        }
        TfTokenVector result;
        result.reserve(attrNames.size());
        for (const TfToken &attrName : attrNames) {
            result.push_back(UsdSchemaRegistry::MakeMultipleApplyNameInstance(attrName, instanceName));
        }
        return result;
    }

    /// Checks if the given name \p baseName is the base name of a property
    /// of PhysxJointAxisAPI.
    static bool IsSchemaPropertyBaseName(const TfToken &baseName)
    {
        static TfTokenVector attrsAndRels = {
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_MaxJointVelocity),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_Armature),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_StaticFrictionEffort),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_DynamicFrictionEffort),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_ViscousFrictionCoefficient),
        };
        return std::find(attrsAndRels.begin(), attrsAndRels.end(), baseName) != attrsAndRels.end();
    }

    /// Checks if the given path \p path is of an API schema of type
    /// PhysxJointAxisAPI. If so, it stores the instance name of
    /// the schema in \p name and returns true. Otherwise, it returns false.
    static bool IsPhysxJointAxisAPIPath(const SdfPath &path, TfToken *name)
    {
        if (!path.IsPropertyPath()) {
            return false;
        }
        const std::string propertyName = path.GetName();
        const TfTokenVector tokens = SdfPath::TokenizeIdentifierAsTokens(propertyName);
        if (tokens.empty()) {
            return false;
        }
        const TfToken &baseName = *tokens.rbegin();
        if (IsSchemaPropertyBaseName(baseName)) {
            return false;
        }
        if (tokens.size() >= 2
            && tokens[0] == PhysxSchemaTokens->physxJointAxis) {
            if (name) {
                *name = TfToken(propertyName.substr(PhysxSchemaTokens->physxJointAxis.GetString().size() + 1));
            }
            return true;
        }
        return false;
    }

    /// Return a PhysxSchemaPhysxJointAxisAPI with name \p name holding the
    /// prim \p prim. Shorthand for PhysxSchemaPhysxJointAxisAPI(prim, name);
    static PhysxSchemaPhysxJointAxisAPI Get(const UsdPrim &prim, const TfToken &name)
    { return PhysxSchemaPhysxJointAxisAPI(prim, name); }

    /// Return a PhysxSchemaPhysxJointAxisAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  \p path must be of the format
    /// <path>.physxJointAxis:name .
    ///
    /// This is shorthand for the following:
    ///
    /// \code
    /// TfToken name = SdfPath::StripNamespace(path.GetToken());
    /// PhysxSchemaPhysxJointAxisAPI(
    ///     stage->GetPrimAtPath(path.GetPrimPath()), name);
    /// \endcode
    ///
    static PhysxSchemaPhysxJointAxisAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    {
        if (!stage) {
            return PhysxSchemaPhysxJointAxisAPI();
        }
        TfToken name;
        if (!IsPhysxJointAxisAPIPath(path, &name)) {
            return PhysxSchemaPhysxJointAxisAPI();
        }
        return PhysxSchemaPhysxJointAxisAPI(stage->GetPrimAtPath(path.GetPrimPath()), name);
    }

    /// Return a vector of all named instances of PhysxSchemaPhysxJointAxisAPI on the
    /// given \p prim.
    static std::vector<PhysxSchemaPhysxJointAxisAPI> GetAll(const UsdPrim &prim)
    {
        std::vector<PhysxSchemaPhysxJointAxisAPI> schemas;
        const TfType &type = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxJointAxisAPI);
        for (const auto &n : _GetMultipleApplyInstanceNames(prim, type)) {
            schemas.emplace_back(prim, n);
        }
        return schemas;
    }

    /// Returns true if this <b>multiple-apply</b> API schema can be applied,
    /// with the given instance name, \p name, to the given \p prim. If this
    /// schema can not be a applied the prim, this returns false and, if
    /// provided, populates \p whyNot with the reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, const TfToken &name, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxJointAxisAPI, name, whyNot); }

    /// Applies this <b>multiple-apply</b> API schema to the given \p prim
    /// along with the given instance name, \p name.
    ///
    /// This information is stored by adding "PhysxJointAxisAPI:<i>name</i>"
    /// to the token-valued, listOp metadata \em apiSchemas on the prim.
    /// For example, if \p name is 'instance1', the token
    /// 'PhysxJointAxisAPI:instance1' is added to 'apiSchemas'.
    ///
    /// \return A valid PhysxSchemaPhysxJointAxisAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxJointAxisAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for
    /// conditions resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxJointAxisAPI Apply(const UsdPrim &prim, const TfToken &name)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxJointAxisAPI, name)) { return PhysxSchemaPhysxJointAxisAPI(prim, name); }
        return PhysxSchemaPhysxJointAxisAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // MAXJOINTVELOCITY
    // --------------------------------------------------------------------- //
    /// Maximum joint velocity. Only applies to joints that are part of an articulation (see PhysicsArticulationRootAPI).
    /// The solver will apply appropriate joint-space impulses in order to enforce the per-axis joint-velocity limit.
    /// Range: [0, inf)
    /// Units: Linear joint - distance / seconds
    /// Angular joint - degrees / seconds
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float maxJointVelocity = inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxJointVelocityAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_MaxJointVelocity, _GetInstanceName())); }

    /// See GetMaxJointVelocityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxJointVelocityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_MaxJointVelocity, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // ARMATURE
    // --------------------------------------------------------------------- //
    /// Conceptually, armature represents the inertia of an actuator driving the joint. It is an artificial mass/inertia
    /// that is added to the joint-space inertia and can help stabilize an articulation. Note that this parameter is used only
    /// when the joint belongs to an articulation (see PhysicsArticulationRootAPI).
    /// Range: [0, inf)
    /// Units: Linear joint - mass
    /// Angular joint - mass * distance^2
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float armature = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetArmatureAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_Armature, _GetInstanceName())); }

    /// See GetArmatureAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateArmatureAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_Armature, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // STATICFRICTIONEFFORT
    // --------------------------------------------------------------------- //
    /// Maximum static friction force or torque applied to resist motion in stationary joints. Only applies to joints that are part of an articulation (see PhysicsArticulationRootAPI).
    /// Prevents motion initiation until the applied force exceeds this threshold.
    /// Range: [0, inf)
    /// Units: Linear joint - force (mass * distance / second^2)
    /// Angular joint - torque (mass * distance^2 / second^2)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float staticFrictionEffort = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetStaticFrictionEffortAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_StaticFrictionEffort, _GetInstanceName())); }

    /// See GetStaticFrictionEffortAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateStaticFrictionEffortAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_StaticFrictionEffort, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // DYNAMICFRICTIONEFFORT
    // --------------------------------------------------------------------- //
    /// Coulomb friction force or torque applied to resist motion in moving joints. Only applies to joints that are part of an articulation (see PhysicsArticulationRootAPI).
    /// Should be less than or equal to staticFrictionEffort.
    /// Range: [0, inf)
    /// Units: Linear joint - force (mass * distance / second^2)
    /// Angular joint - torque (mass * distance^2 / second^2)
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float dynamicFrictionEffort = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDynamicFrictionEffortAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_DynamicFrictionEffort, _GetInstanceName())); }

    /// See GetDynamicFrictionEffortAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDynamicFrictionEffortAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_DynamicFrictionEffort, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // VISCOUSFRICTIONCOEFFICIENT
    // --------------------------------------------------------------------- //
    /// Coefficient used to calculate velocity-dependent friction effort. Only applies to joints that are part of an articulation (see PhysicsArticulationRootAPI).
    /// Total friction effort in moving joints = - sign(jointVelocity) * (dynamicFrictionEffort + viscousFrictionCoefficient * abs(jointVelocity))
    /// Range: [0, inf)
    /// Units: Linear joint - force * second / distance
    /// Angular joint - torque * second / degrees
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float viscousFrictionCoefficient = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetViscousFrictionCoefficientAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_ViscousFrictionCoefficient, _GetInstanceName())); }

    /// See GetViscousFrictionCoefficientAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateViscousFrictionCoefficientAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxJointAxis_MultipleApplyTemplate_ViscousFrictionCoefficient, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
