// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxSurfaceVelocityAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXSURFACEVELOCITYAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXSURFACEVELOCITYAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxSurfaceVelocityAPI
///
/// PhysxSurfaceVelocityAPI enables surface velocity simulation
/// that injects velocity to the solver through internal contact modify
/// callback. Surface velocity can be used typically for conveyer belt
/// simulation. It must be applied to a prim with UsdPhysicsRigidBodyAPI.
///
class PhysxSchemaPhysxSurfaceVelocityAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxSurfaceVelocityAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxSurfaceVelocityAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxSurfaceVelocityAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxSurfaceVelocityAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxSurfaceVelocityAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxSurfaceVelocityAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxSurfaceVelocityAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxSurfaceVelocityAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocityEnabled,
            PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocityLocalSpace,
            PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocity,
            PhysxSchemaTokens->physxSurfaceVelocitySurfaceAngularVelocity,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxSurfaceVelocityAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxSurfaceVelocityAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxSurfaceVelocityAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxSurfaceVelocityAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxSurfaceVelocityAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxSurfaceVelocityAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxSurfaceVelocityAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxSurfaceVelocityAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxSurfaceVelocityAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxSurfaceVelocityAPI)) { return PhysxSchemaPhysxSurfaceVelocityAPI(prim); }
        return PhysxSchemaPhysxSurfaceVelocityAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACEVELOCITYENABLED
    // --------------------------------------------------------------------- //
    /// Whether surface velocity is enabled or not.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxSurfaceVelocity:surfaceVelocityEnabled = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetSurfaceVelocityEnabledAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocityEnabled); }

    /// See GetSurfaceVelocityEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceVelocityEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocityEnabled,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACEVELOCITYLOCALSPACE
    // --------------------------------------------------------------------- //
    /// Whether surface velocity is defined in body local space or in world space.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxSurfaceVelocity:surfaceVelocityLocalSpace = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetSurfaceVelocityLocalSpaceAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocityLocalSpace); }

    /// See GetSurfaceVelocityLocalSpaceAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceVelocityLocalSpaceAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocityLocalSpace,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACEVELOCITY
    // --------------------------------------------------------------------- //
    /// Surface linear velocity applied through contact modify callback.
    /// Units: distance/second.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `vector3f physxSurfaceVelocity:surfaceVelocity = (0, 0, 0)` |
    /// | C++ Type | GfVec3f |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Vector3f |
    UsdAttribute GetSurfaceVelocityAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocity); }

    /// See GetSurfaceVelocityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceVelocityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxSurfaceVelocitySurfaceVelocity,
                   SdfValueTypeNames->Vector3f, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SURFACEANGULARVELOCITY
    // --------------------------------------------------------------------- //
    /// Surface angular velocity applied through contact modify callback.
    /// Units: degrees/second.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `vector3f physxSurfaceVelocity:surfaceAngularVelocity = (0, 0, 0)` |
    /// | C++ Type | GfVec3f |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Vector3f |
    UsdAttribute GetSurfaceAngularVelocityAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxSurfaceVelocitySurfaceAngularVelocity); }

    /// See GetSurfaceAngularVelocityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSurfaceAngularVelocityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxSurfaceVelocitySurfaceAngularVelocity,
                   SdfValueTypeNames->Vector3f, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
