// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxVehicleAckermannSteeringAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXVEHICLEACKERMANNSTEERINGAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXVEHICLEACKERMANNSTEERINGAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxVehicleAckermannSteeringAPI
///
/// Describes a steering system with Ackermann correction for two wheels. This system will
/// result in asymmetric steer angles such that the line defined by the non-steered wheel axle
/// and the lateral lines of the steered wheels meet at the same point. As a consequence, when
/// following the path around a curve, the inner wheel will turn more than the outer one. This
/// avoids that some wheels need to slip sideways to stay on the path. The specified wheels
/// will be connected to the steer control (see PhysxVehicleControllerAPI). This API schema
/// has to be applied to a prim with PhysxVehicleAPI applied. Can only be used for vehicles that
/// have a drive (see PhysxVehicleDriveBasicAPI or PhysxVehicleDriveStandardAPI). This API
/// schema can not be combined with PhysxVehicleSteeringAPI, only one or the other is allowed.
///
class PhysxSchemaPhysxVehicleAckermannSteeringAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxVehicleAckermannSteeringAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxVehicleAckermannSteeringAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxVehicleAckermannSteeringAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxVehicleAckermannSteeringAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxVehicleAckermannSteeringAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxVehicleAckermannSteeringAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxVehicleAckermannSteeringAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxVehicleAckermannSteeringAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxVehicleAckermannSteeringWheel0,
            PhysxSchemaTokens->physxVehicleAckermannSteeringWheel1,
            PhysxSchemaTokens->physxVehicleAckermannSteeringMaxSteerAngle,
            PhysxSchemaTokens->physxVehicleAckermannSteeringWheelBase,
            PhysxSchemaTokens->physxVehicleAckermannSteeringTrackWidth,
            PhysxSchemaTokens->physxVehicleAckermannSteeringStrength,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxVehicleAckermannSteeringAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxVehicleAckermannSteeringAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxVehicleAckermannSteeringAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxVehicleAckermannSteeringAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxVehicleAckermannSteeringAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxVehicleAckermannSteeringAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxVehicleAckermannSteeringAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxVehicleAckermannSteeringAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxVehicleAckermannSteeringAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxVehicleAckermannSteeringAPI)) { return PhysxSchemaPhysxVehicleAckermannSteeringAPI(prim); }
        return PhysxSchemaPhysxVehicleAckermannSteeringAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // WHEEL0
    // --------------------------------------------------------------------- //
    /// The index of the wheel that is negative along the lateral axis and should get
    /// connected to the steering system. The index refers to the attribute "index" of
    /// PhysxVehicleWheelAttachmentAPI.
    ///
    /// Note: this attribute has to be specified (there is no default).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int physxVehicleAckermannSteering:wheel0` |
    /// | C++ Type | int |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Int |
    UsdAttribute GetWheel0Attr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleAckermannSteeringWheel0); }

    /// See GetWheel0Attr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateWheel0Attr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleAckermannSteeringWheel0,
                   SdfValueTypeNames->Int, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // WHEEL1
    // --------------------------------------------------------------------- //
    /// The index of the wheel that is positive along the lateral axis and should get
    /// connected to the steering system. The index refers to the attribute "index" of
    /// PhysxVehicleWheelAttachmentAPI.
    ///
    /// Note: this attribute has to be specified (there is no default).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int physxVehicleAckermannSteering:wheel1` |
    /// | C++ Type | int |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Int |
    UsdAttribute GetWheel1Attr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleAckermannSteeringWheel1); }

    /// See GetWheel1Attr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateWheel1Attr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleAckermannSteeringWheel1,
                   SdfValueTypeNames->Int, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MAXSTEERANGLE
    // --------------------------------------------------------------------- //
    /// The maximum steer angle (in radians) that can be achieved by the wheels.
    /// Has to be in range [-pi, pi]. The steer angle of wheel0 will be defined by
    /// maxSteerAngle * ackermann_correction(0) * physxVehicleController:steer (see PhysxVehicleControllerAPI).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleAckermannSteering:maxSteerAngle = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxSteerAngleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleAckermannSteeringMaxSteerAngle); }

    /// See GetMaxSteerAngleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxSteerAngleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleAckermannSteeringMaxSteerAngle,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // WHEELBASE
    // --------------------------------------------------------------------- //
    /// The longitudinal distance between the axle that is affected by Ackermann
    /// correction and a reference axle. The value has to be greater
    /// than zero.
    ///
    /// Units: distance
    ///
    /// Note: this attribute has to be specified (there is no default).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleAckermannSteering:wheelBase` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetWheelBaseAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleAckermannSteeringWheelBase); }

    /// See GetWheelBaseAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateWheelBaseAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleAckermannSteeringWheelBase,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // TRACKWIDTH
    // --------------------------------------------------------------------- //
    /// The width of the axle defined by wheel0 and wheel1.
    /// The value has to be greater than zero.
    ///
    /// Units: distance
    ///
    /// Note: this attribute has to be specified (there is no default).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleAckermannSteering:trackWidth` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetTrackWidthAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleAckermannSteeringTrackWidth); }

    /// See GetTrackWidthAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateTrackWidthAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleAckermannSteeringTrackWidth,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // STRENGTH
    // --------------------------------------------------------------------- //
    /// The strength of the Ackermann correction with 0 denoting no correction and
    /// 1 denoting perfect correction. The value has to be in range [0, 1].
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleAckermannSteering:strength = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetStrengthAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleAckermannSteeringStrength); }

    /// See GetStrengthAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateStrengthAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleAckermannSteeringStrength,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
