// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxVehicleDriveBasicAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXVEHICLEDRIVEBASICAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXVEHICLEDRIVEBASICAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxVehicleDriveBasicAPI
///
/// Very simple drive model for a PhysX vehicle. A torque will be directly applied to the wheels
/// that are marked as driven (see PhysxVehicleMultiWheelDifferentialAPI or deprecated attribute
/// "driven" in PhysxVehicleWheelAttachmentAPI).
///
/// If the drive setup does not need to be shared among vehicle instances, it can be applied to the
/// prim which has PhysxVehicleAPI applied. If the intent is to share the drive setup, PhysxVehicleDriveBasicAPI
/// can be applied to a separate prim which can be linked to (see PhysxVehicleAPI).
///
class PhysxSchemaPhysxVehicleDriveBasicAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxVehicleDriveBasicAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxVehicleDriveBasicAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxVehicleDriveBasicAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxVehicleDriveBasicAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxVehicleDriveBasicAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxVehicleDriveBasicAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxVehicleDriveBasicAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxVehicleDriveBasicAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxVehicleDriveBasicPeakTorque,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxVehicleDriveBasicAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxVehicleDriveBasicAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxVehicleDriveBasicAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxVehicleDriveBasicAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxVehicleDriveBasicAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxVehicleDriveBasicAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxVehicleDriveBasicAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxVehicleDriveBasicAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxVehicleDriveBasicAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxVehicleDriveBasicAPI)) { return PhysxSchemaPhysxVehicleDriveBasicAPI(prim); }
        return PhysxSchemaPhysxVehicleDriveBasicAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // PEAKTORQUE
    // --------------------------------------------------------------------- //
    /// Maximum torque to generate when the accelerator pedal is at maximum.
    /// The value has to be greater or equal 0.
    ///
    /// Units: mass * distance * distance / seconds / seconds
    ///
    /// Note: PhysxVehicleMultiWheelDifferentialAPI can be used to specify which wheels are connected
    /// to the drive as well as how the torque should be distributed among those wheels. If the
    /// deprecated attribute "driven" of PhysxVehicleWheelAttachmentAPI is used, then each driven
    /// wheel can experience a torque up to the value defined in this attribute.
    ///
    /// Note: the applied torque is the value of the accelerator pedal (in range [0, 1]) multiplied
    /// by peakTorque.
    ///
    /// Note: the default value -1 is not a valid value as such but will result in the value 1000.0
    /// being used (in meter length scale and kilogram mass scale or the equivalent if other units
    /// are used).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleDriveBasic:peakTorque = -1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetPeakTorqueAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleDriveBasicPeakTorque); }

    /// See GetPeakTorqueAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreatePeakTorqueAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleDriveBasicPeakTorque,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
