// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxParticleAnisotropyAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXPARTICLEANISOTROPYAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXPARTICLEANISOTROPYAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxParticleAnisotropyAPI
///
/// WARNING: This is a draft API; the design is not fixed and may change in the future.
/// Applied to a PhysxParticleSystem. Defines settings to compute anisotropic scaling of particles in a post-processing step.
/// The anisotropy post-processing only affects the rendering output including isosurface generation, and not the particle dynamics.
/// Affects point instancer primitives with PhysxParticleSetAPI, which are defined as fluid.
///
class PhysxSchemaPhysxParticleAnisotropyAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxParticleAnisotropyAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxParticleAnisotropyAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxParticleAnisotropyAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxParticleAnisotropyAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxParticleAnisotropyAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxParticleAnisotropyAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxParticleAnisotropyAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxParticleAnisotropyAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxParticleAnisotropyParticleAnisotropyEnabled,
            PhysxSchemaTokens->physxParticleAnisotropyScale,
            PhysxSchemaTokens->physxParticleAnisotropyMin,
            PhysxSchemaTokens->physxParticleAnisotropyMax,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxParticleAnisotropyAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxParticleAnisotropyAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxParticleAnisotropyAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxParticleAnisotropyAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxParticleAnisotropyAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxParticleAnisotropyAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxParticleAnisotropyAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxParticleAnisotropyAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxParticleAnisotropyAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxParticleAnisotropyAPI)) { return PhysxSchemaPhysxParticleAnisotropyAPI(prim); }
        return PhysxSchemaPhysxParticleAnisotropyAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // PARTICLEANISOTROPYENABLED
    // --------------------------------------------------------------------- //
    /// Enables use of fluid anisotropy information for rendering.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxParticleAnisotropy:particleAnisotropyEnabled = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetParticleAnisotropyEnabledAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleAnisotropyParticleAnisotropyEnabled); }

    /// See GetParticleAnisotropyEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateParticleAnisotropyEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleAnisotropyParticleAnisotropyEnabled,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SCALE
    // --------------------------------------------------------------------- //
    /// Scale of anisotropy for rendering.
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxParticleAnisotropy:scale = 1` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetScaleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleAnisotropyScale); }

    /// See GetScaleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateScaleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleAnisotropyScale,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MIN
    // --------------------------------------------------------------------- //
    /// Minimum scale of anisotropy relative to fluidRestOffset for rendering.
    /// Range: [0, max]
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxParticleAnisotropy:min = 0.2` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMinAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleAnisotropyMin); }

    /// See GetMinAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMinAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleAnisotropyMin,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MAX
    // --------------------------------------------------------------------- //
    /// Maximum scale of anisotropy relative to fluidRestOffset for rendering.
    /// Range: [min, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxParticleAnisotropy:max = 2` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxParticleAnisotropyMax); }

    /// See GetMaxAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxParticleAnisotropyMax,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
