// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxSceneQuasistaticAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXSCENEQUASISTATICAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXSCENEQUASISTATICAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxSceneQuasistaticAPI
///
/// PhysxSceneQuasistaticAPI defines quasistatic mode for simulation.
/// The API must be applied to a UsdPhysics.PhysicsScene prim.
///
///
/// In this mode actors are simulated/moved by the physics engine by obeying
/// external forces and constraints as usual, but they do not accumulate momentum.
/// So that e.g. falling due to gravity is with constant speed, and motion stops
/// as soon as external forces cease to apply. There is no conservation of momentum.
///
///
/// By default all actors belonging to the scene have this behavior unless the collection
/// does have the includes defined, then the collection definition does have a precendence.
///
class PhysxSchemaPhysxSceneQuasistaticAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxSceneQuasistaticAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxSceneQuasistaticAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxSceneQuasistaticAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxSceneQuasistaticAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxSceneQuasistaticAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxSceneQuasistaticAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxSceneQuasistaticAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxSceneQuasistaticAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxSceneQuasistaticEnableQuasistatic,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxSceneQuasistaticAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxSceneQuasistaticAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxSceneQuasistaticAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxSceneQuasistaticAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxSceneQuasistaticAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxSceneQuasistaticAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxSceneQuasistaticAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxSceneQuasistaticAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxSceneQuasistaticAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxSceneQuasistaticAPI)) { return PhysxSchemaPhysxSceneQuasistaticAPI(prim); }
        return PhysxSchemaPhysxSceneQuasistaticAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // ENABLEQUASISTATIC
    // --------------------------------------------------------------------- //
    /// Whether the actors should behave quasistatic or not.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxSceneQuasistatic:enableQuasistatic = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetEnableQuasistaticAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxSceneQuasistaticEnableQuasistatic); }

    /// See GetEnableQuasistaticAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateEnableQuasistaticAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxSceneQuasistaticEnableQuasistatic,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

    /// Return the UsdCollectionAPI interface used for defining
    /// what prims belong to the quasistatic API.
    UsdCollectionAPI GetQuasistaticActorsCollectionAPI() const
    { return UsdCollectionAPI(GetPrim(), PhysxSchemaTokens->quasistaticactors); }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
