// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxDrivePerformanceEnvelopeAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXDRIVEPERFORMANCEENVELOPEAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXDRIVEPERFORMANCEENVELOPEAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxDrivePerformanceEnvelopeAPI
///
/// PhysX drive performance envelope parameters. Can be applied to a PhysicsJoint prim or
/// the derived classes PhysicsRevoluteJoint, PhysicsPrismaticJoint (similar to PhysicsDriveAPI).
/// For the PhysxDrivePerformanceEnvelopeAPI to take effect, the PhysicsDriveAPI must also be defined for the same axis. This is because the maxForce parameter of the PhysicsDriveAPI is utilized by the PhysxDrivePerformanceEnvelopeAPI.
/// This API defines characteristics that limit the total joint force (drive force + external cached joint force).
///
class PhysxSchemaPhysxDrivePerformanceEnvelopeAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::MultipleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxDrivePerformanceEnvelopeAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxDrivePerformanceEnvelopeAPI on UsdPrim \p prim with
    /// name \p name . Equivalent to
    /// PhysxSchemaPhysxDrivePerformanceEnvelopeAPI::Get(
    ///    prim.GetStage(),
    ///    prim.GetPath().AppendProperty(
    ///        "physxDrivePerformanceEnvelope:name"));
    ///
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(const UsdPrim& prim=UsdPrim(), const TfToken &name=TfToken())
        : UsdAPISchemaBase(prim, name) {}

    /// Construct a PhysxSchemaPhysxDrivePerformanceEnvelopeAPI on the prim held by \p schemaObj with
    /// name \p name.  Should be preferred over
    /// PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(schemaObj.GetPrim(), name), as it preserves
    /// SchemaBase state.
    explicit PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(const UsdSchemaBase& schemaObj, const TfToken &name)
        : UsdAPISchemaBase(schemaObj, name) {}

    /// Returns the name of this multiple-apply schema instance
    TfToken GetName() const { return _GetInstanceName(); }

    /// Destructor.
    virtual ~PhysxSchemaPhysxDrivePerformanceEnvelopeAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_MaxActuatorVelocity,
            PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_VelocityDependentResistance,
            PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_SpeedEffortGradient,
        };
        return localNames;
    }

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes for a given instance name.  Does not
    /// include attributes that may be authored by custom/extended methods of
    /// the schemas involved. The names returned will have the proper namespace
    /// prefix.
    static TfTokenVector GetSchemaAttributeNames(bool includeInherited, const TfToken &instanceName)
    {
        const TfTokenVector &attrNames = GetSchemaAttributeNames(includeInherited);
        if (instanceName.IsEmpty()) {
            return attrNames;
        }
        TfTokenVector result;
        result.reserve(attrNames.size());
        for (const TfToken &attrName : attrNames) {
            result.push_back(UsdSchemaRegistry::MakeMultipleApplyNameInstance(attrName, instanceName));
        }
        return result;
    }

    /// Checks if the given name \p baseName is the base name of a property
    /// of PhysxDrivePerformanceEnvelopeAPI.
    static bool IsSchemaPropertyBaseName(const TfToken &baseName)
    {
        static TfTokenVector attrsAndRels = {
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_MaxActuatorVelocity),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_VelocityDependentResistance),
            UsdSchemaRegistry::GetMultipleApplyNameTemplateBaseName(
                PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_SpeedEffortGradient),
        };
        return std::find(attrsAndRels.begin(), attrsAndRels.end(), baseName) != attrsAndRels.end();
    }

    /// Checks if the given path \p path is of an API schema of type
    /// PhysxDrivePerformanceEnvelopeAPI. If so, it stores the instance name of
    /// the schema in \p name and returns true. Otherwise, it returns false.
    static bool IsPhysxDrivePerformanceEnvelopeAPIPath(const SdfPath &path, TfToken *name)
    {
        if (!path.IsPropertyPath()) {
            return false;
        }
        const std::string propertyName = path.GetName();
        const TfTokenVector tokens = SdfPath::TokenizeIdentifierAsTokens(propertyName);
        if (tokens.empty()) {
            return false;
        }
        const TfToken &baseName = *tokens.rbegin();
        if (IsSchemaPropertyBaseName(baseName)) {
            return false;
        }
        if (tokens.size() >= 2
            && tokens[0] == PhysxSchemaTokens->physxDrivePerformanceEnvelope) {
            if (name) {
                *name = TfToken(propertyName.substr(PhysxSchemaTokens->physxDrivePerformanceEnvelope.GetString().size() + 1));
            }
            return true;
        }
        return false;
    }

    /// Return a PhysxSchemaPhysxDrivePerformanceEnvelopeAPI with name \p name holding the
    /// prim \p prim. Shorthand for PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(prim, name);
    static PhysxSchemaPhysxDrivePerformanceEnvelopeAPI Get(const UsdPrim &prim, const TfToken &name)
    { return PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(prim, name); }

    /// Return a PhysxSchemaPhysxDrivePerformanceEnvelopeAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  \p path must be of the format
    /// <path>.physxDrivePerformanceEnvelope:name .
    ///
    /// This is shorthand for the following:
    ///
    /// \code
    /// TfToken name = SdfPath::StripNamespace(path.GetToken());
    /// PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(
    ///     stage->GetPrimAtPath(path.GetPrimPath()), name);
    /// \endcode
    ///
    static PhysxSchemaPhysxDrivePerformanceEnvelopeAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    {
        if (!stage) {
            return PhysxSchemaPhysxDrivePerformanceEnvelopeAPI();
        }
        TfToken name;
        if (!IsPhysxDrivePerformanceEnvelopeAPIPath(path, &name)) {
            return PhysxSchemaPhysxDrivePerformanceEnvelopeAPI();
        }
        return PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(stage->GetPrimAtPath(path.GetPrimPath()), name);
    }

    /// Return a vector of all named instances of PhysxSchemaPhysxDrivePerformanceEnvelopeAPI on the
    /// given \p prim.
    static std::vector<PhysxSchemaPhysxDrivePerformanceEnvelopeAPI> GetAll(const UsdPrim &prim)
    {
        std::vector<PhysxSchemaPhysxDrivePerformanceEnvelopeAPI> schemas;
        const TfType &type = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxDrivePerformanceEnvelopeAPI);
        for (const auto &n : _GetMultipleApplyInstanceNames(prim, type)) {
            schemas.emplace_back(prim, n);
        }
        return schemas;
    }

    /// Returns true if this <b>multiple-apply</b> API schema can be applied,
    /// with the given instance name, \p name, to the given \p prim. If this
    /// schema can not be a applied the prim, this returns false and, if
    /// provided, populates \p whyNot with the reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, const TfToken &name, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxDrivePerformanceEnvelopeAPI, name, whyNot); }

    /// Applies this <b>multiple-apply</b> API schema to the given \p prim
    /// along with the given instance name, \p name.
    ///
    /// This information is stored by adding "PhysxDrivePerformanceEnvelopeAPI:<i>name</i>"
    /// to the token-valued, listOp metadata \em apiSchemas on the prim.
    /// For example, if \p name is 'instance1', the token
    /// 'PhysxDrivePerformanceEnvelopeAPI:instance1' is added to 'apiSchemas'.
    ///
    /// \return A valid PhysxSchemaPhysxDrivePerformanceEnvelopeAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxDrivePerformanceEnvelopeAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for
    /// conditions resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxDrivePerformanceEnvelopeAPI Apply(const UsdPrim &prim, const TfToken &name)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxDrivePerformanceEnvelopeAPI, name)) { return PhysxSchemaPhysxDrivePerformanceEnvelopeAPI(prim, name); }
        return PhysxSchemaPhysxDrivePerformanceEnvelopeAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // MAXACTUATORVELOCITY
    // --------------------------------------------------------------------- //
    /// Defines speed limit above which actuator cannot produce any torque/force.
    /// Range: [0, inf)
    /// Units: Linear joint - distance / second
    /// Angular joint - degrees / second
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float maxActuatorVelocity = inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxActuatorVelocityAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_MaxActuatorVelocity, _GetInstanceName())); }

    /// See GetMaxActuatorVelocityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxActuatorVelocityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_MaxActuatorVelocity, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // VELOCITYDEPENDENTRESISTANCE
    // --------------------------------------------------------------------- //
    /// Defines a slope of the maxForce line of the performance envelope:
    /// |F| <= maxForce - velocityDependentResistance * |jointVelocity|
    /// The available max force/torque decreases as velocity magnitude increases due to the effect of the power losses of the motor.
    /// MaxForce parameter is defined in PhysicsDriveAPI.
    /// Range: [0, inf)
    /// Units: Linear joint - force * second / distance
    /// Angular joint - torque * second / degrees
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float velocityDependentResistance = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetVelocityDependentResistanceAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_VelocityDependentResistance, _GetInstanceName())); }

    /// See GetVelocityDependentResistanceAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateVelocityDependentResistanceAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_VelocityDependentResistance, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SPEEDEFFORTGRADIENT
    // --------------------------------------------------------------------- //
    /// Defines how the maximum joint speed decreases as torque increases:
    /// |jointVelocity| <= maxActuatorVelocity - speedEffortGradient * |jointForce|
    /// It incorporates back EMF effects of the motor.
    /// Range: [0, inf)
    /// Units: Linear joint - distance / second / force
    /// Angular joint - degrees / second / torque
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float speedEffortGradient = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSpeedEffortGradientAttr() const
    { return GetPrim().GetAttribute(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_SpeedEffortGradient, _GetInstanceName())); }

    /// See GetSpeedEffortGradientAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSpeedEffortGradientAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(UsdSchemaRegistry::MakeMultipleApplyNameInstance(PhysxSchemaTokens->physxDrivePerformanceEnvelope_MultipleApplyTemplate_SpeedEffortGradient, _GetInstanceName()),
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
