// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxPhysicsDistanceJointAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXPHYSICSDISTANCEJOINTAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXPHYSICSDISTANCEJOINTAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxPhysicsDistanceJointAPI
///
/// PhysX distance joint extended parameters. Can be applied to a PhysicsDistanceJoint prim.
///
class PhysxSchemaPhysxPhysicsDistanceJointAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxPhysicsDistanceJointAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxPhysicsDistanceJointAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxPhysicsDistanceJointAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxPhysicsDistanceJointAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxPhysicsDistanceJointAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxPhysicsDistanceJointAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxPhysicsDistanceJointAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxPhysicsDistanceJointAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxPhysicsDistanceJointSpringEnabled,
            PhysxSchemaTokens->physxPhysicsDistanceJointSpringStiffness,
            PhysxSchemaTokens->physxPhysicsDistanceJointSpringDamping,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxPhysicsDistanceJointAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxPhysicsDistanceJointAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxPhysicsDistanceJointAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxPhysicsDistanceJointAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxPhysicsDistanceJointAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxPhysicsDistanceJointAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxPhysicsDistanceJointAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxPhysicsDistanceJointAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxPhysicsDistanceJointAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxPhysicsDistanceJointAPI)) { return PhysxSchemaPhysxPhysicsDistanceJointAPI(prim); }
        return PhysxSchemaPhysxPhysicsDistanceJointAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // SPRINGENABLED
    // --------------------------------------------------------------------- //
    /// If enabled, a spring/damper, i.e., soft constraint, will be used to maintain the desired
    /// distance range defined by the joint. The soft constraint will only be active when the distance
    /// between the joint frame origins is below minDistance or above maxDistance (see PhysicsDistanceJoint).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxPhysicsDistanceJoint:springEnabled = 0` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetSpringEnabledAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPhysicsDistanceJointSpringEnabled); }

    /// See GetSpringEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSpringEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPhysicsDistanceJointSpringEnabled,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SPRINGSTIFFNESS
    // --------------------------------------------------------------------- //
    /// Spring stiffness to use to resolve violation of the specified joint distance range. Will be ignored
    /// unless springEnabled is set to true. The applied force will be proportional to the length by which the distance
    /// range is violated. Let the violation be defined as geometricError = actualDistance - maxDistance
    /// if actualDistance > maxDistance, and geometricError = actualDistance - minDistance if actualDistance < minDistance.
    /// In addition, a damping term can be specified (see attribute springDamping) such that the applied force can be
    /// roughly defined as:
    /// F = (springStiffness * geometricError) - (springDamping * jointVelocity).
    /// Note that an implicit time-stepping scheme will be used to compute the force.
    /// Range: [0, inf)
    /// Units: force / distance = mass / seconds / seconds
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPhysicsDistanceJoint:springStiffness = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSpringStiffnessAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPhysicsDistanceJointSpringStiffness); }

    /// See GetSpringStiffnessAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSpringStiffnessAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPhysicsDistanceJointSpringStiffness,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // SPRINGDAMPING
    // --------------------------------------------------------------------- //
    /// Spring damping to use to resolve violation of the specified joint distance range. Will be ignored
    /// unless springEnabled is set to true. See attribute springStiffness for details.
    /// Range: [0, inf)
    /// Units: force * seconds / distance = mass / seconds
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxPhysicsDistanceJoint:springDamping = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSpringDampingAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxPhysicsDistanceJointSpringDamping); }

    /// See GetSpringDampingAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSpringDampingAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxPhysicsDistanceJointSpringDamping,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
