// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxJointAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXJOINTAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXJOINTAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxJointAPI
///
/// PhysX joint extended parameters. Can be applied to a PhysicsJoint prim or
/// the derived classes PhysicsRevoluteJoint, PhysicsPrismaticJoint or PhysicsSphericalJoint.
///
class PhysxSchemaPhysxJointAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxJointAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxJointAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxJointAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxJointAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxJointAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxJointAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxJointAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxJointAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxJointJointFriction,
            PhysxSchemaTokens->physxJointMaxJointVelocity,
            PhysxSchemaTokens->physxJointArmature,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxJointAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxJointAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxJointAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxJointAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxJointAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxJointAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxJointAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxJointAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxJointAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxJointAPI)) { return PhysxSchemaPhysxJointAPI(prim); }
        return PhysxSchemaPhysxJointAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // JOINTFRICTION
    // --------------------------------------------------------------------- //
    /// Joint friction. Only applies to joints that are part of an articulation (see PhysicsArticulationRootAPI).
    /// All joint axes will use the same friction value.
    ///
    /// The joint friction is unitless and relates the magnitudes of the linear force vector F and torque vector T
    /// transmitted from parent to child link to the maximal friction force F_resist that may be applied by the solver
    /// to resist joint motion, per axis; i.e. |F_resist| <= coefficient * (|F| + |T|), where F_resist may refer to a
    /// linear force or torque depending on the joint axis (linear vs. angular). The simulated friction effect is
    /// therefore similar to static and Coulomb friction. In order to simulate dynamic joint friction, a joint drive
    /// (see PhysicsDriveAPI) with zero stiffness and zero velocity target, and an appropriately dimensioned damping
    /// parameter should be used.
    ///
    /// Range: [0, inf)
    /// Units: dimensionless
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxJoint:jointFriction = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetJointFrictionAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxJointJointFriction); }

    /// See GetJointFrictionAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateJointFrictionAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxJointJointFriction,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MAXJOINTVELOCITY
    // --------------------------------------------------------------------- //
    /// Maximum joint velocity. Only applies to joints that are part of an articulation (see PhysicsArticulationRootAPI).
    /// All joint axes will use the same maximum joint velocity value.
    ///
    /// The solver will apply appropriate joint-space impulses in order to enforce the per-axis joint-velocity limit.
    ///
    /// Range: [0, inf)
    /// Units: Linear joint - distance / seconds
    /// Angular joint - degrees / seconds
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxJoint:maxJointVelocity = inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxJointVelocityAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxJointMaxJointVelocity); }

    /// See GetMaxJointVelocityAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxJointVelocityAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxJointMaxJointVelocity,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // ARMATURE
    // --------------------------------------------------------------------- //
    /// Conceptually, armature represents the inertia of an actuator driving the joint. It is an artificial mass/inertia
    /// that is added to the joint-space inertia and can help stabilize an articulation. Note that this parameter is used only
    /// when the joint belongs to an articulation (see PhysicsArticulationRootAPI). Furthermore, note that for a joint with
    /// multiple degrees of freedom (like a PhysicsSphericalJoint), the specified armature will be applied to each of the
    /// corresponding axes individually.
    /// Range: [0, inf)
    /// Units: Linear joint - mass
    /// Angular joint - mass * distance^2
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxJoint:armature = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetArmatureAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxJointArmature); }

    /// See GetArmatureAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateArmatureAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxJointArmature,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
