// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxAutoDeformableBodyAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXAUTODEFORMABLEBODYAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXAUTODEFORMABLEBODYAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxAutoDeformableBodyAPI
///
/// PhysxAutoDeformableBodyAPI is used to mark up a prim with OmniPhysicsDeformableBodyAPI for automatic,
/// parameter driven generation of simulation and collision mesh geometry. See PhysxAutoDeformableHexahedralMeshAPI
/// and PhysxAutoDeformableMeshSimplificationAPI for more details. Only the geometry attributes are generated by
/// OmniPhysX - the simulation and collision mesh primitives with corresponding APIs need to be created by the
/// application.
///
class PhysxSchemaPhysxAutoDeformableBodyAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxAutoDeformableBodyAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxAutoDeformableBodyAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxAutoDeformableBodyAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxAutoDeformableBodyAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxAutoDeformableBodyAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxAutoDeformableBodyAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxAutoDeformableBodyAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxAutoDeformableBodyAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxDeformableBodyAutoDeformableBodyEnabled,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxAutoDeformableBodyAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxAutoDeformableBodyAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxAutoDeformableBodyAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxAutoDeformableBodyAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxAutoDeformableBodyAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxAutoDeformableBodyAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxAutoDeformableBodyAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxAutoDeformableBodyAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxAutoDeformableBodyAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxAutoDeformableBodyAPI)) { return PhysxSchemaPhysxAutoDeformableBodyAPI(prim); }
        return PhysxSchemaPhysxAutoDeformableBodyAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // AUTODEFORMABLEBODYENABLED
    // --------------------------------------------------------------------- //
    /// Determines whether automatic mesh generation is enabled
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `bool physxDeformableBody:autoDeformableBodyEnabled = 1` |
    /// | C++ Type | bool |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Bool |
    UsdAttribute GetAutoDeformableBodyEnabledAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxDeformableBodyAutoDeformableBodyEnabled); }

    /// See GetAutoDeformableBodyEnabledAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateAutoDeformableBodyEnabledAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxDeformableBodyAutoDeformableBodyEnabled,
                   SdfValueTypeNames->Bool, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // COOKINGSOURCEMESH
    // --------------------------------------------------------------------- //
    /// Relationship to a single UsdGeomMesh prim that is used to generate the simulation and collision mesh
    /// geometry. The source mesh can reside outside of the deformable body hierachy.
    UsdRelationship GetCookingSourceMeshRel() const
    { return GetPrim().GetRelationship(PhysxSchemaTokens->physxDeformableBodyCookingSourceMesh); }

    /// See GetCookingSourceMeshRel(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create
    UsdRelationship CreateCookingSourceMeshRel() const
    { return GetPrim().CreateRelationship(PhysxSchemaTokens->physxDeformableBodyCookingSourceMesh, /* custom = */ false); }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
