// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxVehicleWheelControllerAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXVEHICLEWHEELCONTROLLERAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXVEHICLEWHEELCONTROLLERAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxVehicleWheelControllerAPI
///
/// PhysX wheel controller that samples user input and allows direct control of the wheel torques and steer angle to drive the vehicle. Has to be applied to a prim with PhysxVehicleWheelAttachmentAPI applied and be a descendant of a prim with a PhysxVehicleAPI applied.
///
class PhysxSchemaPhysxVehicleWheelControllerAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxVehicleWheelControllerAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxVehicleWheelControllerAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxVehicleWheelControllerAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxVehicleWheelControllerAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxVehicleWheelControllerAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxVehicleWheelControllerAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxVehicleWheelControllerAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxVehicleWheelControllerAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxVehicleWheelControllerDriveTorque,
            PhysxSchemaTokens->physxVehicleWheelControllerBrakeTorque,
            PhysxSchemaTokens->physxVehicleWheelControllerSteerAngle,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxVehicleWheelControllerAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxVehicleWheelControllerAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxVehicleWheelControllerAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxVehicleWheelControllerAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxVehicleWheelControllerAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxVehicleWheelControllerAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxVehicleWheelControllerAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxVehicleWheelControllerAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxVehicleWheelControllerAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxVehicleWheelControllerAPI)) { return PhysxSchemaPhysxVehicleWheelControllerAPI(prim); }
        return PhysxSchemaPhysxVehicleWheelControllerAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // DRIVETORQUE
    // --------------------------------------------------------------------- //
    /// Torque to increase wheel angular rate and speed up.
    ///
    /// Units: mass * distance * distance / seconds / seconds
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleWheelController:driveTorque = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetDriveTorqueAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleWheelControllerDriveTorque); }

    /// See GetDriveTorqueAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateDriveTorqueAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleWheelControllerDriveTorque,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // BRAKETORQUE
    // --------------------------------------------------------------------- //
    /// Torque to decrease wheel angular rate and slow down.
    /// The value has to be greater or equal zero.
    ///
    /// Units: mass * distance * distance / seconds / seconds
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleWheelController:brakeTorque = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetBrakeTorqueAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleWheelControllerBrakeTorque); }

    /// See GetBrakeTorqueAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateBrakeTorqueAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleWheelControllerBrakeTorque,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // STEERANGLE
    // --------------------------------------------------------------------- //
    /// Steer angle of the wheel in radians.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleWheelController:steerAngle = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSteerAngleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleWheelControllerSteerAngle); }

    /// See GetSteerAngleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSteerAngleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleWheelControllerSteerAngle,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
