// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxVehicleSteeringAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXVEHICLESTEERINGAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXVEHICLESTEERINGAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxVehicleSteeringAPI
///
/// Describes a steering system for a vehicle by specifying which wheels are connected to the
/// steer control and by defining the maximum steer angle for those wheels (see PhysxVehicleControllerAPI
/// for the steer control). This API schema has to be applied to a prim with PhysxVehicleAPI applied.
/// Can only be used for vehicles that have a drive (see PhysxVehicleDriveBasicAPI or
/// PhysxVehicleDriveStandardAPI).
///
class PhysxSchemaPhysxVehicleSteeringAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxVehicleSteeringAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxVehicleSteeringAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxVehicleSteeringAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxVehicleSteeringAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxVehicleSteeringAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxVehicleSteeringAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxVehicleSteeringAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxVehicleSteeringAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxVehicleSteeringWheels,
            PhysxSchemaTokens->physxVehicleSteeringMaxSteerAngle,
            PhysxSchemaTokens->physxVehicleSteeringAngleMultipliers,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxVehicleSteeringAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxVehicleSteeringAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxVehicleSteeringAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxVehicleSteeringAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxVehicleSteeringAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxVehicleSteeringAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxVehicleSteeringAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxVehicleSteeringAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxVehicleSteeringAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxVehicleSteeringAPI)) { return PhysxSchemaPhysxVehicleSteeringAPI(prim); }
        return PhysxSchemaPhysxVehicleSteeringAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // WHEELS
    // --------------------------------------------------------------------- //
    /// List of indices, referencing the wheels that are going to be steered. The indices
    /// refer to the attribute "index" of PhysxVehicleWheelAttachmentAPI. If not specified,
    /// every wheel will be affected by the steer control using an angle multiplier of 1
    /// (see attribute angleMultipliers).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `int[] physxVehicleSteering:wheels` |
    /// | C++ Type | VtArray<int> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->IntArray |
    UsdAttribute GetWheelsAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSteeringWheels); }

    /// See GetWheelsAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateWheelsAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSteeringWheels,
                   SdfValueTypeNames->IntArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // MAXSTEERANGLE
    // --------------------------------------------------------------------- //
    /// The maximum steer angle (in radians) that can be achieved by the wheels.
    /// Has to be in range [-pi, pi] when multiplied by the attribute angleMultipliers.
    /// The steer angle of wheels[i] will be defined by maxSteerAngle * angleMultipliers[i] *
    /// physxVehicleController:steer (see PhysxVehicleControllerAPI).
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxVehicleSteering:maxSteerAngle = 0` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetMaxSteerAngleAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSteeringMaxSteerAngle); }

    /// See GetMaxSteerAngleAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateMaxSteerAngleAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSteeringMaxSteerAngle,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // ANGLEMULTIPLIERS
    // --------------------------------------------------------------------- //
    /// Allows to adjust the max steer angle for each wheel that is steered. The values are
    /// unitless multipliers. See maxSteerAngle for how these multipliers affect the steer
    /// angle of a wheel. If the attribute is defined, then the length of the array needs
    /// to match the length of the "wheels" array. If the attribute is not defined,
    /// a multiplier value of 1 will be used for all steered wheels.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float[] physxVehicleSteering:angleMultipliers` |
    /// | C++ Type | VtArray<float> |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->FloatArray |
    UsdAttribute GetAngleMultipliersAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxVehicleSteeringAngleMultipliers); }

    /// See GetAngleMultipliersAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateAngleMultipliersAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxVehicleSteeringAngleMultipliers,
                   SdfValueTypeNames->FloatArray, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
