// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_codeless_api.py -- header-only codeless wrapper. DO NOT EDIT.
/// \file physxSchema/physxTriangleMeshSimplificationCollisionAPI.h
#ifndef PHYSXSCHEMA_GENERATED_PHYSXTRIANGLEMESHSIMPLIFICATIONCOLLISIONAPI_API_H
#define PHYSXSCHEMA_GENERATED_PHYSXTRIANGLEMESHSIMPLIFICATIONCOLLISIONAPI_API_H

#include "physxSchema/tokens.h"
#include <pxr/usd/usd/apiSchemaBase.h>
#include <pxr/usd/usd/typed.h>
#include <pxr/usd/usd/prim.h>
#include <pxr/usd/usd/stage.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/collectionAPI.h>
#include <pxr/usd/sdf/path.h>
#include <pxr/base/tf/type.h>
#include <algorithm>
#include <string>
#include <vector>

PXR_NAMESPACE_OPEN_SCOPE

/// \class PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI
///
/// PhysX triangle mesh simplification extended parameters
///
class PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI : public UsdAPISchemaBase
{
public:
    /// Compile time constant representing what kind of schema this class is.
    ///
    /// \sa UsdSchemaKind
    static const UsdSchemaKind schemaKind = UsdSchemaKind::SingleApplyAPI;

    static const TfType &_GetStaticTfType()
    {
        static TfType t = UsdSchemaRegistry::GetTypeFromSchemaTypeName(PhysxSchemaTokens->PhysxTriangleMeshSimplificationCollisionAPI);
        return t;
    }

    /// Construct a PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI on UsdPrim \p prim .
    /// Equivalent to PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI::Get(prim.GetStage(), prim.GetPath())
    /// for a \em valid \p prim, but will not immediately throw an error for
    /// an invalid \p prim
    explicit PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI(const UsdPrim& prim=UsdPrim()) : UsdAPISchemaBase(prim) {}

    /// Construct a PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI on the prim held by \p schemaObj .
    /// Should be preferred over PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI(schemaObj.GetPrim()),
    /// as it preserves SchemaBase state.
    explicit PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI(const UsdSchemaBase& schemaObj) : UsdAPISchemaBase(schemaObj) {}

    /// Destructor.
    virtual ~PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI() {}

    /// Return a vector of names of all pre-declared attributes for this schema
    /// class and all its ancestor classes.  Does not include attributes that
    /// may be authored by custom/extended methods of the schemas involved.
    static const TfTokenVector &GetSchemaAttributeNames(bool includeInherited=true)
    {
        static TfTokenVector localNames = {
            PhysxSchemaTokens->physxTriangleMeshSimplificationCollisionMetric,
            PhysxSchemaTokens->physxTriangleMeshSimplificationCollisionWeldTolerance,
        };
        return localNames;
    }

    /// Return a PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI holding the prim adhering to this
    /// schema at \p path on \p stage.  If no prim exists at \p path on
    /// \p stage, or if the prim at that path does not adhere to this schema,
    /// return an invalid schema object.  This is shorthand for the following:
    ///
    /// \code
    /// PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI(stage->GetPrimAtPath(path));
    /// \endcode
    ///
    static PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI Get(const UsdStagePtr &stage, const SdfPath &path)
    { return PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI(stage->GetPrimAtPath(path)); }

    /// Returns true if this <b>single-apply</b> API schema can be applied to
    /// the given \p prim. If this schema can not be a applied to the prim,
    /// this returns false and, if provided, populates \p whyNot with the
    /// reason it can not be applied.
    ///
    /// Note that if CanApply returns false, that does not necessarily imply
    /// that calling Apply will fail. Callers are expected to call CanApply
    /// before calling Apply if they want to ensure that it is valid to
    /// apply a schema.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static bool CanApply(const UsdPrim &prim, std::string *whyNot=nullptr)
    { return prim.CanApplyAPI(PhysxSchemaTokens->PhysxTriangleMeshSimplificationCollisionAPI, whyNot); }

    /// Applies this <b>single-apply</b> API schema to the given \p prim.
    /// This information is stored by adding "PhysxTriangleMeshSimplificationCollisionAPI" to the
    /// token-valued, listOp metadata \em apiSchemas on the prim.
    ///
    /// \return A valid PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI object is returned upon success.
    /// An invalid (or empty) PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI object is returned upon
    /// failure. See \ref UsdPrim::ApplyAPI() for conditions
    /// resulting in failure.
    ///
    /// \sa UsdPrim::GetAppliedSchemas()
    /// \sa UsdPrim::HasAPI()
    /// \sa UsdPrim::CanApplyAPI()
    /// \sa UsdPrim::ApplyAPI()
    /// \sa UsdPrim::RemoveAPI()
    static PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI Apply(const UsdPrim &prim)
    {
        if (prim.ApplyAPI(PhysxSchemaTokens->PhysxTriangleMeshSimplificationCollisionAPI)) { return PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI(prim); }
        return PhysxSchemaPhysxTriangleMeshSimplificationCollisionAPI();
    }

public:
    // --------------------------------------------------------------------- //
    // SIMPLIFICATIONMETRIC
    // --------------------------------------------------------------------- //
    /// Mesh simplification accuracy.
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxTriangleMeshSimplificationCollision:metric = 0.55` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetSimplificationMetricAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxTriangleMeshSimplificationCollisionMetric); }

    /// See GetSimplificationMetricAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateSimplificationMetricAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxTriangleMeshSimplificationCollisionMetric,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

public:
    // --------------------------------------------------------------------- //
    // WELDTOLERANCE
    // --------------------------------------------------------------------- //
    /// Mesh weld tolerance, controls the distance at which vertices are welded.
    /// Default -inf will autocompute the welding tolerance based on the mesh size. Zero value will disable welding.
    /// Range: [0, inf)
    /// Units: distance
    ///
    /// | ||
    /// | -- | -- |
    /// | Declaration | `float physxTriangleMeshSimplificationCollision:weldTolerance = -inf` |
    /// | C++ Type | float |
    /// | \ref Usd_Datatypes "Usd Type" | SdfValueTypeNames->Float |
    UsdAttribute GetWeldToleranceAttr() const
    { return GetPrim().GetAttribute(PhysxSchemaTokens->physxTriangleMeshSimplificationCollisionWeldTolerance); }

    /// See GetWeldToleranceAttr(), and also
    /// \ref Usd_Create_Or_Get_Property for when to use Get vs Create.
    /// If specified, author \p defaultValue as the attribute's default,
    /// sparsely (when it makes sense to do so) if \p writeSparsely is \c true -
    /// the default for \p writeSparsely is \c false.
    UsdAttribute CreateWeldToleranceAttr(VtValue const &defaultValue = VtValue(), bool writeSparsely=false) const
    {
        return UsdSchemaBase::_CreateAttr(PhysxSchemaTokens->physxTriangleMeshSimplificationCollisionWeldTolerance,
                   SdfValueTypeNames->Float, /* custom = */ false,
                   SdfVariabilityVarying, defaultValue, writeSparsely);
    }

protected:
    /// Returns the kind of schema this class belongs to.
    ///
    /// \sa UsdSchemaKind
    UsdSchemaKind _GetSchemaKind() const override { return schemaKind; }
    const TfType &_GetTfType() const override { return _GetStaticTfType(); }
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
