# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Bounded parallel execution for cmake -P test drivers.
# Each job is a self-contained shell/batch script. The runner starts at most
# MAX_JOBS at a time and waits for completion before launching more.
# Per-job wall time defaults to 120s (override: -DOVPHYSX_PARALLEL_JOB_TIMEOUT=N).

include_guard(GLOBAL)

function(_ovphysx_shell_single_quote OUT_VAR VALUE)
    string(REPLACE "'" "'\\''" _escaped "${VALUE}")
    set(${OUT_VAR} "'${_escaped}'" PARENT_SCOPE)
endfunction()

function(_ovphysx_cmd_double_quote OUT_VAR VALUE)
    string(REPLACE "\"" "\"\"" _escaped "${VALUE}")
    set(${OUT_VAR} "\"${_escaped}\"" PARENT_SCOPE)
endfunction()

function(_ovphysx_join_shell_args OUT_VAR)
    set(_parts "")
    foreach(_arg IN LISTS ARGN)
        _ovphysx_shell_single_quote(_quoted "${_arg}")
        list(APPEND _parts "${_quoted}")
    endforeach()
    string(JOIN " " _joined ${_parts})
    set(${OUT_VAR} "${_joined}" PARENT_SCOPE)
endfunction()

function(_ovphysx_join_cmd_args OUT_VAR)
    set(_parts "")
    foreach(_arg IN LISTS ARGN)
        _ovphysx_cmd_double_quote(_quoted "${_arg}")
        list(APPEND _parts "${_quoted}")
    endforeach()
    string(JOIN " " _joined ${_parts})
    set(${OUT_VAR} "${_joined}" PARENT_SCOPE)
endfunction()

# Write a job script that runs one COMMAND (argv list) in WORKING_DIR.
function(ovphysx_write_job_script SCRIPT_PATH WORKING_DIR)
    if(WIN32)
        _ovphysx_cmd_double_quote(_work_dir_quoted "${WORKING_DIR}")
        _ovphysx_join_cmd_args(_cmd_line ${ARGN})
        file(WRITE "${SCRIPT_PATH}" "@echo off\r\n")
        file(APPEND "${SCRIPT_PATH}" "cd /d ${_work_dir_quoted}\r\n")
        file(APPEND "${SCRIPT_PATH}" "${_cmd_line}\r\n")
        file(APPEND "${SCRIPT_PATH}" "if errorlevel 1 exit /b 1\r\n")
        file(APPEND "${SCRIPT_PATH}" "exit /b 0\r\n")
    else()
        _ovphysx_shell_single_quote(_work_dir_quoted "${WORKING_DIR}")
        _ovphysx_join_shell_args(_cmd_line ${ARGN})
        file(WRITE "${SCRIPT_PATH}" "#!/usr/bin/env bash\n")
        file(APPEND "${SCRIPT_PATH}" "set -euo pipefail\n")
        file(APPEND "${SCRIPT_PATH}" "cd ${_work_dir_quoted}\n")
        file(APPEND "${SCRIPT_PATH}" "exec ${_cmd_line}\n")
    endif()
endfunction()

# Run JOB_SCRIPT_PATHS with at most MAX_JOBS concurrent processes.
function(ovphysx_run_job_scripts_parallel MAX_JOBS JOB_SCRIPT_PATHS
         OUT_FAILED_SCRIPT_PATHS OUT_COMBINED_OUTPUT)
    list(LENGTH JOB_SCRIPT_PATHS _job_count)
    if(_job_count EQUAL 0)
        set(${OUT_FAILED_SCRIPT_PATHS} "" PARENT_SCOPE)
        set(${OUT_COMBINED_OUTPUT} "" PARENT_SCOPE)
        return()
    endif()

    if(MAX_JOBS LESS 1)
        set(MAX_JOBS 1)
    endif()

    set(_job_timeout_sec 120)
    if(DEFINED OVPHYSX_PARALLEL_JOB_TIMEOUT AND NOT "${OVPHYSX_PARALLEL_JOB_TIMEOUT}" STREQUAL "")
        set(_job_timeout_sec "${OVPHYSX_PARALLEL_JOB_TIMEOUT}")
    endif()
    if(_job_timeout_sec LESS 1)
        set(_job_timeout_sec 1)
    endif()
    math(EXPR _job_timeout_ms "${_job_timeout_sec} * 1000")

    list(GET JOB_SCRIPT_PATHS 0 _first_script)
    get_filename_component(_runner_dir "${_first_script}" DIRECTORY)

    if(WIN32)
        set(_runner "${_runner_dir}/_ovphysx_parallel_jobs.ps1")
        set(_lines "$ErrorActionPreference = 'Stop'\n")
        string(APPEND _lines "$maxJobs = ${MAX_JOBS}\n")
        string(APPEND _lines "$jobTimeoutMs = ${_job_timeout_ms}\n")
        string(APPEND _lines "$scripts = @(\n")
        set(_script_idx 0)
        foreach(_script IN LISTS JOB_SCRIPT_PATHS)
            math(EXPR _script_idx "${_script_idx} + 1")
            if(_script_idx EQUAL _job_count)
                string(APPEND _lines "  '${_script}'\n")
            else()
                string(APPEND _lines "  '${_script}',\n")
            endif()
        endforeach()
        string(APPEND _lines ")\n")
        string(APPEND _lines "$failed = @()\n")
        string(APPEND _lines "$queue = [System.Collections.Queue]::new()\n")
        string(APPEND _lines "foreach ($s in $scripts) { [void]$queue.Enqueue($s) }\n")
        string(APPEND _lines "$running = @()\n")
        string(APPEND _lines "while ($queue.Count -gt 0 -or $running.Count -gt 0) {\n")
        string(APPEND _lines "  while ($running.Count -lt $maxJobs -and $queue.Count -gt 0) {\n")
        string(APPEND _lines "    $scriptPath = [string]$queue.Dequeue()\n")
        string(APPEND _lines "    $logPath = \"$scriptPath.log\"\n")
        string(APPEND _lines "    $proc = Start-Process -FilePath 'cmd.exe' -ArgumentList @('/c', $scriptPath) `\n")
        string(APPEND _lines "      -RedirectStandardOutput $logPath -RedirectStandardError \"\${scriptPath}.err.log\" `\n")
        string(APPEND _lines "      -PassThru -NoNewWindow -Wait:$false\n")
        string(APPEND _lines "    $running += [PSCustomObject]@{ Script = $scriptPath; Process = $proc; StartTime = Get-Date }\n")
        string(APPEND _lines "  }\n")
        string(APPEND _lines "  $stillRunning = @()\n")
        string(APPEND _lines "  foreach ($entry in $running) {\n")
        string(APPEND _lines "    if ($entry.Process.HasExited) {\n")
        string(APPEND _lines "      $null = $entry.Process.WaitForExit()\n")
        string(APPEND _lines "      if ($entry.Process.ExitCode -ne 0) { $failed += $entry.Script }\n")
        string(APPEND _lines "    } else {\n")
        string(APPEND _lines "      $elapsedMs = ((Get-Date) - $entry.StartTime).TotalMilliseconds\n")
        string(APPEND _lines "      if ($elapsedMs -ge $jobTimeoutMs) {\n")
        string(APPEND _lines "        $entry.Process.Kill() | Out-Null\n")
        string(APPEND _lines "        $failed += $entry.Script\n")
        string(APPEND _lines "      } else { $stillRunning += $entry }\n")
        string(APPEND _lines "    }\n")
        string(APPEND _lines "  }\n")
        string(APPEND _lines "  $running = $stillRunning\n")
        string(APPEND _lines "  if ($running.Count -gt 0) { Start-Sleep -Milliseconds 100 }\n")
        string(APPEND _lines "}\n")
        string(APPEND _lines "if ($failed.Count -gt 0) { $failed | ConvertTo-Json -Compress | Set-Content -Path '${_runner_dir}/_ovphysx_parallel_failed.json' -Encoding UTF8; exit 1 }\n")
        string(APPEND _lines "exit 0\n")
        file(WRITE "${_runner}" "${_lines}")
        execute_process(
            COMMAND powershell.exe -NoProfile -ExecutionPolicy Bypass -File "${_runner}"
            RESULT_VARIABLE _runner_result
        )
    else()
        set(_runner "${_runner_dir}/_ovphysx_parallel_jobs.sh")
        set(_failed_list "${_runner_dir}/_ovphysx_parallel_failed.list")
        file(WRITE "${_runner}" "#!/usr/bin/env bash\n")
        file(APPEND "${_runner}" "set -euo pipefail\n")
        file(APPEND "${_runner}" "MAX_JOBS=${MAX_JOBS}\n")
        file(APPEND "${_runner}" "JOB_TIMEOUT_SEC=${_job_timeout_sec}\n")
        file(APPEND "${_runner}" "FAILED_LIST='${_failed_list}'\n")
        file(APPEND "${_runner}" ": > \"\${FAILED_LIST}\"\n")
        file(APPEND "${_runner}" "running_pids=()\n")
        file(APPEND "${_runner}" "running_scripts=()\n")
        file(APPEND "${_runner}" "reap_finished_jobs() {\n")
        file(APPEND "${_runner}" "  local still_pids=()\n")
        file(APPEND "${_runner}" "  local still_scripts=()\n")
        file(APPEND "${_runner}" "  local idx\n")
        file(APPEND "${_runner}" "  for idx in \"\${!running_pids[@]}\"; do\n")
        file(APPEND "${_runner}" "    local pid=\"\${running_pids[\${idx}]}\"\n")
        file(APPEND "${_runner}" "    local script=\"\${running_scripts[\${idx}]}\"\n")
        file(APPEND "${_runner}" "    if kill -0 \"\${pid}\" 2>/dev/null; then\n")
        file(APPEND "${_runner}" "      still_pids+=(\"\${pid}\")\n")
        file(APPEND "${_runner}" "      still_scripts+=(\"\${script}\")\n")
        file(APPEND "${_runner}" "    else\n")
        file(APPEND "${_runner}" "      if ! wait \"\${pid}\"; then\n")
        file(APPEND "${_runner}" "        echo \"\${script}\" >> \"\${FAILED_LIST}\"\n")
        file(APPEND "${_runner}" "      fi\n")
        file(APPEND "${_runner}" "    fi\n")
        file(APPEND "${_runner}" "  done\n")
        file(APPEND "${_runner}" "  running_pids=(\${still_pids[@]+\"\${still_pids[@]}\"})\n")
        file(APPEND "${_runner}" "  running_scripts=(\${still_scripts[@]+\"\${still_scripts[@]}\"})\n")
        file(APPEND "${_runner}" "}\n")
        file(APPEND "${_runner}" "wait_for_slot() {\n")
        file(APPEND "${_runner}" "  while [ \"\${#running_pids[@]}\" -ge \"\${MAX_JOBS}\" ]; do\n")
        file(APPEND "${_runner}" "    if wait -n 2>/dev/null; then\n")
        file(APPEND "${_runner}" "      :\n")
        file(APPEND "${_runner}" "    else\n")
        file(APPEND "${_runner}" "      sleep 0.05\n")
        file(APPEND "${_runner}" "    fi\n")
        file(APPEND "${_runner}" "    reap_finished_jobs\n")
        file(APPEND "${_runner}" "  done\n")
        file(APPEND "${_runner}" "}\n")
        foreach(_script IN LISTS JOB_SCRIPT_PATHS)
            _ovphysx_shell_single_quote(_script_quoted "${_script}")
            file(APPEND "${_runner}" "wait_for_slot\n")
            file(APPEND "${_runner}" "timeout \"\${JOB_TIMEOUT_SEC}\" bash ${_script_quoted} >${_script_quoted}.log 2>${_script_quoted}.err.log &\n")
            file(APPEND "${_runner}" "running_pids+=(\$!)\n")
            file(APPEND "${_runner}" "running_scripts+=(${_script_quoted})\n")
        endforeach()
        file(APPEND "${_runner}" "while [ \"\${#running_pids[@]}\" -gt 0 ]; do\n")
        file(APPEND "${_runner}" "  if wait -n 2>/dev/null; then\n")
        file(APPEND "${_runner}" "    :\n")
        file(APPEND "${_runner}" "  else\n")
        file(APPEND "${_runner}" "    sleep 0.05\n")
        file(APPEND "${_runner}" "  fi\n")
        file(APPEND "${_runner}" "  reap_finished_jobs\n")
        file(APPEND "${_runner}" "done\n")
        file(APPEND "${_runner}" "if [ -s \"\${FAILED_LIST}\" ]; then\n")
        file(APPEND "${_runner}" "  exit 1\n")
        file(APPEND "${_runner}" "fi\n")
        file(APPEND "${_runner}" "exit 0\n")
        execute_process(
            COMMAND bash "${_runner}"
            RESULT_VARIABLE _runner_result
        )
    endif()

    set(_failed "")
    if(WIN32)
        set(_failed_json "${_runner_dir}/_ovphysx_parallel_failed.json")
        if(EXISTS "${_failed_json}")
            file(READ "${_failed_json}" _failed_json_content)
            string(JSON _failed ERROR_VARIABLE _json_err GET "${_failed_json_content}")
            if(_json_err)
                set(_failed "${JOB_SCRIPT_PATHS}")
            endif()
        endif()
    else()
        set(_failed_list "${_runner_dir}/_ovphysx_parallel_failed.list")
        if(EXISTS "${_failed_list}")
            file(READ "${_failed_list}" _failed_list_content)
            string(STRIP "${_failed_list_content}" _failed_list_content)
            string(REPLACE "\n" ";" _failed "${_failed_list_content}")
        endif()
    endif()

    if(NOT _runner_result EQUAL 0 AND _failed STREQUAL "")
        set(_failed "${JOB_SCRIPT_PATHS}")
    endif()

    set(_combined "")
    foreach(_script IN LISTS JOB_SCRIPT_PATHS)
        set(_log "${_script}.log")
        set(_err "${_script}.err.log")
        if(EXISTS "${_log}")
            file(READ "${_log}" _log_content)
            string(APPEND _combined "${_log_content}")
        endif()
        if(EXISTS "${_err}")
            file(READ "${_err}" _err_content)
            string(APPEND _combined "${_err_content}")
        endif()
    endforeach()

    set(${OUT_FAILED_SCRIPT_PATHS} "${_failed}" PARENT_SCOPE)
    set(${OUT_COMBINED_OUTPUT} "${_combined}" PARENT_SCOPE)
endfunction()

function(ovphysx_compute_lifecycle_test_jobs OUT_VAR)
    if(DEFINED OVPHYSX_LIFECYCLE_JOBS AND NOT "${OVPHYSX_LIFECYCLE_JOBS}" STREQUAL "")
        set(${OUT_VAR} "${OVPHYSX_LIFECYCLE_JOBS}" PARENT_SCOPE)
        return()
    endif()
    ovphysx_compute_build_jobs(_build_jobs)
    if(_build_jobs GREATER 4)
        set(_jobs 4)
    else()
        set(_jobs ${_build_jobs})
    endif()
    if(_jobs LESS 1)
        set(_jobs 1)
    endif()
    set(${OUT_VAR} ${_jobs} PARENT_SCOPE)
endfunction()
