## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build ServerTest template
#

#IF(PX_CLOUD_GENERATE_STATIC_LIBRARIES)
#	SET(GRIDSERVER_CLOUD_LIBTYPE CLOUD_STATIC_LIB)
#ENDIF()

SET(PVDRUNTIME_COMPILE_DEFS
	# Common to all configurations
	WIN32;WIN64;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_DEPRECATE;_WINSOCK_DEPRECATED_NO_WARNINGS;${PHYSX_LIBTYPE_DEFS};
	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

SET(PVDRUNTIME_PLATFORM_LINKED_LIBS
	Ws2_32
)

set(PVDRUNTIME_COMPILE_PDB_NAME_DEBUG "PVDRuntime_static${CMAKE_DEBUG_POSTFIX}")
set(PVDRUNTIME_COMPILE_PDB_NAME_CHECKED "PVDRuntime_static${CMAKE_CHECKED_POSTFIX}")
set(PVDRUNTIME_COMPILE_PDB_NAME_PROFILE "PVDRuntime_static${CMAKE_PROFILE_POSTFIX}")
set(PVDRUNTIME_COMPILE_PDB_NAME_RELEASE "PVDRuntime_static${CMAKE_RELEASE_POSTFIX}")
