## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXGpu
#

SET(PHYSXGPU_PLATFORM_LINKED_LIBS DelayImp.lib CUDA::cuda_driver)


SET(PHYSXGPU_LINK_FLAGS "/MAP")
SET(PHYSXGPU_LINK_FLAGS_DEBUG "/DELAYLOAD:nvcuda.dll")
SET(PHYSXGPU_LINK_FLAGS_CHECKED "/DELAYLOAD:nvcuda.dll")
SET(PHYSXGPU_LINK_FLAGS_PROFILE "/DELAYLOAD:nvcuda.dll")
SET(PHYSXGPU_LINK_FLAGS_RELEASE "/DELAYLOAD:nvcuda.dll")

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXGPU_LIBTYPE STATIC)
ELSE()
	SET(PHYSXGPU_LIBTYPE SHARED)
	SET(PXPHYSXGPU_LIBTYPE_DEFS
		PX_PHYSX_GPU_EXPORTS;
	)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};${PXPHYSXGPU_LIBTYPE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXGPU_PLATFORM_OBJECT_FILES
		$<TARGET_OBJECTS:PhysXBroadphaseGpu>
		$<TARGET_OBJECTS:PhysXNarrowphaseGpu>
		$<TARGET_OBJECTS:PhysXSimulationControllerGpu>
		$<TARGET_OBJECTS:PhysXSolverGpu>
		$<TARGET_OBJECTS:PhysXCommonGpu>
		$<TARGET_OBJECTS:PhysXCudaContextManager>
	)
ELSE()
	SET(PHYSXGPU_PRIVATE_PLATFORM_LINKED_LIBS
		PhysXBroadphaseGpu PhysXNarrowphaseGpu PhysXSimulationControllerGpu PhysXSolverGpu PhysXCommonGpu PhysXCudaContextManager PhysXArticulationGpu
	)
ENDIF()

# Single source of truth for PHYSXGPU_RESOURCE. Also included by
# cmake/windows/CMakeLists.txt in source-distro mode when GPU is off so the
# Linux-host public flow enumerates these files via windows-crosscompile.
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/PhysXGpuPlatformFiles.cmake)
SOURCE_GROUP(resource FILES ${PHYSXGPU_RESOURCE})

SET(PHYSXGPU_PLATFORM_SOURCES
    ${PHYSXGPU_RESOURCE}
	${PHYSXGPU_PLATFORM_OBJECT_FILES}
)

IF(PHYSXGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXGPU_COMPILE_PDB_NAME_DEBUG "PhysXGpu_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXGPU_COMPILE_PDB_NAME_CHECKED "PhysXGpu_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXGPU_COMPILE_PDB_NAME_PROFILE "PhysXGpu_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXGPU_COMPILE_PDB_NAME_RELEASE "PhysXGpu_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXGPU_COMPILE_PDB_NAME_DEBUG "PhysXGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXGPU_COMPILE_PDB_NAME_CHECKED "PhysXGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXGPU_COMPILE_PDB_NAME_PROFILE "PhysXGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXGPU_COMPILE_PDB_NAME_RELEASE "PhysXGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()

IF(PHYSXGPU_LIBTYPE STREQUAL "SHARED")
	INSTALL(FILES $<TARGET_PDB_FILE:PhysXGpu>
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ELSE()
	INSTALL(FILES ${PHYSX_ROOT_DIR}/$<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile>/$<$<CONFIG:debug>:${PHYSXGPU_COMPILE_PDB_NAME_DEBUG}>$<$<CONFIG:checked>:${PHYSXGPU_COMPILE_PDB_NAME_CHECKED}>$<$<CONFIG:profile>:${PHYSXGPU_COMPILE_PDB_NAME_PROFILE}>$<$<CONFIG:release>:${PHYSXGPU_COMPILE_PDB_NAME_RELEASE}>.pdb
		DESTINATION $<$<CONFIG:debug>:${PX_ROOT_LIB_DIR}/debug>$<$<CONFIG:release>:${PX_ROOT_LIB_DIR}/release>$<$<CONFIG:checked>:${PX_ROOT_LIB_DIR}/checked>$<$<CONFIG:profile>:${PX_ROOT_LIB_DIR}/profile> OPTIONAL)
ENDIF()
