## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXNarrowphaseGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXNARROWPHASEGPU_LIBTYPE OBJECT)
ELSE()
	SET(PHYSXNARROWPHASEGPU_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXNARROWPHASEGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(PHYSXNARROWPHASEGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_DEBUG "PhysXNarrowphaseGpu_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_CHECKED "PhysXNarrowphaseGpu_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_PROFILE "PhysXNarrowphaseGpu_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_RELEASE "PhysXNarrowphaseGpu_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_DEBUG "PhysXNarrowphaseGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_CHECKED "PhysXNarrowphaseGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_PROFILE "PhysXNarrowphaseGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXNPGPU_COMPILE_PDB_NAME_RELEASE "PhysXNarrowphaseGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()