## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXSolverGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXSOLVERGPU_LIBTYPE OBJECT)
ELSE()
	SET(PHYSXSOLVERGPU_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXSOLVERGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(PHYSXSOLVERGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_DEBUG "PhysXSolverGpu_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_CHECKED "PhysXSolverGpu_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_PROFILE "PhysXSolverGpu_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_RELEASE "PhysXSolverGpu_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_DEBUG "PhysXSolverGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_CHECKED "PhysXSolverGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_PROFILE "PhysXSolverGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXSOLVERGPU_COMPILE_PDB_NAME_RELEASE "PhysXSolverGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()