## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXSimulationControllerGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXSIMULATIONCONTROLLERGPU_LIBTYPE OBJECT)
ELSE()
	SET(PHYSXSIMULATIONCONTROLLERGPU_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXSIMULATIONCONTROLLERGPU_COMPILE_DEFS

	# Common to all configurations
	PRIVATE ${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	PRIVATE $<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(PHYSXSIMULATIONCONTROLLERGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_DEBUG "PhysXSimulationControllerGpu_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_CHECKED "PhysXSimulationControllerGpu_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_PROFILE "PhysXSimulationControllerGpu_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_RELEASE "PhysXSimulationControllerGpu_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_DEBUG "PhysXSimulationControllerGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_CHECKED "PhysXSimulationControllerGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_PROFILE "PhysXSimulationControllerGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXSCGPU_COMPILE_PDB_NAME_RELEASE "PhysXSimulationControllerGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()