## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXBroadphaseGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXBROADPHASEGPU_LIBTYPE OBJECT)
ELSE()
	SET(PHYSXBROADPHASEGPU_LIBTYPE STATIC)
ENDIF()

IF(PHYSXBROADPHASEGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_DEBUG "PhysXBroadphaseGpu_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_CHECKED "PhysXBroadphaseGpu_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_PROFILE "PhysXBroadphaseGpu_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_RELEASE "PhysXBroadphaseGpu_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_DEBUG "PhysXBroadphaseGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_CHECKED "PhysXBroadphaseGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_PROFILE "PhysXBroadphaseGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXBROADPHASEGPU_COMPILE_PDB_NAME_RELEASE "PhysXBroadphaseGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXBROADPHASEGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)
