## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXArticulationGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXARTICULATIONGPU_LIBTYPE OBJECT)
ELSE()
	SET(PHYSXARTICULATIONGPU_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXARTICULATIONGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(USE_GAMEWORKS_OUTPUT_DIRS AND PHYSXARTICULATIONGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_DEBUG "PhysXArticulationGpu_static_${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_CHECKED "PhysXArticulationGpu_static_${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_PROFILE "PhysXArticulationGpu_static_${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_RELEASE "PhysXArticulationGpu_static_${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_DEBUG "PhysXArticulationGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_CHECKED "PhysXArticulationGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_PROFILE "PhysXArticulationGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXARTICULATIONGPU_COMPILE_PDB_NAME_RELEASE "PhysXArticulationGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()
