## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXCommonGpu
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(PHYSXCOMMONGPU_LIBTYPE OBJECT)
ELSE()
	SET(PHYSXCOMMONGPU_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(PHYSXCOMMONGPU_COMPILE_DEFS

	# Common to all configurations
	${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	$<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	$<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	$<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	$<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

IF(PHYSXCOMMONGPU_LIBTYPE STREQUAL "STATIC")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_DEBUG "PhysXCommonGpu_static${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_CHECKED "PhysXCommonGpu_static${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_PROFILE "PhysXCommonGpu_static${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_RELEASE "PhysXCommonGpu_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_DEBUG "PhysXCommonGpu${CMAKE_DEBUG_POSTFIX}")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_CHECKED "PhysXCommonGpu${CMAKE_CHECKED_POSTFIX}")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_PROFILE "PhysXCommonGpu${CMAKE_PROFILE_POSTFIX}")
	SET(PHYSXCOMMONGPU_COMPILE_PDB_NAME_RELEASE "PhysXCommonGpu${CMAKE_RELEASE_POSTFIX}")
ENDIF()