## SPDX-FileCopyrightText: Copyright (c) 2008-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
## SPDX-License-Identifier: Apache-2.0

#
# Build PhysXCudaContextManager
#

IF(PX_GENERATE_GPU_STATIC_LIBRARIES)
	SET(CUDACONTEXTMANAGER_LIBTYPE OBJECT)
ELSE()
	SET(CUDACONTEXTMANAGER_LIBTYPE STATIC)
ENDIF()

# Use generator expressions to set config specific preprocessor definitions
SET(CUDACONTEXTMANAGER_COMPILE_DEFS
	# Common to all configurations
	PRIVATE ${PHYSX_WINDOWS_COMPILE_DEFS};PX_PHYSX_STATIC_LIB;${PHYSXGPU_LIBTYPE_DEFS}

	PRIVATE $<$<CONFIG:debug>:${PHYSX_WINDOWS_DEBUG_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:checked>:${PHYSX_WINDOWS_CHECKED_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:profile>:${PHYSX_WINDOWS_PROFILE_COMPILE_DEFS};>
	PRIVATE $<$<CONFIG:release>:${PHYSX_WINDOWS_RELEASE_COMPILE_DEFS};>
)

SET(CUDACONTEXTMANAGER_PLATFORM_SOURCES
)

SET(CUDACONTEXTMANAGER_PLAFORM_HEADERS
)


IF(CUDACONTEXTMANAGER_LIBTYPE STREQUAL "STATIC")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_DEBUG "PhysXCudaContextManager_static${CMAKE_DEBUG_POSTFIX}")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_CHECKED "PhysXCudaContextManager_static${CMAKE_CHECKED_POSTFIX}")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_PROFILE "PhysXCudaContextManager_static${CMAKE_PROFILE_POSTFIX}")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_RELEASE "PhysXCudaContextManager_static${CMAKE_RELEASE_POSTFIX}")
ELSE()
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_DEBUG "PhysXCudaContextManager${CMAKE_DEBUG_POSTFIX}")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_CHECKED "PhysXCudaContextManager${CMAKE_CHECKED_POSTFIX}")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_PROFILE "PhysXCudaContextManager${CMAKE_PROFILE_POSTFIX}")
	SET(CUDACONTEXTMANAGER_COMPILE_PDB_NAME_RELEASE "PhysXCudaContextManager${CMAKE_RELEASE_POSTFIX}")
ENDIF()