#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
"""Generate a C++ header with PXR TfToken definitions from a Newton USD schema.

Parses a generatedSchema.usda file and emits a header containing a token list
macro suitable for use with TF_DECLARE_PUBLIC_TOKENS / TF_DEFINE_PUBLIC_TOKENS
(or TF_DEFINE_PRIVATE_TOKENS for file-local usage).

Usage:
    python gen_newton_tokens.py <schema.usda> -o <output.h>
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import List, Tuple


# ---------------------------------------------------------------------------
# USDA parsing
# ---------------------------------------------------------------------------

def _attr_name_to_identifier(attr_name: str) -> str:
    """Convert a USD attribute name to a C++ identifier.

    ``newton:xpbd:softBodyRelaxation`` -> ``newtonXpbdSoftBodyRelaxation``
    """
    parts = attr_name.split(":")
    result = parts[0]
    for part in parts[1:]:
        result += part[0].upper() + part[1:]
    return result


def parse_schema(usda_path: str) -> Tuple[List[Tuple[str, str]], List[Tuple[str, str]], List[Tuple[str, str]]]:
    """Parse a generatedSchema.usda and return (attributes, classes, allowed_tokens).

    Each entry is (cpp_identifier, token_string).
    """
    with open(usda_path, "r") as f:
        text = f.read()

    attributes: List[Tuple[str, str]] = []
    classes: List[Tuple[str, str]] = []
    allowed_tokens: List[Tuple[str, str]] = []

    seen = set()

    # Extract class names:  class ClassName "ClassName" (
    # Also handles:  class "ClassName" (
    for m in re.finditer(r'^class\s+"?(\w+)"?\s', text, re.MULTILINE):
        name = m.group(1)
        if name not in seen:
            classes.append((name, name))
            seen.add(name)

    # Extract attribute names: TYPE newton:some:attr = DEFAULT (
    # Also handles: rel newton:relName (
    for m in re.finditer(
        r'^\s+(?:uniform\s+)?(?:bool|int|float|double|token|string|rel|asset|color3f|point3f|vector3f|normal3f|matrix4d)\s+(newton:\S+)',
        text, re.MULTILINE
    ):
        attr = m.group(1)
        # Strip trailing = or ( if captured
        attr = attr.rstrip("=(").strip()
        if attr not in seen:
            ident = _attr_name_to_identifier(attr)
            attributes.append((ident, attr))
            seen.add(attr)

    # Extract allowed token values: allowedTokens = ["tok1", "tok2", ...]
    for m in re.finditer(r'allowedTokens\s*=\s*\[([^\]]+)\]', text):
        tokens_str = m.group(1)
        for tok_m in re.finditer(r'"([^"]+)"', tokens_str):
            tok = tok_m.group(1)
            if tok not in seen:
                # For simple identifiers keep as-is; for others make safe
                ident = tok if tok.isidentifier() else tok.replace("-", "_").replace(".", "_")
                allowed_tokens.append((ident, tok))
                seen.add(tok)

    return attributes, classes, allowed_tokens


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
// Auto-generated by gen_newton_tokens.py - DO NOT EDIT.
//
// PXR TfToken definitions for Newton USD schema attributes.
// Source: {source_basename}
//
// Usage (public tokens - one .cpp must define them):
//   // In a header:
//   TF_DECLARE_PUBLIC_TOKENS(NewtonSchemaTokens, NEWTON_SCHEMA_TOKENS);
//   // In exactly one .cpp:
//   TF_DEFINE_PUBLIC_TOKENS(NewtonSchemaTokens, NEWTON_SCHEMA_TOKENS);
//
// Usage (private / file-local tokens):
//   TF_DEFINE_PRIVATE_TOKENS(_newtonTokens, NEWTON_SCHEMA_TOKENS);

#pragma once

// clang-format off
#define NEWTON_SCHEMA_TOKENS \\
{token_lines}
// clang-format on
"""


def _format_token_entry(ident: str, value: str) -> str:
    """Format a single token entry for the macro."""
    if ident == value:
        return f"    ({ident})"
    return f'    (({ident}, "{value}"))'


def generate_header(
    attributes: List[Tuple[str, str]],
    classes: List[Tuple[str, str]],
    allowed_tokens: List[Tuple[str, str]],
    source_basename: str,
) -> str:
    lines = []

    if classes:
        lines.append("    /* API schema class names */")
        for ident, value in sorted(classes, key=lambda x: x[0]):
            lines.append(_format_token_entry(ident, value))
        lines.append("")

    if attributes:
        lines.append("    /* Attribute names */")
        for ident, value in sorted(attributes, key=lambda x: x[0]):
            lines.append(_format_token_entry(ident, value))
        lines.append("")

    # Allowed token values (none, internal, containers, etc.) are intentionally
    # excluded — they clash with common C++ symbols from USD/boost/STL headers
    # and are not needed by the Newton → PhysX compatibility layer.

    # Join with continuation backslashes; last line has no backslash
    token_block = []
    all_lines = [l for l in lines if l]  # remove empty trailing
    for i, line in enumerate(all_lines):
        if i < len(all_lines) - 1:
            token_block.append(line + " \\")
        else:
            token_block.append(line)

    return _HEADER_TEMPLATE.format(
        source_basename=source_basename,
        token_lines="\n".join(token_block),
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description="Generate PXR token header from Newton USD schema.")
    parser.add_argument("schema", help="Path to generatedSchema.usda")
    parser.add_argument("-o", "--output", required=True, help="Output header file path")
    args = parser.parse_args()

    if not os.path.isfile(args.schema):
        print(f"ERROR: Schema file not found: {args.schema}", file=sys.stderr)
        return 1

    attributes, classes, allowed_tokens = parse_schema(args.schema)

    if not attributes and not classes:
        print(f"WARNING: No attributes or classes found in {args.schema}", file=sys.stderr)

    header = generate_header(attributes, classes, allowed_tokens, os.path.basename(args.schema))

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    # Only write if content changed (avoid rebuilds)
    if os.path.isfile(args.output):
        with open(args.output, "r") as f:
            if f.read() == header:
                return 0

    with open(args.output, "w") as f:
        f.write(header)

    count = len(attributes) + len(classes) + len(allowed_tokens)
    print(f"Generated {args.output} ({count} tokens: {len(classes)} classes, {len(attributes)} attributes, {len(allowed_tokens)} allowed values)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
